### ISSUE TITLE
Support WebJars directly in Jersey

### ISSUE THREAD

**Issue by jessemillar** [spring-projects/spring-boot#11355] opened 2017-12-14 22:45 UTC
This is half question and half (potential) bug report. I've inquired about the problem in the [`webjars-locator`](https://github.com/webjars/webjars-locator/issues/105#issuecomment-351828785) project and was directed here.

I'm trying to get [`swagger-ui`](https://github.com/webjars/swagger-ui) working in a version agnostic manner inside of Spring Boot with Jersey and Tomcat. According to the [WebJars documentation](https://www.webjars.org/documentation#springboot), having a `pom.xml` similar to the following should allow me to access `swagger-ui` via http://localhost:8080/webjars/swagger-ui/ but it only works via http://localhost:8080/webjars/swagger-ui/3.6.1.
```
<dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jersey</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>swagger-ui</artifactId>
      <version>3.6.1</version>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>webjars-locator</artifactId>
      <version>0.32-1</version>
    </dependency>
</dependencies>
```
Is there anything special I'd need to do to get `webjars-locator` working in this situation? It works just fine in `spring-boot-starter-web` which leads me to believe this is potentially a bug.

**Comment by philwebb** [comment] 2017-12-15 07:52
Spring MVC support is provided via `org.springframework.web.servlet.resource.WebJarsResourceResolver` from the Spring Framework and Spring Boot gets it for free.

We currently don't have the same type of support for Jersey.

**Comment by marti1125** [comment] 2018-01-28 16:00
@jessemillar  @philwebb could I contribute with this?

**Comment by jessemillar** [comment] 2018-01-29 15:41
@marti1125 I can't contribute anytime soon. I'm certainly not a project maintainer, but the `ideal-for-contribution` label makes me think they'd be okay with a PR from you. :)

**Comment by philwebb** [comment] 2018-01-29 15:59
@marti1125 Yes please, what would be most welcome.

**Comment by Butorchin-Dmitri** [comment] 2018-02-12 12:16
I have tried this in Spring Boot 2.0.0.RC1 and swagger-ui 3.9.3 - can't reproduce the problem. Has it been solved?

**Comment by wilkinsona** [comment] 2018-02-12 13:26
@Butorchin-Dmitri Not that we're aware of; nothing's change in Boot to support this. Can you share your app that appears to work?

**Comment by jessemillar** [comment] 2018-02-12 15:43
@Butorchin-Dmitri Were you trying with Jersey instead of the default Spring Boot container? I can throw together a quick demo that shows the issue today.

**Comment by w4tson** [comment] 2018-02-14 07:10
I've managed to replicate some of the issue in a [git repo](https://github.com/w4tson/spring-boot-jersey/). Instructions to reproduce are in the README. 

I've done some analysis on this and would like to help fix.

As @philwebb mentioned the webjars functionality is getting implemented by `org.springframework.web.servlet.resource.WebJarsResourceResolver`. Unfortunately this is in the spring-mvc project and leverages the ResourceResolver mechanism which isn't available to spring-jersey users.

I've dreamt up a couple of options

1. Allow the servlet 3.0 convention to statically serve webjars
2. A Jersey controller with regex of /webjars/.* to serve content
3. A servlet/filter that does the same

By all accounts a servlet 3.0 should serve static files in the `META-INF/resources` directory. The webjars [documentation](https://www.webjars.org/documentation#servlet3) explains as such. I just can't get this to work. Tried adding in the Tomcat DefaultServlet and setting Jersey to be a Filter but no joy. 

Can someone steer me in the right direction?

**Comment by Butorchin-Dmitri** [comment] 2018-02-14 09:05
@w4tson If you run it with 2.0.0.RC1 the access with version works: http://localhost:8080/webjars/swagger-ui/3.6.1/index.html, although it doesn't work without it, as reported in the original post - I was confused somehow.
https://github.com/Butorchin-Dmitri/spring-boot-jersey

**Comment by w4tson** [comment] 2018-02-14 16:16
Well that's a start! That was the behaviour I was expecting according to the spec. Perhaps I can knock up a servlet filter that does a redirect using the webjars-locator

**Comment by w4tson** [comment] 2018-02-17 21:56
@Butorchin-Dmitri 2.0.0.RC1 did work initially but when you actually add in a JerseyConfig (as anyone will need to do) then the JerseyAutoConfig kicks in and the JerseyServlet is registered thus snaffling the request for webjars.

So the trick to getting this working again is to register Jersey as Filter (it defaults to a Servlet) and switch on "forwardOn404". That gets webjars working again.

To get the Jersey stuff in parity with spring-web I wrote a Filter to conditionally redirect requests using the WebJars locator.

This is in the [same repo](https://github.com/w4tson/spring-boot-jersey/), I haven't made a pull request because I want someone to say this is viable approach first.

Points of note:

1. This change would change the default registration of Jersey as a Filter: is this a problem?
2. Using Filter for redirecting http://localhost:8080/webjars/bootstrap/css/bootstrap.css to http://localhost:8080/webjars/bootstrap/3.1.0/css/bootstrap.css isn't quite the same behaviour as the spring-web way. This is a http redirect, is that a problem? Maybe it should internally do a servlet forward instead?

@philwebb do you have a steer?

**Comment by zappee** [comment] 2018-04-18 14:30
@w4tson I have tried to use your WebJarsFilter.java but it thrown an exception in my application:

java.lang.IllegalArgumentException: swagger-ui/index.html could not be found. Make sure you've added the corresponding WebJar and please check for typos.

**Comment by govi20** [comment] 2019-01-20 17:16
@philwebb is this issue still relevant and ideal for a contribution?

**Comment by bclozel** [comment] 2019-06-07 16:49
While this feature would be useful to Jersey users, I think we can't really address this properly in Spring Boot. Spring Framework supports WebJars in the context of the resource handling feature, supporting serving static resources, cache busting, HTTP cache headers, etc.

Spring Boot should auto-configure this feature, once it's supported officially by Jersey. Closing this issue for now, we should reopen it once it's available in Jersey.

**Closed by bclozel** 2019-06-07 16:49 UTC
Labels: status: declined, type: enhancement
