### ISSUE TITLE
spring.autoconfigure.exclude not evaluated as expected

### ISSUE THREAD

**Issue by luchob** [spring-projects/spring-boot#11218] opened 2017-11-30 12:33 UTC
Hello! 

In my application I want to exclude an auto configuration based on the value of an environment variable. If this variable has no value I provide a default. Here is the `appication.yaml`:

```
spring:
  autoconfigure:
    exclude: ${ABC:com.example.Myautoconfiguration}
```
[Reference](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-auto-configuration.html).

This won't work. The expression is not evaluated but instead it is processed as a string. Here is the output with `--debug` option.

```
=========================
AUTO-CONFIGURATION REPORT
=========================


Exclusions:
-----------

    ${ABC:com.example.Myautoconfiguration}
```
Of course my autoconfiguration is not excluded. If I provide `com.example.Myautoconfiguration` as a string it is excluded.

`Spring Boot 1.5.8.RELEASE`

Is this a bug?

**Comment by snicoll** [comment] 2017-11-30 12:59
Duplicate of #1672

**Closed by snicoll** 2017-11-30 12:59 UTC
Labels: status: waiting-for-triage
