### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ld-github** [spring-projects/spring-boot#10431] opened 2017-09-27 07:29 UTC
Spring Boot ::             (v2.0.0.M4)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

**Comment by wilkinsona** [comment] 2017-09-27 07:40
Sorry, but that's not enough information to diagnose the problem. Can you please provide a small sample that reproduces the exception?

**Comment by xllci** [comment] 2017-09-27 07:41
哈哈

**Comment by bclozel** [comment] 2017-09-27 07:44
Are you using Spring Cloud? This sounds a lot like #10320.

**Comment by xllci** [comment] 2017-09-27 07:46
yes，

**Comment by ld-github** [comment] 2017-09-27 07:46
my pom.xml:

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.0.M4</version>
        <relativePath />
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Finchley.M2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka-server</artifactId>
        </dependency>
    </dependencies>

Run application error: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

**Comment by ld-github** [comment] 2017-09-27 07:46
yes

**Comment by xllci** [comment] 2017-09-27 07:47
are you working at github?

**Comment by ld-github** [comment] 2017-09-27 07:48
And Spring Boot :: (v2.0.0.M4) + spring-boot-starter-actuator , The problem can also occur！

**Comment by bclozel** [comment] 2017-09-27 07:48
Then this is a duplicate of #10320.
There's nothing we can do here, please take a look at spring-cloud/spring-cloud-netflix#2278

**Comment by ld-github** [comment] 2017-09-27 07:49
Wait a minute. I submit it to github!

**Closed by bclozel** 2017-09-27 07:48 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by ld-github** [comment] 2017-09-27 07:56
I can only use spring-boot 2.0.0 with spring cloud?

**Comment by bclozel** [comment] 2017-09-27 08:37
You can use Spring Boot with or without Spring Cloud.
If you're using Spring Cloud + Spring Boot milestone versions, you should make sure those are meant to be compatible. They aren't in your case, see spring-cloud/spring-cloud-netflix#2278

**Comment by ld-github** [comment] 2017-09-27 09:58
I see, thank you very much!  @bclozel
