### ISSUE TITLE
HikariDataSource is not initialized with spring.datasource.data-username

### ISSUE THREAD

**Issue by rafasantos** [spring-projects/spring-boot#15299] opened 2018-11-27 01:49 UTC
* Spring boot version: 2.1.0.RELEASE
* Java version: openjdk version "1.8.0_171" (probably irrelevant to the problem)
* Starters: spring-boot-starter-data-jpa, spring-boot-starter-web, spring-boot-starter-test

See sample project attached which includes integration tests: download, extract and use `mvn verify`
[demo-hikari.zip](https://github.com/spring-projects/spring-boot/files/2617971/demo-hikari.zip)

I would expect that standard properties should be enough when creating a DataSource. Also supported by: 
https://github.com/spring-projects/spring-boot/issues/6907#issuecomment-247601162

With this configuration, username and password are not set (the default values take place)
```
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:h2:mem:test-default-level-properties
spring.datasource.data-username=myUsername
spring.datasource.data-password=myPassword
```
However, this configuration works fine
```
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:h2:mem:test-default-level-properties
spring.datasource.hikari.username=myUsername
spring.datasource.hikari.password=myPassword
```

Integration test sample:
```
@RunWith(SpringRunner.class)
@SpringBootTest(properties = {
	"spring.datasource.type=com.zaxxer.hikari.HikariDataSource",
	"spring.datasource.data-username=myUsernameFromDefault",
	"spring.datasource.data-password=myPasswordFromDefault",
	"spring.datasource.url=jdbc:h2:mem:test-default-level-properties"
})
public class DataSourceWithDefaultPropertiesIntegrationTest {

	@Autowired
	private DataSource dataSource;

	/**
     * Give: {@code spring.datasource.*} are provided
	 * And the DataSource type is {@code com.zaxxer.hikari.HikariDataSource}
	 * When: the application context starts
	 * Then: the DataSource bean should be initialized with the given {@code spring.datasource.*} properties
	 */
	@Test
	public void given_DataSourcePropertiesOnTheDefaultLevel_When_TheApplicationContextStarts_Then_PropertiesShouldBeInitialized() {
		assertTrue(dataSource instanceof HikariDataSource);
		HikariDataSource hikariDataSource = (HikariDataSource) dataSource;
		assertEquals("jdbc:h2:mem:test-default-level-properties", hikariDataSource.getJdbcUrl());
		assertEquals("myUsernameFromDefault", hikariDataSource.getUsername());
		assertEquals("myPasswordFromDefault", hikariDataSource.getPassword());
	}
}
```

**Comment by rafasantos** [comment] 2018-11-27 04:01
I was looking into this issue and trying to fix it but I did not progressed very far (first time looking at spring boot source code). However, I managed to write some tests in the source code which could be used to pin-point the problem.

```
// ./spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/jdbc/HikariDataSourceConfigurationTests.java
  /*
   * This test is working as expected
   */
  @Test
  public void hikariUsernameTakesPrecedenceOverStandardUsername() {
    this.contextRunner
        .withPropertyValues("spring.datasource.data-username=standardUsername",
            "spring.datasource.hikari.username=hikariUsername")
        .run((context) -> {
          HikariDataSource ds = context.getBean(HikariDataSource.class);
          assertThat(ds.getUsername()).isEqualTo("hikariUsername");
        });
  }

  /*
   * Assertion failure: expected:<"standardUsername"> but was:<"sa">
   */
  @Test
  public void standardUsernameIsUsedWhenHikariUsernameIsNotSet() {
    this.contextRunner
        .withPropertyValues("spring.datasource.data-username=standardUsername")
        .run((context) -> {
          HikariDataSource ds = context.getBean(HikariDataSource.class);
          assertThat(ds.getUsername()).isEqualTo("standardUsername");
        });
  }
```
Run it with:
```
mvn test -Dtest=HikariDataSourceConfigurationTests -pl spring-boot-project/spring-boot-autoconfigure
```

**Comment by snicoll** [comment] 2018-11-27 07:11
@rafasantos thanks for the sample as it really helps understanding what you're after. I don't know what you expect `data-username` to do but it won't affect the actual `DataSource` object. 

The documentation for `data-username` states:

> Username of the database to execute DML scripts (if different).

These settings are used if you need a different username/password for creating the schema (`schema-username` and password) or insert data (`data-username` and password) on startup. It looks like you expect that information to be used for the actual `DataSource` the application uses, which is wrong. 

That being clarified, I am going to close this issue. If there is something in the doc that convicted you of a different behaviour, please clarify and we can reopen if necessary.

**Closed by snicoll** 2018-11-27 07:11 UTC
Labels: status: waiting-for-triage

**Comment by rafasantos** [comment] 2018-11-28 03:59
@snicoll Thank you verify much for your help. Yes, it is clarified. I mixed the terms and usage of `spring.datasource.data-username` vs `spring.datasource.username`

**Comment by RobinRheem** [comment] 2019-01-28 11:47
Hello, I've experienced this issue on my CentOS 7 server. But the problem is, my macOS machine works! Even if I put in `spring.datasource.data-username` and put nothing in `spring.datasource.hikari.username=myUsername`, it still works! I don't know why it doesn't work on CentOS and works on macOS.

**Comment by snicoll** [comment] 2019-01-28 12:53
@RobinRheem this issue is closed and we don't use the issue tracker for questions. Please ask on StackOverflow.
