### ISSUE TITLE
SpringBootRepositoryRestMvcConfiguration kills JsonPrettyPrint

### ISSUE THREAD

**Issue by fivedogit** [spring-projects/spring-boot#2999] opened 2015-05-18 17:05 UTC
Once you switch from "extend WebMvcConfigurerAdapter" to "extend SpringBootRepositoryRestMvcConfiguration", pretty-printing of JSON is lost. Doesn't matter if it's done via class configs or application.properties... (both 

http.mappers.jsonPrettyPrint=true
and
spring.jackson.serialization.INDENT_OUTPUT=true

are ignored).

**Comment by wilkinsona** [comment] 2015-05-18 18:07
This is a duplicate of #2914. See [this comment](https://github.com/spring-projects/spring-boot/issues/2914#issuecomment-99103207) for a workaround.

**Closed by wilkinsona** 2015-05-18 18:07 UTC
