### ISSUE TITLE
spring-boot-configuration-processor artifact is being packaged in Spring Boot's fat jar

### ISSUE THREAD

**Issue by PeterWippermann** [spring-projects/spring-boot#15641] opened 2019-01-07 17:55 UTC
If you integrate `spring-boot-configuration-processor` as described [in the docs](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor), that artifact will end up as a lib in the jar, that's being repackaged by the `Spring Boot Maven Plugin`.

Currently integration in Maven is supposed to be done like this:
```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-configuration-processor</artifactId>
	<optional>true</optional>
</dependency>
```

I think there are two issues with this approach:

1. There is no clean solution in Maven to include a dependency only during compile time but not in the artifact. The [\<optional> feature](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) is not meant to be used like this. The community's general approach is to set `<scope>provided</scope>` - as e.g. [supposed by Lombok](https://projectlombok.org/setup/maven).
2. Still, the `spring-boot-configuration-processor.jar` (and its dependencies! - in case there would be any)  will end up in the fat jar built by the `Spring Boot Maven Plugin`.
Since both projects are part of Spring Boot, I'd expect a note in the Configuration Processor's docs [how to exclude it's artifact in the jar](https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/exclude-dependency.html).

**Comment by snicoll** [comment] 2019-01-07 19:01
Duplicate of #10539

**Closed by snicoll** 2019-01-07 19:01 UTC
Labels: status: waiting-for-triage
