### ISSUE TITLE
Loading application context from Spring Boot application fails for imports of recources with relative paths

### ISSUE THREAD

**Issue by kappmeier** [spring-projects/spring-boot#8523] opened 2017-03-07 12:18 UTC
When creating an application context from xml configuration located in a jar file, relative includes are not found when using standalone. The following construct fails when `<import resource="../other.xml" />` is present:

```
String configLocation = "jar:file:pathToSomeJar.jar!/some/config/in-jar.xml"
ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext();        
context.setConfigLocation(configLocation);
context.refresh();
```

The failure in the exception is for example: `java.io.FileNotFoundException: JAR entry some/config/../other.xml not found in pathToSomeJar.jar`

It works when started using maven or from IDE, the reason seems to be that `sun.net.www.protocol.jar.JarURLConnection.connect.JarURLConnection` supports this where  `org.springframework.boot.loader.jar.JarURLConnection.connect.JarURLConnection.java` does not.

The issue does not occur in Spring Boot 1.4.1. It happens with version 1.5.1 and 1.5.2.

I have created an example that should be self contained. The configuration that is loaded as ApplicationContext is stored within the fat jar, but the issue occurs with any jar on the file system as well.

https://github.com/kappmeier/spring-boot-bug-jar-load

After checkout the following works:
```
$ mvn package
$ java -jar target/jar-load-example-1.4.1.RELEASE.jar
 :: Load custom config with Spring Boot (v1.4.1.RELEASE) ::

Expected: a test value
a test value
Expected: another value
another value
Expected: custom value
custom value

```

When the version is switched to 1.5.1 it fails:
```
$ mvn package
$ java -jar target/jar-load-example-1.5.1.RELEASE.jar
 :: Load custom config with Spring Boot (v1.5.1.RELEASE) ::

Expected: a test value
a test value
Expected: another value
another value
Expected: custom value
2017-03-07 13:04:17.060 ERROR 25969 --- [           main] o.s.boot.SpringApplication               : Application startup failed
...
Caused by: java.io.FileNotFoundException: JAR entry config/custom/../default/some-config.xml not found in spring-boot-bug-jar-load/target/jar-load-example-1.5.1.RELEASE.jar!/BOOT-INF/classes/configuration.jar
        at org.springframework.boot.loader.jar.JarURLConnection.throwFileNotFound(JarURLConnection.java:185) ~[jar-load-example-1.5.1.RELEASE.jar:1.5.1.RELEASE]

```

The first two values are loaded without relative paths and work as expected. The third fails.

**Comment by wilkinsona** [comment] 2017-03-07 12:23
I believe this is a duplicate of #7581. See [this comment](https://github.com/spring-projects/spring-boot/issues/7581#issuecomment-265515992) for an explanation of the chanage.

Can you please try with a shaded jar (rather than a Spring Boot fat jar) and see if it fails then as well?

**Comment by kappmeier** [comment] 2017-03-07 13:27
I will try to use a shaded jar and post results.

However, the same issue occurs when loading a jar file from external, i.e. some file on the file system. In the comment you mention the JDK URL stream loader. Is this the one mentionad above? (`sun.net.www.protocol.jar.JarURLConnection.connect.JarURLConnection`)

I have tried some more cases and it also works when using Spring only (without Boot) in a classic application.

**Comment by wilkinsona** [comment] 2017-03-07 13:33
> I will try to use a shaded jar and post results.

Thank you

>  Is this the one mentionad above? (`sun.net.www.protocol.jar.JarURLConnection.connect.JarURLConnection`)

No, it's `sun.net.www.protocol.jar.Handler`.

**Comment by kappmeier** [comment] 2017-03-13 15:02
I tried adding the maven-shade-plugin as described [in the comment](https://github.com/spring-projects/spring-boot/issues/7581#issuecomment-265515992). However, I was not able to make packaging work, I get an error `Cannot find 'mainClass' in class org.apache.maven.plugins.shade.resource.AppendingTransformer`, similar to the one described in [this stackoverflow question](http://stackoverflow.com/questions/36301277/maven-shade-plugin-can-not-find-mainclass-exception). I don't know where the mentioned class AppendingTransormer comes from.

Moreover, loading also does not work when the target is a jar file residing on the hard drive outside a Spring Boot fat jar.

**Comment by philwebb** [comment] 2017-03-13 18:10
The `mainClass` attribute should be appled to the `org.apache.maven.plugins.shade.resource.ManifestResourceTransformer`, I'm not sure why it's complaining about `AppendingTransformer`.

Perhaps you can share your `pom.xml` file, or better still provide a complete sample application that shows the problem?

**Comment by wilkinsona** [comment] 2017-03-13 18:46
Here's a pom for the sample linked to above that builds a shaded jar:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.1.RELEASE</version>
    </parent>

    <artifactId>jar-load-example</artifactId>
    <name>Spring Boot Jar Load Example</name>
    <description>Example showing how loading resources from jar files fails in Spring Boot 1.5.1.</description>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
    <properties>
        <start-class>example.JarLoad</start-class>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

As expected, it fails, albeit even earlier:

```
java -jar target/jar-load-example-1.4.1.RELEASE.jar
 :: Load custom config with Spring Boot (v1.4.1.RELEASE) ::

Expected: a test value
2017-03-13 18:43:39.238 ERROR 97570 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:803) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at example.JarLoad.main(JarLoad.java:95) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [jar:file:/Users/awilkinson/dev/temp/spring-boot-bug-jar-load/target/jar-load-example-1.4.1.RELEASE.jar/configuration.jar!/config/default/some-config.xml]; nested exception is java.io.FileNotFoundException: /Users/awilkinson/dev/temp/spring-boot-bug-jar-load/target/jar-load-example-1.4.1.RELEASE.jar/configuration.jar (Not a directory)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:344) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:252) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:612) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:513) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at example.JarLoad.loadFrom(JarLoad.java:88) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at example.JarLoad.run(JarLoad.java:38) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) [jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	... 6 common frames omitted
Caused by: java.io.FileNotFoundException: /Users/awilkinson/dev/temp/spring-boot-bug-jar-load/target/jar-load-example-1.4.1.RELEASE.jar/configuration.jar (Not a directory)
	at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:103) ~[na:1.8.0_121]
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93) ~[na:1.8.0_121]
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69) ~[na:1.8.0_121]
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99) ~[na:1.8.0_121]
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122) ~[na:1.8.0_121]
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150) ~[na:1.8.0_121]
	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:169) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:330) ~[jar-load-example-1.4.1.RELEASE.jar:1.4.1.RELEASE]
	... 19 common frames omitted
```

That could be do to the way that the example is working with the URI, but it illustrates the brittleness of the approach.

**Comment by wilkinsona** [comment] 2017-03-13 20:34
I should also have mentioned that the sample above fails for me when run using mvn spring-boot:run because the URI gets mangled.

**Comment by kappmeier** [comment] 2017-03-20 10:10
Thank you for the help with configuring the maven-shade-plugin. And sorry for the brittleness of the example project, I wanted to make it self contained and simple to reproduce the error.

We simply import a Spring project as dependency in Maven. The project brings its own xml configuration and we use the `PathMatchingResourcePatternResolver` to find the correct URI for the location. It works quite well for us.

With shading it works now, the package `org.springframework.boot.loader` is not included any more in the fat jar and also loading from external jar files on the file system works perfectly. I should mention for others facing the same problem that `spring-boot-maven-plugin` conflicts with the maven shade plugin and must be removed.

Regarding the issue:
I know you mentioned in the other issue that this should be the correct behaviour, however I would argue against it. When a Spring application is simply wrapped into a boot application to make it a web service, then loading of its configuration should imho not be broken and require custom configuration. This seems to be the contrast of what I see with Boot and Spring where everything just fits well together and is totally simple for standard use cases. And I would consider using `include "../default/base-config.xml" a standard use case, but probably this is debatable.

**Comment by philwebb** [comment] 2017-03-20 15:33
@kappmeier Are you able to share the sample project now that you have configured the Maven shade plugin correctly?

**Comment by wilkinsona** [comment] 2017-03-20 15:35
> With shading it works now, the package org.springframework.boot.loader is not included any more in the fat jar and also loading from external jar files on the file system works perfectly

To build a bit on what @philwebb just said, if it works with shade but not with a Spring Boot fat jar then I would consider that to be a bug. A sample project that demonstrates it working with shade and failing with a fat jar would be very useful.

**Comment by spring-issuemaster** [comment] 2017-03-27 15:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-04-03 15:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-04-03 15:37 UTC
Labels: status: waiting-for-triage
