### ISSUE TITLE
h2 not run schema.sql when start

### ISSUE THREAD

**Issue by Dreampie** [spring-projects/spring-boot#7933] opened 2017-01-10 05:20 UTC
```yml
spring:
    profiles: dev
    datasource:
      schema: classpath:db/schema.sql
      url: jdbc:h2:~/h2/test;MODE=MySql
      driver-class-name: org.h2.Driver
      username: sa
      initialize: true
    h2:
      console:
        enabled: true
```

```sql
CREATE TABLE alc_city (
  id          INT PRIMARY KEY AUTO_INCREMENT,
  name        VARCHAR,
  state       VARCHAR,
  country     VARCHAR,
  delete_able INT,
  deleted_at  TIMESTAMP
);

INSERT INTO alc_city (name, state, country, delete_able, deleted_at)
VALUES ('San Francisco', 'CA', 'US', 1, '2016-10-10 10:11:20');
```

![image](https://cloud.githubusercontent.com/assets/3667080/21794683/81c723c4-d737-11e6-8486-72ff48ac0c27.png)

**Comment by wilkinsona** [comment] 2017-01-10 10:45
@Dreampie As we've said to you before, a screenshot tells us almost nothing. It's not even clear that you had a schema.sql file or that it was in the right place. If you'd like us to investigate please provide a minimal sample that reproduces the problem

**Comment by spring-issuemaster** [comment] 2017-01-17 10:48
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-01-24 10:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-01-24 10:49 UTC
Labels: status: waiting-for-triage
