### ISSUE TITLE
update from 2.2.0.M4 to 2.2.0.M5 breaks JPA

### ISSUE THREAD

**Issue by Ed42** [spring-projects/spring-boot#18121] opened 2019-09-04 06:53 UTC
simple JPA app using `xxx extends JpaRepository<x, y>` works just fine with 2.2.0.M4 but fails like this with 2.2.0.M5:

```
2019-09-04 16:47:27.364  INFO 4282 --- [           main] com.wombat.jardb_jpa.Application         : Started Application in 12.819 seconds (JVM running for 13.264)
2019-09-04 16:47:33.466  WARN 4282 --- [ool-1-worker-18] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23502
2019-09-04 16:47:33.467  WARN 4282 --- [ool-1-worker-26] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23502
2019-09-04 16:47:33.469  WARN 4282 --- [ool-1-worker-19] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23502
2019-09-04 16:47:33.474 ERROR 4282 --- [ool-1-worker-19] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: null value in column "id" violates not-null constraint
  Detail: Failing row contains (null, commons-lang-2.1.jar, /home/ed/.m2/repository/commons-lang/commons-lang/2.1).
```

The dependency version change in the POM was the only change.

**Comment by snicoll** [comment] 2019-09-04 07:03
@Ed42 it's not obvious why you think this is a bug in Spring Boot. If you want us to investigate, please share a minimal sample that reproduces the problem with M5 and does not with M4 (something we can clone or unzip and run ourselves).

**Comment by Ed42** [comment] 2019-09-05 06:28
I think it's a bug in somewhere in the combination of dependencies. Will try and find a minimal runnable example.

**Comment by Ed42** [comment] 2019-09-05 07:39
[eg.zip](https://github.com/spring-projects/spring-boot/files/3578021/eg.zip)

Please see attached. This is an attempt at the beginnings of a spring boot tutorial. Instructions enclosed

**Comment by snicoll** [comment] 2019-09-05 08:42
@Ed42 thank you for the sample but that's not really a minimal sample. It shouldn't require a persistent database either unless the issue is Postgres specific (and therefore a sign this isn't a Spring Boot issue anyway).

I have tried with H2. The `curl` command in your readme yield this for me:

```
10:39:55.493 [qtp289281017-28] WARN  org.eclipse.jetty.server.HttpChannel - /api/v1/load
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: com/wombat/jardb_jpa/service/LoaderServiceImpl$Visitor
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: com/wombat/jardb_jpa/service/LoaderServiceImpl$Visitor
	at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:254)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:236)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:436)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	... 44 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/wombat/jardb_jpa/service/LoaderServiceImpl$Visitor
	at com.wombat.jardb_jpa.service.LoaderServiceImpl$LoadInfo.lambda$load$5(LoaderServiceImpl.java:96)
	at com.wombat.jardb_jpa.util.Timed.timed(Timed.java:29)
	at com.wombat.jardb_jpa.util.Timed.timed(Timed.java:14)
	at com.wombat.jardb_jpa.service.LoaderServiceImpl$LoadInfo.load(LoaderServiceImpl.java:94)
	at com.wombat.jardb_jpa.service.LoaderServiceImpl$LoadInfo.access$000(LoaderServiceImpl.java:66)
	at com.wombat.jardb_jpa.service.LoaderServiceImpl.load(LoaderServiceImpl.java:50)
	at com.wombat.jardb_jpa.resource.LoaderResource.load(LoaderResource.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	... 53 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.wombat.jardb_jpa.service.LoaderServiceImpl$Visitor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 73 common frames omitted
```

Can you please rework your sample to eliminate as much details as possible. Removing the cross-compilation between Groovy and Java would help as well as it shouldn't be required to reproduce the issue.

**Comment by snicoll** [comment] 2019-09-05 11:29
@Ed42 I've managed to reproduce the issue by running the app outside of the IDE (missed that from the README, sorry).

However, this project fails with both M4 and M5. If you want us to investigate, please simplify your sample and make sure it works with M4 and breaks with M5.

**Comment by Ed42** [comment] 2019-09-06 04:13
This project works with M4 and fails with M5, that is why I raised the ticket.

**Comment by wilkinsona** [comment] 2019-09-06 06:22
Thanks for the sample. I've have reproduced the difference in behaviour between M4 and M5.

It being necessary to drop the database created by M4 for the problem to occur with M5 suggests that the problem is caused during database initialization. You are using Liquibase and M5 upgraded to Liquibase 3.7.0. If I downgrade Liquibase to 3.6.3 (the version used in M4), the problem does not occur any more with M5. In short this appears to be due to a bug or change in behaviour in Liquibase 3.7.0 so I'm going to close this issue for now. If it turns out that the problem is caused by how we have auto-configured Liquibase we can re-open it and take another look.

**Closed by wilkinsona** 2019-09-06 06:22 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by Ed42** [comment] 2019-09-06 06:31
If the problem magically disappears in M6, then all good :-)

**Comment by wilkinsona** [comment] 2019-09-06 07:05
If you are expecting it to magically disappear I think you may be disappointed. As far as I can tell, this is a bug in Liquibase. There's also a possibility that there's a backwards-incompatible change in Liquibase 3.7 that requires an update to your database change log. If you think it's the former, Liquibase uses [JIRA](https://liquibase.jira.com) for issue tracking and I would recommend checking for an existing issue and, if one does not exist, opening a new one that provides as much detail as possible. I imagine that information about the tables that are created when the database is initialised would be useful to them.

**Comment by wilkinsona** [comment] 2019-09-06 09:31
The difference in behaviour is due to a change in the type of the id column. With Liquibase 3.6.3 the columns are `SERIAL`. For example:

```
CREATE TABLE public.archive (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(512) NOT NULL, CONSTRAINT ARCHIVE_PKEY PRIMARY KEY (id))
```

With 3.7.0 they are `INTEGER`. For example:

```
CREATE TABLE public.archive (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(512) NOT NULL, CONSTRAINT ARCHIVE_PKEY PRIMARY KEY (id))
```

It works with 3.7.0 if you configure the `id` columns to be ` type="integer" autoIncrement="true"` rather than `type="serial"`, although the resulting table definition isn't exactly the same. For example:

```
CREATE TABLE public.archive (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(512) NOT NULL, CONSTRAINT ARCHIVE_PKEY PRIMARY KEY (id))
```

This appears to be a reoccurrence of https://liquibase.jira.com/browse/CORE-1559.

**Comment by Ed42** [comment] 2019-09-06 22:56
Great, thanks for the analysis. I don't expect you guys to fix liquibase problems, but I was alluding to the fact that Spring Boot has traditionally supplied _curated_ dependencies that are known to work together. It is a potential issue if it breaks, but if the workaround is to revert the liquibase version then we can live with that.
