### ISSUE TITLE
Setting the log level from application.properties in docker environment variables does not work properly.

### ISSUE THREAD

**Issue by huleana** [spring-projects/spring-boot#15874] opened 2019-02-08 09:00 UTC
In application.properties:
logging.level.root=INFO

In docker environment variable:

 - docker run -e LOGGING_LEVEL_ROOT=INFO <image>

Workaround: Change the environment variable to be the same as in application.properties:

 - docker run -e logging.level.root=INFO <image>

Possible root cause:
logging.level is hardcoded in base library:

```
protected void setLogLevels(LoggingSystem system, Environment environment) {
		Map<String, Object> levels = new RelaxedPropertyResolver(environment)
				.getSubProperties("logging.level.");
}
```

I believe this should follow the pattern defined for application.properties properties as snake_case.

**Comment by wilkinsona** [comment] 2019-02-08 09:31
> I believe this should follow the pattern defined for application.properties properties as snake_case

That's not necessary. As properties are consumed from the various sources (environment variables, system properties, YAML files, etc) they are transformed into the [canonical form](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding#relaxed-binding). There is no need for the form of a property in an environment variable to match the form in an application.properties file.

Can you please take a step back an explain the problem that you are experiencing? From what you've shared thus far, I would expect the root log level to be configured to `INFO` (which is the default anyway). What is it that you believe does not work properly?

To move things forward as efficiently as possible, can you please provide a minimal and complete example that we can build and run to reproduce the problem. That should be in the form of a zip attached to this issue or a Git repository that we can clone.

**Comment by spring-issuemaster** [comment] 2019-02-15 09:35
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by cldsnchz** [comment] 2019-02-19 22:32
Sorry if this comment only generates noise instead of helping, but probably is related to the original post.

One thing that happened to me in the past was that for example this configuration doesn't work:
`LOGGING_LEVEL_ORG_ACME=DEBUG`
but this one does:
`LOGGING_LEVEL_org.acme=DEBUG`

Which somehow make sense but it wasn't that clear in the beginning, at least for me. 
I tried `_ORG_ACME` first and then, as it didn't work tried `_org.acme`

**Comment by spring-issuemaster** [comment] 2019-03-06 00:39
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-03-06 00:39 UTC
Labels: status: feedback-reminder, status: waiting-for-triage
