### ISSUE TITLE
Regression of Caffeine test when upgrading from 2.1.9 to 2.2.0

### ISSUE THREAD

**Issue by aznan2** [spring-projects/spring-boot#18677] opened 2019-10-21 14:54 UTC
I have a Caffeine cache that expires items after a certain amount of time. I have a unit test that checks if this is really the case.

The test works on Spring Boot 2.1.9 but fails on 2.2.0. It seems the item is cached, but does not expire.

Spring Boot 2.2.0 has upgraded Caffeine from 2.6.2 to 2.8.0. I tried running Spring Boot 2.1.9 with Caffeine 2.8.0, but the test still passed, so it's probably not Caffeine's fault.

I have not yet checked if it's just the test that is affected, or if items are no longer expired when running the application for real.

```java
public class Service {
  private Repository repository;

  public Service(Repository repository) {
    this.repository = repository;
  }

  @Cacheable("theCache")
  public Object getThingFromService(String id) {
    return repository.getThingFromRepo(id);
  }
}
```
```java
public interface Repository {
  Object getThingFromRepo(String id);
}
```
```java
@TestConfiguration
@EnableCaching
public class CacheTestConfig {
  @MockBean
  public static Repository mockRepo;

  @Bean
  public Service service() {
    return new Service(mockRepo);
  }

  @Bean
  public CacheManager cacheManager() {
    SimpleCacheManager cacheManager = new SimpleCacheManager();
    cacheManager.setCaches(List.of(theCache()));
    return cacheManager;
  }

  @Bean
  public CaffeineCache theCache() {
    return new CaffeineCache("theCache", Caffeine.newBuilder()
        .maximumSize(1000)
        .expireAfterWrite(5, TimeUnit.MINUTES)
        .ticker(ticker())
        .build(), false);
  }

  @Bean
  public Ticker ticker() {
    return fakeTicker()::read;
  }

  @Bean
  public FakeTicker fakeTicker() {
    return new FakeTicker(); // FakeTicker from guava-testlib
  }
}
```
```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {CacheTestConfig.class, CacheAutoConfiguration.class})
public class CacheTest {

  @Autowired
  private Service service;

  @Autowired
  private FakeTicker fakeTicker;

  @Test
  public void cacheHitAndExpire() {
    String id = "someId";
    when(mockRepo.getThingFromRepo(any())).thenAnswer(invocation -> new Object());

    // Start at 0 minutes, ask service - should return new object from repo
    Object response1 = service.getThingFromService(id);
    verify(mockRepo).getThingFromRepo(eq(id));

    // After 3 minutes from start, ask service - should use cached object
    fakeTicker.advance(3, TimeUnit.MINUTES);
    Object response2 = service.getThingFromService(id);
    assertThat(response2, sameInstance(response1));
    verifyNoMoreInteractions(mockRepo);

    // After 7 minutes from start, ask service - should return new object
    fakeTicker.advance(4, TimeUnit.MINUTES);
    Object response3 = service.getThingFromService(id);
    assertThat(response3, not(sameInstance(response1))); // <- This fails!
    verify(mockRepo, times(2)).getThingFromRepo(eq(id));
  }
}
```

**Comment by wilkinsona** [comment] 2019-10-21 14:58
This looks like a duplicate of https://github.com/spring-projects/spring-boot/issues/18653. Can you please try replacing `@TestConfiguration` with `@Configuration` and `@TestComponent`?

**Comment by aznan2** [comment] 2019-10-21 15:02
@wilkinsona Indeed, that solved the problem. Thank you!

**Closed** 2019-10-21 15:03 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
