### ISSUE TITLE
Add max capacity configuration for embedded Jetty QueuedThreadPool.

### ISSUE THREAD

**Issue by bono007** [spring-projects/spring-boot#19493] opened 2019-12-31 03:22 UTC
We are replacing our legacy in-house Java application framework with Spring Boot. The last missing feature parity is the ability to constrain Jetty's backing queue. 

Issue #8662 was the same issue from a couple years back. It landed on [this comment](https://github.com/spring-projects/spring-boot/issues/8662#issuecomment-287706410) from @wilkonsa

>  A pull request that adds this configuration option for Jetty, Tomcat, and Undertow would be welcome.

However, the issue ended up closing due to inactivity. I intend to submit that PR.

**Comment by snicoll** [comment] 2019-12-31 08:45
@bono007 thanks but there is no need to create an issue and a PR as one supersedes the other. 

Closing in favour of PR #19494

**Closed by snicoll** 2019-12-31 08:45 UTC
Labels: status: waiting-for-triage

**Comment by bono007** [comment] 2019-12-31 14:01
Got it. 
I was curious about that @snicoll . In the case where I go straight to a PR I just skip the "Closes gh-abc" text in the commit message I am assuming,

**Comment by snicoll** [comment] 2019-12-31 14:04
The commit message of a PR we process is almost always rewritten. We rewrite the `closes` if pressent as the issue is closed (like here) and we use the PR issue id as the reference in the commit message.
