### ISSUE TITLE
@ServerEndpoint url is being caught by dispacher Servlet even if the url mapping of dispacher servlet is different

### ISSUE THREAD

**Issue by ManojKrT** [spring-projects/spring-boot#5643] opened 2016-04-09 11:43 UTC
Spring Boot verrsion:1.3.3
created endpoint using `@ServerEndpoint`

```java
@ServerEndpoint(value = "/echo", configurator = SpringConfigurator.class)
```

DispatcherServlet 's url mapping is "/v1/*"

When try to connect server endpoint using client , getting below error.Running it on Embedded tomcat with springBoot

```
o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/demo/echo] in DispatcherServlet with name 'dispatcherServlet'
```

**Comment by wilkinsona** [comment] 2016-04-11 14:38
@ManojKrT Unfortunately, it's very difficult to tell what's going on from the information that you have provided. Can you please provide a small sample that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2016-04-18 14:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-04-25 14:39
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-04-25 14:39 UTC
