### ISSUE TITLE
Add ability to exclude environment variables when initializing AbstractEnvironment

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#6773] opened 2016-08-28 16:28 UTC
In some environments, common environment variables may be set that may effect application binding in undesirable ways. A common example is the [MAIL](https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#MAIL) environment variable in many linux systems. If this is set, it will likely cause a binding exceptions in a `@ConfigurationProperties` class that uses the `mail` namespace. To avoid such scenarios, it would be desirable to add a "black list" of environmental variables to ignore.

**Comment by btiernay** [comment] 2016-08-28 17:16
Seems to be related to #3427

**Comment by philwebb** [comment] 2016-08-28 17:52
I think this is a duplicate of #3427. It's been on the list for a little while but it might be something we can't fix properly until Spring Boot 2.0.

**Closed by philwebb** 2016-08-28 17:52 UTC
Labels: waiting-for-triage
