### ISSUE TITLE
 javax.validation and hibernate validator dependencies missing in Spring Boot 2.3.0

### ISSUE THREAD

**Issue by ajkr195** [spring-projects/spring-boot#21512] opened 2020-05-20 04:04 UTC
I tried to upgrade my Spring Boot 2.2.6 project to 2.3.0. The build and start up failed complaining about javax.validation apis missing. On top of it Hibernate validators too I had to add manually. Why it has been done or what are the advantages of doing so?

**Comment by gingermanjh** [comment] 2020-05-20 05:05
@ajkr195 
[This](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters) will help.

**Comment by bclozel** [comment] 2020-05-20 05:53
Duplicate of #21465.

**Closed by bclozel** 2020-05-20 05:53 UTC
Labels: status: waiting-for-triage
