### ISSUE TITLE
NullPointerException in FlywayEndpoint with schema baseline

### ISSUE THREAD

**Issue by gbehrmann** [spring-projects/spring-boot#14009] opened 2018-08-07 10:54 UTC
Spring Boot 2.0.4

In case a Flyway managed schema has a baseline, migrations prior to the baseline are not considered as applied by Flyway. As a result `org.flyway.core.api.MigrationInfo#getInstalledOn` returns `null`. This triggers a `NullPointerException` in the `org.springframework.boot.actuate.flyway.FlywayEndpoint$FlywayMigration` constructor when the installation time is to be converted to an `Instant`:
```
		private FlywayMigration(MigrationInfo info) {
			this.type = info.getType();
			this.checksum = info.getChecksum();
			this.version = nullSafeToString(info.getVersion());
			this.description = info.getDescription();
			this.script = info.getScript();
			this.state = info.getState();
			this.installedBy = info.getInstalledBy();
			this.installedOn = Instant.ofEpochMilli(info.getInstalledOn().getTime());
			this.installedRank = info.getInstalledRank();
			this.executionTime = info.getExecutionTime();
		}
```

<details>
<summary>Stack Trace</summary>
<pre>
Caused by: java.lang.NullPointerException: null
        at org.springframework.boot.actuate.flyway.FlywayEndpoint$FlywayMigration.<init>(FlywayEndpoint.java:167)
        at org.springframework.boot.actuate.flyway.FlywayEndpoint$FlywayMigration.<init>(FlywayEndpoint.java:137)
        at org.springframework.boot.actuate.flyway.FlywayEndpoint$FlywayDescriptor.lambda$new$0(FlywayEndpoint.java:120)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.springframework.boot.actuate.flyway.FlywayEndpoint$FlywayDescriptor.<init>(FlywayEndpoint.java:121)
        at org.springframework.boot.actuate.flyway.FlywayEndpoint$FlywayDescriptor.<init>(FlywayEndpoint.java:115)
        at org.springframework.boot.actuate.flyway.FlywayEndpoint.lambda$flywayBeans$0(FlywayEndpoint.java:59)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.springframework.boot.actuate.flyway.FlywayEndpoint.flywayBeans(FlywayEndpoint.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223)
        at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76)
        at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:61)
        at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:243)
        at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:299)
        at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        ... 92 common frames omitted
</pre>
</details>

**Comment by eddumelendez** [comment] 2018-08-08 18:54
I could reproduce the issue and found something interesting

My steps were the following:

1. Initialize a database with a initial table
2. Perform `flyway` baseline version 1
3. Create a `spring boot` project with 3 scripts: `V1__init.sql`, `V2__init.sql`, `V3__init.sql`. Also, the following properties were added `spring.flyway.baseline-version=2`, `spring.flyway.baseline-on-migrate=true`
4. Access to `flyway` endpoint and the failure was expected for the reason explined by @gbehrmann

As you can see in the steps I followed, baseline version 1 was created and also a sql file `V1__init.sql` was added for migration. Flyway will read all sql scripts (including `V1__init.sql`) and it will try to perform all sql scripts and get the `installedOn` for each of them. But, since `spring.flyway.baseline-version=2` was set, `V1__init.sql` will be ignored or will not be inserted into the table which will not retrieve the `installedOn` field.

Just fixed renaming the scripts to `V3__init.sql`, `V4__init.sql`, `V5__init.sql`

One suggestion for `spring-boot` side would be:

1. Add filter with `installedOn` different to `null` in `FlywayEndpoint`

```
private FlywayDescriptor(MigrationInfo[] migrations) {
    this.migrations = Stream.of(migrations).map(FlywayMigration::new)
		.collect(Collectors.toList());
}
```

WDYT?

**Comment by wilkinsona** [comment] 2018-08-09 08:51
@eddumelendez Thanks for the suggestion. I think it's useful for the endpoint to show migrations that Flyway was aware of but chose not to run. If we filter out migrations with a `null` `installedOn` we'll lose that information.

**Comment by wilkinsona** [comment] 2018-08-09 08:52
Closing in favour of PR #14019.

**Closed by wilkinsona** 2018-08-09 08:52 UTC
Labels: type: bug
