### ISSUE TITLE
spring-boot-test / spock-spring  / groovy logging annotation problem

### ISSUE THREAD

**Issue by woglinde** [spring-projects/spring-boot#22716] opened 2020-08-04 08:25 UTC
Hi,

when using spring-boot 2.3.2.RELEASE with spock-spring:1.3-groovy-2.5, using the  @Slf4j annotation and running with the gradle wraper  from the commandline the following error occurs:

```
Caused by: groovy.lang.MissingPropertyException: No such property: log for class: ....
    Possible solutions: port
```

**Comment by wilkinsona** [comment] 2020-08-04 08:32
This looks like a duplicate of [GROOVY-9650](https://issues.apache.org/jira/browse/GROOVY-9650) to me.

**Closed by wilkinsona** 2020-08-04 08:32 UTC
Labels: status: waiting-for-triage
