### ISSUE TITLE
Upgrade to Prometheus Pushgateway 0.7.0

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#18419] opened 2019-09-29 10:19 UTC

**Comment by snicoll** [comment] 2019-09-29 10:36
`PrometheusMetricsExportAutoConfigurationTests` is failing as the `gatewayBaseURL` has changed so need a proper investigation.

**Comment by dreis2211** [comment] 2019-09-29 11:48
Seems to be caused by https://github.com/prometheus/client_java/pull/491/files.

**Comment by wilkinsona** [comment] 2019-10-02 10:23
Thank you, @dreis2211.

Rather than always appending `metrics/job/` to the provided base URL, only `metrics/` is appended up front. The, when making the request, `job/` or `job@base64/` is appended followed by the encoded job (URL-encoding for the former and Base64-encoding for the latter). We should update the tests to remove `job/` from the expected URL.

**Comment by wilkinsona** [comment] 2019-10-02 10:28
Closed by dab69cfbd23314001bdd62679d1ff114b230c194.

**Closed by wilkinsona** 2019-10-02 10:28 UTC
Labels: type: dependency-upgrade
