### ISSUE TITLE
Exclude additional-config-metadata.json from jars

### ISSUE THREAD

**Issue by chicobento** [spring-projects/spring-boot#28399] opened 2021-10-20 18:32 UTC
The **additional-spring-configuration-metadata.json** file is landing in generated JARs: refer to spring-boot-autoconfigure.jar as an example.

I assume this is unnecessary as the contents are already merged on **spring-configuration-metadata.json** produced by spring-boot-configuration-processor, and STS/plugins will not read it when the source is a JAR file.

I started a PR on this, but as per @wilkinsona comments, ideally it should support both maven, gradle and people who are not deriving from spring-boot-starter-parent.

See #28398

**Comment by snicoll** [comment] 2021-10-21 05:54
Thanks for the report and the PR @chicobento. We are already tracking an issue for this.

Duplicate of #27430

**Closed by snicoll** 2021-10-21 05:54 UTC
Labels: status: waiting-for-triage
