### ISSUE TITLE
Hibernate's @JoinFormula in a @OneToMany fails only in Spring Boot

### ISSUE THREAD

**Issue by CarlomaCampus** [spring-projects/spring-boot#18533] opened 2019-10-08 10:36 UTC
So, there's a bug that, as far as I investigated, appears in Hibernate only when used with Spring Boot.

The problem appears when mapping the childs into a @OneToMany property of a entity using a custom join with the @JoinFormula annotation, but it throws this exception:

```
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.MappingException: Could not instantiate collection persister org.hibernate.persister.collection.OneToManyPersister
    [...]
    Caused by: java.lang.ClassCastException: org.hibernate.mapping.Formula cannot be cast to org.hibernate.mapping.Column
```

So theoretically, this can be made the [other way around](https://vladmihalcea.com/how-to-customize-an-entity-association-join-on-clause-with-hibernate-joinformula/), but when done from Spring Boot, [keeps happening exactly the same exception](https://discourse.hibernate.org/t/how-to-use-the-hibernate-joinformula-annotation-with-a-onetomany-jpa-association/1461/3).

All conclusions lead to the [same conclusion](https://forum.hibernate.org/viewtopic.php?f=1&t=1044758&view=next) (also Vlad Mihalcea says so), that this is a behaviour happening from the integration between Spring Boot and Hibernate. I have no clue on which side the problem is, but It may be fixed.

Thank you.

Some more interesting links:

- [Same issue closed two years ago delegating to StackOverflow.](https://github.com/spring-projects/spring-boot/issues/10149)

- [My question in StackOverflow with some examples and other researchs.](https://stackoverflow.com/questions/58231576/how-to-use-hibernates-joinformula-annotation-to-retrieve-a-list-of-childs)

**Comment by wilkinsona** [comment] 2019-10-08 12:16
This appears to be a bug in Hibernate as it is possible to reproduce the problem without any involvement from Spring. Here's a minimal bootstrapping of Hibernate that does so:

```
package example;

import java.net.URL;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Properties;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SharedCacheMode;
import javax.persistence.Table;
import javax.persistence.ValidationMode;
import javax.persistence.spi.ClassTransformer;
import javax.persistence.spi.PersistenceUnitInfo;
import javax.persistence.spi.PersistenceUnitTransactionType;
import javax.sql.DataSource;

import org.hibernate.annotations.JoinFormula;
import org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl;
import org.hibernate.jpa.boot.internal.PersistenceUnitInfoDescriptor;

public class FormulaToColumnClassCastApplication {

	public static void main(String[] args) {
		PersistenceUnitInfo info = new PersistenceUnitInfo() {

			@Override
			public String getPersistenceUnitName() {
				return "test";
			}

			@Override
			public String getPersistenceProviderClassName() {
				return null;
			}

			@Override
			public PersistenceUnitTransactionType getTransactionType() {
				return null;
			}

			@Override
			public DataSource getJtaDataSource() {
				return null;
			}

			@Override
			public DataSource getNonJtaDataSource() {
				return null;
			}

			@Override
			public List<String> getMappingFileNames() {
				return null;
			}

			@Override
			public List<URL> getJarFileUrls() {
				return null;
			}

			@Override
			public URL getPersistenceUnitRootUrl() {
				return null;
			}

			@Override
			public List<String> getManagedClassNames() {
				return Arrays.asList(Parent.class.getName(), Child.class.getName());
			}

			@Override
			public boolean excludeUnlistedClasses() {
				return false;
			}

			@Override
			public SharedCacheMode getSharedCacheMode() {
				return null;
			}

			@Override
			public ValidationMode getValidationMode() {
				return null;
			}

			@Override
			public Properties getProperties() {
				return new Properties();
			}

			@Override
			public String getPersistenceXMLSchemaVersion() {
				return null;
			}

			@Override
			public ClassLoader getClassLoader() {
				return null;
			}

			@Override
			public void addTransformer(ClassTransformer transformer) {

			}

			@Override
			public ClassLoader getNewTempClassLoader() {
				return null;
			}

		};
		new EntityManagerFactoryBuilderImpl(new PersistenceUnitInfoDescriptor(info),
				Collections.singletonMap("hibernate.dialect", "org.hibernate.dialect.H2Dialect")).build();
	}

}

@Entity
@Table(name = "child")
class Child {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@ManyToOne()
	private Parent parent;

}

@Entity
@Table(name = "parent")
class Parent {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@OneToMany(mappedBy = "parent")
	@JoinFormula(value = "(SELECT * FROM child)")
	private Set<Child> childs;

}
```

Running this with Hibernate 5.3.12.Final results in the same `ClassCastException`:

```
Exception in thread "main" javax.persistence.PersistenceException: [PersistenceUnit: test] Unable to build Hibernate SessionFactory
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1016)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:942)
	at com.example.demo.FormulaToColumnClassCastApplication.main(FormulaToColumnClassCastApplication.java:120)
Caused by: org.hibernate.MappingException: Could not instantiate collection persister org.hibernate.persister.collection.OneToManyPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.createCollectionPersister(PersisterFactoryImpl.java:167)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createCollectionPersister(PersisterFactoryImpl.java:140)
	at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:198)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:295)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:939)
	... 1 more
Caused by: java.lang.ClassCastException: org.hibernate.mapping.Formula cannot be cast to org.hibernate.mapping.Column
	at org.hibernate.persister.collection.AbstractCollectionPersister.<init>(AbstractCollectionPersister.java:307)
	at org.hibernate.persister.collection.OneToManyPersister.<init>(OneToManyPersister.java:69)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createCollectionPersister(PersisterFactoryImpl.java:152)
	... 6 more
```

Can you please raise this with the Hibernate team? In the meantime, in the absence of any Spring Boot code being involved when recreating the problem, I'm going to close this issue. If it turns out that changes to Hibernate's bootstrapping are needed to prevent it from failing with a `ClassCastException`, we can re-open this issue and take another look.

**Closed by wilkinsona** 2019-10-08 12:16 UTC
Labels: status: waiting-for-triage

**Comment by CarlomaCampus** [comment] 2019-10-08 12:42
I'm going to make a post on Hibernate's issue tracker explaing this, but please, @wilkinsona, can you tell me if you tried [this](https://discourse.hibernate.org/t/how-to-use-the-hibernate-joinformula-annotation-with-a-onetomany-jpa-association/1461/2?u=carlos_lopez)?

It seems that it is what it solves the problem in Hibernate itself. It would be very revealing to reproduce this behaviour in the same scenary in which they say it only fails with Spting Boot.

**Comment by wilkinsona** [comment] 2019-10-08 13:30
I hadn't, but I just have and it fails with a similar exception:

```
Exception in thread "main" java.lang.ClassCastException: org.hibernate.mapping.Formula cannot be cast to org.hibernate.mapping.Column
	at org.hibernate.cfg.annotations.TableBinder.bindFk(TableBinder.java:573)
	at org.hibernate.cfg.annotations.CollectionBinder.bindCollectionSecondPass(CollectionBinder.java:1709)
	at org.hibernate.cfg.annotations.CollectionBinder.bindOneToManySecondPass(CollectionBinder.java:940)
	at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:856)
	at org.hibernate.cfg.annotations.CollectionBinder$1.secondPass(CollectionBinder.java:795)
	at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:53)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1684)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1652)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:286)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:900)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:931)
	at example.FormulaToColumnClassCastApplication.main(FormulaToColumnClassCastApplication.java:120)
```

Unfortunately, without some evidence that the problem's caused by Spring Boot (which seems unlikely given that it can be reproduced without any Spring code at all), I cannot justify spending any more time on this. Please do open a Hibernate issue and link to it from here. That will allow us to follow the problem and make changes here if it turns out that they are necessary after all.

**Comment by CarlomaCampus** [comment] 2019-10-08 13:54
Yes, I'm getting the same exception.
Thank you very much, this spotlights the problem into Hibernate's Team.
Unfortunately, I found [this](https://hibernate.atlassian.net/browse/HHH-12997) issue which is having no  attention for a year. I hope your test unit helps clarifying this problem.

(I'll update with the new track)
