### ISSUE TITLE
Spring Data JPA Auditing stopped working after upgrade to 1.4.1

### ISSUE THREAD

**Issue by mihn** [spring-projects/spring-boot#7181] opened 2016-10-18 13:08 UTC
Hi,
After updating Spring Boot in my application  to 1.4.1 from 1.4.0 my Spring Data JPA auditing stopped working (doesnt fill the fields with values, even handler isnt executed):
Code sample here: https://github.com/mihn/spring-data-jpa-auditing-fail (fails on 1.4.1, works fine on 1.4.0)

**Comment by mihn** [comment] 2016-10-18 13:09
Made [ticket](https://jira.spring.io/browse/DATAJPA-982) also with Data JPA team

**Comment by olivergierke** [comment] 2016-10-18 13:15
Looks like a duplicate of #6983.

**Comment by mihn** [comment] 2016-10-18 13:16
oh great. and i was looking for auditing error, not specificcs of orm.xml not loading. Thanks, @olivergierke

**Closed** 2016-10-18 14:39 UTC
Labels: duplicate
