### ISSUE TITLE
Problem with tomcatEmbeddedServletContainerFactory, HibernateValidator and EntityScan

### ISSUE THREAD

**Issue by svenhornberg** [spring-projects/spring-boot#6712] opened 2016-08-22 08:13 UTC
We have a webservice and noticed 2 things after upgrading to 1.4.0.RELEASE. It seems that EntityScan works different in 1.4.0.M2 and 1.4.0.RELEASE. One reason might be the downgrade of hibernate-entitymanager 5.1.0 -> 5.0.9.

 I don't know if its a bug or a failure of myself. Starting my spring boot webservice over eclipse launchConfiguration behaves different to commandline. 

1.4.0.M2
```json
spring-boot-starter-web:1.4.0.M2
	-> hibernate-validator:5.2.4.Final
sorubg-boot-starter-data-jpa:1.4.0.M2
	-> hibernate-entitymanager:5.1.0.Final

```

1.4.0.RELEASE
```json
spring-boot-starter-web:1.4.0.RELEASE
	-> hibernate-validator:5.2.4.Final
sorubg-boot-starter-data-jpa:1.4.0.RELEASE
	-> hibernate-entitymanager:5.0.9.Final

```

I am using Windows 10 and JDk 1.8.0_120

I am starting my webservice jar as following: 
```
"c:\Program Files\Java\jdk1.8.0_102\bin\java.exe" -jar -Dport=11000 -DLOG_PATH=local_log_%d{yyyy-MM-dd}.log -Dpwfile="J:\pwd" -Dspring.profiles.active=local -DLOG_FORMAT=JSON ws-order-1.0.21-SNAPSHOT.jar
```

The same code with different entityscan annotation results in different results (works/failure) when starting over commandline.

| Spring Boot Version        | EntityScan           | Result  |
| ------------- |-------------| -----:|
| 1.4.0.RELEASE      | org.springframework.boot.autoconfigure.domain.EntityScan | failure |
| 1.4.0.RELEASE      | org.springframework.boot.orm.jpa.EntityScan | failure |
| 1.4.0.M2 | org.springframework.boot.orm.jpa.EntityScan| works |

The strange thing is, that all combination work if i start my webservice over eclipse launchConfiguration
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration type="org.springframework.ide.eclipse.boot.launch">
<stringAttribute key="org.eclipse.debug.core.source_locator_id" value="org.eclipse.jdt.launching.sourceLocator.JavaSourceLookupDirector"/>
<booleanAttribute key="org.eclipse.jdt.launching.ATTR_USE_START_ON_FIRST_THREAD" value="true"/>
<stringAttribute key="org.eclipse.jdt.launching.MAIN_TYPE" value="com.company.webservice.order.WebserviceApp"/>
<stringAttribute key="org.eclipse.jdt.launching.PROJECT_ATTR" value="ws-order"/>
<stringAttribute key="org.eclipse.jdt.launching.SOURCE_PATH_PROVIDER" value="org.springframework.ide.eclipse.boot.launch.BootMavenSourcePathProvider"/>
<stringAttribute key="org.eclipse.jdt.launching.VM_ARGUMENTS" value="-Dpwfile=&quot;J:\encryption\pwd&quot;&#13;&#10;-Dspring.profiles.active=local&#13;&#10;-DLOG_PATH=log_%d{yyyy_MM_dd}.log&#13;&#10;-DLOG_FORMAT=JSON"/>
<booleanAttribute key="spring.boot.ansi.console" value="true"/>
<booleanAttribute key="spring.boot.dash.hidden" value="false"/>
<booleanAttribute key="spring.boot.debug.enable" value="false"/>
<booleanAttribute key="spring.boot.lifecycle.enable" value="true"/>
<stringAttribute key="spring.boot.lifecycle.termination.timeout" value="15000"/>
<booleanAttribute key="spring.boot.livebean.enable" value="true"/>
<stringAttribute key="spring.boot.livebean.port" value="30543"/>
<stringAttribute key="spring.boot.profile" value=""/>
</launchConfiguration>
```

### Questions:

* Any idea why starting over launchConfiguration works and over commandline does not ?
* Is there a reason for the downgrade of hibernate-entitymanager from M2 to RELEASE ?

Thank you in advance 

error-log:
```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties' defined in class path resource 
[org/springframework/boot/autoconfigure/web/ServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
        at com.company.webservice.order.WebserviceApp.main(WebserviceApp.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatEmbeddedServletContainerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/EmbeddedServletContainerAutoConfiguration$EmbeddedTomcat.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties' defined in class path resource [org/springframework/boot/autoconfigure/web/ServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:199)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
        ... 16 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties' defined in class path resource [org/springframework/boot/autoconfigure/web/ServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:536)
        at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1192)
        at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.getCustomizers(EmbeddedServletContainerCustomizerBeanPostProcessor.java:77)
        at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:67)
        at org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor.postProcessBeforeInitialization(EmbeddedServletContainerCustomizerBeanPostProcessor.java:54)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        ... 24 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl
        at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:31)
        at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
        at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:248)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$LocalValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:452)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.getValidator(ConfigurationPropertiesBindingPostProcessor.java:386)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.determineValidator(ConfigurationPropertiesBindingPostProcessor.java:369)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:331)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:302)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        ... 37 common frames omitted
```

**Comment by snicoll** [comment] 2016-08-22 08:30
Wild guess, if the previous `EntityScan` works, it might be because you have a custom `DataSource` configuration and you're relying on `EntityScan` to give you the list of packages. This weird scenario is no longer supported, see [the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#entityscan) for more details.

That's probably not helping the validator exception you have but the symptoms you described made me think of that issue. Thoughts?

**Comment by svenhornberg** [comment] 2016-08-23 07:51
Yes we have a custom DataSource , with sub maven modules containing other entities. I try to make smaller application with the same problem.

One thing that is confusing is, that starting the application over eclipse works.
Any idea why starting over launchConfiguration works and over commandline does not ?

Does this entry do some magic :) ?
`<stringAttribute key="org.eclipse.jdt.launching.SOURCE_PATH_PROVIDER" value="org.springframework.ide.eclipse.boot.launch.BootMavenSourcePathProvider"/>`

As said I try to make a smaller example application with the same problem.

**Comment by snicoll** [comment] 2016-08-23 07:54
Sorry I meant a custom `LocalEntityManagerFactoryBean`. If you do, please use `packages()` and specify the packages to use there rather than relying on `EntityScan`. This annotation is only supported with the JPA auto-configuration.

**Comment by svenhornberg** [comment] 2016-08-23 10:45
I tried it over LocalEntityManagerFactoryBean but didnt help. We have a new theory. Our spring boot application contains serveral sub maven projects which contains provided maven dependencies.

Our theory is  mvn:package and spring-boot run tie in our provided dependencies, and if we start it over command line it does not work. On the other hand, if we run it within the STS IDE we run it over the integated launchconfiguration which use "org.springframework.ide.eclipse.boot.launch" for launching the application will start flawless.

Do you think this can make a difference? that we encounter that different behavior

**Comment by svenhornberg** [comment] 2016-08-25 07:29
Any information which I could provide you ? 

Any Idea why org.springframework.ide.eclipse.boot.launch.BootMavenSourcePathProvider starts without problems and java -jar app.jar (with parameters) does not ?

**Comment by snicoll** [comment] 2016-08-25 07:33
Classes aren't found in the fat jar yes. We have several other use cases like that. That's why I am asking for a sample. Can you give us that please?

**Comment by svenhornberg** [comment] 2016-08-29 10:22
I could not provide my code (company restriction), but i found the reason.
Before spring boot 1.4.0 we wanted to use Java 8 LocalDateTime but run into some serialisation deserialisation issues due to the hibernate version 4, which does not support these types.

We used a custom [type ](https://gist.github.com/svenhornberg/5b74685107abd073159882e9c04df03c)from [here](http://blog.progs.be/550/java-time-hibernate). Now with the newer version of spring boot and hibernate, I run into the issue, that I cant start my jar from commandline.

Hope this will help you.

**Comment by philwebb** [comment] 2016-08-29 10:40
@svenhornberg It's still quite hard to tell exactly what's going on here. It's completely understandable that you can't share your entire codebase, but would you be able to put together a minimal sample that reproduces the problem?

**Comment by svenhornberg** [comment] 2016-09-09 09:40
I solved the problem. 

In our submaven project we had the following dependencies and i needed to set them optional true:

       <dependency>
            <groupId>jboss</groupId>
            <artifactId>jbossall-client</artifactId>
            <version>3.2.6</version>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.jboss.netty</groupId>
            <artifactId>netty</artifactId>
            <version>3.2.0.Final</version>
            <optional>true</optional>
        </dependency>

We have a common lib which is used for 2 products. I will try to reproduce it in a smaller example, but maybe you already know a bit more. 

I am still wondering, why does eclipse start it with no problems and jar -jar does not work.

**Comment by spring-issuemaster** [comment] 2016-09-16 13:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-09-23 13:34
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-09-23 13:34 UTC
Labels: feedback-provided

**Comment by choene** [comment] 2016-11-24 08:27
I noticed the same problem

**Comment by wilkinsona** [comment] 2016-11-24 09:33
@choene We never managed to figure out what was happening here as we could reproduce the problem. If you have a small sample that reproduces it, please share it with us and we can take a proper look.

**Comment by jansyk13** [comment] 2016-11-24 10:44
I got the same problem. It runs from Idea well but when I wan't to run the jar it fails on ` java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.ConfigurationImpl` - same stacktraces.  When looking into repackaged jar, I can see that `hibernate-validator` is there.

**Comment by choene** [comment] 2016-11-24 10:48
I had to remove the old Jboss Common dependency. Now it is working.

**Comment by choene** [comment] 2016-11-24 10:51
if you want to reproduce it, at the https://mvnrepository.com/artifact/jboss/jboss-common, compile the jar file with maven, and run it. Then, you get the error...

If you start the app with Eclipse, all is fine.

**Comment by wilkinsona** [comment] 2016-11-24 13:01
Thanks, @choene.

The problem is that `jboss:jboss-common` contains `org.jboss.logging` classes. These have the potential to conflict with the same classes from `org.jboss.logging:jboss-logging` which is a transitive dependency of Hibernate Validator. If `jboss-common` is on the classpath before `jboss-logging` the failure will occur. That applies both in an IDE and in a packaged jar, it just depends on the ordering used in each case.
