### ISSUE TITLE
Autowired HttpServletRequest does not work in jersey's filter and listener

### ISSUE THREAD

**Issue by tutufool** [spring-projects/spring-boot#15433] opened 2018-12-10 11:23 UTC
Hi,

After upgrade to 2.1.1, the autowired HttpServletRequest in my ContainerRequestFilter not work anymore;

    public class MyFilter implements ContainerRequestFilter {
  
      @Autowired
      HttpServletRequest request;

I think this is caused by: https://github.com/spring-projects/spring-boot/commit/b094e28081bf733215679d4a22014ddd477ccde7

My project simply have starter-jersey dependency, without starter-web.

I know it's to solve https://github.com/spring-projects/spring-boot/issues/15048
But I'm afraid that simply remove the bean definition from JerseyAutoConfiguration might impact existing code.

Leon

**Comment by wilkinsona** [comment] 2018-12-10 11:36
Duplicate of #15376

**Closed by wilkinsona** 2018-12-10 11:36 UTC
Labels: status: waiting-for-triage
