### ISSUE TITLE
Spring WebFlux does not log uncaught exceptions by default

### ISSUE THREAD

**Issue by andreysaksonov** [spring-projects/spring-boot#15953] opened 2019-02-14 11:12 UTC
In case of classic servlet-based applications you usually get logging of errors with nice stacktrace out of the box (I checked this with default Tomcat setup, and actually not sure if it is true for all embedded servlet containers).

However, is you go to "https://start.spring.io/", choose only "Reactive Web" and add to the project the following code:

```
@RestController
public class TestErrorController {

    @GetMapping
    public String test() {
        throw new RuntimeException("ERROR!");
    }
}
```

You will get only error in response like:

```
✔ ~/Downloads/demo-reactive 
14:04 $ curl http://localhost:8080
{"timestamp":"2019-02-14T11:04:35.280+0000","path":"/","status":500,"error":"Internal Server Error","message":"ERROR!"}✔ ~/Downloads/demo-reactive 
14:04 $ 
```

However logs keep silence about what happened:

```
2019-02-14 14:04:17.605  INFO 92904 --- [           main] c.e.d.DemoReactiveApplication            : Starting DemoReactiveApplication on AndreySaksonov.local with PID 92904 (/Users/andrey.saksonov/Downloads/demo-reactive/target/classes started by andrey.saksonov in /Users/andrey.saksonov/Downloads/demo-reactive)
2019-02-14 14:04:17.609  INFO 92904 --- [           main] c.e.d.DemoReactiveApplication            : No active profile set, falling back to default profiles: default
2019-02-14 14:04:19.007  INFO 92904 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
2019-02-14 14:04:19.012  INFO 92904 --- [           main] c.e.d.DemoReactiveApplication            : Started DemoReactiveApplication in 1.98 seconds (JVM running for 3.818)
```

It is very unfriendly to newcomers, I believe that for all out-of-the box setups, uncaught exceptions should be logged.

**Comment by nosan** [comment] 2019-02-14 11:42
Hi @andreysaksonov,
Have you seen this [issue](https://github.com/spring-projects/spring-boot/issues/15769).
Looks like you have the same problem.

**Comment by wilkinsona** [comment] 2019-02-14 11:43
Thanks, @nosan. I was just about to say that this is a duplicate of https://github.com/spring-projects/spring-boot/issues/15769.

**Closed by wilkinsona** 2019-02-14 11:43 UTC
Labels: status: waiting-for-triage

**Comment by andreysaksonov** [comment] 2019-02-14 12:00
@nosan @wilkinsona Thanks, I tried to search, but didn't find it for some reason
