### ISSUE TITLE
Iterating over JarFile.entries() is very slow.

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-boot#15096] opened 2018-11-05 12:35 UTC
Iterating over `org.springframework.boot.loader.jar.JarFile#entries()` is very slow. The successive calls to [`JarFileEntries#getEntry`](https://github.com/spring-projects/spring-boot/blob/804f647a34326599f2f98975c5d55494e10643cc/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarFileEntries.java#L242) by [`EntryIterator#next`](https://github.com/spring-projects/spring-boot/blob/804f647a34326599f2f98975c5d55494e10643cc/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarFileEntries.java#L296) are causing the underlying `RandomAccessFile` to jump back and forth in order to re-read the file headers from the central directory of the jar file. This could be much faster if [`JarFileEntries#visitFileHeader`](https://github.com/spring-projects/spring-boot/blob/804f647a34326599f2f98975c5d55494e10643cc/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarFileEntries.java#L99) would store the complete `FileHeader` instead of just it's offset and the hash of its name.

### Some Background

While working on https://github.com/joinfaces/joinfaces/pull/565 i noticed that ClassGraph is about 500ms slower when scanning a repackaged Spring Boot application than scanning the same application in its unpacked form. So I had a look at the code of ClassGraph and saw that it extracted all the nested jars in order to scan them. Hoping to improve the performance of scanning nested jars, I prepared the following patch to use the JarFile implementation of `spring-boot-loader` in order to avoid the extra cost of extracting all the nested jars:
https://github.com/larsgrefer/classgraph/compare/ba4c69347eaf915571e9f5142e09f7a481471570...cfb317aff4d6949afbddcc1fd0ad78b118ef52ec?expand=1

Surprisingly this approach is even a bit slower, so I dug deeper into the code and traced the performance difference down to the Iteration done here: https://github.com/classgraph/classgraph/blob/b170d2bebb871824f7d53d54aa7a9b6939f25cf0/src/main/java/io/github/classgraph/utils/JarfileMetadataReader.java#L148

In my tests, iterating over a `org.springframework.boot.loader.jar.JarFile` is about 5 to 10 times slower than iterating over a `java.util.zip.ZipFile`. Ths performance impact is so severe that its even faster to extract the nested jar first, to be able to use `java.util.zip.ZipFile`

### Conclusion

After I read the commit message of https://github.com/spring-projects/spring-boot/commit/e2368b909b46bc5bcec6792fb208ba9bd0fe6aaa it seems to me, that memory efficiency is more important for you than iteration performance. So my question is if you would accept a pull request which changes the current behavior or allows ClassGraph to change the behavior of the `JarFileEntries` implementation and how this PR should look like.

**Comment by wilkinsona** [comment] 2018-11-05 12:52
Interesting findings, thank you for sharing them.

Our overriding goal with any changes that we've made to Spring Boot's fat jar support is to optimise for startup performance. While the changes made in e2368b9 reduced memory usage, the end result was faster startup due to reduced GC pressure. This includes scanning of the jar's contents by Spring Framework's class path scanning machinery.

We haven't, to my knowledge, done any analysis of startup performance when `ClassGraph` is involved. On first impression, it seems to take a different approach to scanning than is taken by Spring Framework. It may be that the change you're proposing here could be generally useful or it could only be of use when ClassGraph-style scanning is being performed. Another possibility is that we can recommend some changes to ClassGraph that improve its performance without requiring any changes in Boot.

Could you please provide some example code that reproduces the behaviour that you've described above? I'd like to take a look at both the real-world scenario with Joinfaces and the more focussed case where you've looked at `org.springframework.boot.loader.jar.JarFile` vs `java.util.zip.ZipFile`.

**Comment by larsgrefer** [comment] 2018-11-05 13:54
I'm not sure if the proposed change would have a big impact on the GC pressure. The necessary objects are [created anyway](https://github.com/spring-projects/spring-boot/blob/804f647a34326599f2f98975c5d55494e10643cc/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/CentralDirectoryParser.java#L65-L69) and passed to [`JarFileEntries#visitFileHeader`](https://github.com/spring-projects/spring-boot/blob/804f647a34326599f2f98975c5d55494e10643cc/spring-boot-project/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarFileEntries.java#L99). They just aren't stored, so `getEntry` needs to create them again while iterating.

Instead of changing the current implementation it would also be possible to add a second implementation of `JarFileEntries`.

I'll publish my example code later and then link it here so you can have a look at it.

**Comment by larsgrefer** [comment] 2018-11-05 20:34
Here is my example project: https://github.com/larsgrefer/zip-performance-test

Just execute the unit tests and have a look at their output (stdout)

**Comment by larsgrefer** [comment] 2018-11-05 21:39
> On first impression, it seems to take a different approach to scanning than is taken by Spring Framework.

Spring Framework iterates over `JarFile#entries()` exactly [here](https://github.com/spring-projects/spring-framework/blob/5e7a8b275d94586237a6725a80cedb761194b3d3/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L647). (The Spring Boot `JarFile` is obtained [here](https://github.com/spring-projects/spring-framework/blob/5e7a8b275d94586237a6725a80cedb761194b3d3/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L600))

**Comment by larsgrefer** [comment] 2018-11-07 12:13
What kind of real-world scenario would you prefer?

- I could prepare a test based on the classpath scanning done by ClassGraph.
  - For non-nested jars this would compare `ZipFile` <> `JarFile`,
  - for nested jars this would compare `Unzip + ZipFile` <> `Jarfile`.

- I could prepare the proposed change in a feature branch of spring-boot, so you can compare the performance of the current `JarFile`-implementation with the proposed one.

If I start working on this, should I base my work on `1.5.x`, `2.0.x` or only `2.1.x`?

**Comment by wilkinsona** [comment] 2018-11-07 12:18
By real-world scenario, I mean a complete application as that's the context in which the performance of our `JarFile` is important. The application that you used when working on https://github.com/joinfaces/joinfaces/pull/565 or something similar to it would be ideal.

**Comment by larsgrefer** [comment] 2018-11-07 12:44
I'll try to assemble such an example.

**Comment by larsgrefer** [comment] 2018-11-10 19:17
I've also added a mid-sized example which provides more stable results.

When executing the unit tests of `:half-example:zipfile` and `:half-example:jarfile` this are my results:

Using ZipFile:
```
Classpath scan took 207,036227 ms
Classpath scan took 191,851481 ms
Classpath scan took 193,802979 ms
Classpath scan took 182,531380 ms
```

Using JarFile:
```
Classpath scan took 232,512777 ms
Classpath scan took 245,336233 ms
Classpath scan took 248,245218 ms
Classpath scan took 230,905295 ms
```

**Comment by wilkinsona** [comment] 2018-11-12 12:29
Thanks for the new examples. Unfortunately, I'm not sure I'm really any the wiser having looked at them. The patched versions of Classgraph are, largely, a black box. I've spent a bit of time trying to see what your patches do, but they're spread over numerous commits. They also seem to be using Boot's jar loader reflectively and in scenarios where it would not normally be used, neither of which I would recommend.

Spring Boot's launcher is intended to be used when an application has been packaged as an executable jar file or war file and is using a `org.springframework.boot.loader.Launcher` sub-class as its entry point. This includes a scenario where the application has been packaged as an executable jar file or war file and then exploded as happens, for example, on CloudFoundry. The use of `org.springframework.boot.loader.jar.JarFile` rather than `java.util.jar.JarFile` should then be entirely transparent. This intended transparency is why the former is a sub-class of the latter and we do not expect `org.springframework.boot.loader.jar.JarFile` to be used directly. This is one area where what you are proposing for Classgraph is different to Spring Framework. Spring Framework has no knowledge of Spring Boot and deals purely with `java.net.JarURLConnection` and `java.util.jar.JarFile`.

There may be room for improvement in the performance of `org.springframework.boot.loader.jar.JarFile`. Unfortunately, the examples provided so far make it difficult to justify spending any more time investigating as, as far as I can tell, they aren't using `org.springframework.boot.loader.jar.JarFile` in the manner in which it's intended to be used. It should be possible for Classgraph to scan a Spring Boot fat jar without knowing that's what it is and without having any dependency on `org.springframework.boot.loader.jar.JarFile`. This is exactly what Spring Framework does, for example, and I would recommend that Classgraph does so too.

I am happy to spend some more time on this and to explore making some changes that will improve performance, but only if `org.springframework.boot.loader.jar.JarFile` is being used as intended. As I said above, any change that's intended to improve performance will need to do so in a real-world scenario where a fat jar is being launched with `java -jar`.

**Comment by wilkinsona** [comment] 2018-11-12 12:44
Reading the discussion again, I think that this is the best route forward:

> I could prepare the proposed change in a feature branch of spring-boot, so you can compare the performance of the current JarFile-implementation with the proposed one.

**Comment by larsgrefer** [comment] 2018-11-12 13:05
The way in which the `org.springframework.boot.loader.jar.JarFile` instances are obtained are indeed different for Spring Framework and the proposed ClassGraph version, but in fact they both iterate over `org.springframework.boot.loader.jar.JarFile.entries()`.

I also understand that the way I'm planning to use `org.springframework.boot.loader.jar.JarFile` in ClassGraph isn't exactly it's intended use case and that this issue therefore might be less important for you.

At the tip of which branch should I start to implement the proposed change?

**Comment by wilkinsona** [comment] 2018-11-12 13:35
I'd use `master` for now at least.

**Comment by larsgrefer** [comment] 2018-11-12 13:54
Okay :+1: 

I'll implement the proposed change

**Comment by larsgrefer** [comment] 2018-11-14 00:02
I've started to implement my proposed changes: https://github.com/spring-projects/spring-boot/compare/master...larsgrefer:feature/jarFilePerformance?expand=1

I've also updated the example project to test the new `JarFile` implementation. These are my results so far:

- `small-example`:
  - ZipFile: 2-4ms
  - current JarFile: 40-55ms
  - new JarFile: 15-18ms
- `half-example`:
  - ZipFile: 180-210ms
  - current JarFile: 230-250ms
  - new JarFile: 66-77ms

Shall I open a pull request with my changes already so they can be easier reviewed and disscussed or should I wait until I think it's ready to be merged?

Do you have any tipps how I can produce a repackaged jar with my new JarFile implementation instead of the current one?

**Comment by philwebb** [comment] 2018-11-14 01:20
> Do you have any tipps how I can produce a repackaged jar with my new JarFile implementation instead of the current one?

@larsgrefer You can use a custom `LayoutFactory` and return a [CustomLoaderLayout](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/CustomLoaderLayout.java) that writes additional classes.

**Comment by larsgrefer** [comment] 2018-11-14 02:34
I'll definitely want to build an additional example, where we can compare the current and the new JarFile implementation in a "normal" Spring Boot application in terms of execution speed and memory consumption.

I'd also like to emphasize that my feature branch isn't finished yet. As all entries are now cached in the Map, some other things like the int arrays might be redundant now. Cleaning this up should improve the performance of my proposal a bit more.

While the memory consumption will definitely rise a bit, I'm very curious how spring's component-scan will be affected by this. (As mentioned earlier, _Spring Framework_ also iterates over the entries of a JarFile [here](https://github.com/spring-projects/spring-framework/blob/5e7a8b275d94586237a6725a80cedb761194b3d3/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L647))

A few 10-100kb more RAM usage is a disadvantage I'm willing to accept for faster execution speed, but we have to see what the real numbers will be.

**Comment by philwebb** [comment] 2018-11-14 03:33
> I'd also like to emphasize that my feature branch isn't finished yet. As all entries are now cached in the Map, some other things like the int arrays might be redundant now.

One idea behind the arrays was to be able to very quickly answer the question "is this class missing". With so many optional dependencies in Spring, It's quite common to have numerous `Class.forName("something.not.on.the.classpath")` calls. The array let's us very quickly answer that question without consuming too much memory.

If we cache _all_ entries then those arrays can go, but that's something that doesn't sit easy with me at the moment. I think I'd rather explore making `entriesCache` something that can grow and shrink as needed. That way, if memory is tight, those entries can go.

Spring Framework has a `ConcurrentReferenceHashMap` class that's designed for caches. It uses weak references so that it gets GC'd if necessary. The problem we have is that we'd need to copy a version that class into the loader if we want to use it.

**Comment by spring-issuemaster** [comment] 2018-11-23 16:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-11-30 16:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-11-30 16:32 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by larsgrefer** [comment] 2018-12-18 01:17
While working on this I noticed that my idea would have a much bigger impact on the memory usage than I thought it would. In the current implementation only one `CentralDirectoryFileHeader` instance is created for each jar file and subsequently filled with the information of the jar file entries. With my implementation I'd have to create one instance per entry.

In the meantime we found two other solutions to our inital problem:

1. @lukehutch implemented a custom directory parser for classgraph, so classgraph can now scan nested jar files directly, without extracting them first.
2. At JoinFaces we implemented a Maven plugin and a Gradle plugin which perform the classpath scan at build-time.

With the build-time scan we reduced this part of the application startup to ~200ms for reading a list of class names from a text file and loading them.

**Comment by lukehutch** [comment] 2018-12-18 02:16
If you have time to do this, I would be very curious to see a benchmark of Spring's central directory parser vs. the latest version of ClassGraph (where for ClassGraph you wouldn't enable classfile scanning so that directory entries are not actually inflated, so use `.whitelistPaths()` rather than `.whitelistPackages()`, and don't call `.enableClassInfo()`, etc.).
