### ISSUE TITLE
After upgrade from Spring Boot 2.7 to SpringBoot 3.1.6 @Transactional is not working for the async calls

### ISSUE THREAD

**Issue by santoshmasal123** [spring-projects/spring-boot#39214] opened 2024-01-17 19:50 UTC
When you  Upgrade  Spring Boot2.7 to SpringBoot3.1.6 @Transactional is not working for the Async calls.
1. There is no error while aysnc calls.
2. we are using springCloudAWS 3.0.4

Can U please assist what is wrong with this

**Comment by scottfrederick** [comment] 2024-01-17 19:56
@santoshmasal123 I'm afraid there's not much information here for us to go on. If you would like us to spend some time investigating, please provide a complete minimal sample that we can run ourselves to reproduce the problem. Such a minimal sample should not include Spring Cloud AWS. If Spring Cloud AWS is required to reproduce the problem, then an issue should be filed against [that project](https://github.com/awspring/spring-cloud-aws) instead of Spring Boot. You can share it with us by pushing it to a separate repository on GitHub or by zipping it and attaching it to this issue.

**Comment by wilkinsona** [comment] 2024-01-31 12:06
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by wilkinsona** 2024-01-31 12:06 UTC
Labels: status: waiting-for-triage, status: feedback-reminder
