### ISSUE TITLE
spring.messages.basename not working when I config custom value

### ISSUE THREAD

**Issue by panzhuowen** [spring-projects/spring-boot#18513] opened 2019-10-04 13:58 UTC
`spring.messages.basename` when I config custom value, I debug source code, I find String `basename = context.getEnvironment().getProperty("spring.messages.basename", "messages");`  return default value. can't get my custom value

**Comment by wilkinsona** [comment] 2019-10-04 16:21
Thanks for the report. Unfortunately, that isn't enough information for us to diagnose the problem. It sounds very similar to https://github.com/spring-projects/spring-boot/issues/18440. Perhaps you are disabling bean metadata caching or using a custom JVM that is doing so? If that's not the case and you'd like us to spend some time investigating, please spend some time creating a minimal example that reproduces the problem that you have described and then attach it as a zip to this issue.

**Comment by panzhuowen** [comment] 2019-10-05 02:43
I use orcalejdk1.8 , config spring.messages.basename=messages,static.i18n.messages
spring.messages.fallback-to-system-locale=false, it not woring

**Comment by wilkinsona** [comment] 2019-10-05 08:49
Thanks for the additional information. So that we can be sure that we're looking at the exact same problem as you are seeing, can you please provide a complete and minimal sample that reproduces the problem? A small project, zipped and attached to this issue is ideal.

**Comment by spring-issuemaster** [comment] 2019-10-12 08:54
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-10-19 08:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-10-19 08:52 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
