### ISSUE TITLE
Groovy Markup Template tries to grab HTML 

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2212] opened 2014-12-20 21:20 UTC
I have an application using Thymeleaf exclusively for view rendering but Groovy extensively for model/controller logic,with groovy-all. I just updated to 1.2 and am seeing nondeterministic errors where the Groovy Markup Template engine is trying to render my HTML files and is throwing exceptions on the first character. The application worked fine in staging and was deployed to an identical production runtime (PWS). I am attempting to work around by disabling all the Groovy Web autoconfig.

**Comment by philwebb** [comment] 2015-01-07 05:20
Pinging @ghillert or @dsyer for a sample app.

**Comment by wilkinsona** [comment] 2015-01-26 13:22
> I think it might be because `GroovyMarkupViewResolver` is a `UrlBasedViewResolver` and always returns a non-null `View` if caching is off

I don't think the above is true. Beneath `resolveViewName` `checkResource` is called on `GroovyMarkupView`. It returns `false` when it can't resolve the `.tpl` template, causing `resolveViewName` to return `null`.

**Comment by wilkinsona** [comment] 2015-01-27 13:54
With thanks to @davetownsend, I've managed to whittle things down to the bare minimum required to reproduce the problem. I've added [an app](https://github.com/spring-projects/spring-boot-issues/tree/master/gh-2212) to spring-projects/spring-boot-issues. Now that I understand what's happening, I'm not entirely surprised we've struggled to reproduce this.

You need to be using Thymeleaf and accidentally have Groovy templates on the classpath. You also need to have already make a request that causes a mapping from `.html` to `text/html` to be added to `ServletPathExtensionContentNegotiationStrategy`. Accessing a static `/index.html`, for example.

If you then make a request to a templated page asking for `text/html` the problem will occur. If the view that's being resolved is named `foo`, `foo.tpl` will be tried. This doesn't exist so the `Accept` header's then used to identify additional extensions to try. Due to the `text/html` to `.html` mapping, this leads to `foo.tpl.html` being tried. `MarkupTemplateEngine.TemplateResource.parse("foo.tpl.html")` turns `foo.tpl.html` into `foo.html`. This file does exist but it's a Thymeleaf template so the attempt to compile it as Groovy fails.

The behaviour of `MarkupTemplateEngine.TemplateResource.parse` seems a little suspect to me. I don't understand why `foo.tpl.html` gets mapped to `foo.html`. It's done with a regex:

    (.+?)(?:_([a-z]{2}(?:_[A-Z]{2,3})))?\\.(\\p{Alnum}+)

`baseName`, `locale`, and `extension` are group 1, 2, and 3 respectively from the regex.

**Comment by wilkinsona** [comment] 2015-01-27 15:11
I've emailed @melix to get his thoughts on the behaviour of `TemplateResource.parse`

**Comment by wilkinsona** [comment] 2015-01-27 17:59
https://jira.codehaus.org/browse/GROOVY-7277

**Comment by wilkinsona** [comment] 2015-01-28 17:42
I've submitted a Groovy PR that should fix the underlying bug: groovy/groovy-core#600

**Comment by philwebb** [comment] 2015-01-28 19:35
Looks like this has been merged so we should be boot when Groovy 2.3.10 is released.

**Comment by spencergibb** [comment] 2015-01-28 19:40
:+1: "we should be boot", made me chuckle.

**Comment by philwebb** [comment] 2015-01-28 19:41
Whoops. `s/boot/good/`, I seems to have some muscle memory with that word for some reason!

**Closed** 2015-02-18 16:56 UTC
Labels: bug

**Comment by Guada** [comment] 2015-02-24 23:47
it's weird but it still seems present in Groovy 2.4.1. I've an app with Thymeleaf and Groovy, everthing is fine if I use Groovy 2.3.10, but then in 2.4.1 the issue pops up again.
