### ISSUE TITLE
CapturedOutputExtension with Log4j?

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-boot#32210] opened 2022-09-01 08:05 UTC
According to this article https://www.codebyamir.com/blog/testing-log-statements-in-spring-boot, it's possible to assert `log4j` logging statements with springs `OutputCaptureExtension`. Is that correct? Because the following test fails:

```
public class LogServiceTest {
	private final Logger logger = LoggerFactory.getLogger(LogServiceTest.class);

	@Test
	@ExtendWith(OutputCaptureExtension.class)
	public void test(CapturedOutput capture) {
		logger.info("junit");
	       assertEquals("junit", capture.getAll());
	}
}
```

If that's not supported, maybe this issue could serve for an extension proposal to support log4j?

**Comment by wilkinsona** [comment] 2022-09-01 08:12
Without a sample, it's hard to be certain, but I suspect this is a duplicate of https://github.com/spring-projects/spring-boot/issues/27902. If that's not the case, please provide a complete yet minimal sample that reproduces the problem and we can take another look.

**Closed by wilkinsona** 2022-09-01 08:12 UTC
Labels: status: waiting-for-triage

**Comment by membersound** [comment] 2022-09-01 08:26
Indeed adding `follow="true"` fixes the problem.
