### ISSUE TITLE
Programatically Declare "keys-to-sanitize"

### ISSUE THREAD

**Issue by michaelmcfadyensky** [spring-projects/spring-boot#27296] opened 2021-07-12 18:04 UTC
### Problem I am looking to solve:
I am building a library that exposes configuration properties and some of these configuration properties would be seen as sensitive. So we'd want these properties to be masked on the `/configprops` endpoint. I would prefer for the library to be the source that declares these properties as sensitive and not push that responsibility down to each spring boot application using this library.

### Current Solution
Each application using this library needs to be aware that they need to update the `management.endpoint.configprops.keys-to-sanitize` property to ensure sensitive information is not leaked. This results in this responsibility being managed in many places, instead of one.

### Proposed Solution(s)
Below are a couple suggestions but more than welcome to suggestions.

1 .Introduce a mechanism to define **additional** `keys-to-santize` programmatically.

2 .Introduce a way to tag a field within a `@ConfigurationProperties` class as "should be santized"

```
@ConfigurationProperties(prefix = "my.sensitive")
public class SensitiveProperties {
    
    @Sanitize
    private String valueToSanitise;
}
```

More than happy to find out this functionality already exists in Spring Boot and I've just missed it.

**Comment by wilkinsona** [comment] 2021-07-12 18:26
Have you seen the [support that we added for this in 2.5](https://github.com/spring-projects/spring-boot/issues/25384)?

**Comment by michaelmcfadyensky** [comment] 2021-07-12 18:57
Correct me if I'm wrong but that feature still requires yml/properties to be set. I'm not sure how that could be used by a custom "starter" library to define additional keys to sanitize.

**Comment by wilkinsona** [comment] 2021-07-12 19:03
You can call [`keysToSanitize(String...)`](https://github.com/spring-projects/spring-boot/blob/a3c7a7d44045794631e5275525e1cbeb5eaede1a/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/env/EnvironmentEndpoint.java#L79) on the endpoint to add additional keys.

**Comment by wilkinsona** [comment] 2021-07-13 08:02
Judging by the :+1:, I think we're good here. Closing as a duplicate of #25384.

**Closed by wilkinsona** 2021-07-13 08:02 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by michaelmcfadyensky** [comment] 2021-07-13 08:27
sorry, for the delay. I was just testing a few things and you're right, we're good here. Thanks for your help.
