### ISSUE TITLE
Spring Boot 3.2.5 -> 3.2.6: org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.24 compiled against JDK 22

### ISSUE THREAD

**Issue by sanderino666** [spring-projects/spring-boot#40887] opened 2024-05-23 13:57 UTC
After upgrading Spring Boot 3.2.5 to 3.2.6, maven enforcer throws an error:

```
[INFO] --- enforcer:3.4.1:enforce (enforce-versions) @ service ---
[INFO] Rule 1: org.apache.maven.enforcer.rules.dependency.RequireUpperBoundDeps passed
[INFO] Restricted to JDK 21 yet org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.24:compile contains org/apache/tomcat/util/net/openssl/panama/OpenSSLContext$1.class targeted to JDK 22
```

**Comment by bclozel** [comment] 2024-05-23 14:23
Closing as a duplicate of https://bz.apache.org/bugzilla/show_bug.cgi?id=68947

**Closed by bclozel** 2024-05-23 14:23 UTC
Labels: status: waiting-for-triage
