### ISSUE TITLE
MeterRegistryCustomizer not called if Spring Data is in the classpath

### ISSUE THREAD

**Issue by samcontesse** [spring-projects/spring-boot#26675] opened 2021-05-26 18:11 UTC
Hello!

It seems that the newly introduced `RepositoryMetricsAutoConfiguration` (Spring Boot 2.5.0) triggers the creation of the `MeterRegistry` bean during the initialization of the bean post processor. This leaves no chance for `MeterRegistryPostProcessor#postProcessAfterInitialization` to customize the registry with `MeterRegistryCustomizer`.
The call stack shows some `registerBeanPostProcessors` when the registry is instanciated which is not the case when `RepositoryMetricsAutoConfiguration` is not loaded. 

I created a [minimal sample repo](https://github.com/samcontesse/metrics-customizer-not-called) to reproduce the issue.

If you run it, you can see that `MetricsCustomizerNotCalledApplication#meterRegistryCustomizer` is never called. If  `spring-boot-starter-data-jpa` is removed from dependencies, it is called as expected.

A ugly workaround would be to call it again afterwards with something like:
```
    @Bean
    public InitializingBean forceMeterPostProcessor(BeanPostProcessor meterRegistryPostProcessor, MeterRegistry registry) {

        return () -> meterRegistryPostProcessor.postProcessAfterInitialization(registry, "");
    }
```

Thanks for your help.

**Comment by izeye** [comment] 2021-05-26 18:49
This seems to be a duplicate of https://github.com/spring-projects/spring-boot/issues/26630.

**Comment by scottfrederick** [comment] 2021-05-26 18:55
Running the sample against Spring Boot `2.5.1-SNAPSHOT` results in the expected message being shown. Marking as duplicate.

**Closed by scottfrederick** 2021-05-26 18:55 UTC
Labels: status: waiting-for-triage
