### ISSUE TITLE
Spring Boot 2.2.6

### ISSUE THREAD

**Issue by yegulang** [spring-projects/spring-boot#21010] opened 2020-04-18 09:49 UTC
When I use spring boot of version 2.2.6, I also use spring boot starter data redis.At this time,using fastjson does not work.Even if fastjsonhttpmessageconverter is configured.So,I remove Jackson.
There is another problem.When using redisTemplate, the efficiency is very low when the project is first started to take data from redis.After the first time,the efficiency is obviously accelerated,about several hundred times.Is there any optimization scheme?

**Comment by snicoll** [comment] 2020-04-18 12:54
@yegulang I don't understand what you're trying to report. If you think you've found a bug in Spring Boot, you'll need to provide us more details in the form of a small sample reproducing the problem (a zip or a link to a github repo). If you're looking for support, please do so on StackOverflow, 
as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by spring-issuemaster** [comment] 2020-04-25 12:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-05-02 12:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-05-02 12:57 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
