### ISSUE TITLE
Encounter circular dependencies with constructor Autowired

### ISSUE THREAD

**Issue by shaopro** [spring-projects/spring-boot#14231] opened 2018-08-29 02:25 UTC
**Version：SpringBoot2.0.4.RELEASE**
DataBase MongoDB

In the same position, I did not encounter this problem with @Autowired injection.
```
@Component
public class ModelOutputSmartListener2 implements SmartApplicationListener {
    private final BaseModelOutputRepository repository;
    public ModelOutputSmartListener2(BaseModelOutputRepository repository) {
        this.repository = repository;
    }

//    @Autowired
//    private  BaseModelOutputRepository repository;

    @Override
    public boolean supportsEventType(Class<? extends ApplicationEvent> eventType) {
        return eventType == ModelOutputSmartEvent.class;
    }

    @Override
    public boolean supportsSourceType(Class<?> sourceType) {
        return sourceType == ModelPredictServiceImpl.class;
    }

    @Override
    public void onApplicationEvent(ApplicationEvent event) {
        ModelOutputSmartEvent outputSmartEvent = (ModelOutputSmartEvent) event;
        repository.save(outputSmartEvent.getOutputDTO());
    }

    @Override
    public int getOrder() {
        return 2;
    }
}
```
------------------------------------------------------------------
```
public interface BaseModelOutputRepository extends PagingAndSortingRepository<ModelOutputDTO, String> {
}
```
------------------------------------------------------------------
```
public class ModelOutputSmartEvent extends ApplicationEvent {

    private static final long serialVersionUID = -6389484257875675237L;

    @Getter
    private ModelOutputDTO outputDTO;

    public ModelOutputSmartEvent(Object source, ModelOutputDTO outputDTO) {
        super(source);
        this.outputDTO = outputDTO;
    }
}
```
------------------------------------------------------------------
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>

```

**Comment by snicoll** [comment] 2018-08-29 07:04
>  circular dependencies

What is the stacktrace, or better yet, the failure analysis of the circular dependencies. We can't really guess what the problem might be looking at isolated text in code, that's why we always prefer a sample (github repo, or link to a zip) that we can run ourselves. If you can share that, that would be much better.

**Comment by spring-issuemaster** [comment] 2018-09-05 07:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by shaopro** [comment] 2018-09-11 07:52
链接: https://pan.baidu.com/s/1XVJFsPedDK2LSA-mozFvIA 密码: i2y5

**Comment by wilkinsona** [comment] 2018-09-11 08:56
Thanks for the sample but I have been unable to reproduce the problem with it. It seems to require Redis, Kafka, and Mongo but there are no instruction on how to set those up and I don't have time to figure it out from your code and configuration. Can you please provide a minimal sample (the smallest amount of code and configure required to reproduce the problem)?

**Comment by spring-issuemaster** [comment] 2018-09-18 09:00
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-09-25 08:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-09-25 08:59 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
