### ISSUE TITLE
Setting max file size for upload when running on Tomcat

### ISSUE THREAD

**Issue by fredrikwithpettersen** [spring-projects/spring-boot#11284] opened 2017-12-07 15:08 UTC
Hello

Spring Boot 2.0.0.M7

When I try to upload a MultipartFile I get:
`java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException: The field files exceeds its maximum permitted size of 1048576 bytes.`

I have tried the following in application.yaml:
```
spring:
    servlet:
        multipart:
            max-file-size: 10240MB
            max-request-size: 10240MB
```

I have also tried on the controller:
```
@RestController
@RequestMapping(path = "/api/files")
@MultipartConfig(maxFileSize = 10737418240L, maxRequestSize = 10737418240L, fileSizeThreshold = 52428800)
public class FilesController {
...
}
```

None of these are working when im running a local Tomcat. 

Before I upgraded to Spring Boot 2.0.0.M7 I used the CommonsMultipartResolver (where this worked) but after upgrading I noticed that the, for some reason, DispatcherServlet took a long time processing the request. Therefore I have started using the standard Spring Boot implementation of the MultipartResolver.

**Comment by wilkinsona** [comment] 2017-12-07 17:12
> None of these are working when im running a local Tomcat.

What do you mean by "a local Tomcat"? Are you using embedded Tomcat, or building a war file and deploying it to Tomcat? If it's the former, can you please provide a minimal sample that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2017-12-14 17:13
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-12-21 17:16
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-12-21 17:16 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by nicolasandrieux** [comment] 2019-08-30 12:18
For me nothing of previous works (maybe use application with yaml is an issue here), but get ride of that issue using that:

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.MultipartConfigFactory;
import org.springframework.boot.web.servlet.ServletComponentScan;
import org.springframework.context.annotation.Bean;
import org.springframework.util.unit.DataSize;

import javax.servlet.MultipartConfigElement;

@ServletComponentScan
@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Bean
    MultipartConfigElement multipartConfigElement() {
        MultipartConfigFactory factory = new MultipartConfigFactory();
        factory.setMaxFileSize(DataSize.ofBytes(512000000L));
        factory.setMaxRequestSize(DataSize.ofBytes(512000000L));
        return factory.createMultipartConfig();
    }
}
