### ISSUE TITLE
Sleeping JDBC connections are never recreated with test-on-borrow and validationQuery set

### ISSUE THREAD

**Issue by jmkgreen** [spring-projects/spring-boot#6569] opened 2016-08-05 10:20 UTC
Spring-Boot: 1.3.5.RELEASE
JAVA_VERSION=8u91

We have an application that has a single task that "wakes up" in the morning to run a billing report against a MySQL database. When this tasks runs we get stack traces including:

```
2016-08-05 07:05:29,997 WARN  [DefaultQuartzScheduler-camel-1_Worker-1] org.hibernate.engine.jdbc.spi.SqlExceptionHelper (SqlExceptionHelper.java:144) - SQL Error: 0, SQLState: 08003
2016-08-05 07:05:29,997 ERROR [DefaultQuartzScheduler-camel-1_Worker-1] org.hibernate.engine.jdbc.spi.SqlExceptionHelper (SqlExceptionHelper.java:146) - No operations allowed after connection closed.
2016-08-05 07:05:29,998 ERROR [DefaultQuartzScheduler-camel-1_Worker-1] org.apache.camel.util.CamelLogger (CamelLogger.java:204) - Failed delivery for (MessageId: ID-3f23e520a75b-36693-1470332144420-0-8 on ExchangeId: ID-3f23e520a75b-36693-1470332144420-0-9). Exhausted after delivery attempt: 1 caught: org.springframework.dao.DataAccessResourceFailureException: could not prepare statement; nested exception is org.hibernate.exception.JDBCConnectionException: could not prepare statement
```

Further down:
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 48,589,522 milliseconds ago.  The last packet sent successfully to the server was 48,589,522 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
```

The following environment variables are set (via a `docker-compose.yaml`):
```
spring.datasource.url=jdbc:mysql://mysql-test:3307/mydb?user=foo&password=xxx
spring.datasource.tomcat.test-on-borrow=true
spring.datasource.tomcat.min-idle=2
spring.datasource.tomcat.validationQuery=SELECT 1
spring.datasource.tomcat.testWhileIdle=true
spring.datasource.tomcat.max-active=10
```

The `--debug` output does show Tomcat as the Datasource Pool provider.

I am uncertain what else I can do at this point but will try with an alternate Datasource Pool provider such as HikariCP.

**Comment by jmkgreen** [comment] 2016-08-05 12:32
To be precise: on the MySQL server the SLEEP connections seen after starting the application are all gone by the time the above stack trace has occurred.

**Comment by jmkgreen** [comment] 2016-08-05 16:05
I have:

a) Added to my pom.xml:
```
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
```
b) Added to my `docker-compose.yaml`:
```
- spring.datasource.type=com.zaxxer.hikari.HikariDataSource
- logging.level.com.zaxxer.hikari=INFO
```

And on somewhat limited testing connections are now being re-created and database records inserted/updated. I have in my log `INFO  [main] com.zaxxer.hikari.HikariDataSource (HikariDataSource.java:93) - HikariPool-1 - Started.` so reasonably confident this has had an effect at least.

**Comment by wilkinsona** [comment] 2016-08-09 14:09
I can't reproduce this on OS X using MySQL 5.6.19 and mysql-java-connector 5.1.39.

With MySQL configured with a `wait_timeout` of 30 seconds, `show processlist` shows the connections in sleep state up to a time of 30 seconds at which point they're closed. With `spring.datasource.log-validation-errors` set to `true`, I see an exception being logged when connection validation fails. A new connection is then established and the application is able to access the database.

@jmkgreen I can't see anything to suggest that there's a problem in Spring Boot. If you'd like me to investigate further please provide as simple a sample as possible that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2016-08-16 14:09
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-08-23 14:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-08-23 14:12 UTC
Labels: waiting-for-triage
