### ISSUE TITLE
Blank spring boot app stops unexpectedly

### ISSUE THREAD

**Issue by archie-swif** [spring-projects/spring-boot#14976] opened 2018-10-27 08:28 UTC
**Description**
A blank spring boot project, generated on https://start.spring.io with all default options, stops immediately after the start. 
This started after a .m2/repository cleanup, maybe one of the dependencies got corrupted in artifactory. 

**Steps to reproduce:**
1) Clean up ~/.m2/repository
2) Download Maven-Java-Spring 2.0.6 default template from https://start.spring.io
3) Run './mvnw clean spring-boot:run'

Application builds correctly, "Started DemoApplication ..." message is present, and spring app shuts down by itself.

**Two Exceptions are present during startup:**
>2018-10-27 00:58:11.049 TRACE 58879 --- [           main] o.s.boot.diagnostics.FailureAnalyzers    : Failed to load org.springframework.boot.diagnostics.analyzer.ValidationExceptionFailureAnalyzer
java.lang.NoClassDefFoundError: javax/validation/ValidationException

>2018-10-27 00:58:11.055 TRACE 58879 --- [           main] o.s.boot.diagnostics.FailureAnalyzers    : Failed to load org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer
java.lang.NoClassDefFoundError: org/springframework/jdbc/CannotGetJdbcConnectionException

**Logs**
Trace log: https://gist.github.com/archie-swif/ab7e3ee9a2288a5a7c62a228957e97af
Gradle dependencies task: https://gist.github.com/archie-swif/3ea3032754fd1942dc1a4ba27a003a24

**Env**
Build tool: Maven or Gradle
JDK: 1.8.0_181 and 10.0.1
Spring Boot: 2.0.6
OS: MacBook Pro with macOS High Sierra 10.13.6, reproduced on 3 different laptops
Time: Started 10/27/2018 at ~3:30 AM UTC

**Comment by bclozel** [comment] 2018-10-27 09:07
HI @archie-swif 

Your Spring Boot application starts and stops immediately - and this is expected. When creating your application you didn't check any additional starter. This means Spring Boot has no extra dependencies, just the basics, and you've expressed no particular opinion. As far as Spring Boot knows, this could be a simple CLI app; and this is a perfectly fine use case.

If you''d like a web server to start and keep the application alive, you should consider adding `spring-boot-starter-web` or `spring-boot-starter-webflux`, for example.

Now the `NoClassDefFoundError` exceptions you're seeing are expected, and that's why they're only visible at the `TRACE` level. Spring Boot ships with many `FailureAnalyzers`, and some of them require extra classes to work. In this case, you don't have the required dependencies on classpath so they can't be loaded. This behavior is described in #6606.

I'm closing this issue now as it's working as expected, but feel free to reopen it if I've missed something.

Thanks!

**Closed by bclozel** 2018-10-27 09:07 UTC
Labels: status: waiting-for-triage

**Comment by dkaukov** [comment] 2019-01-23 00:32
Hi @bclozel,
The problem is that `java.lang.NoClassDefFoundError: org/springframework/jdbc/CannotGetJdbcConnectionException` is "hiding" actual problem. So, if you have autowiring problem and do not have `spring-jdbc` in class path, you will get "NoClassDefFoundError" instead of failure report.

**Comment by bclozel** [comment] 2019-01-25 08:43
@dkaukov that's not what this report says. The NCDFE are raised at the TRACE level. If you've got a different experience, please create a new issue with a repro project.
