### ISSUE TITLE
Problem with configuration in a @WebMvcTest since Spring Boot 2.1

### ISSUE THREAD

**Issue by celcius112** [spring-projects/spring-boot#15108] opened 2018-11-06 13:31 UTC
Hello,

I have been testing Spring Boot 2.1 recently and I have an issue with configuration in my tests. Several of my tests were working correctly in Spring Boot 2.0.x, but fail in Spring Boot 2.1. 

I have a web MVC test class with a basic test:
```java
@WebMvcTest // In Spring Boot 2.0.x we also had @ExtendWith(SpringExtension.class) below
class WithJUnit5 extends AbstractClass {

    @Test
    void contextLoads() {
    }
}
```

which is extending this abstract class (who's using a bit of lombok magic): 
```java
@ActiveProfiles("test")
@ExtendWith(SpringExtension.class) // Needed in Spring Boot 2.0.x
public abstract class AbstractClass {

    @Autowired
    protected MyProperties myProperties;

    @Setter
    @Getter
    @Component
    @ConfigurationProperties(prefix = "properties")
    protected static class MyProperties {
        private String property;
    }
}
```
This abstract class simply binds a value from a property file, and inject the class afterwards.

The binding and the injection work properly from Spring Boot 1.5.x to Spring Boot 2.0.x, but now fails in Spring Boot 2.1 with stacktrace:
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.springboot21bug.junit5.AbstractClass$MyProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1646)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1205)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 57 more
```

I was not able to go very deep in the code, but I found that `DefaultListableBeanFactory.beanDefinitionNames` does not contain a reference to `AbstractClass$MyProperties` in Spring Boot 2.1, but does in Spring Boot 2.0. Also it is worth noting that `AbstractClass$MyProperties` is correctly configured if defined in a `@SpringBootApplication` class.

The issue is reproduced in this [sample project](https://github.com/celcius112/spring-boot-2-1-property-binding-test). Note that the error appears with JUnit 4 and 5.

**Comment by celcius112** [comment] 2018-11-06 13:40
A solution would be to annotate my abstract class with: `@EnableConfigurationProperties(AbstractClass.MyProperties.class)`, but I couldn't find the reason why in Spring 5.1 and Spring Boot 2.1's release notes.

**Comment by wilkinsona** [comment] 2018-11-06 14:02
Duplicate of #15061. You were relying on some obscure behaviour in Spring Framework where it would find a `@Component` if it's nested within another bean (the bean for the test class in the case), despite that bean not being annotation with `@Configuration`. This behaviour has been tightening up in Spring Framework 5.1.

I works when `MyProperties` is nested inside a `@SpringBootApplication` class as `@SpringBootApplication` is meta-annotated with `@Configuration`.

**Closed by wilkinsona** 2018-11-06 14:02 UTC
Labels: status: waiting-for-triage
