### ISSUE TITLE
Upgrade to Groovy 3.0.0

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#20119] opened 2020-02-11 09:32 UTC
Hi,

as Groovy 3.0.0 is finally released, I was wondering if Spring-Boot should support it. I initially hoped that the upgrade would be easy enough, but there are some things that seem to be not working when I upgrade it. I have a WIP branch where you can see the changes I made so far: https://github.com/spring-projects/spring-boot/compare/master...dreis2211:groovy-3.0.0

Specifically, the Spock framework worries me a bit, because we pull in `org.spockframework:spock-core:1.3-groovy-2.5`. Also the other tests that seem to fail seem to require further investigation and might needs work on Spring-Framework side (see the bean test that I disabled).

Given that Groovy 2.5.x doesn't really support JDK 14, I thought it might be a good point in time to discuss this as 2.3.0 is not out yet, but on the other hand it's already quite late in its development. 

Anyhow, I wanted to start a discussion on this. ;-)

Cheers,
Christoph

**Comment by snicoll** [comment] 2020-02-11 09:36
Thanks Christoph, you're beating me to it again :-) 

I was discussing this with @jhoeller yesterday and I assumed the upgrade on the framework side was completed (at least locally). Will investigate a bit more.

**Comment by dreis2211** [comment] 2020-02-11 09:51
It might on Boot side though. I just couldn't find anything on Boot side, yet. And as the `beans` support is in the Framework I was thinking that it might needs investigation there. Spring-Framework is only using 3.x if a custom java home is set, so in the end it's not really included, just on the CI as far as I got it. See https://github.com/spring-projects/spring-framework/commit/d521d37f14f03688a17b6657df30ff533f2d5f9f

**Comment by dreis2211** [comment] 2020-02-11 11:23
spock-2.0-M2 has Groovy 3.x support, but I doubt there will be a final release in time.

**Comment by jhoeller** [comment] 2020-02-11 11:40
As far as we are testing it, all core Spring Framework tests pass with Groovy 3.0 on JDK 14. Granted, there may be subtle issues with our standard binaries (compiled against Groovy 2.5.9 on JDK 8) running against Groovy 3.0; maybe that disabled bean test in Boot in one such case. If you could track it down from Boot's side, I'd be happy to consider specific adaptations at core framework level.

We intend to fully upgrade to Groovy 3.0 for Spring Framework 5.3 later this year. For the time being, it'd be great to remain compatible with both Groovy 2.5 and 3.0 at runtime.

**Comment by dreis2211** [comment] 2020-02-11 13:10
I think I nailed it down to the changes made in https://issues.apache.org/jira/browse/GROOVY-8399 for the `ImportCustomizer`. It seems that they cause the import processing to be skipped on the `Application` class as it has already been done for the beans classnode. The naive approach of copying the old mechanism to Boot's `SmartImportCustomizer` fixes the failing bean test.

**Comment by dreis2211** [comment] 2020-02-11 20:05
The [groovy-3.0.0 branch](https://github.com/spring-projects/spring-boot/compare/master...dreis2211:groovy-3.0.0) should now be green (at least it is locally).

**Comment by dreis2211** [comment] 2020-02-12 22:22
I wonder if there's value in communicating the `ImportCustomizer` issues to the Groovy team. I tried isolating an example, but wasn't successful. What do you think?

**Comment by wilkinsona** [comment] 2020-02-18 12:14
Thanks for investigating the `ImportCustomizer` problem, @dreis2211. I think it's worth bringing it to the Groovy team's attention.

@paulk-asert We've noticed a behaviour change in Groovy 3.0, although we've been unable to isolate the cause thus far. @dreis2211 has kindly dug a bit and believes it may be related to the changes made for [GROOVY-8399](https://issues.apache.org/jira/browse/GROOVY-8399). Can we please collaborate on identifying and hopefully fixing the problem?

**Comment by paulk-asert** [comment] 2020-02-18 12:44
Sure, we'd be happy to help. Getting an isolated reproducer would be ideal but I can see that hasn't happened yet. The next best thing would be to describe in some detail what is going on in your scenario that is causing the problem with GROOVY-8399. I'd suggest raising a new issue in the GROOVY issue tracker with those details. If we can understand what cases are being skipped, we should be able to work out a fix.

**Comment by dreis2211** [comment] 2020-02-18 14:18
I will investigate a bit further, @wilkinsona if you don't mind and report back if I could find something.

**Comment by dreis2211** [comment] 2020-02-18 20:29
I've finally managed to reproduce it in a minimal example. See https://github.com/dreis2211/groovy3-import-bug

I would open a new issue if that's okay for you, @wilkinsona & @paulk-asert ?

**Comment by paulk-asert** [comment] 2020-02-18 21:12
Sounds good to me.

**Comment by dreis2211** [comment] 2020-02-18 21:30
Here we go: https://issues.apache.org/jira/browse/GROOVY-9407

**Comment by dreis2211** [comment] 2020-02-19 20:59
I've applied the suggestion in the Groovy ticket above, which seems to work around the behaviour change. At least it's better than copying the old `ImportCustomizer` logic to `SmartImportCustomizer`.

**Comment by lpandzic** [comment] 2020-03-18 07:39
Any idea when this might get resolved? JDK 14 doesn't work with current version of groovy specified in `spring-boot-dependencies`.

**Comment by dreis2211** [comment] 2020-03-18 07:45
@lpandzic Which version are you referring to? 2.5.10?
Apart from that the only thing missing here is a Spock release that aligns with Groovy 3.x. I have everything else ready.

**Comment by lpandzic** [comment] 2020-03-18 07:46
In Spring Boot 2.2.5.RELEASE groovy.version is 2.5.9

**Comment by dreis2211** [comment] 2020-03-18 07:48
The current snapshots of 2.3.0 build against 2.5.10, which enables (basic) JDK 14 support.

**Comment by snicoll** [comment] 2020-03-18 07:48
@lpandzic same conversation as the one we had recently on Gitter. `2.5.10` was released after Spring Boot `2.2.5`. We'll pick it up in due  course.

**Comment by jonathanlermitage** [comment] 2020-04-02 12:39
Switching to Groovy 3 would fix issues with some libraries like RestAssured (e.g. https://github.com/rest-assured/rest-assured/issues/1283#issuecomment-607814337)

**Comment by dreis2211** [comment] 2020-04-02 12:44
I wonder if there's a way forward without having a Spock release with Groovy 3 support.

**Comment by jonathanlermitage** [comment] 2020-04-02 12:50
Spock 2 Milestone 2 seems to support Groovy 3 

> [The latest 2.0 release version is 2.0-M2 (2.0-M2-groovy-2.5, 2.0-M2-groovy-3.0), released on 2019-12-31](https://github.com/spockframework/spock#latest-versions).

**Comment by dreis2211** [comment] 2020-04-02 12:54
I know - I'm talking about a proper release.

**Comment by snicoll** [comment] 2020-04-02 13:11
@jonathanlermitage I don't think Spring Boot is holding you up there. You can override the `groovy.version` property  to use Groovy 3.

**Comment by drewtwitchell** [comment] 2020-06-01 19:25
Has Spock been upgraded to leverage Groovy 3? Would love to see this fixed.

**Comment by dreis2211** [comment] 2020-06-01 19:29
No, unfortunately there is no release version of Spock with Groovy 3 support. There is only a milestone available. Like @snicoll mentioned before, for most use cases it's perfectly reasonable (and possible) to override the `groovy.version` property if you need it, @drewtwitchell .

**Comment by dreis2211** [comment] 2020-06-01 19:48
Maybe @szpak or any of the other members of the Spock team can shed some light on the release plans for a 2.0 GA release of Spock.

**Comment by szpak** [comment] 2020-06-01 20:23
Spock 2.0-M3 will be released "soon". Unfortunately. there is no schedule for GA.

Using Spock 1.3 with Groovy 3 is unsupported, but what's more important there is no simply way to run the non-SNAPSHOT version of Spock 1.3 with Groovy 3 due to the sanity check in Spock (many people using Spock 1.3-SNAPSHOT with Groovy 3 reports it generally works fine). I [implemented](https://github.com/spockframework/spock/pull/1164) a way to override that restriction in the future (e.g. for Groovy 4), but it will be available only in Spock 2.0-M3+.

**Comment by wilkinsona** [comment] 2021-01-19 16:58
Once we've upgraded, we should revert 452fbf3a3e48a9445f598cbdb4bb2df687c9b472 and upgrade REST Assured as well.

**Comment by dreis2211** [comment] 2021-01-19 17:03
Just to mention it once. Is it maybe an option to drop support for Spock? Or depend on the milestone releases? It's now blocking Groovy & REST Assured.

**Comment by wilkinsona** [comment] 2021-01-19 17:12
I was just typing the below when your comment popped up, @dreis2211.

I'm getting increasingly tempted to proceed with this as it feels a bit like the tail is wagging the dog at the moment. We don't have any public dependency management for Spock and we only have a `testImplementation` dependency on it (in `spring-boot-test`). Spock's milestones are published to Central so there's nothing technical stopping us from upgrading.

If we did upgrade to Groovy 3.0, users of Spock would have two choices:

1. Upgrade to the latest Spock 2.0 milestone
2. Stick with Spock 1.3 and downgrade Boot's Groovy version to 2.5.x.

Looking at the changes in the upgrade branch, only those in the CLI's `GroovyCompiler` would appear to require Groovy 3.0. I think we could probably live with that as the CLI controls its Groovy version anyway.

Let's see what the rest of the team thinks.

**Comment by philwebb** [comment] 2021-01-20 16:12
We've decided not to wait for Spock. @dreis2211 Are you interested in submitting a PR for this based on the work you've already done?

**Comment by dreis2211** [comment] 2021-01-20 16:16
Surely. But to get this straight: Should I upgrade Boot to Spock's Milestone or should I get rid of the few Spock internal usages?

**Comment by wilkinsona** [comment] 2021-01-20 16:18
Thank you. Upgrade to Boot to use Spock's latest 2.0 milestone please, Christoph. IIRC, the dependency is there to test that we detect Spock test annotations correctly when figuring out the context cache key. That's functionality that it would be good to keep if we can.

**Comment by dreis2211** [comment] 2021-01-20 16:20
Hence my question...I can't promise it this week still, but feel free to assign it to me. I'll provide something next week the latest.

**Comment by philwebb** [comment] 2021-01-20 16:58
There's no rush to get it into M1 from our side, we can merge it whenever.

**Comment by philwebb** [comment] 2021-01-20 18:23
Closing in favor of PR #24946

**Closed by philwebb** 2021-01-20 18:23 UTC
Labels: type: dependency-upgrade
