### ISSUE TITLE
[spring-boot 2.3.0] ResponseStatusException reason is ignored

### ISSUE THREAD

**Issue by pull-vert** [spring-projects/spring-boot#21496] opened 2020-05-18 19:33 UTC
I am using spring-webflux, and in some error cases I throw a ResponseStatusException using 2 parameters constructor : a HttpStatus and a reason (String).
Code is written in Kotlin

```kotlin
// NotFoundStatusException is simply a subclass of ResponseStatusException
internal class NotFoundStatusException(reason: String? = null) : ResponseStatusException(HttpStatus.NOT_FOUND, reason)

repository.findByName(name)
                    .switchIfEmpty { Mono.error(NotFoundStatusException("No Cow found for $name name")) }
```

An API integration test verify that JSON in this error case is correct
```kotlin
assertThat(error["message"] as String).isEqualTo("No Cow found for $name name")
```

This test is working fine with spring-boot 2.2.7, but this fails with spring-boot 2.3.0.

To reproduce, just clone my [demo-kotlin repository](https://github.com/pull-vert/demo-kotlin), all tests are passing because it is currently configured with spring-boot 2.2.7. Change spring_boot_plugin_version to 2.3.0.RELEASE in gradle.properties, now some tests are failing because message field in error JSON body is empty :
```
Expecting:
 <"">
to be equal to:
 <"No Cow found for no-name name">
but was not.
{"timestamp":"2020-05-18T19:28:19.060+00:00","path":"/api/cows/name/no-name","status":404,"error":"Not Found","message":"","requestId":"ffef802b-5"}
```

**Comment by scottfrederick** [comment] 2020-05-18 19:37
This is an intentional change in `2.3.0`. Please see the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content) for more information.

**Comment by scottfrederick** [comment] 2020-05-18 19:38
Duplicate of #21469

**Closed by scottfrederick** 2020-05-18 19:37 UTC
Labels: status: waiting-for-triage

**Comment by pull-vert** [comment] 2020-05-18 20:35
Thanks a lot !
