### ISSUE TITLE
When using Jetty, the JVM does not exit until Jetty's thread idle timeout has elapsed

### ISSUE THREAD

**Issue by Artur-** [spring-projects/spring-boot#26634] opened 2021-05-22 10:34 UTC
Not sure if this is a Spring Boot problem or a Vaadin problem but upgrading from Spring Boot 2.4.5 to 2.4.6 causes our integration tests to fail (https://github.com/vaadin/spring/issues/810) because the RMI port (9001) remains in use even after `spring-boot:stop` has executed. 

The server process seems to be left running:
```
61070 s018  S      0:13.03 /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/bin/java -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -cp lots-of-classes-here com.vaadin.flow.spring.scan.test.TestServletInitializer --spring.application.admin.enabled=true --spring.application.admin.jmx-name=org.springframework.boot:type=Admin,name=SpringApplication
```
and it only goes away after waiting for some time.

I cannot immediate see the reason for the server staying up from the Java stack trace or anything else.

It seems to reproduce with any of our test modules only by having
```
     <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>pre-integration-test</id>
                        <goals>
                            <goal>start</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>post-integration-test</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

and doing e.g. `mvn install`

Any ideas?

**Comment by Artur-** [comment] 2021-05-22 10:38
The same happens also with Spring Boot 2.5.0

**Comment by mbhave** [comment] 2021-05-24 20:47
@Artur- Nothing comes to mind immediately on what could have caused this. Could you provide a small sample application that we can run to reproduce the issue?

**Comment by spring-projects-issues** [comment] 2021-06-01 07:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-06-07 20:50
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by snicoll** [comment] 2021-06-10 06:24
@Artur- would you be able the sample application we've requested so that we can hopefully make progress here? Something might be preventing the server to stop and I really can't see what it could be, especially in a maintenance release.

**Comment by Artur-** [comment] 2021-06-10 07:03
I was not able to reproduce this in a standalone project. Only in https://github.com/vaadin/spring as described in https://github.com/vaadin/spring/issues/810.

**Comment by Artur-** [comment] 2021-06-11 12:23
I did a git bisect between spring boot `v2.4.5` and `v2.4.6` with the result

```
b6e860b2d431b104f47b20feae4c49c3446c3cb6 is the first bad commit
commit b6e860b2d431b104f47b20feae4c49c3446c3cb6
Author: Andy Wilkinson <wilkinsona@vmware.com>
Date:   Wed May 19 19:02:24 2021 +0100

    Prevent Jetty from delaying shutdown beyond grace period
    
    Fixes gh-22689
```

I also tried checking out `v2.4.7`, reverting `b6e860b2d431b104f47b20feae4c49c3446c3cb6` and that allows our test to pass

**Comment by wilkinsona** [comment] 2021-06-11 13:14
That's an odd one. Reducing the timeout should cause Jetty to shutdown more not less aggressively. Unfortunately, I don't think reverting b6e860b2 is a good option for us to make in Boot itself. Users can configure the timeout themselves so changing the default would just mask the problem rather than fixing it, leaving it lurking for anyone who tunes the timeout themselves.

I'd really like to understand why Jetty isn't shutting down as it should. To that end, I think we're really going to need some steps that we can follow that will reproduce the problem. @Artur- how difficult would it be for us to get things setup to run the relevant part of Vaadin's build (I think that's what the various `mvn` commands in https://github.com/vaadin/spring/issues/810 are doing) to reproduce the problem?

**Comment by Artur-** [comment] 2021-06-11 15:07
I tested it as follows using Java 8:
```
git clone git@github.com:vaadin/spring.git
cd spring
# edit pom.xml to change Spring Boot version to 2.4.6
mvn install -DskipTests 
```

It takes a while and fails in some of the test modules

**Comment by wilkinsona** [comment] 2021-06-11 16:44
Thanks, @Artur-.

The cause appears to be a bug in Jetty's `QueuedThreadPool`. With a stop timeout of zero it leaves its threads running. They'll eventually exit after 60 seconds which is the default idle timeout. With a stop timeout of just 1ms, the JVM exists nigh-on immediately. I've opened https://github.com/eclipse/jetty.project/issues/6400.

Let's see what the Jetty team say. If I've misunderstood how `QueuedThreadPool` should behave or a fix won't be available in time for the next Spring Boot release, we could change from 0ms to 1ms for the default stop timeout in Boot.

**Comment by wilkinsona** [comment] 2021-06-11 16:45
I've assigned this to 2.4.8 so that we don't forget to do something with it before our next release.

**Comment by wilkinsona** [comment] 2021-06-23 15:38
Jetty 9.4.43, to which we'll upgrade in due course, will fix the `QueuedThreadPool` problem. It doesn't look like it will be released in time for tomorrow's Boot releases, but, rather than changing the timeout in one release and changing it back again in the next, we recommend that anyone affected by the problem temporarily configures the workaround [described above](https://github.com/spring-projects/spring-boot/issues/26634#issuecomment-859709434).

**Closed by wilkinsona** 2021-06-23 15:38 UTC
Labels: status: blocked, status: on-hold, status: waiting-for-triage
