### ISSUE TITLE
In Spring Boot 3.0.3, component scanning does not work when application's path contains one or more spaces and it's not being run as an archive

### ISSUE THREAD

**Issue by lspil** [spring-projects/spring-boot#34379] opened 2023-02-25 06:48 UTC
Write any simple configuration class:

```
@Configuration
public class ProjectConfig {

  @Bean
  public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
    return http.build();
  }

  @Bean
  public String anyBean() {
    return "Test";
  }
}
```

Any of these beans are not created. If you add a breakpoint in the methods and start with debug you can see that they are not called at all.

However, adding a @Bean method in the Main class **works**:

```
@SpringBootApplication
public class Sb303IssueRepApplication {

  public static void main(String[] args) {
    SpringApplication.run(Sb303IssueRepApplication.class, args);
  }

  @Bean
  public String anyBean() {
    return "Test";
  }
}
```

This issue cannot be reproduced with 3.0.2.

**Comment by lspil** [comment] 2023-02-25 06:53
Here you have a simple project that reproduces the issue: https://github.com/lspil/youtubechannel/tree/master/sb303_issue_rep

**Comment by lspil** [comment] 2023-02-25 07:30
Also, here's a short unlisted video with my issue: https://www.youtube.com/watch?v=5pLtEWy7ByA

**Comment by maciejwalkowiak** [comment] 2023-02-25 07:51
@lspil I run the sample on both Java 19 and Java 17 and cannot reproduce this issue.

**Comment by dev-himanshu** [comment] 2023-02-25 11:03
Hi @wilkinsona , As you have suspected it's a Windows-specific problem related to component scanning, Is there any way to fix it at our end?

**Comment by wilkinsona** [comment] 2023-02-25 11:04
Thanks for trying the sample, @maciejwalkowiak. I too cannot reproduce the problem on macOS. My suspicion is that it's a Windows-specific problem as both @lspil and @dev-himanshu, are using Windows. What OS did you try on, @maciejwalkowiak?

@lspil Can you please run your application on the command line using Maven with trace level logging enabled:

```
mvnw spring-boot:run -Dspring-boot.run.jvmArguments=-Dlogging.level.org.springframework=trace
```

Please do this with both Spring Boot 3.0.2 and Spring Boot 3.0.3 and share the complete output of both runs. It would also be interesting to know if the problem occurs with Spring Boot 3.0.3 when you downgrade to Spring Framework 6.0.4. You can do so by adding `<spring-framework.version>6.0.4</spring-framework.version>` to the `<properties>` in your pom.xml.

**Comment by dev-himanshu** [comment] 2023-02-25 11:15
Hi @wilkinsona, 
I have tried but not working by using spring boot 3.0.3 with spring framework 6.0.4

**Comment by maciejwalkowiak** [comment] 2023-02-25 12:26
@wilkinsona on MacOS. Will give a try on Windows later this weekend.

**Comment by wilkinsona** [comment] 2023-02-25 14:56
I can reproduce the problem. Rather than being specific to Windows, it happens when the application's path contains a space, which is much more common on Windows than it is on other operating systems. The log output for #34380 shows multiple spaces in the path:

```
G:\Java\IntelliJ Workspace\Learning\Spring Boot By Raghu\Spring Boot Data\SpringBootDataJpaStoredProcedureEx\target\classes
```

I cannot reproduce the problem, even with a space in the application's path, when using Spring Boot 3.0.3 and Framework 6.0.4 @dev-himanshu, are you certain that your downgrade to Spring Framework 6.0.4 was effective?

**Comment by wilkinsona** [comment] 2023-02-25 15:00
It looks like it's a URL encoding problem:

```
14:58:42.632 [main] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Failed to complete search in directory [/Users/awilkinson/dev/temp/youtube%20channel/sb303_issue_rep/target/test-classes/com/example/sb303_issue_rep] for files matching pattern [*.class]: java.nio.file.NoSuchFileException: /Users/awilkinson/dev/temp/youtube%20channel/sb303_issue_rep/target/test-classes/com/example/sb303_issue_rep
```

Note the `%20` in the file's path. This looks like a regression introduced in https://github.com/spring-projects/spring-framework/commit/dbf360997aba5177775c231e473e1b0d8d8bcf06. We'll get the Framework team to take a look.

**Comment by wilkinsona** [comment] 2023-02-25 15:08
#30031 is already tracking this on the Framework side. Closing in favor of that issue. We'll pick up a new release of Framework that fixes the problem in due course.

**Closed by wilkinsona** 2023-02-25 15:08 UTC
Labels: status: waiting-for-triage

**Comment by dev-himanshu** [comment] 2023-02-25 17:48
> I can reproduce the problem. Rather than being specific to Windows, it happens when the application's path contains a space, which is much more common on Windows than it is on other operating systems. The log output for #34380 shows multiple spaces in the path:
> 
> ```
> G:\Java\IntelliJ Workspace\Learning\Spring Boot By Raghu\Spring Boot Data\SpringBootDataJpaStoredProcedureEx\target\classes
> ```
> 
> I cannot reproduce the problem, even with a space in the application's path, when using Spring Boot 3.0.3 and Framework 6.0.4 @dev-himanshu, are you certain that your downgrade to Spring Framework 6.0.4 was effective?

I am sure that downgrade to spring framework 6.0.4 was not effective in my case.

**Comment by rishiraj88** [comment] 2023-02-25 18:07
Thanks, @dev-himanshu

**Comment by wilkinsona** [comment] 2023-02-25 20:07
@dev-himanshu Was Framework 6.0.4 definitely on the classpath? If it was, you appear to have a different problem. It would be interesting to know if your application works when run from a location with no spaces in its path.

**Comment by Bob-Lennon** [comment] 2023-02-25 22:17
I had exactly the same problem with two Spring Boot 3.0.3 projects on Windows OS, I replaced all the spaces in the path with hyphens `C:\..\path-to-folder\..\project` and they both work fine now.

Like lspil said, I didn't have this problem on 3.0.2.

**Comment by lspil** [comment] 2023-02-26 06:14
Thanks everyone! You're such a great team! I love this community!

**Comment by dev-himanshu** [comment] 2023-02-26 06:18
> @dev-himanshu Was Framework 6.0.4 definitely on the classpath? If it was, you appear to have a different problem. It would be interesting to know if your application works when run from a location with no spaces in its path.

In Runner.java
```
package com.example.runners;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class Runner implements CommandLineRunner {
    @Override
    public void run(String... args) throws Exception {
        log.info("Runner execution started.");
        System.out.println("Runner is running.....");
        log.info("Runner execution completed.");
    }
}
```
Console Output:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.3)

2023-02-26T11:44:43.945+05:30  INFO 10112 --- [  restartedMain] c.example.SpringTestRunnerApplication    : Starting SpringTestRunnerApplication using Java 18.0.2.1 with PID 10112 (H:\SpringTestRunner\target\classes started by himan in H:\SpringTestRunner)
2023-02-26T11:44:43.951+05:30  INFO 10112 --- [  restartedMain] c.example.SpringTestRunnerApplication    : No active profile set, falling back to 1 default profile: "default"
2023-02-26T11:44:44.003+05:30  INFO 10112 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2023-02-26T11:44:44.523+05:30  INFO 10112 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2023-02-26T11:44:44.540+05:30  INFO 10112 --- [  restartedMain] c.example.SpringTestRunnerApplication    : Started SpringTestRunnerApplication in 1.326 seconds (process running for 3.046)
2023-02-26T11:44:44.542+05:30  INFO 10112 --- [  restartedMain] com.example.runners.Runner               : Runner execution started.
Runner is running.....
2023-02-26T11:44:44.542+05:30  INFO 10112 --- [  restartedMain] com.example.runners.Runner               : Runner execution completed.

Process finished with exit code 0
```
Hello @wilkinsona 
Yes, you are right. I tried with the no spaces path and its working
So, There is URL encoder issue only.

**Comment by wilkinsona** [comment] 2023-02-26 13:54
Thanks for the confirmation, @dev-himanshu.

**Comment by dev-himanshu** [comment] 2023-02-26 15:53
you're welcome @wilkinsona

**Comment by 123Haynes** [comment] 2023-02-27 16:51
This also happens if the path contains other chars like ## not only with spaces.
I ran into this because my application is named `frontend##3.0.0.war` so the tomcat manager recognizes the 3.0.0 as the version number.

**Comment by kamrankamilli** [comment] 2023-02-28 09:23
I have the same issue with spring boot 3.0.3 using Ubuntu, I'm not sure if it is specific to Windows. Previously I was using Spring Boot 3.0.2 and had no problems. Looks like spring not scanning for component.
`
//working
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@GetMapping("/hello")
    public String hello() {
        return "hello";
    }

}`

`//not working 
package com.example.demo.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {

    @GetMapping("/hello/hello")
    public String hello() {
        return "hello";
    }
}`

**Comment by kamrankamilli** [comment] 2023-02-28 09:35
I have the same issue with spring boot 3.0.3 using Ubuntu, I'm not sure if it is specific to Windows. Previously I was using Spring Boot 3.0.2 and had no problems. Looks like spring is not scanning for components.


```
//Working
package com.example.demo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@GetMapping("/hello")
	public String hello() {
		return "hello";
	}

}



//Not working no mapping 404

package com.example.demo.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {

    @GetMapping("/hello/hello")
    public String hello() {
        return "hello";
    }
}

**Comment by wilkinsona** [comment] 2023-02-28 09:49
@kamrankamilli As described in the existing comments on this issue, the problem is not specific to Windows. It will affect an application on any OS when there are characters in its path that are encoded when included in a URL. Spaces are probably the most common.

**Comment by kamrankamilli** [comment] 2023-02-28 09:58
@wilkinsona Yeah I had space in my project folder name, now it is working thanks

**Comment by jruedas1** [comment] 2023-03-01 20:15
Hi everyone, I had this problem on Mac OS in 3.0.3 vs 3.0.2, getting 404 when I have a slash in the path, here are some details.

**Comment by jruedas1** [comment] 2023-03-01 20:15
Using a super simple controller

**Comment by jruedas1** [comment] 2023-03-01 20:18
When I regress to version 3.0.2, the problem is not there
Here are the corresponding logs:
`2023-03-01T13:47:27.578-06:00 DEBUG 1522 --- [o-8080-Acceptor] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-8080-Acceptor] latch=1
2023-03-01T13:47:27.599-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.coyote.http11.Http11InputBuffer      : Before fill(): parsingHeader: [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position(): [0], byteBuffer.limit(): [0], end: [0]
2023-03-01T13:47:27.600-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6a921077:org.apache.tomcat.util.net.NioChannel@1a933c66:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8080 remote=/127.0.0.1:49760]], Read from buffer: [0]
2023-03-01T13:47:27.600-06:00 DEBUG 1522 --- [nio-8080-exec-1] org.apache.tomcat.util.net.NioEndpoint   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6a921077:org.apache.tomcat.util.net.NioChannel@1a933c66:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8080 remote=/127.0.0.1:49760]], Read direct from socket: [639]
2023-03-01T13:47:27.600-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.coyote.http11.Http11InputBuffer      : Received [GET /hello HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: Idea-342842ef=a28fef40-f970-418e-a243-0f98617a3455; _octo=GH1.1.1565316306.1670356781; Webstorm-9f03f5b7=a18d96f9-89d7-44df-862b-d843b374dc36; _ga=GA1.1.1880333784.1676404539
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1

]
2023-03-01T13:47:27.611-06:00 DEBUG 1522 --- [nio-8080-exec-1] org.apache.tomcat.util.http.Parameters   : Set query string encoding to UTF-8
2023-03-01T13:47:27.612-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.t.util.http.Rfc6265CookieProcessor   : Cookies: Parsing b[]: Idea-342842ef=a28fef40-f970-418e-a243-0f98617a3455; _octo=GH1.1.1565316306.1670356781; Webstorm-9f03f5b7=a18d96f9-89d7-44df-862b-d843b374dc36; _ga=GA1.1.1880333784.1676404539
2023-03-01T13:47:27.614-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.c.authenticator.AuthenticatorBase    : Security checking request GET /hello
2023-03-01T13:47:27.614-06:00 DEBUG 1522 --- [nio-8080-exec-1] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2023-03-01T13:47:27.616-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.c.a.jaspic.AuthConfigFactoryImpl     : Loading persistent provider registrations from [/private/var/folders/xn/x2z1qzds6jl_d31jdwtnyz3r0000gn/T/tomcat.8080.5933864671982932482/conf/jaspic-providers.xml]
2023-03-01T13:47:27.616-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.c.authenticator.AuthenticatorBase    : Not subject to any constraint
2023-03-01T13:47:27.618-06:00  INFO 1522 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-03-01T13:47:27.618-06:00  INFO 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-03-01T13:47:27.618-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Detected StandardServletMultipartResolver
2023-03-01T13:47:27.618-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Detected AcceptHeaderLocaleResolver
2023-03-01T13:47:27.618-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Detected FixedThemeResolver
2023-03-01T13:47:27.618-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Detected org.springframework.web.servlet.view.DefaultRequestToViewNameTranslator@74d35c00
2023-03-01T13:47:27.619-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Detected org.springframework.web.servlet.support.SessionFlashMapManager@291959c6
2023-03-01T13:47:27.619-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : enableLoggingRequestDetails='false': request parameters and headers will be masked to prevent unsafe logging of potentially sensitive data
2023-03-01T13:47:27.619-06:00  INFO 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-03-01T13:47:27.623-06:00 DEBUG 1522 --- [nio-8080-exec-1] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2023-03-01T13:47:27.624-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : GET "/hello", parameters={}
2023-03-01T13:47:27.631-06:00 DEBUG 1522 --- [nio-8080-exec-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to com.example.demo4.controllers.WelcomeController#sayHello()
2023-03-01T13:47:27.644-06:00 DEBUG 1522 --- [nio-8080-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Using 'text/html', given [text/html, application/xhtml+xml, image/avif, image/webp, application/xml;q=0.9, */*;q=0.8] and supported [text/plain, */*, application/json, application/*+json]
2023-03-01T13:47:27.645-06:00 DEBUG 1522 --- [nio-8080-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Writing ["hello"]
2023-03-01T13:47:27.649-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed 200 OK
2023-03-01T13:47:27.650-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.coyote.http11.Http11InputBuffer      : Before fill(): parsingHeader: [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position(): [0], byteBuffer.limit(): [0], end: [639]
2023-03-01T13:47:27.650-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6a921077:org.apache.tomcat.util.net.NioChannel@1a933c66:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8080 remote=/127.0.0.1:49760]], Read from buffer: [0]
2023-03-01T13:47:27.650-06:00 DEBUG 1522 --- [nio-8080-exec-1] org.apache.tomcat.util.net.NioEndpoint   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6a921077:org.apache.tomcat.util.net.NioChannel@1a933c66:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8080 remote=/127.0.0.1:49760]], Read direct from socket: [0]
2023-03-01T13:47:27.650-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.a.coyote.http11.Http11InputBuffer      : Received []
2023-03-01T13:47:27.650-06:00 DEBUG 1522 --- [nio-8080-exec-1] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6a921077:org.apache.tomcat.util.net.NioChannel@1a933c66:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8080 remote=/127.0.0.1:49760]], Status in: [OPEN_READ], State out: [OPEN]
2023-03-01T13:47:27.650-06:00 DEBUG 1522 --- [nio-8080-exec-1] org.apache.tomcat.util.net.NioEndpoint   : Registered read interest for [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@6a921077:org.apache.tomcat.util.net.NioChannel@1a933c66:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8080 remote=/127.0.0.1:49760]]
2023-03-01T13:47:46.247-06:00 DEBUG 1522 --- [(3)-10.10.49.20] sun.rmi.transport.tcp                    : RMI TCP Connection(3)-10.10.49.20: (port 49755) connection closed
2023-03-01T13:47:46.247-06:00 DEBUG 1522 --- [(3)-10.10.49.20] sun.rmi.transport.tcp                    : RMI TCP Connection(3)-10.10.49.20: close connection, socket: Socket[addr=/10.10.49.20,port=49759,localport=49755]
2023-03-01T13:47:46.247-06:00 DEBUG 1522 --- [(3)-10.10.49.20] sun.rmi.transport.tcp                    : RMI TCP Connection(3)-10.10.49.20: socket close: Socket[addr=/10.10.49.20,port=49759,localport=49755]
`

**Comment by jruedas1** [comment] 2023-03-01 20:20
In version 3.0.3 when I remove the slash from the GetMapping path, the problem is resolved. This works just fine in 3.0.3:
`@RestController
public class WelcomeController {

    @GetMapping(path = "hello")
    public String sayHello(){
        return "hello";
    }
}`

**Comment by jruedas1** [comment] 2023-03-01 20:21
Hope this helps identify and resolve the issue

**Comment by wilkinsona** [comment] 2023-03-01 20:29
@jruedas1 Thanks, but that appears to be a different problem. This issue is about having a space or other character that would be URL encoded in the path on the file system from which the application is running. It's unrelated to paths in `@GetMapping` annotations. If you believe you've found a bug there, please open a [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues).

**Comment by HerNidza** [comment] 2023-03-01 22:02
Any luck fixing issue on 3.0.3 ? 
On 3.0.2 works perfectly

**Comment by 123Haynes** [comment] 2023-03-01 22:08
> Any luck fixing issue on 3.0.3 ? On 3.0.2 works perfectly

@HerNidza You can downgrade the spring Framework to 6.0.4 and still use spring-boot 3.0.3 until this is fixed.
Simply add the property 
`<spring-framework.version>6.0.4</spring-framework.version>`

**Comment by HerNidza** [comment] 2023-03-01 22:10
@123Haynes Awesome!

Thanks a lot!

**Comment by philwebb** [comment] 2023-03-03 22:15
For anyone watching this issue, we've just done an earlier than scheduled 3.0.4 release to specifically address this regression. Please upgrade.

**Comment by dev-himanshu** [comment] 2023-03-04 08:00
> For anyone watching this issue, we've just done an earlier than scheduled 3.0.4 release to specifically address this regression. Please upgrade.
Hi @philwebb, thanks for the update in that issue. I have tried with latest release of 3.0.4 and now working fine.
