### ISSUE TITLE
Breaking change of transaction autoconfiguration in 2.7.6

### ISSUE THREAD

**Issue by vlastikcz** [spring-projects/spring-boot#33430] opened 2022-12-01 10:28 UTC
Spring Boot 2.7.6 introduced a breaking change in the autoconfiguration order/priority, which makes it behave differently to 2.7.5. More precisely, the `JdbcTransactionAutoconfiguration`/`DataSourceTransactionManager` precedence was changed.

In our case, the `JdbcTransactionAutoconfiguration` is initialized in 2.7.6, but 2.7.5 initializes `JpaTransactionAutoconfiguration`.

I think a patch version should not introduce a potentially breaking change like this.

This change was probably introduced here: https://github.com/spring-projects/spring-boot/commit/4bb13bcdfd5af5f33841e9f53055e4b2fd5d59aa

**Comment by barryspearce** [comment] 2022-12-27 23:12
Having just migrated from 2.7.3 to 3.0.0 some of my integration tests are now failing due to database isolation issues, despite @Transactional being on the test class.

I suspect this issue might be the cause of the difference.

My Integration test declares the following in this order:

@SpringBootTest
@AutoConfigureTestDatabase
@AutoConfigureDataJpa
@AutoConfigureTestEntityManager
@EnableAutoConfiguration
@EnableJpaAuditing
@EntityScan
@EnableJpaRepositories
@ComponentScan
@Transactional

Whereas before the Integration tests worked, they now fail with index failures on inserts - which has been caused by a failure to rollback the transaction properly between tests.

Perhaps this is related?

**Comment by izanaj** [comment] 2023-01-25 13:27
I think I have reached in the same issue, some integration tests are failing since from tests I try to delete some data during and than endpoint.

The data after deletion is still there even though the method is annotated with @Transactional(propagation = Propagation.REQUIRES_NEW).

The method does not fail so no exception happens but it looks like the change is not committed.

Did you discover any workaround?

**Comment by vlastikcz** [comment] 2023-01-26 16:38
A workaround would be manual transaction manager initialization.

Over the time, I was trying to figure out the repro steps, but I was not successful. It just happens only with some of our projects, and I do not know why, unfortunately.

**Comment by spring-projects-issues** [comment] 2023-03-06 14:22
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-03-13 14:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-03-13 14:22 UTC
Labels: type: regression, status: waiting-for-feedback, status: feedback-reminder
