### ISSUE TITLE
TCP connections is growing unless restart

### ISSUE THREAD

**Issue by hcl78184889** [spring-projects/spring-boot#22413] opened 2020-07-20 14:11 UTC
TCP connections is growing unless restart when using Spring Cloud Gateway. 
I think the issue is springboot or netty reacter. 

spring boot 2.3 is growing fleetly.

Could you help me, thanks.
Refer below img,
![gateway各版本TCP链接数曲线-标注](https://user-images.githubusercontent.com/6574953/87946960-43a5b700-cad5-11ea-898c-c133e9ce2382.png)

**Comment by bclozel** [comment] 2020-07-20 14:16
Closing as a duplicate of #21923

**Closed by bclozel** 2020-07-20 14:16 UTC
Labels: status: waiting-for-triage
