### ISSUE TITLE
Caused by: java.io.FileNotFoundException: ReactiveWebContext resource [xxx.properties] cannot be opened because it does not exist

### ISSUE THREAD

**Issue by dbacinski** [spring-projects/spring-boot#9244] opened 2017-05-16 11:26 UTC
In version of Spring Boot 20170516.070255-627 / 2.0.0.M1 there was introduced regression in properties files handling.

I have a project with multiple properties files aggregated from Gradle modules:

```
@SpringBootApplication(scanBasePackages = arrayOf("com.example"),
        exclude = arrayOf(DataSourceAutoConfiguration::class, JooqAutoConfiguration::class))
@PropertySource("xxx.properties", "yyy.properties", "zzz.properties", "application.properties")
class FacadeApplication

fun main(args: Array<String>) {
    SpringApplication.run(FacadeApplication::class.java, *args)
}
```
build.gradle:
```
dependencies {
    compile project(':xxx')
    compile project(':yyy')
    compile project(':zzz')
}
```
Now when i start application I am getting an exception `Caused by: java.io.FileNotFoundException: ReactiveWebContext resource [xxx.properties] cannot be opened because it does not exist`. It seams that xxx.properties, yyy.properties, zzz.properties are not bundled into app.

Full exception:
```
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext@2e55dd0c: startup date [Tue May 16 13:07:10 CEST 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:413) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:233) ~[spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:951) [spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:958) [spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1032) [spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555) [spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:49) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:795) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1278) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at info.stsa.facade.MaintenanceFacadeApplicationKt.main(MaintenanceFacadeApplication.kt:15) [main/:?]
ERROR 2017-05-16 13:07:11.171 thread=1   org.springframework.boot.SpringApplication  - Application startup failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [info.stsa.facade.MaintenanceFacadeApplication]; nested exception is java.io.FileNotFoundException: ReactiveWebContext resource [maintenance.properties] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:182) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:308) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:49) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:795) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1278) [spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at info.stsa.facade.MaintenanceFacadeApplicationKt.main(MaintenanceFacadeApplication.kt:15) [main/:?]
Caused by: java.io.FileNotFoundException: ReactiveWebContext resource [xxx.properties] cannot be opened because it does not exist
	at org.springframework.boot.web.reactive.context.GenericReactiveWebApplicationContext$FilteredReactiveWebContextResource.getInputStream(GenericReactiveWebApplicationContext.java:99) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:154) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:98) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:72) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:58) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:65) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.core.io.support.DefaultPropertySourceFactory.createPropertySource(DefaultPropertySourceFactory.java:36) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:449) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:272) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:246) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:168) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	... 13 more
```

Broken version:
```
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/2.0.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-2.0.0.BUILD-20170516.070255-627.pom
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-tools/2.0.0.BUILD-SNAPSHOT/spring-boot-tools-2.0.0.BUILD-20170516.070255-626.pom
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-parent/2.0.0.BUILD-SNAPSHOT/spring-boot-parent-2.0.0.BUILD-20170516.070255-627.pom
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-dependencies/2.0.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.0.0.BUILD-20170516.070255-627.pom
```

Was working with:
```
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-gradle-plugin/2.0.0.BUILD-SNAPSHOT/spring-boot-gradle-plugin-2.0.0.BUILD-20170516.001457-626.pom
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-tools/2.0.0.BUILD-SNAPSHOT/spring-boot-tools-2.0.0.BUILD-20170516.001457-625.pom
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-parent/2.0.0.BUILD-SNAPSHOT/spring-boot-parent-2.0.0.BUILD-20170516.001457-626.pom
Download https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-dependencies/2.0.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.0.0.BUILD-20170516.001457-626.pom
```

**Comment by dbacinski** [comment] 2017-05-16 12:03
The same error occurs when i use `classpath:` prefix

```
@SpringBootApplication(scanBasePackages = arrayOf("com.example"),
        exclude = arrayOf(DataSourceAutoConfiguration::class, JooqAutoConfiguration::class))
@PropertySource("classpath:xxx.properties", "classpath:yyy.properties", "classpath:zzz.properties", "classpath:application.properties")
class MaintenanceFacadeApplication

fun main(args: Array<String>) {
    SpringApplication.run(MaintenanceFacadeApplication::class.java, *args)
}
```

Property files are also missing in `build/resources/main` but the one for test are there in `build/resources/test`

**Comment by wilkinsona** [comment] 2017-05-16 12:04
As discussed on Gitter this isn't a regression, but an intentional side-effect of the fix for https://github.com/spring-projects/spring-boot/issues/8485. By not saying where you expected the properties file to be loaded (classpath, file system, etc) you we relying on `GenericReactiveWebApplicationContext` loading all paths via the classpath. This is differs from a servlet-based web application which only loads paths via the servlet context. It also had the unwanted side-effect of exposing all of the application over HTTP.

Loading properties from the classpath with the `classpath:` prefix should work. If it does not, please provide a small sample application that reproduces the behaviour you are seeing.

**Comment by dbacinski** [comment] 2017-05-16 13:06
I have mange to reproduce this error in sample app:
https://github.com/dbacinski/spring-boot-issue-9244

**Comment by dsyer** [comment] 2017-05-16 13:22
Your "xxx" library is a Spring Boot app (executable jar). You probably need to just remove the Spring Boot plugin (or configure it differently so that you get a library jar as well as the executable one).

**Comment by bclozel** [comment] 2017-05-16 13:24
Just tried your sample — it works both from the command line and my IDE.
The application starts and the root endpoint returns "It works" to my browser.

But also: what @dsyer said. Issue #9242 explains a bit why this is a problem.

**Comment by bclozel** [comment] 2017-05-16 13:29
Scratch that - your sample depends on 2.0 SNAPSHOT, not the milestone.
Depending on the milestone does reproduce the issue.

But it just points to what @dsyer said and #9242, as the build log shows:

```
:xxx:compileJava
:xxx:copyMainKotlinClasses
:xxx:processResources
:xxx:classes
:xxx:jar SKIPPED
```

**Comment by dbacinski** [comment] 2017-05-16 13:50
@bclozel you probably had cached snapshots from yesterday, SNAPSHOT and M1 is pointing to the same version now

**Comment by dbacinski** [comment] 2017-05-16 14:19
https://github.com/dbacinski/spring-boot-issue-9244/pull/1/files this is how i have fixed sample app now I will try with my project. Thanks for support.

**Comment by bclozel** [comment] 2017-05-16 14:47
Happy to see everything works now.
Closing this as a duplicate of #9242

**Closed by bclozel** 2017-05-16 14:47 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by dbacinski** [comment] 2017-05-17 06:32
I have also manage to fix my project. Thank you!
