### ISSUE TITLE
@MockBean on feign client is not working

### ISSUE THREAD

**Issue by hikaru-shindo** [spring-projects/spring-boot#22229] opened 2020-07-06 09:20 UTC
The update to 2.2.7 seems to have broken the support of MockBean for interfaces it seems.

I tried mocking a Feign client with MockBean but the real Feign client is used instead of my mock, so the test fails.

I have create a sample project showcasing the issue with springmockk (which ported this change) and mockito: https://github.com/hikaru-shindo/springmokk-mockkbean-feign-error-example

Downgrading springmockk to 2.0.1 (not part of THIS report) and Spring Boot to 2.2.6 (for mockito test) will make the tests pass.

My [bug report to springmockk ](https://github.com/Ninja-Squad/springmockk/issues/43) suggests the problematic change is in https://github.com/spring-projects/spring-boot/commit/b9c2b7b257c0f36ee489fcc2cabda2c17cc19908.

**Comment by wilkinsona** [comment] 2020-07-06 10:04
Thanks for the report. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/21379. It should have been fixed by https://github.com/spring-cloud/spring-cloud-openfeign/issues/337.

**Closed by wilkinsona** 2020-07-06 10:04 UTC
Labels: status: waiting-for-triage
