### ISSUE TITLE
DataSourceHealthIndicator need timeout 

### ISSUE THREAD

**Issue by bohrqiu** [spring-projects/spring-boot#4391] opened 2015-11-05 07:54 UTC
for the  business function，we will set database timeout(get connent form pool time out or exec query wait time out  ) very long ,but  It's not appropriate for HealthIndicator. in HealthIndicator，We just check whether the connection is available. so we should add timeout for HealthIndicator,as DataSourceHealthIndicator an example 

https://gist.github.com/bohrqiu/094e6e22a56b684fcec8

**Comment by bohrqiu** [comment] 2015-11-05 08:01
We'd better add timeout on `org.springframework.boot.actuate.health.AbstractHealthIndicator#health` method，all  HealthIndicator can timeout

**Comment by philwebb** [comment] 2018-07-27 15:33
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by philwebb** [comment] 2018-07-27 15:33
It's also worth noting that as of 2.0 there is caching with health endpoints and the option of a custom TTL

**Closed by philwebb** 2018-07-27 15:33 UTC
Labels: type: enhancement

**Comment by kostellodon** [comment] 2022-05-25 16:02
Sorry, don't know the etiquette, if leaving a comment here vs creating a new issue is preferred. This is something that we need. We have a spring boot app deployed to a container (cloud foundry) that gets intermittent health check failures due to the endpoint not responding. We see no exceptions in our logs, so I'm assuming one of the health check components is taking too long to respond, but we have no way of knowing which one. Having a timeout on the health check indicators would help us track down what is causing our intermittent failures.

**Comment by philwebb** [comment] 2022-06-01 19:35
@kostellodon Timeout support is going to be quite hard for us to implement, but your use-case makes me think that we should try to improve our logging. I've opened #31231 to track that.

**Comment by philwebb** [comment] 2024-12-04 19:57
Understood, but we still don't have an easy to implement timeout support I'm afraid.

**Comment by yassenb** [comment] 2024-12-05 07:49
I'm not familiar enough with Spring internals to open a PR but where is the complication in implementing it for `DataSourceHealthIndicator`. If I'm not missing anything in the method
```java
private Boolean isConnectionValid(Connection connection) throws SQLException {
	return connection.isValid(0);
}
```
all that's needed is to replace the `0` with something configurable, something in the lines of `management.endpoint.health.db.timeout` for the configuration path

**Comment by philwebb** [comment] 2024-12-06 22:11
Perhaps it's not as hard as I feared. Some vendors seem to ignore the timeout, but it looks like MySQL and Postgres support it. We'll discuss this on a team call and decide what to do.

**Comment by philwebb** [comment] 2024-12-09 18:04
@yassenb We talks about this on our team call and other members of the team reminded me why we didn't go down the `connection.isValid(timeout)` route. The problem is that we also support [the use of a validation query](https://github.com/spring-projects/spring-boot/blob/565ec07046f3e7ab73cdba3c28006465ebbec710/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/jdbc/DataSourceHealthIndicator.java#L107) and the JDBC API doesn't offer a timeout for calling that.

That leaves us back with the idea of running the health indicator in a background thread so we can offer a timeout. It seems like there is demand for that, and it's a more general problem than just datasource health indicators. I've opened #43449 to see what we can do.

**Comment by philwebb** [comment] 2024-12-12 20:37
Interesting, it looks like I missed that `java.sql.Statement` also supports a timeout (although only in seconds). The code in `DataSourceUtils.applyTimeout(...)` is used by `JdbcTemplate`.
