### ISSUE TITLE
YamlPropertiesFactoryBean getObject() ignores the active profile data and returns incorrect profile's data

### ISSUE THREAD

**Issue by edward0001** [spring-projects/spring-boot#7429] opened 2016-11-20 17:36 UTC
I am experiencing an issue, using **YamlPropertiesFactoryBean** to get the Properties object. 
I have 3 profiles configured in the application.yaml file. 
One of them is set as the active (profile2).

**Server.java**
`YamlPropertiesFactoryBean yaml = new  YamlPropertiesFactoryBean();`
`yaml.setResources(new ClassPathResource("/config/application.yaml"));`
`yaml.getObject();`

**application.yaml** file
```
spring:
  profiles:
    active: profile2
---
spring:
  profiles: profile1
dev:
  datasource:
    url:  jdbcUrl...   
    username: profile1DevUsername
    password: profile1DevPassword
prod:
  datasource:
    url: jdbcUrl...
    username: profile1ProdUsername
    password: profile1ProdPassword
---
spring:
  profiles: profile2
dev:
  datasource:
    url: jdbcUrl
    username: profile2DevUsername
    password: profile2DevPassword
prod:
  datasource:
    url: jdbcUrl
    username: profile2ProdUsername
    password: profile2ProdPassword
---
spring:
  profiles: profile3
dev:
  datasource:
    url: jdbcUrl
    username: profile3DevUsername
    password: profile3DevPassword
prod:
  datasource:
    url: jdbcUrl
    username: profile3ProdUsername
    password: profile3ProdPassword

```
Though the active profile has been set to **profile2**, **yaml.getObject()** returns me the data of the last profile, specified in the file. (in this case it is **profile3**, but this is true for profile2, when it is in the end of the list).
The rest of the data, placed after profiles (in the global scope) is being displayed correctly. 

P.S. The same thing is about YamlMapFactoryBean

**Comment by snicoll** [comment] 2016-11-20 23:21
Nothing in the contract of `YamlPropertiesFactoryBean` can you make believe that the profile value is actually taken into account. Because it doesn't, it's sole purpose is to parse the yaml structure and return a `Properties` object (see class javadoc).

Can we take a step back and discuss what you're trying to do?

**Comment by edward0001** [comment] 2016-11-21 06:55
You are right.
1. Isn't YamlPropertiesFactoryBean supposed to return the data of the entire application.yaml then? 
2. I need to set server specific configurations depending not just on the environment type (dev/prod), but on the server type itself. Server type is profile and the environment is a separate field in the global scope.
P.S. Thank you for your fast reply

**Comment by snicoll** [comment] 2016-11-21 16:12
I haven't tried for 1 yet, that looks suspicious.

2 doesn't tell me why you need to use that class in your own code. Can you please elaborate why you need to read `application.yml` yourself? IMO, this is wrong and you should use `EnvironmentPostProcesor` instead.

**Comment by edward0001** [comment] 2016-11-22 15:13
I receive an exception on attempt to resolve dataSource parameters, which are configured in application.yml. No wonder, since there are multiple dataSources configured in yml, when the system expects only one set of properties, depending on the parameters, stored in the same application.yml. 

I'd use `Environment`, but the exception is being thrown before the injection occurs, so this class is always null. 
Thus, I've reached the point, that I have to read application.yml manually and set the necessary properties by my own. 
I'd be very glad, if you'd offer me any better solution, because the one I'm using does not suit me and imo either is not correct. 
Thanks

**Comment by snicoll** [comment] 2016-11-22 15:54
What exception? You can have multiple data source parameters. `EnvironmentPostProcesssor` is invoked before injection. Please don't assume something may or may not work.

It looks quite obvious that there isn't a Spring Boot bug here so I am closing this issue. I'd advise to create a stackoverflow thread with a sample that reproduces what you're trying to do. Feel free to add the link here for reference. I'll certainly have a look to that once it's available.

**Closed by snicoll** 2016-11-22 15:54 UTC
Labels: feedback-provided

**Comment by edward0001** [comment] 2016-11-22 16:24
If `YamlPropertiesFactoryBean` is supposed to return the data of the entire application.yaml, then it does not, in my case. 
Its method **getObject()** returns the data of the last profile only. 

Thank you for your time anyway.

**Comment by snicoll** [comment] 2016-11-22 17:17
It's not. Check `YamlPropertySourceLoader`
