### ISSUE TITLE
get error messag Could not fetch the SequenceInformation from the database, hibernate_sequence doesn't exist

### ISSUE THREAD

**Issue by zhyhang** [spring-projects/spring-boot#16586] opened 2019-04-17 06:43 UTC
- upgrade from 2.2.0.M1 to 2.2.0.M2
- datasource: mariadb10.3.13
- dependency:spring-boot-starter-data-jpa
- got the error message, when starting:

```
2019-04-17 13:11:03.372 ERROR 11884 --- [main] o.h.e.j.e.internal.JdbcEnvironmentImpl   : Could not fetch the SequenceInformation from the database ava.sql.SQLSyntaxErrorException: (conn=1878197) Table 'asd.hibernate_sequence_1' doesn't exist
    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)
    at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
    at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
    at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:501)
    at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorMariaDBDatabaseImpl.extractMetadata(SequenceInformationExtractorMariaDBDatabaseImpl.ja va:73)
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl.sequenceInformationList(JdbcEnvironmentImpl.java:403)
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl.(JdbcEnvironmentImpl.java:268)
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:114)
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
    at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
    at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
    at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
    at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.(InFlightMetadataCollectorImpl.java:175)
    at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:118)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:900)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:931)
    at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1841)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:404)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
    at com.ipinyou.optimus.asd.AsdApplication.main(AsdApplication.java:15)
Caused by: java.sql.SQLException: Table 'asd.hibernate_sequence_1' doesn't exist
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:227)
    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:321)
    ... 39 common frames omitted
```
- jdbc current database is **asd** not contains the table **hibernate_sequence_1** which in database **test"

**Comment by zhyhang** [comment] 2019-04-17 07:03
degrade hibernate 5.4.2 to 5.4.0, eliminate the error.

**Comment by wilkinsona** [comment] 2019-04-17 07:34
Thanks for the report. Given that it works with Hibernate 5.4.0 but fails with Hibernate 5.4.2, your problem would appear to be due to a change in Hibernate. It's not clear if the change in Hibernate is a bug or something that has caused some misconfiguration to start causing a failure. If you believe the problem is caused by Spring Boot's configuration of Hibernate and you would like us to spend some time investigating, please provide a complete and minimal sample that reproduces the problem as a zip attached to this issue or in a separate GitHub repository.

**Comment by zhyhang** [comment] 2019-04-17 07:48
I reviewed the hibernate code, the problem certainly caused by hibernate not Spring Boot's configuration.

**Comment by zhyhang** [comment] 2019-04-17 08:10
**mariadb server:**
```bash
MariaDB [(none)]> select table_schema,table_name from information_schema.TABLES where table_type='SEQUENCE';
+--------------+----------------------+
| table_schema | table_name           |
+--------------+----------------------+
| test         | hibernate_sequence_1 |
| mdb          | hibernate_sequence   |
+--------------+----------------------+
```

**current connect to database is _asd_, but where not existing tables like hibernate_sequence**

the hibernate class **SequenceInformationExtractorMariaDBDatabaseImpl** using above sql query two tales in other databases. Then execute following sql, we got the error message:
```sql
select
    'hibernate_sequence_1' as sequence_name,
    minimum_value,
    maximum_value,
    start_value,
    increment,
    cache_size
from
    hibernate_sequence_1
union all
select
    'hibernate_sequence' as sequence_name,
    minimum_value,
    maximum_value,
    start_value,
    increment,
    cache_size
from
    hibernate_sequence
```
**related codes in class SequenceInformationExtractorMariaDBDatabaseImpl:**
```java
	@Override
	public Iterable<SequenceInformation> extractMetadata(ExtractionContext extractionContext) throws SQLException {
		final String lookupSql = extractionContext.getJdbcEnvironment().getDialect().getQuerySequencesString();

		// *should* never happen, but to be safe in the interest of performance...
		if (lookupSql == null) {
			return SequenceInformationExtractorNoOpImpl.INSTANCE.extractMetadata(extractionContext);
		}

		final IdentifierHelper identifierHelper = extractionContext.getJdbcEnvironment().getIdentifierHelper();

		final List<SequenceInformation> sequenceInformationList = new ArrayList<>();
		final List<String> sequenceNames = new ArrayList<>();

		try (
				final Statement statement = extractionContext.getJdbcConnection().createStatement();
				final ResultSet resultSet = statement.executeQuery( lookupSql );
		) {
			while ( resultSet.next() ) {
				sequenceNames.add( resultSetSequenceName( resultSet ) );
			}
		}

		if ( !sequenceNames.isEmpty() ) {
			StringBuilder sequenceInfoQueryBuilder = new StringBuilder();

			for ( String sequenceName : sequenceNames ) {
				if ( sequenceInfoQueryBuilder.length() > 0 ) {
					sequenceInfoQueryBuilder.append( UNION_ALL );
				}
				sequenceInfoQueryBuilder.append( String.format( SQL_SEQUENCE_QUERY, sequenceName ) );
			}

			int index = 0;

			try (
					final Statement statement = extractionContext.getJdbcConnection().createStatement();
					final ResultSet resultSet = statement.executeQuery( sequenceInfoQueryBuilder.toString() );
			) {

				while ( resultSet.next() ) {

					SequenceInformation sequenceInformation = new SequenceInformationImpl(
						new QualifiedSequenceName(
								null,
								null,
								identifierHelper.toIdentifier(
										resultSetSequenceName(resultSet)
								)
						),
						resultSetStartValueSize(resultSet),
						resultSetMinValue(resultSet),
						resultSetMaxValue(resultSet),
						resultSetIncrementValue(resultSet)
					);

					sequenceInformationList.add(sequenceInformation);
				}

			}
		}

		return sequenceInformationList;
	}
```

**Comment by wilkinsona** [comment] 2019-04-17 08:20
Thanks for the analysis. Please report the problem to the Hibernate team via their [issue tracker](https://hibernate.atlassian.net/browse/HHH) and comment here with a link to the issue. I'll close this one for now as I don't think there's anything to do in Spring Boot. If it turns out that a change in Spring Boot is needed we can re-open this issue.

**Closed by wilkinsona** 2019-04-17 08:20 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by zhyhang** [comment] 2019-04-17 08:42
hibernate issue tracker url:
https://hibernate.atlassian.net/browse/HHH-13373
