### ISSUE TITLE
spring-boot-maven-plugin: support two different registries for builder and runImage when one of them is authenticated

### ISSUE THREAD

**Issue by pgalache** [spring-projects/spring-boot#26759] opened 2021-06-04 12:20 UTC
Currently the `spring-boot-maven-plugin` requires that both builder and runImage registries are the same in case authentication has to be set (`docker.builderRegistry` parameters ), as the authentication is applied for both.

A reasonable use case is that one of the images needs to be customized, for example, to add an application specific runtime dependency. In that case, the runImage could  extend the default runImage  and probably would have to be  pushed to an internal registry of the organization, which will require authentication. But still want to use the builder image from the community, which is in a public registry. 

One possible approach would be copying the builder image to the internal registry but losing automatic updates or proxying from the internal registry to the community one, but it's not always allowed.

Allowing different authentication parameters for builder and runImage (`docker.runImageRegistry`) would solve this problem and give developers more flexibility.

**Comment by pgalache** [comment] 2021-06-04 12:25
Closed because it already exists one issue for this #24547

**Comment by scottfrederick** [comment] 2021-06-04 12:33
This is a duplicate of #24547.

**Closed by scottfrederick** 2021-06-04 12:33 UTC
Labels: status: waiting-for-triage
