### ISSUE TITLE
logback-spring.xml reloading not working for springProfile in 1.4.2.RELEASE

### ISSUE THREAD

**Issue by ximanta** [spring-projects/spring-boot#7955] opened 2017-01-11 19:08 UTC
I was expecting scan="true" with scanPeriod="5 seconds" to work with logback configuration in SpringBoot 1.4.2.RELEASE 
 
The error I get on updating a logger level inside <springProfile> is

    -ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:39 - no applicable action for [springProfile],   
     current ElementPath  is [[configuration][springProfile]]

Same goes for springProperty

     -ERROR in ch.qos.logback.core.joran.spi.Interpreter@12:125 - no applicable action for [springProperty],    
     current ElementPath  is [[configuration][springProperty]]

Without springProfile and springProperty scan happens as expected, but only when changes done in target/classes/logback-spring.xml and not in src/main/resources/logback-spring.xml

Without setting scan, springProfile working as expected.

Maven is being used for this SpringBoot Web app.

**Comment by wilkinsona** [comment] 2017-01-11 23:08
Sadly, I think we may need to document this as a limitation. To support `springProfile` and `springProperty` we use a `JoranConfigurator` subclass. Unfortunately, Logback's `ReconfigureOnChangeTask` doesn't give us an opportunity to plug in our subclass:

```java
private void performXMLConfiguration(LoggerContext lc, URL mainConfigurationURL) {
    JoranConfigurator jc = new JoranConfigurator();
    jc.setContext(context);
    StatusUtil statusUtil = new StatusUtil(context);
    List<SaxEvent> eventList = jc.recallSafeConfiguration();

    URL mainURL = ConfigurationWatchListUtil.getMainWatchURL(context);
    lc.reset();
    long threshold = System.currentTimeMillis();
    try {
        jc.doConfigure(mainConfigurationURL);
        if (statusUtil.hasXMLParsingErrors(threshold)) {
            fallbackConfiguration(lc, eventList, mainURL);
        }
    } catch (JoranException e) {
        fallbackConfiguration(lc, eventList, mainURL);
    }
}
```

**Comment by wilkinsona** [comment] 2017-01-17 14:06
I've just noticed that this is a duplicate of #5611

**Closed by wilkinsona** 2017-01-17 14:06 UTC
Labels: priority: normal, type: documentation

**Comment by extraneu** [comment] 2017-11-28 23:34
My apologies for commenting on a closed ticket, but shouldn't this limitation/RFE be reported to logback? (I can't find it on their JIRA)

**Comment by snicoll** [comment] 2017-11-29 09:07
@extraneu I am not aware this has been reported but feel free to do so.

**Comment by guai** [comment] 2023-12-26 12:50
Hi
Any workaroud to make logback+spring be reloadable?
