### ISSUE TITLE
Unable to instantiate factory class [org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor] for factory type [org.springframework.boot.env.EnvironmentPostProcessor]

### ISSUE THREAD

**Issue by sanndeepg** [spring-projects/spring-boot#34138] opened 2023-02-09 12:43 UTC
In my case, it's solved by changing the approach of running the application in the IDE.

2.4.0 may not encourage running the Main Class file directly from the IDE. (this is undeclared anywhere !!)

However, the below goal doesn't make noise for me, so it might be good to go with Springboot plans entirely, even in the development phase. 

`
spring-boot:run -Dspring-boot.run.arguments="--spring.profiles.active=dev"`

Not sure about your case, it may work if the problem statement matches.

_Originally posted by @sanndeepg in https://github.com/spring-projects/spring-boot/issues/24141#issuecomment-1422626407_

**Comment by wilkinsona** [comment] 2023-02-09 13:11
@sanndeepg Sorry, I don't understand why you've duplicated your comment in a separate issue.

> 2.4.0 may not encourage running the Main Class file directly from the IDE. (this is undeclared anywhere !!)

That's not the case. All versions of Spring Boot support running the application using its main method in your IDE.

> However, the below goal doesn't make noise for me, so it might be good to go with Springboot plans entirely, even in the development phase.
>
> `spring-boot:run -Dspring-boot.run.arguments="--spring.profiles.active=dev"`

I don't see the connection between the profiles that are active in the title of the issue.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-projects-issues** [comment] 2023-02-16 13:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-02-23 13:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-02-23 13:12 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
