### ISSUE TITLE
Conditional registration of @ConfigurationProperties bean

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-boot#2312] opened 2015-01-08 16:45 UTC
I have [an outstanding SO question](https://stackoverflow.com/questions/27845102/spring-boot-conditional-on-configurationproperties) that I don't think is supported as a use case as of 1.2.1. Essentially, I would like to use the functionality provided by `@ConditionalOnProperty` along with the type-safe `@ConfigurationProperties`. Currently, Spring Boot registers the properties bean regardless of whether any of the properties listed on it exist, so it's impossible to use `@ConditionalOnBean(MyConfigProps.class)` (I just get a bean with all `null` fields).

I would like either a way to suppress registration of an "empty" properties bean or a condition that matches only if the bean of the specified `@ConfigurationProperties` class exists.

Example:

```
@ConfigurationProperties(prefix = 'my.service')
class ServiceProps {
    String apiKey
}

@Configuration
@ConditionalOnConfigurationProperties(ServiceProps.class)
// or @ConditionalOnBean(ServiceProps.class)
class MyServiceAutoConfig {
    @Autowired
     ServiceProps serviceProps

    @Bean MyService myService() // ...
}
```

**Comment by chrylis** [comment] 2015-01-08 16:46
This is tangentially related to #2282.

**Comment by dsyer** [comment] 2015-01-08 18:25
Can't you do this:

```java
@Bean
@ConfigurationProperties('my.service')
@ConditionalOnWhatever
public ServiceProps serviceProps() { return new ServiceProps(); }
```

**Comment by chrylis** [comment] 2015-01-09 22:56
The issue is specifically that `@Conditional`. It would have to duplicate the information (e.g., list of property names) inside `ServiceProps`. I'd like to have a standard condition that matches if/unless a typed `@ConfigurationProperties` gets populated instead of having to list the property names in the annotation.

**Comment by dsyer** [comment] 2015-01-10 07:29
I'm not sure I understand the use case yet. We often use a single "enabled" flag to switch a feature on. Is that the sort of thing?

**Comment by chrylis** [comment] 2015-01-12 02:31
Sort of, except that if the properties are present, I don't understand the purpose of a separate `enable` property; it seems like duplication to me. The use case is the exact same as for `@ConditionalOnProperty`, just wanting to make use of the type-safe config object instead.

**Comment by snicoll** [comment] 2015-01-12 08:58
I think that #2282 is a better take at this issue. 

If I understand what you're saying, the `@ConfigurationProperties` annotated pojo should be "injected" only if (at least) one of its property is set. And then use that to enable a behaviour in auto-configuration. I think it's a bit vague to say that "if one property of that pojo is set then do X" and I really like the explicit "enabled" flag as it reads quite well in auto-configuration.

The other problem is when you want to disable the auto-config. Let's assume that you have configured tons of properties for that POJO. With your system, you'll have to comment these out instead of just adding an `xyz.enabled=false` property. Assume now you have defined those properties in a separate configuration file that is enabled by a profile or something. Now you have to touch that file to disable the behaviour. 

My point is that the separate `enabled` property is extremely useful. If we can agree on that, then  #2282 is actually a duplicate of this issue. Does that make sense?

**Comment by chrylis** [comment] 2015-01-13 04:26
I can see the multiple-properties-merge issue, and looking at the `enabled` flag as perhaps more useful as a "disabled" flag makes sense.

What about a `@Condition` something like this:

    Class<@ConfigurationProperties> value;
    String enableProperty default "enabled";

**Comment by snicoll** [comment] 2015-01-13 05:28
I am sorry, I didn't get your example.

**Comment by chrylis** [comment] 2015-01-13 23:12
I mean an `@Conditional` annotation with properties something like that, so that by default it will check the `enabled` property on an `@ConfigurationProperties` object (so no configuration required for the usual case of `prefix.enabled`).

**Comment by snicoll** [comment] 2015-01-14 07:41
Oh, interesting.

**Comment by longfeizheng** [comment] 2018-01-10 06:25
`@Configuration
@EnableConfigurationProperties(ServiceProps .class)
public class CoreConfig {

}`

**Comment by philwebb** [comment] 2018-03-22 15:57
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Closed by philwebb** 2018-03-22 15:57 UTC
Labels: type: enhancement

**Comment by izeye** [comment] 2018-05-23 01:19
This looks intended to tag as "declined" based on the @philwebb 's comment.

**Comment by Edhendil** [comment] 2020-12-14 13:55
For anyone interested in a flexible workaround check [my comment in another issue](https://github.com/spring-projects/spring-boot/issues/2282#issuecomment-744453407). It's a full implementation of `@ConditionalOnConfigurationProperties` that you can use in your project. It has some downsides but works.
