### ISSUE TITLE
Unable to find Liquibase migration files

### ISSUE THREAD

**Issue by gianpaolodn** [spring-projects/spring-boot#11615] opened 2018-01-12 16:46 UTC
Hi,

i've got a weird issue with spring-boot m7 and liquibase 3.5.3

Liquibase change-log file is in the default path

```
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
```

During the boot spring reads correctly the file.
Inside I have this infos:

```
databaseChangeLog:
  - includeAll:
    - path: db/changelog/changes
```

Suddenly, if the project runs inside eclipse everything works fine, the migration files are loaded and db populated, but if i run this from the console or from the dockerized image, these files are not found and the database is not populated. 

So I tried several configs:

```
databaseChangeLog:
  - includeAll:
    - path: classpath:db/changelog/changes
```

```
databaseChangeLog:
  - includeAll:
    - path: changes
    - relativeToChangelogFile: true
```

No one works outside eclipse.

Everything works if I use `include` instead of `includeAll`

```
databaseChangeLog:
  - include:
    - file: changes/v0001-init.sql
    - relativeToChangelogFile: true
  - include:
    - file: changes/v0002-questions.sql
    - relativeToChangelogFile: true
```
When i test the jar I run this command (I guess docker does the same):

`java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=development -Dspring.datasource.username=devel -Dspring.datasource.password=devel -Dspring.datasource.url=jdbc:postgresql://localhost:5433/db -jar build.jar`

**Comment by wilkinsona** [comment] 2018-01-12 17:02
I would guess it's a problem with Liquibase being unable to find resources in a fat jar. Can you please provide a small sample (something that we can unzip or git clone and run) that reproduces the problem you have described?

**Comment by eddumelendez** [comment] 2018-01-13 19:24
@wilkinsona I just created [spring-boot-gh-11615](https://github.com/eddumelendez/spring-boot-gh-11615) which reproduce the issue. Running the app from IDE works as expected but running the fat jar doesn't.

**Comment by wilkinsona** [comment] 2018-01-15 09:54
Thank you, @eddumelendez. It looks to be a limitation of Liquibase's `ClassLoaderResourceAccessor`, specifically its `list` method. It makes some faulty assumptions about URLs of entries in a jar (for example, that the URL will only contain a single `!`). Liquibase's `SpringResourceOpener` overrides `ClassLoaderResourceAccessor` and its `list` method, but it ultimately calls `super.list` and suffers the same problem.

It looks like we could override `createResourceOpener` on `SpringLiquibase` and return a custom subclass of `SpringResourceOpener` and, hopefully, override the faulty assumptions. It looks quite involved though.

**Comment by gianpaolodn** [comment] 2018-01-15 10:18
thanks @eddumelendez for the provided example. 

@wilkinsona the issue was present in springboot 2 milestone 7, why did you add this to 1.5.10?

**Comment by wilkinsona** [comment] 2018-01-15 10:21
Because I believe it's also present in Spring Boot 1.5.x and, if it is, we want to fix it there and then merge the change forwards so it's also included in 2.0.

**Comment by gianpaolodn** [comment] 2018-01-15 10:27
Ah ok... Sorry :)

Il 15 gen 2018 11:22, "Andy Wilkinson" <notifications@github.com> ha
scritto:

Because I believe it's also present in Spring Boot 1.5.x and, if it is, we
want to fix it there and then merge the change forwards so it's also
included in 2.0.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spring-projects/spring-boot/issues/11615#issuecomment-357640879>,
or mute the thread

**Comment by pwielgolaski** [comment] 2018-01-24 17:04
could be fix for it https://github.com/liquibase/liquibase/pull/698

**Comment by wilkinsona** [comment] 2018-01-24 17:14
Thank you, @pwielgolaski. I'm going to close this issue now as it doesn't make sense to add a work around in Boot given that a fix in Liquibase appears to be imminent. We'll upgrade to the Liquibase 3.5.x release that contains the fix in due course.

**Closed by wilkinsona** 2018-01-24 17:14 UTC
Labels: priority: normal, type: bug

**Comment by bjsee** [comment] 2018-07-06 07:13
Has this really been fixed? I´m facing the same problem with Spring Boot 2.0.3.RELEASE and liquibase 3.5.3.

**Comment by bjsee** [comment] 2018-07-06 07:31
ok thanks.. and sorry :)
