### ISSUE TITLE
@ActiveProfiles no longer supports ${some.env:default} property placeholder expressions

### ISSUE THREAD

**Issue by icyerasor** [spring-projects/spring-boot#25466] opened 2021-02-25 18:29 UTC
**Affects:** spring-test 5.3.3

Back with _5.2.1.RELEASE_ I could annotate a test class with:

```java
@ActiveProfiles("${testprofiles.active:test}")
```

when supplying `-Dtestprofiles.active=integrationtest` the context would load the resolved `integrationtest` Profile:

> org.springframework.core.env.StandardEnvironment - Activating profiles [integrationtest]
> com.iteratec.MyTest: The following profiles are active: integrationtest

After upgrading to _5.3.3_ this doesn't seem to work anymore:

> org.springframework.core.env.StandardEnvironment - Activating profiles [${testprofiles.active:test}]
> com.iteratec.MyTest: The following profiles are active: ${testprofiles.active:test}

and thus a fallback to no matching profile at all / base-properties happens.

Is this expected behavior or a bug?

---

I worked around this by using a custom ActiveProfilesResolver:

```java
@ActiveProfiles(value = "test", resolver = SystemPropertyActiveProfilesResolver.class)
```

```java
public class SystemPropertyActiveProfilesResolver implements ActiveProfilesResolver {

	private final DefaultActiveProfilesResolver defaultActiveProfilesResolver = new DefaultActiveProfilesResolver();


	@Override
	public String[] resolve(Class<?> testClass) {
		Assert.notNull(testClass, "Class must not be null");

		if (System.getProperties().containsKey("spring.profiles.active")) {
			final String profiles = System.getProperty("testprofiles.active");
			return profiles.split("\\s*,\\s*");
		} else {
			return defaultActiveProfilesResolver.resolve(testClass);
		}
	}
}
```

**Comment by mbhave** [comment] 2021-03-01 19:54
I am able to reproduce what @sbrannen [described](https://github.com/spring-projects/spring-boot/issues/25466#issuecomment-787509993). It must be related to the config data changes because it works with 2.4 if `spring.config.use-legacy-processing` is set to `true`.

What I found odd was that with 2.3.x too, `environment.getActiveProfiles()` contains `${testprofiles.active:test}`. But it also contains `test` which is why it works. @sbrannen Is `${testprofiles.active:test}` in the environment's active profiles expected behavior?

**Comment by sbrannen** [comment] 2021-03-01 20:11
With 2.3.9, if I run my test with `-Dtestprofiles.active=integrationtest` and print out the active profiles, I see the following.

> [${testprofiles.active:test}, integrationtest]

So I'm seeing the same behavior as you, which I hadn't noticed before.

To answer your question, no I would not expect to see `${testprofiles.active:test}` registered as an active profile.

So part of the mystery is why the placeholder expression and resolved placeholder both end up as registered active profiles.

The other side of the story involves whether resolution of property placeholders in `@ActiveProfiles` was ever an intentional feature of Spring Boot Test. I can imagine that it was an accident, and yet some users may have come to depend on it. So perhaps the Spring Boot team wishes to reinstate that behavior. Another option would be investigating introducing that support in `spring-test`.

Thoughts?

**Comment by sbrannen** [comment] 2021-03-01 20:15
> It must be related to the config data changes because it works with 2.4 if `spring.config.use-legacy-processing` is set to `true`.

By the way, good catch on that!

**Comment by sbrannen** [comment] 2021-03-01 20:23
Another thing to keep in mind is the `MergedContextConfiguration` (MCC), specifically regarding what active profiles are being stored in the MCC.

I suppose the unresolved property placeholder should be stored in the MCC and then only resolved once actually adding it to the `Environment` -- resolved against properties available in the `Environment` at that point in time.

**Comment by mbhave** [comment] 2021-03-01 20:33
> Another option would be investigating introducing that support in spring-test.

oh I thought this was something `spring-test` also supported. I am not sure if Spring Boot's support is intentional or by accident. It also gets tricky if the property that is resolved by `@ActiveProfiles` lives in a `profile-specific` file such as `application-dev.yml`.

Flagging for team attention to see if the rest of the team thinks that placeholder resolution in `@ActiveProfiles` was intentional and something that we should support.

**Comment by wilkinsona** [comment] 2021-03-02 08:23
I can't remember for certain, but given that we don't have any tests for it, I would assume that it was not intentional. If it's not supported by `spring-test` then I would lean towards not supporting it in Boot.

**Comment by mbhave** [comment] 2021-03-03 20:05
We discussed this on the team call and we have decided to follow Spring Framework and not support placeholders in `@ActiveProfiles`. This is not a regression because it happened to work by accident before 2.4.x and the behavior is neither tested nor documented.

**Closed by mbhave** 2021-03-03 20:05 UTC
Labels: type: regression
