### ISSUE TITLE
while updgrading springboot 2.2.2

### ISSUE THREAD

**Issue by sumit-gurav** [spring-projects/spring-boot#19587] opened 2020-01-09 06:24 UTC
```java
@ConditionalOnProperty(name = "opentracing.spring.cloud.mongo.enabled", havingValue = "true", matchIfMissing = true)
public class MongoTracingAutoConfiguration extends MongoAutoConfiguration {

    private Tracer tracer;

    public MongoTracingAutoConfiguration(@Autowired(required = false) MongoProperties properties, ObjectProvider options, Environment environment, Tracer tracer) {
        super(properties, options, environment); //******* error Expected 0 arguments but found 3
        this.tracer = tracer;
    }
 
    @override //***** error Method does not override method from its superclass
    public MongoClient mongo() {
        MongoClient mongo = super.mongo(); // **** Expected 3 arguments but found 0
        return new TracingMongoClient(tracer, mongo.getAllAddress(), mongo.getCredentialsList(), mongo.getMongoClientOptions());
    }

}
```

**Comment by wilkinsona** [comment] 2020-01-09 08:16
@sumit-gurav A snippet of code with no explanation really doesn't give us enough to help you with whatever problem you may be facing. Looking at the code snippet, this also appears to be a duplicate of the issues that you opened yesterday so I am going to close this issue.

**Closed by wilkinsona** 2020-01-09 08:16 UTC
Labels: status: waiting-for-triage
