### ISSUE TITLE
Tomcat is serving web page response content extremely slow

### ISSUE THREAD

**Issue by sisqo** [spring-projects/spring-boot#23231] opened 2020-09-08 16:33 UTC
After upgrading from spring-boot 2.2.7. to spring boot 2.3.3 we are experiencing **extreme slowness in receiving web content** in the production environment. 

The document of our application is 30kb and is downloaded in over 8.9 sec. Normally it takes about 200 ms.

With version 2.3.3. every request experience this issue, going back to version 2.2.7. the problem disappears. 

The problem occurs only in the production environment (Google Cloud VM), while in local we are unable to reproduce it.

I attach the chrome inspection page that verify the problem 
![image](https://user-images.githubusercontent.com/2743927/92503455-95c7a680-f201-11ea-9608-deb3aeeeac47.png)

**Comment by wilkinsona** [comment] 2020-09-08 16:48
Thanks for the report.

Unfortunately, it's not clear why you believe that this is a problem with Spring Boot itself. You also haven't described what sort of content you're serving, whether it's generated by a controller, static content served by Spring MVC, static content served by Tomcat, or something else.

Given that we haven't heard of similar problems from anyone else, I think it's highly likely that the problem is specific to your application and/or the deployment environment. Perhaps you could spend some time describing exactly how the content is being served and narrowing down the possible causes of the problem by trying different versions of Tomcat, etc.

**Comment by sisqo** [comment] 2020-09-08 17:54
Thanks Andy for your feedback, you are absolutely right I try to go into more detail.

The application where the problem occurs is a spring-boot **MVC application** with embedded **Tomcat**. The calls are standard get calls handled with _@GetMapping_ by an _@Controller_.
The controller returns the name of the .jsp page we use to render the content.

The problem o
<img width="951" alt="Schermata 2020-09-08 alle 19 45 54" src="https://user-images.githubusercontent.com/2743927/92511024-04f6c800-f20d-11ea-8359-d9f89f717e48.png">
ccurs in the download time of the document, and this happens with all controllers and with all calls of our application. For example, this is the home page eg: https://www.vino75.com (at the moment we are up with version 2.2.7 and the problem does not appear).

We are thinking that the problem is spring-boot because this is the only difference between deploy and with and without the problem: we have tried to deploy the application several times by changing only the version of spring-boot. With version 2.2.7 the problem does not arise while with 2.3.3 it occurs systematically.

I attach a screenshot of when the content is downloaded successfully.

Let me know if I can provide more information to better investigate the problem.

**Comment by philwebb** [comment] 2020-09-08 18:06
Without a way to replicate things locally it's very hard to say what the problem might be. JSP rendering is usually handled directly by Tomcat, and Spring Boot doesn't really get involved that much. Can you try with Spring Boot v2.2.9.RELEASE just to see if it's a Tomcat upgrade that caused the issue?

If that works, we need to find a way to replicate the issue or get some more server-side logs that could shed some light on the cause.

**Comment by sisqo** [comment] 2020-09-08 19:53
We have upgraded from Spring Boot v2.2.7.RELEASE to v2.2.9.RELEASE and the issue is not present.

<img width="660" alt="Schermata 2020-09-08 alle 21 52 00" src="https://user-images.githubusercontent.com/2743927/92521507-a2f28e80-f21d-11ea-9308-7c22609532b1.png">

**Comment by philwebb** [comment] 2020-09-08 22:41
Are you able to create a minimal sample that you can share that fails in the same way when you deploy it to Google Cloud?

**Comment by sisqo** [comment] 2020-09-09 07:16
We are unable to reproduce the problem, everything works fine locally.

**Comment by wilkinsona** [comment] 2020-09-09 07:39
We understand that. We're interested in a minimal sample that reproduces the problem when deployed to Google Cloud.

**Comment by spring-issuemaster** [comment] 2020-09-16 07:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-09-23 07:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-09-23 07:41 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by glennvdv** [comment] 2020-10-14 18:50
We are experiencing a similair problem. We upgraded from 2.2.5 to 2.3.4 and now in our production environment we are experiencing performance issues. Most Pages are 2 seconds slower then before the upgrade. We have Java melody for monitoring and there we can see that jsp are using high cpu and slower rendering. Unfortunately we haven't been able tot reproduce this locally. 
Our app is packaged as a war (because of jsp) and are using embedded tomcat.

**Comment by asafbart** [comment] 2020-12-22 10:29
same issue here also, upgrade 2.2.6 to 2.3.3, 10 times slower response time 5ms vs 50 ms for very simple configuration

**Comment by snicoll** [comment] 2020-12-22 10:55
@asafbart we've requested a minimal sample that we can use to reproduce the problem. Can you please do that in the form of a sample project that works with 2.2.6 and is much slower by only changing the version to 2.3.3? You can do so by attaching a zip to this issue or share a link to a GitHub repository. Thank you.

**Comment by asafbart** [comment] 2020-12-23 13:16
@snicoll found the issue. it was an import which used a library called jasypt-spring-boot and does not officially support this version spring

**Comment by sisqo** [comment] 2020-12-23 13:46
> @snicoll found the issue. it was an import which used a library called jasypt-spring-boot and does not officially support this version spring
@asafbart thank you for your feedback, unfortunately it does not completely solve the case, in our project we don't have jasypt-spring-boot library

**Comment by asafbart** [comment] 2020-12-23 14:02
@sisqo  Probably unrelated, but generally my lesson is to see if some library on your classpath might affect the AutoConfiguration... but yeah maybe unrelated to you

**Comment by sisqo** [comment] 2021-04-01 14:15
Issue finally solved!!! This is the complete explanation: 
https://vivekvara.medium.com/jsp-performance-degrades-from-spring-boot-2-3-x-for-undefined-attributes-8cb434f743c2#_=_

**Comment by wilkinsona** [comment] 2021-04-01 14:45
Thanks for following up, @sisqo. I don't understand why the EL implementation would only cause a problem on Google Cloud, but I'm glad that you got to the bottom of it. Your problem's a duplicate of https://github.com/spring-projects/spring-boot/issues/24744 which is the issue where we switched to the faster Apache EL implementation in 2.5.

**Comment by sisqo** [comment] 2021-04-01 19:35
> Thanks for following up, @sisqo. I don't understand why the EL implementation would only cause a problem on Google Cloud, but I'm glad that you got to the bottom of it. Your problem's a duplicate of #24744 which is the issue where we switched to the faster Apache EL implementation in 2.5.

It's not related to Google Cloud, now is clear. We were misled by the fact that this problem only occurred in production, but it was due to the fact that some parts of jsp were being processed in production that were obviously involved.
Thank you for your feedback and linking to the duplicate case.
