### ISSUE TITLE
spring-boot 2.0.0.M5 - Gradle Debug mode doesn't work

### ISSUE THREAD

**Issue by ldelahaye** [spring-projects/spring-boot#10891] opened 2017-11-02 15:59 UTC
Bug report

Spring boot 2 : 2.0.0.M5
IDE IntelliJ 2017.2
Gradle : 4.2
JDK : 8

After I upgrade spring boot 2.0.0.M4 to 2.0.0.M5 and i run gradle in debug mode. 
But my breakpoints aren't working and I don't have some error log

After some investigation, I decide to downgrade to 2.0.0.M4 and it's work correctly.

Excuse my English.

**Comment by wilkinsona** [comment] 2017-11-02 16:01
Duplicate of #10872.

**Closed by wilkinsona** 2017-11-02 16:01 UTC
