### ISSUE TITLE
The order of custom TestExecutionListener is not configurable neither via '@Ordered' nor 'implements Ordered'

### ISSUE THREAD

**Issue by rfelgent** [spring-projects/spring-boot#13107] opened 2018-05-08 21:36 UTC
Hello everybody,

I use Selenium WebDriver for my Frontend-Tests.
I wanna take a screenshot in case of test failures. For this, I created a custom TestExecutionListener that should take a picture of the current Browser window after each test method in the event of test failure.

Unfortunately the WebDriverTestExecutionListener from Spring Boot autoconfigure closes the WebDriver before I am able to take a screenshot.

I tried different settings with Ordered annotation and implementing Ordered interface to no avail.

I created a test project here: https://github.com/rfelgent/springboot-testexecutionlistener-order

Best regards

**Comment by wilkinsona** [comment] 2018-05-09 15:56
Duplicate of #11796. This should work if you upgrade to Spring Boot 2.0 where Boot's listeners are all now ordered. Specifically, `WebDriverTestExecutionListener` now has an order of `Ordered.LOWEST_PRECEDENCE - 100`.

**Closed by wilkinsona** 2018-05-09 15:56 UTC
Labels: status: waiting-for-triage

**Comment by rfelgent** [comment] 2018-05-10 17:57
Hi @wilkinsona ,

I only partly agree that this issue is similar to #11796. I am also "disappointed" that you just closed this issue...

Please let me allow to explain:

1) I want to configure my custom TestExecutionListener _before_ and not after the WebDriverTestExecutionListener as described in #11796
2) The suggestion to upgrade from Spring Boot 1.5.10 to Spring Boot 2.0 is currently not applicable for different reasons (team ressources for library upgrade, no Spring Boot Admin 2.0 release yet, testing for not automated parts of the application and so on...)
3) Even if you change the order as described in #11796, I do not see how this would ensure that my custom listener would be applied earlier. I guess there must be some other code bugfixing involved, too?! 

The reason for asking about detailed information is, that I could apply changes in request to a PR for 1.5.X Release. I really would like to have a working bugfix for the 1.5.X and not only for 2.X streamline

**Comment by wilkinsona** [comment] 2018-05-10 18:39
Test execution listeners wrap the invocation of a test method. This means that they're driven in order for the `beforeTestMethod` callback and in the reverse order for the `afterTestMethod` callback. You want your `afterTestMethod` callback to be called before `WebDriverTestExcectionListener` so it needs to be ordered after it. That isn't possible in 1.5.x as it has no order and, therefore, inherits the default which is lowest precedence. This has been fixed in 2.0 by #11796 and is why I closed this issue as a duplicate of #11796.

It's regrettable that the test execution listeners aren't ordered in 1.5.x, but we can't change that now as people may be relying on that behaviour and it would be a breaking change for them if we did.

If upgrading to 2.0 isn't an option for you at the moment, you may be able to work around the current behaviour by running your tests using a custom subclass of `SpringBootTestContextBootstrapper` that overrides the `getTestExecutionListeners` method and reorders the list to meet your needs. You can make the test framework aware of the custom bootstrapped by annotating your test with `@BootstrapWith(YourCustomBootstrapper.class)`.

**Comment by rfelgent** [comment] 2018-05-11 06:33
Hello @wilkinsona ,

thank you very much for taking the time to provide in-depth details of #11796. I was not aware of the
> ...order for the beforeTestMethod callback and in the reverse order for the afterTestMethod callback...
With those information, I clearly understand why you closed my issue as a duplicate of #11796.

The idea of a custom bootstrapper sounds reasonable to me as long as the application is using Spring Boot 1.5.X. Thank you for the hint!

**Comment by MariuszJozala-Avaleo** [comment] 2018-07-23 09:57
I am having similar problem where I need to set order of TestExecutionListeners. Unfortunately creating subclass of `SpringBootTestContextBootstrapper` is not really an option, because `getTestExecutionListeners` is declared `final` in `AbstractTestContextBootstrapper`. Do you know of any other way to do it?

**Comment by MariuszJozala-Avaleo** [comment] 2018-07-23 12:03
Thank you for replying @philwebb.

I am adding multitenancy with EclipseLink to my application. If method is transactional, tenant is set from context on the start of transaction. However, in my implementation, tenant is get from security context. 
That is why I need `WithSecurityContextTestExecutionListener` to be initialized before `TransactionalTestExecutionListener`. Between those two listeners I am going to put my TestExecutionListener which is setting the tenant.
I cannot do it right now, because `WithSecurityContextTestExecutionListener` has order 10000 and `PermissionInitializerTestExecutionListener` has order 4000. 

For now I will make workaround by implementing interface `TestContextBootstrapper` and delegating all method calls to `SpringBootTestContextBootstrapper`. I will create a JIRA ticket if I will not find any better way to achieve what I need. Thanks.
