### ISSUE TITLE
DataSource initialisation is skipped when hibernate generate ddl

### ISSUE THREAD

**Issue by laplantb** [spring-projects/spring-boot#18358] opened 2019-09-25 20:08 UTC
Migrating my app from spring boot 1.5.17 to 2.1.8

While running tests, the hsqldb database is not populated from data.sql script.

properties:
```
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.initialization-mode=always
```

I found the source of issue in class org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher, line 103.
```
Object dataSource = 
entityManagerFactory.getProperties().get("javax.persistence.nonJtaDataSource");
```
 It does not publish the ```DataSourceSchemaCreatedEvent``` because it does not find the nonJtaDataSource in entityManagerFactory.  It was finding it using spring boot 1.5 but, in 2.1, the dataSource is stored under property 'hibernate.connection.datasource' instead of 'javax.persistence.nonJtaDataSource'

**Comment by philwebb** [comment] 2019-09-25 20:48
I think this is a duplicate of #17061

**Closed by philwebb** 2019-09-25 20:48 UTC
Labels: status: waiting-for-triage
