### ISSUE TITLE
Test fails after update 2.6.4 to 2.6.5

### ISSUE THREAD

**Issue by datengaertnerei** [spring-projects/spring-boot#30458] opened 2022-03-29 07:43 UTC
I am working on an OSS project at https://github.com/datengaertnerei/test-data-service

During one of the regular updates of Spring Boot dependency by Renovate Bot (2.6.4 to 2.6.5) one test failes and the PR was stopped.  Tested manually the Maven build is successful with skipped tests and the service works fine even with that endpoint of the failed test.

Log excerpt from Maven build
```
org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [\] did not match expected type [java.lang.String (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [\] did not match expected type [java.lang.String (n/a)]
	at com.datengaertnerei.test.dataservice.junit.TestDataServiceApiTests.shouldReturnRandomPersonForArea(TestDataServiceApiTests.java:170)
Caused by: java.lang.IllegalArgumentException: Parameter value [\] did not match expected type [java.lang.String (n/a)]
	at com.datengaertnerei.test.dataservice.junit.TestDataServiceApiTests.shouldReturnRandomPersonForArea(TestDataServiceApiTests.java:170)

```

The failed method call at line 170 is `result = restController.personForPostcode("20", AgeRange.ALL);`

The called method is

```
	/**
	 * @param postalCode postalCode
	 * @param age age
	 * @return random person with a valid german postal address within the given postal code (zip) area (1-5 digits)
	 */
	@GetMapping(value = "/person/postalcode/{postalcode}")
	@Operation(summary = "random person with a valid german postal address within the given postal code (zip) area (1-5 digits)")
	@ApiResponse(responseCode = "200", description = "OK")
	@ApiResponse(responseCode = "400", description = "Bad Request", content = @Content())
	public Person personForPostcode(
			@Parameter(description = "the postal code to look for random postal address", required = true) @PathVariable("postalcode") String postalCode,
			@RequestParam(required = false) AgeRange age) {
		if (null == age) {
			return personGen.createRandomPersonInArea(postalCode, AgeRange.ALL);
		} else {
			return personGen.createRandomPersonInArea(postalCode, age);
		}
	}

```

There is a second very similar test that works just fine. So this is a low priority issue but maybe there is a quick fix.

**Comment by knoobie** [comment] 2022-03-29 07:52
See https://github.com/spring-projects/spring-data-jpa/issues/2472#issuecomment-1078845101

**Comment by bclozel** [comment] 2022-03-29 08:39
Closing as a duplicate of #30454

**Closed by bclozel** 2022-03-29 08:39 UTC
Labels: status: waiting-for-triage
