### ISSUE TITLE
Upgrade Hsqldb to version that doesn't cause Flyway to deadlock

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-boot#6394] opened 2016-07-14 14:13 UTC
When I upgrade my projects to use Spring Boot 1.3.6 instead of 1.3.5 my flyway migration test gets stuck. Here's a very minimal sample project: https://github.com/timtebeek/flyway-hsqldb

Setting `spring-boot-starter-parent` to `1.3.5.RELEASE` will make the test succeed. With `1.3.6.RELEASE` it gets stuck, as shown here: https://travis-ci.org/timtebeek/flyway-hsqldb/builds/144749071

Can anyone look into it and confirm/fix my issue? (And is this the right place?)

**Comment by bradf83** [comment] 2016-07-14 14:45
Hi @timtebeek ,

This seems to have to do with the version of HSQLDB.

In Spring Boot 1.3.5 the version was 2.3.3 and in Spring Boot 1.3.6 the version is 2.3.4.

If you manually downgrade just your HSQLDB version you will see your test succeed.

The following Stackoverflow question led me to this information and may have more information to help you solve this.  [Stackoverflow Question](http://stackoverflow.com/questions/38279412/flyway-hsql-db-create-tables-sql-migrate-hangs)

**Comment by timtebeek** [comment] 2016-07-14 15:03
Hi @bradf83 , thanks for the quick reply! I'll use `<hsqldb.version>2.3.3</hsqldb.version>` in my POM for now then, since the SO answer is a bit ambiguous on how to `hsqldb.tx=mvcc` for less strict locking.

I'm guessing this change will affect other Spring Boot users as well, so maybe some action is still required from the Spring team?

**Comment by philwebb** [comment] 2016-07-14 16:26
Thanks for the sample and for tracking down the stackoverflow answer. That's quite an unexpected change for HSQLDB to make at patch release.

**Comment by wilkinsona** [comment] 2016-07-14 18:42
HSQLDB issue: https://sourceforge.net/p/hsqldb/bugs/1441/

**Comment by wilkinsona** [comment] 2016-07-14 18:44
Flyway issue: https://github.com/flyway/flyway/issues/1346

**Comment by philwebb** [comment] 2016-07-14 19:16
I'm tempted to just downgrade HSQLDB and let them sort it out amongst themselves.

**Comment by wilkinsona** [comment] 2016-07-15 08:50
Me too. The suggested workaround (setting `hsqldb.tx=mvcc`) doesn't help and, interestingly, makes 2.3.3 hang as well. I've put together a sample that reproduces the various problems: https://github.com/wilkinsona/flyway-hsqldb-hang

**Comment by wilkinsona** [comment] 2017-02-01 10:39
The Flyway issue has been fixed. It looks like it'll be part of 4.1. It moves HSQLDB to a new single connection mode which avoids the problems with its locking.

In summary, we can safely upgrade to the latest version of HSQLDB once Flyway 4.1 is out and we've upgraded to it. I suspect that will happen during 2.0's development.

**Comment by wilkinsona** [comment] 2017-02-11 09:36
HSQLDB 2.3.5 will fix this: https://sourceforge.net/p/hsqldb/bugs/1441/#ccb6

**Comment by wilkinsona** [comment] 2017-04-28 14:45
Closed by 59d04d06797a92f7fd981618f71a4e8e19117432

**Closed by wilkinsona** 2017-04-28 14:45 UTC
Labels: type: dependency-upgrade
