### ISSUE TITLE
SpringBoot 3.0.3 can't identify any @RestController anotated class except in Startup Class

### ISSUE THREAD

**Issue by r-asou** [spring-projects/spring-boot#34382] opened 2023-02-25 11:59 UTC
SpringBoot version: `3.0.3`
OS: `Windows 11`
Java: `OpenJDK 19`
Recently I just wrote a simple Spring Boot application.
And I used the latest Spring Boot and the version is  3.0.3.

What I did is I wrote a simple controller, but I found Spring boot can't identify this.
But if I put the simple mapping in startup class, it can work.

The code is simple as below:

```java
package com.example.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class StorageController {

    @GetMapping("/hello/hello")
    public String hello() {
        return "hello";
    }
}
```

The startup class:

```java
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class StorageApplication {

    public static void main(String[] args) {
        SpringApplication.run(StorageApplication.class, args);
    }

    @GetMapping("hello")
    public String hello() {
        return "hello";
    }
}
```

Base on my setting, it should have 2 mapping which is `/hello` and` /hello/hello`.
Actually, it only can find the first one written in startup class

But it's work in Spring boot `2.7.9`

**Comment by bclozel** [comment] 2023-02-25 12:09
Closing as a duplicate of #34379

**Closed by bclozel** 2023-02-25 12:09 UTC
Labels: status: waiting-for-triage

**Comment by kamrankamilli** [comment] 2023-02-28 09:19
I have the same issue with spring boot 3.0.3 using Ubuntu, I'm not sure if it is specific to Windows. Previously I was using Spring Boot 3.0.2 and had no problems.

**Comment by softboy99** [comment] 2023-03-08 08:12
spring boot 3.0.4 still has this problem

**Comment by wilkinsona** [comment] 2023-03-08 08:20
@softboy99 Please ensure that you're using Spring Framework 6.0.6 as that's where the fix was made. If you still have a problem when using Spring Framework 6.0.6 please open [a Spring Framework issue](https://github.com/spring-projects/spring-framework/issues).

**Comment by softboy99** [comment] 2023-03-08 08:54
Spring Boot 3.0.4 shiped with Spring Framework 6.0.6, on the spring official website, it's said

**Comment by wilkinsona** [comment] 2023-03-08 09:37
@softboy99 Yes, that's correct, but we have no way of knowing if that's the version that your application is actually using. Something may have overridden Spring Boot's dependency management. As I said above, if you can reproduce the problem with Spring Boot 3.0.4 and Spring Framework 6.0.6, please open a Spring Framework issue and provide a minimal sample.
