### ISSUE TITLE
Register method is called twice on DockerComposeLifecycleManager during startup

### ISSUE THREAD

**Issue by llapinski1987** [spring-projects/spring-boot#36442] opened 2023-07-18 11:28 UTC
As in the topic, docker is trying to register two times the same bean and that is causing  the exception
`The bean 'mongoConnectionDetailsForDemoMongodb1' could not be registered. A bean with that name has already been defined and overriding is disabled.`

# Reproduce

To reproduce create a [Maven Spring Boot 3.1.1 with 'Docker Compose Support', 'data-mongoDb' , 'cloud-eureka' and 'Web' on start.spring.io](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.1.1&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=web,data-mongodb,docker-compose,cloud-eureka,actuator,lombok) and then just start the application (even with empty properties for service discovery)

**Comment by snicoll** [comment] 2023-07-18 11:44
This looks like a duplicate of #35878. If you can reproduce without Spring Cloud, we can reopen this issue.

**Closed by snicoll** 2023-07-18 11:44 UTC
Labels: status: waiting-for-triage

**Comment by llapinski1987** [comment] 2023-07-18 12:04
Ok, but in this project i am not using spring-cloud-starter-config in the dependencies

**Comment by snicoll** [comment] 2023-07-18 12:14
Like I said, if you can reproduce without Spring Cloud, we can reopen. If not, a follow-up in the Spring Cloud issue tracker will be required if necessary.

**Comment by llapinski1987** [comment] 2023-07-18 12:16
Ok, thanks for help ;)
