### ISSUE TITLE
OutOfMemory when use spring-boot-actuator with prometheus

### ISSUE THREAD

**Issue by DianaQiao2023** [spring-projects/spring-boot#37819] opened 2023-10-11 10:07 UTC
Hi,

I got the OOM every few days after I restart the project. Please check the details as below. Thanks for your help!

Environment:
JDK: 17
SpringBoot: 3.1.2
SpringCloud: 2022.0.3
spring-boot-starter-actuator: 3.1.2
micrometer-registry-prometheus: 1.11.2

Management endpoints config:
![image](https://github.com/spring-projects/spring-boot/assets/133354778/ead6513b-80cc-4865-a3bb-31b9d46ecb11)

OutOfMemory Error:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537) ~[na:na]
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:228) ~[na:na]
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:582) ~[na:na]
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:313) ~[na:na]
	at java.base/java.io.StringWriter.write(StringWriter.java:106) ~[na:na]
	at io.prometheus.client.exporter.common.TextFormat.writeOpenMetrics100(TextFormat.java:233) ~[simpleclient_common-0.16.0.jar!/:na]
	at org.springframework.boot.actuate.metrics.export.prometheus.TextOutputFormat$2.write(TextOutputFormat.java:62) ~[spring-boot-actuator-3.1.2.jar!/:3.1.2]
	at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(PrometheusScrapeEndpoint.java:62) ~[spring-boot-actuator-3.1.2.jar!/:3.1.2]

Heapdump Analysis:
![image](https://github.com/spring-projects/spring-boot/assets/133354778/00a05c8b-cb62-4a35-ba7d-0991f4da1e15)
More Stack:
![image](https://github.com/spring-projects/spring-boot/assets/133354778/0d9e5ec0-4582-447e-906f-a13d4a53ce77)
JVM Memory Usage: 
![image](https://github.com/spring-projects/spring-boot/assets/133354778/b2895cbc-f9a1-4e9f-bb19-5a4dc8b2c5d2)
JVM GC CPU Usage:
![image](https://github.com/spring-projects/spring-boot/assets/133354778/e48a06d8-9f53-4c7a-bac9-1b6052bcfd6d)
The Tenured Gen and GC CPU were keep rising unusually.

**Comment by wilkinsona** [comment] 2023-10-11 10:24
Thanks for the report. Unfortunately, the information you have provided isn't sufficient to identify the problem. It tells us is that there wasn't enough memory available to create the response from the Prometheus endpoint but it does not tell us why there wasn't enough memory. The problem could be completely unrelated to Prometheus.

> The Tenured Gen and GC CPU were keep rising unusually

This sounds like a memory leak but it could be anywhere in your application. You should be able to identify the leak by comparing multiple heap dumps and identifying growth in the heap that should not be occurring. 

Unfortunately, we don't have the time to help with general diagnosis of a memory leak so I'm going to close this issue as there's no evidence of it being caused by Spring Boot. If your problem diagnosis reveals that it is caused by Spring Boot, please comment again on this issue with that diagnosis and we will re-open it and take another look.

**Closed by wilkinsona** 2023-10-11 10:24 UTC
Labels: status: waiting-for-triage
