### ISSUE TITLE
serializerByType is not work

### ISSUE THREAD

**Issue by juzi214032** [spring-projects/spring-boot#22338] opened 2020-07-15 03:55 UTC
```java
@Bean
public Jackson2ObjectMapperBuilderCustomizer jackson2ObjectMapperBuilderCustomizer() {
    return builder -> builder
            .serializerByType(LocalDateTime.class, jacksonLocalDateTimeSerializer)
            .deserializerByType(LocalDateTime.class, jacksonLocalDateTimeDeserializer);
}
```
I specified Serializer and Deserializer, but they didn't work!
Example Repository：https://github.com/juzi214032/oerp
Branch：feat/jackson

![image](https://user-images.githubusercontent.com/38206169/87501582-ff0fbb00-c691-11ea-8c42-f07fc278a472.png)

**Comment by wilkinsona** [comment] 2020-07-15 07:06
Thanks for the sample, but I'm afraid it's not clear how we should use it to reproduce the problem that you are seeing. This is partly because the sample is rather large and contains a lot of code and dependencies that don't appear to be related to a Jackson serialisation problem. Unfortunately, we don't have time to reduce things down ourselves, particularly as doing so may mean that we change the behaviour so that we can't reproduce the problem or end up solving a different problem. If you would like us to spend some time investigating, can you please spend some time reducing the same to the minimum that is required to reproduce the problem and providing some instructions on how to reproduce it.

**Comment by spring-issuemaster** [comment] 2020-07-22 07:11
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-07-29 07:09
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-07-29 07:09 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
