### ISSUE TITLE
Nested jars are not opened with runtime version set

### ISSUE THREAD

**Issue by Hartigan** [spring-projects/spring-boot#38050] opened 2023-10-25 20:53 UTC
Hello

I tried new version of spring-framework 3.2.0-RC1 with `spring.threads.virtual.enabled=true` feature. But I faced issue with jar provided by `bootJar`: ` java.lang.UnsupportedOperationException: Virtual threads not supported on JDK <21`
I prepared minimal reproducible example:

Environment:
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)

Project generated by https://start.spring.io/ with options:
Project: Gradle - Groovy
Language: Java
Spring Boot: 3.2.0-RC1
Packaging: Jar
Java: 21

`DemoApplication.java` contents:

```
package com.example.demo;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.task.VirtualThreadTaskExecutor;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		new VirtualThreadTaskExecutor().getVirtualThreadFactory();
		System.out.println("Hello world");
	}

}
```

Output for `./gradlew bootRun`:

```
Welcome to Gradle 8.3!

Here are the highlights of this release:
 - Faster Java compilation
 - Reduced memory usage
 - Support for running on Java 20

For more details see https://docs.gradle.org/8.3/release-notes.html


> Task :bootRun
Hello world

BUILD SUCCESSFUL in 1s
4 actionable tasks: 3 executed, 1 up-to-date
```

Output for `./gradlew bootJar && java -jar ./build/libs/demo-0.0.1-SNAPSHOT.jar`:

```
BUILD SUCCESSFUL in 1s
4 actionable tasks: 1 executed, 3 up-to-date
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:54)
Caused by: java.lang.UnsupportedOperationException: Virtual threads not supported on JDK <21
        at org.springframework.core.task.VirtualThreadDelegate.<init>(VirtualThreadDelegate.java:32)
        at org.springframework.core.task.VirtualThreadTaskExecutor.<init>(VirtualThreadTaskExecutor.java:41)
        at com.example.demo.DemoApplication.main(DemoApplication.java:10)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 4 more
```

**Comment by philwebb** [comment] 2023-10-25 21:55
This looks like a regression with our new nested jar loader. For now you can add the following to your build to roll-back to the older implementation:

```
bootJar {
  loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC
}
```

**Comment by Hartigan** [comment] 2023-10-25 22:04
Yes, this solution works. Is my task a duplicate? Should I close it?

**Comment by philwebb** [comment] 2023-10-26 01:04
@Hartigan No thanks, we need to fix it in Boot. We'll transfer the issue or create a new one and close this one ourselves.

**Comment by philwebb** [comment] 2023-10-26 03:23
I bit of digging shows the assumption that the `URLClassLoader` will append `#runtime` to URLs so that they are opened with the correct runtime version set isn't true.

The code in `jdk.internal.loader.URLClassPath` does [have some logic to do that](https://github.com/openjdk/jdk/blob/jdk-17%2B35/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java#L826), but only for `JarLoader`. We end up with the vanilla `Loader` due to [this check](https://github.com/openjdk/jdk/blob/jdk-17%2B35/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java#L512).

I think we need to update our archive URLs to include `#runtime`.

**Comment by philwebb** [comment] 2023-10-26 03:57
Unfortunately appending `#runtime` to the URL is not enough because it is lost [here](https://github.com/openjdk/jdk/blob/jdk-17%2B35/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java#L604)

**Closed** 2023-10-26 04:25 UTC
Labels: type: regression

**Comment by sergmain** [comment] 2023-10-26 07:29
This bug is appearing only on Linux. No issue on Windows
