### ISSUE TITLE
Pagination w/ HATEOAS doesn't serialize the entire tree

### ISSUE THREAD

**Issue by efenderbosch** [spring-projects/spring-boot#2350] opened 2015-01-13 18:33 UTC
I've created a simple project to demonstrate my problem here: 

https://github.com/efenderbosch/springboot-hateoas-test

The info is in the readme.md, but I'll duplicate it here.

http://localhost:8080/childrenWithPagination will return

``` json
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/childrenWithPagination{?page,size,sort}",
      "templated" : true
    }
  },
  "_embedded" : {
    "children" : [ {
      "id" : 1,
      "attribute" : "attribute"
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 1,
    "totalPages" : 1,
    "number" : 0
  }
}
```

http://localhost:8080/childrenWithoutPagination will return

``` json
[
  {
    "id":1,
    "attribute":"attribute",
    "parent":{
      "id":1,
      "attribute":"attribute"
    }
  }
]
```

Note that the pagination endpoint does not serialize the parent. The Repository does return the full tree, it just doesn't get fully serialized.

**Comment by efenderbosch** [comment] 2015-01-14 19:31
I've removed spring-boot-starter-data-rest and included spring-boot-starter-web and spring-hateoas and this seems to have fixed my problem.

**Comment by philwebb** [comment] 2015-01-15 00:10
Reopening as I'd like to try and take a look at the underlying cause.

**Comment by efenderbosch** [comment] 2015-01-15 14:19
RepositoryRestMvcConfiguration adds PersistentEntityJackson2Module to the ObjectMapper(s). PersistentEntityJackson2Module then tries to render HATEOAS links for each persistent entity in the tree. I don't know why the links aren't being rendered, but it would be nice to be able to turn this on and off.

We are purposely returning the entire tree to avoid multiple calls to backend RESTful services.

**Comment by snicoll** [comment] 2016-12-22 16:32
@efenderbosch I've upgraded your sample to `1.4.2.RELEASE` and I can reproduce what you experience. However, I can also experience it with the workaround you've suggested in your comment. 

In that context, I am not sure there is an issue in Boot. But perhaps @olivergierke has an idea about this setup?

**Comment by spring-issuemaster** [comment] 2016-12-29 16:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-01-05 16:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-01-05 16:36 UTC
Labels: waiting-for-triage
