### ISSUE TITLE
Chinese support for springboot3

### ISSUE THREAD

**Issue by jianjiaF** [spring-projects/spring-boot#30709] opened 2022-04-18 02:08 UTC
I use springboot3, which doesn't seem to support outputting Chinese.
I have configured VM to use UTF-8
<img width="439" alt="springboot3" src="https://user-images.githubusercontent.com/39707338/163743198-b23b6525-8ef3-41e8-96f7-b6a195395c60.png">
<img width="621" alt="springboot(2)" src="https://user-images.githubusercontent.com/39707338/163743410-e4761b22-d08b-453e-80e3-b8d170c72570.png">

**Comment by pruidong** [comment] 2022-04-18 03:27
I also had this problem, you can try to set the file encoding to GBK in IDEA.


![idea_file_encoding_setting](https://user-images.githubusercontent.com/13309008/163749829-ddc25194-fd9f-4cf0-90eb-529eea0cf306.png)


If you are not using JDK18, you can ignore this one:

I suspect that this problem is caused by JDK modifying the default encoding, but I haven't researched this problem yet. (JDK18: https://openjdk.java.net/jeps/400)

**Comment by pruidong** [comment] 2022-04-18 03:36
JVM arguments you need to use:

-Dfile.encoding=GBK

![idea_run_chinese](https://user-images.githubusercontent.com/13309008/163750599-0716d96e-03f4-425f-994f-1d78ce6d2a1b.png)

**Comment by jianjiaF** [comment] 2022-04-18 03:39
Yeah！If I use 2.6.6 version of springboot and jdk17, it will not be like this, but if I use jdk18, it will be garbled; Using springboot and jdk18 of version 3.0.0 will cause garbled code, but using jdk17 will not cause garbled code.But jdk18 seems to support Chinese by default.

**Comment by pruidong** [comment] 2022-04-18 03:40
If you are not using JDK18, you can ignore this one:

I suspect that this problem is caused by JDK modifying the default encoding, but I haven't researched this problem yet. (JDK18: https://openjdk.java.net/jeps/400)

If it still doesn't display properly, you need to check your IDEA file encoding:

![idea_file_encoding_setting](https://user-images.githubusercontent.com/13309008/163750902-90b55e71-e479-4ed6-8f53-a3e81f397dc8.png)

**Comment by pruidong** [comment] 2022-04-18 03:42
> Yeah！If I use 2.6.6 version of springboot and jdk17, it will not be like this, but if I use jdk18, it will be garbled; Using springboot and jdk18 of version 3.0.0 will cause garbled code, but using jdk17 will not cause garbled code.But jdk18 seems to support Chinese by default.

This is due to a change in JDK18, usually I recommend you to use a long-term supported version of the JDK in production, such as: JDK8, JDK11, JDK17.

**Comment by jianjiaF** [comment] 2022-04-18 03:45
> > 是啊！如果我用2.6.6版本的springboot和jdk17就不会这样了，但是如果我用jdk18就会乱码；使用3.0.0版本的springboot和jdk18会出现乱码，但是使用jdk17不会出现乱码。不过jdk18好像默认支持中文。
> 
> 这是由于JDK18发生了变化，通常我建议您在生产中使用长期支持的JDK版本，例如：JDK8、JDK11、JDK17。

Yeah!My production environment uses jdk17, but I like to try something new, so I use jdk18 to create projects, which causes this problem. At present, it should be the problem of jdk18, but I don't know how to solve it.

**Comment by jianjiaF** [comment] 2022-04-18 03:47
> > Yeah！If I use 2.6.6 version of springboot and jdk17, it will not be like this, but if I use jdk18, it will be garbled; Using springboot and jdk18 of version 3.0.0 will cause garbled code, but using jdk17 will not cause garbled code.But jdk18 seems to support Chinese by default.
> 
> This is due to a change in JDK18, usually I recommend you to use a long-term supported version of the JDK in production, such as: JDK8, JDK11, JDK17.

Yeah!My production environment uses jdk17, but I like to try something new, so I use jdk18 to create projects, which causes this problem. At present, it should be the problem of jdk18, but I don't know how to solve it.

**Comment by pruidong** [comment] 2022-04-18 03:48
> > > Yeah！If I use 2.6.6 version of springboot and jdk17, it will not be like this, but if I use jdk18, it will be garbled; Using springboot and jdk18 of version 3.0.0 will cause garbled code, but using jdk17 will not cause garbled code.But jdk18 seems to support Chinese by default.
> > 
> > 
> > This is due to a change in JDK18, usually I recommend you to use a long-term supported version of the JDK in production, such as: JDK8, JDK11, JDK17.
> 
> Yeah!My production environment uses jdk17, but I like to try something new, so I use jdk18 to create projects, which causes this problem. At present, it should be the problem of jdk18, but I don't know how to solve it.

JVM arguments you need to use:

-Dfile.encoding=GBK

**Comment by jianjiaF** [comment] 2022-04-18 03:51
> > > > Yeah！If I use 2.6.6 version of springboot and jdk17, it will not be like this, but if I use jdk18, it will be garbled; Using springboot and jdk18 of version 3.0.0 will cause garbled code, but using jdk17 will not cause garbled code.But jdk18 seems to support Chinese by default.
> > > 
> > > 
> > > This is due to a change in JDK18, usually I recommend you to use a long-term supported version of the JDK in production, such as: JDK8, JDK11, JDK17.
> > 
> > 
> > Yeah!My production environment uses jdk17, but I like to try something new, so I use jdk18 to create projects, which causes this problem. At present, it should be the problem of jdk18, but I don't know how to solve it.
> 
> JVM arguments you need to use:
> 
> -Dfile.encoding=GBK

Oh! thank you!

**Comment by snicoll** [comment] 2022-04-18 06:13
All of this is outside spring boot's control, closing.

**Closed** 2022-04-18 06:13 UTC
Labels: status: waiting-for-triage
