### ISSUE TITLE
@WebMvcTest permitAll() no longer works after upgrade to 2.6.0

### ISSUE THREAD

**Issue by markusheiden** [spring-projects/spring-boot#28765] opened 2021-11-21 09:36 UTC
After upgrading to 2.6.0 a @WebMvcTest controller test for an unauthenticated endpoint no longer works, because a 401 instead of a 200 is returned.

This looks similar to the @SpringBootTest issue https://github.com/spring-projects/spring-boot/issues/28759

Minimal repro:
```java
@Order(1)
@Configuration
public class Security extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.cors().and().antMatcher("/test/**").authorizeRequests()
                .antMatchers("/test").permitAll()
                .anyRequest().authenticated();
    }
}
@Order(2)
@Configuration
public class BaseSecurity extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .anyRequest().authenticated();
    }
}
@RestController
public class Controller {
    @GetMapping("/test")
    public String test() { return "test"; }
}
@WebMvcTest(Controller.class)
class ControllerTest {
    @Autowired
    private MockMvc mockMvc;
    @Test
    void test() throws Exception { mockMvc.perform(get("/test")).andExpect(status().isOk()); }
}
```

**Comment by wilkinsona** [comment] 2021-11-21 13:15
Thanks for the report. This is a duplicate of #28759.

**Closed by wilkinsona** 2021-11-21 13:15 UTC
Labels: status: waiting-for-triage
