### ISSUE TITLE
Actuator is not working with Jersey starter

### ISSUE THREAD

**Issue by ouaibsky** [spring-projects/spring-boot#2025] opened 2014-11-30 22:33 UTC
Hi

I just cloned the starter-jersey sample then tried to add dependency spring-boot-starter-actuator.
Looks like any context mapped by actuator are working
The trouble is stdout looks fine, saying all endpoints are added, but when doing /health or /metrics ....  nothing appears in a browser. 
In fact it's a 404 error (displayed woth curl -i)
Looks like error page are not working as well.

I guess all this is due to Jersey but not able to do more troubleshooting.

Tested on 1.2.0-BUILD-SNAPSHOT

Christophe

**Comment by wujek-srujek** [comment] 2015-07-15 21:32
I was also caught by this one, i.e. expecting the actuator to work with boot-starter-jersey. This was after we already committed to Jersey, so going back to webmvc is not an option. So now, it seems we have to depend on both webmvc (for example, via boot-starter-web) and jersey 2 (via boot-starter-jersey), i.e. have two REST libraries, which imho is not nice.
Anyways, I was able to configure it both ways:

* add @ApplicationPath("api") on the ResourceConfig @Component - in this case, all my custom resources are accessed with /api/hello etc.
* remap the dispatcherServlet to /spring with server.servlet-path - the only thing I find strange is that while log says the dispatcher has been remapped, the endpoints are still reported under their original urls, for example:

	2015-07-15 23:15:24.292  INFO 2272 --- [           main] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/spring/*]
	2015-07-15 23:15:26.218  INFO 2272 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
	2015-07-15 23:15:26.219  INFO 2272 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest)
	2015-07-15 23:15:26.249  INFO 2272 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
	2015-07-15 23:15:26.249  INFO 2272 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
	2015-07-15 23:15:26.290  INFO 2272 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
	2015-07-15 23:15:26.661  INFO 2272 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/configprops],methods=[GET]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()

Above, the /configprops URL is still reported although the one to use is /spring/configprops. Also, I don't really know if the /webjars/** is now /spring/webjars/**, the same for /error etc.

What makes things very, very confusing is that it is not documented anywhere that the actuator depends on webmvc; what is more, the spring-boot-actuator/pom.xml says the dependency on webmvc is optional (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/pom.xml#L145-L149), i.e. webmvc is not really necessary for the actuator to work.

**Comment by snicoll** [comment] 2015-07-16 06:58
I think the misunderstanding comes from the fact that the "web" exposure is just one feature of the actuator. You can access to the same features via JMX endpoints for instance. That's  why it's optional

>  that it is not documented anywhere that the actuator depends on webmvc;

Granted it's not *super obvious* but [this page](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-monitoring) on "Monitoring and management over HTTP" starts with:

> If you are developing a Spring MVC application, Spring Boot Actuator will ....

I'll add an explicit tip in that section.

**Comment by wujek-srujek** [comment] 2015-07-16 20:12
Now I understand why it's marked optional, I didn't know about the other options (JMX, shell), now I read the full docs and know better.

As for the note you added - do you think it would be worth adding __how__ both MVC and Jersey can be used together? It seems, even in this very issue, even the Boot core devs weren't sure if and how to make it work.

**Comment by snicoll** [comment] 2015-07-17 07:00
I think we didn't try to make it work, indeed. You can always create a separate issue to ask fro a sample. PR more than welcome.

**Closed by snicoll** 2015-07-17 07:00 UTC
Labels: question

**Comment by Avec112** [comment] 2016-11-24 14:19
See [77.3 Actuator and Jersey](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-actuator.html)

**Comment by yahyayouness** [comment] 2017-07-20 09:22
I turn around by adding @ApplicationPath("/api") to my jersey config 

so dispatcher servlet map /
and JerseyServlet override but only map /api/*

**Comment by anilkonduru** [comment] 2018-02-27 20:30
This might help someone using Jersey with Spring Boot.

If you are using Jersey with Spring Boot, actuator doesn't work default 
like spring MVC. To make it work, spring.jersey.application-path need 
to be set with your context path.

spring.jersey.application-path=/mytest-app

OR

server.servlet-path=/mytest-app

Also make sure following properties are set.

server.context-path=/mytest-app
management.security.enabled=false
management.health.defaults.enabled=true

**Comment by philwebb** [comment] 2018-02-27 23:05
@anilkonduru Jersey actuator endpoints are supported in Spring Boot 2.0

**Comment by adenix** [comment] 2018-03-07 20:59
@philwebb Are you saying that actuator endpoints work by default in Spring Boot 2.0? Because I'm not seeing that behavior. I'm still seeing Jersey overrun the actuator endpoints:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.test</groupId>
	<artifactId>actuator-jersey</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.RELEASE</version>
		<relativePath/>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jersey</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	
</project>
```

```
2018-03-07 15:56:57.385  INFO 7661 --- [           main] c.d.t.i.u.Application     : Starting Application on SCRUBBED with PID 7661 (/SCRUBBED/target/classes started by SCRUBBED in /SCRUBBED/myID/user-preferences)
2018-03-07 15:56:57.388  INFO 7661 --- [           main] c.d.t.i.u.Application     : No active profile set, falling back to default profiles: default
2018-03-07 15:56:57.494  INFO 7661 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@624ea235: startup date [Wed Mar 07 15:56:57 EST 2018]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/SCRUBBED/.m2/repository/org/springframework/spring-core/5.0.4.RELEASE/spring-core-5.0.4.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-03-07 15:56:58.575  INFO 7661 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-03-07 15:56:58.900  INFO 7661 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2018-03-07 15:56:58.947  INFO 7661 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-03-07 15:56:58.947  INFO 7661 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.28
2018-03-07 15:56:58.956  INFO 7661 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/SCRUBBED/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2018-03-07 15:56:59.071  INFO 7661 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-03-07 15:56:59.071  INFO 7661 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1586 ms
2018-03-07 15:56:59.676  INFO 7661 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-03-07 15:56:59.676  INFO 7661 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-03-07 15:57:00.088  INFO 7661 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-07 15:57:00.133  INFO 7661 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-03-07 15:57:00.137  INFO 7661 --- [           main] c.d.t.i.u.Application     : Started Application in 3.225 seconds (JVM running for 3.794)
```

**Comment by wilkinsona** [comment] 2018-03-07 21:11
What makes you think the endpoints have been “overrun”?  Note that Jersey doesn’t log any mappings at startup so their absence from the log doesn’t mean anything.

**Comment by adenix** [comment] 2018-03-07 21:13
@wilkinsona Navigating to `http://localhost:8080/actuator` and `http://localhost:8080/actuator/health` returns 404 - Not Found

**Comment by wilkinsona** [comment] 2018-03-07 21:20
There’s no sign in the log output that you’ve shared that Jersey’s filter or Servlet has been registered so it looks like a broader problem. I’d check for corrupted dependencies, that you have a `ResourceConfig` Bean, and the auto-configuration report to see what’s going on. If that doesn’t help, please open a new issue with a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by jokerr** [comment] 2018-03-10 04:05
@wilkinsona @adenix Hopefully this will help - https://github.com/jokerr/boot2-jersey-actuator

```
2018-03-09 21:56:15.179  INFO 12148 --- [           main] com.example.BootApp                      : Starting BootApp on REDACTED with PID 12148 (C:\Users\jokerr\dev\boot2-jersey-actuator\target\classes started by jokerr in C:\Users\jokerr\dev\boot2-jersey-actuator)
2018-03-09 21:56:15.182  INFO 12148 --- [           main] com.example.BootApp                      : No active profile set, falling back to default profiles: default
2018-03-09 21:56:15.247  INFO 12148 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@4c22c4ba: startup date [Fri Mar 09 21:56:15 CST 2018]; root of context hierarchy
2018-03-09 21:56:16.386  INFO 12148 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-03-09 21:56:16.792  INFO 12148 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2018-03-09 21:56:16.823  INFO 12148 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-03-09 21:56:16.823  INFO 12148 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.28
2018-03-09 21:56:16.836  INFO 12148 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [REDACTED]
2018-03-09 21:56:16.958  INFO 12148 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-03-09 21:56:16.959  INFO 12148 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1717 ms
2018-03-09 21:56:18.124  INFO 12148 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-03-09 21:56:18.124  INFO 12148 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-03-09 21:56:18.124  INFO 12148 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-03-09 21:56:18.124  INFO 12148 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet com.example.jaxrs.JerseyConfig mapped to [/v1/*]
2018-03-09 21:56:18.526  INFO 12148 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-09 21:56:18.586  INFO 12148 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-03-09 21:56:18.591  INFO 12148 --- [           main] com.example.BootApp
```

**Comment by wilkinsona** [comment] 2018-03-10 07:53
Thanks, @jokerr. Hopefully it will. @adenix That sample shows the actuator available at `/v1/actuator`. For example, you can access the health endpoint like this:

```
$ curl -i :8080/v1/actuator/health
HTTP/1.1 200
Content-Type: application/vnd.spring-boot.actuator.v2+json
Content-Length: 15
Date: Sat, 10 Mar 2018 07:52:42 GMT

{"status":"UP"}
```

**Comment by snicoll** [comment] 2018-03-10 08:04
If it does not, there is [another sample here](https://github.com/snicoll-scratches/jersey-actuator)

**Comment by jokerr** [comment] 2018-03-10 13:50
@wilkinsona This is just my personal opinion, I think a point of confusion is not seeing the actuator endpoints register in the start up logs.  Through tinkering with the Jersey + Actuator combo I've found that not all the documented management properties work out of the box unless you make certain changes.

For example, I added a `application.properites` file to my sample app with only one property, `management.server.servlet.context-path=/management`.  The Actuator is **only** available at `/v1/actuator`.  

```
2018-03-10 07:44:15.538  INFO 3472 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-03-10 07:44:15.538  INFO 3472 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1422 ms
2018-03-10 07:44:16.576  INFO 3472 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-03-10 07:44:16.576  INFO 3472 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-03-10 07:44:16.576  INFO 3472 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-03-10 07:44:16.576  INFO 3472 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet com.example.jaxrs.JerseyConfig mapped to [/v1/*]
2018-03-10 07:44:16.947  INFO 3472 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-10 07:44:16.999  INFO 3472 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-03-10 07:44:17.004  INFO 3472 --- [           main] com.example.BootApp                      : Started BootApp in 3.304 seconds (JVM running for 7.064)
```

However when I also change the port then things start working a little different. `management.server.port=8081`.  The actuator is available at `:8081/management/actuator` and the Jersey app at `:8080/v1/`

```
2018-03-10 07:46:10.204  INFO 8968 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-03-10 07:46:10.205  INFO 8968 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1546 ms
2018-03-10 07:46:10.536  INFO 8968 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-03-10 07:46:10.536  INFO 8968 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-03-10 07:46:10.536  INFO 8968 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-03-10 07:46:10.536  INFO 8968 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet com.example.jaxrs.JerseyConfig mapped to [/v1/*]
2018-03-10 07:46:11.393  INFO 8968 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-10 07:46:11.401  INFO 8968 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@58e34793: startup date [Sat Mar 10 07:46:11 CST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5947e435
2018-03-10 07:46:11.465  INFO 8968 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-03-10 07:46:11.512  INFO 8968 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2018-03-10 07:46:11.513  INFO 8968 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-03-10 07:46:11.514  INFO 8968 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.28
2018-03-10 07:46:11.531  INFO 8968 --- [ost-startStop-1] o.a.c.c.C.[.[localhost].[/management]    : Initializing Spring embedded WebApplicationContext
2018-03-10 07:46:11.531  INFO 8968 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 130 ms
2018-03-10 07:46:11.644  INFO 8968 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet servletContainer mapped to [/*]
2018-03-10 07:46:11.703  INFO 8968 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path '/management'
2018-03-10 07:46:11.724  INFO 8968 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-03-10 07:46:11.727  INFO 8968 --- [           main] com.example.BootApp                      : Started BootApp in 3.461 seconds (JVM running for 7.29)
```

Appreciate all your hard work on this project!

**Comment by adenix** [comment] 2018-03-10 14:01
Yeah, I got it working a few days ago. Then I had an issue using `packages()` with a fat jar so I used someones solution to implement the same functionality for a fat jar.

**Comment by wilkinsona** [comment] 2018-03-12 16:55
> This is just my personal opinion, I think a point of confusion is not seeing the actuator endpoints register in the start up logs.

That's a side-effect of using Jersey. Boot itself doesn't look any of the Actuator endpoint mappings. Spring MVC and Spring WebFlux both log mappings at info level by default, Jersey doesn't and I don't believe there's a way to switch it on. I've opened https://github.com/spring-projects/spring-boot/issues/12442 to consider adding some logging to Boot.

> For example, I added a application.properites file to my sample app with only one property, management.server.servlet.context-path=/management. The Actuator is only available at /v1/actuator.

This is the expected behaviour. `management.server.servlet.context-path` only has an effect if `management.server.port` has been set and has a different value to `server.port`.

> However when I also change the port then things start working a little different. management.server.port=8081. The actuator is available at :8081/management/actuator and the Jersey app at :8080/v1/

In some ways that's what I'd expect. On one hand, your `@ApplicationPath("v1")`-annotated resource config isn't part of the management context that's used when a separate port has been specified so it makes some sense that it doesn't affect the actuator in that case. On the other hand, the actuator endpoints must have picked up the `ResourceConfig` from your app and used it otherwise they wouldn't be available. I don't yet understand why they apparently picked up the `ResourceConfig` but didn't pick up the `@ApplicationPath`. I suspect it also means that we're sharing one `ResourceConfig` across the management "app" and your app. That's unlikely to be a good idea… I've opened https://github.com/spring-projects/spring-boot/issues/12443.

**Comment by bric3** [comment] 2019-07-15 14:47
Reading this https://docs.spring.io/spring-boot/docs/2.1.6.RELEASE/reference/htmlsingle/#production-ready-customizing-management-server-context-path (Using 2.1.6.RELEASE)

> Unless the management port has been configured to expose endpoints by using a different HTTP port, `management.endpoints.web.base-path` is relative to `server.servlet.context-path`. If `management.server.port` is configured, `management.endpoints.web.base-path` is relative to `management.server.servlet.context-path`.

I modified the configuration this way

```diff
+server:
+  servlet:
+    context-path: /
spring.mvc.servlet.path: /static
spring:
  jersey:
    application-path: /
    servlet:
      load-on-startup: 1

management:
  endpoint:
    health.enabled: true
+  endpoints:
+    web:
+      base-path: /actuator
+      path-mapping.health: healthcheck
```

However actuators keep showing up under `/static` instead of `/`

* `curl localhost:8080/static/actuator/healthcheck` => 200
* `curl localhost:8080/actuator/healthcheck` => 404

So either there's something missing on the documentation or they are some limitations to how aftuator integrate when there's both spring mvc and jersey.

**Comment by wilkinsona** [comment] 2019-07-15 14:58
@bric3 If you have both Jersey and Spring MVC on the classpath, Actuator has to pick one so Spring MVC will take precedence. If you believe that something is unclear or that there's an improvement that could be made somewhere please open a new issue and we will take a look.

**Comment by bric3** [comment] 2019-07-15 15:17
Hi @wilkinsona, I believe that both could be improved.

1. The doc should state which technology it will take precedence. And as such how other properties are affected, i.e. `server.servlet.context-path` has no effect when Spring MVC is also present.
2. Is there a way to configure which technology will be used.
3. If not maybe indicate how to play with the DispatcherServlet to not hide Spring MVC when jersey and MVC are mapped on the same context path `/`

```
Mapping servlets: oldMetricsService urls=[/metrics], company.web.JerseyConfig urls=[/*], dispatcherServlet urls=[/]
```

This last is actually interesting if one want to migrate one endpoint at a time from one technology to another.

I will open the issue. Thanks a lot.
