### ISSUE TITLE
Provide a health indicator for reactive Cassandra

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11767] opened 2018-01-25 09:46 UTC

**Comment by izeye** [comment] 2018-07-31 13:44
This looks resolved via https://github.com/spring-projects/spring-boot/pull/13864.

**Comment by snicoll** [comment] 2018-07-31 13:56
Indeed, thanks again.

Duplicate of #13864

**Closed by snicoll** 2018-07-31 13:56 UTC
Labels: type: enhancement
