### ISSUE TITLE
Unable to create a folder in the root directory of the application in spring boot 2.5.0

### ISSUE THREAD

**Issue by lyousan** [spring-projects/spring-boot#26722] opened 2021-06-01 08:47 UTC
BUG report:
Unable to create a folder in the root directory of the application (the equivalent of src), such as a folder called config in the equivalent of src. Starting the application at this time will cause an exception [  **java.lang.IllegalStateException: No subdirectories found for mandatory directory location 'file:./config/*/'**  ], even if the entire SpringBoot application has not written a single line of code.

**Comment by mschneid** [comment] 2021-06-01 09:02
Duplicate of #26627 (4.x) and #26672 (5.x).

**Closed** 2021-06-01 09:23 UTC
Labels: status: waiting-for-triage
