### ISSUE TITLE
WebMvcTest WithMockUser not working principal is null

### ISSUE THREAD

**Issue by sysmat** [spring-projects/spring-boot#31165] opened 2022-05-25 08:58 UTC
- spring-boot-starter-parent:2.7.0
- java 8
- code:

```java
@ExtendWith(SpringExtension.class)
@WebMvcTest(controllers = ReservationResource.class)
@DisplayName("Testing ReservationResource Web layer")
class ReservationResourceMvcTest {

    @Test
    @WithMockUser(roles = "USER", username = TEST_NET_ID)
    @DisplayName("deleteReservationByOwner mock MVC with mock user")
    void deleteReservationByOwner() throws Exception {

        this.mockMvc
              .perform(delete(Util.PATH_RESERVATION + "/1"))
              .andExpect(status().is2xxSuccessful());
        
        verify(reservationService).deleteReservationById(1L, TEST_NET_ID);
    }
}
```
- when I check principal in ReservationResource it is **NULL**

**Comment by wilkinsona** [comment] 2022-05-25 09:16
Thanks for the report. We have tests, [such as this one](https://github.com/spring-projects/spring-boot/blob/e13f187c37200145005d6dbf47da739e5e659886/spring-boot-project/spring-boot-test-autoconfigure/src/test/java/org/springframework/boot/test/autoconfigure/security/MockMvcSecurityIntegrationTests.java#L45-L49), that verify the behavior of `@WithMockUser` and `@WebMvcTest`. Unfortunately, an incomplete code snippet is insufficient for us to diagnose what differences are causing things not to work for you. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by sysmat** [comment] 2022-05-25 09:31
- WebSecurityConfigurerAdapter is deprecated so I move to SecurityFilterChain
- in WebMvcTest if I don't mock SecurityFilterChain then the client doesn't hit the REST endpoint
-  in WebMvcTest if I use `@MockBean SecurityFilterChain apiSecurity`  then in REST endpoint method principle is NULL

```java
@DeleteMapping("/{id}")
public void deleteReservationByOwner(@PathVariable Long id, Principal principal) {
        System.out.println("user="+principal);
        this.reservationService.deleteReservationById(id, principal.getName());
}
```

- is there any migration guide for WebMvcTest 
- https://docs.spring.io/spring-security/reference/5.7.0-M2/servlet/configuration/java.html#_multiple_httpsecurity here test suite is not covered

**Comment by wilkinsona** [comment] 2022-05-25 09:40
Your problem may be a duplicate of #31162 but it's impossible to say for certain without a sample. If you would like us to look into this further, please provide one.

**Comment by sysmat** [comment] 2022-05-25 10:10
- sample
[filter.zip](https://github.com/spring-projects/spring-boot/files/8770077/filter.zip)

**Comment by sysmat** [comment] 2022-05-25 10:21
- demo, where in rest endpoint Principle is NULL

[filter.zip](https://github.com/spring-projects/spring-boot/files/8770177/filter.zip)

**Comment by wilkinsona** [comment] 2022-05-25 10:48
Thanks for the sample. Your `SecurityConfig` class is a plain `@Configuration` class so it isn't included in a `@WebMvcTest`. As described in the javadoc of `@WebMvcTest`, you need to use `@Import` to create any additional collaborators that are needed by your test:

```java
@Import(SecurityConfig.class)
@WebMvcTest(controllers = RestEndPoint.class)
@DisplayName("Testing REST end point")
public class MvcTest {
```

You should also remove your mock `apiSecurity` bean. With these changes in place, your test passes.

**Closed by wilkinsona** 2022-05-25 10:48 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by sysmat** [comment] 2022-05-25 11:14
@wilkinsona thx, it would be really nice to have documentation

**Comment by wilkinsona** [comment] 2022-05-25 11:21
We [already have some](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#howto.testing.slice-tests) as a result of [these changes](https://github.com/spring-projects/spring-boot/commit/ed8f8d59ef9ef73553b9b3acd60b5e8ba618b6d5) in 2.5.11 for https://github.com/spring-projects/spring-boot/issues/16088.
