### ISSUE TITLE
Logging config in application.yml are not parsed under some conditions

### ISSUE THREAD

**Issue by mdeknowis** [spring-projects/spring-boot#11972] opened 2018-02-09 08:31 UTC
We upgraded from spring boot 2.0.0.M4 to 2.0.0.RC1

We experienced that our spring boot application is not longer starting anylonger, if we have some conditions of logging configurations. Then we get this error:

```txt
***************************
APPLICATION FAILED TO START
***************************
 Description:
 Failed to bind properties under 'logging.level.de.knowis.cp.another_package' to java.util.Map&lt;java.lang.String, java.lang.Object&gt;:
     Reason: No converter found capable of converting from type [java.lang.String] to type [java.util.Map&lt;java.lang.String, java.lang.Object&gt;]
 Action:
 Update your application's configuration
```

Perhaps it's related to [ConfigurationProperties treat .yml files differently in test environment #11960](https://github.com/spring-projects/spring-boot/issues/11960)

We tried several combinations in your `application.yml` (some more configuration in it, but these where the only logging related once)

* :red_circle: Not working situation:
    
    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.Jjsh": "INFO",
    ```

* :red_circle: Not working situation:
    
    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.Jjsh": "INFO",
    ```
    
* :white_check_mark: Working again

    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
    ```

* :white_check_mark: Also working

    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodo": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.hjdghgs.HJghfg": "INFO",
    ```

* :red_circle: Not working situation (as before)
    
    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.Jjsh": "INFO",
    ```
    
* :white_check_mark: Working again

    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodo": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
    ```

* :white_check_mark: Also working

    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
    ```
    
* :red_circle: Not working situation (as before)

    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.Jjsh": "INFO",
    ```

* :white_check_mark: Working again (as before)

    ```json
        "logging.level.de.knowis.cp.another_package": "INFO",
        "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
    ```

**Comment by snicoll** [comment] 2018-02-09 09:30
@mdeknowis I have a hard time reading this report.

>  if we have some conditions of logging configurations
What does that mean? Can you please share a sample that reproduces the migration problem? Also, I am not sure I understand the sequence of those working/not  working snippets.

**Comment by mdeknowis** [comment] 2018-02-13 10:48
Hi!

I created a reduced app of our to reproduce this issue: 
[spring-application.zip](https://github.com/spring-projects/spring-boot/files/1719559/spring-application.zip)

We create a docker image out of it and deploy it on a kubernetes cluster.

A working config map is for example that one:

```json
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "data": {
    "logging.level.de.knowis.cp": "DEBUG",
    "logging.level.de.knowis.cp.another_package": "INFO",
    "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO"
  }
}
```

Two not working ones are:
```json
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "data": {
    "logging.level.de.knowis.cp": "DEBUG",
    "logging.level.de.knowis.cp.another_package": "INFO",
    "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
    "logging.level.de.knowis.cp.util.web.client.interceptor.LoggerInterceptor": "TRACE"
  }
}
```

and 

```json
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "data": {
    "logging.level.de.knowis.cp": "DEBUG",
    "logging.level.de.knowis.cp.another_package": "INFO",
    "logging.level.de.knowis.cp.another_package.sample.Woodooo.JHdhjsj": "INFO",
    "logging.level.de.knowis.cp.util.web.client.interceptor.LoggerInterceptor": "TRACE",
    "logging.level.de.knowis.cp.util.web.context": "INFO",
    "logging.level.de.knowis.cp.util.web.provider.interceptor": "INFO",
    "logging.level.de.knowis.cp.util.web.provider.security": "INFO"
  }
}
```

So we get this error:

```txt
 java -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -Dkubernetes.master=xxxx:443 -Dsun.jnu.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.timezone=UTC -Duser.variant= -DDEPLOYMENT_IMAGE_TAG=xxxx:build_5115 -DDEPLOYMENT_GIT_COMMIT=cb17ee143a24aaabe949abe3d5924cc2ecc54853 -jar app.jar
10:32:10.043 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
10:32:10.066 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find Kubernetes config at: [/root/.kube/config]. Ignoring.
10:32:10.066 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from service account...
10:32:10.067 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
10:32:10.079 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
10:32:10.079 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client namespace from Kubernetes service account namespace path...
10:32:10.079 [main] DEBUG io.fabric8.kubernetes.client.Config - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
2018-02-13 10:32:13.003+0000  INFO [repository-application,,,] 8 --- [           main] [MID:,RID:,SNID:,USER:] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@69d9c55: startup date [Tue Feb 13 10:32:12 UTC 2018]; root of context hierarchy
2018-02-13 10:32:13.561+0000  INFO [repository-application,,,] 8 --- [           main] [MID:,RID:,SNID:,USER:] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$12fd815f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
████████╗███████╗███████╗████████╗
╚══██╔══╝██╔════╝██╔════╝╚══██╔══╝
   ██║   █████╗  ███████╗   ██║   
   ██║   ██╔══╝  ╚════██║   ██║   
   ██║   ███████╗███████║   ██║   
   ╚═╝   ╚══════╝╚══════╝   ╚═╝   
                                  
repository-application   2.0.0.RC1 (2018-02-13T10:30:12Z)
cb17ee143a24aaabe949abe3d5924cc2ecc54853
2018-02-13 10:32:14.435+0000  INFO [repository-application,,,] 8 --- [           main] [MID:,RID:,SNID:,USER:] b.c.PropertySourceBootstrapConfiguration : Located property source: ConfigMapPropertySource {name='configmap.repository-application.repository-dev'}
2018-02-13 10:32:14.437+0000  INFO [repository-application,,,] 8 --- [           main] [MID:,RID:,SNID:,USER:] b.c.PropertySourceBootstrapConfiguration : Located property source: SecretsPropertySource {name='secrets.repository-application.repository-dev'}
2018-02-13 10:32:14.453+0000 ERROR [repository-application,,,] 8 --- [           main] [MID:,RID:,SNID:,USER:] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
Failed to bind properties under 'logging.level.de.knowis.cp' to java.util.Map&lt;java.lang.String, java.lang.Object&gt;:
    Reason: No converter found capable of converting from type [java.lang.String] to type [java.util.Map&lt;java.lang.String, java.lang.Object&gt;]
Action:
Update your application's configuration 
```

**Comment by mdeknowis** [comment] 2018-02-13 12:09
Define logging in `bootstrap.yml`:

```yml
spring:
  application:
    name: "@project.artifactId@"
    version: "@project.version@"
logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: DEBUG
```


Got this exception:
```txt
 org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'logging.level.de.knowis.cp' to java.util.Map&lt;java.lang.String, java.lang.Object&gt;
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:227)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:203)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$0(Binder.java:283)
	at org.springframework.boot.context.properties.bind.Binder$Context.withSource(Binder.java:390)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$1(Binder.java:285)
	at org.springframework.boot.context.properties.bind.AggregateElementBinder.bind(AggregateElementBinder.java:39)
	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.lambda$bindEntries$0(MapBinder.java:118)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) 
 	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.bindEntries(MapBinder.java:117)
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:69)
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:57)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:288)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:415)
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:287)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:245)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$0(Binder.java:283)
	at org.springframework.boot.context.properties.bind.Binder$Context.withSource(Binder.java:390)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$1(Binder.java:285)
	at org.springframework.boot.context.properties.bind.AggregateElementBinder.bind(AggregateElementBinder.java:39)
	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.lambda$bindEntries$0(MapBinder.java:118)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) 
 	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.bindEntries(MapBinder.java:117)
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:69)
...
	at org.springframework.boot.context.properties.bind.AggregateElementBinder.bind(AggregateElementBinder.java:39)
	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.lambda$bindEntries$0(MapBinder.java:118)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) 
    at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.bindEntries(MapBinder.java:117)
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:69)
...
	at org.springframework.boot.context.properties.bind.AggregateElementBinder.bind(AggregateElementBinder.java:39)
	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.lambda$bindEntries$0(MapBinder.java:118)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) 
    at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.bindEntries(MapBinder.java:117)
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:69)
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:57)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:288)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:415)
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:287)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:245)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:198)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:187)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:143) 
    at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.reinitializeLoggingSystem(PropertySourceBootstrapConfiguration.java:119)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:110)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:366)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at de.knowis.cp.repository.RepositoryApplication.main(RepositoryApplication.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.reinitializeLoggingSystem(PropertySourceBootstrapConfiguration.java:119)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:110)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:366)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at de.knowis.cp.repository.RepositoryApplication.main(RepositoryApplication.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by wilkinsona** [comment] 2018-02-13 13:03
@mdeknowis Thanks, but I've been unable to reproduce the problem with the sample you've provided. I took the following steps when trying to do so:

1. Added the missing repository declarations in pom.xml to be able to use milestones
2. Updated src/main/filtered/boostrap.yml to configure logging levels as [suggested above](https://github.com/spring-projects/spring-boot/issues/11972#issuecomment-365248604)
3. Ran the application with `mvn spring-boot:run` and it started successfully

If you'd like us to spend some more time investigating your problem, please spend some time to reduce your sample to something that's minimal and that reproduces the problem without requiring any modification.

**Comment by mdeknowis** [comment] 2018-02-13 14:31
Hi!

i will minify the project further. But: the issue only occurs, if we start the app in kubernetes.

**Comment by mdeknowis** [comment] 2018-02-14 10:20
Hi!
It looks like, I found something 
[minimum-application.zip](https://github.com/spring-projects/spring-boot/files/1720539/minimum-application.zip)


Not working dependencies:
```xml
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>spring-cloud-kubernetes-core</artifactId>
      <version>0.1.6</version>
    </dependency>
```

Working one:
```xml
    <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes</artifactId>
    <version>0.2.0.RELEASE</version>
    </dependency>
```

I'm not sure, if it's really related with that one, especially, as we experience this issue somehow randomly on our kubernetes, never before in Eclipse, but now I was able to provoke it by reducing the maven dependencies also in Eclipse, and reducing further the dependencies I was able to reproduce it using `mvn spring-boot:run`, so I wonder, if it's really related to the dependencies, or if it's depending on any kind of list or map (holding converters, beans or something else), and how the elements are ordered in it.

**Comment by mdeknowis** [comment] 2018-02-14 14:02
Hi,

Not working dependencies:
```xml
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>spring-cloud-kubernetes-core</artifactId>
      <version>0.1.6</version>
    </dependency>
```

Working one:
```xml
    <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes</artifactId>
    <version>0.2.0.RELEASE</version>
    </dependency>
```

But if I add the dependency to read kubernetes config maps, it fails again:
```xml
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes</artifactId>
      <version>0.2.0.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-config</artifactId>
      <version>0.2.0.RELEASE</version>
    </dependency>
```

Then `mvn spring-boot:run` fails with the reported error:

```txt
***************************
APPLICATION FAILED TO START
***************************
 Description:
 Failed to bind properties under 'logging.level.de.knowis.cp' to java.util.Map&lt;java.lang.String, java.lang.Object&gt;:
     Reason: No converter found capable of converting from type [java.lang.String] to type [java.util.Map&lt;java.lang.String, java.lang.Object&gt;]
 Action:
 Update your application's configuration
```

Here are the sample projects, I created: 
[minimum-application.zip](https://github.com/spring-projects/spring-boot/files/1724241/minimum-application.zip)

**Comment by mdeknowis** [comment] 2018-02-14 14:16
I also updated the dependency to the last current snapshot provided by https://repo.spring.io/libs-snapshot-local :

```xml
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes</artifactId>
      <version>0.2.1.BUILD-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-config</artifactId>
      <version>0.2.1.BUILD-SNAPSHOT</version>
    </dependency>
```

But also with this dependency I get the same error.

**Comment by wilkinsona** [comment] 2018-02-15 10:33
Thanks for the minimal application. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/11892 and was fixed by https://github.com/spring-projects/spring-boot/commit/16b7dbf487f2fb033fb43b0fe2f2c52d53e87d82. If I update `spring-cloud-kubernetes-NotWorking` to use Spring Boot 2.0.0.BUILD-SNAPSHOT and Spring Cloud Finchley.BUILD-SNAPSHOT it starts successfully.

**Closed by wilkinsona** 2018-02-15 10:33 UTC
Labels: status: feedback-provided, status: waiting-for-triage
