### ISSUE TITLE
Spring upgrade issue

### ISSUE THREAD

**Issue by giri-teja** [spring-projects/spring-boot#22992] opened 2020-08-18 05:41 UTC
Recently we upgraded spring version, kept minimal dependency to run only one controller, facing issue like this

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.3.RELEASE)

2020-08-18 07:24:36.383  INFO 16032 --- [           main] com.abnamro.crf.ara.AppInitializer       : Starting AppInitializer on NLVHPRAABW31673 with PID 16032 (C:\Users\C53101\git\STACK_UPGRADE\ara\ARA_Web\target\classes started by C53101 in C:\Users\C53101\git\STACK_UPGRADE\ara\ARA_Web)
2020-08-18 07:24:36.387  INFO 16032 --- [           main] com.abnamro.crf.ara.AppInitializer       : No active profile set, falling back to default profiles: default
2020-08-18 07:24:37.817 ERROR 16032 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Error processing condition on org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.3.3.RELEASE.jar:2.3.3.RELEASE]
```

**Comment by snicoll** [comment] 2020-08-18 08:23
@giri-teja it's very hard to give you support with the information that you've shared. `spring-boot-actuator-autoconfigure` has a compile dependency on `spring-boot-actuator`. If you keep the former but explicitly exclude the latter, your project will be invalid. 

If you want some support, please take the time to build a small sample that reproduces the problem. You can share that with us as a zip attached to this issue or as a link to a GitHub repo.

**Comment by spring-issuemaster** [comment] 2020-08-25 08:24
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Davio** [comment] 2020-08-29 10:23
It would also help to show the logging with -Ddebug enabled.

**Comment by snicoll** [comment] 2020-08-29 10:41
@davio thank you for trying to help but the sample will allow us to get that information.

**Comment by spring-issuemaster** [comment] 2020-09-12 10:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-09-12 10:42 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
