### ISSUE TITLE
Spring boot doesn't include micrometer-registry-cloudwatch

### ISSUE THREAD

**Issue by cmakinen** [spring-projects/spring-boot#13981] opened 2018-08-02 12:20 UTC
`micrometer-registry-cloudwatch` isn't part of spring-boot dependencyManagement section. As of now, version has to be explicitly provided if it is to be used.

Here's the dependency management section where it is missing. 
https://github.com/spring-projects/spring-boot/blob/435c47925ec80f4f98e488400d79889eeedab8e3/spring-boot-project/spring-boot-dependencies/pom.xml#L868-L921

Spring-Boot versions tested: 2.0.4.RELEASE, 2.0.3.RELEASE

**Comment by snicoll** [comment] 2018-08-02 12:45
Thanks for the report @cmakinen. FYI we don't need an issue and a PR as one duplicates the other.

Duplicate of #13981

**Closed by snicoll** 2018-08-02 12:45 UTC
Labels: type: bug
