### ISSUE TITLE
server.context-path, management.port not respected in external tomcat container

### ISSUE THREAD

**Issue by aayushgupta** [spring-projects/spring-boot#4682] opened 2015-12-04 21:51 UTC
If I deploy my spring boot application war file to external tomcat container, it does not respect the context path and management port defined in the application.properties file. if there is no way for Boot to trigger external container to run management interfaces on different port, but is there any way to configure the same on external container explicitly.

**Comment by wilkinsona** [comment] 2015-12-04 22:22
The context path is determined by the servlet container. For example, Tomcat used the file name of the war copied into the web apps directory.

The management.path is a duplicate of #552

**Closed by wilkinsona** 2015-12-04 22:22 UTC
Labels: waiting-for-triage
