### ISSUE TITLE
Spring MVC @Validated validator being called twice

### ISSUE THREAD

**Issue by edeandrea** [spring-projects/spring-boot#8998] opened 2017-04-25 15:47 UTC
Moving from Spring MVC 4.3.7 to 4.3.8 (spring-boot 1.5.2 to 1.5.3) I notice that in my RestControllers we implement Spring's Validator interface, wire it into a controller using an @InitBinder method. Then in our controller action method we use the @Validated annotation on the request body attribute. With the move to 4.3.8 I see that our validator is being called twice instead of once.

I downgraded spring-boot to 1.5.2 and changed the version of Spring MVC to 4.3.8 (as suggested by @snicoll here: https://jira.spring.io/browse/SPR-15482) and the validator was only being fired once, so its not related to the version change between Spring 4.3.7 & 4.3.8.

**Comment by edeandrea** [comment] 2017-04-25 18:03
Here you go.

[spring-boot-multiple-validator.zip](https://github.com/spring-projects/spring-boot/files/956059/spring-boot-multiple-validator.zip)

**Comment by snicoll** [comment] 2017-04-25 20:20
Thanks for the sample (side note, making your sample fails out of the box is less confusing than showcasing what actually works. It took me some time to figure out why I couldn't reproduce the problem until I relialized your sample was using 1.5.2).

Anyway, I've confirmed this is a duplicate of #8979. Thanks for taking the time to build a sample, much appreciated.

**Closed by snicoll** 2017-04-25 20:20 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by edeandrea** [comment] 2017-04-25 20:29
Sorry about that - I've taken note for the next time. After reading #8979 it may be that change that broke it (so it is related) but this seems like a different side-effect. I appreciate how quick you were able to look into it.

It may not seem like a big deal that validation routines are running more than once, but we have a customized FaultBarrier which catches these errors and returns a standardized payload. These payloads now have extra "stuff" in them that shouldn't be there.

Is there a workaround I can use? Or should I simply downgrade back to 1.5.2?

**Comment by snicoll** [comment] 2017-04-25 20:41
> Is there a workaround I can use? Or should I simply downgrade back to 1.5.2?

We consider this issue very serious. As soon as I get the necessary review from other team members, I intend to release 1.5.4 with a fix. I hope to do that this week still.

You can workaround that particular issue in the meantime by registering a second `Validator`. If there are more than one bean in the context, then you'll bypass the faulty condition. For instance, adding this to your app:

```java
@Component
public class DummyValidator implements Validator {

	@Override
	public boolean supports(Class<?> clazz) {
		return false;
	}

	@Override
	public void validate(Object target, Errors errors) {

	}
}
```

Another option is to not register your `DemoValidator` as a @Bean but that's more involved that this simple (stupid) hack.

**Comment by edeandrea** [comment] 2017-04-25 20:43
Appreciate the quick response. If you consider it serious and will be releasing 1.5.4 with a fix (relatively) soon then I'll just wait for it while downgrading back to 1.5.2. I'm OCD and don't like (stupid) hack code in my codebase :)
