### ISSUE TITLE
While running Spring batch from CommandLineJobRunner datasource Driver class not identifying

### ISSUE THREAD

**Issue by padamatavijji** [spring-projects/spring-boot#25530] opened 2021-03-06 11:10 UTC
While running Spring batch from CommandLineJobRunner datasource Driver class not identifying
Iam using the command java -jar .\batchsample-0.0.1.jar JobClass JobName
If i remove main-class property from bootJar then jar is running like spring boot application. No errors

 Error creating bean with name 'org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration': Unsatisfied dependency expressed through field 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class

**Comment by wilkinsona** [comment] 2021-03-06 13:19
Without knowing how you've built the jar file, I don't think we can figure out for certain why this isn't working. If you're trying to use a Spring Boot fat jar and you've customized the `Main-Class` attribute in the manifest, Spring Boot's launcher won't be adding everything in `BOOT-INF/lib` to the classpath. However, if that were the case I'd expect to see a failure occur earlier than the one that you're apparently seeing. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by padamatavijji** [comment] 2021-03-09 03:37
Yes I am doing the spring boot fat jar and customized the main-class attribute in manifest.  
As you said spring boot not adding driver classes. How to overcome this is there any way to execute spring boot with spring batch command line runner.
```
bootJar {
    archiveBaseName = rootProject.name.toLowerCase().replaceAll(' ', '-')
    archiveVersion = "$allprojects.version"
    mainClass= "org.springframework.batch.core.launch.support.CommandLineJobRunner"
}

**Comment by spring-projects-issues** [comment] 2021-03-16 09:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-03-23 09:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-03-23 09:37 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
