### ISSUE TITLE
 All providers must be registered and verified in the Native Image builder?

### ISSUE THREAD

**Issue by wghdir** [spring-projects/spring-boot#36395] opened 2023-07-13 04:12 UTC
I use bouncycastle1.69,it can run in jar,but run error in native image.
I have regist hints.the demo is in https://github.com/wghdir/smdemo.git.
How can i do?
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Trying to verify a provider that was not registered at build time: BC version 1.59. All providers must be registered and verified in the Native Image builder.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@17.0.6/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:380)
        at java.base@17.0.6/javax.crypto.Cipher.getInstance(Cipher.java:718)
        at java.base@17.0.6/javax.crypto.Cipher.getInstance(Cipher.java:642)
        at com.example.demo.SM4Util.encrypt(SM4Util.java:92)
        at com.example.demo.SmdemoApplication.sm4Test(SmdemoApplication.java:25)
        at com.example.demo.SmdemoApplication.main(SmdemoApplication.java:21)

**Comment by wilkinsona** [comment] 2023-07-13 08:02
This problem isn't specific to Spring Boot and as such this is the wrong issue tracker. Your issue appears to be a duplicate of https://github.com/oracle/graal/issues/3197.

**Closed by wilkinsona** 2023-07-13 08:02 UTC
Labels: status: waiting-for-triage
