### ISSUE TITLE
Add smoke test with Spring Session and Hazelcast

### ISSUE THREAD

**Issue by pmverma** [spring-projects/spring-boot#27793] opened 2021-08-21 07:57 UTC
With SB 2.4.7 and spring (session+hazelcast) 2.5.2, I was expecting the `sessions` endpoint to work properly.
In trace log there is,
```
   SessionsEndpointAutoConfiguration#sessionEndpoint:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.session.FindByIndexNameSessionRepository; SearchStrategy: all) did not find any beans of type org.springframework.session.FindByIndexNameSessionRepository (OnBeanCondition)

```
But `Hazelcast4IndexedSessionRepository` is already there implementing `FindByIndexNameSessionRepository`

The endpoints docs mention only the following which is already set up in my case.
```
Allows retrieval and deletion of user sessions from a Spring Session-backed session store. Requires a Servlet-based web application using Spring Session.

```

**Comment by snicoll** [comment] 2021-08-22 07:01
@pmverma can you please share a small minimal sample that showcases the problem you've described. You can do so by attaching a zip to this issue or pushing the project on a GitHub repository.

**Comment by vpavic** [comment] 2021-08-22 08:07
@snicoll I was able to reproduce this using my [Spring Session samples repo](https://github.com/vpavic/spring-session-samples) - use `sample-httpsession-hazelcast` subproject.

I think this is actually a bug in Spring Session that was introduced together with the support for Hazelcast 4, when the return type of `@Bean` factory method in `HazelcastHttpSessionConfiguration` was changed to return `SessionRepository<?>` (see [here](https://github.com/spring-projects/spring-session/commit/0ab781e53719621acf20c8880c7ca62e1bd85b6d#diff-01afbb9e544db8babebcd1baf31b03178089ba297ac8540c7aa186c308a07cbcR88)). I can look into this from Spring Session side tomorrow.

**Comment by wilkinsona** [comment] 2021-09-06 08:35
They are not. IIRC, the profiles are a fairly direct translation of what we used to have with Maven. They need to be enabled as part of a manual build.

**Comment by vpavic** [comment] 2021-09-07 07:17
I see, so in reality those profiles don't add much value having in mind these are _smoke tests_. But I understand that historically they've been samples (or at least were named as such) so in that context profiles would be of more use.

Either way, what's your take on ensuring that Actuator integration for Spring Session gets smoke tested across all the session stores Spring Boot provides auto-config for? Even though there are some tests on Spring Session side now, the integration is owned by Spring Boot so it makes sense that things primarily get smoke tested here.

**Comment by kandulsh** [comment] 2021-10-01 18:35
Would like to work on this issue.

**Comment by mbhave** [comment] 2021-10-05 20:27
Closing in favor of PR #28173.

**Closed by mbhave** 2021-10-05 20:27 UTC
Labels: type: task, status: reserved-for-conference-event

**Comment by vpavic** [comment] 2021-10-08 10:37
I think this should be reopened (and a bit repurposed) because the [my previous comment](#issuecomment-914054036) raised some concerns that weren't addressed. I really think it would be valuable to have smoke tests that verify actuator integration for all the supported session stores.
