### ISSUE TITLE
SpringBoot Dev Tools DataSouceAutoconfiguration eagerly instantiate beans

### ISSUE THREAD

**Issue by lislon** [spring-projects/spring-boot#13327] opened 2018-06-01 11:37 UTC
My app has a XML bean definition like this: 
```xml
    <bean class="org.springframework.beans.factory.config.MethodInvokingFactoryBean" lazy-init="true">
        <property name="staticMethod"
                  value="com.mycompany.MyClass.myStaticMethod"/>
        <property name="arguments">
            <list>
                <value>${myPropertyName:true}</value>
            </list>
        </property>
    </bean>
```
When I use DevTools, the class `DevToolsDataSourceCondition` tries to find a `DataSource` bean, but it do it in eargerly manner, invoking factory beans.

It instantiates my `MethodInvokingFactoryBean` too early, before `${myPropertyName:true}` is resolved by `BeanFactoryPostProcessor`.

In my understanding the issue is here `org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration.DevToolsDataSourceCondition`:
```java
		@Override
		public ConditionOutcome getMatchOutcome(ConditionContext context,
				AnnotatedTypeMetadata metadata) {
			ConditionMessage.Builder message = ConditionMessage
					.forCondition("DevTools DataSource Condition");
                        // This instantiates my factory beans too early
			String[] dataSourceBeanNames = context.getBeanFactory()
					.getBeanNamesForType(DataSource.class);
```
Spring boot version: 2.0.1.RELEASE

**Comment by wilkinsona** [comment] 2018-06-01 11:44
Thanks for the report and analysis. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/11048.

**Closed by wilkinsona** 2018-06-01 11:44 UTC
Labels: status: waiting-for-triage
