### ISSUE TITLE
Javascript css stops loading at any time 

### ISSUE THREAD

**Issue by pratt8084** [spring-projects/spring-boot#26224] opened 2021-04-23 21:23 UTC
we have deployed the springboot based jar file(with embedded undertow server) on one of our linux server and at any point of time the javascript and css stops loading and our application stops working.

Also when i tried inspect in google chrome resources from static folder shows null pointer exception ie error 500.

Please let us know what can be the cause as it occurs very frequently nowadays.

Thanks in Advance.

**Comment by philwebb** [comment] 2021-04-23 21:53
I'm afraid there's not enough information here to diagnose the problem. Please provide a small sample application as a zip file or github project that replicates the issue.

**Comment by spring-projects-issues** [comment] 2021-04-30 21:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by pratt8084** [comment] 2021-05-04 05:49
sorry i cant provide the sample application as it is our internal and beyond our scope due to organisation policies

**Comment by snicoll** [comment] 2021-05-04 06:02
@pratt8084 we're not asking for your application but a sample you'd build that reproduces the problem. This technical problem could be extracted in something minimal that has no visible link to your organisation. Without the sample, we can't really justify spending time based on the description you've provided.

**Comment by spring-projects-issues** [comment] 2021-05-18 06:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-05-18 06:03 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
