### ISSUE TITLE
SpringApplicationShutdownHandlers do not run in deterministic order

### ISSUE THREAD

**Issue by betalb** [spring-projects/spring-boot#43430] opened 2024-12-05 18:33 UTC
Spring Boot version: tested on 3.2.12 and 3.4.0

This issue was mostly resolved in [#40178](https://github.com/spring-projects/spring-boot/issues/40178), but one edge case still left.

When app receives `SIGTERM` during application startup after `ApplicationEnvironmentPreparedEvent`, but before `ApplicationContextInitializedEvent`, Log4j2 (and other logging systems) will run shutdown handler in `SpringApplicationShutdownHook`, i.e. the one that is returned by `org.springframework.boot.logging.log4j2.Log4J2LoggingSystem#getShutdownHandler`. During shutdown it will try to read some properties (i.e. `log4j2.disable.jmx`) from `SpringEnvironmentPropertySource` which still holds reference to underlying environment.

Attaching small repro of this issue: [sample-app.tar.gz](https://github.com/user-attachments/files/18028011/sample-app.tar.gz)

**Comment by wilkinsona** [comment] 2024-12-12 15:54
Thanks for the sample, @betalb. It has left me wondering what the real-world problem might be as closing a property source and throwing an exception from it seems a little bit artificial. Can you please describe the symptom that you saw in your real app that led to you creating a sample that fails in the manner that it does?

**Comment by betalb** [comment] 2024-12-12 18:14
Yes, this example is really artificial. In our real case we are getting a deadlock.

Our property source, that we are trying to close, is reading properties over unix socket. If socket is not yet available, getProperty will get stuck in wait until it appears. What happens in our specific case:

1) app is launched while socket is not available
2) shutdown hook is registered via SpringApplicationShutdownHook (not explicitly, but because spring is starting to read properties during context startup)
3) app startup is suspended, waiting for socket to become available 
4) app receives SIGTERM
5) SpringApplicationShutdownHook starts executing registered callbacks: one of them is log4j2 handler and other is ours, that releases the lock and interrupts the thread which is waiting for socket file

The problem is that log4j2 handler tries to read some properties and if it is executed 1st, it will be blocked by our property source, which was not yet signaled that application is shutting down. Even though, I see that actions list that are executed by [`SpringApplicationShutdownHook.run`](https://github.com/spring-projects/spring-boot/blob/65a862c13c022fd368eb3d2b1b999001d00b8a94/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplicationShutdownHook.java#L112) is wrapped into LinkedHasSet, original set of actions is backed by IdentityHashMap, so in the end the order is not defined and I can't overcome this problem by registering own shutdown hook before log4j2.

We also can't rely on other application events, because they won't be fired, as app context haven't started yet.

In following scenario problem won't occur in spring boot >= 3.2.5 and >= 3.1.11 https://github.com/spring-projects/spring-boot/commit/a946f66e7c6dad2668031559aa4e5b8e00bf651d:
1) we launch app when socket file is already available
2) app fully launches
3) socket file is removed
4) app receives SIGTERM
5) app is terminated gracefully

In this case [`LoggingApplicationListener.cleanupLoggingSystem`](https://github.com/spring-projects/spring-boot/blob/65a862c13c022fd368eb3d2b1b999001d00b8a94/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/logging/LoggingApplicationListener.java#L274) will be called as reaction to `ContextClosedEvent` or `ApplicationFailedEvent`, so while executing `SpringApplicationShutdownHook.run` log4j2 won't have access to environment, won't hit our property source and won't be blocked.

**Comment by wilkinsona** [comment] 2024-12-13 09:46
Thanks for the additional details. Unfortunately, I don't understand how your application is getting into the described situation. If a `PropertySource` that blocks is registered (either through a custom environment or an environment post-processor), I would expect it to start blocking very early and before the logging system is initialized. In my experimentation, that blocking occurs during environment post-processing:

```
java.lang.Exception
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication$TestPropertySource.getProperty(SpringBootSigtermApplication.java:88)
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication$TestPropertySource.getProperty(SpringBootSigtermApplication.java:1)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.getConfigurationProperty(SpringConfigurationPropertySource.java:84)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource.findConfigurationProperty(ConfigurationPropertySourcesPropertySource.java:70)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.findPropertyValue(ConfigurationPropertySourcesPropertyResolver.java:91)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:75)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:66)
	at org.springframework.core.env.AbstractPropertyResolver.getProperty(AbstractPropertyResolver.java:191)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:573)
	at org.springframework.boot.reactor.ReactorEnvironmentPostProcessor.postProcessEnvironment(ReactorEnvironmentPostProcessor.java:59)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:132)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:115)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:353)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149)
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication.main(SpringBootSigtermApplication.java:60)
```

I don't think we'll be able to make a change here without a complete understanding of the problem. There's a risk of regression and that's hard to justify unless we can be confident that any change will fix the problem.

Can you please provide a sample that recreates the deadlock? Perhaps you could synthesise the role of the socket by waiting for a latch or similar that's never counted down?

**Comment by betalb** [comment] 2024-12-13 12:32
In my case, property source is registered in `ApplicationEnvironmentPreparedEvent` listener, it has priority lower than `LoggingApplicationListener`, so logging is already initialized by that time.

Registration in `ApplicationEnvironmentPreparedEvent` listener works only with environment classes from spring-core, spring-boot versions of environments won't reflect changes to property source list after it was created.

I've updated sample app [sample-app-v2.tar.gz](https://github.com/user-attachments/files/18126307/sample-app-v2.tar.gz). This time issue reproducibility depends on `IdentityHashMap`. On my setup, issue can be reproduced. Also instead of blocking, I'm throwing exception if property source was not yet closed. So any access to TestPropertySource with produce an exception until it's closed.

```
➜  sample-app java -version
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (build 17.0.12+7, mixed mode)
➜  sample-app uname -a
Darwin ip-192-168-1-97.ec2.internal 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 arm64
```

But, just in case, I've placed patched `SpringApplicationShutdownHook.java` + it's diff with version from main `SpringApplicationShutdownHook.java.diff` in archive. Patched version is based on `LinkedHashSet` for actions storage.

**Comment by wilkinsona** [comment] 2024-12-13 15:01
Thanks. With that latest information, I think I may have reproduced what you have described using the following:

```
package com.pleeco.core.springbootsigterm;

import java.util.concurrent.CountDownLatch;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent;
import org.springframework.boot.context.logging.LoggingApplicationListener;
import org.springframework.context.ApplicationListener;
import org.springframework.core.Ordered;
import org.springframework.core.env.PropertySource;

@SpringBootApplication
public class SpringBootSigtermApplication {

    public static void main(String[] args) {
        new SpringApplicationBuilder(SpringBootSigtermApplication.class)
            .listeners(new TestApplicationListener())
            .run(args);
    }

    static class TestApplicationListener implements ApplicationListener<ApplicationEnvironmentPreparedEvent>, Ordered {
        
        @Override
        public int getOrder() {
            return LoggingApplicationListener.DEFAULT_ORDER + 10;
        }

        @Override
        public void onApplicationEvent(ApplicationEnvironmentPreparedEvent event) {
            event.getEnvironment().getPropertySources().addLast(new TestPropertySource("test"));
        }
        
    }

    static class TestPropertySource extends PropertySource<Object> {
        
        private final CountDownLatch socketAvailable = new CountDownLatch(1);

        public TestPropertySource(String name) {
            super(name);
        }

        @Override
        public String getProperty(String name) {
            try {
                this.socketAvailable.await();
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
            return null;
        }

    }

}
```

When the application's started, the `main` thread is blocked:

```
"main" #1 prio=5 os_prio=31 cpu=691.72ms elapsed=13.61s tid=0x00007f8eb480d400 nid=0x2803 waiting on condition  [0x00007000100e3000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.10/Native Method)
	- parking to wait for  <0x000000061ecf52b8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.10/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.10/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.10/AbstractQueuedSynchronizer.java:1047)
	at java.util.concurrent.CountDownLatch.await(java.base@17.0.10/CountDownLatch.java:230)
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication$TestPropertySource.getProperty(SpringBootSigtermApplication.java:47)
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication$TestPropertySource.getProperty(SpringBootSigtermApplication.java:1)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.getConfigurationProperty(SpringConfigurationPropertySource.java:84)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource.findConfigurationProperty(ConfigurationPropertySourcesPropertySource.java:70)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.findPropertyValue(ConfigurationPropertySourcesPropertyResolver.java:91)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:75)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:61)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:557)
	at org.springframework.boot.context.FileEncodingApplicationListener.onApplicationEvent(FileEncodingApplicationListener.java:61)
	at org.springframework.boot.context.FileEncodingApplicationListener.onApplicationEvent(FileEncodingApplicationListener.java:48)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at org.springframework.boot.SpringApplicationRunListeners$$Lambda$153/0x000000013810e9d8.accept(Unknown Source)
	at java.lang.Iterable.forEach(java.base@17.0.10/Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:353)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149)
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication.main(SpringBootSigtermApplication.java:19)
```

If I send `SIGTERM` to the process, it does not exit. Instead, it's stuck. `main` remains blocked as before. Additionally, `SIGTERM handler` is now blocked waiting for the `SpringApplicationShutdownHook` thread to complete. `SpringApplicationShutdownHook` is blocked waiting for the "socket" to become available:

```
"SIGTERM handler" #19 daemon prio=9 os_prio=35 cpu=0.38ms elapsed=2.96s tid=0x00007f8eb5823c00 nid=0x6107 in Object.wait()  [0x0000700011317000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.10/Native Method)
	- waiting on <0x000000061ecf1138> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@17.0.10/Thread.java:1313)
	- locked <0x000000061ecf1138> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@17.0.10/Thread.java:1381)
	at java.lang.ApplicationShutdownHooks.runHooks(java.base@17.0.10/ApplicationShutdownHooks.java:107)
	at java.lang.ApplicationShutdownHooks$1.run(java.base@17.0.10/ApplicationShutdownHooks.java:46)
	at java.lang.Shutdown.runHooks(java.base@17.0.10/Shutdown.java:130)
	at java.lang.Shutdown.exit(java.base@17.0.10/Shutdown.java:173)
	- locked <0x00000007ffb020b8> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(java.base@17.0.10/Terminator.java:51)
	at jdk.internal.misc.Signal$1.run(java.base@17.0.10/Signal.java:219)
	at java.lang.Thread.run(java.base@17.0.10/Thread.java:840)

"SpringApplicationShutdownHook" #17 prio=5 os_prio=31 cpu=2.04ms elapsed=2.96s tid=0x00007f8eb5824200 nid=0x5b07 waiting on condition  [0x000070001161c000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.10/Native Method)
	- parking to wait for  <0x000000061ecf52b8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.10/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.10/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.10/AbstractQueuedSynchronizer.java:1047)
	at java.util.concurrent.CountDownLatch.await(java.base@17.0.10/CountDownLatch.java:230)
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication$TestPropertySource.getProperty(SpringBootSigtermApplication.java:47)
	at com.pleeco.core.springbootsigterm.SpringBootSigtermApplication$TestPropertySource.getProperty(SpringBootSigtermApplication.java:1)
	at org.springframework.boot.context.properties.source.SpringConfigurationPropertySource.getConfigurationProperty(SpringConfigurationPropertySource.java:84)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource.findConfigurationProperty(ConfigurationPropertySourcesPropertySource.java:70)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.findPropertyValue(ConfigurationPropertySourcesPropertyResolver.java:91)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:75)
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:61)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:557)
	at org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource.getProperty(SpringEnvironmentPropertySource.java:45)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.sourceGetProperty(PropertiesUtil.java:560)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.lambda$get$1(PropertiesUtil.java:542)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment$$Lambda$39/0x000000013801ea48.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(java.base@17.0.10/ReferencePipeline.java:197)
	at java.util.stream.SortedOps$RefSortingSink.end(java.base@17.0.10/SortedOps.java:400)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(java.base@17.0.10/AbstractPipeline.java:528)
	at java.util.stream.AbstractPipeline.copyInto(java.base@17.0.10/AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@17.0.10/AbstractPipeline.java:499)
	at java.util.stream.FindOps$FindOp.evaluateSequential(java.base@17.0.10/FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(java.base@17.0.10/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(java.base@17.0.10/ReferencePipeline.java:647)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:545)
	at org.apache.logging.log4j.util.PropertiesUtil$Environment.access$500(PropertiesUtil.java:496)
	at org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:444)
	at org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:188)
	at org.apache.logging.log4j.core.jmx.internal.JmxUtil.isJmxDisabled(JmxUtil.java:29)
	at org.apache.logging.log4j.core.LoggerContext.unregisterJmxBeans(LoggerContext.java:408)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:375)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:135)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.lambda$getShutdownHandler$2(Log4J2LoggingSystem.java:429)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem$$Lambda$274/0x0000000138187cd8.run(Unknown Source)
	at org.springframework.boot.SpringApplicationShutdownHook$$Lambda$277/0x000000013818d780.accept(Unknown Source)
	at java.lang.Iterable.forEach(java.base@17.0.10/Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.lang.Thread.run(java.base@17.0.10/Thread.java:840)
```

Is this an accurate reproduction of the problem that you're seeing?

**Comment by betalb** [comment] 2024-12-13 16:03
Yes, that's exactly the problem that I observe.

My initial idea was to:
* make PropertySource Closeable that calls socketAvailable.countDown() in close() and flags PropertySource as "closed"
* register TestPropertySource::close as ShutdownHandler of SpringApplication

But it fails due to undefined other of execution of shutdown handlers.

* property source close, than Log4j2 close -> works
* Log4j2 close, than property source close -> blocks

While trying to find a solution, I've patched [`LoggingApplicationListener.registerShutdownHookIfNecessary`](https://github.com/spring-projects/spring-boot/blob/65a862c13c022fd368eb3d2b1b999001d00b8a94/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/logging/LoggingApplicationListener.java#L420) and added a call to LoggingApplicationListener.cleanupLoggingSystem before logging's system shutdownHandler implementation. This approach worked out pretty well. In this case order of execution of shutdown handlers doesn't matter, as Log4j2 won't try to access TestProperty source.

**Comment by ppkarwasz** [comment] 2024-12-14 09:55
Note that Log4j 2.24.0 and later ignores exceptions thrown by property sources (see apache/logging-log4j2#2454), so it shouldn't be affected by this problem.
In version 2.24.3 we also added protection against recursive calls to `PropertiesUtil` (see apache/logging-log4j2#3252). The latter kind of problems occurs if a property source (in the specific case `JndiPropertySource`) starts performing logging calls that end up calling `PropertiesUtil`.

**Comment by philwebb** [comment] 2024-12-17 01:17
Reopening because I'd like @wilkinsona to review the change and also consider if we should additionally support `Ordered`.

**Comment by wilkinsona** [comment] 2024-12-17 07:51
I don't think we need to support ordered but I do wonder if we should call the handlers in the reverse of their addition order. It makes sense to me that the later something is "started" and adds its handler then the earlier it should be called to clean up during shutdown.

**Closed** 2024-12-17 17:51 UTC
Labels: type: bug
