### ISSUE TITLE
Actuator /actuator endpoint contains links to disabled Spring Cloud endpoints

### ISSUE THREAD

**Issue by maxromanovsky** [spring-projects/spring-boot#5389] opened 2016-03-10 13:02 UTC
HATEOAS `/actuator` endpoint renders `spring-cloud-context` endpoints even if they are disabled (`actuator.*.enabled=false` in `application.properties`). [Build-in endpoints](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints) are not rendered if disabled.

Example:

```
endpoints.pause.enabled=false
endpoints.refresh.enabled=false
```

but the `/actuator` endpoint contains them. Excerpt from output:

``` json
{
    "_links": {
        "pause": {
            "href": "http://localhost:8080/pause"
        },
        "refresh": {
            "href": "http://localhost:8080/refresh"
        }
    }
}
```

I've added this issue to the Spring Boot project instead of Spring Cloud per @dsyer recommendation in https://github.com/spring-cloud/spring-cloud-commons/issues/109#issuecomment-216482742

**Comment by wilkinsona** [comment] 2016-03-30 15:59
I can't reproduce this. With the following properties:

```
endpoints.info.enabled=false
endpoints.health.enabled=false
endpoints.configprops.enabled=false
endpoints.mappings.enabled=false
endpoints.metrics.enabled=false
endpoints.trace.enabled=false
endpoints.env.enabled=false
endpoints.beans.enabled=false
endpoints.dump.enabled=false
endpoints.autoconfig.enabled=false
```

I only get a self link from `/actuator`:

```
$ curl localhost:8080/actuator
{"_links":{"self":{"href":"http://localhost:8080/actuator"}}}
```

@maxromanovsky Can you provide a sample project that illustrates the problem?

**Comment by maxromanovsky** [comment] 2016-04-02 06:30
@wilkinsona, sorry. I'm in a hospital right now, so I'll be able to provide feedback approx. in a month

**Comment by wilkinsona** [comment] 2016-04-02 08:00
Sorry to hear that. Get well soon. We can come back to this when you're ready.

**Comment by maxromanovsky** [comment] 2016-04-26 16:59
I've figured out that it's specific to Spring Cloud endpoints and created an issue in the proper repo: https://github.com/spring-cloud/spring-cloud-commons/issues/109

**Comment by maxromanovsky** [comment] 2016-05-06 07:09
Reopening the issue per [comment](https://github.com/spring-cloud/spring-cloud-commons/issues/109#issuecomment-216482742) from @dsyer:
> Interestingly, this is semi-intentional because endpoints can always be enabled at runtime, so it is better to provide the resource and make it send a "disabled" response than to not create it at all. I can see why it arguably should be otherwise, and ultimately we should be consistent with Spring Boot, but I'm not really willing to make the change here right now. Perhaps the Spring Boot issue should be re-opened.

**Comment by wilkinsona** [comment] 2016-05-06 07:52
The intention doesn't make sense to me. One of the main benefits of HATEOAS is that the links are representative of the application's state. If an endpoint is disabled, the response should reflect that state by not providing a link to the endpoint.

I'm not sure what Spring Boot alone can do to fix this. @dsyer what did you anticipate happening as a result of this issue being re-opened?

**Comment by dsyer** [comment] 2016-05-06 10:07
I didn't really anticipate anything. The endpoints are actually there in the Cloud case (for those custom endpoints added by Spring Cloud), but they return an error saying they are disabled. Couldn't the component that creates the links check for "enabled=true" before rendering each one?

**Comment by wilkinsona** [comment] 2016-05-06 10:35
@dsyer All that `MvcEndpointAdvice` knows is that it's dealing with an `MvcEndpoint`. There's no way for it to know whether or not the endpoint is enabled as it doesn't know the name of the property, if any, that controls it. In Boot, we don't create then endpoint if it's disabled which avoids the problem we're seeing with Spring Cloud. Perhaps we need to add `isEnabled` to `MvcEndpoint`, or introduce a new `DynamicMvcEndpoint` that extends `MvcEndpoint` and has `isEnabled` on it?

**Comment by dsyer** [comment] 2016-05-06 11:06
`MvcEndpoint` has a `DISABLED_RESPONSE`. So we already sort of admit that an `MvcEndpoint` is allowed to know whether it is delegating to something that is disabled. So maybe the extra boolean property is a good idea. For compatibility reasons it will probably have to be implemented as a new interface.

**Comment by wilkinsona** [comment] 2017-07-29 20:02
This will be addressed by the new endpoint infrastructure that's planned for M4. When an endpoint is disabled, no beans will be created and, therefore, there will be no links to it.

**Closed** 2017-08-11 15:39 UTC
Labels: priority: normal, theme: actuator, type: bug
