### ISSUE TITLE
logging.file not working in 2.3.0

### ISSUE THREAD

**Issue by barryku** [spring-projects/spring-boot#21627] opened 2020-05-30 05:21 UTC
No log file was created for my new app using 2.3.0. It started working again after changing to 2.2.6.  I also tested 2.2.7, and it works fine as well.  I get the following log for 2.2.6 and 2.2.7, but not in 2.3.0,

`LOGBACK: No context given for c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1132967838`

Steps to reproduce this isssue,

1. create a project at https://start.spring.io/ using default values for everything
2. update application.properties by adding,  logging.file=demo.log
3. mvn spring-boot:run
4. no demo.log generated
5. update pom.xml by changing 2.3.0.RELEASE to 2.2.7.RELEASE
6. mvn spring-boot:run

demo.log was created properly.

**Comment by spencergibb** [comment] 2020-05-30 05:54
https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/spring-boot-features.html#boot-features-logging-file-output

**Comment by wilkinsona** [comment] 2020-05-30 06:16
Thanks, @spencergibb.

This is a duplicate of https://github.com/spring-projects/spring-boot/issues/21479.

**Closed by wilkinsona** 2020-05-30 06:16 UTC
Labels: status: waiting-for-triage
