### ISSUE TITLE
Misleading error message in ApplicationContextServerWebExchangeMatcher#createContext

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#13783] opened 2018-07-16 13:41 UTC
`ApplicationContextServerWebExchangeMatcher#createContext` has a misleading exception message when the `ApplicationContext` on a `ServerWebExchange` is `null`

> No WebApplicationContext found.

The reason why it's misleading is that `WebApplicationContext` is the base contract for Spring MVC.

**Comment by snicoll** [comment] 2018-07-17 09:46
Looking at `ApplicationContextServerWebExchangeMatcher` a bit more, I think we should take the opportunity to review this class altogether.

**Comment by aheritier** [comment] 2018-07-17 15:55
@snicoll please see this sample : https://github.com/aheritier/springboot-sample/compare/sb-13783?expand=1
Extracted from a real project I tried to remove as much things as possible. Adding the annotation @AutoConfigureWebTestClient broke the test (at the end this one is useless but it's annoying and hard to troubleshoot)

**Comment by snicoll** [comment] 2018-07-17 16:05
Thanks @aheritier - I can reproduce. Spring Cloud Gateway is not necessary. However, I don't have this error as soon as I remove Spring Security from the classpath.

**Comment by aheritier** [comment] 2018-07-17 16:21
hi @snicoll yes I didn't try to remove all the dependencies I have in my real project. I already removed spring data and few others that I considered out of the scope.
For sure in my project I'm trying to use Spring Cloud Gateway (to use use it as a reverse proxy for another "service" - kibana on AWS) and this is because of it that I'm trying to see if moving from springmvc to webflux is complex because it doesn't work with the first one
Spring security is used for the basic auth right now

**Comment by mbhave** [comment] 2018-07-17 19:51
The root cause of the error in the sample is [this bug](https://jira.spring.io/browse/SPR-16972) in Spring Framework which has been fixed now. The latest Spring Boot snapshot has the fix. 

We will use this issue to avoid the use of `WebApplicationContext` in the exception message.

**Closed** 2018-07-18 00:09 UTC
Labels: type: bug
