### ISSUE TITLE
Embedded undertow does not work with Java7

### ISSUE THREAD

**Issue by Tera** [spring-projects/spring-boot#4821] opened 2015-12-21 10:54 UTC
Hi

I've just upgraded from Spring Boot 1.3.0 to 1.3.1 by simply change gradle dependency 

	dependencies {
            classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.3.0.RELEASE'
        }

to

	dependencies {
            classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.3.1.RELEASE'
        }

If i stat my application, context starts correctly without any error, but if i try to query any of my REST endpoints  or actuator's /health or /env browser returns ERR_EMPTY_RESPONSE.

If i change from spring-boot-starter-undertow to spring-boot-starter-jetty everything works fine.

I haven't found any additional configuration for undertow webserver in documentation so i think is a spring boot bug

**Comment by snicoll** [comment] 2015-12-21 11:40
Hey, it's quite hard to answer without knowing more about your app and its dependencies. Can you tell us a bit more (a sample project would be even better).

**Comment by Tera** [comment] 2015-12-21 14:29
Sure is not a problem

My sample project is made with this build.gradle



        apply plugin: 'maven'
        apply plugin: 'java'
        apply plugin: 'spring-boot'

		buildscript {
			repositories {
				mavenCentral()
				jcenter()
				maven {url "http://repo.spring.io/libs-release" }
			}

			dependencies {
		            classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.3.1.RELEASE'
		            classpath 'org.springframework:springloaded:1.2.4.RELEASE'
		        }
		}


		repositories {
			mavenCentral()
			jcenter()
		}

		configurations.all {
		    exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
		}

		dependencies {
			compile 'org.springframework.boot:spring-boot-starter-web'
			compile 'org.springframework.boot:spring-boot-starter-actuator'

			compile 'org.springframework.boot:spring-boot-starter-undertow'

			testCompile 'org.springframework.boot:spring-boot-starter-test'
		}

this is my boot application class:



    package org.skeleton;

    import org.springframework.boot.SpringApplication;
    import org.springframework.boot.autoconfigure.SpringBootApplication;
    import org.springframework.boot.context.web.SpringBootServletInitializer;

    @SpringBootApplication
    public class SkeletonApp extends SpringBootServletInitializer {

        public static void main(final String[] args) throws Throwable {
            SpringApplication.run(SkeletonApp.class, args);
        }
    }

and this is my controller



      package org.skeleton.controller;

      import org.springframework.web.bind.annotation.RequestMapping;
      import org.springframework.web.bind.annotation.RestController;

      @RestController
      public class HomeController {
          
          @RequestMapping()
          public String home() {
              return "Skeleton 1.0";
          }
      }


With this configuration if a run gradle bootrun this is the output


        .   ____          _            __ _ _
        /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
        ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
        \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
        '  |____| .__|_| |_|_| |_\__, | / / / /
        =========|_|==============|___/=/_/_/_/
        :: Spring Boot ::        (v1.3.1.RELEASE)

        2015-12-21 15:19:10.292  INFO 8800 --- [           main] org.skeleton.SkeletonApp       : Starting SkeletonApp on Mac-Massera.local with PID 8800 (started by stefano.massera in /Users/stefano.massera/Progetti/john-doe copia/service)
        2015-12-21 15:19:10.299  INFO 8800 --- [           main] org.skeleton.SkeletonApp       : No active profile set, falling back to default profiles: default
        2015-12-21 15:19:10.428  INFO 8800 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5e959a06: startup date [Mon Dec 21 15:19:10 CET 2015]; root of context hierarchy
        2015-12-21 15:19:11.893  INFO 8800 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
        2015-12-21 15:19:12.941  WARN 8800 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
        2015-12-21 15:19:12.959  INFO 8800 --- [           main] org.xnio                                 : XNIO version 3.3.3.Final
        2015-12-21 15:19:13.035  INFO 8800 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.3.Final
        2015-12-21 15:19:13.099  WARN 8800 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
        2015-12-21 15:19:13.115  INFO 8800 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
        2015-12-21 15:19:13.115  INFO 8800 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2689 ms
        2015-12-21 15:19:13.521  INFO 8800 --- [           main] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
        2015-12-21 15:19:13.528  INFO 8800 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'metricFilter' to: [/*]
        2015-12-21 15:19:13.530  INFO 8800 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
        2015-12-21 15:19:13.531  INFO 8800 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
        2015-12-21 15:19:13.538  INFO 8800 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
        2015-12-21 15:19:13.548  INFO 8800 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
        2015-12-21 15:19:13.549  INFO 8800 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'webRequestLoggingFilter' to: [/*]
        2015-12-21 15:19:13.550  INFO 8800 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'applicationContextIdFilter' to: [/*]
        2015-12-21 15:19:13.796  INFO 8800 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5e959a06: startup date [Mon Dec 21 15:19:10 CET 2015]; root of context hierarchy
        2015-12-21 15:19:13.888  INFO 8800 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[]}" onto public java.lang.String org.skeleton.controller.HomeController.home()
        2015-12-21 15:19:13.892  INFO 8800 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
        2015-12-21 15:19:13.893  INFO 8800 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
        2015-12-21 15:19:13.949  INFO 8800 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
        2015-12-21 15:19:13.949  INFO 8800 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
        2015-12-21 15:19:14.009  INFO 8800 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
        2015-12-21 15:19:14.397  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/env/{name:.*}],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EnvironmentMvcEndpoint.value(java.lang.String)
        2015-12-21 15:19:14.398  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/env || /env.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.399  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/beans || /beans.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.400  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/configprops || /configprops.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.401  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/mappings || /mappings.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.407  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/trace || /trace.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.408  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/autoconfig || /autoconfig.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.410  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/info || /info.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.411  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/metrics/{name:.*}],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.MetricsMvcEndpoint.value(java.lang.String)
        2015-12-21 15:19:14.412  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/metrics || /metrics.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.413  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/health || /health.json],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(java.security.Principal)
        2015-12-21 15:19:14.414  INFO 8800 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/dump || /dump.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
        2015-12-21 15:19:14.634  INFO 8800 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
        2015-12-21 15:19:14.647  INFO 8800 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
        2015-12-21 15:19:14.859  INFO 8800 --- [           main] b.c.e.u.UndertowEmbeddedServletContainer : Undertow started on port(s) 8080 (http)
        2015-12-21 15:19:14.867  INFO 8800 --- [           main] org.skeleton.SkeletonApp       : Started SkeletonApp in 5.193 seconds (JVM running for 5.756)



but browser returns ERR_EMPTY_RESPONSE if i try to connect to http://localhost:8080/env

if i change from undertow to jetty everything works fine


I hope this helps

**Comment by snicoll** [comment] 2015-12-22 07:15
> I hope this helps

Not really. I copy/pasted that code in a project (next time could you please share a project or a zip rather than dumping all the code in a comment?). 

And that project worked. Maybe you have some nasty environment variables? (though I'd be surprised it would have such effect). The `ERR_EMPTY_RESPONSE` isn't very helpful either, the output of `curl -v :8080/env` would be better but please try to find a way to allow us to reproduce the problem.

**Comment by Tera** [comment] 2015-12-22 09:31
[skeleton.zip](https://github.com/spring-projects/spring-boot/files/69481/skeleton.zip)

Hi this is the zip containing my sample test project.

I've tested your curl command using undertow started with attached project and this is the output:


        curl -v :8080/env
        *   Trying ::1...
        * Connected to  (::1) port 8080 (#0)
        > GET /env HTTP/1.1
        > Host: :8080
        > User-Agent: curl/7.43.0
        > Accept: */*
        >
        * Empty reply from server
        * Connection #0 to host  left intact
        curl: (52) Empty reply from server

**Comment by Tera** [comment] 2015-12-22 09:49
I'm very sorry but i forgot to say a very important thing. 
My compile/runtime environment use java 1.7, in that environment undertow starts but do not responds.

If i compile and run same project with java 1.8 (as i presume you did) everything works fine.

**Comment by snicoll** [comment] 2015-12-22 09:54
Oh well. that would have helped, indeed.

**Comment by ofbizbrazil** [comment] 2015-12-23 02:12
Hi all,

I have had this same issue these days, and after looking into for a while I found out the reason of this error.

Please look at my notes:

1)  Undertow after the version 1.3.7 has changed the xnio-nio and xnio-api dependencies to new version 3.3.3.
2) It looks the version 3.3.3 does not work with Undertow since 1.3.8 version.
3) So, I decide to go back to 3.3.2 version including manually them.
```
<dependency>
	<groupId>org.jboss.xnio</groupId>
	<artifactId>xnio-nio</artifactId>
	<version>3.3.2.Final</version>
</dependency>
<dependency>
	<groupId>org.jboss.xnio</groupId>
	<artifactId>xnio-api</artifactId>
	<version>3.3.2.Final</version>
</dependency>
```
4) After that, Undertow started working again with Spring Boot 1.3.1

By the way, Spring Boot 1.3.0 uses Undertow 1.3.5 and Spring Boot 1.3.1 uses Undertow 1.3.10, that's the cause about the error you're getting now.

What I can tell you is Jboss has an issue with xnio libraries.

Cheers, :)

**Comment by snicoll** [comment] 2015-12-23 08:41
Thanks for the analysis @ofbizbrazil - For the record, Undertow works fine _with Java8_ so it must be something Java7 related they broke.

**Comment by snicoll** [comment] 2015-12-23 08:53
I've created [an issue in the Undertow tracker](https://issues.jboss.org/browse/UNDERTOW-599)

**Comment by snicoll** [comment] 2015-12-23 14:11
@Tera the issue has been fixed on the Undertow side. It's not obvious when this will be included in Undertow itself but you can use `xnio` `3.3.4.Final` with the version of Undertow you are using in the meantime.

**Closed** 2016-01-12 15:33 UTC
