### ISSUE TITLE
Upgrade to Reactor 2.0.7 in order to fix memory leak

### ISSUE THREAD

**Issue by daveburnsLIT** [spring-projects/spring-boot#4394] opened 2015-11-06 14:34 UTC
Version : Spring Boot 1.3.0 RC1

There is a memory leak in the Stomp Relay Broker with active open stomp websocket connections. We are using a rabbitMQ backend stomp Broker. We initial noticed the memory usage pattern after running a long 10 hour endurance test.

To replicate the issue we setup a test to connect 2,000 websocket stomp connections to a RabbitMQ WebSocketMessageBroker using the Spring WebSocketStompClient. After monitoring the JVM for around 1 hour the server will either run out of memory or become unresponsive due to excessive garbage collection, then drop the connections. Profiling the JVM over this period shows a leak probably in either the reactor or netty libraries (although, afraid we’re no experts on memory leaks).  

The [attached sample application](https://github.com/stuartgreenlees/springboot-websocket-leak) (based on the Spring Websocket getting started guide for the server) demonstrates the issue. The broker/server and Java Websocket clients were executed on separate machines during the test run. The WebsocketTest starts the client websocket connections.

Included in the sample app repo is the out of memory heap dump generated after a one hour test run. Also, the attached VisualVM screen shot shows the memory usage pattern where old gen memory accumulates even after all 2000 websocket clients are connected at the 6:10 marker. 

![stompbrokerleak](https://cloud.githubusercontent.com/assets/15671409/10998509/727f9ab6-848d-11e5-8196-a50a3aa54a74.png)

**Comment by snicoll** [comment] 2015-11-06 14:48
ping @rstoyanchev @smaldini

**Comment by rstoyanchev** [comment] 2015-11-06 14:54
When you say memory leak, can you describe the memory usage pattern in more detail? How much have is allocated to the JVM, how much is used after the clients are connected, does it stay that way, or does it grow? Or is it perhaps at or near max memory and just happens to fall over after 1 hour? Have you tried giving it more memory than 500MB?

**Comment by daveburnsLIT** [comment] 2015-11-06 15:10
Fast reply! Yeah, we were running our app in a cloud foundry env with 3GB initially then noticed via monitoring that the old gen mem was accumulating. We built the stripped down simple sample app and gave it less memory to speed up the out of memory error. Basically after about 10 minutes you have 2,000 connected clients and you see a saw-tooth type memory pattern on the heap useage. The problem is after the GC runs there's always a small piece of old gen not reclaimed, after long enough you see the "tooth" of the saw tooth get so small the CPU is used up doing garbage collection and we out of memory. Interestingly if we drop the socket connections from the client and then connect again we can run the test for longer, so the connection close seems to free the memory.

**Comment by stuartgreenlees** [comment] 2015-11-06 15:14
I've uploaded the heap dump to the sample project repo.

**Comment by rstoyanchev** [comment] 2015-11-06 17:16
Thanks is this a difference in behavior as a result of an upgrade, i.e. changing versions? Was it running okay before? 

> Profiling the JVM over this period shows a leak probably in either the reactor or netty libraries (although, afraid we’re no experts on memory leaks).

@smaldini, any chance you could  have an initial look? I'm tied up currently with RFD-related fallout.

**Comment by stuartgreenlees** [comment] 2015-11-06 18:14
We haven't had websockets running before. This is a new feature we are adding to our app.

**Comment by daveburnsLIT** [comment] 2015-11-06 19:33
Did notice this behaviour on the M5 release also but saw there was a reactor perf fix in RC1, hoped that might have fixed this issue too. As Stuart says, new feature in our app so can't say when it crept in.

**Comment by daveburnsLIT** [comment] 2015-11-09 14:22
We just ran our sample application against a Spring Boot 1.2.7 version of the server and got the following memory usage, very different pattern (looks to us like there's no leak in this version). 

![springboot1 2 7 release-2000connections](https://cloud.githubusercontent.com/assets/15671409/11035631/77718ab0-86eb-11e5-801e-215a63ba1c6b.PNG)

I suppose the main difference in libraries is the 1.3.0 release needs the `io.projectreactor ` dependency whereas 1.2.7 uses the older `org.projectreactor `. ([current Spring docs](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp-handle-broker-relay) still state `org.projectreactor `, needs updated )

**Comment by smaldini** [comment] 2015-11-09 14:32
Sorry for the late response, let me have a look, might be an issue with the Pooled byte buffer factory from Netty we use in 2.0.6.

**Comment by smaldini** [comment] 2015-11-09 15:35
Hey again, can you try io.projectreactor:2.0.7.BUILD-SNAPSHOT anytime on your side, I'm evaluating further deep, but I pushed a quick default behavior fix to that allocator in the meantime.

**Comment by smaldini** [comment] 2015-11-09 15:49
Another comment (sorry!). The graph looks somehow fine from a certain perspective, with Bytes pooling, after a warmup period it might reach its max potential and have pre-allocated all the room it needed. That means the cap we see in the end should tend to stay here (or may change again down or up to expand/shrink the bytes heap cache). It does seem strange the GC is that intensively used, I would expect it to be worse in the older version without Bytes pooling.

**Comment by daveburnsLIT** [comment] 2015-11-09 16:11
Sorry Stephane, in the first graph we reach steady state (2000 connections) just after the 6:10 marker, if left long enough we do get an out of memory, watching the mem usage over time shows netty and reactor class instances continually growing even after GC. The second graph above seems to better represent what we would expect to see in steady state i.e. the same 2000 connections doing a ping/pong every 10 seconds.

**Comment by daveburnsLIT** [comment] 2015-11-09 16:12
Oh, will setup that test on the 4.0.7 snapshot now and post back

**Comment by smaldini** [comment] 2015-11-09 16:31
2.0.7.BUILD-SNAPSHOT for reactor-net only. Thanks a lot for your help, I'm still investigating tho as we might not be lucky on that quick check.

**Comment by daveburnsLIT** [comment] 2015-11-09 17:39
Sorry, typo, just ran with 2.0.7 for reactor-net only, heres the graph 

![springboot1 3 1 reactornet2 0 7-2000connections-30mins](https://cloud.githubusercontent.com/assets/15671409/11041227/71acd69e-8708-11e5-8e51-df7887e554ea.PNG)

Full 2000 websocket connections around 12:14 marker. Around 12:30 connections start dropping as clients report server going quiet, ends with a java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by smaldini** [comment] 2015-11-09 18:36
Thanks a lot. It does seem the root cause is somewhere else indeed and I've looked at the dump, it seems there are only 2 IO threads for 2000 clients, which seems to be correlating with the default number of CPU on a CF instance. To tune that default, you might want to affect the System env property -Dreactor.tcp.ioThreadCount=16. 

The Reactor/Netty write in the current integration with Spring Messaging will always need to enqueue its write since it is invoked outside the event loop. That means 2000 increasingly concurrent writes (heartbeat 10sec) to be serialized in 2 event loops. I suspect we had a higher default number previously ignoring the number of CPU was.

**Comment by daveburnsLIT** [comment] 2015-11-09 18:44
Thanks, the graphs above are all from a local dev machine, didn't run these in CF and yeah the local machine has 2 CPU's. Will try increasing the threadcount to see if that helps.

**Comment by smaldini** [comment] 2015-11-09 19:42
For the record this part of design has been greatly improved in reactor lately and in coordination with the Spring 5 development branch, we'll have interesting solutions to offer. I'll continue the investigation a bit later today or tomorrow morning I still have a few checks to make.

**Comment by daveburnsLIT** [comment] 2015-11-10 11:41
Still the same result after adding the thread count env property. Graph below, looks the same (again this is 2.0.7 for reactor-net only)

![springboot1 3 1 reactornet2 0 7-2000-connections-16-threads](https://cloud.githubusercontent.com/assets/15671409/11061561/dd58c280-879f-11e5-9b9f-ac8282f49dd9.PNG)

**Comment by rstoyanchev** [comment] 2015-11-10 16:53
Okay we have a good lead on the root cause. See [Reactor issue #568](https://github.com/reactor/reactor/issues/568). @smaldini is working on a fix and we'll confirm when we have something good.

Note also that I've [created a ticket](https://jira.spring.io/browse/SPR-13664) in the Spring Framework JIRA to improve the efficiency of managing heartbeats on the client side. It's not the reason for the issue but it would improve the ability to run thousands of clients and a server locally.

**Comment by smaldini** [comment] 2015-11-10 17:54
There's a new 2.0.7 snapshot available with a fix for that leaking close issue, unfortunately the netty encapsulation of close future listeners is preventing immediate unit testing (we can improve that later by registering our own pub/sub component from Reactor, like an Emitter which gives more introspection facilities).

**Comment by philwebb** [comment] 2015-11-10 17:57
@smaldini When are planning to release 2.0.7? Ideally we would like to release Spring Boot 1.3 on Monday so I'm wondering if we should aim for 2.0.7 or leave 2.0.6 and note a known issue?

**Comment by rstoyanchev** [comment] 2015-11-10 19:31
I've been able to confirm the fix in my tests so @daveburnsLIT this would be a good time to try and confirm from your end.

Note however that Reactor's 2.0 branch is still building as 2.0.6.BUILD-SNAPSHOT. @smaldini will update this quite soon and produce another build. In the mean time however simply use a 2.0.6 snapshot. It should be reactor-net-2.0.6.BUILD-20151110.174150-15 or more recent.

**Comment by smaldini** [comment] 2015-11-10 20:44
@philwebb 2.0.7 is ok and we can make it before Monday!

**Comment by philwebb** [comment] 2015-11-10 21:00
Sweet!

**Comment by smaldini** [comment] 2015-11-10 21:05
Thanks to @daveburnsLIT @rstoyanchev for the investigation btw, we have a different use pattern for the operation underneath (1 write stream of N == 1 close future vs N write of 1 == N close future) which made this issue hard to notice. Hopefully we get your green light on your side before proceeding to a patch release :)

**Comment by philwebb** [comment] 2015-11-10 21:20
@smaldini Is your build deploying 2.0.7? https://github.com/reactor/reactor/blob/2.0.x/gradle.properties

**Comment by rstoyanchev** [comment] 2015-11-10 21:42
Yep and I sent a PR https://github.com/reactor/reactor/pull/569 :)

**Comment by smaldini** [comment] 2015-11-10 22:17
Should be building now, merged the PR thanks @rstoyanchev

**Comment by daveburnsLIT** [comment] 2015-11-11 10:51
Sorry for the late reply guys. Just ran a 30 minute test with the 2.0.6 SNAPSHOT and it looks really good, actually looks the same as the 1.2.7 Boot test above.

![springboot1 3 1 reactornet2 0 6-snapshot-2000connections-30mins](https://cloud.githubusercontent.com/assets/15671409/11089179/c694de38-885f-11e5-9665-73bc77c3a959.PNG)

Just for interest we originally spotted this issue while perf testing our application, we have a very large userbase and were trying to mimic thousands of users/websocket connections without having to spark up lots of browsers. The aim was to get a balance of how many stomp broker JVMS would be required by maximizing Cloud Foundry JVM instances with connections. Basically what is optimal, 2000 users on a 2GB broker/JVM or 4000 on a 3GB, that type of test. We're utilizing the new User Registry Broadcast on the broker so its brilliant that this should make the 1.3.0 release. 

Many thanks @smaldini @rstoyanchev, really amazed by the response time on this.

**Comment by rstoyanchev** [comment] 2015-11-11 13:51
Okay great to hear and thanks for reporting the issue!

**Comment by smaldini** [comment] 2015-11-11 18:08
Should be available soon on central as 2.0.7.RELEASE, thanks again!

**Closed** 2015-11-14 05:44 UTC
Labels: blocker
