### ISSUE TITLE
Provide more flexible actuator support in Spring Boot 2.0

### ISSUE THREAD

**Issue by jgoldhammer** [spring-projects/spring-boot#10800] opened 2017-10-28 14:25 UTC
The new actuator support in Spring Boot 2.0 is not flexible enough for the purposes I have.

Example:
- We have used spring-boot-actuator-logview (https://github.com/lukashinsch/spring-boot-actuator-logview) in the past. The current code cannot be migrated to Spring Boot 2.0 actuators framework. 

Reasons:
- the code directly uses httprequest and httpresponse. Actuator in 2.0 does not allow this AFAIK.
- the code contains several endpoints  in one actuator. Actuator in 2.0 does not support it.

Please revisit actuator support in Spring Boot 2.0 to increase the flexibility for developers.
BTW, you have made an exemption for the heapdumpwebendpoint and introduced a webendpointresponse to get access to the body and status. Maybe this is a good direction?

**Comment by wilkinsona** [comment] 2017-10-28 15:04
Duplicate of #10257

**Closed by wilkinsona** 2017-10-28 15:04 UTC
Labels: status: waiting-for-triage
