### ISSUE TITLE
Cannot package OCI image when 'docker.io/paketobuildpacks/new-relic' is provided as a buildpack

### ISSUE THREAD

**Issue by RobertoGraham** [spring-projects/spring-boot#43126] opened 2024-11-12 19:19 UTC
Spring Boot version: 3.2.6.
Docker Engine version: 27.3.1.

When running Spring Boot Gradle Plugin's `bootBuildImage` task while providing the alternate set of buildpacks below, I observe a failure. Reproducer: https://github.com/RobertoGraham/spring-boot-buildpack-bug/tree/31900583887eb0a05730d89b50a1acaecb9eb822.

```gradle
tasks.named<BootBuildImage>("bootBuildImage") {
    buildpacks.set(listOf("urn:cnb:builder:paketo-buildpacks/java", "docker.io/paketobuildpacks/new-relic"))
    bindings.set(listOf("${layout.projectDirectory.dir("paketo-bindings")}:/platform/bindings"))
}
```

```text
> Task :bootBuildImage
Building image 'docker.io/library/spring-boot-buildpack-bug:latest'

 > Pulling builder image 'docker.io/paketobuildpacks/builder-jammy-base:latest' ..................................................
 > Pulled builder image 'paketobuildpacks/builder-jammy-base@sha256:cc091c78cabb481e6abe97b1ae410993a028074a973eae9964e9271c59a8b08d'
 > Pulling run image 'docker.io/paketobuildpacks/run-jammy-base:latest' ..................................................
 > Pulled run image 'paketobuildpacks/run-jammy-base@sha256:8239d931b73e87afc5c9f446d89f6cc225bc0c4d0aed80c98312636e90254b28'
 > Pulling buildpack image 'docker.io/paketobuildpacks/new-relic:latest' ..................................................
 > Pulled buildpack image 'paketobuildpacks/new-relic@sha256:a33bac27dbe13d0f93da3719b235e3664b1fd016f124caedea44997d0e1d990a'
 > Executing lifecycle version v0.20.3
 > Using build cache volume 'pack-cache-0daef3812104.build'

 > Running creator
    [creator]     ===> ANALYZING
    [creator]     Image with name "docker.io/library/spring-boot-buildpack-bug:latest" not found
    [creator]     ===> DETECTING
    [creator]     ERROR: failed to initialize detector: open /cnb/buildpacks/paketo-buildpacks_new-relic/9.3.0/buildpack.toml: no such file or directory

> Task :bootBuildImage FAILED
```

**Comment by mhalbritter** [comment] 2024-11-13 13:17
Does this work when building the image with [`pack`](https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/pack/)?

**Comment by scottfrederick** [comment] 2024-11-13 14:55
Possibly a duplicate of https://github.com/spring-projects/spring-boot/issues/39323#issuecomment-2441939885

**Comment by philwebb** [comment] 2024-11-14 23:49
We have a couple of issues causing this. The first is that we don't support nested index (as documented [here](https://github.com/opencontainers/image-spec/blob/main/image-index.md#image-index-property-descriptions)). The second is the media type seems to have changed in the manifest from`tar.gzip` to `tar+gzip`.

**Closed** 2024-11-14 23:50 UTC
Labels: type: bug
