### ISSUE TITLE
JSON starter should include spring-web

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#10167] opened 2017-09-05 10:29 UTC
The JSON starter currently pulls Jackson into the classpath but does not pull in `spring-web` which contains `Jackson2ObjectMapperBuilder` that's in turn required for auto-configuration of Jackson.

**Comment by olivergierke** [comment] 2017-09-05 10:29
Related to #10166.

**Comment by snicoll** [comment] 2017-09-05 10:30
Uh? What currently? Master does it as far as I am aware.

**Comment by wilkinsona** [comment] 2017-09-05 10:35
Sorry, that's my mistake. @olivergierke and I were discussing this on Slack and I'd forgotten that we'd fixed this for M4.

Duplicate of #10031.

**Closed by wilkinsona** 2017-09-05 10:35 UTC
Labels: status: waiting-for-triage
