### ISSUE TITLE
@SQLDelete seems broken when using inheritance

### ISSUE THREAD

**Issue by yuvalbo** [spring-projects/spring-boot#9123] opened 2017-05-07 09:35 UTC
Spring-Boot 2.0.0.BUILD-SNAPSHOT
We have a class named Asset
``` java
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(name = "asset_type", columnDefinition = "TINYINT(3) UNSIGNED NOT NULL")
@SQLDelete(sql = "UPDATE asset SET deleted = true where id=?")
@Where(clause = "deleted = false")
public abstract class Asset {
```

And 2 concrete classes Video and Image:

``` java
@Entity
@DiscriminatorValue(value = "1")
@SQLDelete(sql = "UPDATE asset SET deleted = true where id=?")
public class Video extends Asset {
```

``` java
@Entity
@DiscriminatorValue(value = "2")
@SQLDelete(sql = "UPDATE asset SET deleted = true where id=?")
public class Image extends Asset {
```
snippet from our build:
```
compile('org.springframework.boot:spring-boot-starter-data-jpa')
```
After recent Spring-Boot updates we have noticed that entities are not being deleted anymore.
We are using MySQL 5.7.17
Let me know if you need any additional information

**Comment by wilkinsona** [comment] 2017-05-07 09:54
It's not clear why you think this is a bug in Spring Boot rather than, say, Hibernate or Spring Data JPA. Can you please provide a small sample that reproduces the problem? Also, any details of what you know that suggests this is a bug in Spring Boot would be useful.

**Comment by yuvalbo** [comment] 2017-05-07 11:19
Hi @wilkinsona and thank you for your quick response: chances are its not spring-boot directly but as we are using snapshot and dependencies change by the hour we cannot pin-point the root cause.
My guess would be Spring Data JPA but can't say 100% nor can I state the exact spring data jpa's version.

Regarding a sample code, can't provide something more than I already sent.
It is part of a larger project and would be hard to slice

**Comment by wilkinsona** [comment] 2017-05-07 12:39
> Regarding a sample code, can't provide something more than I already sent.
> It is part of a larger project and would be hard to slice

The sample need not be produced from your project. In fact, ideally, it would be a small app that's no bigger than is necessary to reproduce the problem. If you'd like us to spend some time trying to locate and diagnose the problem then please spend some time providing a sample.

**Comment by spring-issuemaster** [comment] 2017-05-14 12:43
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by yuvalbo** [comment] 2017-05-15 22:06
@wilkinsona assuming its a Spring-JPA issue, as we are using SpringBoot 2.0.0 snapshot
How do I figure out the exact spring-jpa version?

Thanks

**Comment by wilkinsona** [comment] 2017-05-16 06:07
The latest Spring Boot snapshots are using Spring Data Kay m3 which contains Spring Data JPA 2.0.0.M3

**Comment by spring-issuemaster** [comment] 2017-05-23 06:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-05-30 06:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-05-30 06:12 UTC
Labels: status: waiting-for-triage

**Comment by elvisciotti** [comment] 2022-01-11 11:39
Spring boot 2.6.1, Hibernate 5.6.1.
SQLDelete works well when applied to children. Does NOT get applied when added only to the parent. Not sure if that's wanted, I didn't find any mention in the documentation
