### ISSUE TITLE
Dev-tools reloading issue with spring-hateoas

### ISSUE THREAD

**Issue by sergiorc** [spring-projects/spring-boot#4117] opened 2015-10-08 09:23 UTC
Using, from spring-boot-starter 1.3.0.M5
 - spring-boot-devtools 1.3.0.M5
 - spring-hateoas 0.19.0.RELEASE

```
@SuppressWarnings({"rawtypes", "unchecked"})
@RequestMapping(method = RequestMethod.GET)
public ResponseEntity<?> findEscrituras(Pageable p, PagedResourcesAssembler<EscriturasBO> pagedResourcesAssembler) {
		Collection<Link> links = new ArrayList<Link>();
		// link to search(filter)
		links.add(linkTo(
				methodOn(EscriturasRestController.class).searchEscrituras(p, pagedResourcesAssembler,
						new EscriturasBO())).withRel(EscriturasResource.SEARCH_REL));
```

It works ok until you make any modification in the application.
After devtools reload, invoking "findEscrituras" methods produces:

```
java.lang.ClassCastException: com.qipert.tseo.rest.escrituras.mvc.EscriturasRestController$$EnhancerByCGLIB$$2770108b cannot be cast to com.qipert.tseo.rest.escrituras.mvc.EscriturasRestController
	at com.qipert.tseo.rest.escrituras.mvc.EscriturasRestController.findEscrituras(EscriturasRestController.java:123) ~[classes/:na]
	at com.qipert.tseo.rest.escrituras.mvc.EscriturasRestController$$FastClassBySpringCGLIB$$cfc373ab.invoke(<generated>) ~[spring-core-4.2.0.RELEASE.jar:na]
```

**Comment by snicoll** [comment] 2015-10-08 10:04
Most probably a duplicate of #3805

**Comment by RobMaskell** [comment] 2015-10-08 15:13
Looks similar to the one I raised a while ago [#3784](https://github.com/spring-projects/spring-boot/issues/3784)

**Comment by wilkinsona** [comment] 2015-10-08 15:37
@RobMaskell It does indeed. Thanks, and apologies; it looks like we missed that issue when you raised it.

**Comment by wilkinsona** [comment] 2015-10-08 16:42
This is a duplicate of #3784

**Closed by wilkinsona** 2015-10-08 16:42 UTC
