### ISSUE TITLE
Issue with Mockito and JpaRepository

### ISSUE THREAD

**Issue by YLombardi** [spring-projects/spring-boot#12467] opened 2018-03-13 16:19 UTC
Hello,

I don't know if this an issue with Spring boot data JPA or with Mockito but I encountered a strange behaviour.
I create 2 Controller. In the first, I inject a Service. In the second, I inject a JpaRepository.

Now I create UnitTests for both this Controller.
For the second Controller, I mock the Repository. Everything works fine.
For the first Controller, I mock the Service. The test fail.
It seems to search to inject the Repository whereas it is not used in this Controller.

I create a very simple project to reproduce this behavior :
https://github.com/YLombardi/mockito-spring-jpa-issue

Is it my test that is wrong or a bug ?

**Comment by wilkinsona** [comment] 2018-03-16 17:21
Thanks for the sample, @YLombardi. This looks like a bug to me. I'd expect your `ControllerAUnitTests` to have filtered out `ControllerB` due to your configuration of `@WebMvcTest` specifying a single controller:

```java
@WebMvcTest(ControllerA.class)
```

**Comment by bclozel** [comment] 2018-03-16 19:51
The main application class has a `@ComponentScan(basePackages = "com.geodis.rt")`; removing it solves the issue. Also, the test has a typo where it's checking for a view `.andExpect(view().name("aview"))`; this line should be removed.

**Comment by wilkinsona** [comment] 2018-03-16 20:27
Thanks, @bclozel. I was wondering why our tests for this were passing and hadn't spotted that difference . I wonder if there's something we can do to at least make it obvious that the use of `@ComponentScan`, rather than the aliased attributes on `@SpringBootApplication`, is going to cause a problem.

Either way, I think we should update the javadoc as it currently says that `@SpringBootApplication` is "a convenience annotation that is equivalent to declaring `@Configuration`, `@EnableAutoConfiguration`, and `@ComponentScan`".

**Comment by wilkinsona** [comment] 2018-03-16 20:31
Now that I know what's going on, this is a duplicate of #10933.

**Closed by wilkinsona** 2018-03-16 20:31 UTC
Labels: priority: normal, type: bug

**Comment by YLombardi** [comment] 2018-03-19 09:29
Thanks for your answers.
I will see if I can remove the @ComponentScan in my main application.
