### ISSUE TITLE
spring.profiles.active does not work with Spring Boot tests

### ISSUE THREAD

**Issue by sakky11** [spring-projects/spring-boot#13593] opened 2018-06-27 05:05 UTC
I have spring.profiles.active=override in my Spring Boot Test configuration.But properties are still getting picked up from application.yml instead of application-override.yml.

**Comment by wilkinsona** [comment] 2018-06-27 05:50
Thanks for the report but you haven’t provided enough information for us to accurately reproduce the problem and we don’t have time to guess. You haven’t even said which version of Boot your are using. If you would like us to spend some time trying to help you, please spend some time producing a minimal and complete (something we can unzip or git clone and run) sample that reproduces the problem.

**Comment by sakky11** [comment] 2018-06-28 05:56
Sorry for incomplete information.I am using Spring Boot 1.5.8 Release version.In Spring Boot application,when I pass -Dspring.active.profiles=test,I expect Spring Boot to take up "my-application-name-test.yml" with overriden values.And I am expecting same with Spring Boot Test,but it is not picking up values from "my-application-name-test.yml" and picking values from "my-application-name.yml".

**Comment by wilkinsona** [comment] 2018-06-28 06:08
Thanks, but we need more than that:

> If you would like us to spend some time trying to help you, please spend some time producing a minimal and complete (something we can unzip or git clone and run) sample that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2018-07-05 06:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-07-12 06:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-07-12 06:10 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
