### ISSUE TITLE
Fix couchbase auto-configuration

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8200] opened 2017-02-06 06:28 UTC
This commit https://github.com/spring-projects/spring-data-couchbase/commit/d62f4bbe8c7d4aed544934ebf795aa1e90fcd8ed#diff-4564410042dc9bc9eb4fdd6680204b82 has broken things.

Looks like `SpringBootCouchbaseDataConfiguration` needs to extend `AbstractCouchbaseConfiguration` now. We also need a `getBootstrapHosts()` method (but I don't know what it should return).

**Comment by Jack2code** [comment] 2017-02-06 07:09
pls merge it ASAP.

**Comment by snicoll** [comment] 2017-02-06 08:11
@philwebb we don't want to extend from a `@Configuration` class. We've actually worked with the couchbase team so that it isn't necessary. Is there a reason why we can't ask the data team to fix this instead?

**Comment by snicoll** [comment] 2017-02-06 09:40
It looks like I mixed up with something else. We do have a configurer and extend from the configuration class internally... I am looking into the breakagfe

**Comment by snicoll** [comment] 2017-02-06 12:07
I've reported [DATACOUCH-279](https://jira.spring.io/browse/DATACOUCH-279)

**Comment by snicoll** [comment] 2017-02-06 12:27
The support is broken and I had to ignore the couchbase sample for the time being.

**Comment by sandip-jadhav** [comment] 2017-02-07 07:12
While executing sample application , facing cyclic dependency , is this application in not usable state ?

2017-02-07 12:33:29.819  WARN 9524 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sampleCouchbaseApplication': Unsatisfied dependency expressed through field 'userRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.couchbase.SpringBootCouchbaseDataConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.data.couchbase.SpringBootCouchbaseDataConfiguration$$EnhancerBySpringCGLIB$$bc45f58c]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springBootCouchbaseConfigurer' defined in class path resource [org/springframework/boot/autoconfigure/data/couchbase/CouchbaseConfigurerAdapterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.couchbase.config.CouchbaseConfigurer]: Factory method 'springBootCouchbaseConfigurer' threw exception; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.data.couchbase.SpringBootCouchbaseDataConfiguration': Requested bean is currently in creation: Is there an unresolvable circular reference?

**Comment by snicoll** [comment] 2017-02-07 07:19
@sandip-jadhav it isn't, that why the test has been disabled for now. We're waiting the data couchbase team to restore the support. There is a PR that I just reviewed this morning. As soon as it lands on master, we'll be able to restore the couchbase support.

**Comment by simonbasle** [comment] 2017-02-07 09:16
@snicoll the fix has now been merged in Spring Data Couchbase `3.0.x` branch.

**Closed** 2017-02-07 11:03 UTC
Labels: priority: blocker, type: bug

**Comment by ghilainm** [comment] 2017-02-07 12:15
Still not working for me, is there any possibility that I didn't get the correct snapshot? I have deleted my whole org/springframework maven repository and still get this error:

┌─────┐
|  org.springframework.boot.autoconfigure.data.couchbase.SpringBootCouchbaseDataConfiguration
↑     ↓
|  springBootCouchbaseConfigurer defined in class path resource [org/springframework/boot/autoconfigure/data/couchbase/CouchbaseConfigurerAdapterConfiguration.class]
└─────┘

**Comment by snicoll** [comment] 2017-02-07 12:46
"not working for me" isn't really helpful. Is that the official spring boot sample you're trying to run?

**Comment by ghilainm** [comment] 2017-02-07 12:50
No I am not but I am think I am rather close to it. It used to work one week ago and I run into this error since you declared that bug. I didn't declare any specific configuration bean and just use the following boot starters dependencies.

`        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator-docs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-couchbase</artifactId>
        </dependency>`

**Comment by snicoll** [comment] 2017-02-07 12:54
Once you have your sample share somewhere so that I can run it, please create a separate issue for it.

**Comment by sandip-jadhav** [comment] 2017-02-07 17:12
@snicoll : I am still facing same issue in sample application Test as well as in main
   sampleCouchbaseApplication (field private sample.data.couchbase.UserRepository sample.data.couchbase.SampleCouchbaseApplication.userRepository)
┌─────┐
|  org.springframework.boot.autoconfigure.data.couchbase.SpringBootCouchbaseDataConfiguration
↑     ↓
|  springBootCouchbaseConfigurer defined in class path resource [org/springframework/boot/autoconfigure/data/couchbase/CouchbaseConfigurerAdapterConfiguration.class]
└─────┘

**Comment by snicoll** [comment] 2017-02-07 18:06
@sandip-jadhav I don't using `8899b93de0396365`. Make sure your copy of master is up to date.

**Comment by ghilainm** [comment] 2017-02-07 21:34
@snicoll  I don't understand your last message. I have the same issue as @sandip-jadhav and I did update all the spring-boot snapshots I depend on (deleted all my spring dependencies from maven repository).

**Comment by wilkinsona** [comment] 2017-02-08 09:05
@ghilainm I believe @snicoll was saying that it works fine for him using a particular commit on master. It also works fine for me, and on CI running on both Bamboo and Travis. It sounds to me like you still have a stale dependency. If you really think that's not the case, then please provide a sample that reproduces the problem.

**Comment by ghilainm** [comment] 2017-02-08 16:50
@wilkinsona Thanks for your answer. It seems that the problem is solved on my side also now! There must have been some kind of stale dependency as you said despite my tentative to clean everything! Thanks for your support :)
