### ISSUE TITLE
Why mvn spring-boot:build-image Downloading from https://github.com/bell-sw/Liberica/releases/download/8u275+1/bellsoft-jre8u275+1-linux-amd64.tar.gz every time?

### ISSUE THREAD

**Issue by uqix** [spring-projects/spring-boot#24261] opened 2020-11-26 11:32 UTC

**Comment by bclozel** [comment] 2020-11-26 12:27
Closing as a duplicate of #24262

**Closed by bclozel** 2020-11-26 12:27 UTC
Labels: status: waiting-for-triage
