### ISSUE TITLE
HTTP Status is always 200 for HealthCheck

### ISSUE THREAD

**Issue by mazenaissa** [spring-projects/spring-boot#22026] opened 2020-06-19 10:50 UTC
Hello,
The HealthCheck Response HTTP Status is always OK 200 no matter the app status is UP or DOWN or ...
I am using the version 1.5.9.RELEASE.
Thanks,

**Comment by wilkinsona** [comment] 2020-06-19 12:37
Thanks for the report. Unfortunately, Spring Boot 1.5.x is no longer supported as [it reached end of life in August 2019](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019). If you can reproduce the problem with a supported version of Spring Boot 2.x then please provide us with a minimal sample that reproduces the problem using that supported version and we can take a look.

**Comment by spring-issuemaster** [comment] 2020-06-26 12:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-07-03 12:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-07-03 12:40 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
