### ISSUE TITLE
One random.int for two keys in appliation.properties

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#25124] opened 2021-02-06 07:44 UTC
I want  to use a random int value to start rsocket server, and then use  the port number as discovery metadata for serve registry.  application.properties as following:  

```
spring.rsocket.server.port=${random.int[1025,65535]}
spring.cloud.consul.discovery.metadata.rsocketPort=${spring.rsocket.server.port}
```

I think that `metadata.rsocketPort` 's value should be same with `spring.rsocket.server.port`'s value.  But I found the `metadata.rsocketPort`'s value is another random int value, and they are different.  Is it a bug?

**Comment by wilkinsona** [comment] 2021-02-06 08:32
This is a duplicate of #7009. If you would like us to reconsider, please comment on that issue.

**Closed by wilkinsona** 2021-02-06 08:32 UTC
Labels: status: waiting-for-triage
