### ISSUE TITLE
Running `spring-boot:help" fails on 2.3.0.RELEASE

### ISSUE THREAD

**Issue by thorntonrp** [spring-projects/spring-boot#21767] opened 2020-06-08 19:03 UTC
When running `mvn spring-boot:help` on a Spring Boot 2.3.0 project created with `spring init` fails with the error:
```
A required class is missing: org.springframework.boot.maven.HelpMojo
```
By backing down the version to 2.2.7.RELEASE, the command executes normally without error.

I've attached the log.

[output.txt](https://github.com/spring-projects/spring-boot/files/4748005/output.txt)

**Comment by thorntonrp** [comment] 2020-06-08 19:05
Running the following command shows that HelpMojo.java is included in the jar, but not HelpMojo.class:
```
$ jar tf ~/.m2/repository/org/springframework/boot/spring-boot-maven-plugin/2.3.0.RELEASE/spring-boot-maven-plugin-2.3.0.RELEASE.jar | grep HelpMojo
org/springframework/boot/maven/HelpMojo.java
```

**Comment by bclozel** [comment] 2020-06-08 19:37
I think this is a duplicate of #21556

**Closed by bclozel** 2020-06-08 19:37 UTC
Labels: status: waiting-for-triage
