### ISSUE TITLE
"unable be resolved to persistence unit root url" in Spring Boot 2.0.4

### ISSUE THREAD

**Issue by jliu666** [spring-projects/spring-boot#14279] opened 2018-09-01 11:22 UTC
My project pom is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.github.jliu666</groupId>
  <artifactId>develop-tools</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>develop-tools</name>
  <description>Demo project for Spring Boot</description>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.0.4.RELEASE</version>
    <relativePath/>
  </parent>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>1.8</java.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>de.roskenet</groupId>
      <artifactId>springboot-javafx-support</artifactId>
      <version>2.1.6</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.datafx</groupId>
      <artifactId>flow</artifactId>
      <version>8.0.1</version>
    </dependency>
    <dependency>
      <groupId>io.datafx</groupId>
      <artifactId>datafx</artifactId>
      <version>8.0.1</version>
    </dependency>
  </dependencies>

  <build>
    <finalName>Develop-Tools</finalName>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.zenjava</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>8.8.3</version>
        <configuration>
          <mainClass>org.github.jliu666.developtools.DevelopToolsApplication</mainClass>
          <appName>${project.build.finalName}-${project.version}</appName>
          <deployDir>${basedir}/src/deploy/</deployDir>
          <vendor>LIU JICHUN</vendor>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```
I just use `@SpringBootApplication` annotation on my start class. 
1. I use `maven jfx:native` to package app on my mac os. 
2. I start the macos app by double click. An exception like below.
![image](https://user-images.githubusercontent.com/14869749/44945364-6ca5fb80-ae1a-11e8-8355-be5bc5494869.png)
3. When I use `java -jar Develop-Tools.jar` to start the app in bash, It works.
4. When I double click Develop-Tools.jar to start the jar file. An exception like below:
![image](https://user-images.githubusercontent.com/14869749/44945448-47b28800-ae1c-11e8-84ad-406b37457f7b.png)

**Comment by jliu666** [comment] 2018-09-01 11:27
I find #6983 issue like this. But that one was closed.

**Comment by jliu666** [comment] 2018-09-01 11:28
#6983

**Comment by jliu666** [comment] 2018-09-01 11:40
#6537

**Comment by wilkinsona** [comment] 2018-09-03 10:56
Can you please provide a minimal sample that reproduces the problem.

**Comment by jliu666** [comment] 2018-09-03 14:56
Yes, I can.
The demo on https://github.com/jliu666/develop-tools is a sample. But I have removed the jpa dependencies. If you want to reproduce the problem. Maybe 
1. You need add jpa and h2 dependencies to the pom.
```xml
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
  <groupId>com.h2database</groupId>
  <artifactId>h2</artifactId>
</dependency>
```
2. Use `mvn jfx:native` to package a native app.
3. Start the app by double click (in the target/jfx ) or start the fatjar (in the target) by double click.
4. A window will show on your deskop. Then you can see the exception.

**Comment by jliu666** [comment] 2018-09-03 15:03
Important! When started by `java -jar develop-tools-0.0.1-SNAPSHOT.jar`, it works correctly.

**Comment by wilkinsona** [comment] 2018-09-03 15:35
Thanks for the sample.

The built JavaFX app doesn't use Boot's launcher (the jar isn't fat) which is why it behaves differently. When there are only jars on the classpath, the JVM's app class loader is unable to resolve the root of the classpath. On the other hand, our launcher and its custom jar handling will return `BOOT-INF/classes` as the root of the classpath which allows the default persistence unit root to be resolved.

When resolving multiple resources, Spring Framework contains some logic to cope with the app class loader being unable to resolve the root of the classpath when there are only jars (no directories) on the class path. However, this logic is not used when resolving a single resource and I wonder if it should be. What do you think, @jhoeller?

**Comment by jhoeller** [comment] 2018-09-07 15:32
For the default persistence unit case, we have no `persistence.xml` file to derive a root URL from which is why we're relying on the default root URL (which is the classpath root by default but can be configured through the `defaultPersistenceUnitRootLocation` property). The question is: Which root URL should we expose to the persistence provider instead? The first of the packages to scan? The first mapping file in the list (if any)? Note that we're already deriving the root URL from a `META-INF/orm.xml` file if present (even if empty), so that might also be a workaround for the time being.

**Comment by wilkinsona** [comment] 2018-09-18 15:30
Thank you, @jhoeller. Perhaps the URL of the first resource that would be returned when resolving multiple resources could be used?

@jliu666 It looks like Framework, if anywhere, is going to be the right place to make a change for this. So that it's not forgotten, can you please open a [JIRA](https://jira.spring.io/browse/SPR) providing as much information as possible and referencing this issue.

**Closed by wilkinsona** 2018-09-18 15:30 UTC
Labels: status: feedback-provided, status: waiting-for-triage
