### ISSUE TITLE
actuator cause performance issue

### ISSUE THREAD

**Issue by huanzhang** [spring-projects/spring-boot#12738] opened 2018-04-03 13:09 UTC
Bug report || Enhancement

Our server's QPS is about 1,700.
When we deploy our app without actuator, the system load is as below:
load average: 1.04, 1.50, 2.61

However when our app include actuator, the system load is about 100% increment,
load average: 1.94, 2.90, 3.42

I think this is either an bug or an Enhancement.

**Comment by wilkinsona** [comment] 2018-04-03 13:37
Unfortunately, those numbers alone don't really tell us anything. To be able to diagnose where the performance overhead is coming from, we need to know exactly how you have configured the Actuator, what version of Spring Boot you're using, etc.

Can you please provide a small sample project that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2018-04-10 14:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-04-17 14:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-04-17 14:29 UTC
Labels: status: feedback-reminder, status: waiting-for-triage
