### ISSUE TITLE
DuplicateClasses

### ISSUE THREAD

**Issue by rgkjhshi** [spring-projects/spring-boot#7934] opened 2017-01-10 05:50 UTC
DuplicateClasses Error When use `spring-boot-starter-test(1.4.3.RELEASE)`.
```
Found in:
net.minidev:accessors-smart:jar:1.1:test
org.ow2.asm:asm:jar:5.0.3:test
Duplicate classes:
org/objectweb/asm/Item.class
org/objectweb/asm/signature/SignatureWriter.class
org/objectweb/asm/MethodWriter.class
org/objectweb/asm/Opcodes.class
org/objectweb/asm/signature/SignatureVisitor.class
org/objectweb/asm/AnnotationVisitor.class
org/objectweb/asm/ClassWriter.class
org/objectweb/asm/Context.class
org/objectweb/asm/TypePath.class
org/objectweb/asm/Type.class
org/objectweb/asm/Handler.class
org/objectweb/asm/Label.class
org/objectweb/asm/MethodVisitor.class
org/objectweb/asm/FieldWriter.class
org/objectweb/asm/Handle.class
org/objectweb/asm/signature/SignatureReader.class
org/objectweb/asm/Edge.class
org/objectweb/asm/ClassReader.class
org/objectweb/asm/Frame.class
org/objectweb/asm/FieldVisitor.class
org/objectweb/asm/ByteVector.class
org/objectweb/asm/Attribute.class
org/objectweb/asm/ClassVisitor.class
org/objectweb/asm/TypeReference.class
org/objectweb/asm/AnnotationWriter.class
```

**Comment by wilkinsona** [comment] 2017-01-10 10:49
There's nothing we can do about the contents of those two jars. Are the duplicate classes causing an actual problem when you run your tests? If they are, please provide a minimal sample that reproduces that problem.

**Comment by rgkjhshi** [comment] 2017-01-11 07:02
There's no effect on my tests.

**Comment by wilkinsona** [comment] 2017-01-11 15:53
Thanks. Given that this isn't causing you a problem and I'm not sure it's even possible for us to do anything about this, I'm going to close this one.

**Closed by wilkinsona** 2017-01-11 15:53 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by jrgleason** [comment] 2018-04-03 18:49
I am having an issue that is stuck because of this. My sample is here... 

https://github.com/jrgleason/simple-fat-jar

The problem is when I create a fat jar the extra files corrupt it. You can test this by running `gradle fatJarTest` Then try to go to `build\libs` and run `java -cp gradle-jar-test-all.jar com.me.MyClass`. Notice it fails. When I remove the `testCompile('org.springframework.boot:spring-boot-starter-test')` everything works.

**Comment by jrgleason** [comment] 2018-04-03 19:03
This is my temp fix...

    testCompile('org.springframework.boot:spring-boot-starter-test'){
        exclude group: "org.ow2.asm", module: "asm"
     }

**Comment by wilkinsona** [comment] 2018-04-03 19:25
Your sample works fine for me:

```
$: gradle clean fatJarTest

BUILD SUCCESSFUL in 4s
3 actionable tasks: 3 executed
$: java -cp build/libs/simple-fat-jar-test-all.jar com.me.MyClass
Working
```

That aside, there's still nothing that we can do about the contents of those two dependencies. It's also not clear to me why you're trying to create your own fat jar (rather than using Boot's fat jar's or the Gradle Shadow plugin) and why you want to package test dependencies in a fat jar. If you'd like further guidance, please come and chat on [Gitter](https://gitter.im/spring-projects/spring-boot).
