### ISSUE TITLE
spring-boot-maven-plugin-2.3.0.RELEASE.jar doesn't contain HelpMojo.class

### ISSUE THREAD

**Issue by nkjackzhang** [spring-projects/spring-boot#21662] opened 2020-06-03 06:07 UTC
When i run command `mvn spring-boot:help`, i got this error below:
```
 [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.0.RELEASE:help (default-cli) on project crm: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.3.0.RELEASE:help failed: Unable to load the mojo 'help' in the plugin 'org.springframework.boot:spring-boot-maven-plugin:2.3.0.RELEASE'. A required class is missing: org.springframework.boot.maven.HelpMojo
```
I looked into the `spring-boot-maven-plugin-2.3.0.RELEASE.jar`, and found `HelpMojo.java` instead of `HelpMojo.class`.

**Comment by wilkinsona** [comment] 2020-06-03 06:10
Thanks for the report. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/21556.

**Closed by wilkinsona** 2020-06-03 06:10 UTC
Labels: status: waiting-for-triage
