### ISSUE TITLE
Spring Boot 1.2.7 and 1.3.0.RC1 do not allow to use ".html" in @ResponseMapping anymore

### ISSUE THREAD

**Issue by bartolom** [spring-projects/spring-boot#4358] opened 2015-10-31 12:42 UTC
I'm not sure if this is a Spring Boot or Framework issue. Because I let Spring Boot do all the configuration I suspect it does something odd.

I came up with this simple Spring Boot application to reproduce my odd behavior

```java
@RestController
@SpringBootApplication
public class OddApplication {

    public static void main(String[] args) {
        SpringApplication.run(OddApplication.class, args);
    }

    // works with Spring Boot 1.2.6.RELEASE
    // odd behavior in 1.2.7.RELEASE (f.txt download forced)
    // works with Spring Boot 1.3.0.M5
    // odd behavior in 1.3.0.RC1 (f.txt download forced)
	@RequestMapping(value = "/with.html", produces = MediaType.TEXT_HTML_VALUE)
	public String someMethodWithFileExtension() {
		return "<!doctype html><body>some <b>bold</b> content with .html</body>";
	}

	// works with Spring Boot 1.2.6.RELEASE
	// works with Spring Boot 1.2.7.RELEASE
	// works with Spring Boot 1.3.0.M5
	// works with Spring Boot 1.3.0.RC1
	@RequestMapping(value = "/without", produces = MediaType.TEXT_HTML_VALUE)
	public String someMethodWithoutFileExtension() {
		return "<!doctype html><body>some <b>bold</b> content without .html</body>";
	}
}
```
gradle file created with start.spring.io. Only value change is the Spring-Boot-Plugin

```groovy
    springBootVersion = '1.3.0.RC1'
    // ...
    compile('org.springframework.boot:spring-boot-starter-web')
    testCompile('org.springframework.boot:spring-boot-starter-test') 
```

http://localhost:8080/with.html
http://localhost:8080/without

(Win 8.1) Chrome Version 46.0.2490.80 m
(Win 8.1) Firefox 42.0b9
(Win 8.1) IE 11
(Ubuntu) Firefox 41.0.2 (calling the IP address of the windows computer)

The odd behavior of downloading an f.txt might be due to the browser security features of 2014 described here (Rosetta Flash). 

http://stackoverflow.com/questions/28535603/google-chrome-forcing-download-of-f-txt-file/32738110#32738110

I'm not able to identify which change in Spring Boot 1.2.7 or Framework 4.1.8 caused this change. The release notes do not make this obvious.

The Release Notes for Spring Framework 4.1.8
https://jira.spring.io/secure/ReleaseNote.jspa?projectId=10000&version=15227
Maybe it is related to SPR-13558 ?

Release Notes Spring Boot 1.2.7
https://github.com/spring-projects/spring-boot/issues?q=milestone%3A1.2.7

because this might have to do with security I turned off the Anti-Virus Software (Windows Defender) for some more tests, but this did not change the behaviour

**Comment by bartolom** [comment] 2015-10-31 13:43
I started the example in on an Ubuntu computer and the behavior is the same
(Ubuntu) Firefox 41.0.2
(Android Nexus 5) Mobile Chrome
(Android Nexus 5) Mobile Firefox

**Comment by wilkinsona** [comment] 2015-10-31 14:11
This is a duplicate of #4220. Please see that issue for details and some suggestions on what you need to do.

**Closed by wilkinsona** 2015-10-31 14:11 UTC
