### ISSUE TITLE
Upgrade to Spring Boot 2.1.1 causes MappingException in tests

### ISSUE THREAD

**Issue by gznglor** [spring-projects/spring-boot#15851] opened 2019-02-05 16:01 UTC
Hello,

I'm running into a possible bug with Spring Boot 2.1.1. 

I believe it's a bug because before upgrading, my project builds successfully. Then, after upgrading to Spring Boot 2.1.1, the tests and the build fail with this error:

```
org.springframework.data.mapping.MappingException: Cannot lookup property @groovy.transform.Generated() 
@com.fasterxml.jackson.annotation.JsonIgnore(value=true)private java.util.Set bug.sample.domain.Student.classes 
on null intermediate! Original path was: classes.created on bug.sample.domain.Student.
```

I have not seen any Spring Boot 2 documentation addressing new changes that may cause this (but it's possible that I missed it). 

Here's what I'm using...
Gradle version: 5.0
Groovy version: 2.5.4
Spring Boot version: 2.1.1

And here is a project demonstrating the issue (there is more documentation in the README describing my observations): [gznglor/spring-boot-mongo-bug](https://github.com/gznglor/spring-boot-mongo-bug)

Any sort of insight into this would be appreciated. I really hope it's not a bug and I'm just missing something..

**Comment by wilkinsona** [comment] 2019-02-05 17:43
Thanks for the report. This is a duplicate of [DATACMNS-1461](https://jira.spring.io/browse/DATACMNS-1461). It has already been fixed in Spring Data Lovelace SR4 which is included in Spring Boot 2.1.2.

**Closed by wilkinsona** 2019-02-05 17:43 UTC
Labels: status: waiting-for-triage

**Comment by gznglor** [comment] 2019-02-05 17:46
@wilkinsona Awesome, thank you!

**Comment by snow-drop** [comment] 2019-04-03 08:38
@gznglor Does the bug have been fixed in your project? If it does, may I ask what steps have you done to resolve it?
