### ISSUE TITLE
Does add a source tag to WebFluxTags to tag the data for which application records, return the real path instead of UNKNOW when using the gateway, deduplication the data according to source

### ISSUE THREAD

**Issue by xuande** [spring-projects/spring-boot#19182] opened 2019-11-28 16:36 UTC

**Comment by wilkinsona** [comment] 2019-11-28 17:26
Assuming I have understood the issue title correctly, this is a duplicate of https://github.com/spring-projects/spring-boot/issues/16208. If you don't think it is a duplicate, can you please comment with some more details about the problem and we can re-open this issue.

**Closed by wilkinsona** 2019-11-28 17:26 UTC
Labels: status: waiting-for-triage
