### ISSUE TITLE
BufferCounterService should check for the "counter." prefix like it is done in the DefaultCounterService

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#10145] opened 2017-09-01 16:54 UTC
The `DefaultCounterService` has the code:
```
if (metricName.startsWith("counter.") || metricName.startsWith("meter.")) {
	return metricName;
}
```
Meanwhile `BufferCounterService`:
```
if (metricName.startsWith("counter") || metricName.startsWith("meter")) {
	return metricName;
}
```
That doesn't look consistent and breaks our project when we switch from Java 7 to Java 8. Just because we can't read `spring.metrics.counter.*` from the Redis properly any more.

See https://github.com/spring-cloud-stream-app-starters/counter/issues/3 for more info.

**Comment by wilkinsona** [comment] 2017-09-20 05:31
Duplicate of #10278

**Closed by wilkinsona** 2017-09-20 05:31 UTC
Labels: status: waiting-for-triage
