### ISSUE TITLE
Upgrading to Spring Boot 2.4.4 results in "Failed to bind properties"

### ISSUE THREAD

**Issue by vananiev** [spring-projects/spring-boot#25881] opened 2021-04-04 18:39 UTC
I've update Spring Boot from 2.4.3 to 2.4.4 and got

    ***************************
    APPLICATION FAILED TO START
    ***************************

    Description:

    Failed to bind properties under 'investbook.report-backup-path' to java.nio.file.Path:
        Property: investbook.report-backup-path
        Value: ${user.home}/report-backups
        Origin: class path resource [application-dev.properties] - 55:33
        Reason: No converter found capable of converting from type [java.lang.String] to type [java.nio.file.Path]
for property

    investbook.report-backup-path = ${user.home}/report-backups

Without  `${user.home}`

    investbook.report-backup-path = report-backups

2.4.4 works well.

With 2.4.3 both property values works.

A similar issue, but for 2.4.2 and `Duration` (relates #25878).

**Comment by scottfrederick** [comment] 2021-04-05 15:54
@vananiev This appears to be a duplicate of https://github.com/spring-projects/spring-framework/issues/26702. Can you try using Spring Boot 2.4.4 but downgrading Spring Framework to 5.3.4 as was [tested previously](https://github.com/spring-projects/spring-framework/issues/26702#issuecomment-802178896) to see if that works?

**Comment by vananiev** [comment] 2021-04-10 20:12
Yes, downgrading Spring Framework to 5.3.4 with pom.xml setting
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-framework-bom</artifactId>
            <version>5.3.4</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
solves the problem.

**Comment by philwebb** [comment] 2021-04-11 00:30
Closing as a duplicate of spring-projects/spring-framework#26702

**Closed by philwebb** 2021-04-11 00:30 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by vananiev** [comment] 2021-04-11 11:23
#26702 tells  about linux. If it matter, my problem occures on windows 7.
