### ISSUE TITLE
Undocumented behaviour in Binder

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#9136] opened 2017-05-09 05:15 UTC
This [useful guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Configuration-Binding) doesn't mention an important feature that is used in the `LoggingApplicationListener`, namely that you can bind a `Map<String,String>`, where the keys have periods, without putting brackets round them.

E.g.

```
logging.level.org.springframework.web=DEBUG
```

with

```java
Binder binder = Binder.get(environment);
binder.bind("logging.level", Bindable
			.mapOf(String.class, String.class)).orElseGet(Collections::emptyMap)
	.forEach((name, level) -> setLogLevel(system, environment, name, level));
```

yields

```
["org.springframework.web"="DEBUG"]
```

Actually, the `Binder` API isn't even mentioned in the docs linked above. Maybe that would be a good idea too?

**Comment by mbhave** [comment] 2017-05-09 16:43
@dsyer think this is a duplicate of #9025

**Comment by dsyer** [comment] 2017-05-09 18:13
Not precisely a duplicate, since I was quite specifically referring to missing detail, rather than missing docs completely. Feel free to copy this one over and close it if you think it will get the message over.

**Comment by mbhave** [comment] 2017-05-09 20:54
ok, I'll move it over to that one.

**Closed by mbhave** 2017-05-09 20:54 UTC
