### ISSUE TITLE
Custom ErrorController side stepped in Weblogic Server 12.1.3

### ISSUE THREAD

**Issue by renholm** [spring-projects/spring-boot#5941] opened 2016-05-13 08:15 UTC
We're having trouble getting exception handling to work in the WLS 12.1.3 application server. For unhandled exception, instead of going through the ErrorController it returns the status code 500 with only the exception message as body. Catching specific exceptions through `@ExceptionHandler` works without problems. 

As I understand it Spring Boot adds the ErrorPageFilter which catches the exception. It that code, in the 
`forwardToErrorPage` method, calls `sendError` and then forwards the request to the ErrorController. We've implemented our own ErrorController and according to logs it is never reached. Could it be that WLS ends the response upon `sendError`? **Update:** ErrorWrapperResponse makes sure it is not actually sent until `flushBuffer()`. In Jersey there looks to be a setting to work around it, see `jersey.config.server.response.setStatusOverSendError` in [doc](https://jersey.java.net/documentation/latest/appendix-properties.html). Any thoughts?

**Comment by wilkinsona** [comment] 2016-05-13 09:08
WebSphere has some behaviour that sounds somewhat similar. There's a [configuration setting](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-error-handling-websphere) that we recommend people use. Perhaps WebLogic has something similar?

**Comment by renholm** [comment] 2016-05-13 11:42
Thanks for your response! Unfortunately not that I can find. 

I've been doing some more digging and I was incorrect in stating that our custom error controller isn't reached, it is. The error controller completes successfully and spring starts to flush the response. What happens though is that `flushBuffer` on `ErrorWrapperResponse` gets called because of the flag `hasErrorToSend=true` and that the response isn't commited. By using the debugger and changing the `hasErrorToSend` to `false` I can get the actual response from the error controller to the client. Here is the code from `ErrorPageFilter`.

```java
@Override
public void flushBuffer() throws IOException {
  if (this.hasErrorToSend && !isCommitted()) {
    ((HttpServletResponse) getResponse()).sendError(this.status,
        this.message);
  }
  super.flushBuffer();
}
```

My guess is that we need to commit the response in the error controller somehow? And therefore is not similar to the Websphere issue?

**Comment by renholm** [comment] 2016-05-18 14:18
@wilkinsona A friendly ping, not sure you saw my reply

**Comment by wilkinsona** [comment] 2016-05-23 09:37
@renholm I saw it, I just haven't had a chance to look at it yet. It's on my todo list.

**Comment by adrianosimoes** [comment] 2017-02-27 23:35
Is this still a issue?

**Comment by wilkinsona** [comment] 2017-02-28 09:40
Yes, as far as we know. A sample that reproduces the problem would make it much more likely that someone will have the time to look at it in detail.

**Comment by spring-issuemaster** [comment] 2017-05-04 14:51
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-05-11 14:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-05-11 14:54 UTC
Labels: status: waiting-for-triage
