### ISSUE TITLE
Access uri ‘/actuator/mappings’ throw exception

### ISSUE THREAD

**Issue by zhanglei-1987** [spring-projects/spring-boot#18292] opened 2019-09-20 10:40 UTC
```
DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.springframework.boot.actuate.web.mappings.MappingsEndpoint$ApplicationMappings["contexts"]->java.util.HashMap["cloud-docs-1"]->org.springframework.boot.actuate.web.mappings.MappingsEndpoint$ContextMappings["mappings"]->java.util.HashMap["dispatcherServlets"]->java.util.HashMap["dispatcherServlet"]->java.util.ArrayList[45]->org.springframework.boot.actuate.web.mappings.servlet.DispatcherServletMappingDescription["details"]->org.springframework.boot.actuate.web.mappings.servlet.DispatcherServletMappingDetails["requestMappingConditions"])]
```

**Comment by wilkinsona** [comment] 2019-09-20 10:52
Thanks for the report. Unfortunately it's not clear what was `null` and, therefore, what caused the `NullPointerException`. Can you please provide a complete and minimal sample that reproduces the problem as a zipped project attached to this issue, or at least the complete stack trace of the failure?

**Comment by spring-issuemaster** [comment] 2019-09-27 10:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-10-04 10:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-10-04 10:54 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
