### ISSUE TITLE
spring-boot-maven-plugin do not support unicode characters

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#10187] opened 2017-09-07 08:28 UTC
Demo: [demo.zip](https://github.com/spring-projects/spring-boot/files/1283919/demo.zip)

In the demo, there is a file name: `中文.txt`.

```bahs
mvn clean package -DskipTests
unzip target/demo-0.0.1-SNAPSHOT.jar -d spring-result
```

The fat jar created by `spring-boot-maven-plugin` result:

```
Archive:  target/demo-0.0.1-SNAPSHOT.jar
   creating: spring-result/META-INF/
  inflating: spring-result/META-INF/MANIFEST.MF
   creating: spring-result/BOOT-INF/
   creating: spring-result/BOOT-INF/classes/
   creating: spring-result/BOOT-INF/classes/com/
   creating: spring-result/BOOT-INF/classes/com/example/
   creating: spring-result/BOOT-INF/classes/com/example/demo/
  inflating: spring-result/BOOT-INF/classes/application.properties
  inflating: spring-result/BOOT-INF/classes/com/example/demo/DemoApplication.class
  inflating: spring-result/BOOT-INF/classes/������.txt
```

---

```bash
mvn clean package -DskipTests
unzip target/demo-0.0.1-SNAPSHOT.jar.original -d original-result
```

The original jar created by `maven-jar-plugin` result:

```
Archive:  target/demo-0.0.1-SNAPSHOT.jar.original
   creating: original-result/META-INF/
  inflating: original-result/META-INF/MANIFEST.MF
   creating: original-result/com/
   creating: original-result/com/example/
   creating: original-result/com/example/demo/
  inflating: original-result/application.properties
  inflating: original-result/com/example/demo/DemoApplication.class
  inflating: original-result/中文.txt
```

---

OS version:

```
Mach kernel version:
	 Darwin Kernel Version 15.6.0
```

Unzip version:

```
unzip -v
UnZip 5.52 of 28 February 2005, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1) for Unix on Aug  1 2015.
```

**Comment by wilkinsona** [comment] 2017-09-07 08:37
Thanks for the sample. This is a duplicate of #9405.

**Closed by wilkinsona** 2017-09-07 08:37 UTC
Labels: status: waiting-for-triage
