### ISSUE TITLE
kotlin: Unresolved reference: ref

### ISSUE THREAD

**Issue by toplinuxsir** [spring-projects/spring-boot#18738] opened 2019-10-25 07:12 UTC
I  Upgrade to spring boot 2.2, But when I compile  the project 
code as below 
```
fun beans() = beans {


    val logger = LoggerFactory.getLogger(javaClass)


    logger.info("begin to initialize beans..................................")
    bean<PlmDsConfig>()

    val cfg = ref<PlmDsConfig>()
}
```
error prone:

```
kotlin: Unresolved reference: ref
```

**Comment by wilkinsona** [comment] 2019-10-25 12:59
`ref` is provided by Spring Framework's Kotlin extension. If there's a problem in Spring code I suspect it's there rather than in Spain boot, but it's impossible to say with only a small snippet of Kotlin code to go on. If you would like us to spend some more time investigation, please take the time to create a small sample that reproduces the problem and share it with us by zipping it up and attaching it to this issue.

**Comment by spring-issuemaster** [comment] 2019-11-01 13:00
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-11-08 13:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-11-08 13:01 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
