### ISSUE TITLE
mark @ConditionalOnProperty on s specific Spring data mongodb Repository implementation. Spring boot 2.0.2 can't launch.

### ISSUE THREAD

**Issue by itatkakaxi2** [spring-projects/spring-boot#14943] opened 2018-10-24 10:37 UTC

**Comment by itatkakaxi2** [comment] 2018-10-24 10:40
Marking a spring data mongodb repository with @ConditionalOnProperty causes application to fail to start.
Exception Trace:
Caused by: java.lang.IllegalStateException: Error processing condition on com.itat.mongo.dao.UserCustomImpl
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64) ~[spring-boot-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isConditionMatch(ClassPathScanningCandidateComponentProvider.java:515) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:498) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:431) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	... 69 common frames omitted
Caused by: java.lang.IllegalStateException: No ConfigurableListableBeanFactory available
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.context.annotation.ConditionEvaluator$ConditionContextImpl.getBeanFactory(ConditionEvaluator.java:206) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.recordEvaluation(SpringBootCondition.java:113) ~[spring-boot-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:49) ~[spring-boot-autoconfigure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
	... 75 common frames omitted

Demo : https://github.com/itatkakaxi2/mongoDemo

**Comment by snicoll** [comment] 2018-10-24 14:10
Looks similar to #13226

**Comment by snicoll** [comment] 2018-10-24 14:12
@itatkakaxi2 I can see you're using Spring Boot 2.0.2. Have you tried your project with the latest bug fix? (2.0.6)

**Comment by itatkakaxi2** [comment] 2018-10-25 03:16
Yeah, when updating to Spring 2.0.6, it works. there's no exceptions thrown.  There's other resources or urls that gives out a detailed explain of why this happens?

**Comment by philwebb** [comment] 2018-10-25 04:44
@itatkakaxi2 The root cause was a Spring Framework issue ([SPR-16866](https://jira.spring.io/browse/SPR-16866)) which was fixed in [this commit](https://github.com/spring-projects/spring-framework/commit/46a89d9534cbb5596a2754a7655f678b27d504da#diff-3f68fc93f74ee8b7cf16f58787344180L206).

**Closed by philwebb** 2018-10-25 04:44 UTC
Labels: status: feedback-provided, status: waiting-for-triage
