### ISSUE TITLE
Unable to find org.apache.tomcat.util.scan-7.0.47.jar 

### ISSUE THREAD

**Issue by Nileshsachin10** [spring-projects/spring-boot#14289] opened 2018-09-03 11:50 UTC

**Comment by wilkinsona** [comment] 2018-09-03 12:41
Without more details, it's very hard to know what the problem is. If you're using embedded Tomcat, Boot doesn't support Tomcat 7. If you're using standalone Tomcat, `org.apache.tomcat.util.scan` is an internal detail of Tomcat that Boot doesn't care about. I'm going to close this one for now as it's not clear that this has anything to do with Spring Boot. If it does, please provide so more details and we can re-open this issue and investigate.

**Closed by wilkinsona** 2018-09-03 12:41 UTC
Labels: status: waiting-for-triage
