### ISSUE TITLE
Upgrade to Jackson 2.10.0

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17999] opened 2019-08-29 15:22 UTC
We should also test early with 2.10.0.pr2

**Comment by wilkinsona** [comment] 2019-08-31 08:08
I couldn't find a release date for 2.10. Do we know it's going to GA before we want to GA 2.2?

**Comment by snicoll** [comment] 2019-08-31 08:23
There has been some discussion with @cowtowncoder and it looks like a release may happen in September. We should probably move this one back to `2.2.x`.

**Comment by cowtowncoder** [comment] 2019-08-31 17:20
2.10.0.pr2 is out now (released yesterday): intent is to release in second part of September, not expecting blockers. Happy to coordinate, given that 2.10 will get rid of pesky polymorphic deser CVEs that users are... not thrilled to have upgrade for.

**Comment by wilkinsona** [comment] 2019-09-05 16:15
Boot's build's cleanly with 2.10.0.pr2 with some [minor changes](https://github.com/spring-projects/spring-boot/commit/58eddb8fa495739e1cc756a234babb0a7662d923). Those changes are also 2.9.x-compatible.

**Comment by cowtowncoder** [comment] 2019-09-05 17:02
@wilkinsona Good. Intention was to try to limit compatibility problems. There was one change that may be somewhat visible (assignment-compatibility for `TypeReference<T>` taking `readValue()` methods), being source-incompatible in some cases (but fully binary compatible); and for users running on Java 9 and later there is the question of how good module-info definitions are (being the first version with that info).

Please let me know of new issues found. I still hope to fix a few before final release.

**Comment by sdeleuze** [comment] 2019-09-18 14:28
Jackson 2.10 release may happen September 26th in time for Spring Framework 5.2 GA, see [related issue](https://github.com/spring-projects/spring-framework/issues/23662).

**Comment by juergenzimmermann** [comment] 2019-09-27 05:45
@philwebb @wilkinsona Jackson 2.10 is available. Pls. see e.g. http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.10.0/

**Comment by snicoll** [comment] 2019-09-27 05:55
@juergenzimmermann thank you but there is no need to at us, the issue is assigned to `2.2.0.RC1` already.

**Closed** 2019-09-28 02:42 UTC
Labels: type: dependency-upgrade
