### ISSUE TITLE
Quartz Sheduler can not get default spring datasource anymore

### ISSUE THREAD

**Issue by flaxoiu** [spring-projects/spring-boot#28886] opened 2021-12-02 08:24 UTC
With Spring Boot Version 2.5.7, Quartz cant find the default datasource configured on the spring node in the application.yaml

With versions <= 2.5.6 it was working 

This datasource setting is no longer propagated to Quartz automatically since SpringBoot 2.5.7
spring
  datasource:
    hikari: maximum-pool-size: 4
    url: "jdbc:postgresql://localhost:8081/postgresApplicationName=${spring.application.name}&currentSchema=${ph.database.schema-name}"
    username: exampleUser
    password: examplePassword

**Comment by snicoll** [comment] 2021-12-02 08:26
Duplicate of #28758

**Closed by snicoll** 2021-12-02 08:26 UTC
