### ISSUE TITLE
Spring Boot 1.5 performance issue

### ISSUE THREAD

**Issue by martin-tarjanyi** [spring-projects/spring-boot#15146] opened 2018-11-10 23:06 UTC
Hi,

We have a Spring Boot application which has been upgraded from 1.3.1 to 1.5.16. After the upgrade we noticed significant performance degradation regarding our response time.  Even the requests with a response of status code 400 occasionally took more than 6(!) seconds to complete. CPU utilization also increased (maybe that's just a consequence).

Actually, one year ago we ran into the same issue when tried to upgrade from 1.3 to 1.5 but other priorities prevented us from spending more time with it then.

Unfortunately I'm not able to share the whole application code/config.
Here are some details that might be important:
* We use Java 8
* Application runs inside a Docker container
* We run a WAR file (but we do not deploy to a standalone container, we use the embedded tomcat)
* Tomcat max threads are set in the config

Could you help us find the root cause of the issue?
I understand it's quite difficult without actual code and config but if you can advise what we should check and try that would be a great help. Please, let me know if any other info is needed.

Thanks.

**Comment by snicoll** [comment] 2018-11-11 09:28
> Could you help us find the root cause of the issue?

I am afraid not. One way to figure out what is going on is to trim down so part of your infrastructure (i.e. running a simple repackaged war file for a start) and look and what has changed besides Spring Boot. Going from 1.3 to 1.5 means you've also updated some third party dependencies. 

I don't expect Spring Boot itself to be responsible to such response time so here isn't the best place. That said, if you can share a sample we can run ourselves that demonstrates the behaviour you're experiencing, we can certainly have a look.

**Comment by martin-tarjanyi** [comment] 2018-11-11 12:08
Okay. Thanks for the quick reply. I will get back to you if we can reproduce the issue with a sample.

**Comment by martin-tarjanyi** [comment] 2018-11-11 14:58
Seems switching to jar from war packaging solves the issue (at least high latency is gone in local environment, testing with gatlin). I tried to reproduce it with a sample app but did not succeed.

**Comment by wilkinsona** [comment] 2018-11-11 19:59
That’s interesting. Thanks. The differences between an executable war and jar are fairly minimal. One difference is the serving of static resources from the war by the container. I’m not sure that would produce such high latency though. It might give you an avenue to explore in reproducing the problem or an area to focus on when profiling. Please do let us know if you manage to reproduce the behaviour with a sample.

**Comment by spring-issuemaster** [comment] 2018-11-18 20:01
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-11-25 20:04
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-11-25 20:04 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
