### ISSUE TITLE
Non-resolvable parent POM org.springframework.boot:spring-boot-starter-parent:2.0.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by hellocomrade** [spring-projects/spring-boot#10527] opened 2017-10-05 14:39 UTC
On a newly built spring starter project in STS, mvn build returns the following...

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM org.springframework.boot:spring-boot-starter-parent:2.0.0.BUILD-SNAPSHOT for com.example:demo:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.BUILD-20171005.044727-1 in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 14, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.example:demo:0.0.1-SNAPSHOT (/home/foobar/Documents/workspace-sts-3.8.3.RELEASE/demo/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM org.springframework.boot:spring-boot-starter-parent:2.0.0.BUILD-SNAPSHOT for com.example:demo:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.BUILD-20171005.044727-1 in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 14, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by hellocomrade** [comment] 2017-10-05 14:52
In my .m2, I have the following in my settings.xml

```xml
<repositories>
                <repository>
                        <id>repository.springframework.maven.release</id>
                        <name>Spring Framework Maven Release Repository</name>
                        <url>http://maven.springframework.org/milestone/</url>
                </repository>
                <repository>
                        <id>org.springframework</id>
                        <url> http://maven.springframework.org/snapshot</url>
                </repository>
                <repository>
                        <id>spring-milestone</id>
                        <name>Spring Maven MILESTONE Repository</name>
                        <url>http://repo.spring.io/libs-milestone</url>
                </repository>
                <repository>
                        <id>spring-release</id>
                        <name>Spring Maven RELEASE Repository</name>
                        <url>http://repo.spring.io/libs-release</url>
                </repository>

```

**Comment by kazuki43zoo** [comment] 2017-10-05 14:56
me too. I created a mavne project using SPRING INITIALIZR for Spring Boot 2.0.0.BUILD-SNAPSHOT.
It fail a mavne build as follow:

```
$ ./mvnw clean test
/Users/xxx/Downloads/demo
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM org.springframework.boot:spring-boot-starter-parent:2.0.0.BUILD-SNAPSHOT for com.example:demo:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.BUILD-20171005.044727-1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 14, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.example:demo:0.0.1-SNAPSHOT (/Users/shimizukazuki/Downloads/demo 23/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM org.springframework.boot:spring-boot-starter-parent:2.0.0.BUILD-SNAPSHOT for com.example:demo:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.BUILD-20171005.044727-1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 14, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by wilkinsona** [comment] 2017-10-05 15:01
Duplicate of #10521.

**Closed by wilkinsona** 2017-10-05 15:01 UTC
Labels: status: waiting-for-triage
