### ISSUE TITLE
Offer --list in the tab completion for spring init

### ISSUE THREAD

**Issue by Jeansen** [spring-projects/spring-boot#13940] opened 2018-07-29 18:00 UTC
`spring --version` gives me: Spring CLI v2.0.3.RELEASE

I have installed the bash completion script and if I do `spring init --<tab><tab>` I get:
```
--artifactId    
--boot-version
--build
--dependencies
--description 
--extract
--force
--format
--groupId
--java-version
--language
--name
--package-name
--packaging
--target
--type
--version
```
But the `--list` option is missing.

**Comment by philwebb** [comment] 2018-07-30 07:09
Can you provide some more details? There's no `--list` command offered by the CLI out of the box:
```
usage: spring [--help] [--version] 
       <command> [<args>]

Available commands are:

  run [options] <files> [--] [args]
    Run a spring groovy script

  grab                
    Download a spring groovy script's dependencies to ./repository

  jar [options] <jar-name> <files>
    Create a self-contained executable jar file from a Spring Groovy script

  war [options] <war-name> <files>
    Create a self-contained executable war file from a Spring Groovy script

  install [options] <coordinates>
    Install dependencies to the lib/ext directory

  uninstall [options] <coordinates>
    Uninstall dependencies from the lib/ext directory

  init [options] [location]
    Initialize a new project using Spring Initializr (start.spring.io)

  encodepassword [options] <password to encode>
    Encode a password for use with Spring Security

  shell                
    Start a nested shell

Common options:

  -d, --debug Verbose mode   
    Print additional status information for the command you are running


See 'spring help <command>' for more information on a specific command.
```

**Comment by snicoll** [comment] 2018-07-30 07:19
I think this was intentional to leave `--list` out as it does not participate in the creation of a project. It's the best compromise I could think of at the time to not confuse users using the auto-completion but maybe that was dumb. There is a `--list` option that will list the available dependencies rather than generating the project.

**Comment by philwebb** [comment] 2018-07-30 07:44
Oh sorry, I totally missed the `init` part of the earlier report. I'll get myself some more coffee :)

**Comment by Jeansen** [comment] 2018-07-31 08:27
@philwebb No problem :smile: 
@snicoll It is not dumb. It is a fair decision. On the one hand I agree that it might be confusing beacuse `init --list` does not generate anything. On the other hand it is a valid option that shows what is available to init. But for me it was a bit confusing because I had expected to get all available options.

**Comment by ivange94** [comment] 2018-09-13 08:52
Trying to reproduce this. I've installed the snapshot version of the cli. 

> ➜  ~ spring --version
> Spring CLI v2.1.0.BUILD-SNAPSHOT

But when I do `spring init --<tab><tab>`

Nothing happens. I just get the bell twice. No options are displayed.

**Comment by wilkinsona** [comment] 2018-09-13 09:08
Have you got the [command line completion](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started-cli-command-line-completion) installed in your shell?

**Comment by ivange94** [comment] 2018-09-13 09:29
Oh I did not. But I've tried now with no success.

<img width="566" alt="screen shot 2018-09-13 at 10 28 42 am" src="https://user-images.githubusercontent.com/11330494/45480018-dccc4f80-b73f-11e8-9236-7c8ad19dec7d.png">

**Comment by ivange94** [comment] 2018-09-13 09:31
<img width="803" alt="screen shot 2018-09-13 at 10 31 14 am" src="https://user-images.githubusercontent.com/11330494/45480151-359be800-b740-11e8-8df0-0c91ef86d352.png">

**Comment by wilkinsona** [comment] 2018-09-13 10:56
I've just tried with a clean setup and have the same problem in a bash shell (I haven't tried zsh). I guess we must have broken the completion script at some point.

**Comment by wilkinsona** [comment] 2018-09-13 10:58
Hmm, perhaps not. The completion works fine when installed via homebrew. I suspect the problem lies with sourcing the completion script as a way of installing it.

**Comment by ruslanys** [comment] 2018-09-13 11:06
@wilkinsona @ivange94 Make sure that `bash-completion` is installed.
`_get_comp_words_by_ref` function is available only with installed `bash-completion`.

**Comment by ruslanys** [comment] 2018-09-13 11:26
@ivange94 I'm not sure about zsh. But for bash, yep, you need to install it separately if you are using sdkman as well.

**Comment by wilkinsona** [comment] 2018-09-13 11:29
I already have bash completion installed and working. It also works fine for Boot's CLI when installed via homebrew (it puts it in `/usr/local/etc/bash_completion.d`). As I said above, it just doesn't work when sourced.

**Comment by ruslanys** [comment] 2018-09-13 11:29
@wilkinsona Agreed. The same for me.

**Comment by ruslanys** [comment] 2018-09-13 12:00
In fact, `--list` should have been displayed. The problem is in the `OptionHandler` class. The fact is that init has two identical keys `-l (language)` and `-l (list)`.

**Comment by ruslanys** [comment] 2018-09-13 12:01
So, the solution is just removing `-l` key for `--list` section, because `-l` is already used by `--language`.

**Comment by ruslanys** [comment] 2018-09-13 12:07
And actually, the type of the issue is not `enhancement`, displaying `--list` option should work out of the box. The type of the issue `bug` I would say.

**Comment by ruslanys** [comment] 2018-09-13 12:26
```
--artifactId Project coordinates; infer archive name (for example 'test')
--boot-version Spring Boot version (for example '1.2.0.RELEASE')
--build Build system to use (for example 'maven' or 'gradle')
--dependencies Comma-separated list of dependency identifiers to include in the generated project
--description Project description
--force Force overwrite of existing files
--format Format of the generated content (for example 'build' for a build file, 'project' for a project archive)
--groupId Project coordinates (for example 'org.test')
--java-version Language level (for example '1.8')
--language Programming language  (for example 'java')
--list List the capabilities of the service. Use it to discover the dependencies and the types that are available
--name Project name; infer application name
--packaging Project packaging (for example 'jar')
--package-name Package name
--type Project type. Not normally needed if you use --build and/or --format. Check the capabilities of the service (--list) for more details
--target URL of the service to use
--version Project version (for example '0.0.1-SNAPSHOT')
--extract Extract the project archive. Inferred if a location is specified without an extension
```

**Comment by ivange94** [comment] 2018-09-13 12:35
Lol. I was actually trying to reproduce this because I wanted to fix it but
it's ok. I'll just look for something else.

**Comment by philwebb** [comment] 2018-09-13 15:32
Closing in favor of PR #14460

**Closed by philwebb** 2018-09-13 15:32 UTC
Labels: status: superseded
