### ISSUE TITLE
Empty @DefaultValue cannot be used on collections, maps, arrays or optional values

### ISSUE THREAD

**Issue by wind57** [spring-projects/spring-boot#32559] opened 2022-09-30 13:17 UTC
I have this simple configuration:

```java
@ConfigurationProperties("dummy")
public record TestRecord(@DefaultValue Set<String> values, @DefaultValue("default") String one) {
}
```

This fails with : `Parameter of type java.util.Set<java.lang.String> must have a non-empty default value.`

What I would like to get as a default value is an empty Set. Of course as a workaround, I can:

```java
public Set<String> values() {
    return values == null ? Set.of() : values;
}
```

but considering there are any of these default collections/maps, I do not want to add an accessor for each of the properties. Is there are a way to make `@DefaultValue` "return" an empty Set? thank you.

**Comment by philwebb** [comment] 2022-09-30 18:32
@wind57 This looks like a duplicate of #18917 which should have been fixed in Spring Boot 2.2.7. Which version of Spring Boot are you using? Are you able to provide a sample application that shows the problem?

**Comment by wind57** [comment] 2022-09-30 18:51
```
@ConfigurationProperties("dummy")
public record TestRecord(@DefaultValue Set<String> values, @DefaultValue("default") String one) {

}
```

and a test:

```
	@Test
	void testSpringBindingFields() {
		new ApplicationContextRunner().withUserConfiguration(UnderTest.Config.class)
			.run(context -> {
				TestRecord props = context.getBean(TestRecord.class);
				assertThat(props).isNotNull();
				assertThat(props.one()).isEqualTo("default");
				assertThat(props.values().size()).isEqualTo(0);
			});
	}

	@Configuration
	@EnableConfigurationProperties(TestRecord.class)
	static class Config {

	}
```

This is for `3.0.0-M5`. I am actually trying to simplify some code in `spring-cloud-kubernetes` , this were I spotted it.

thank you for looking into it.

**Comment by philwebb** [comment] 2022-09-30 21:12
Thanks, I misread our current code and thought that it dealt with collection types, but it doesn't. I think we should change that and allow `@DefaultValue` to mean an empty instance.

**Closed** 2022-10-01 03:17 UTC
Labels: type: bug

**Comment by wind57** [comment] 2022-10-01 03:22
That was fast! Thank you.

**Comment by wind57** [comment] 2022-10-08 19:57
would you happen to know when this one will reach spring-boot-3? just want to put a note for myself to slightly change some code when that happens, so that I do not forget; nothing more. thank you

**Comment by snicoll** [comment] 2022-10-09 07:08
@wind57 all fixes are merged forward at the same time as the fix itself. Please follow the linked issues for more details, that is https://github.com/spring-projects/spring-boot/issues/32564

**Comment by wind57** [comment] 2022-10-09 07:32
thank you.
