### ISSUE TITLE
Autoconfigure Jersey Server Metrics in a JAX-RS environment

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-boot#12904] opened 2018-04-18 11:33 UTC
Micrometer metrics for Jersey Server should be collected when Spring Boot Actuator, Micrometer Core and Micrometer Jersey 2 is on the classpath of a JAX-RS / Jersey 2 Spring Boot application as they are collected for Web MVC and Web Flux.

**Comment by snicoll** [comment] 2018-04-18 14:06
Duplicate of #12904 - @michael-simons thanks but we don't need an issue and a PR.

**Closed by snicoll** 2018-04-18 14:06 UTC
Labels: status: waiting-for-triage
