### ISSUE TITLE
Spring Boot 2.0.1 fails to start when web application uses spring-boot-starter-test

### ISSUE THREAD

**Issue by beldenge** [spring-projects/spring-boot#13047] opened 2018-05-03 14:14 UTC
A Spring Boot 2.0.1 web application will not start if the spring-boot-starter-test dependency is included.

https://stackoverflow.com/questions/49917449/cannot-start-tomcat-server-when-having-spring-boot-starter-test-dependency-in/50157009#50157009

It seems to be related to the spring-core dependency within spring-boot-starter-test.  If that specific dependency is excluded, then Spring Boot starts up fine.

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by wanghongfei** [comment] 2018-05-04 02:31
+1, I have exact same issue.

**Comment by snicoll** [comment] 2018-05-04 07:15
@wanghongfei a +1 without a sample is not helping. I've created a sample project with web and test (removing the `test` scope for the latter) and the app starts just fine as @wilkinsona indicated above.

If you want us to diagnose the problem you're experiencing, we need a sample that we can run ourselves.

**Comment by wanghongfei** [comment] 2018-05-04 08:43
hi, I created a demo project that is able to reproduce this issue:
`https://github.com/wanghongfei/springboot-issue-demo`

This application is unable to start unless you uncomment specific code snippet in `pom.xml`

**Comment by wilkinsona** [comment] 2018-05-04 08:54
Thanks for the sample. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/12457.

You need to exclude `commons-logging:common-logging` which is currently being pulled in as a transitive dependency of `org.hyperledger.fabric-sdk-java:fabric-sdk-java`. You can do so by updating your pom like this:

```diff
diff --git a/pom.xml b/pom.xml
index 6fa205d..e9743e8 100644
--- a/pom.xml
+++ b/pom.xml
@@ -36,6 +36,12 @@
             <groupId>org.hyperledger.fabric-sdk-java</groupId>
             <artifactId>fabric-sdk-java</artifactId>
             <version>1.1.0-alpha</version>
+            <exclusions>
+                <exclusion>
+                    <groupId>commons-logging</groupId>
+                    <artifactId>commons-logging</artifactId>
+                </exclusion>
+            </exclusions>
         </dependency>

         <dependency>
```

**Closed by wilkinsona** 2018-05-04 08:54 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by snicoll** [comment] 2018-05-04 09:04
> This application is unable to start

For the record, it's starting just fine, you just don't get any console log for the reason @wilkinsona mentioned.

**Comment by wanghongfei** [comment] 2018-05-04 09:06
@snicoll Yes, I've noticed that. Thanks!

**Comment by wilkinsona** [comment] 2018-05-04 18:27
@beldenge My somewhat educated guess is that I was wrong when I said "a test-scoped dependency should have no effect at all on the classpath when you run your application " above and that the exclusion affected the ordering of the main class path. If you're sufficiently curious, you could verify that theory by comparing the classpath in the working and non-working cases.
