### ISSUE TITLE
why the count of request goes to 1.4 billion in a few minutes. I use prometheus to monitor a spring boot project

### ISSUE THREAD

**Issue by nope-J** [spring-projects/spring-boot#15431] opened 2018-12-10 03:03 UTC
![1544185092279](https://user-images.githubusercontent.com/18301302/49708594-396dd680-fc6b-11e8-8433-c55e76b1c0c5.jpg)

**Comment by wilkinsona** [comment] 2018-12-10 06:49
Duplicate of #15405

**Closed by wilkinsona** 2018-12-10 06:49 UTC
Labels: status: waiting-for-triage
