### ISSUE TITLE
Springboot RestTemplate giving 500 internal error when calling service is returning 400 (POSTMAN tested)

### ISSUE THREAD

**Issue by chiranjitjasu** [spring-projects/spring-boot#16417] opened 2019-04-02 15:16 UTC

**Comment by mbhave** [comment] 2019-04-02 15:53
There’s nowhere near enough information here to diagnose the problem. If you would like us to spend time trying to help you, please spend some time describing the problem in the form of a minimal, complete sample that we can run to reproduce the issue.

**Comment by spring-issuemaster** [comment] 2019-04-09 15:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-16 15:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-16 15:55 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
