### ISSUE TITLE
Setting logging properties in application.properties not working when custom logback-spring.xml used?

### ISSUE THREAD

**Issue by wujek-srujek** [spring-projects/spring-boot#5095] opened 2016-02-05 20:30 UTC
Hi. It seems when a custom logback-spring.xml is used, the settings like logging.pattern.level, logging.pattern.console, root.level etc. stop working. Is this the case? I can't find a definite answer in the documentation.

**Comment by shakuzen** [comment] 2016-02-06 09:08
@wujek-srujek I believe the cause of the behavior you are experiencing is described in detail in issue #5073

**Comment by wujek-srujek** [comment] 2016-02-06 15:54
So I decided to understand it and debugged into it, and here are my observations of the behavior when logback-spring.xml is used:

* It seems settings like CONSOLE_LOG_PATTERN etc. are to never set as System properties, contrary to what the documentation says. The only exceptions are PID and LOG_EXCEPTION_CONVERSION_WORD. I run code printing the properties when defaults are used and the results are nulls except for the aforementioned two. They at most seem to be set as context properties of the logging context of choice. I think the documentation is wrong here.
* I was wrong thinking the logger levels settings in application.properties did not work (I made a typo) - they are applied as this is the very last thing performed in LoggingApplicationListener#initialize(ConfigurableEnvironment, ClassLoader) when it calls initializeFinalLoggingLevels(ConfigurableEnvironment, LoggingSystem).
* PID and LOG_EXCEPTION_CONVERSION_WORD work fine as they are set as system properties (which Logback can use) early in the initialization process by LogginApplicationListener, even before the logging system is chosen and initialized.
* Setting logging.pattern.level in application.properties has no effect as it is only used when Spring Boot defaults are used - see LogbackLoggingSystem#loadDefaults(LoggingInitializationContext, LogFile), which sets a Logback context property using logging.level.pattern. I guess this could be fixed if the property was set earlier before the decision whether to apply the defaults or a config file is made. But, as this decision is made in the AbstractLoggingSystem class, and this setting only works for Logback (as described in the configuration), we are out of luck. I guess the setting the LOG_LEVEL_PATTERN context property would have to be copied to the LogbackLoggingSystem#loadConfiguration method as well.

**Comment by wilkinsona** [comment] 2016-02-08 10:03
@wujek-srujek Thanks for sharing your analysis. As @shakuzen suggested, what you have described is a duplicate of #5073.

If you are using `logback-spring.xml`, you don't actually need the system properties. You can reference values straight from the environment. Please see [this section in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_environment_properties) for more details.

**Closed** 2016-02-08 10:03 UTC
Labels: duplicate

**Comment by wujek-srujek** [comment] 2016-02-08 21:49
@wilkinsona I'm sorry, I wasn't aware it is all clear now. At the very least I got to know a bit more about Boots internals ;d

Using springProperty in logback-spring.xml is a workaround I have been using thus far. But it is just a workaround, and a kind of ugly one. Here is why I think so: right now, I need the confusing extra step of smuggling something from the Spring Environment (logging.pattern.level) into a Logback scope (local is enough, no need to set it co context scope like the docs imply, if it is just for variable replacement within logback-spring.xml). And I need to know the name of the property to set (it has to be named LOG_LEVEL_PATTERN in order for the default CONSOLE_LOG_PATTERN from defaults.xml to pick it up). And, it must be defined before the defaults.xml is actually imported, as otherwise it won't work (this is the most confusing part, I guess) - CONSOLE_LOG_PATTERN will have been already evaluated at the point the level pattern is set and it would never be used by anybody.
Whereas the other solution of automatically setting system properties nothing special needs to be done and it would just work (Logback does look things up in system props).
