### ISSUE TITLE
My application response time is high for some random get api requests. when I drill down the logs then I found  OrderedRequestContextFilter.doFilter() taking 5-25 seconds

### ISSUE THREAD

**Issue by krishnkanttnf** [spring-projects/spring-boot#17450] opened 2019-07-08 12:13 UTC

**Comment by krishnkanttnf** [comment] 2019-07-08 12:16
Spring Boot Version:- 2.1.5.RELEASE

**Comment by bclozel** [comment] 2019-07-08 12:23
In this case, the time spent within the `doFilter` method is probably including everything behind that filter (the request processing by the Framework, other filters, your controllers, etc).

Please provide more information, such as a project we can run to reproduce the issue.
If the issue is hard to reproduce, adding logs within the controllers, or profiling your application might help to narrow down the issue.

**Comment by krishnkanttnf** [comment] 2019-07-11 04:11
I could not found much in my logs but the following is my newrelic traces where it is stating OrderedRequestContextFilter.doFilter() is only taking most of the time.

Newrelic shnapshot
=============
![image](https://user-images.githubusercontent.com/49519510/61021655-02f26880-a3c0-11e9-8824-e601f196cfe3.png)

**Comment by wilkinsona** [comment] 2019-07-11 07:35
Thanks for the snapshot from New Relic. I am a little skeptical about what it is showing. The `doFilter()` method of `OrderedRequestContextFilter` is inherited from `OncePerRequestFilter` and it does very little so I would not expect it to take anywhere near 100% or 99.98% of the time. Without knowing what New Relic considers to be "Application code", I don't think we can draw too many conclusions here.

Can you please try to provide a sample that reproduces the application, or profile the application with something like YourKit to get a clearer view of where the time is spent?

**Comment by krishnkanttnf** [comment] 2019-07-15 08:43
@NewRelic says deeper visibility is not available because these classes and methods are not instrumented with java code.
As it occurs randomly that's why we are not able to reproduce or get thread dump for this to further analysis.

**Comment by wilkinsona** [comment] 2019-07-15 08:52
Thanks for the update. Unfortunately, without any further information we aren't going to be able to help you. It looks very much like the problem lies in your application code or in something that your application code is calling. Perhaps you can configure New Relic to instrument (some of) that code so that you have more information available to diagnose the problem the next time it occurs.

I'm going to close this issue for now. We can re-open it in the future if you get some more information and it shows that the problem is caused by Spring Boot after all.

**Closed by wilkinsona** 2019-07-15 08:52 UTC
Labels: status: feedback-provided, status: waiting-for-triage
