### ISSUE TITLE
memory leak problem about redirect

### ISSUE THREAD

**Issue by zhao41654828** [spring-projects/spring-boot#13771] opened 2018-07-14 14:58 UTC
our team has a memory leak problem lately.
I have dump the heap and found that there are many strings in the heap. the strings is something about redirect string. So we reproduce the problem by the following demo project: https://github.com/zhao41654828/springstudy/tree/master/service-hi

controller adress: https://github.com/zhao41654828/springstudy/blob/master/service-hi/src/main/java/com/forezp/web/MiniProgramController.java

Debug the program by sending a request:127.0.0.1:8763/web/testRedirect1
we can find that it run into like this:
![image](https://user-images.githubusercontent.com/4076590/42725577-69dcd74e-87b8-11e8-8d2e-107e0c960af1.png)

In the AbstractAutoProxyCreator class, the advisedBeans don't have number limit, the ConcurrentHashMap will have a lot of objects.

I want to know this is whether or not a bug in springmvc. If not, I want to know the reason and how can I to avoid it.
Now i do like this to avoid it.
```
	/**
	 * @param
	 * @return
	 */
	@RequestMapping("/testRedirect1")
	public void getTest2(HttpServletRequest req, HttpServletResponse resp) throws IOException {
		String redirectUrl =  "http://www.baidu.com";
		Random random = new Random();
		int data = random.nextInt(21_0000_0000);
		redirectUrl = redirectUrl + "/" + data;
		resp.sendRedirect(redirectUrl);
	}
```

**Comment by wilkinsona** [comment] 2018-07-15 14:47
Thanks for the sample. You are using Spring Boot 1.4.2 which is no longer supported. You are also using a mixture of versions of Spring Framework modules (4.3.4.RELEASE and 4.3.9.RELEASE) and of Spring Cloud modules. Please update your dependency versions to use supports versions (the latest Spring Boot 1.5.x, for example) and see if the problem remains. If it does, we'll happily take a look at an updated sample.

**Comment by wilkinsona** [comment] 2018-07-15 16:45
Thanks, but 1.5.7 isn’t the latest 1.5.x version. Please upgrade Spring Boot to 1.5.14 and all your other dependencies to their matching latest version.

**Comment by zhao41654828** [comment] 2018-07-16 04:33
I have try 1.5.14, the result is still as before.
![springboot_1_5_14](https://user-images.githubusercontent.com/4076590/42743195-589e9fca-88f4-11e8-9584-283d0f657a6d.png)

**Comment by wilkinsona** [comment] 2018-07-16 08:38
Thanks. There are still some problems with your dependencies (mixing Spring Cloud versions, for example) but I don't think they're causing the problem you're seeing. You can reproduce your problem with Spring Boot 1.5.15, dependencies on `spring-boot-starter-web` and `spring-boot-starter-aop` and this minimal application:

```java
package com.example.demo;

import java.util.UUID;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@SpringBootApplication
@EnableAspectJAutoProxy
public class Gh13771Application {

	public static void main(String[] args) {
		SpringApplication.run(Gh13771Application.class, args);
	}

	@Controller
	public static class RedirectController {

		@RequestMapping("/")
		public String redirect() {
			return "redirect:/example/" + UUID.randomUUID();
		}
		
	}

}
```

The problem is that `InternalResourceViewResolver` calls `AutowireCapableBeanFactory.initializeBean(Object existingBean, String beanName)` using the complete URL as the `beanName`. The bean name is then used by `AbstractAutoProxyCreator.wrapIfNecessary(Object, String, Object)` as the key when it caches the fact that no advice applies to it. This feels like a bug to me, but it will have to be addressed in Spring Framework as it is out of Boot's control. I've opened [SPR-17045](https://jira.spring.io/browse/SPR-17045).

**Closed** 2018-07-16 08:38 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by zhao41654828** [comment] 2018-07-17 01:37
Thanks.
I searched the spr and found that someone has reported before:
https://jira.spring.io/browse/SPR-15220?jql=text%20~%20%22AbstractAutoProxyCreator%20memory%22

But the Spring Framewok may think that to make the beanname to be the same is a better solution. 
I hope they can notice this problem and give some solutions.
