### ISSUE TITLE
git clone failure,filename too long

### ISSUE THREAD

**Issue by zhoujw8792** [spring-projects/spring-boot#10880] opened 2017-11-02 03:50 UTC
git.exe clone --progress -v "git@github.com:spring-projects/spring-boot.git" "D:\Git\spring-boot"

Cloning into 'D:\Git\spring-boot'...
remote: Counting objects: 302554, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 302554 (delta 21), reused 35 (delta 9), pack-reused 302473
Receiving objects: 100% (302554/302554), 62.79 MiB | 491.00 KiB/s, done.
Resolving deltas: 100% (124075/124075), done.
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/JavaPluginActionIntegrationTests-additionalMetadataLocationsCompilerArgumentIsAddedWhenAnnotationProcessorIsOnTheClasspath.gradle: Filename too long
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/JavaPluginActionIntegrationTests-additionalMetadataLocationsCompilerArgumentIsNotAddedWhenAnnotationProcessorIsNotOnTheClasspath.gradle: Filename too long
Checking out files: 100% (4883/4883), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by wilkinsona** [comment] 2017-11-02 07:35
Duplicate of #10868

**Closed by wilkinsona** 2017-11-02 07:35 UTC
Labels: status: waiting-for-triage
