### ISSUE TITLE
Document using the Shadow plugin as an alternative to Boot's fat jars when using Gradle

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-boot#1828] opened 2014-11-05 13:12 UTC
I found the following is required in Gradle to get a fat jar working when cannot use the `spring-boot-gradle-plugin` plugin:

``` groovy
import com.github.jengelman.gradle.plugins.shadow.transformers.*

// Can't use Boot's nested jar packaging due to environment constrained classloader
apply plugin: 'com.github.johnrengelman.shadow'

shadowJar {
  zip64 true

  exclude 'META-INF/*.SF'
  exclude 'META-INF/*.DSA'
  exclude 'META-INF/*.RSA'

  // Required for Spring
  mergeServiceFiles()
  transform(AppendingTransformer) { resource = 'reference.conf'  }
  transform(AppendingTransformer) { resource = 'META-INF/spring.handlers'  }
  transform(AppendingTransformer) { resource = 'META-INF/spring.schemas'  }
  transform(AppendingTransformer) { resource = 'META-INF/spring.tooling'  }
  transform(PropertiesFileTransformer) { paths = ['META-INF/spring.factories' ] }

  // ...
}
```

The docs should strongly recommend the `shadow` / `shade` plugins for environmentally constrained classloaders¹ because resource transformation is a requirement. Without it, essential beans such as converters, property placeholder configurers, etc. go missing from Spring Boot's autoconfiguration (i.e. `spring.factories`). The result is very difficult to diagnose.

¹environmentally constrained classloaders: A system classloader not under your control.

**Comment by btiernay** [comment] 2015-08-18 02:18
Just hit an issue in a new Spring Boot version. I needed to amend the above to have:

```groovy
transform(PropertiesFileTransformer) { paths = ['META-INF/spring.factories' ] }
```
This seemed to have resolved my issue.

**Comment by unilama** [comment] 2016-07-07 14:59
Final working example should be like that, strategy is required if you are using several components that contains spring.factories: 

```groovy

import com.github.jengelman.gradle.plugins.shadow.transformers.*
shadowJar {

    // Required for Spring
    mergeServiceFiles()
    append 'META-INF/spring.handlers'
    append 'META-INF/spring.schemas'
    append 'META-INF/spring.tooling'
    transform(PropertiesFileTransformer) {
        paths = ['META-INF/spring.factories' ]
        mergeStrategy = "append"
    }

}

```

I hope it will save someone's lot of time :)

**Comment by philwebb** [comment] 2018-03-22 15:23
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by wilkinsona** [comment] 2018-04-24 14:32
I think there might be some merit to doing something in this area. Spring Cloud Function (and FaaS in general) would benefit from an easy way to produce a shadowed jar. We really need something that's equivalent to the Maven Shade Plugin's configuration from the starter parent pom. That could take the form of documentation, or it could possibly take the form of some code in Boot's gradle plugin that sets up the various transformers.

**Comment by wilkinsona** [comment] 2018-11-27 15:31
With the `spring-boot-docs` project, there's no easy way for us to test that the Shadow plugin configuration works as expected and I don't want to add an untested snippet. I will add a link to the Shadow plugin alongside the other alternatives though.

**Closed** 2018-11-27 15:32 UTC
Labels: type: documentation

**Comment by vinothkumarcyantriks** [comment] 2020-03-24 18:57
> Final working example should be like that, strategy is required if you are using several components that contains spring.factories:
> 
> ```groovy
> import com.github.jengelman.gradle.plugins.shadow.transformers.*
> shadowJar {
> 
>     // Required for Spring
>     mergeServiceFiles()
>     append 'META-INF/spring.handlers'
>     append 'META-INF/spring.schemas'
>     append 'META-INF/spring.tooling'
>     transform(PropertiesFileTransformer) {
>         paths = ['META-INF/spring.factories' ]
>         mergeStrategy = "append"
>     }
> 
> }
> ```
> 
> I hope it will save someone's lot of time :)

Helped a alot 🤗 Thanks

**Comment by raj-saxena** [comment] 2020-04-01 16:25
@unilama thanks for your comment. I was looking for this as Google's Dataflow also doesn't work with Spring's Fat-jar.
For **KotlinDSL**, here's what I had to do to make it work - 
```
plugins {
    id("com.github.johnrengelman.shadow") version "5.2.0"
}

...

tasks.withType<ShadowJar> {
    isZip64 = true
    // Required for Spring
    mergeServiceFiles()
    append("META-INF/spring.handlers")
    append("META-INF/spring.schemas")
    append("META-INF/spring.tooling")
    transform(PropertiesFileTransformer().apply {
        paths = listOf("META-INF/spring.factories")
        mergeStrategy = "append"
    })
}
```

**Comment by adrian-baker** [comment] 2021-08-12 21:29
Another aspect of the Spring Gradle plugin that needs manually recreating is the exclusion of the `developmentOnly` from the resulting jar. By default shadowJar consumes the `runtimeClasspath` configuration, and the plugin applies `runtimeClasspath.extendsFrom(developmentOnly)`, which means the examples above include `developmentOnly` dependencies in the resulting shadowedJar, which is likely not desired.

I've found this the simplest way to recreate that:

```
shadowJar {
  configurations = [project.configurations.productionRuntimeClasspath]
```

Hopefully my reading of https://github.com/spring-projects/spring-boot/issues/26686 is that the `productionRuntimeClasspath` configuration created by the plugin is considered "API":

**Comment by ShalabhR** [comment] 2022-11-08 19:04
Has this issue been addressed in spring-boot 2.7.5 ? I was using the shadowJar task defined above with my app that used spring-boot v2.6.6 but after upgrading to 2.7.5 looks like it stopped working and I had to remove shadowJar. Can anyone confirm if there was an effort to fix in 2.7.5 ?

**Comment by wilkinsona** [comment] 2022-11-08 19:29
@ShalabhR This was a documentation issue, adding to Boot's reference documentation a link to the Shadow plugin. As such,  there was nothing to fix. If you have a build that works with 2.6.6 and fails with 2.7.5, you may have found a regression. If you open a new issue and provide a minimal sample that reproduces the problem, we'll take a look.

**Comment by Djaytan** [comment] 2024-08-28 20:08
Because I struggled several hours solving my issue, here is what I have done with Spring Boot v3.0+ (but may work for v2.7+ as well... To be tested):

> Spring Boot 2.7 introduced a new ‘META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports’ file for registering auto-configurations, while maintaining backwards compatibility with registration in ‘spring.factories’. With Spring Boot 3.0 release, support for registering auto-configurations in ‘spring.factories’ has been removed in favor of the imports file.

=> https://stackoverflow.com/q/74871072/10165346

This means that it is required to merge the `org.springframework.boot.autoconfigure.AutoConfiguration.imports` files as well. Starting from there, auto-configuration starts to work again!

This leads me to the following Gradle configuration for the `shadowJar` task (Kotlin DSL):

```kotlin
shadowJar {
  // Required for proper Spring Boot shading
  mergeServiceFiles()
  append("META-INF/spring.handlers")
  append("META-INF/spring.schemas")
  append("META-INF/spring.tooling")
  append("META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports")
  transform(PropertiesFileTransformer().apply {
    paths = listOf("META-INF/spring.factories")
    mergeStrategy = "append"
  })
}
```

Hope it will help.

**Comment by Goooler** [comment] 2025-07-17 16:07
There is a new feature request on Shadow side, see https://github.com/GradleUp/shadow/issues/1489.
