### ISSUE TITLE
Project use spring-boot 3.2.0，run jar package  NegativeArraySizeException: -26949

### ISSUE THREAD

**Issue by Aerotheif** [spring-projects/spring-boot#38616] opened 2023-12-01 04:36 UTC
I upgraded the project from Spring Boot 2.7.18 to 3.2.0. The project runs normally in IDEA, but when I package it into a JAR using Maven, I encounter an error, specifically java.lang.NegativeArraySizeException: -26949. However, when I downgrade the dependency version to 3.1.6, the generated package can run successfully.Maybe it is a bug?

Exception 
```
PS C:\Users\twist\workspace\java-project\qince\agent\admin\agent-admin-platform> java -jar .\target\agent-admin-platform-1.0.0.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: java.lang.IllegalArgumentException: Unable to instantiate factory class [org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer] for factory type [org.springframework.context.ApplicationContextInitializer]
        at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$throwing$0(SpringFactoriesLoader.java:647)
        at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$handleMessage$3(SpringFactoriesLoader.java:671)
        at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:231)
        at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:206)
        at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:160)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:482)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:478)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:283)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:262)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331)
        at com.qince.AgentAdminApplication.main(AgentAdminApplication.java:22)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.isKotlinType(SpringFactoriesLoader.java:420)
        at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.findPrimaryKotlinConstructor(SpringFactoriesLoader.java:415)
        at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.findConstructor(SpringFactoriesLoader.java:403)
        at org.springframework.core.io.support.SpringFactoriesLoader$FactoryInstantiator.forClass(SpringFactoriesLoader.java:394)
        at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:227)
        ... 16 more
Caused by: java.lang.NegativeArraySizeException: -26949
        at org.springframework.boot.loader.zip.ZipContent$Loader.<init>(ZipContent.java:435)
        at org.springframework.boot.loader.zip.ZipContent$Loader.loadContent(ZipContent.java:565)
        at org.springframework.boot.loader.zip.ZipContent$Loader.openAndLoad(ZipContent.java:543)
        at org.springframework.boot.loader.zip.ZipContent$Loader.loadNestedZip(ZipContent.java:537)
        at org.springframework.boot.loader.zip.ZipContent$Loader.load(ZipContent.java:522)
        at org.springframework.boot.loader.zip.ZipContent.open(ZipContent.java:372)
        at org.springframework.boot.loader.zip.ZipContent.open(ZipContent.java:361)
        at org.springframework.boot.loader.jar.NestedJarFileResources.<init>(NestedJarFileResources.java:57)
        at org.springframework.boot.loader.jar.NestedJarFile.<init>(NestedJarFile.java:141)
        at org.springframework.boot.loader.jar.NestedJarFile.<init>(NestedJarFile.java:120)
        at org.springframework.boot.loader.net.protocol.jar.UrlNestedJarFile.<init>(UrlNestedJarFile.java:42)
        at org.springframework.boot.loader.net.protocol.jar.UrlJarFileFactory.createJarFileForNested(UrlJarFileFactory.java:86)
        at org.springframework.boot.loader.net.protocol.jar.UrlJarFileFactory.createJarFile(UrlJarFileFactory.java:55)
        at org.springframework.boot.loader.net.protocol.jar.UrlJarFiles.getOrCreate(UrlJarFiles.java:72)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.connect(JarUrlConnection.java:289)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.getJarFile(JarUrlConnection.java:99)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.getJarFile(JarUrlClassLoader.java:185)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.definePackage(JarUrlClassLoader.java:143)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.definePackageIfNecessary(JarUrlClassLoader.java:126)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:99)
        at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:304)
        at org.springframework.core.KotlinDetector.<clinit>(KotlinDetector.java:47)
        ... 21 more

```

My pom.xml

```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.qince</groupId>
	<artifactId>agent-admin-platform</artifactId>
	<version>1.0.0</version>
	<name>agent_admin_init</name>
	<description>XX前置机管理端</description>



    <dependencies>
	
		<!-- web -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
    
        <!-- Postgresql驱动包 -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>


		<!--监控依赖-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- 前置机管理端-->
		<dependency>
			<groupId>com.qince</groupId>
			<artifactId>agent-admin-dependency-pkg</artifactId>
			<version>3.2.0</version>
		</dependency>




	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by bclozel** [comment] 2023-12-01 07:14
This is most likely a duplicate of #38572. I'm closing this issue as a result. You can check your application with 3.2.1-SNAPSHOT and let us know. If the problem is not fixed we can reopen this issue if you can provide a sample application that reproduces the problem with the latest SNAPSHOT version. Thanks!

**Closed** 2023-12-01 07:14 UTC
Labels: status: waiting-for-triage

**Comment by Aerotheif** [comment] 2023-12-01 08:39
THS~

**Comment by manjunathkadrolli** [comment] 2023-12-15 08:35
Any ETA for 3.2.1 release ?

**Comment by bclozel** [comment] 2023-12-15 09:21
@manjunathkadrolli see https://github.com/spring-projects/spring-boot/milestones and https://calendar.spring.io/

**Comment by manjunathkadrolli** [comment] 2023-12-15 11:27
@bclozel thank you missed to check that
