### ISSUE TITLE
Artifactory contains wrong metadata

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#10532] opened 2017-10-06 00:35 UTC
Related to the recent build update, artifactory is picking older versions.

**Comment by philwebb** [comment] 2017-10-06 00:40
The root cause is that our [concourse artifactory resource](https://github.com/spring-io/artifactory-resource) is uploading version with timestamp snapshot names (`1.0.0.BUILD-20171005.194031-1`) rather then `1.0.0.BUILD-SNAPSHOT`).

Although these files upload fine, they aren't sorted correctly. By default artifactory only sorts on the very last part of the filename (`-1` in our case). See [RTFACT-7266](https://www.jfrog.com/jira/browse/RTFACT-7266) for more background on sorting.

If we can upload our artifacts using a simple `-SNAPSHOT` suffix, then the number will be generated by artifactory and things should work.

**Comment by mbhave** [comment] 2017-10-06 01:43
duplicate of #10521

**Closed by mbhave** 2017-10-06 01:43 UTC
Labels: status: duplicate
