### ISSUE TITLE
spring-boot-starter-parent 3.2.4 controller advise issue

### ISSUE THREAD

**Issue by mbanaszkiewicz-vonage** [spring-projects/spring-boot#40148] opened 2024-04-02 10:23 UTC
Looks like spring-boot-starter-parent 3.2.4 changed some behavior vs 3.2.3, reproduction steps:

clone https://github.com/mbanaszkiewicz-vonage/controller-advise-repro 
run the app, go to http://localhost:9000/test - you should see default error page with http 400 status & no stacktrace in app logs.

change spring-boot-starter-parent from 3.2.3 to 3.2.4, refresh maven deps, build & re-run the app, go to http://localhost:9000/test - now default error page shows http 500 & there is a stacktrace, IllegalArgumentException was not properly converted to ResponseStatusException(BAD_REQUEST).

**Comment by bclozel** [comment] 2024-04-02 12:12
Thanks for the report and sample project. I think this is a duplicate of spring-projects/spring-framework#32538 and I'm closing this issue as a result.

**Closed by bclozel** 2024-04-02 12:12 UTC
Labels: status: waiting-for-triage
