### ISSUE TITLE
Remove ConfigurationPropertiesBindingPostProcessor @Autowired setters

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#8918] opened 2017-04-18 03:55 UTC
`ConfigurationPropertiesBindingPostProcessor` has some unusual autowired setters that are "self injected". The `getDefaultConversionService` calls `applicationContext.getAutowireCapableBeanFactory().autowireBean(this)` to inject them.

Interestingly they don't work if called in `afterPropertiesSet` which makes me a little suspicious that things aren't working more by luck than design.

We'll probably need to revisit `ConfigurationPropertiesBindingPostProcessor` again anyway to support interface based properties.

**Comment by snicoll** [comment] 2017-04-18 07:15
See also #8344

**Comment by snicoll** [comment] 2017-09-04 12:11
Actually, Duplicate of #8344

**Closed by snicoll** 2017-09-04 12:11 UTC
Labels: priority: normal, theme: configuration, type: chore
