### ISSUE TITLE
The description for spring-boot-starter-jdbc in Spring Boot 2 reference documentation should be HikariCP

### ISSUE THREAD

**Issue by simonwg** [spring-projects/spring-boot#12565] opened 2018-03-21 02:58 UTC
Spring Boot 2.0 reference documentation

In Spring Boot starters listing, Table 13.1. Spring Boot application starters, the description for `spring-boot-starter-jdbc` should be `Starter for using JDBC with the
HikariCP connection pool` instead of Tomcat Connection Pool as it is the default in `Spring Boot 2.0`

**Comment by snicoll** [comment] 2018-03-21 03:46
Duplicate of #12387

**Closed by snicoll** 2018-03-21 03:46 UTC
Labels: status: waiting-for-triage
