### ISSUE TITLE
Support for MetricRegistry in Spring Boot 2?

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-boot#11702] opened 2018-01-20 09:14 UTC
Spring Boot v1.5.x auto configured a `MetricRegistry` bean, with which developers could add their custom metrics to and were exposed on the actuator `/metrics` endpoint. This has worked very well for us.

Spring Boot v2 does not appear to auto configure a `MetricRegistry` bean. So without changes, when you startup you'll get a `org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.codahale.metrics.MetricRegistry'`.

I don't see references to this change in any of the [2.0.0.M1-M7 release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Release-Notes), nor [migration guide.](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide). Is this just an oversight or did I miss something? I do see references to Micrometer, but nothing saying the previous support is no longer included.

Also, is there a way to manually enable the previous support?

**Comment by snicoll** [comment] 2018-01-20 09:20
Duplicate of #10313

The previous support is no longer included.

**Closed by snicoll** 2018-01-20 09:20 UTC
Labels: status: waiting-for-triage

**Comment by wilkinsona** [comment] 2018-01-22 10:15
Boot's metrics being replaced with Micrometer is listed in [the user-facing changes in M4](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M4-Release-Notes#user-facing-changes).
