### ISSUE TITLE
Investigate performance of 1.3.0.RC1

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#4252] opened 2015-10-21 04:46 UTC
Running a `java -jar` web app seems about 300-500ms slower than 1.2.x to me.

**Comment by philwebb** [comment] 2015-10-21 21:28
Running 1.3.x with Spring 4.1.8 shows similar timings so it looks like it's a Boot issue.

**Comment by wilkinsona** [comment] 2015-10-26 11:59
Some numbers (averages from 10 runs) from `spring-boot-sample-web-freemarker. 1.2.7.RELEASE started in 2.461 seconds with the JVM running for 2.824 seconds. 1.3.0.BUILD-SNAPSHOT started in 2.729 seconds with the JVM running for 3.082 seconds.

**Comment by wilkinsona** [comment] 2015-10-26 13:48
1.3.0 evaluates an addition 32 conditions but that only accounts for ~40ms of the time difference.

**Comment by wilkinsona** [comment] 2015-10-26 14:11
Hacking `spring.factories` in `spring-boot-autoconfigure` so that 1.3 has (roughly) the same set of auto-configuration classes and conditions as 1.2.x still shows the same difference in startup time.

**Comment by snicoll** [comment] 2015-10-26 16:59
The batch samples is also quite slower on `master`: `1.2.8.BUILD-SNAPSHOT` executes around 0.12 sec while master executes around 0.14 sec.

**Comment by snicoll** [comment] 2015-10-27 08:58
@philwebb are you sure you ran `1.3.x` with Spring Framework `4.1.x`? There are some basic stuff (event listener) that couldn't work so I am wondering how you managed to to work around that.

**Comment by snicoll** [comment] 2015-10-28 19:57
Alright, something is definitely related to Spring Framework. I created an empty Spring Boot application with `spring-boot-starter-web` and `spring-boot-starter-actuator` and I started it 50 times in a loop. I then switch to the exact same code base running with Spring Framework `4.1.8.RELEASE`

* master with Spring Framework: `4.2.3.BUILD-SNAPSHOT`: between `27.2` and `28.1` sec 
* ["patched" master](https://github.com/snicoll/spring-boot/commit/11b75c379a8174c2b45ebf317b190b6da882a39b) with Spring Framework: `4.1.8.RELEASE`: between `21.1` and `23.1` sec

On master this app starts around `0.35` sec while with the patched version using Spring Framework `4.1.8.RELEASE` a typical startup time is more around `0.3` sec.

**Comment by snicoll** [comment] 2015-10-29 12:38
There is a confirmed performance regression in annotation lookup that we are currently investigating, see [SPR-13621](https://jira.spring.io/browse/SPR-13621) for more details.

**Comment by snicoll** [comment] 2015-11-03 17:05
@jhoeller has been working on some optimizations in Spring Framework and we could manage to cut those numbers a bit: From a [27.2 to 28.1 sec] range we are more around a [26.9 to 27.6 sec] range. There are more pointers in Spring Framework but I'll also start looking a bit more at boot itself (even though I haven't see any specific indication yet).

**Comment by snicoll** [comment] 2015-11-04 11:08
So an update, testing that same app with 3 configurations: Spring Boot `1.2.8-SNAP`, Spring Boot `1.3.0-SNAP` (patched) with Spring Framework `4.1.8.RELEASE` and  finally Spring Boot `1.3.0-SNAP` (using the latest Spring Framework `4.2.3-SNAP` build.

```
1.2.8-SNAP + 4.1.8

Started SampleWebFreeMarkerApplication in 2.543 seconds (JVM running for 2.879)
Started SampleWebFreeMarkerApplication in 0.274 seconds (JVM running for 3.224)
Started SampleWebFreeMarkerApplication in 0.252 seconds (JVM running for 3.535)
Started SampleWebFreeMarkerApplication in 0.224 seconds (JVM running for 3.815)
Started SampleWebFreeMarkerApplication in 0.222 seconds (JVM running for 4.097)
Started SampleWebFreeMarkerApplication in 0.232 seconds (JVM running for 4.39)
Started SampleWebFreeMarkerApplication in 0.217 seconds (JVM running for 4.666)
Started SampleWebFreeMarkerApplication in 0.22 seconds (JVM running for 4.945)
Started SampleWebFreeMarkerApplication in 0.231 seconds (JVM running for 5.233)
Started SampleWebFreeMarkerApplication in 0.224 seconds (JVM running for 5.518)

1.3.0-SNAP (patched) + 4.1.8

Started SampleWebFreeMarkerApplication in 2.632 seconds (JVM running for 3.027)
Started SampleWebFreeMarkerApplication in 0.381 seconds (JVM running for 3.481)
Started SampleWebFreeMarkerApplication in 0.257 seconds (JVM running for 3.743)
Started SampleWebFreeMarkerApplication in 0.253 seconds (JVM running for 4.056)
Started SampleWebFreeMarkerApplication in 0.252 seconds (JVM running for 4.367)
Started SampleWebFreeMarkerApplication in 0.251 seconds (JVM running for 4.678)
Started SampleWebFreeMarkerApplication in 0.249 seconds (JVM running for 4.983)
Started SampleWebFreeMarkerApplication in 0.268 seconds (JVM running for 5.308)
Started SampleWebFreeMarkerApplication in 0.255 seconds (JVM running for 5.624)
Started SampleWebFreeMarkerApplication in 0.265 seconds (JVM running for 5.951)

1.3.0-SNAP + 4.2.3-SNAP

Started SampleWebFreeMarkerApplication in 3.012 seconds (JVM running for 3.36)
Started SampleWebFreeMarkerApplication in 0.491 seconds (JVM running for 3.921)
Started SampleWebFreeMarkerApplication in 0.449 seconds (JVM running for 4.428)
Started SampleWebFreeMarkerApplication in 0.456 seconds (JVM running for 4.942)
Started SampleWebFreeMarkerApplication in 0.411 seconds (JVM running for 5.416)
Started SampleWebFreeMarkerApplication in 0.405 seconds (JVM running for 5.883)
Started SampleWebFreeMarkerApplication in 0.387 seconds (JVM running for 6.329)
Started SampleWebFreeMarkerApplication in 0.435 seconds (JVM running for 6.824)
Started SampleWebFreeMarkerApplication in 0.472 seconds (JVM running for 7.358)
Started SampleWebFreeMarkerApplication in 0.445 seconds (JVM running for 7.863)
```

In case someone is interested, the [Yourkit performance snapshots are also available](https://www.dropbox.com/s/iit6cskbt7h9z1i/yourkit-spring-boot-1.3-snapshots.zip?dl=0). According to these figures, there is a ~8% increase between 1.2 and 1.3 when the Spring Framework version has _not_ changed but that increases to up to 40% when we also switch to Spring Framework 4.2.

A few hotspots:

* `Method.invoke` invocation count has increased by ~30%
* _lots_ of CPU cycles are spent in the new annotation processing stuff introduced in 4.2

**Comment by philwebb** [comment] 2015-11-05 08:30
I've made some tweaks to both Spring Boot and Spring Framework. Rests required.

**Comment by snicoll** [comment] 2015-11-05 10:40
Tweaks in Spring Boot + 4.1.8

```
Started SampleWebFreeMarkerApplication in 2.532 seconds (JVM running for 2.868)
Started SampleWebFreeMarkerApplication in 0.403 seconds (JVM running for 3.342)
Started SampleWebFreeMarkerApplication in 0.293 seconds (JVM running for 3.697)
Started SampleWebFreeMarkerApplication in 0.269 seconds (JVM running for 4.027)
Started SampleWebFreeMarkerApplication in 0.272 seconds (JVM running for 4.358)
Started SampleWebFreeMarkerApplication in 0.251 seconds (JVM running for 4.671)
Started SampleWebFreeMarkerApplication in 0.235 seconds (JVM running for 4.965)
Started SampleWebFreeMarkerApplication in 0.239 seconds (JVM running for 5.26)
Started SampleWebFreeMarkerApplication in 0.249 seconds (JVM running for 5.566)
Started SampleWebFreeMarkerApplication in 0.234 seconds (JVM running for 5.857)
```

Tweaks in Spring Boot and Spring Framework

```
Started SampleWebFreeMarkerApplication in 2.555 seconds (JVM running for 2.913)
Started SampleWebFreeMarkerApplication in 0.521 seconds (JVM running for 3.506)
Started SampleWebFreeMarkerApplication in 0.372 seconds (JVM running for 3.94)
Started SampleWebFreeMarkerApplication in 0.371 seconds (JVM running for 4.372)
Started SampleWebFreeMarkerApplication in 0.35 seconds (JVM running for 4.782)
Started SampleWebFreeMarkerApplication in 0.358 seconds (JVM running for 5.202)
Started SampleWebFreeMarkerApplication in 0.332 seconds (JVM running for 5.596)
Started SampleWebFreeMarkerApplication in 0.36 seconds (JVM running for 6.017)
Started SampleWebFreeMarkerApplication in 0.349 seconds (JVM running for 6.425)
Started SampleWebFreeMarkerApplication in 0.377 seconds (JVM running for 6.863)
```

Funnily enough, the performance gain is more or less (even exactly here) 1 sec which is almost 13% better. The performance drop between 1.2 and 1.3 is now around 25%

**Comment by snicoll** [comment] 2015-11-05 12:26
Latest changes

```
Started SampleWebFreeMarkerApplication in 2.426 seconds (JVM running for 2.721)
Started SampleWebFreeMarkerApplication in 0.51 seconds (JVM running for 3.302)
Started SampleWebFreeMarkerApplication in 0.371 seconds (JVM running for 3.729)
Started SampleWebFreeMarkerApplication in 0.407 seconds (JVM running for 4.196)
Started SampleWebFreeMarkerApplication in 0.371 seconds (JVM running for 4.624)
Started SampleWebFreeMarkerApplication in 0.337 seconds (JVM running for 5.019)
Started SampleWebFreeMarkerApplication in 0.355 seconds (JVM running for 5.437)
Started SampleWebFreeMarkerApplication in 0.335 seconds (JVM running for 5.833)
Started SampleWebFreeMarkerApplication in 0.362 seconds (JVM running for 6.254)
Started SampleWebFreeMarkerApplication in 0.329 seconds (JVM running for 6.644)
```

The performance drop compared to 1.2 is around 20% now.

**Comment by philwebb** [comment] 2015-11-05 16:58
Running with Spring Framework at commit [54ce42e1](https://github.com/spring-projects/spring-framework/commit/c88877f1c4547c692bee372cd487c22c54ce42e1) I'm seeing the following results with `SampleWebFreeMarkerApplication`.

I changed the `main` method as follows:

```java
	public static void main(String[] args) throws Exception {
		SpringApplication.run(SampleWebFreeMarkerApplication.class, args).close();
	}
```

**Running manually in Eclipse**

_1.2.x_

```
Started SampleWebFreeMarkerApplication in 2.509 seconds (JVM running for 2.825)
Started SampleWebFreeMarkerApplication in 2.481 seconds (JVM running for 2.801)
Started SampleWebFreeMarkerApplication in 2.543 seconds (JVM running for 2.869)
Started SampleWebFreeMarkerApplication in 2.491 seconds (JVM running for 2.817)
Started SampleWebFreeMarkerApplication in 2.532 seconds (JVM running for 2.851)
```

_1.3.x_

```
Started SampleWebFreeMarkerApplication in 2.572 seconds (JVM running for 2.901)
Started SampleWebFreeMarkerApplication in 2.521 seconds (JVM running for 2.85)
Started SampleWebFreeMarkerApplication in 2.427 seconds (JVM running for 2.749)
Started SampleWebFreeMarkerApplication in 2.472 seconds (JVM running for 2.797)
Started SampleWebFreeMarkerApplication in 2.484 seconds (JVM running for 2.809)
```

**Running manually as JAR**

```
$ for i in {0..10}; do java -jar spring-boot-samples/spring-boot-sample-web-freemarker/target/spring-boot-sample-web-freemarker*.jar | grep seconds; done
```

_1.2.x_

```
Started SampleWebFreeMarkerApplication in 3.148 seconds (JVM running for 3.572)
Started SampleWebFreeMarkerApplication in 3.318 seconds (JVM running for 3.737)
Started SampleWebFreeMarkerApplication in 3.438 seconds (JVM running for 3.855)
Started SampleWebFreeMarkerApplication in 3.276 seconds (JVM running for 3.724)
Started SampleWebFreeMarkerApplication in 3.323 seconds (JVM running for 3.741)
Started SampleWebFreeMarkerApplication in 3.268 seconds (JVM running for 3.697)
Started SampleWebFreeMarkerApplication in 3.375 seconds (JVM running for 3.788)
Started SampleWebFreeMarkerApplication in 3.266 seconds (JVM running for 3.684)
Started SampleWebFreeMarkerApplication in 3.354 seconds (JVM running for 3.775)
Started SampleWebFreeMarkerApplication in 3.314 seconds (JVM running for 3.73)
Started SampleWebFreeMarkerApplication in 3.444 seconds (JVM running for 3.871)
```

_1.3.x _

```
Started SampleWebFreeMarkerApplication in 3.094 seconds (JVM running for 3.533)
Started SampleWebFreeMarkerApplication in 3.025 seconds (JVM running for 3.446)
Started SampleWebFreeMarkerApplication in 2.965 seconds (JVM running for 3.384)
Started SampleWebFreeMarkerApplication in 3.146 seconds (JVM running for 3.719)
Started SampleWebFreeMarkerApplication in 3.069 seconds (JVM running for 3.493)
Started SampleWebFreeMarkerApplication in 2.98 seconds (JVM running for 3.395)
Started SampleWebFreeMarkerApplication in 3.057 seconds (JVM running for 3.545)
Started SampleWebFreeMarkerApplication in 3.241 seconds (JVM running for 3.666)
Started SampleWebFreeMarkerApplication in 3.263 seconds (JVM running for 3.693)
Started SampleWebFreeMarkerApplication in 3.317 seconds (JVM running for 3.752)
Started SampleWebFreeMarkerApplication in 3.107 seconds (JVM running for 3.554)
```

**Comment by jhoeller** [comment] 2015-11-05 17:09
@philwebb, rubbing my eyes... So are you saying that it is actually a little bit *faster* with 4.2.3 now?

**Comment by philwebb** [comment] 2015-11-05 17:12
I think commits c94cb1f3d1d6061e07f8b06403c4290aa7f9012e and d88210f6260b9feebba849b5163ad5d38351de7f have made some difference. The background thread idea is something I had on the back burner for a while.

**Comment by philwebb** [comment] 2015-11-05 17:13
Although seeing that @snicoll still sees slower results I'm starting to doubt my sanity a little.

**Comment by jhoeller** [comment] 2015-11-05 17:18
Stéphane feels that we're at the end of what we can achieve with the profiler though. What really matters is actual application startup times... Some of those recent optimizations matter for larger applications in particular, even if they've been motivated by minimal startup profiling sessions.

**Comment by snicoll** [comment] 2015-11-05 17:44
I am happy that someone else tried it because I was going in circles really. The results with the profiler were very weird but everything that was changed recently went in the right direction.

As far as I am concerned I am happy about the outcome for this issue, see my numbers for the same test

_1.2.x_

```
Started SampleWebFreeMarkerApplication in 2.671 seconds (JVM running for 2.993)   
Started SampleWebFreeMarkerApplication in 2.377 seconds (JVM running for 2.695)   
Started SampleWebFreeMarkerApplication in 2.462 seconds (JVM running for 2.782)   
Started SampleWebFreeMarkerApplication in 2.381 seconds (JVM running for 2.699)   
Started SampleWebFreeMarkerApplication in 2.813 seconds (JVM running for 3.144)   
Started SampleWebFreeMarkerApplication in 2.456 seconds (JVM running for 2.783)   
Started SampleWebFreeMarkerApplication in 2.464 seconds (JVM running for 2.786)   
Started SampleWebFreeMarkerApplication in 2.468 seconds (JVM running for 2.793)   
Started SampleWebFreeMarkerApplication in 2.447 seconds (JVM running for 2.77)    
Started SampleWebFreeMarkerApplication in 2.465 seconds (JVM running for 2.791)   
Started SampleWebFreeMarkerApplication in 2.47 seconds (JVM running for 2.797)    
```

_1.3.x_

```
Started SampleWebFreeMarkerApplication in 2.379 seconds (JVM running for 2.691)
Started SampleWebFreeMarkerApplication in 2.06 seconds (JVM running for 2.371) 
Started SampleWebFreeMarkerApplication in 2.08 seconds (JVM running for 2.397) 
Started SampleWebFreeMarkerApplication in 2.396 seconds (JVM running for 2.707)
Started SampleWebFreeMarkerApplication in 2.116 seconds (JVM running for 2.426)
Started SampleWebFreeMarkerApplication in 2.154 seconds (JVM running for 2.457)
Started SampleWebFreeMarkerApplication in 2.148 seconds (JVM running for 2.462)
Started SampleWebFreeMarkerApplication in 2.505 seconds (JVM running for 2.826)
Started SampleWebFreeMarkerApplication in 2.232 seconds (JVM running for 2.539)
Started SampleWebFreeMarkerApplication in 2.259 seconds (JVM running for 2.571)   
```

The last thing that I came up with was that closing the context might be slower in `1.3.x` and might explain that difference (since my profiling session is in one VM for all processes so the shutdown phase counts as well. The fact that Boot 1.3 may have a higher memory pressure could be related.

In any case, as far as the startup performance is concerned, I think we can close this one.

**Closed by snicoll** 2015-11-05 17:44 UTC
Labels: blocker

**Comment by cemo** [comment] 2015-11-05 18:36
@snicoll and others, 

Thank you so much for detailed investigation. We have really appreciated what have you done in this issue. All your efforts are priceless.
