### ISSUE TITLE
Migrate from deprecate NCSARequestLog

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#16647] opened 2019-04-24 19:48 UTC
`NCSARequestLog` has been deprecated and we should migrate to `CustomRequestLog`

**Comment by dreis2211** [comment] 2019-04-24 19:49
Isn't this a duplicate of #16416?

**Comment by snicoll** [comment] 2019-04-24 20:44
It is. Thanks Christoph!

**Closed by snicoll** 2019-04-24 20:44 UTC
Labels: type: task
