### ISSUE TITLE
Dropwizard Histogram

### ISSUE THREAD

**Issue by digaobarbosa** [spring-projects/spring-boot#4761] opened 2015-12-11 17:48 UTC
We have two servers using `SlidingWindowReservoirHistogram` from dropwizard metrics.
We are also using `RedisMetricsRepository`. But it seems since we started this configuration, our metrics do not match reality anymore. 

Do you know of any bug related to this?
If not, I can try reproduce it.

**Comment by wilkinsona** [comment] 2015-12-14 20:00
I haven't heard of any problems in this area and it'll be very hard for us to diagnose it without some more information. Can you please provide a sample project that reproduces the issue?

**Comment by spring-issuemaster** [comment] 2015-12-21 20:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2015-12-28 20:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2015-12-28 20:05 UTC

**Comment by digaobarbosa** [comment] 2016-05-07 22:45
I am sorry I didn't respond before. 
But if anyone hás the same problem. It seems that as the MetricsRepository and publisher combination I used made we read only the last value from multiple servers. 

Probably the best thing, is to us implement a sliding window reservoir using redis to store all samples.
