### ISSUE TITLE
Prometheus metrics missing after update to Spring Boot 3.0.6 for apps running on webflux stack

### ISSUE THREAD

**Issue by dietzsch** [spring-projects/spring-boot#35198] opened 2023-04-28 17:14 UTC
Hi,

we have a set of Microservices, which are using the prometheus actuator for monitoring. All of them worked fine with Spring Boot 3.0.5. After update to Spring Boot 3.0.6 all the apps running on webflux return only a subset of the metrics returned before, while all apps running on web return all the metrics as before. This must be a regression in Spring Boot 3.0.6 as switching back to 3.0.5 fixed the issue. In the logs there are no errors or warnings.

Thank you for your support!

best regards,
Alex

**Comment by wilkinsona** [comment] 2023-04-28 17:18
Are you deploying your applications to Cloud Foundry? If so, this is a duplicate of https://github.com/spring-projects/spring-boot/issues/35163.

**Comment by dietzsch** [comment] 2023-04-28 17:20
> Are you deploying your applications to Cloud Foundry? If so, this is a duplicate of #35163.

yes, we deploy to Cloud Foundry.

**Comment by wilkinsona** [comment] 2023-04-28 17:21
Thanks for the quick follow-up.

**Closed by wilkinsona** 2023-04-28 17:21 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
