### ISSUE TITLE
Support ReloadableResourceBundleMessageSource in MessageSourceAutoConfiguration

### ISSUE THREAD

**Issue by deeaitche** [spring-projects/spring-boot#31269] opened 2022-06-08 03:24 UTC
Currently ``ResourceBundleMessageSource`` is used as MessageSource in ``MessageSourceAutoConfiguration``. But in some way ``ReloadableResourceBundleMessageSource`` is more preferable. Would it be possible if the MessageSource type is configurable?

**Comment by snicoll** [comment] 2022-06-08 07:09
@deeaitche thanks for the suggestion. This is a duplicate of #15007

**Closed by snicoll** 2022-06-08 07:09 UTC
Labels: status: waiting-for-triage
