### ISSUE TITLE
Strange error when using @MockBean

### ISSUE THREAD

**Issue by jonhkr** [spring-projects/spring-boot#9359] opened 2017-05-30 19:13 UTC
Hi.

I'm trying to use `@MockBean` to create a mock in a test but strange things are happening when I use it.

I'm using it like this:
```Java
@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
class TestClass {
   @MockBean
   private TestService service;
}
```
When the test is run, some tests (**that where passing before**) fail with the exception:
```
org.springframework.dao.InvalidDataAccessApiUsageException: detached entity passed to persist: [ENTITY CLASS NAME HERE]; nested exception is org.hibernate.PersistentObjectException: detached entity passed to persist: [ENTITY CLASS NAME HERE]
```
**That error only appears when `@MockBean` is present in the test, if I remove the annotation all tests pass.**

It doesn't make any sense to me why this is happening.
I'm sorry I can't give you more details of the implementation since it is a private project. I just wanted to know if you have any clue of what is going on.

**Comment by wilkinsona** [comment] 2017-05-30 19:26
It's going to be very hard, if not impossible, to diagnose without some more information. We don't need to see the actual project, a small sample that reproduces the behaviour would be fine (and is actually better than having to wade through a larger project).

**Comment by jonhkr** [comment] 2017-05-30 20:27
Ok, I managed to get it to work but there is a catch.

I have an abstract class called `AbstractIntegrationTest` that has the annotations:

```
@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
```
I use this class in all the tests that depend on Spring (the tests classes extend this abstract class). If I use the `@MockBean` annotation in some **specific** test classes, then some tests fail, but if I put the annotation in the `AbstractIntegrationTest` class, all tests pass.

So this makes me think that the problem is related to the order the tests are run, when the test runner executes the class that has the `@MockBean` annotation it has to change the spring context, and this is messing up something and causing the error. If the `@MockBean` is in the `AbstractIntegrationTest` class it is detected right away and processed, so the context is not changed when running the tests. This is my guess on what is happening.

I'll try to compile a sample project that reproduces this and send it to you.

**Comment by spring-issuemaster** [comment] 2017-06-13 21:33
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-06-20 21:33
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-06-20 21:33 UTC
Labels: status: waiting-for-triage
