### ISSUE TITLE
Encoutering memory issues post Spring boot 2.7.1 version

### ISSUE THREAD

**Issue by loveshjain** [spring-projects/spring-boot#32071] opened 2022-08-12 02:34 UTC
After upgrading our applications to Spring boot 2.7.1 version, we have started encountering memory issues.  

**Our Observations**
 
Changes were made in 2.7.1 in the `org.springframework.boot.loader.jar` package around closing jar files. A list of nested jars were added and that is what is holding on to objects in our heap dump.

We can see 22,000 JarFile objects in the heap dump where we'd expect about 118 as that is how many nested jars there are in the application. Note that apart from the expected jar files, the other 22,000-odd are all url = jar:file:/deployments/application-web-1.0.0.jar!/BOOT-INF/lib/swagger-ui-4.11.1.jar!/

Please find below the heap dump and Dynatrace screenshot as reference

![image](https://user-images.githubusercontent.com/20214999/184274270-fdf43204-71ed-4230-bf74-7df7ef78f0f2.png)

![image](https://user-images.githubusercontent.com/20214999/184274296-dd727f89-c60b-401e-b3d6-b29910e62cc6.png)

**Note** :- No changes were made in **org.springframework.boot.loader.jar** package in 2.7.2 so I suspect the problem will still be there.

Can someone please look into this.

**Comment by wilkinsona** [comment] 2022-08-14 18:46
Thanks for the report, @loveshjain. There are some similarities with #32042 and #31853. Are you using `PropertiesLauncher` to run your app? To allow us to diagnose the problem, please provide a minimal sample that reproduces the leak.

**Comment by philwebb** [comment] 2022-08-16 01:08
@loveshjain I've pushed a fix for #31853 that removes the nested jars list. Once [build 713](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.7.x/jobs/build/builds/713) could you please try the latest SNAPSHOT and see if the memory issues persist?

**Comment by beggsj42** [comment] 2022-08-17 04:21
Hi @philwebb - I work with @loveshjain and am looking at this. Our problem is that we haven't been able to replicate this in non-prod. I'm going to see what I can do in that regard in the next couple of days.

I'm speculating that this might have to do with the JarFile objects being removed by the GC (as they are soft referenced?) if there is memory pressure, and then being reloaded later, but never getting removed from the nested jars list? I've never really looked at custom class loader code though so I'm a bit in the dark. 
Does that sound reasonable though - to maybe try to get the JVM close to the heap limit and see if that causes it? I'm just looking for things to try really.

It was fairly odd behaviour in production - it went for several days without us noticing an issue, and when we did hit the issue it wasn't in a high-load period and it seemed to self-correct. In the tenured gen picture above it looks like it started to have a GC issue about 10am, but we didn't notice until it started affecting response time badly at about 9:45pm. 

We have had similar issues on multiple services though and rolling back to 2.7.0 resolved it.

**Comment by beggsj42** [comment] 2022-08-17 04:46
I believe we're using the JarLauncher - we're just using the spring-boot-maven-plugin and we're not overriding the 'layout'.

**Comment by philwebb** [comment] 2022-08-17 18:32
See https://github.com/spring-projects/spring-boot/issues/31853#issuecomment-1218359941. We're going to revert #29356

**Comment by beggsj42** [comment] 2022-08-18 21:27
Right, thanks - I'm fairly sure that will solve our issue. I'll still try to put some effort in to replicating the problem though hopefully it'll mostly just be for the intellectual exercise now.

**Comment by snicoll** [comment] 2022-08-19 06:33
@beggsj42 upgrading to `2.7.3` contains the change that Phil mentioned if you want to double check.

**Comment by spring-projects-issues** [comment] 2022-09-10 13:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by beggsj42** [comment] 2022-09-11 19:38
Sorry for the late reply. I still haven't been able to replicate the problem in 2.7.1 in non-prod, but 2.7.3 definitely has solved the issue for us in production.

We're happy for this issue to be closed, thanks.

**Comment by snicoll** [comment] 2022-09-12 05:30
Thanks for  following up.

**Closed by snicoll** 2022-09-12 05:30 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by sm0217** [comment] 2023-11-03 09:55
Apologies for commenting on a closed ticket but we are seeing similar issues upgrading from 2.4 to 2.7.16. May I know if there was any fix provided for this and it is present in the latest 2.7.x versions

**Comment by wilkinsona** [comment] 2023-11-03 10:22
Please see above. A change was made in Spring Boot 2.7.3 that fixed the problem that was reported in this issue. That fix has not be removed and should be present in the latest 2.7.x versions.

**Comment by sushmitha-malae** [comment] 2023-12-18 04:47
Hi @sm0217 Were you able to fix the issues? we are also facing similar issues when upgraded to 2.7.16.
