### ISSUE TITLE
Switch FilteringSpringBootCondition to use Class.forName

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#19342] opened 2019-12-10 19:12 UTC
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background

In our efforts to support running Spring Boot applications on GraalVM, it [was discovered](https://github.com/oracle/graal/issues/1940#issuecomment-564126763) that `FilteringSpringBootCondition.resolve` calls `ClassLoader.loadClass()` directly and the agent is not able to intercept such calls and that makes it problematic to run this part of the code on GraalVM.

## Problem

The offending code is in `FilteringSpringBootCondition.resolve` when the `classLoader` is available:

```java
protected static Class<?> resolve(String className, ClassLoader classLoader) throws ClassNotFoundException {
	if (classLoader != null) {
		return classLoader.loadClass(className);
	}
	return Class.forName(className);
}
```

## Solution

Instead, if we used a static method on `Class` the agent could intercept it, as follows:

```java
protected static Class<?> resolve(String className, ClassLoader classLoader) throws ClassNotFoundException {
	if (classLoader != null) {
		return Class.forName(className, false, classLoader);
	}
	return Class.forName(className);
}
``` 

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by philwebb** [comment] 2019-12-10 19:12
See https://github.com/oracle/graal/issues/1940#issuecomment-564126763

**Comment by JosejeSinohui** [comment] 2019-12-12 18:44
Hi, can i make this change or is it already addressed somewhere else?

**Comment by snicoll** [comment] 2019-12-30 08:06
@JosejeSinohui thanks for asking. We've switched this one to first timers only so if you've never contributed before, feel free to claim it.

**Comment by victor-ferrer** [comment] 2019-12-30 08:32
Hello @snicoll, @philwebb,

I can take a look to it. A couple of questions:
- How urgent is this? It might take me a while to get a correct working setup.
- How should we test this? Is there a way to run the whole test suite using GraalVM instead of OpenJDK? (Which is the standard JRE, right?)

**Comment by snicoll** [comment] 2019-12-30 08:37
@victor-ferrer thanks for the interest, let's give a bit of time to @JosejeSinohui to claim it and if they don't, you're on. 

Regardless of that you can start configuring your environment and we're more than happy to help you with that. Come chat with us on [our Gitter channel](https://gitter.im/spring-projects/spring-boot) if you have questions.

There's no testing involved here, besides making sure that the project still builds after the suggested change above.

**Comment by victor-ferrer** [comment] 2019-12-30 08:44
OK, let´s wait. I am sure there are plenty of issues to work on. 
Thanks!

**Comment by protyay** [comment] 2019-12-30 09:24
Hello, @snicoll coming here from the tweet I've just seen. Is this already taken ? Thanks.

**Comment by snicoll** [comment] 2019-12-30 09:32
Hey @protyay, you're third on the list after @JosejeSinohui and @victor-ferrer.

**Comment by sumantrana** [comment] 2019-12-30 10:59
Hi, Can you please put me in queue as well. I would like to take a stab at it (if it is not resolved before my turn)

**Comment by JosejeSinohui** [comment] 2019-12-30 16:42
Hi @victor-ferrer. I can leave this to you. I am already working on another issue.

**Comment by snicoll** [comment] 2019-12-30 17:14
Thanks for the feedback @JosejeSinohui. @victor-ferrer, the issue is yours.

**Comment by victor-ferrer** [comment] 2019-12-30 17:32
I will take it then, thanks.

**Comment by snicoll** [comment] 2019-12-31 08:37
Closing in favour of PR #19490

**Closed by snicoll** 2019-12-31 08:37 UTC
Labels: status: first-timers-only, type: task
