### ISSUE TITLE
RestTemplateBuilder replaces messageConverters even when using `additionalMessageConverters`.

### ISSUE THREAD

**Issue by weltonrodrigo** [spring-projects/spring-boot#13700] opened 2018-07-04 02:21 UTC
### The Problem
`RestTemplateBuilder.additionalMessageConverters()` should *add* additional `HttpMessageConverter`s, but when `build()`ing the RestTemplate client, the builder clears the client messageConverters and replace with the list provided:

First, the method sets the `messageConverters` field:

	/**
	 * Add additional {@link HttpMessageConverter HttpMessageConverters} that should be
	 * used with the {@link RestTemplate}.
	 * @param messageConverters the converters to add
	 * @return a new builder instance
	 * @see #messageConverters(HttpMessageConverter...)
	 */
	public RestTemplateBuilder additionalMessageConverters(
			HttpMessageConverter<?>... messageConverters) {
		Assert.notNull(messageConverters, "MessageConverters must not be null");
		return additionalMessageConverters(Arrays.asList(messageConverters));
	}

Then, when building, it creates a new RestTemplate instance and procedes to configure it, setting the messageConverters (using only the converters add before):

	/**
	 * Configure the provided {@link RestTemplate} instance using this builder.
	 * @param <T> the type of rest template
	 * @param restTemplate the {@link RestTemplate} to configure
	 * @return the rest template instance
	 * @see RestTemplateBuilder#build()
	 * @see RestTemplateBuilder#build(Class)
	 */
	public <T extends RestTemplate> T configure(T restTemplate) {
		configureRequestFactory(restTemplate);
		if (!CollectionUtils.isEmpty(this.messageConverters)) {
			restTemplate.setMessageConverters(new ArrayList<>(this.messageConverters));
		}
        // ...
	}

This will cause RestTemplate to replace it's own converters with the ones provided.

	/**
	 * Set the message body converters to use.
	 * <p>These converters are used to convert from and to HTTP requests and responses.
	 */
	public void setMessageConverters(List<HttpMessageConverter<?>> messageConverters) {
		Assert.notEmpty(messageConverters, "At least one HttpMessageConverter required");
		// Take getMessageConverters() List as-is when passed in here
		if (this.messageConverters != messageConverters) {
			this.messageConverters.clear();
			this.messageConverters.addAll(messageConverters);
		}
	}

### To reproduce

    ArrayList<MediaType> myList = new ArrayList<MediaType>(1);
    myList.add(new MediaType("text", "html"));

    MappingJackson2HttpMessageConverter myConverter = new MappingJackson2HttpMessageConverter();
    myConverter.setSupportedMediaTypes(myList);

    RestTemplate restClient = restTemplateBuilder.additionalMessageConverters(myConverter).build();

    // Will have only one element.
    restClient.getMessageConverters();

    MultiValueMap<String, String> map = new LinkedMultiValueMap<String, String>();
    map.add("paramA", "A");
    map.add("paramB", "B");
    map.add("paramC", "C");

    String result = restClient.postForObject("http://www.google.com", map, String.class);

That will give you a POST with a JSON object, but a text/html Content-type, because there are no HttpMessageConverters on the RestTemplate other than the add before.

**Comment by wilkinsona** [comment] 2018-07-04 08:21
This is working as designed so it looks like we need to improve the documentation. The additional converters are additional to the builder not to any `RestTemplate` that it builds. The intention is that a builder can be created with some default converters (using the `messageConverters` methods) and then customised as needed with additional converters (using the `additionalMessageConverters` methods).

**Comment by weltonrodrigo** [comment] 2018-07-05 16:34
I added a suggestion of documentation. Please feel free to refuse it.

**Comment by philwebb** [comment] 2018-07-06 02:37
Thanks @weltonrodrigo, I'll close this one in favor of PR #13714

**Closed by philwebb** 2018-07-06 02:37 UTC
Labels: type: documentation
