### ISSUE TITLE
Binder conversion fails intermittently when called from multiple threads

### ISSUE THREAD

**Issue by Linyuzai** [spring-projects/spring-boot#27813] opened 2021-08-25 04:41 UTC
I compile a jar to provide coroutines for java, like 'kotlin-coroutines-java-support.jar'.

It works well until `org.springframework.boot.context.properties.bind.Binder` used.

I use binder like this:

```java
//custom properties
Map<String, Object> map = new LinkedHashMap<>();
map.put("demo.get", 1);
map.put("demo.list", "1,2,3");
map.put("demo.map.m1", true);
map.put("demo.map.m2", false);
map.put("demo.el", "el,${demo.get}");

StandardEnvironment env = new StandardEnvironment();
//remove default propertySources
//......
//add new
OriginTrackedMapPropertySource propertySource = new OriginTrackedMapPropertySource("newEnv", map, true);
env.getPropertySources().addFirst(propertySource);

//class to bind
@Data
public static class DemoBinderToUse {

  private int get;

  private String el;

  private List<Integer> list;

  private Map<String, Boolean> map;
}

//finally run in coroutines concurrently
Binder.get(env).bindOrCreate("demo", DemoBinderToUse.class);
```

List's value is wrong sometimes

![image](https://user-images.githubusercontent.com/18523183/130726171-cc5442a9-7c55-4361-bf94-5244dfa1113f.png)

**Comment by philwebb** [comment] 2021-08-25 15:47
I'm not familiar enough with Kotlin coroutines to be able to help from the description alone. Can you please provide a sample application that we can run and debug?

**Comment by philwebb** [comment] 2021-08-28 02:40
Thanks for the additional info. I've managed to replicate this in a pure Java application. I think the root cause is that our `TypeConverterConversionService` is using the same `SimpleTypeConverter` from multiple threads. The javadoc for that class states:

> Due to its reliance on `PropertyEditors` `SimpleTypeConverter` is *not* thread-safe. Use a separate instance for each thread.

We somehow missed that warning.

**Comment by philwebb** [comment] 2021-08-28 05:51
Fixed in 87dbda2339815f983e423b26154815d89a7fea2e

**Closed by philwebb** 2021-08-28 05:51 UTC
Labels: type: bug
