### ISSUE TITLE
Unable to start Netty (TimeoutException)

### ISSUE THREAD

**Issue by ganesshkumar** [spring-projects/spring-boot#9905] opened 2017-07-29 10:59 UTC
**Issue**: Netty is unable to start due to timeout in the latest '2.0.0.M3'.  In '2.0.0.M2' everything works fine. 

```
2017-07-29 16:19:35.028  INFO 1698 --- [           main] o.s.w.r.r.m.a.ControllerMethodResolver   : Looking for @ControllerAdvice: org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext@1d76aeea: startup date [Sat Jul 29 16:19:30 IST 2017]; root of context hierarchy
2017-07-29 16:19:36.221  INFO 1698 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-07-29 16:19:41.577  INFO 1698 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-07-29 16:19:41.595 ERROR 1698 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.boot.web.server.WebServerException: Unable to start Netty
        at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:74) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.startReactiveWebServer(ReactiveWebServerApplicationContext.java:139) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.finishRefresh(ReactiveWebServerApplicationContext.java:72) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.0.0.RC3.jar:5.0.0.RC3]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:49) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
        at <mypackage>.<myclass>.main(MyApplication.kt:10) [main/:na]
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: HttpServer couldn't be started within 3000ms
        at reactor.core.Exceptions.propagate(Exceptions.java:240) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
        at reactor.core.publisher.Mono.block(Mono.java:1280) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
        at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:55) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
        at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:45) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
        at reactor.ipc.netty.NettyConnector.start(NettyConnector.java:53) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
        at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:64) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
        ... 10 common frames omitted
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:88) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
                ... 15 common frames omitted
Caused by: java.util.concurrent.TimeoutException: HttpServer couldn't be started within 3000ms
        at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:53) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
        ... 13 common frames omitted
```

**Environment**
Kotlin: 1.1.3-2
SpringBoot: 2.0.0.M3
Java: 1.8.0_112 (build 1.8.0_112-b16)
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 3.5.1
------------------------------------------------------------

Build time:   2017-06-16 14:36:27 UTC
Revision:     d4c3bb4eac74bd0a3c70a0d213709e484193e251

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_112 (Oracle Corporation 25.112-b16)
OS:           Mac OS X 10.12.4 x86_64
```

**Steps to reproduce**
Create a project from [Spring Initializr](http://start.spring.io/) using `Spring Boot: 2.0.0 M3` with `Reactive Web`

**Comment by ganesshkumar** [comment] 2017-07-29 11:00
It is not related to https://thoeni.io/post/macos-sierra-java, as my `/ect/hosts` have the required entries for `127.0.0.0` and `::1`.

**Comment by wilkinsona** [comment] 2017-07-29 11:34
Has M2 worked successfully since you experienced this problem with M3?

**Comment by ganesshkumar** [comment] 2017-07-29 11:42
Yes, I am using M2 currently and it is running successfully.

**Comment by wilkinsona** [comment] 2017-08-01 06:41
@ganesshkumar I can't recreate this so it's either specific to your environment or there's more to it than you've described. To eliminate the latter, can you please provide a minimal sample that reproduces the problem?

**Comment by ganesshkumar** [comment] 2017-08-03 14:30
Here is the [repo](https://github.com/ganesshkumar/test-spring-boot-2.0.0.M3) I just created using [Spring Initializr](https://start.spring.io/).

I have added the complete stack track in README. Let me know if you want more details.

**Comment by wilkinsona** [comment] 2017-08-03 14:46
Thanks for the sample. It starts fine for me via both `bootRun` and `java -jar` so it would appear that the problem is in some way specific to your environment.

Can you please try running with `logging.level.root=debug` so that we can see what's going on during startup? A thread dump taken towards the end of the 5 second period while it waits for Netty to start may also be informative.

**Comment by onionf91** [comment] 2017-08-04 08:58
I have the same issue too. In both my Macbook pro and dell xps 13(arch linux).

**Comment by ganesshkumar** [comment] 2017-08-04 10:50
@wilkinsona I have updated the logs in the repo. 

[Log via gradle task](https://raw.githubusercontent.com/ganesshkumar/test-spring-boot-2.0.0.M3/master/task-debug.log) by running `./gradlew bootRun --debug`

[Log via application.properties](https://raw.githubusercontent.com/ganesshkumar/test-spring-boot-2.0.0.M3/master/app-prop-debug.log) by adding `logging.level.root=debug` in application.properties

**Comment by onionf91** [comment] 2017-08-07 03:42
I follow this [solution](https://stackoverflow.com/a/41847289) then it work now.

**Comment by wilkinsona** [comment] 2017-08-08 06:52
Reopening as @onionf91 isn't the OP and @ganesshkumar has already said that:

> It is not related to https://thoeni.io/post/macos-sierra-java, as my /ect/hosts have the required entries for 127.0.0.0 and ::1.

My suspicion is that it is related but we should wait for confirmation.

**Comment by snicoll** [comment] 2017-08-08 06:56
Apologizes, I thought the OP was reporting back 😰

**Comment by hendisantika** [comment] 2017-08-12 00:30
I got same issue. I upgrade from Spring Boot 2.0.0.BUILD.SNAPSHOT to 2.0.0.M3.

My /etc/host has already done above settings.

Is there any solution?

I use macOS Sierra i7.

Thanks

**Comment by wilkinsona** [comment] 2017-08-12 08:22
@hendisantika We don't know exactly what the problem is just yet. We still need some more information, specifically:

> How long does a call to InetAddress.getLocalHost() take on your machine? If it's quick and my suspicion is wrong, I think we'll need a thread dump during the 5 second window after the first line has been logged to make further progress.

**Comment by hendisantika** [comment] 2017-08-12 08:51
It takes 5 ms.

**Comment by ganesshkumar** [comment] 2017-08-12 09:22
Sorry for delayed update. 

After updating to macOS Sierra 10.12.6, everything is working fine as expected.

**Comment by ganesshkumar** [comment] 2017-08-12 09:25
@hendisantika, just double check you have the hostname as third field  in`/etc/hosts` file. 

```
127.0.0.1   localhost    mac.local
::1              localhost     mac.local
```

I have faced this issue around M2. I had both the entries but the missing hostname field made InetAddress.getLocalHost() to take more than 3s.

**Comment by hendisantika** [comment] 2017-08-12 09:25
My mac already used macOS Sierra 10.12.6 @ganesshkumar. But, I still got the issue.

Should I post the repo so that anyone can test it?

**Comment by snicoll** [comment] 2017-08-12 09:35
Yes please.

**Comment by mohitsinha** [comment] 2017-08-15 11:49
I am facing the same issue for 2.0.0.M3 while it works fine for 2.0.0.M2

**Comment by snicoll** [comment] 2017-08-15 11:51
we are still waiting for a sample. Can you please share one?

**Comment by spring-issuemaster** [comment] 2017-08-24 12:29
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by hendisantika** [comment] 2017-08-24 23:12
@spring-issuemaster and the others member like @mohitsinha or @ganesshkumar  can try my repo to see if it works on your machine. 

BTW, I already follow the /etc/host but it still got error.

[Here's my repo](https://github.com/hendisantika/spring5-reactive.git) 

And here's my errors : 
```
org.springframework.boot.web.server.WebServerException: Unable to start Netty
	at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:74) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.startReactiveWebServer(ReactiveWebServerApplicationContext.java:139) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.finishRefresh(ReactiveWebServerApplicationContext.java:72) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.0.0.RC3.jar:5.0.0.RC3]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:49) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M3.jar:2.0.0.M3]
	at org.spring5.Spring5ReactiveApplication.main(Spring5ReactiveApplication.java:12) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:496) [spring-boot-maven-plugin-2.0.0.M3.jar:2.0.0.M3]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: HttpServer couldn't be started within 3000ms
	at reactor.core.Exceptions.propagate(Exceptions.java:240) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
	at reactor.core.publisher.Mono.block(Mono.java:1280) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
	at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:55) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
	at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:45) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
	at reactor.ipc.netty.NettyConnector.start(NettyConnector.java:53) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
	at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:64) ~[spring-boot-2.0.0.M3.jar:2.0.0.M3]
	... 16 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:88) ~[reactor-core-3.1.0.M3.jar:3.1.0.M3]
		... 21 common frames omitted
Caused by: java.util.concurrent.TimeoutException: HttpServer couldn't be started within 3000ms
	at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:53) ~[reactor-netty-0.7.0.M1.jar:0.7.0.M1]
	... 19 common frames omitted

2017-08-25 06:08:07.452  INFO 63567 --- [           main] .r.c.ReactiveWebServerApplicationContext : Closing org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext@1c13cb3b: startup date [Fri Aug 25 06:08:01 WIB 2017]; root of context hierarchy
2017-08-25 06:08:07.454  INFO 63567 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:496)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start Netty
	at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:74)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.startReactiveWebServer(ReactiveWebServerApplicationContext.java:139)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.finishRefresh(ReactiveWebServerApplicationContext.java:72)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:49)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233)
	at org.spring5.Spring5ReactiveApplication.main(Spring5ReactiveApplication.java:12)
	... 6 more
Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: HttpServer couldn't be started within 3000ms
	at reactor.core.Exceptions.propagate(Exceptions.java:240)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1280)
	at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:55)
	at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:45)
	at reactor.ipc.netty.NettyConnector.start(NettyConnector.java:53)
	at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:64)
	... 16 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:88)
		... 21 more
Caused by: java.util.concurrent.TimeoutException: HttpServer couldn't be started within 3000ms
	at reactor.ipc.netty.tcp.BlockingNettyContext.<init>(BlockingNettyContext.java:53)
	... 19 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.951 s
[INFO] Finished at: 2017-08-25T06:08:07+07:00
[INFO] Final Memory: 47M/507M

```

**Comment by xBATx** [comment] 2017-08-25 05:50
Hi @hendisantika,
I have no problem to start you repo on my mac so probably, you have some issues with your configuration. To ensure that it's not problem of inet address, you can use [inetTester](https://github.com/thoeni/inetTester) which show you how much time did take hostname resolution. Are you sure that your etc hosts file looks as it should? Does **yourHostname** in `/etc/host` match your mac hostname as described in [document mentioned in previous messages](https://thoeni.io/post/macos-sierra-java/)

> 127.0.0.1 &nbsp;  localhost **yourHostname**.local
> ::1 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    localhost **yourHostname**.local

**Comment by hendisantika** [comment] 2017-08-25 06:16
Hi @xBATx, 
My `/etc/host` looks like this : 
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
#127.0.0.1 Hendis-MacBook-Pro.local # added by Apache Friends XAMPP
127.0.0.1   dev-server localhost.localdomain localhost
127.0.0.1 Hendis-MacBook-Pro.local # added by Apache Friends XAMPP
```

Is it not correct?

**Comment by hendisantika** [comment] 2017-08-25 06:46
Sorry guys,
It looks like my `/etc/hosts` file not properly setup.

Now, it runs well.

You can close this issue now, @spring-issuemaster.

Thanks everybody.

**Closed** 2017-08-25 08:43 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by zhaoyin** [comment] 2017-09-11 14:56
but why?I am facing the same issue for 2.0.0.M3 while it works fine for 2.0.0.M2.
``/etc/hosts``should be reset in 2.0.0.M3,and the same ``/etc/hosts``should not be reset in 2.0.0.M2?
