### ISSUE TITLE
Rest request handlers initialized after 1st request

### ISSUE THREAD

**Issue by imprashast** [spring-projects/spring-boot#13882] opened 2018-07-25 10:01 UTC
So we recently migrated to Spring 5 and Spring Boot 2 and here is the issue in one of our application. After the app is started, the first request takes more than 10 seconds to be served. All other applications work normal as expected. Enabled debug and trace logs for this application and this is how it looks like:

```
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Bound request context to thread: org.apache.catalina.connector.RequestFacade@64cc17ff []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Creating shared instance of singleton bean 'mvcHandlerMappingIntrospector' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Creating instance of bean 'mvcHandlerMappingIntrospector' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Eagerly caching bean 'mvcHandlerMappingIntrospector' to allow for resolving potential circular references []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Getting BeanInfo for class [org.springframework.web.servlet.handler.HandlerMappingIntrospector] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Caching PropertyDescriptors for class [org.springframework.web.servlet.handler.HandlerMappingIntrospector] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Found bean property 'applicationContext' of type [org.springframework.context.ApplicationContext] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Found bean property 'class' of type [java.lang.Class] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Found bean property 'handlerMappings' of type [java.util.List] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Invoking afterPropertiesSet() on bean with name 'mvcHandlerMappingIntrospector' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'faviconHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'requestMappingHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'viewControllerHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'beanNameHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'resourceHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'defaultServletHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'welcomePageHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'webEndpointServletHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'controllerEndpointHandlerMapping' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionAdvisor' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Finished creating instance of bean 'mvcHandlerMappingIntrospector' []
[TRACE] 09:43:51 [http-nio-4004-exec-1] No handler mapping found for [/booking/list/1] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Looking up handler method for path /booking/list/1 []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Did not find handler method for [/booking/list/1] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Looking up handler method for path /booking/list/1 []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Did not find handler method for [/booking/list/1] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Looking up handler method for path /booking/list/1 []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Found 1 matching mapping(s) for [/booking/list/1] : [{[/booking/list/{id}],methods=[GET],produces=[application/json]}] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning handler method [public java.util.Map<java.lang.String, java.lang.Object> no.finn.travel.fhh.api.booking.BookingController.list(java.lang.String)] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'bookingController' []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Bound request context to thread: org.apache.catalina.connector.RequestFacade@64cc17ff []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] DispatcherServlet with name 'dispatcherServlet' processing GET request for [/booking/list/1] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing handler map [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping@f60c6ca] in DispatcherServlet with name 'dispatcherServlet' []
[TRACE] 09:43:51 [http-nio-4004-exec-1] No handler mapping found for [/booking/list/1] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing handler map [org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping@7d9f19e1] in DispatcherServlet with name 'dispatcherServlet' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Looking up handler method for path /booking/list/1 []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Did not find handler method for [/booking/list/1] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing handler map [org.springframework.boot.actuate.endpoint.web.servlet.ControllerEndpointHandlerMapping@4ab520f5] in DispatcherServlet with name 'dispatcherServlet' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Looking up handler method for path /booking/list/1 []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Did not find handler method for [/booking/list/1] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing handler map [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping@1a012107] in DispatcherServlet with name 'dispatcherServlet' []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Looking up handler method for path /booking/list/1 []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Found 1 matching mapping(s) for [/booking/list/1] : [{[/booking/list/{Id}],methods=[GET],produces=[application/json]}] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning handler method [public java.util.Map<java.lang.String, java.lang.Object> package.Controller.list(java.lang.String)] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning cached instance of singleton bean 'bookingController' []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing handler adapter [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter@13def21b] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Last-Modified value for [/booking/list/1] is: -1 []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing if argument resolver [org.springframework.web.method.annotation.RequestParamMethodArgumentResolver@1a9601ca] supports [class java.lang.String] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing if argument resolver [org.springframework.web.method.annotation.RequestParamMapMethodArgumentResolver@6cacfa28] supports [class java.lang.String] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Testing if argument resolver [org.springframework.web.servlet.mvc.method.annotation.PathVariableMethodArgumentResolver@36db5e57] supports [class java.lang.String] []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Invoking 'package.Controller.list' with arguments [100351641] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Executing prepared SQL query []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Executing prepared SQL statement [SELECT * FROM table WHERE id = ?] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Fetching JDBC Connection from DataSource []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Setting SQL statement parameter value: column index 1, parameter value [100351641], value class [java.lang.String], SQL type unknown []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning JDBC Connection to DataSource []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Executing prepared SQL query []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Executing prepared SQL statement [SELECT * FROM table WHERE id = ? AND deleted IS NULL ORDER BY start_date ASC] []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Fetching JDBC Connection from DataSource []
[TRACE] 09:43:51 [http-nio-4004-exec-1] Setting SQL statement parameter value: column index 1, parameter value [100351641], value class [java.lang.String], SQL type unknown []
[DEBUG] 09:43:51 [http-nio-4004-exec-1] Returning JDBC Connection to DataSource []
[TRACE] 09:43:52 [http-nio-4004-exec-1] Method [no.finn.travel.fhh.api.booking.BookingController.list] returned [{json data] []
[DEBUG] 09:43:52 [http-nio-4004-exec-1] Written [{ json data}] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@6b2fdffc] []
[DEBUG] 09:43:52 [http-nio-4004-exec-1] Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling []
[TRACE] 09:43:52 [http-nio-4004-exec-1] Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@64cc17ff []
[DEBUG] 09:43:52 [http-nio-4004-exec-1] Successfully completed request []
[TRACE] 09:43:52 [http-nio-4004-exec-1] Publishing event in org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@42b02722: ServletRequestHandledEvent: url=[/booking/list/1]; client=[0:0:0:0:0:0:0:1]; method=[GET]; servlet=[dispatcherServlet]; session=[null]; user=[null]; time=[334ms]; status=[OK] []
[DEBUG] 09:43:52 [http-nio-4004-exec-1] Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@64cc17ff []
```

So from these logs I understand that `mvcHandlerMappingIntrospector` is initialised after the first http call was made to the application which explains the slow response time. But the question is why this is initialised after the request goes in and not at start? Also this happens for each endpoint inside this application. So the first request for all endpoints take longer to respond. Any help would be much appreciated 😄

**Comment by philwebb** [comment] 2018-07-25 12:04
It's very hard to say what's happening from the log file alone what's happening. Are you able to share an application the reproduce the problem so that we can run it locally?

**Comment by spring-issuemaster** [comment] 2018-08-01 12:08
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-08-08 12:08
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-08-08 12:08 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
