### ISSUE TITLE
Migration from 1.5.8 to 2.1.4. Docker over 100% CPU consumption

### ISSUE THREAD

**Issue by smuryginim** [spring-projects/spring-boot#16958] opened 2019-05-24 10:03 UTC
Hello.
Maybe related to https://github.com/spring-projects/spring-boot/issues/16057
We migrated our applications from from 1.5.8 to 2.1.4 spring boot version, after migration we face over CPU consumption during approximately after 1 hour after start. There was no such problem on previous spring boot version.

We launch our spring boot application in docker container on AWS Fargate service, so once the CPU consumption is reached more then 100% the container is stopped Docker OOM-killer with error 
`Reason: OutOfMemoryError: Container killed due to memory usage`

Docker file is used:
`FROM openjdk:8-jre
ADD target/service-distribution/our-spring-boot-application.jar /usr/share/jvmservice/service.jar
ENTRYPOINT exec /usr/bin/java $JAVA_OPTS -jar /usr/share/jvmservice/service.jar
`
Next java options are used
`JAVA_OPTS=-XshowSettings:vm -XX:+PrintGCDetails -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`

Docker container is launched with parameters RAM hard memory limit = 500 (-m=500)
The process of build and deploy of docker image was unchanged.

Some additional info:
Inside docker in logs:
`Max. Heap Size (Estimated): 121.81M`
GC Logs looks fine
`[GC (Allocation Failure) [DefNew: 31381K->269K(34880K), 0.0050619 secs] 97920K->66809K(112208K), 0.0051101 secs] [Times: user=0.00 sys=0.00, real=0.00 secs]`

There is no additional logs before over 100% CPU consumption.
Also there a very few workload on application when the over 100%CPU consumption happens.
Appreciate you help!

**Comment by wilkinsona** [comment] 2019-05-24 11:01
Thanks for the report. Unfortunately, there's insufficient information for us to be able to help you.

The connection between 100% CPU and the container being killed due to memory usage is not clear to me. Perhaps your application's memory usage is higher when using Spring Boot 2.1.4 and, as a result, the JVM has exceeded the container's memory limit. The 100% CPU could be related to memory usage if the GC is thrashing, however you've said that the GC logs look fine.

In addition to a new version of Spring Boot, the upgrade from 1.5.8 to 2.1.4 will also have picked up a new version of Spring Framework and perhaps of other components too. Any of those could require more memory or be responsible for the high CPU utilisation. If you have done some analysis and identified that the problem is with Spring Boot itself rather than one of the other components with which it integrates, can you please share that analysis.

Failing that, if you would like us to spend some time trying to help you, you will need to spend some time providing some more information. A minimal sample that reproduces the behaviour you have described would be ideal. Failing that, some additional analysis of your application would be useful, either with a profiler or using some of the JVM's built-in diagnostic tools.

**Comment by smuryginim** [comment] 2019-05-27 13:44
Thanks for quick reply, I thought there is some "known issue" which can help to resolve the situation.
We will continue to investigate.

**Comment by spring-issuemaster** [comment] 2019-06-03 14:08
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-10 14:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-10 14:07 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by smuryginim** [comment] 2019-06-20 11:35
For those how will have the same problem. The was the bug in JVM. It was fixed in the issue
https://bugs.openjdk.java.net/browse/JDK-8146115
The full detailed description is in
https://stackoverflow.com/questions/56446891/docker-on-aws-jvm-cpu-limit
