### ISSUE TITLE
Endpoints for liveness and readiness are changed in Spring Boot 2.3.3

### ISSUE THREAD

**Issue by Davio** [spring-projects/spring-boot#23035] opened 2020-08-21 08:13 UTC
Recently, there have been a lot of issues with the liveness and readiness probes in Spring Boot, see for instance https://github.com/spring-projects/spring-boot/issues/22562

After I switched from 2.3.1 to 2.3.2, I had to include the groups explicitly in my application.yml, like so:
```
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      group:
        liveness:
          include: livenessStateProbeIndicator
        readiness:
          include: readinessStateProbeIndicator
```
This would make the liveness and readiness probes show up in /actuator/health and make them available under /actuator/health/liveness and /actuator/health/readiness respectively.

With version 2.3.3, I can remove these explicit groups and configure it like so:
```
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
```

Now, if you look at /actuator/health, you see the groups liveness and readiness listed. So far, so good.

But here's the kicker, the URLs /actuator/health/liveness and /actuator/health/readiness don't work and return a 404!
After stepping through the actuator code in my debugger, I found that under the hood, these groups are referenced as 'livenessState' and 'readinessState' respectively.

So I tried the URLs /actuator/health/livenessState and /actuator/health/readinessState and they both worked!

I don't know if this is a misunderstanding on my part, or whether the groups listed in health need to be renamed or the endpoints need to be made available under the old names again.

**Comment by snicoll** [comment] 2020-08-21 08:21
> But here's the kicker, the URLs /actuator/health/liveness and /actuator/health/readiness don't work and return a 404!

What you've done in your configuration above is to enable the individual health indicators but that's not going to enable the groups. You should remove the workaround for the issue that got fixed in `2.3.3` now that you've upgraded to that. The only thing to get those groups to show up is `management.endpoint.health.probes.enabled`, [as documented in the reference guide](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-kubernetes-probes). 

If is currently only documented in the Kubernetes section and I wonder if we shouldn't change that and make it a bit more explicit outside of that context.

**Comment by Davio** [comment] 2020-08-21 08:23
I had added that to my application.yml, but skipped over it in copy-pasting it to my post in this issue.

But the issue remains the same.

**Comment by snicoll** [comment] 2020-08-21 08:35
> But that is simply not true as they are exposed as "/actuator/health/livenessState" and "/actuator/health/readinessState"

I can't reproduce what you're describing. I can however reproduce exactly what is described in the doc. To make some progress, please share a small sample that we can run ourselves, either attached as a zip to this issue or in the form of a GitHub repo.

**Comment by Davio** [comment] 2020-08-21 08:55
Haven't been able to reproduce it with a simple demo yet, but in my simplified demo, both the endpoints /liveness and /livenessState are working and return the same result.

In my application, it seems that something is dropping / blocking the /liveness endpoint and only /livenessState still works.

**Comment by bclozel** [comment] 2020-08-25 10:29
I've carefully read this thread and it seems that #22562 created a lot of confusion and frustration, I'm really sorry about that. I'm not aware of other issues on that matter.

This issue seems to really be about the pain of applying the workaround and removing it afterwards. All the behavior described here (including the 404 when a configured group has no existing indicator) has been discussed already in #22562. 

I've [updated the release notes to underline that issue](https://github.com/spring-projects/spring-boot/releases/tag/v2.3.3.RELEASE). I don't think we should update other types of documentation as it would be even more confusing for developers.

@Davio I'd really like to know if removing the workaround fixed this problem for you. Are there remaining issues with the probes?

**Comment by YatishKumar** [comment] 2020-08-25 14:04
I have the same issue, in version 2.3.1. RELEASE I was able to access /actuator/health/liveness and /actuator/health/readiness but after changing to 2.3.3. RELEASE I changed my application.yml file as below 

`management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true`

/actuator/health i receive below JSON response 
`{
  "status": "UP",
  "components": {
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": *******,
        "free": *******,
        "threshold": ********,
        "exists": true
      }
    },
    "livenessStateProbeIndicator": {
      "status": "UP"
    },
    "ping": {
      "status": "UP"
    },
    "readinessStateProbeIndicator": {
      "status": "UP"
    }
  },
  "groups": Array[2][
    "liveness",
    "readiness"
  ]
}`

but when I request the URLs /actuator/health/liveness and /actuator/health/readiness don't work and return a 404!
I even tried "/actuator/health/livenessState" and "/actuator/health/readinessState" but i get 404!

**Comment by Davio** [comment] 2020-08-25 14:07
Removing the configuration which we needed to add in 2.3.2 fixed my issue.

I just found it weird that /livenessState worked in all cases with all
configurations and /liveness only worked after removing the 2.3.2
configuration.

I still don't understand why that happens exactly. I would have expected
that the probes would either work under /liveness or not at all. That they
can appear under /livenessState instead, surprised me

Op di 25 aug. 2020 12:29 schreef Brian Clozel <notifications@github.com>:

**Comment by snicoll** [comment] 2020-08-25 14:44
> I just found it weird that /livenessState worked in all cases with all
configurations and /liveness only worked after removing the 2.3.2
configuration.

Rather than letting those groups have their default configuration, that explicit override was requesting the inclusion of `livenessStateProbeIndicator`. Such a bean doesn't exist in `2.3.3`. The group is empty and therefore 404 when you try to access it.

**Comment by bclozel** [comment] 2020-08-25 14:49
@YatishKumar the behavior you're describing is consistent with #22562, so you're probably running Spring Boot 2.3.2.RELEASE. Could you ensure that you're running 2.3.3 as mentioned in your comment?

**Comment by bclozel** [comment] 2020-08-25 14:52
@Davio It seems you're confused by the difference between "health indicators" and "health groups". We've tried to improve [the documentation on Kubernetes Probes](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-kubernetes-probes) in the latest release. Feel free to suggest improvements if you think this is not clear.

I guess the Kubernetes Probes make the Health Groups feature front and center, whereas developers might have not noticed it previously.

**Comment by Davio** [comment] 2020-08-25 16:51
> > I just found it weird that /livenessState worked in all cases with all
> > configurations and /liveness only worked after removing the 2.3.2
> > configuration.
> 
> Rather than letting those groups have their default configuration, that explicit override was requesting the inclusion of `livenessStateProbeIndicator`. Such a bean doesn't exist in `2.3.3`. The group is empty and therefore 404 when you try to access it. Same for readiness.
> 
> That being said, @bclozel was asking you in context of
> 
> > there have been a lot of issues with the liveness and readiness probes in Spring Boot

I think I understand now.

The group include just replaces the regular thing with a non existing bean so by accessing that group you get the 404.
But /livenessState is a thing which always exists even if it doesn't belong to the /liveness group.

My minimal example to get the /liveness URL working without a Kubernetes environment is as follows:

```
management:
  endpoint:
    health:
      probes:
        enabled: true
```

**Comment by bclozel** [comment] 2020-08-25 17:08
Alright I'm closing this issue for now since the docs and the release notes are now in order.
Thanks!

**Closed by bclozel** 2020-08-25 17:08 UTC
Labels: status: feedback-provided, status: waiting-for-triage
