### ISSUE TITLE
What is the bug JettyEmbeddedWebAppContext about springboot?

### ISSUE THREAD

**Issue by friends110110** [spring-projects/spring-boot#13726] opened 2018-07-07 14:25 UTC
When I use the command java -jar mypro-0.0.1-SNAPSHOT.jar --logging.level.root=TRACE ,the springboot failed ,but some computer could works, the springboot version is 2.0.0.RELEASE,

```
      <group>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
          <exclusions>
              <exclusion>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-tomcat</artifactId>
              </exclusion>
.....

	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
		</dependency>
```

the log as followers:

```

2018-07-07 18:02:27.487 DEBUG 21534 --- [           main] o.e.j.u.DecoratedObjectFactory           : Creating Instance: class org.eclipse.jetty.websocket.jsr356.encoders.LongEncoder
2018-07-07 18:02:27.487 DEBUG 21534 --- [           main] o.e.j.u.DecoratedObjectFactory           : Creating Instance: class org.eclipse.jetty.websocket.jsr356.encoders.ShortEncoder
2018-07-07 18:02:27.487 DEBUG 21534 --- [           main] o.e.j.u.DecoratedObjectFactory           : Creating Instance: class org.eclipse.jetty.websocket.jsr356.encoders.ByteBufferEncoder
2018-07-07 18:02:27.487 DEBUG 21534 --- [           main] o.e.j.u.DecoratedObjectFactory           : Creating Instance: class org.eclipse.jetty.websocket.jsr356.encoders.ByteArrayEncoder
2018-07-07 18:02:27.487 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : starting org.springframework.boot.web.embedded.jetty.JettyEmbeddedErrorHandler@7d0b7e3c
2018-07-07 18:02:27.488  INFO 21534 --- [           main] o.e.j.s.h.ContextHandler                 : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@4310d43{/,[file:///tmp/jetty-docbase.8016560841686360205.13000/],AVAILABLE}
2018-07-07 18:02:27.488 DEBUG 21534 --- [           main] o.e.j.w.WebAppContext                    : postConfigure o.s.b.w.e.j.JettyEmbeddedWebAppContext@4310d43{/,[file:///tmp/jetty-docbase.8016560841686360205.13000/],AVAILABLE} with org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration@5824a83d
2018-07-07 18:02:27.488 DEBUG 21534 --- [           main] o.e.j.w.WebAppContext                    : postConfigure o.s.b.w.e.j.JettyEmbeddedWebAppContext@4310d43{/,[file:///tmp/jetty-docbase.8016560841686360205.13000/],AVAILABLE} with org.springframework.boot.autoconfigure.websocket.servlet.JettyWebSocketServletWebServerCustomizer$1@537f60bf
2018-07-07 18:02:27.488 DEBUG 21534 --- [           main] o.e.j.w.WebAppContext                    : postConfigure o.s.b.w.e.j.JettyEmbeddedWebAppContext@4310d43{/,[file:///tmp/jetty-docbase.8016560841686360205.13000/],AVAILABLE} with org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory$1@5677323c
2018-07-07 18:02:27.488 DEBUG 21534 --- [           main] o.e.j.w.WebAppContext                    : postConfigure o.s.b.w.e.j.JettyEmbeddedWebAppContext@4310d43{/,[file:///tmp/jetty-docbase.8016560841686360205.13000/],AVAILABLE} with org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory$2@18df8434
2018-07-07 18:02:27.488 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : starting org.eclipse.jetty.server.handler.ErrorHandler@a38c7fe
2018-07-07 18:02:27.489  INFO 21534 --- [           main] o.e.j.s.Server                           : Started @4487ms
2018-07-07 18:02:27.512 DEBUG 21534 --- [           main] o.e.j.s.Server                           : doStop org.eclipse.jetty.server.Server@2dc54ad4[9.4.8.v20171121]
2018-07-07 18:02:27.513 DEBUG 21534 --- [           main] o.e.j.s.Server                           : Graceful shutdown org.eclipse.jetty.server.Server@2dc54ad4[9.4.8.v20171121] by 
2018-07-07 18:02:27.514 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : stopping org.eclipse.jetty.server.Server@2dc54ad4[9.4.8.v20171121]
2018-07-07 18:02:27.514  INFO 21534 --- [           main] o.e.j.s.session                          : Stopped scavenging
2018-07-07 18:02:27.514 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : stopping org.eclipse.jetty.server.handler.ErrorHandler@a38c7fe
2018-07-07 18:02:27.514 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : stopping o.s.b.w.e.j.JettyEmbeddedWebAppContext@4310d43{/,[file:///tmp/jetty-docbase.8016560841686360205.13000/],UNAVAILABLE}
2018-07-07 18:02:27.514 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : stopping org.springframework.boot.web.embedded.jetty.JettyEmbeddedErrorHandler@7d0b7e3c
2018-07-07 18:02:27.515 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : stopping org.eclipse.jetty.server.session.SessionHandler1420232606==dftMaxIdleSec=1800
2018-07-07 18:02:27.515 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : stopping org.eclipse.jetty.security.ConstraintSecurityHandler@26e356f0
2018-07-07 18:02:27.515 DEBUG 21534 --- [           main] o.e.j.s.h.AbstractHandler                : stopping org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler@4b8ee4de
2018-07-07 18:02:27.517  INFO 21534 --- [           main] o.e.j.s.h.ContextHandler                 : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@4310d43{/,[file:///tmp/jetty-docbase.8016560841686360205.13000/],UNAVAILABLE}

```

**Comment by philwebb** [comment] 2018-07-07 20:56
I'm not sure I understand the bug report I'm afraid. Are you seeing an exception? Is that the full log output.

> springboot failed ,but some computer could works

Do you mean the failure only occurs on some computers? If so what's different about them?

Perhaps you could provide a small sample application along with the steps needed to reproduce the issue.

**Comment by friends110110** [comment] 2018-07-08 01:10
It is the complete log, and the springboot stoped. And no other exceptions. Yeah my macbook woks , while linux debian failed. Yesterday I changed the springboot verstion to 2.0.2.RELEASE. happily it works.

**Comment by friends110110** [comment] 2018-07-08 01:18
This is the screenshot:
![11791531012534_ pic_hd](https://user-images.githubusercontent.com/3381671/42415830-cd6596c6-828f-11e8-9a30-3c02eb50ca0a.jpg)

**Comment by philwebb** [comment] 2018-07-08 11:33
Since the upgrade works I'll close this issue. If you find the same problem happening with 2.0.2, please provide a small sample that we can run.

**Closed by philwebb** 2018-07-08 11:33 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by friends110110** [comment] 2018-07-08 14:39
From the log, could you give some suggestions?

**Comment by philwebb** [comment] 2018-07-08 15:00
@friends110110 There's not much to go on. The logs seem to suggest that jetty is shutting down as soon as it starts, but I don't see an exception. It's almost like someone is calling `close()` on the `ApplicationContext`.

I thought you said the upgrade to 2.0.2 had fixed the error? Is that not the case? If you're still having problems we're really going to need a sample application so we can see what's going on.
