### ISSUE TITLE
Probably bug of 2.0 version

### ISSUE THREAD

**Issue by BlueFlakes** [spring-projects/spring-boot#12329] opened 2018-03-03 11:34 UTC
Exception appear after I create project and just run It. Switching to previous version of spring boot fix the problem. App is running well, but this damn exception make me feels that something is wrong under the hood.

Used:
- Spring boot jpa
- PostgreSQL

![zrzut ekranu z 2018-03-03 12-19-54](https://user-images.githubusercontent.com/27349374/36933744-cabdece4-1ede-11e8-962a-f9ce2d3d9cf6.png)

example:
https://github.com/BlueFlakes/spring-boot-bug

**Comment by wilkinsona** [comment] 2018-03-03 11:39
Duplicate of #12007.

**Closed by wilkinsona** 2018-03-03 11:39 UTC
Labels: status: waiting-for-triage

**Comment by brunokrebs** [comment] 2018-03-06 12:50
Hey there, @BlueFlakes. [Take a look at this reference if you want to get rid of this error](http://vkuzel.blogspot.com.br/2016/03/spring-boot-jpa-hibernate-atomikos.html).
