### ISSUE TITLE
2.0.0.M7 “spring-boot-starter-actuator”  caused OOM

### ISSUE THREAD

**Issue by chenjinkai** [spring-projects/spring-boot#11338] opened 2017-12-13 09:46 UTC
maybe this jar will caused the OOM problem

<dependency>
    <groupId>org.latencyutils</groupId>
    <artifactId>LatencyUtils</artifactId>
    <version>2.0.3</version>
</dependency>

**Comment by chenjinkai** [comment] 2017-12-13 09:50
after my application runned 24 hours, it will be shown.

**Comment by chenjinkai** [comment] 2017-12-13 09:57
dump the memory, amost all objects is instances of org/LatencyUtils/LatencyStats$PauseTracker .

**Comment by bclozel** [comment] 2017-12-13 10:07
Did you report that issue to https://github.com/LatencyUtils/LatencyUtils ?

**Comment by philwebb** [comment] 2017-12-13 16:06
Possibly related to #11333

**Comment by jkschneider** [comment] 2017-12-13 16:06
> Possibly related to #11333

Only vaguely in that they are related to the same mechanism.

**Comment by jkschneider** [comment] 2017-12-13 20:06
@chenjinkai Are you super-positive that this is running on Boot 2 M7 and that you have a version of micrometer >= 1.0.0-rc.4 on your runtime classpath?

We had a memory leak in 1.0.0-rc.3 (Boot 2 M6) that was fixed in rc4. It's not impossible that there is still a leak, but I'm having a difficult time reproducing it.

**Comment by jkschneider** [comment] 2017-12-14 02:13
One idea: perhaps you have a custom metric that is running up the cardinality on a particular tag? In effect, you create a separate `Timer` for every unique combination of name and tags. Since there are by default 5 histograms kept in a ring buffer for every timer with 1 `LatencyStats` and therefore 1 `PauseDetector` per histogram, in such a scenario it might appear that `PauseDetector` is the dominator. If you have 1/5 as many `Timer` instances as `PauseDetector`'s when the OOM occurs, we can be confident this is a tag cardinality problem and not a general leak in `Timer`.

**Comment by mweirauch** [comment] 2017-12-14 08:26
Here's some plotting of a test app running with micrometer-core:1.0.0-rc.4 (~4 weeks) and rc.5 (~11 hours). No problems observable. Note, this is with a steady amount of meters.

![evam-micrometer_1 0 0-rc 4-sb_1 5 8-4w](https://user-images.githubusercontent.com/1134031/33981321-a4e454f6-e0ac-11e7-957d-2749db470ca0.png)

![evam-micrometer_1 0 0-rc 5-sb_1 5 9-10h](https://user-images.githubusercontent.com/1134031/33981328-ac67dcfc-e0ac-11e7-96d2-1da81208ea04.png)

Now - as Jon said - produce Timers on a steady basis with changing tag values, actually making them distinct metrics on each construction one can quickly get to OOMs. Testapp with -Xmx64m with Timer created every second with a distinct tag. Does lead to OOM within minutes.
Observed instance count:

![micrometer-latencyutils-01](https://user-images.githubusercontent.com/1134031/33982286-433fd532-e0b0-11e7-97d0-5d2f7ba01577.png)

![micrometer-latencyutils-02](https://user-images.githubusercontent.com/1134031/33982305-50bf0a84-e0b0-11e7-9cc2-21c455f80c5f.png)

![micrometer-latencyutils-03](https://user-images.githubusercontent.com/1134031/33982311-58a0dd0e-e0b0-11e7-9dfc-6985399c9ba9.png)

I'd second @jkschneider wrt tag cardinality "problem" on user side.

**Comment by bclozel** [comment] 2017-12-14 14:56
Thanks @mweirauch !

@chenjinka, let us know if you can reproduce this consistently with a recent version and/or if it's actually about creating multiple Timers for tags/name combinations.

**Comment by spring-issuemaster** [comment] 2017-12-21 14:56
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-12-28 14:56
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by erlioniel** [comment] 2018-01-15 14:35
Looks like we encountered the same issue, when migrated our application from M5 to M7. It is stable reproduces twice per day, so I can try to provide more data, but I'm not sure that we will be able to reproduce it in more managed environment.

Anyway I think the issue itself should be reopened and somehow solved.

![leak_suspect](https://user-images.githubusercontent.com/1926766/34947022-88b0d65a-fa11-11e7-9eba-cf569f2b6405.PNG)

**Comment by erlioniel** [comment] 2018-01-15 14:54
Some additional information. We have two services on M7 with the same load. The interesting that the second service is OK, while the first one is stable leaking.

The main difference is that the first service uses RestTemplate to call the second service.

**Comment by snicoll** [comment] 2018-01-15 14:57
@erlioniel that's interesting. Could you please give it a try with `2.0.0.BUILD-SNAPSHOT`? We've upgraded to micrometer 1.0.0-rc.7 in the meantime with specific changes around `RestTemplate`.

**Comment by jkschneider** [comment] 2018-01-15 15:15
@erlioniel Also, can you verify the cardinality of all meters you have in your app? A runaway tag value on a timer will cause an OOM eventually.

**Comment by erlioniel** [comment] 2018-01-15 15:37
@snicoll okay, sounds a bit risky but we will try tomorrow.
@jkschneider we are not using any specific meters in our application and I don't see any suspicious objects in the service heap. But maybe you can describe what I can check to be sure?

![latency](https://user-images.githubusercontent.com/1926766/34950020-8bbafe08-fa1a-11e7-8f88-db6c26ccd8ac.PNG)

**Comment by jkschneider** [comment] 2018-01-15 16:30
If you have 5,850 `LatencyStats` objects while accepting the defaults elsewhere, you have 1,170 distinct timers living in the app. Assuming this is somehow caused by `RestTemplate`, let's inspect the tags of that metric:

`http://YOURSERVICE/actuator/metrics/http.client.requests`

You'll have to specifically enable that actuator endpoint in Boot 2.

**Comment by jkschneider** [comment] 2018-01-15 16:35
@snicoll We current have a `MeterFilter#maximumAllowableMetrics(int)` concept for an application-wide max. But it would be trivial to add an additional `MeterFilter#maximumAllowableMetrics(String, int)` to limit tag explosion on a given metric name. And we could add some default cap in `RestTemplateMetricsConfiguration` to prevent instrumentation from causing memory problems when the `RestTemplate` interface is misused.

**Comment by snicoll** [comment] 2018-01-16 09:37
> when the RestTemplate interface is misused.

I am not sure I agree with that statement. Perhaps we should make the instrumentation of `RestTemplate` completely optional and clarify in the doc what is required to avoid those side effects?

**Comment by erlioniel** [comment] 2018-01-16 09:49
@jkschneider Yes, your assumption was correct. Looks like we are using restTemplate in a wrong way and spring creates a new tag for every single request.

`URI uri = fromUri(path)
        .queryParam("param", value)
        .build().encode().toUri();
return restTemplate.getForObject(uri, Entity.class);`

Should I check SNAPSHOT version or it is correct behavior of the framework? If it is I think there should be more clear way to avoid problem like we encountered, because it isn't easy to debug and fix actually.

**Comment by erlioniel** [comment] 2018-01-16 10:08
@jkschneider @snicoll 
Btw we are using UriComponentsBuilder because we have to pass array as GET param into the endpoint. So it might be useful to create overload for getForObject() with UriComponentsBuilder (instead of URI) for instrumentation and collecting statistics in cases like we have.

**Comment by erlioniel** [comment] 2018-01-16 14:08
I will leave my solution here, just for guys who will search how to disable / change tags for RestTemplate metrics or will fight with the same issue.

```
@Bean
public RestTemplateExchangeTagsProvider restTemplateTagConfigurer() {
    return new CustomRestTemplateExchangeTagsProvider();
}

private static class CustomRestTemplateExchangeTagsProvider implements RestTemplateExchangeTagsProvider {
    @Override
    public Iterable<Tag> getTags(String urlTemplate, HttpRequest request, ClientHttpResponse response) {
        String url = substringBefore(urlTemplate, "?");
        return asList(
                RestTemplateExchangeTags.method(request),
                RestTemplateExchangeTags.uri(url),
                RestTemplateExchangeTags.status(response),
                RestTemplateExchangeTags.clientName(request));
    }
}
```

**Comment by wilkinsona** [comment] 2018-01-16 14:12
@erlioniel So, in your case, it was the query parameters that were causing the problem rather than path variables?

**Comment by jkschneider** [comment] 2018-01-16 15:05
>  If it is I think there should be more clear way to avoid the problem like this, because it isn't easy to debug and fix actually.

Agreed. My plan is to add a `MeterFilter` limiting the tag cardinality of `http.client.requests`.

**Comment by erlioniel** [comment] 2018-01-16 15:46
@wilkinsona yes

**Comment by erlioniel** [comment] 2018-01-22 07:37
@jkschneider nice plan btw, is there any issue for that? Just to follow.

**Comment by erlioniel** [comment] 2018-01-22 07:42
Also I will leave this link here :) https://github.com/spring-cloud/spring-cloud-netflix/commit/5a127d07002daa6e7cb8ef8d4e9ce302aa49e84c

**Comment by jkschneider** [comment] 2018-01-22 14:37
@erlioniel Here is the associated Micrometer issue: https://github.com/micrometer-metrics/micrometer/issues/363

**Comment by philwebb** [comment] 2018-01-27 04:42
We need to port See https://github.com/spring-projects/spring-boot/pull/11776/commits/1a9c268b6baecaa44ffb770e736c40960c625cd3

**Closed** 2018-01-30 08:37 UTC
Labels: priority: normal, type: bug
