### ISSUE TITLE
Spring Boot updated from 1.5x to 2.0.9 , HTML rendering issues

### ISSUE THREAD

**Issue by sarath-s** [spring-projects/spring-boot#16743] opened 2019-05-08 06:25 UTC
Hello Team
I had Upgraded the spring boot to 2.0.9 from 1.5x.
Html file has jquery datatables.
Issues:
->For simple html pages, when script tags move from header to the end of the body, works fine.
->But for little complex pages, which has jquery datatables, earlier css are not at all working thought he script files are moved from head to body after all divs.one problem noticed is body tag not occuping 100%, but so many other css and other pages, js also wont work properly
->dependencies are given below:
```xml
   <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.9.RELEASE</version>
		<relativePath />
	</parent>
	</dependency>
		<dependency>
          <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
         </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web-services</artifactId>
		</dependency>
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
        <groupId>org.thymeleaf.extras</groupId>
        <artifactId>thymeleaf-extras-springsecurity5</artifactId>
		</dependency>
```

**Comment by snicoll** [comment] 2019-05-08 06:34
@sarath-s that's nowhere near enough detail for describing a bug. Have you looked at the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide) for a start? Perhaps you're [using webjars](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#webjars-locator)?

If you believe you've found an issue in Spring Boot, please share a small sample (zip or github repo) that reproduces the problem you've described.

**Comment by spring-issuemaster** [comment] 2019-05-15 06:38
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-05-22 06:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-22 06:36 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
