### ISSUE TITLE
Too many open files 

### ISSUE THREAD

**Issue by SahilWkar** [spring-projects/spring-boot#33518] opened 2022-12-14 05:12 UTC
We are getting too many open files issue on our AWS cloud application when using lambda with spring boot.
io.netty.channel.ChannelException:io.netty.channel.unix.Errors$NativeException:newSocketStream(...) failed too many open files.

Spring boot version is 2.6.6 and reactor netty core/http version used is 1.0.17

Can anyone please advise on same.

**Comment by JanStureNielsen** [comment] 2022-12-14 06:50
This is likely an OS configuration issue rather than a bug in Spring Boot. Search for "too many open files" for your OS to find solutions.

**Comment by SahilWkar** [comment] 2022-12-14 07:08
We are running this service in cloud on lambda.
Also i see similar issue raised earlier  #21923 and #1792 in past.
https://github.com/spring-cloud/spring-cloud-gateway/issues/1792
https://github.com/spring-projects/spring-boot/issues/21923
Is there any changes we need to do w.r.t using netty reactor library version which might help.

**Comment by mhalbritter** [comment] 2022-12-14 08:14
Hey, Spring Boot 2.6.6 is no longer in [OSS support](https://spring.io/projects/spring-boot#support). Please upgrade to at least Spring Boot 2.7 and feel free to chime back in if the problem persists.

**Comment by SahilWkar** [comment] 2022-12-14 10:40
We did upgrade the library to 2.7 ,problem still persists.
Can you please help.

**Comment by mhalbritter** [comment] 2022-12-14 13:28
If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-12-21 13:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-12-28 13:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-12-28 13:32 UTC

**Comment by CCx3x** [comment] 2024-01-23 07:32
I meet the same question with springboot 2.5.12 and reactor-netty 1.0.17 and netty 4.1.75.Final, what can I do to fix it or find the cause.
this is my stack message:
io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files; nested exception is io.netty.channel.ChannelException: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files
org.springframework.web.reactive.function.client.WebClientRequestException: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files; nested exception is io.netty.channel.ChannelException: io.netty.channel.unix.Errors$NativeIoException: newSocketStream(..) failed: Too many open files
        at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:141)

**Comment by mhalbritter** [comment] 2024-01-23 07:36
Spring Boot 2.5.12 is out of OSS support. Please upgrade to a [supported version of Spring Boot](https://spring.io/projects/spring-boot/#support) and chime in if the problem still persists. A sample with which we can reproduce the issue would be great.

**Comment by CCx3x** [comment] 2024-01-23 07:45
Can I use 2.7.2 or 2.7.18？I can't reoroduce the issue now, it's not frequent,  still need to obverse, is there any idea to do?

**Comment by mhalbritter** [comment] 2024-01-23 07:59
No, 2.7.x is out of OSS support, too. Only 3.1.x and 3.2.x are supported. 2.6.x - 3.2.x has [commercial support](https://spring.io/support/) available, if you'd like.

**Comment by CCx3x** [comment] 2024-01-23 08:07
All right. But I find the unlimit config is 655350, it has problem on two of 11 machines. I'm confused too...
