### ISSUE TITLE
JDK11: @ComponentScan doesn't work properly in JUnit tests

### ISSUE THREAD

**Issue by sergey-derugo** [spring-projects/spring-boot#18516] opened 2019-10-06 00:33 UTC
`@ComponentScan` cannot detect components in sub-packages if module-info.java(JDK11) presents in the sources.

**Steps to reproduce:**
1. Use Spring Boot 2.1.9.RELEASE and JDK 11.0.4
2. Download the [sample](https://github.com/spring-projects/spring-boot/files/3693830/testcase.zip)
3. Run `mvn clean test`

**Actual result:** 

- org.springframework.beans.factory.UnsatisfiedDependencyException is thrown, see the attached  [stack trace](https://github.com/spring-projects/spring-boot/files/3693832/error.log).

**Expected result:**

- All tests passed.

**Workarounds:**

1. Remove module-info.java
2. Use `@Import` instead of `@ComponentScan` , see com.example.demo.ServiceModuleConfiguration in the attached sample

**Comment by wilkinsona** [comment] 2019-10-06 12:01
Thanks for the report. This is a duplicate of https://github.com/spring-projects/spring-framework/issues/21515.

**Closed by wilkinsona** 2019-10-06 12:01 UTC
Labels: status: waiting-for-triage
