### ISSUE TITLE
Support JSP with Embedded Jetty

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#367] opened 2014-02-17 19:51 UTC
Documentation lists some JSP limitations, however, some of these may have been fixed with recent 'fat jar' updates. We should revisit to see what problems still exist.

**Comment by luizguimaraes** [comment] 2015-06-08 12:14
I have solved the "The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved..." problem in my app by setting a new classloader to jetty WebAppContext as sugest here: https://github.com/jetty-project/embedded-jetty-jsp

I'm also using the following dependency:


    <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-jsp</artifactId>
    </dependency>

**Comment by AlexeyPanichenko** [comment] 2015-08-21 13:53
I have added 
 <dependency>
            <groupId>org.mortbay.jetty</groupId>
            <artifactId>jsp-2.1-glassfish</artifactId>
            <version>2.1.v20100127</version>
 </dependency>

to depencencies and it started work! Taken from http://stackoverflow.com/questions/17685330/how-do-you-get-embedded-jetty-9-to-successfully-resolve-the-jstl-uri

**Comment by arcadius** [comment] 2015-10-24 08:20
@AlexeyPanichenko  Please would you mind summarizing all the steps taken to make JSP+JSTL work on embedded Jetty?

Thanks.

**Comment by wilkinsona** [comment] 2015-10-27 16:31
This is more than just a documentation issue.

We can't use the `org.mortbay.jetty:jsp-2.1-glassfish` dependency as it predates Jetty's move to Eclipse. There's no equivalent [org.eclipse.jetty](http://repo1.maven.org/maven2/org/eclipse/jetty/) dependency as far as I can see.

The tip from @luizguimaraes is a little more fruitful. It gets things working in an IDE and with `mvc spring-boot:run`. Things still explode when running an executable war (I haven't tried a jar). Another step forward can be made by marking any dependencies that contain TLDs as requiring unpacking. However, things still explode, just in a different way.

**Comment by tsachev** [comment] 2016-03-01 12:49
With recent versions of jetty they are now using jasper with tomcat dependencies removed for jsp.

I created an PR #5290 that demonstrates it is possible to do with `jetty` 9.2 and 9.3 the same thing you can to with `tomcat-embed`.

There are few glitches
* for 9.3 to work #5287 needs to be fixed (PR is here #5289)
* for 9.2 to work I had to add `org.mortbay.jasper` in `spring-boot-dependencies`. This might not be needed if they fix it on their side (opened an question eclipse/jetty.project#371).

I will be really happy to see this in 1.4. Let me know if I can help with something else.

**Comment by joakime** [comment] 2016-03-10 20:06
Where's the [`JettyJspServlet`](http://download.eclipse.org/jetty/9.2.15.v20160210/apidocs/org/eclipse/jetty/jsp/JettyJspServlet.html) reference?  It seems to be missing.

**Comment by janbartel** [comment] 2016-03-15 01:23
@tsachev  and @ghillert not sure what spring boot is doing, however I can contribute the following information:

* nothing is going to work with classes and resources stored inside jars inside jars: the classloader can't deal with this, so all jars will need to be extracted. 
* once the embedded jars have been extracted the "server" classpath and the "webapp" classpaths need to be setup for jetty.  If the executable jar actually contains a webapp, then this is easy and you can let jetty do the unpacking and things should mostly be good
* in jetty-9.2 you had the option of using either Glassfish jsp or Apache jsp. Looks like spring-boot may have selected Glassfish jsp ?, which has certain requirements for the classloader setup. Apache jsp would be a better choice as it doesn't require an explicit classpath setup. To use Apache-based jsp, you will need to define org.eclipse.jetty.jsp.JettyJspServlet as the servlet with id="jsp" in a webdefault.xml or in code and you will also need to use the org.mortbay.jasper.apache-jsp.jar and org.mortbay.jasper.apache-el.jar artifacts as mentioned by @tsachev .
* in jetty-9.3 we dropped support for Glassfish jsp, so there's only Apache-based jsp. Same comments apply as above as to which jars are needed (updated versions thereof) and the JettyJspServlet.

We've had bug reports before of problems with users with executable jars and they have pretty much all been caused by trying to run with packed jars inside a packed war/jar. Once the unpacking happens and the classpaths are correct, then jetty and jsps work correctly.

If there is more info required please ask.

I will reply separately to @tsachev on https://github.com/eclipse/jetty.project/issues/371 regarding upgrade support to more recent Apache-based jsp for old jetty-9.2 series.

**Comment by tsachev** [comment] 2016-03-15 05:49
Thanks @janbartel, I understand that jars inside jar/war is not currently working with jetty. But in case of apache jsp I saw that what jasper is doing in this case is to transform `jar:jar:file` urls to `war:jar:file` urls. This is done here `org.apache.tomcat.util.scan.JarFactory#getJarEntryURL(URL, String)`. What tomcat have, but jetty does not is a `WarUrlStreamHandler` that understands this.
In my PR I register one such handler here `https://github.com/tsachev/spring-boot/blob/gh-367/spring-boot/src/main/java/org/springframework/boot/context/embedded/jetty/JasperInitializer.java`.

I am not sure if there is any standard involved here. If this is not part of the Jsp spec I would not expect this to be supported by Jetty, too. That is why I decided to try adding it in spring-boot. Later I discovered this https://github.com/eclipse/jetty.project/tree/master/jetty-osgi/jetty-osgi-boot-warurl/src/main/java/org/eclipse/jetty/osgi/boot/warurl, but I do not think it will support exactly the same structure of `war` urls.

**Comment by LvR** [comment] 2016-03-17 10:50
Hi
@tsachev Facing the same issue, I tryied your solution with Jetty 9.2.15.v20160210. It works well as executable war. I manage to get it work with executable jar with those 2 steps:
- moving webapp folder into resource folder
- changing jetty resourceBase (by adding a JettyServerCustomizer) :
`jettyContext.setResourceBase(new ClassPathResource("webapp").getURI().toString());`

**Comment by joakime** [comment] 2016-03-17 12:21
Note: you can use `jettyContext.setBaseResource(new ClassPathResource("webapp"))` and force the Resource type to be a `ClassPathResource` and not have Jetty attempt to figure out what kind of Resource implementation to use from the String in `.setResourceBase(String)`.

**Comment by janbartel** [comment] 2016-03-30 07:22
Looking at the code in spring-boot master to support jetty embedding, I can't see how it would work with jsps at all:

1 The standard apache JspServlet is configured instead of the org.eclipse.jetty.jsp.JettyJspServlet
2 The JettyJasperInitializer (a ServletContainerInitializer which helps set up jsp) is not called

For 1 the workaround is to follow the doco at https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-embedded-container and create a new JettyEmbeddedServletContainerFactory, and then explicitly set the name of the jsp class that it should use. Ideally though the spring-boot code would be fixed to use the correct servlet name.

For 2 needs some development work in the spring-boot jetty embedding code. I note that the tomcat embedding code does explicitly set up a jsp ServletContainerInitializer, so something similar would need to be done for jetty. I am happy to contribute some lines of code that would be needed, but I'd also like to understand a little more about some of the current jetty embedding code first. For example, I'm not sure why none of the standard jetty Configuration classes are used on the WebApPContext - eg MetaInfConfiguration that would find resources and tlds inside jar files?

Jan

**Comment by wilkinsona** [comment] 2016-03-30 07:24
@janbartel We know it doesn't work. That's why this issue is open as an enhancement.

**Comment by janbartel** [comment] 2016-03-30 08:56
@wilkinsona  ok, well I'm offering to help :)

**Comment by dsyer** [comment] 2016-03-30 09:24
@janbartel thanks, that would be great. If there's anything odd or missing in the current Jetty support I doubt it was intentional (just ignorance). Please feel free to fix anything you think appropriate and send PRs.

**Comment by wilkinsona** [comment] 2016-03-30 09:34
@janbartel Thank you. Perhaps you could take a look at the PR that @tsachev has already contributed: https://github.com/spring-projects/spring-boot/pull/5290 and see what more, if anything, you think needs to be done?

**Comment by wilkinsona** [comment] 2016-03-30 09:36
@janbartel And sorry for being rather blunt in my [comment above](https://github.com/spring-projects/spring-boot/issues/367#issuecomment-203287288). I'm guilty of skimming your final paragraph and missed your offer to contribute.

**Comment by cemo** [comment] 2016-05-13 14:50
Any chance to merge it? :)

**Comment by arcadius** [comment] 2016-05-17 05:47
... Or in which Milestone will this get merged?
 :+1:

**Comment by wilkinsona** [comment] 2016-05-17 08:19
The PR (#5290) is targetted at 1.4 RC1.

**Comment by arcadius** [comment] 2016-05-17 10:59
Thanks @wilkinsona

**Closed** 2016-06-15 14:10 UTC
Labels: enhancement
