### ISSUE TITLE
SpringIterableConfigurationPropertySource fails when underlying source throws ConcurrentModificationException

### ISSUE THREAD

**Issue by ddcruver** [spring-projects/spring-boot#17013] opened 2019-05-29 17:40 UTC
We have not been able to reproduce it reliably but we have notice instances of Spring Boot not initializing correctly and each time throwing a `java.Util.ConcurrentModificationException` exception when trying to bind properties for the Spring Application.

This seems to happen in a AWS instance were the I/O and CPU is more restrained and does not happen as much when we deploy to larger instances.  There is no documented case of this happening in our local development environments.

```
Caused by: java.util.ConcurrentModificationException
    at java.util.Hashtable$Enumerator.next(Hashtable.java:1387) [rt.jar:1.8.0_212]
    at java.util.AbstractCollection.addAll(AbstractCollection.java:343) [rt.jar:1.8.0_212]
    at java.util.HashSet.<init>(HashSet.java:120) [rt.jar:1.8.0_212]
    at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource$CacheKey.copyKey(SpringIterableConfigurationPropertySource.java:189)
    at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource$CacheKey.copy(SpringIterableConfigurationPropertySource.java:184)
    at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.getCache(SpringIterableConfigurationPropertySource.java:142)
    at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.getConfigurationPropertyNames(SpringIterableConfigurationPropertySource.java:97)
    at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.iterator(SpringIterableConfigurationPropertySource.java:87)
    at org.springframework.boot.context.properties.source.ConfigurationPropertyState.search(ConfigurationPropertyState.java:62)
    at org.springframework.boot.context.properties.source.SpringIterableConfigurationPropertySource.containsDescendantOf(SpringIterableConfigurationPropertySource.java:93)
    at org.springframework.boot.context.properties.bind.Binder.containsNoDescendantOf(Binder.java:367)
    at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:256)
    at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220)
    ... 65 more
```

I will attach more complete stack traces to it being called from different points in the initialization of our application.

[concurrent-modification-instance-1.txt](https://github.com/spring-projects/spring-boot/files/3233728/concurrent-modification-instance-1.txt)
[concurrent-modification-instance-2.txt](https://github.com/spring-projects/spring-boot/files/3233730/concurrent-modification-instance-2.txt)

**Comment by philwebb** [comment] 2019-05-29 22:23
There appears to be a few issues with the way we're storing the cache and cache key which should be fixed, but I'm not sure those updates will totally solve your issue. Although I can protect against a `ConcurrentModificationException` when copying the key, it's likely to just pop up again in `getPropertyMappings` when we call `getPropertySource().getPropertyNames()`.

The real problem appears to be that multiple threads are trying to access a property source that isn't thread safe. With most Spring Boot applications, the contents of the property sources aren't modified once they're created so I'm curious if there's something specific to your environment? Do you have any custom property sources? Or do you change property sources on the fly?

If you're able to create a sample project that replicates the issue, or share privately your existing project we can dig a little more.

**Comment by philwebb** [comment] 2019-05-29 22:27
I've raise #17017 for the obvious concurrency issues. We'll leave this one to track the root cause of `ConcurrentModificationException`.

**Comment by dewthefifth** [comment] 2019-05-30 14:17
> 
> 
> There appears to be a few issues with the way we're storing the cache and cache key which should be fixed, but I'm not sure those updates will totally solve your issue. Although I can protect against a `ConcurrentModificationException` when copying the key, it's likely to just pop up again in `getPropertyMappings` when we call `getPropertySource().getPropertyNames()`.
> 
> The real problem appears to be that multiple threads are trying to access a property source that isn't thread safe. With most Spring Boot applications, the contents of the property sources aren't modified once they're created so I'm curious if there's something specific to your environment? Do you have any custom property sources? Or do you change property sources on the fly?
> 
> If you're able to create a sample project that replicates the issue, or share privately your existing project we can dig a little more.

I work with ddcruver, and can provide a little bit more detail about the deployment environment. Our application is being deployed along side many other applications on a shared wildfly 12 application server (as WARs). My suspicion is that the SystemProperties are being modified by one of the other applications during startup, and as a result of that we're getting the concurrent modification exception. I suspect that the problem lies in how System.getProperties values are accessed and not in other property sources (necessarily)

**Comment by ddcruver** [comment] 2019-05-30 14:35
My co-worker chimed in while writing this but it is possible that because of other applications are modifying Java System properties we are getting this issue.  Regardless here are some more details on what we are doing ....

We do change the spring default profile and configuration locations "on-the-fly" but nothing after SpringApplicationBuilder#run(args) is called.

Depending on if we are deploying standalone or in the traditional deployment we setup things differently in the CommonConfig.setup(standalone, persistenceRequired, args, logger) method and through the web.xml respectably.

For Traditional Deployment (WAR) the web.xml setups:
```
spring.config.name=example-application
spring.profiles.default = production,jpa
product.config.root = file:${jboss.server.config.dir}/<product-name>
spring.config.additional-location= classpath:/config/application-default.yaml,classpath:/config/application.properties,classpath:/config/application.yaml,${product.config.root}/<product-name>.properties,${product.config.root}/<product-name>.yaml,${product.config.root}/${spring.config.name}/
```

For Standalone Deployment the CommonConfig.setup() function setups:
```
spring.profiles.default = production,jpa,standalone
spring.config.location = classpath:/config/application-default.yaml,classpath:/,classpath:/config,classpath:/config/standalone-default.yaml,classpath:/config/standalone.yaml,file:./,file:./config
```

Our configuration maybe a little complex but has some requirements:
- Configuration property locations in JBoss/WildFly match existing non-Spring Boot applications conventions. (why we assign spring.config.name in our web.xml)

- Our product has common properties that are shared between all our applications. (application-default.yaml and standalone-default.yaml)

- Keep config properties in classpath using spring.config.name default of application instead of custom name so editors (Eclipse/IntelliJ) do not need to be setup to recognize the custom name by each developer for each individual application each time they checkout the project.

Additionally we have a main method similar to what is described in [Traditional Deployment](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html

```
package org.example.productname.application.web;


import org.example.common.config.CommonConfig;
import org.example.common.config.CommonWebApplicationConfig;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.ImportResource;
import org.springframework.integration.config.EnableIntegrationManagement;

@Import(CommonWebApplicationConfig.class)
@ImportResource("classpath:spring-context/initial-context.xml")
@SpringBootApplication(
		scanBasePackages = {
				"org.example.application.web"
		},
		exclude = {
				SecurityAutoConfiguration.class,
				ManagementWebSecurityAutoConfiguration.class
		})
@EnableIntegrationManagement
public class ExampleApplication
		extends SpringBootServletInitializer
{
	private static final Logger log = LoggerFactory.getLogger(ExampleApplication.class);

	/**
	 * Spring Boot Standalone Entry Point
	 *
	 * @param args arguments provided by command line.
	 */
	public static void main(String[] args)
	{
		CommonConfig.setup(true, false, args, log);
		configureApplication(new SpringApplicationBuilder()).run(args);
	}

	/**
	 * Shared customization
	 *
	 * @param builder Spring Application Builder from Servlet Initialization
	 */
	private static SpringApplicationBuilder configureApplication(SpringApplicationBuilder builder)
	{
		builder.sources(ExampleApplication.class);
		return builder;
	}

	/**
	 * Spring Boot Servlet Entry Point
	 *
	 * @param builder Spring Application Builder from Servlet Initialization
	 */
	@Override
	protected SpringApplicationBuilder configure(final SpringApplicationBuilder builder)
	{
		return configureApplication(builder);
	}
}


```

**Comment by philwebb** [comment] 2019-05-30 15:46
> My suspicion is that the `SystemProperties` are being modified by one of the other applications during startup.

That would certainly explain things. It looks like [this is quite a common problem](https://www.google.com/search?q=system.getproperties+concurrentmodificationexcaption). I think it's perhaps something we should try and solve in the `systemProperties` `PropertySource` so I'll raise a Spring Framework issue.

**Comment by philwebb** [comment] 2019-06-12 18:44
@ddcruver Spring Framework now gets property names in a `synchronized` block. What code to you have that inserts items? Is it possible to also add `synchronized` to it? i.e:

```java
Properties properties = System.getProperties();
synchronized (properties) {
    properties.setProperty("name", "value");
}
```

**Comment by ddcruver** [comment] 2019-06-20 21:05
We write to system properties in various places and have multiple applications running in a WildFly Application Server doing this.  A majority of the writes happen in a shared component that takes all our Spring Properties and writes them to Java System Properties.  This occurs in our legacy applications that don't use Spring Boot but do use Spring Framework.

While we could add a synchronized to that function, as far as I know this won't prevent threads running in a different application from calling that function.

**Comment by wilkinsona** [comment] 2019-06-20 23:04
There’s no need to synchronise when getting, setting, or removing properties as `Hashtable`, which `Properties` extends, is already synchronized. Problems only arise when iterating over the contents which Framework has now addressed by taking a snapshot while synchronized on the same lock as `Properties` uses for other operations.

I think we can close this one as the Framework changes should be sufficient.

**Comment by philwebb** [comment] 2019-06-21 19:31
Thanks for the clarification @wilkinsona and sorry for the confusion I caused by thinking we needed an explicit `synchronized` block.

**Closed by philwebb** 2019-06-21 19:31 UTC
Labels: status: feedback-provided, status: waiting-for-triage
