### ISSUE TITLE
Reactor Nettty should be a dependency of spring-test or spring-boot-test?

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#10368] opened 2017-09-21 03:51 UTC
When I wrote some tests for `webflux` applications, but when I used none Reactor Netty runtime, such as Tomcat, Jetty, Undertow etc, I found the `WebTestClient` depends on [HttpClient](https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/ipc/netty/http/client/HttpClient.java), it is part of `reactor-netty`. 

So I am not sure it should be a dependency of `spring-test` or `spring-boot-test`, or set it `optional` for test dependencies?

**Comment by wilkinsona** [comment] 2017-09-21 04:59
Duplicate of #8914

**Closed by wilkinsona** 2017-09-21 04:59 UTC
Labels: status: waiting-for-triage
