### ISSUE TITLE
ShallowEtagHeaderFilter breaks Controller endpoint that returns a CompletableFuture 

### ISSUE THREAD

**Issue by mdoh** [spring-projects/spring-boot#19100] opened 2019-11-22 13:17 UTC
I have a simple Controller like this.

```java
@RestController
public class Controller {

    @GetMapping("/bar")
    @ResponseBody
    public CompletableFuture<ResponseEntity<String>> bar() {
        return CompletableFuture.completedFuture(new ResponseEntity<>("bar", HttpStatus.OK));
    }
}
```

When I add a configuration that has a ShallowEtagHeaderFilter bean it breaks the /bar endpoint
```java
@Configuration
public class Configuration {

    @Bean
    public Filter shallowEtagHeaderFilter() {
        return new ShallowEtagHeaderFilter();
    }
} 
```
This code was working with Spring Boot 1.5.x

**Comment by wilkinsona** [comment] 2019-11-22 13:39
Thanks for the issue report. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/18931. It worked in Spring Boot 1.5 as the default dispatcher types for a filter were not aligned with the servlet spec. They were aligned in 2.0 so the default is now `REQUEST`.

**Closed by wilkinsona** 2019-11-22 13:39 UTC
Labels: status: waiting-for-triage
