### ISSUE TITLE
InstanceAlreadyExistsException during continuous build

### ISSUE THREAD

**Issue by huxi** [spring-projects/spring-boot#5286] opened 2016-02-29 15:36 UTC
I receive lots of messages like this in case of a continuous Gradle build in a Ratpack application:

```
663870 [main] ERROR o.s.b.a.e.jmx.EndpointMBeanExporter - Could not register MBean for endpoint [healthEndpoint]
org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.springframework.boot.actuate.endpoint.jmx.DataEndpointMBean@48e4869] with key 'healthEndpoint'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=healthEndpoint
```

This happens during restart triggered by a change in one of the application files.

It seems that `org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter` isn't properly unregistering the MBeans during shutdown.

**Comment by wilkinsona** [comment] 2016-02-29 15:50
@huxi Can you please provide a small sample project that reproduces the problem?

**Comment by huxi** [comment] 2016-02-29 16:33
@wilkinsona I created a small project demonstrating the problem:
https://github.com/huxi/bugs/tree/master/spring-boot/instance-already-exists

**Comment by wilkinsona** [comment] 2016-02-29 17:31
@huxi Thanks for the sample project.

The problem is that the application context isn't being closed when the Ratpack server is restarted. Given that Ratpack is refreshing the application context as part of startup, it is also its responsibility to close it as part of its stop processing.

Unfortunately, that means that there's nothing we can do in Spring Boot to fix this. You'll need to raise an issue against Ratpack.

**Closed by wilkinsona** 2016-02-29 17:31 UTC
Labels: feedback-provided
