### ISSUE TITLE
spring.resources.chain.strategy.content.enabled not working

### ISSUE THREAD

**Issue by 112921482** [spring-projects/spring-boot#15104] opened 2018-11-06 02:29 UTC
spring.resources.chain.strategy.content.enabled not working

**Comment by philwebb** [comment] 2018-11-06 06:14
There's not enough information in this report to be sure, but I'm guessing this might be a duplicate of #14897. Please try the latest SNAPSHOT version to check. If it doesn't work, we're going to need a sample that shows the problem.

**Closed by philwebb** 2018-11-06 06:14 UTC
Labels: status: waiting-for-triage
