### ISSUE TITLE
Could not disable auto-creation of DataSource

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot#2918] opened 2015-05-05 13:06 UTC
See https://jira.spring.io/browse/SPR-12978

**Comment by snicoll** [comment] 2015-05-05 13:08
My first reaction would be that `@EnableJms` does nothing else but processing `@JmsListener` annotated method. It's harmless if you don't use it so what do you want to disable exactly?

**Comment by dantheperson** [comment] 2015-05-06 05:26
It tries to load a datasource, which causes startup to fail, because i don't have a datasource in this configuration.   The app reads from JMS, and updates data via a REST interface.

Even though you have required=false on the database, spring-boot tries to find it anyway and then falls over in a heap. 

At first it was failing with the DataSourceAutoConfiguration, then transaction manager.  When i exclude those

    @EnableAutoConfiguration(exclude = { DataSourceAutoConfiguration.class, DataSourceTransactionManagerAutoConfiguration.class })

then this JMS autoconfiguration still tries to load those even though they are excluded.

    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jms.JmsAnnotationDrivenConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.transaction.PlatformTransactionManager org.springframework.boot.autoconfigure.jms.JmsAnnotationDrivenConfiguration.transactionManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.sql.DataSource org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration.dataSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath.

**Comment by dantheperson** [comment] 2015-05-06 05:28
All the other spring-boot AutoConfiguration classes have public visibility which allows them to be excluded.  You don't need to add a new property to disable handling of @EnableJms, just change the visibility of the AutoConfiguration and then we can exclude it using the existing spring-boot mechanism.

**Comment by snicoll** [comment] 2015-05-06 11:57
What you're experiencing sounds a bit weird. `JmsAnnotationDrivenConfiguration` is not an auto-configuration; `JmsAutoConfiguration` is so if you need to exclude JMS support, you're just using the wrong class.

**Comment by dantheperson** [comment] 2015-05-06 20:22
Oh i see that one is included.  I just saw that in the stacktrace and didn't realise it was getting included indirectly.  I'll give JmsAutoConfiguration.

I wonder also, if it would be considered a bug that i have to exclude these things at all, spring-boot is failing to start up as it's failing to load a speculative autoconfigured dependency, but that dependency (the transaction-manager) is marked required=false, and anyway i have explicitly declared a transaction-manager in my own configuration.

I think i small illustration project could be in order.

**Comment by dantheperson** [comment] 2015-05-06 21:50
Ok yup, once i add JmsAutoConfiguration.class to the excludes, then the error about failing to initialise JmsAnnotationDrivenConfiguration disappears.

Still fails to startup though.  Tries to load DataSourceAutoConfiguration even though it's excluded.

    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$JdbcTemplateConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.sql.DataSource org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$JdbcTemplateConfiguration.dataSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath.

**Comment by snicoll** [comment] 2015-05-07 02:01
Yes, I sort of came to the same conclusion. Could you please contribute a sample project that demonstrates what you're doing please? 

The `PlatformTransactionManager` thing is guarded as well so maybe you have two transaction managers? In any case, there is certainly an issue on our side so a sample may help us to figure out quickly what's wrong. Thanks!

**Comment by snicoll** [comment] 2015-05-12 14:53
Ping @dantheperson

**Comment by dantheperson** [comment] 2015-05-14 10:01
working on it.  I can't reproduce with a trivial example as i don't have enough jms configuration in place to trigger JmsAnnotationDrivenConfiguration.  I'll have to check the real code back at work.

**Comment by snicoll** [comment] 2015-05-14 10:31
Add spring-boot-starter-hornetq and you'll trigger it.

**Comment by snicoll** [comment] 2015-05-22 14:11
ping?

**Comment by wilkinsona** [comment] 2015-10-12 12:50
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.

**Closed by wilkinsona** 2015-10-12 12:50 UTC
Labels: icebox, waiting-for-feedback
