### ISSUE TITLE
NoSuchMethodError in WebSocketMessageBrokerConfigurationSupport

### ISSUE THREAD

**Issue by nitin-** [spring-projects/spring-boot#18243] opened 2019-09-17 03:27 UTC
> messageBrokerTaskScheduler method is missing in class file WebSocketMessageBrokerConfigurationSupport Hence throwing an error 

java.lang.NoSuchMethodError: 'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurationSupport.messageBrokerTaskScheduler()'

**Comment by nitin-** [comment] 2019-09-17 04:05
@spring-issuemaster Please take an immediate action

**Comment by spencergibb** [comment] 2019-09-17 04:29
You likely have mismatched versions of spring

**Comment by snicoll** [comment] 2019-09-17 06:26
@nitin- this is likely a broken setup on your end with mismatched versions of Spring. To be sure, please share a minimal sample that we can run and reproduces the issue. Pasting incomplete stacktrace is not helping us helping you.

**Comment by spring-issuemaster** [comment] 2019-09-24 06:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-10-01 06:29
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-10-01 06:29 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
