### ISSUE TITLE
Management web endpoint with `base-path=/` not working with SpringBoot 2.0.4

### ISSUE THREAD

**Issue by endSly** [spring-projects/spring-boot#14236] opened 2018-08-29 10:20 UTC
Management endpoint has stopped working since `2.0.4.RELEASE` when the `base-path` is set to `"/"`.

With the following config:
```yaml
management:
  server.port: 10011
  endpoints.web:
    base-path: '/'
    exposure.include: jolokia
```

it returns 404 with spring boot 2.0.4:
```bash
curl http://127.0.0.1:10011/jolokia
{"timestamp":"2018-08-29T10:15:25.249+0000","status":404,"error":"Not Found","message":"No message available","path":"/jolokia"}

curl http://127.0.0.1:10011/jolokia/
{"timestamp":"2018-08-29T10:15:30.709+0000","status":404,"error":"Not Found","message":"No message available","path":"/jolokia/"}
```

but it worked with `2.0.3.RELEASE`:
```bash
curl http://127.0.0.1:10011/jolokia 
{"request":{"type":"version"},"value":{"agent":"1.6.0","protocol":"7.2","config":{"listenForHttpService":"true","authIgnoreCerts":"false","agentId":"192.168.104.67-30932-555e866c-servlet","debug":"false","agentType":"servlet","policyLocation":"classpath:\/jolokia-access.xml","agentContext":"\/jolokia","serializeException":"false","mimeType":"text\/plain","dispatcherClasses":"org.jolokia.http.Jsr160ProxyNotEnabledByDefaultAnymoreDispatcher","authMode":"basic","streaming":"true","canonicalNaming":"true","historyMaxEntries":"10","allowErrorDetails":"true","allowDnsReverseLookup":"true","realm":"jolokia","includeStackTrace":"true","useRestrictorService":"false","debugMaxEntries":"100"},"info":{"product":"tomcat","vendor":"Apache","version":"8.5.31"}},"timestamp":1535537652,"status":200}      
```

it works as expected with a different base path

Could it be related with #13921 ?

**Comment by snicoll** [comment] 2018-08-29 11:15
Duplicate of #13964

**Closed by snicoll** 2018-08-29 11:15 UTC
Labels: status: waiting-for-triage
