### ISSUE TITLE
Currently no Bootiful way to get a `CachingConnectionFactory`

### ISSUE THREAD

**Issue by mminella** [spring-projects/spring-boot#13065] opened 2018-05-04 16:55 UTC
When using JMS and Spring Boot, Spring Boot will provide a `JmsTemplate` out of the box for you that is configurable via external properties.  This is great.  However, the `ConnectionFactory` provided is not a `CachingConnectionFactory`.  It's considered a best practice to use a `CachingConnectionFactory` when using the `JmsTemplate`.  It would be great to provide a way to get one autoconfigured out of the box that is configurable via Boot properties.  cc: @garyrussell

**Comment by garyrussell** [comment] 2018-05-04 17:00
Or, at least a `SingleConnectionFactory`, but preferably fully configurable SCF/CCF.

From the Spring docs for the SCF:

>This is useful for testing and standalone environments so that the same connection can be used for multiple JmsTemplate calls that may span any number of transactions. 

There's a lot of folklore on the internet about "Spring JMS being slow". In most cases, this is due to opening a new connection for every `JmsTemplate` operation.

**Comment by wilkinsona** [comment] 2018-05-04 17:28
Duplicate of #12161.

**Closed by wilkinsona** 2018-05-04 17:28 UTC
Labels: status: waiting-for-triage
