### ISSUE TITLE
spring-boot-loader  classpath 

### ISSUE THREAD

**Issue by TanqiZhou** [spring-projects/spring-boot#15731] opened 2019-01-17 13:28 UTC
我发现spring-boot-loader并没有从自己的classpath首先获取配置，而是顺序加载，这个是错误的！！！
这样自己的classpath配置可能被覆盖。
在mybatis调试中出现了这个问题。
Sorry, my English is not good, I hope you can understand.

**Comment by wilkinsona** [comment] 2019-01-17 14:12
Courtesy of Google Translate:

> I found that spring-boot-loader didn't get the configuration first from its own classpath, but loaded sequentially, this is wrong! ! !
This way your own classpath configuration may be overwritten.
This problem occurred in mybatis debugging.

Sorry, but I don't understand what you mean by "it own classpath" or by "loaded sequentially". Perhaps you can provide a small sample the reproduces the problem and shows how your own classpath configuration is being overwritten?

**Comment by spring-issuemaster** [comment] 2019-01-24 14:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-01-31 14:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-01-31 14:13 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
