### ISSUE TITLE
Exclude avro generated classes from RestartClassLoader

### ISSUE THREAD

**Issue by TeNNoX** [spring-projects/spring-boot#14622] opened 2018-09-27 10:23 UTC
I am experiencing a problem similar to #3316 & #4636 - but I don't have classes that are loaded from a library, but classes generated by the **avro-maven-plugin** into `/target/generated-sources/avro`

As they are loaded with all of the other classes with the URL `/target/classes`, I can't exclude them with the `spring-devtools.properties`' `restart.exclude.`.

The issue I'm having is a **ClassCastException** inside my `@KafkaListener`because the Record class I'm loading in my code is loaded by `RestartClassLoader`, but in the foreign code that deserializes the Avro data ([AbstractKafkaAvroDeserializer](https://github.com/confluentinc/schema-registry/blob/eb247ee5761c806595e6486054330557e266b7b9/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java#L257)) it is loaded by the AppClassLoader.

Spring-Boot: 2.0.2.RELEASE

**Comment by wilkinsona** [comment] 2018-09-27 10:53
I suspect this is a bug in `AbstractKafkaAvroDeserializer`. It should probably be using the thread context class loader rather than the class loader that loaded `AbstractKafkaAvroDeserializer`. That's only a somewhat educated guess at the moment. Can you please provide a minimal sample (something that we can `git clone` or unzip and run) that reproduces the problem?

**Comment by wilkinsona** [comment] 2018-09-28 15:37
Thanks for the sample. I've reproduced the problem.

The failure is occurring due to a [limitation in Avro](https://issues.apache.org/jira/browse/AVRO-1425) that means it falls back to its own `ClassLoader` when it's not told which `ClassLoader` to use. It would be more flexible (and DevTools would work) if it fell back to the thread context class loader.

You could avoid the problem for now by moving your Avro-generated classes into a separate jar. That will cause DevTools to identify them as classes that won't change and load them using the app class loader rather than the restart class loader.

Another option would be to compile the code in `target/generated-sources/avro` into a directory other than `target/classes`. I'm not sure if Maven offers that level of flexibility, but it should be possible in your IDE which is the main environment that DevTools targets. It's also possible with Gradle.

I'm not sure what we'll be able to do to improve things beyond that. We could look at more sophisticated configuration of what is and is not loaded using the restart class loader, but that would introduce some extra complexity for something that should really be fixed in Avro.

**Comment by philwebb** [comment] 2018-10-03 22:41
I'm not keen to add dedicated logic in the restarter to deal with Avro. I think the best course of action is to get this fixed upstream.

**Closed by philwebb** 2018-10-03 22:41 UTC
Labels: for: team-attention, status: feedback-provided, status: waiting-for-triage
