### ISSUE TITLE
Possible typo WebClient docs

### ISSUE THREAD

**Issue by fadelgaber** [spring-projects/spring-boot#21568] opened 2020-05-25 18:41 UTC
On [this page](https://docs.spring.io/spring-boot/docs/2.0.3.RELEASE/reference/html/boot-features-webclient.html):

```java
@Service
public class MyService {

	private final WebClient webClient;

	public MyService(WebClient.Builder webClientBuilder) {
		this.webClient = webClientBuilder.baseUrl("http://example.org").build();
	}

	public Mono<Details> someRestCall(String name) {
		return this.webClient.get().url("/{name}/details", name)
						.retrieve().bodyToMono(Details.class);
	}

}
```
`this.webClient.get().url("/{name}/details", name)` should be `uri` instead?

**Comment by philwebb** [comment] 2020-05-26 03:40
Good spot! Thanks for reporting the issue.

**Comment by wilkinsona** [comment] 2020-06-02 10:56
This is a duplicate of https://github.com/spring-projects/spring-boot/pull/14499. It has already been fixed in 2.0.6 and later.

**Closed by wilkinsona** 2020-06-02 10:56 UTC
Labels: type: documentation
