### ISSUE TITLE
Health Indicator does not support custom endpoint path.

### ISSUE THREAD

**Issue by miggy8234** [spring-projects/spring-boot#6428] opened 2016-07-19 15:47 UTC
Bug report

Based on the latest Spring Documentation there should be support for altering the path of a standard endpoint such as /health for health checks to be /Status. This is stated in section [46.2](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-monitoring.html) of the current reference documents. However, after seeing this fail for me and investigating the code if you look at the [health endpoint](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/HealthEndpoint.java) and those alike you are passing hard coded values to the super method vs using the property and having a default value. Now this super method assigns a value to the id however, for these objects the id is used as the path. I would recommend althering it [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/mvc/AbstractEndpointMvcAdapter.java) becasue it would be the most passive change where you read the path from the properties and default to the id if nothing was provided.

**Comment by wilkinsona** [comment] 2016-07-19 16:01
It works for me. This configuration:

```
endpoints.health.path=status
```

Results in this mapping:

```
2016-07-19 16:55:53.416  INFO 98498 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/status || /status.json],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(java.security.Principal)
```

Alternatively, this configuration:

```
endpoints.health.id=status
```

Produces the same mapping:

```
2016-07-19 16:57:32.426  INFO 98647 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/status || /status.json],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(java.security.Principal)
```

The hardcoded values are just the defaults. They can be changed via the setter methods based on what your configuration. Unfortunately, you haven't described that. Can you please provide a sample that reproduces the problem?

**Comment by miggy8234** [comment] 2016-07-19 16:38
What version was this ability introduced? The code I experienced it in I can not share however I am making a second mock up that can be shared now.

The the main difference maybe I am not using the auto configuration. I am still using spring MVC but to access the health check in actuator I create the following beans: EndpointHandlerMapping, EndpointMvcAdapter, HealthEndpoint, HealthAggregator, and then I create the health indicators.

**Comment by wilkinsona** [comment] 2016-07-19 16:42
IIRC, configuring the id has worked for a long time. There was a bug with configuring the path that was fixed in 1.3.3. See https://github.com/spring-projects/spring-boot/issues/5105.

**Comment by philwebb** [comment] 2016-07-19 16:49
> The the main difference maybe I am not using the auto configuration

Have you included `@EnableConfigurationProperties` in your configuration? You'll need this to ensure that `HealthEndpoint.setId()` is called with value from your `application.properties`.

**Comment by miggy8234** [comment] 2016-07-19 17:51
So I see the addition in version 1.3.3 and I guess the documentation is missing the `@EnableConfigurationProperties` to utilize this setting.

**Comment by philwebb** [comment] 2016-07-19 17:59
The documentation assumes that you're using auto-configuration.

**Comment by miggy8234** [comment] 2016-07-19 18:02
Will there be a version where this is not assumed?

**Comment by philwebb** [comment] 2016-07-19 18:10
I think that's likely to make the documentation much more difficult to digest for the majority of our users. If you don't want to use auto-configuration then you'll need to dig a little more into the code to see how to configure things.

**Closed** 2016-07-19 18:14 UTC
Labels: feedback-provided
