### ISSUE TITLE
PhysicalNamingStrategy Bean Confiugured on my code is not working 

### ISSUE THREAD

**Issue by Omololu98** [spring-projects/spring-boot#43504] opened 2024-12-13 16:07 UTC
I have configured my naming strategy, which works on my local machine but it does not work when I deploy to an EC2 instance.

Properties 
```
    private HashMap<String, Object> propertiesMap(){
        HashMap<String, Object> properties = new HashMap<>();
        properties.put("hibernate.hbm2ddl.auto", "none");
        properties.put("hibernate.naming.physical-strategy", "com.beamsolutions.beam.utils.services.DBNamingStrategyManager");
        properties.put("hibernate.temp.use_jdbc_metadata_defaults", "false");
        properties.put("hibernate.jdbc.lob.non_contextual_creation", "false");
        properties.put("hibernate.dialect", "org.hibernate.dialect.MySQL8Dialect");
        return properties;
    }
```

```
    @Bean(name="tenantEntityManager")
    @Primary
    public LocalContainerEntityManagerFactoryBean tenantEntityManager(EntityManagerFactoryBuilder builder,
                                                                   DataSource dataSource){
        return builder.dataSource(dataSource)
                .packages("com.beamsolutions.beam.hr_mgt",
                        "com.beamsolutions.beam.hse_mgt",
                        "com.beamsolutions.beam.inv_mgt",
                        "com.beamsolutions.beam.maint_mgt",
                        "com.beamsolutions.beam.ops_mgt",
                        "com.beamsolutions.beam.req_mgt",
                        "com.beamsolutions.beam.dashboard_mgt",
                        "com.beamsolutions.beam.repos_mgt")
                .properties(propertiesMap())
                .build();
    }
```
this is the bean where i use the configured jpa properties. I notice that the confgurations are basically ignored and the field names are not affected by the DBNamingStrategyManager

**Comment by wilkinsona** [comment] 2024-12-13 16:38
This doesn't look like a Spring Boot problem to me as you're configuring things yourself rather than relying on Boot's auto-configuration. Perhaps you can use trace-level logging or debug your application on EC2 to determine why it's apparently taking a different code path in that environment. I'm going to close this one for now. If the logging or debugging should that this is, in fact, a problem caused by Spring Boot, please add a comment to this issue containing that evidence and we can re-open it and take another look.

**Closed by wilkinsona** 2024-12-13 16:38 UTC
Labels: status: waiting-for-triage

**Comment by wilkinsona** [comment] 2024-12-13 16:44
I'd also double-check the names of the properties that you're using and that it is working on your local machine. AFAIK, the correct property name for the physical naming strategy is [`hibernate.physical_naming_strategy`](https://github.com/hibernate/hibernate-orm/blob/74f0839a947a9e2e837f35f7940f117687522eee/hibernate-core/src/main/java/org/hibernate/cfg/MappingSettings.java#L381).

**Comment by Omololu98** [comment] 2024-12-13 17:00
Thank you on the advise
