### ISSUE TITLE
gradle customize managed versions not work

### ISSUE THREAD

**Issue by jacky1193610322** [spring-projects/spring-boot#18657] opened 2019-10-18 13:22 UTC
In the document [spring-boot-document](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/asciidoc/managing-dependencies.adoc#reacting-to-other-plugins-dependency-management), the user can customize managed versions, for example ext['slf4j.version'] = '2.1.1',
but when i customize log4j2 versions, ext['log4j2.version'] = '2.11.0-p1.0.0', the log4j2 version is 2.11.0-p1.0.0(the version is inner company), it can impact spring-context version. 
![image](https://user-images.githubusercontent.com/16514353/67097061-f1ed9a80-f1eb-11e9-868b-140c8839b962.png)
but when the version is 2.11.0, it's ok.
my build.gradle
```
ext {
    springBootVersion = '1.5.10.RELEASE'
    jacksonVersion = '2.8.11'
    log4jVersion = '2.11.0-p1.0.0'
    env = System.getProperty("env") == null ? "development" : System.getProperty("env")
}

ext['jackson.version'] = '2.8.11'
ext['log4j2.version'] = '2.11.0-p1.0.0'
//ext['spring-framework.version'] = '4.3.18.RELEASE'


buildscript {

    ext {
        springBootVersion = '1.5.10.RELEASE'
    }

    repositories {
        // inner repository
    }

    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion")
    }

}

apply plugin: 'java'

repositories {
     // inner repository
}

sourceSets {
    main {
        java {
            srcDirs = ["src/main/java"]
        }
        resources {
            srcDirs = ["src/main/resources/base", "src/main/resources/$env"]
        }
    }
    test {
        java {
            srcDirs = ["src/test/java"]
        }
        resources {
            srcDirs = ["src/test/resources/base", "src/test/resources/$env"]
        }
    }
}

apply plugin: 'org.springframework.boot'
dependencies {
    compile "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    compile "org.apache.logging.log4j:log4j-core:${log4jVersion}"
    compile "org.apache.logging.log4j:log4j-api:${log4jVersion}"
    compile "org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"
}
```

my gradle version is Gradle 4.9.
so why it impacts the spring-context version?

**Comment by wilkinsona** [comment] 2019-10-18 13:44
The `log4j2.version` property is used to import Log4j 2's bom (`org.apache.logging.log4j:log4j-bom`). Given that everything's fine with the 2.11.0 version of the bom but broken with your private `2.11.0-p1.0.0` version, the private version must contain dependency management for some Spring Framework modules. Unfortunately, there's nothing that we can do about this in Spring Boot and you'll need to amend your private variant of the log4j 2 bom.

**Comment by jacky1193610322** [comment] 2019-10-18 14:20
Thank you, but the gradle dependencyInsight --dependency context command don't show the log4j depend on spring-context.
![image](https://user-images.githubusercontent.com/16514353/67102032-60832600-f1f5-11e9-92b1-e7d7651a841e.png)

**Comment by wilkinsona** [comment] 2019-10-18 16:24
There doesn't need to be a dependency between a Log4j module and a Spring Framework module for the problem to occur, just some unwanted dependency management in a bom. That said, I can't see any in the bom that you've now shared so I'm not longer certain that I understand what's going on. That's re-open this for now and see if we can reproduce the behaviour that you're seeing.

**Comment by wilkinsona** [comment] 2019-10-25 14:45
I've been unable to reproduce this, but I do not have the complete picture. I still suspect some faulty dependency management in your fork of Log4j2. For example, there may be some in `org.apache.logging.log4j:log4j` which is the parent of the bom. I've also just noticed that you are using Spring Boot 1.5.x which has reached the end of its life and is no longer supported.

Given that there's no sign of a problem with Spring Boot itself and the use of an unsupported version, I'm going to close this issue. If you would like us to spend some more time investigating, please provide a complete and minimal sample that reproduces the problem and that uses Spring Boot 2.1.x or 2.2.x and we can re-open the issue and take another look.

**Closed by wilkinsona** 2019-10-25 14:45 UTC
Labels: status: waiting-for-triage
