### ISSUE TITLE
Likely bug when using @Column(name = "QuizId")

### ISSUE THREAD

**Issue by 7--** [spring-projects/spring-boot#11644] opened 2018-01-16 15:23 UTC
Not sure if this is a spring boot issue or a hibernate or javax.persistance one. 

I have this simple application https://github.com/7--/GoldTeam-Tomcat/blob/master/src/main/java/com/revature/beans/Quiz.java

I'm specifying this classes get method with @Column(name = "QuizId"). However when running it's selecting "quiz_id" instead of "QuizId". "select quiz0_.quiz_id as quiz_id1_1_, quiz0_.name as name2_1_ from quiz quiz0_"

I grepped my project and "quiz_id" never occurs. I also cleaned, deleted and repulled my project.

**Comment by wilkinsona** [comment] 2018-01-16 15:42
Duplicate of #2129.

**Closed by wilkinsona** 2018-01-16 15:42 UTC
Labels: status: waiting-for-triage
