### ISSUE TITLE
spring-boot-maven-plugin:2.1.4.RELEASE:repackage finalName is not correct

### ISSUE THREAD

**Issue by gerogeforli** [spring-projects/spring-boot#16862] opened 2019-05-15 07:26 UTC
<build>
        <finalName>${project.artifactId}-${project.version}_${current.time}</finalName>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.12</version>
                <executions>
                    <execution>
                        <id>timestamp-property</id>
                        <goals>
                            <goal>timestamp-property</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <name>current.time</name>
                    <pattern>yyyyMMdd.HHmmss</pattern>
                    <timeZone>GMT+8</timeZone>
                    <regex/>
                    <source/>
                    <value/>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.1.4.RELEASE</version>
            </plugin>
        </plugins>
</build>

mvn package 
the finalName property ${current.time} not replaced by timestamp
The previous version is normal

**Comment by snicoll** [comment] 2019-05-15 08:02
@gerogeforli please take the time to search the issue tracker before reporting an issue as this one has been reported tree times already.

Duplicate of #16456

**Closed by snicoll** 2019-05-15 08:02 UTC
Labels: status: waiting-for-triage
