### ISSUE TITLE
IllegalAccessError when creating CGLIB proxies for package-private classes using Spring DevTools

### ISSUE THREAD

**Issue by sirianni** [spring-projects/spring-boot#7267] opened 2016-11-01 16:34 UTC
I hit this error using `gradle bootRun` when `spring-boot-devtools` is on the classpath:
```
o.s.aop.framework.CglibAopProxy : Unable to proxy method [...] because it is package-visible across different ClassLoaders: All calls to this method via a proxy will NOT be routed to the target instance.
<snip>
java.lang.IllegalAccessError: class Foo$$EnhancerBySpringCGLIB$$8345c360 cannot access its superclass Foo
```

If I remove `spring-boot-devtools`, the application starts fine.  I'm guessing this is due to the classloader architecture of `spring-boot-devtools`...

**Comment by snicoll** [comment] 2016-11-01 16:44
Do you have the same package in different jars and you are using package protected access across different jars?

**Comment by sirianni** [comment] 2016-11-01 16:50
No - in this situation I just have a single package-private class with an `@Transactional` annotation.

**Comment by snicoll** [comment] 2016-11-01 17:07
That's weird, can you share a sample that reproduces the issue please?

**Comment by sirianni** [comment] 2016-11-01 17:52
Yes, I will try to distill down to a trivial example.

**Comment by spring-issuemaster** [comment] 2016-11-09 07:11
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-11-16 07:11
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by mraible** [comment] 2016-11-17 20:12
Here's a simple example that demonstrates this issue:

`pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>demo</name>
  <description>Demo project for Spring Boot</description>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.2.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>1.8</java.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
```

`src/main/java/com/example/DemoApplication.java`
```java
package com.example;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Component;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}

@Entity
class Blog {

    @Id
    @GeneratedValue
    private Long id;
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Blog{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}

interface BlogRepository extends JpaRepository<Blog, Long> {
}

@Component
class BlogCommandLineRunner implements CommandLineRunner {

    @Override
    public void run(String... strings) throws Exception {
        System.out.println(repository.findAll());
    }

    @Autowired
    private BlogRepository repository;
}
```

Start it with `mvn spring-boot:run` and you'll see the following error:

```
Caused by: java.lang.IllegalAccessError: class com.example.$Proxy77 cannot access its superinterface com.example.BlogRepository
	at java.lang.reflect.Proxy.defineClass0(Native Method) ~[na:1.8.0_112]
	at java.lang.reflect.Proxy.access$300(Proxy.java:228) ~[na:1.8.0_112]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:642) ~[na:1.8.0_112]
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557) ~[na:1.8.0_112]
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230) ~[na:1.8.0_112]
	at java.lang.reflect.WeakCache.get(WeakCache.java:127) ~[na:1.8.0_112]
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419) ~[na:1.8.0_112]
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719) ~[na:1.8.0_112]
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:122) ~[spring-aop-4.3.4.RELEASE.jar:4.3.4.RELEASE]
```

Remove `spring-boot-devtools` as a dependency and everything starts fine.

**Comment by snicoll** [comment] 2016-11-17 21:24
> Start it with mvn spring-boot:run and you'll see the following error:

@mraible thanks for the sample but  that's not happening for me. I've pushed it in our [spring-framework-issues repo](https://github.com/spring-projects/spring-boot-issues/tree/master/gh-7267) (btw we prefer runnable sample over code in comments). 

What am I missing?

**Comment by spring-issuemaster** [comment] 2016-11-24 21:25
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mraible** [comment] 2016-11-28 23:49
@snicoll I'm not able to reproduce this issue anymore either. It was easy to reproduce a couple weeks ago. ¯\_(ツ)_/¯

**Closed** 2016-11-29 07:16 UTC
Labels: feedback-provided, waiting-for-triage

**Comment by kartoffelsup** [comment] 2017-06-21 15:24
I've ran into this today and submitted a PR to spring-boot-issues to reproduce the problem.

**Comment by wilkinsona** [comment] 2017-06-21 17:20
@kartoffelsup In your case the problem is because your application is split into multiple modules which can cause problems with DevTools' restart class loader.

The proxy for BarServiceImpl is loaded by the restart class loader but BarServiceImpl itself is loaded by the app class loader. A package is scoped to the class loader that defined it so, in this case, we end up with two different `org.bar.devtools.autoconfig.demo` packages and a package-private type in one of those package is not visible to a type in the other of those packages.

You can fix the problem by [adding bar to the restart class loader](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload) using `META-INF/spring-devtools.properties`:

```
restart.include.bar=/bar-.+\.jar
```

**Comment by kartoffelsup** [comment] 2017-06-21 19:45
Ahh, thank you @wilkinsona :)! Sorry for the inconvenience.
