### ISSUE TITLE
Move Spring Cloud features to Spring Boot Actuator

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-boot#2182] opened 2014-12-17 11:53 UTC
Hi, I am not aware of plans regarding Spring Cloud project but It has awesome features. It would be nice to include some features in `spring-boot-actuator`.

I believe that following features would be very nice specifically for Spring applications:
- `@RefreshScope` for Spring `@Beans` that want to be re-initialized when configuration changes
-  `/env` for updating `Environment` and rebinding `@ConfigurationProperties` and log levels
-  `/refresh` for refreshing the `@RefreshScope` beans

Any chances to move these features to Spring Boot Actuator?

**Comment by cemo** [comment] 2016-10-04 10:18
@philwebb @wilkinsona What do you think to target 1.5 this issue?

**Comment by wilkinsona** [comment] 2016-10-04 19:53
That almost certainly won't happen. The scope of 1.5 is intentionally very narrow. Also please note that #4353, which is probably a duplicate of this issue, was recently cut from the 2.0 plan.

**Comment by spencergibb** [comment] 2016-10-04 20:07
@wilkinsona yeah, seem like dups to me.

**Comment by philwebb** [comment] 2018-03-22 15:29
This seems mainly to be about refresh scope now which we can only tackle after we've extended our configuration properties support. I'm going to close this one for now then we can consider refresh scope again at a later date.

FWIW logging changes can now be made via an actuator endpoint.

**Closed by philwebb** 2018-03-22 15:29 UTC
Labels: status: on-hold
