### ISSUE TITLE
Support for ant wildcards in configuration properties

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#12993] opened 2018-04-27 19:34 UTC
I have the following configuration properties

```
@ConfigurationProperties(prefix = "dummy")
public DummyProperties {

    private Resource[] dummyFiles;

    // getters and setters
}

```

And then in my `application.properties`

```
dummy.dummy-files=classpath*:/com/example/dummy/*.json
```

When this is done then `DummyProperties#dummyFiles` contains a single `ServletContextResource`.
If you change the property to `classpath*:/com/example/dummy/single.json` then it works correctly.

I asked in the gitter channel and @snicoll said that you don't support this. However, I didn't understand if this is on purpose or it's just not implemented. If it is the first sorry for opening this issue and feel free to close it.

**Comment by snicoll** [comment] 2018-04-28 08:48
@filiphr we're using Spring Framework's property editor for this and I don't think than ant-style pattern is supported so I'd assume that this issue will have to move to the framework. But let's use the opportunity of this issue to figure out what we can do.

**Comment by filiphr** [comment] 2018-04-28 12:43
I am not sure what the property editor from Spring Framework is. One thing I know is that when the same expression is used in `@Value` everything works correctly.

For example doing:

```java
@Value("${dummy.dummy-files}")
private Resource[] resources;
```

Maybe different strategy is used for `@Value` and `@ConfigurationProperties`. To me they are "similar" and that is why I expected that to work.

Thanks for having a look at it.

**Comment by snicoll** [comment] 2018-04-28 16:24
> One thing I know is that when the same expression is used in @Value everything works correctly.

Well that's crucial to the report. It means then we have to configure something on the Spring Boot side as `@Value` is a Spring Framework feature.

**Comment by snicoll** [comment] 2018-05-02 06:57
It is interesting to see that [`@PropertySource` does not support that either](https://jira.spring.io/browse/SPR-16785)

**Comment by rfelgent** [comment] 2018-07-04 21:11
Hello,

are there any new information about progress ? I miss that feature "ant style path patterns" for configuration properties in my project, too. I use SB 1.5.10

**Comment by philwebb** [comment] 2018-07-04 21:17
@rfelgent There's not been any recent updates to the issue and since it's a relatively low priority nobody is actively working on it. It might be easer to fix this with Spring Boot 2.0 as much of the property binding support was rewritten. Even if we find a fix, I'm afraid we won't be adding this to Spring Boot 1.5.x.

**Comment by mbhave** [comment] 2019-07-01 16:07
I think this a duplicate of #15835. Feel free to reopen if it isn't.

**Closed by mbhave** 2019-07-01 16:07 UTC
Labels: type: enhancement

**Comment by filiphr** [comment] 2019-07-01 16:52
@mbhave yes #15835 is the same issue as this one. This one is an older issue though.
