### ISSUE TITLE
Can not checkout master branch on windows 

### ISSUE THREAD

**Issue by netroby** [spring-projects/spring-boot#11900] opened 2018-02-04 08:10 UTC
```
unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/DependencyManagementPluginActionIntegrationTests-helpfulErrorWhenVersionlessDependencyFailsToResolve.gradle: Filename too long
```

**Comment by wilkinsona** [comment] 2018-02-04 08:32
Duplicate of #10953 
Duplicate of #10868

**Closed by wilkinsona** 2018-02-04 08:32 UTC
Labels: status: waiting-for-triage

**Comment by netroby** [comment] 2018-02-04 08:33
The solution

E:\workspace\netroby\spring-boot [master ≡ +0 ~0 -1 !]
λ  git config --global core.longpaths true
