### ISSUE TITLE
'spring.data.mongodb.auto-index-creation=true' not working

### ISSUE THREAD

**Issue by GitLinko** [spring-projects/spring-boot#28478] opened 2021-10-29 10:04 UTC
I've added as per the documentation the following line to my application.properties:
`spring.data.mongodb.auto-index-creation=true`

However there is still no index created in my model-class that is annotated with @Document and the field with @Indexed.

If I overwrite autoIndexCreation in Java via: 
```
@Configuration
public class MongoConfig extends AbstractMongoClientConfiguration {

	@Override
    protected boolean autoIndexCreation() {               
        return true;
    }
}
```
the index is created. So this method works, but the application.properties entry doesn't work.

Using Spring Boot 2.5.5

**Comment by spring-projects-issues** [comment] 2021-11-05 10:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-11-12 10:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-11-12 10:31 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder

**Comment by jthomae1** [comment] 2021-11-17 14:56
Hi, I don't want to open a new issue, but I encountered the same problem and tested it with Spring Boot 2.5.3 and 2.5.5 like the opener.

If I overwrite `autoIndexCreation` in Java the indexes are created.

I always have a `AbstractMongoClientConfiguration` sub-class in my project. Is it necessary to override the method if I am using the sub-class?

**Comment by wilkinsona** [comment] 2021-11-17 14:58
Yes, it is. Please see my [comment above](https://github.com/spring-projects/spring-boot/issues/28478#issuecomment-954627106) that hopefully explains why that's the case.

**Comment by NicoHeller** [comment] 2021-11-20 06:57
The behavior is still the same in Spring Boot 2.6.0. spring.data.mongodb.auto-index-creation=true' has no effect. I am not using AbstractMongoClientConfiguration right now and nothing else is configured.

**Comment by wilkinsona** [comment] 2021-11-20 10:08
@NicoHeller No changes have been made so the same behaviour is to be expected. Thus far, as far as we know, everyone who has had this problem has defined their own `AbstractMongoClientConfiguration` which causes the auto-configuration to back off. If you are having the problem without anything defining a `AbstractMongoClientConfiguration` then, if you provide a sample that reproduces the problem, we can take a look.

**Comment by NicoHeller** [comment] 2021-11-20 10:37
> 

Sorry. I have simply forgotten the @Document annotation above the "Entity", if that is there everything works out of the box spring.data.mongodb.auto-index-creation=true

**Comment by wilkinsona** [comment] 2021-11-21 13:21
Thanks for letting us know. Good to hear you've got things working.

**Comment by NicoHeller** [comment] 2021-11-21 16:35
More precisely, also for other people, a POJO without @Document/@Entity annotation gets persisted into the MongoDb and the Collection is also created. Only the annotation with @Document causes the index creation.

**Comment by GitLinko** [comment] 2021-11-22 11:38
Just to add back to this as the OP.
I didn't figure out what caused the issue for me, but I couldn't recreate it in a demo project and the problem just disappeared after some further testing in my application...

**Comment by mgfzemor** [comment] 2023-03-01 23:35
Hi, just to contribute I was with my configs all set, but it was not working, then a did the following change in my `MongoConfig` :

Before (not creating indexes)
` @Bean(name = "QualifierName")
    public MongoTemplate mongoTemplate() {
        ConnectionString connectionString = new ConnectionString(this.uri);
        MongoDatabaseFactory clientDatabaseFactory = new SimpleMongoClientDatabaseFactory(connectionString);
        return new MongoTemplate(clientDatabaseFactory);
    }`

After (creating indexes) - just added `MappingMongoConverter`
` @Bean(name = "QualifierName")
    public MongoTemplate mongoTemplate(MappingMongoConverter converter) {
        ConnectionString connectionString = new ConnectionString(this.uri);
        MongoDatabaseFactory clientDatabaseFactory = new SimpleMongoClientDatabaseFactory(connectionString);
        return new MongoTemplate(clientDatabaseFactory, converter);
    }`

**Comment by karnsweta92** [comment] 2023-07-23 16:58
In one of my project I am also facing similar issue and AbstractMongoClientConfiguration class does not contain the method autoIndexCreation.
Kindly suggest me way. I have made true in application.properties and not using in "AbstractMongoClientConfiguration" in any of sub class.

**Comment by nikhilznr** [comment] 2023-10-30 05:36
I think below config works. not auto-index-creation=true

```
spring:
  data:
    mongodb:
      autoIndexCreation: true
```

**Comment by asgs** [comment] 2024-05-14 23:05
> I think below config works. not auto-index-creation=true
> 
> ```
> spring:
>   data:
>     mongodb:
>       autoIndexCreation: true
> ```

I can confirm. this works! Configuration like how it should be done :-)
