### ISSUE TITLE
SpringBootTest doesn't resolve @Validated @ConfigurationProperties

### ISSUE THREAD

**Issue by mkyrychenko** [spring-projects/spring-boot#16277] opened 2019-03-20 23:37 UTC
SpringBoot 2.1.3.RELEASE

I have following set:

```yaml
group:
    property: xyz
```

```java
@Configuration
@ConfigurationProperties("group")
public class GroupProperties {

    @NotBlank
    private String property;

    public String getProperty(){
        return this.property;
    }

    public void setProperty(final String property){
        this.property = property;
    }
}
```

```java
@Component
@EnableConfigurationProperties({GroupProperties.class})
public class GroupLoader implements ApplicationListener<ContextRefreshedEvent> {

    private final GroupProperties group;

    public GroupLoader(final GroupProperties group){
        this.group = group;
    }

    @Override
    public void onApplicationEvent(final @Nonnull ContextRefreshedEvent event) {
        // put group.parameter somewhere, e.g. in DB
    }
}
```

```java
@SpringBootTest
@RunWith(SpringRunner.class)
public class GroupTest {

    @Test
    public void should_read_group_parameter_from_db() {
        ....
    }
}
```

In normal cases, during application start, in the `GroupLoader` an autowired `GroupProperties` contains value from `application.yml` properties file.<br/>
But in `@SpringBootTest`, the instance of `GroupProperties` is autowired, but field `property` is null.<br/>
If `@Validated` and optionally `@NotBlank` annotations removed
from `GroupProperties` configuration, it autowires successfully in `GroupLoader`  and contains values also in `@SpringBootTest`.

Interesting is, that if I remove or comment `group.parameter` in `application.yml` out, 
the `ApplicationContext` fails to load (which is actually expected behaviour)

```bash
Caused by: org.springframework.boot.context.properties.bind.validation.BindValidationException: Binding validation errors on group
   - Field error in object 'group' on field 'parameter': rejected value [null]; codes [NotBlank.group.parameter,NotBlank.parameter,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [group.parameter,parameter]; arguments []; default message [parameter]]; default message [must not be blank]
```

Expected is, that `@Validated`-annotated `@ConfigurationProperties` are also resolved in `@SpringBootTest` integration tests.

Have I missed something?

Thank you in advance.

**Comment by mbhave** [comment] 2019-03-20 23:50
@mkyrychenko Can you provide a minimal sample that we can run to reproduce the issue?

**Comment by mkyrychenko** [comment] 2019-03-21 09:42
> @mkyrychenko Can you provide a minimal sample that we can run to reproduce the issue?

In which form should I provide this sample? Some project in GitHub or .zip with sources?
The minimal reproduce set is already described.

**Comment by snicoll** [comment] 2019-03-21 09:45
@mkyrychenko code in text is not really helpful as we'd have to copy all the bits one by one in the hope of reproducing what you're describing. A link to a github project or the zip of the project is what we're after.

**Comment by spring-issuemaster** [comment] 2019-03-28 09:49
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-04 09:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-04 09:48 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
