### ISSUE TITLE
InvalidPropertyException while binding configuration properties to Collection

### ISSUE THREAD

**Issue by artbasov** [spring-projects/spring-boot#9874] opened 2017-07-26 19:53 UTC
Plain Spring Boot 1.5.5.RELEASE App

`application.yml`:
```yaml
spring:
  application:
    name: Demo app
app:
  list:
   - aaaaa
   - bbbbbb
```
`configuration`:
```java
@SpringBootApplication
@ConfigurationProperties("app")
public class DemoApplication {
    Collection<String> list;

    public Collection<String> getList() {
        return list;
    }

    public void setList(Collection<String> list) {
        this.list = list;
    }
    @PostConstruct
    public void init() {
	System.out.println("=========================================");
	System.out.println("list: " + list);
	System.out.println("=========================================");
    }
    public static void main(String[] args) {
	SpringApplication.run(DemoApplication.class, args);
    }
}
```
I did debug a bit and it seems that in `org.springframework.beans.AbstractNestablePropertyAccessor#processKeyedProperty` there are missing checks for `Set` or `Collection` types, but in the call chain:
`org.springframework.beans.AbstractNestablePropertyAccessor#createDefaultPropertyValue` ->
`org.springframework.beans.AbstractNestablePropertyAccessor#newValue` ->
`org.springframework.core.CollectionFactory#createCollection(...)` we make a decision to create `LinkedHashSet` (see `CollectionFactory.java:180`)

Lookslike `spring-core` issue?

p.s.: Apart from desynchronization of those two pieces, wouldn't it have more sense to use `ArrayList` as general `Collection` ? That way if i added something in my .yml, i expect this to be in collection.

**Comment by philwebb** [comment] 2017-07-26 20:03
This is a long standing issue and one of the many drivers for rewriting property binding in 2.0. See #1415 for background.

Unfortunately it's too difficult to change this in 1.x, but you should try the latest 2.0 milestones and see if they solve the issue for you.

**Comment by philwebb** [comment] 2017-07-26 20:03
Duplicate of #1415

**Comment by wilkinsona** [comment] 2017-07-26 20:04
Alternatively, if you want the property's value to be a list, you need to tell it that. You can either initialise `list`:

```java
Collection<String> list = new ArrayList<>();
```

Or you can type it more specifically:

```java
    List<String> list;

    public List<String> getList() {
        return list;
    }

    public void setList(List<String> list) {
        this.list = list;
    }
```

Your sample works fine for me with either of those changes.

**Closed** 2017-07-26 20:03 UTC
Labels: status: duplicate

**Comment by artbasov** [comment] 2017-07-27 07:58
Thanks for your time, Phil. Sorry that i didn't found dublicate.

@wilkinsona, i actually tested it and yes, it works just fine, but the use-case is that i tried to do [3rd-party-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-3rd-party-configuration) and the library has exactly `Collection` and there is no reasons for them to change it just because of us. Not to worry, we workaround this for now.

But still, thanks for your time too!
