### ISSUE TITLE
Consider disabling auto-commit when wiring connection pool configs and setting hibernate.connection.provider_disables_autocommit for resource-local transactions

### ISSUE THREAD

**Issue by vladmihalcea** [spring-projects/spring-boot#9261] opened 2017-05-18 06:59 UTC
As I explained in [this article](https://vladmihalcea.com/2017/05/17/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/), there is a new optimization option we introduced in Hibernate 5.2.10 which makes a lot of sense for most Spring applications:

    <property name="hibernate.connection.provider_disables_autocommit" valaue="true"/>

With this property in place, Hibernate can delay the database connection acquisition until there is a JDBC Statement to execute. This is very convenient, as otherwise, the database connection is acquired when entering the `@Transactional` service method.

Now, to benefit from this optimization, you'd have to do 2 things:

1. To make sure you disable auto-commit when wiring up the connection pool Spring bean. For instance, HickariCP allows you to set it via `HikariConfiguartion#setAutoCommit(false)`.
2. To set up the `hibernate.connection.provider_disables_autocommit` when wiring a `JpaTransactionManager` or `HibernateTranscationManager`.

Enabling auto-commit by default is unlikely to break anything since, even if you don't do it, Hibernate does that anyway when starting a JPA Transaction.

**Comment by philwebb** [comment] 2017-05-18 16:18
Thanks @vladmihalcea, I'll flag this one for discussion and we'll talk about it on our next team call.

**Comment by philwebb** [comment] 2017-05-18 16:21
The `setAutoCommit` change will need careful consideration since it will affect all sorts of applications (not just Hibernate users).

**Comment by vladmihalcea** [comment] 2017-05-18 17:26
Sure. Maybe it's better to inspect the `DataSource` connection pool configuration and check if the user has disabled auto-commit explicitly. In this case, it's safe to apply this optimization since the user already opted for auto-commit=false.

**Comment by philwebb** [comment] 2017-05-25 14:42
Changing `setAutoCommit(false)` by default is a bit of a risky change. Perhaps we can detect auto-commit and use this to set the `hibernate.connection.provider_disables_autocommit` flag.

@vladmihalcea What happens if you set `hibernate.connection.provider_disables_autocommit` but your pool doesn't have `setAutoCommit(true)`?

**Comment by vladmihalcea** [comment] 2017-05-25 14:50
> What happens if you set hibernate.connection.provider_disables_autocommit but your pool doesn't have setAutoCommit(true)?

The problem is when the `hibernate.connection.provider_disables_autocommit` and the pool does not disable the auto-commit, meaning it doe snot call `setAutoCommit(false)`. In this case, Hibernate will not disable it either and every statement will be executed in auto-commit, hence you get no transaction unit-of-work.

However, since Spring Boot supports 3 connection pools: Hikari, DBCP2 and TomcatCP, it's possible to add to the `DataSourcePoolMetadata` interface a new method `isAutoCommit()`, and implement it for every supported CP. This way, Spring Boot can figure out if the CP has disabled auto-commit and configure the aforementioned hibernate property too.

**Comment by wilkinsona** [comment] 2017-09-22 08:06
I think I'm in favour of making this change. We know that the `DataSource` has been fully configured by the time we're configuring Hibernate so it should be safe to introspect the `DataSource` and see if it has auto commit disabled. If auto commit is disabled on the `DataSource` we could then safely pass that knowledge into Hibernate.

A possible danger is that a user changes the pool's auto-commit configuration at some later point while the application is running. Some connection pools may not even support doing so and, even if they do, it feels like an unusual thing for someone to do.

**Comment by wilkinsona** [comment] 2017-09-27 14:36
We're going to proceed with this in the manner proposed in #9737.

**Comment by wilkinsona** [comment] 2017-09-27 14:37
Duplicate of #9737.

**Closed by wilkinsona** 2017-09-27 14:37 UTC
Labels: for: team-attention, status: feedback-provided, status: waiting-for-triage

**Comment by itmightygroup** [comment] 2018-08-21 15:02
I was trying to use this for my application, but this doesn't seem to work for me. I am opening transaction using TransactionInterceptor and using HibernateTransactionManager and com.zaxxer.hikari.HikariDataSource as datasource.  I have set <property name="autoCommit" value="false"/> for datasource and <prop key="hibernate.connection.provider_disables_autocommit">true</prop> as the hibernate property. Event then transaction is getting opened when it is not required. 

5.3.1.Final version of hibernate-core is used for the above. Please let me in case I need to do something else or what is exact meaning of delaying in grabbing the connection.

Thanks in advance.

**Comment by snicoll** [comment] 2018-08-21 15:14
@itmightygroup as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask questions on StackOverflow.
