### ISSUE TITLE
Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@13acb0d1: startup date [Mon Aug 17 14:38:19 EST 2020]; 

### ISSUE THREAD

**Issue by impremkumar** [spring-projects/spring-boot#23033] opened 2020-08-21 06:10 UTC
Hello Team,

Spring boot application going down so often ( with in a day or two) with below info message. We are not seeing any other useful information from logs which could help us understand the issue better. Please note this application not yet went live so it is not taking any traffic from outside world and it is idle. You can find complete log information from application started to the time it went down at (https://github.com/impremkumar/application-logs/blob/master/ca-card-service-20200817.log). Kindly let me know if you need any other information. 

[INFO ] 2020-07-26 06:58:17.217 [Thread-6] AnnotationConfigEmbeddedWebApplicationContext - Closing [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@13acb0d1:] startup date [Wed Jul 22 04:20:54 EST 2020]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@65e579dc

**Comment by snicoll** [comment] 2020-08-21 08:12
@impremkumar we can't unfortunately provide you support on Spring Boot `1.x` that is EOL for over a year now. Even if you were using a supported version, the logs aren't nearly enough for us to understand the environment in which this application runs. The logs show a clean shutdown sequence so perhaps you're using an orchestration layer that determined the application was down? (perhaps due to the health endpoint if you're using that?). 

I am going to close this now. If you upgrade to a supported version of Spring Boot and have a small sample that reproduces the problem  in the form of a zip or a GitHub project, we can reconsider this issue. Please also note that questions have to be asked on StackOverflow (as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements).

**Closed by snicoll** 2020-08-21 08:12 UTC
Labels: status: waiting-for-triage
