### ISSUE TITLE
LiveReload not working since 2.5.2

### ISSUE THREAD

**Issue by slawekludwiczak** [spring-projects/spring-boot#27424] opened 2021-07-21 09:37 UTC
LiveReload Chrome plugin cannot connect to LiveReload server since Spring Boot 2.5.2. I believe that this is the issue #26920
With 2.5.0 everything is ok.
I'm using adoptopenjdk16, MacOS 11.4

To reproduce the problem, just create hello world application with web, thymeleaf and devtools dependencies.

2.5.0:
```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Connected to the target VM, address: '127.0.0.1:65237', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.0)

2021-07-21 11:13:14.364  INFO 11397 --- [  restartedMain] p.j.devtools.DevtoolsApplication         : Starting DevtoolsApplication using Java 16.0.1 on slaweks-macbook-pro.home with PID 11397 (/Users/slawek/Projects/courses/spring21/spring-mvc/devtools/target/classes started by slawek in /Users/slawek/Projects/courses/spring21/spring-mvc/devtools)
2021-07-21 11:13:14.366  INFO 11397 --- [  restartedMain] p.j.devtools.DevtoolsApplication         : No active profile set, falling back to default profiles: default
2021-07-21 11:13:14.406  INFO 11397 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-07-21 11:13:14.407  INFO 11397 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-07-21 11:13:15.022  INFO 11397 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-07-21 11:13:15.029  INFO 11397 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-07-21 11:13:15.029  INFO 11397 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2021-07-21 11:13:15.067  INFO 11397 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-07-21 11:13:15.067  INFO 11397 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 660 ms
2021-07-21 11:13:15.224  INFO 11397 --- [  restartedMain] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2021-07-21 11:13:15.303  INFO 11397 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2021-07-21 11:13:15.332  INFO 11397 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-07-21 11:13:15.342  INFO 11397 --- [  restartedMain] p.j.devtools.DevtoolsApplication         : Started DevtoolsApplication in 1.276 seconds (JVM running for 1.864)
2021-07-21 11:13:15.343  INFO 11397 --- [  restartedMain] o.s.b.a.ApplicationAvailabilityBean      : Application availability state LivenessState changed to CORRECT
2021-07-21 11:13:15.345  INFO 11397 --- [  restartedMain] o.s.b.a.ApplicationAvailabilityBean      : Application availability state ReadinessState changed to ACCEPTING_TRAFFIC
2021-07-21 11:13:33.654  INFO 11397 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-07-21 11:13:33.654  INFO 11397 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-07-21 11:13:33.655  INFO 11397 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
```
![livereload_250_1](https://user-images.githubusercontent.com/7830062/126465990-9e0018ab-eebb-4bb8-8d72-272b500af3c9.png)
<img width="1082" alt="livereload_250_2" src="https://user-images.githubusercontent.com/7830062/126466009-ed171de9-69ed-4687-b2e6-7cee999ef381.png">

2.5.2:
```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Connected to the target VM, address: '127.0.0.1:52795', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.2)

2021-07-21 11:28:51.526  INFO 11546 --- [  restartedMain] p.j.devtools.DevtoolsApplication         : Starting DevtoolsApplication using Java 16.0.1 on slaweks-macbook-pro.home with PID 11546 (/Users/slawek/Projects/courses/spring21/spring-mvc/devtools/target/classes started by slawek in /Users/slawek/Projects/courses/spring21/spring-mvc/devtools)
2021-07-21 11:28:51.528  INFO 11546 --- [  restartedMain] p.j.devtools.DevtoolsApplication         : No active profile set, falling back to default profiles: default
2021-07-21 11:28:51.570  INFO 11546 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-07-21 11:28:51.571  INFO 11546 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-07-21 11:28:52.274  INFO 11546 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-07-21 11:28:52.281  INFO 11546 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-07-21 11:28:52.281  INFO 11546 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.48]
2021-07-21 11:28:52.325  INFO 11546 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-07-21 11:28:52.326  INFO 11546 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 755 ms
2021-07-21 11:28:52.508  INFO 11546 --- [  restartedMain] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2021-07-21 11:28:52.598  INFO 11546 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2021-07-21 11:28:52.628  INFO 11546 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-07-21 11:28:52.638  INFO 11546 --- [  restartedMain] p.j.devtools.DevtoolsApplication         : Started DevtoolsApplication in 1.435 seconds (JVM running for 2.088)
```
![livereload_252_1](https://user-images.githubusercontent.com/7830062/126466622-dabf72fd-6c2a-4125-b9e0-ad31e326ba46.png)
<img width="1106" alt="livereload_252_2" src="https://user-images.githubusercontent.com/7830062/126466707-46a07802-e2cf-40d8-bd77-b723bc5f41ff.png">

**Comment by wilkinsona** [comment] 2021-07-21 09:41
This is a duplicate of https://github.com/spring-projects/spring-boot/issues/27147. It will be fixed in 2.4.9 and 2.5.3. If you have a moment, please try 2.4.9-SNAPSHOT or 2.5.3-SNAPSHOT (available from https://repo.spring.io/snapshot) and let us know if your problem remains.

**Closed by wilkinsona** 2021-07-21 09:41 UTC
Labels: status: waiting-for-triage
