### ISSUE TITLE
Possible confliction between external config and classpath config

### ISSUE THREAD

**Issue by astkaasa** [spring-projects/spring-boot#37024] opened 2023-08-18 04:13 UTC
Hi, I'm using external config combined with classpath config, the doc says "The list is ordered by precedence (with values from lower items overriding earlier ones)". My problem is my classpath (which consist directories like BOOT-INF META-INF and springboot things like JarLauncher) is the same directory with the current directory, so the `config` directory in current directory seems to be loaded as the classpath `config` package (not the external one). The true classpath config which located in `BOOT-INF/classes/` is ignored and not loaded at all (which has some default properties like spring.application.name, so I know it's not loaded correctly because of the immediate startup error)

My solusion is put all classpath folders in a seperate directory like boot/ inside curret directory (and point the classpath to it), or rename the external config file inside the `config` directory to application-default.properties (which is the default profile so I don't need to add another env variables).

Is this a bug or feature?

![image](https://github.com/spring-projects/spring-boot/assets/2796928/b25f8c07-6a59-41fd-bf86-e0e083838e55)

> 1. From the classpath
> The classpath root
> The classpath `/config` package
> 
> 2. From the current directory
> The current directory
> The `config/` subdirectory in the current directory
> Immediate child directories of the config/ subdirectory

**Comment by snicoll** [comment] 2023-08-18 11:21
Based on your description, it looks like you have a custom classpath setup that is causing this but I can't say for sure. If you want support, please share a minimal sample with us that we can run that reproduces what you've described. You can share it with us by attaching a zip to this issue or by pushing it to a separate GitHub repository.

**Comment by astkaasa** [comment] 2023-08-18 17:38
Here is the sample zip file.
[demo.zip](https://github.com/spring-projects/spring-boot/files/12381663/demo.zip)

This is the structure of the unzipped jar file with a config folder. I have two `application.properties` files, one in external config directory and one in classpath config directory.
![image](https://github.com/spring-projects/spring-boot/assets/2796928/db4d88bd-9a02-4e87-8acb-de32cd162ceb)

I add an `EnvironmentPostProcessor` to print all the property source names after loaded.
![image](https://github.com/spring-projects/spring-boot/assets/2796928/fc370564-4def-4301-8477-86ffb90f54ee)

Run the application using IDEA or vscode, both `application.properties` files are loaded correctly.
![image](https://github.com/spring-projects/spring-boot/assets/2796928/03306597-9cb3-4243-9de2-8a1ba8151de2)

Run maven to package the fat jar: `mvn clean package -Dmaven.test.skip=true -ntp`.

Run the application using `java -jar` inside the `target` folder, both `application.properties` files are loaded correctly.
![image](https://github.com/spring-projects/spring-boot/assets/2796928/6f8bb5ad-6413-44bb-9fe8-32cb6e4bb611)

Run the application using `org.springframework.boot.loader.JarLauncher` after unzipped the jar file into the `output` directory using `maven-antrun-plugin`, only the external config file is loaded, property `spring.application.name` is null.
![image](https://github.com/spring-projects/spring-boot/assets/2796928/bd55f50b-44f3-4771-89ad-3793524131b9)

Put application.properties directly inside the resources folder or rename one of the `application.properties` file to `application-default.properties` solve the problem.
![image](https://github.com/spring-projects/spring-boot/assets/2796928/87f5bad7-91b2-4a01-b7ed-4de814be486d)

**Comment by krishna-prasad-sharma** [comment] 2023-09-05 11:58
I want to work on this issue please assign it to me

**Comment by wilkinsona** [comment] 2023-09-05 13:19
Thanks for the offer, @krishna-prasad-sharma. As indicated by the `for: team-attention` label, @snicoll would like to discuss this with the rest of the team. No work can be done until that has happened.

**Comment by wilkinsona** [comment] 2023-09-08 09:53
Stephane and I discussed this today and it is working as designed. I'll try to explain.

When you launch the app with `java org.springframework.boot.loader.JarLauncher`, the working directory is on the classpath. This is java's standard behavior when you don't specify `-cp`. `JarLauncher` then creates Boot's class loader that adds `BOOT-INF/classes` to the classpath. You have a `config` directory at both `./config/` and `BOOT-INF/classes/config`. With an classpath that is effectively `.:BOOT-INF/classes`, both of these `config` directories are available at `classpath:config/`. When something occurs multiple times of the classpath, the first occurrence wins. As a result, your configuration in `./config/` is used and your configuration in `BOOT-INF/classes/config/` is ignored.

> My solusion is put all classpath folders in a seperate directory like boot/ inside current directory (and point the classpath to it)

This is what I would recommend. It avoids `./config` accidentally becoming unwanted classpath content.

**Closed by wilkinsona** 2023-09-08 09:53 UTC
Labels: for: team-attention, status: waiting-for-triage, status: feedback-provided

**Comment by astkaasa** [comment] 2023-09-12 06:12
Thanks a lot. I got it. Always avoid unnecessary directories/files added to the classpath.
