### ISSUE TITLE
Exception caused by using @JsonTest annotation with spring-boot-starter-test 1.4 snapshot

### ISSUE THREAD

**Issue by jasoncarreira** [spring-projects/spring-boot#6308] opened 2016-07-01 19:50 UTC
I'm trying to use the new @JsonTest annotation in spring-boot-starter-test 1.4 and I'm getting a weird error. It seems like the @JsonTest annotation depends on a class that doesn't get added to the classpath. Here's my test...

    @RunWith(SpringJUnit4ClassRunner.class)
    @JsonTest
    public class JsonSerializationTest {
    ...
    }

And here's the error:

    java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
      at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
      at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
      at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
      at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
      at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
      at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
      at java.lang.Class.createAnnotationData(Class.java:3521)
      at java.lang.Class.annotationData(Class.java:3510)
      at java.lang.Class.getAnnotation(Class.java:3415)

If I remove the @JsonTest annotation I get this error instead, because there's nothing setting up the ApplicationContext:

    Caused by: java.lang.IllegalArgumentException: Cannot load an ApplicationContext with a NULL 'contextLoader'.

It looks like it's these 2 imports in the org.springframework.boot.test.autoconfigure.json.JsonExcludeFilter that cause it:

    import org.springframework.boot.context.TypeExcludeFilter;
    import org.springframework.boot.jackson.JsonComponent;

**Comment by wilkinsona** [comment] 2016-07-01 21:37
http://stackoverflow.com/questions/38152336/getting-exception-from-jsontest-annotation-with-spring-boot-starter-test-1-4-sn

Can you please provide a sample that reproduces the problem?

**Comment by wilkinsona** [comment] 2016-07-02 05:41
The two classes you believe are missing are both new in Spring Boot 1.4. I believe this is a duplicate of #6307, but this time you have an old version of `spring-boot` on the classpath. As I said before, your best bet is to let Spring Boot's dependency management control the versions of your dependencies.

I'm going to close this as a duplicate of #6307. If it's not, please provide a sample that reproduces the problem and we can reopen the issue.

**Closed by wilkinsona** 2016-07-02 05:41 UTC
Labels: waiting-for-feedback
