### ISSUE TITLE
Default handler for "/" doesn't rewrite resource URLs

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#16546] opened 2019-04-12 10:06 UTC
With `spring-boot-starter-web` and `spring-boot-starter-thymeleaf`, the path "/" is by default mapped to the template "index.html".

However this is done in such a way that that resource URL rewriting isn't applied. Resolvers like `VersionResourceResolver` and `WebJarsResourceResolver` will have no effect.

Workaround is to explicitly define a controller mapping:
```java
@Controller
public class IndexController {
    @GetMapping("/")
    public String get() {
        return "index";
    }
}
```

**Comment by OrangeDog** [comment] 2019-04-12 10:47
Similarly, the default chain for "/**/favicon.ico" only has a `PathResourceResolver`, so it doesn't get e.g. a content hash for cache-busting.

**Comment by wilkinsona** [comment] 2019-04-15 13:55
I think this is a duplicate of #16309.

**Closed by wilkinsona** 2019-04-15 13:55 UTC
Labels: status: waiting-for-triage
