### ISSUE TITLE
Revisit JpaProperties

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#11112] opened 2017-11-22 16:01 UTC
It's got a lot of logic in it and it's a bit weird.

**Comment by wilkinsona** [comment] 2018-03-08 17:13
It also, via the nested `Naming` class, has a hard dependency on Hibernate (see #12408).

**Comment by snicoll** [comment] 2018-03-09 15:41
Duplicate of #1327

**Closed by snicoll** 2018-03-09 15:41 UTC
Labels: priority: normal, type: enhancement
