### ISSUE TITLE
spring-boot-starter-data-cassandra required as first dependency in dependency management

### ISSUE THREAD

**Issue by NuwanSameera** [spring-projects/spring-boot#9361] opened 2017-05-31 06:32 UTC
```xml
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-cassandra</artifactId>
</dependency>
```

This dependency need to put as first dependency in dependency management. Otherwise it throws `NoClassDefFoundError`.

Thank you.

**Comment by snicoll** [comment] 2017-05-31 07:38
There is no order concept in `dependencyManagement` (there is in `dependencies`). Rather than describing what you think is a solution, can you please describe the problem? Please share a sample that reproduces the `NoClassDefFoundError` you're experiencing.

**Comment by spring-issuemaster** [comment] 2017-06-07 07:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-06-14 07:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-06-14 07:38 UTC
Labels: status: waiting-for-triage
