### ISSUE TITLE
Spring Boot deployment on WLP (WebSphere Liberty) throws CWWKC0044W error

### ISSUE THREAD

**Issue by sw-samuraj** [spring-projects/spring-boot#11618] opened 2018-01-12 18:23 UTC
_Spring Boot_ application v. **2.0.0.M7** throws a following error during a deployment on the _WebSphere Liberty_ application server v. **17.0.0.4**.

```
[WARNING ] CWWKC0044W: An exception occurred while scanning class and annotation data. The exception was java.lang.RuntimeException
        at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
        at [internal classes]
.
```

There are used following _Gradle_ dependencies:

```groovy
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web:2.0.0.M7'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:2.0.0.M7'

    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat:2.0.0.M7'
}
```

An exclusion of the _Log4j_ transitive dependency from both `web` and `thymeleaf` starters can be used as a workaround:

```groovy
configurations {
    implementation {
        exclude group: 'org.apache.logging.log4j'
    }
}
```

**Comment by wilkinsona** [comment] 2018-01-12 19:31
Can you please explain why you have raised this issue against Spring Boot rather than WebSphere Liberty? Also, the message you have shared is a warning rather than an error. Does deployment actually fail. If you'd like us to spend some time investigating this issue, please spend some time describing why you think it's a problem in Spring Boot and providing complete details of the failure that occurs.

**Comment by sw-samuraj** [comment] 2018-01-12 21:12
@wilkinsona I raised this issue here for two reasons:

- The same application on the same _WLP_ version deploys without the exception for _Boot_ v. 1.5.9.
- _WLP_ 17.0.0.4 is a production release, whereas _Boot_ 2.0.0.M7 is a milestone release. Therefore I assume that _Boot_ is more volatile at given moment.

You are right that it's not an error - it's a runtime exception which is logged (by _WLP_) as a warning. It doesn't stop the deployment.

I'm not sure that this issue is a problem of _Spring Boot_ - my intention was just to bring it to attention. If it's not worth investigation, I'm fine to let it close. Otherwise, I can bring more information, or provide a sample project.

**Comment by wilkinsona** [comment] 2018-01-15 07:17
Thanks. I can’t tell if it’s worth investigation as Instill don’t know exactly what the problem is. Can you please provide complete details of the failure as requested above?

**Comment by NottyCode** [comment] 2018-01-16 18:37
The Liberty logs/messages.log file should contain full stack trace. That would help identify what the issue was that ASM hit.

**Comment by sw-samuraj** [comment] 2018-01-19 15:58
Here is the [messages.log](https://github.com/spring-projects/spring-boot/files/1647098/messages.log) file. Yes, it contains a full stack trace, but at least for me, there is no lead what is the real cause. I try to enable finer grain logging, if there will be something more meaningful.

**Comment by wilkinsona** [comment] 2018-01-19 16:34
Thanks. Unfortunately, the diagnostics aren't very helpful as they don't indicate what class file caused the problem. In the absence of any indication that this is a bug in Spring Boot I'm going to close this issue. If you pursue this with IBM and it transpires that a change in Spring Boot is necessary, we can reopen this issue.

**Closed by wilkinsona** 2018-01-19 16:34 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by jeanabraham** [comment] 2018-07-12 20:09
@wilkinsona i am running in the very same issue. Did you ever get to the root of this? Thanks!

**Comment by wilkinsona** [comment] 2018-07-13 10:20
I did not. We didn't hear anything more from @sw-samuraj so I assume that they solved the problem without a change in Spring Boot being needed. My suspicion remains that the problem's due to the version of ASM that Liberty is using for byte code processing. Spring Boot 1.5 produces Java 6-compatible byte code whereas 2.0 produces Java 8-compatible byte code.

**Comment by sw-samuraj** [comment] 2018-07-16 09:11
@jeanabraham No, I didn't catch the root case - I had set trace logging for _WLP_, but still no info about which class is causing the problem. We stuck with the workaround I had described at the top (_Log4j_ exclusion from `web` and `thymeleaf`).
