### ISSUE TITLE
setting registerShutDownHook on SpringApplication/Builder does not work as expected

### ISSUE THREAD

**Issue by LutzStrobel** [spring-projects/spring-boot#4640] opened 2015-11-30 08:18 UTC
We have a spring application as follows:

```
        SpringApplication app = new SpringApplication(Myeureka1Application.class);
                app.setRegisterShutdownHook(false);
                app.run(args);

```

We would expect that no shutdownhook will be registred, so that we can register an own extended shutDownHook. But instead the default shutDownHook will be registred.
The problem seems to result from the fact that there will be created one/more additional spring application/s and the original setting of registerShutDownHook will not be populated.

The reason why we want to register an own shutDownHook is that we want a micro service not to accept further requests but process the accepted requests until they are ready before the shutDown should complete.

**Comment by wilkinsona** [comment] 2015-11-30 09:41
It works for me. Are you sure you're not calling the static variant of `SpringApplication.run`, i.e. `SpringApplication.run(MyApplication.class, args)`?

If you'd like us to investigate further, please provide a simple sample project that reproduces the problem.

**Comment by LutzStrobel** [comment] 2015-11-30 20:12
I have created a sample project with the following maven dependencies:

```

  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>Angel.SR4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <dependencies>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-feign</artifactId>
    </dependency>

  </dependencies>

```
and an apllication class as follows:

```
@Configuration
@ComponentScan
@EnableAutoConfiguration
@EnableEurekaClient
@EnableFeignClients(basePackages = {"de.lstrobel.ms"})
@RestController
public class App {

    @RequestMapping("/")
    public String home() {
         return "Hello world";
    }

    public static void main(String[] args) {
        new SpringApplicationBuilder(App.class).registerShutdownHook(false).web(true).run(args);
    }

}

```

When I set a breakpoint inside 
```
 AbstractApplicationContext.registerShutDownHook(...)

```

the debugger stops and the shutdownhook will be registred.
Hope this helps.
Thanx
Lutz Strobel

**Comment by philwebb** [comment] 2015-11-30 20:34
Looks like this is a Spring Clould issue. The `BootstrapApplicationListener` is creating its own `SpringApplication` that always registers the hook.

Here's the stack trace:

```
Thread [main] (Suspended (breakpoint at line 799 in AbstractApplicationContext))	
	owns: AtomicBoolean  (id=21)	
	owns: AtomicBoolean  (id=22)	
	AnnotationConfigApplicationContext(AbstractApplicationContext).registerShutdownHook() line: 799	
	SpringApplication.run(String...) line: 296	
	SpringApplicationBuilder.run(String...) line: 139	
	BootstrapApplicationListener.bootstrapServiceContext(ConfigurableEnvironment, SpringApplication) line: 126	
	BootstrapApplicationListener.onApplicationEvent(ApplicationEnvironmentPreparedEvent) line: 75	
	BootstrapApplicationListener.onApplicationEvent(ApplicationEvent) line: 55	
	SimpleApplicationEventMulticaster.invokeListener(ApplicationListener, ApplicationEvent) line: 151	
	SimpleApplicationEventMulticaster.multicastEvent(ApplicationEvent) line: 128	
	EventPublishingRunListener.publishEvent(SpringApplicationEvent) line: 100	
	EventPublishingRunListener.environmentPrepared(ConfigurableEnvironment) line: 59	
	SpringApplication.run(String...) line: 286	
	SpringApplicationBuilder.run(String...) line: 139	
	HookApplication.main(String[]) line: 14	
```

And this is the line of code that probably needs to change:

https://github.com/spring-cloud/spring-cloud-commons/blob/1.0.2.RELEASE/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java#L109

**Comment by philwebb** [comment] 2015-11-30 20:36
Please track https://github.com/spring-cloud/spring-cloud-commons/issues/61 for a fix. Closing here since it's not really a Spring Boot issue.

**Closed by philwebb** 2015-11-30 20:36 UTC
Labels: waiting-for-feedback
