### ISSUE TITLE
GraalVM support for spring-boot

### ISSUE THREAD

**Issue by dheeraj29** [spring-projects/spring-boot#16677] opened 2019-04-28 11:59 UTC
Current GraalVM is able to generate a spring boot based hello-world app into native image.

https://github.com/oracle/graal/issues/348

But it gives an error while running the generated image. **Unable to determine code source archive**. So how to resolve this issue with spring boot.
Most issues currently raised and related to spring are expected to be resolved by GraalVM 1.0-RC17 (next release).

Tested with GraalVM 1.0-RC16  with spring boot 2.1 also. Same error appears.

**Comment by snicoll** [comment] 2019-04-28 12:01
Duplicate of #16261

**Closed by snicoll** 2019-04-28 12:01 UTC
Labels: status: waiting-for-triage
