### ISSUE TITLE
Actuator env endpoint renders entry in infinite loop when deployed to Weblogic

### ISSUE THREAD

**Issue by pmihalcin** [spring-projects/spring-boot#10820] opened 2017-10-30 11:13 UTC
When I deploy spring boot application to weblogic container and hit `/env` endpoint, I get response which contains entry:

```
"weblogic.management.server": {
	"mbeanHome": {
		"mbeanServer": {
			"mbeanHome": {
				"mbeanServer": {
					"mbeanHome": {
						"mbeanServer": {
							"mbeanHome": {
								"mbeanServer": {
									"mbeanHome": {
										"mbeanServer": {
...
```
This entry is more than 2000 lines long.

Spring Boot `1.5.7-RELEASE`

**Comment by wilkinsona** [comment] 2017-10-30 11:22
What version of Weblogic are you using?

**Comment by pmihalcin** [comment] 2017-10-30 11:46
Weblogic 12.1.3.0.0

**Comment by wilkinsona** [comment] 2017-10-30 20:38
Thanks. I can't reproduce this with 12.1.3.0. Can you please provide a small sample and step-by-step instructions for configuring WebLogic in such a way that the problem occurs?

**Comment by spring-issuemaster** [comment] 2017-11-06 20:39
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-11-13 20:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-11-13 20:42 UTC
