### ISSUE TITLE
prototype use AOP case metaspace leak

### ISSUE THREAD

**Issue by braveboo** [spring-projects/spring-boot#15627] opened 2019-01-05 16:04 UTC

**Comment by braveboo** [comment] 2019-01-05 16:08
In my project has a lot of prototype objects , when I use AOP(cglib) aspect in these prototype objects,I find metaspace alway increase, and when full gc occur, the meataspace size can't be reclaimed

**Comment by wilkinsona** [comment] 2019-01-10 12:15
Metaspace can't be reclaimed until the classes are unloaded, and classes aren't unloaded until their ClassLoader is garbage collected. `LaunchedURLClassLoader` will be referenced for the lifetime of the app so the GC and metaspace behaviour that you have described is to be expected.

It sounds like the problem, if indeed there is one, may be due to how the proxies for your prototypes are being created. Perhaps there's an opportunity to reuse a CGLib-generated class rather than creating a new one each time, but I can't tell from the information that you've provided thus far.

Can you please provide a minimal and complete sample project that reproduces the problem that you've described?

**Comment by braveboo** [comment] 2019-01-17 00:18
> Metaspace can't be reclaimed until the classes are unloaded, and classes aren't unloaded until their ClassLoader is garbage collected. `LaunchedURLClassLoader` will be referenced for the lifetime of the app so the GC and metaspace behaviour that you have described is to be expected.
> 
> It sounds like the problem, if indeed there is one, may be due to how the proxies for your prototypes are being created. Perhaps there's an opportunity to reuse a CGLib-generated class rather than creating a new one each time, but I can't tell from the information that you've provided thus far.
> 
> Can you please provide a minimal and complete sample project that reproduces the problem that you've described?

May be i find the bug, my springboot version is 1.4.1 and the related spring framework version is 4.3.0. 
I find the static class ClassLoaderData in the org.springframework.cglib.core.AbstractClassGenerator, the method:
public boolean allocateName(String name) {
    return this.reservedClassNames.putIfAbsent(name, true) != null;
} 
in class ClassLoaderData case the cglibclass version increase such as com.xxxx.service.xxxx$$EnhancerBySpringCGLIB$$7f2e2a4c_version.
and in spring framework version is 4.3.10，the method changed,the content is:
private final Set<String> reservedClassNames = new HashSet();
private final Predicate uniqueNamePredicate = new Predicate() {
            public boolean evaluate(Object name) {
                return ClassLoaderData.this.reservedClassNames.contains(name);
            }
};
so please help confirming my guess,thank you.

**Comment by wilkinsona** [comment] 2019-01-17 10:54
Spring Boot 1.4 is no longer supported. Please upgrade to the latest Spring Boot 1.5.x release. If that does not resolve your problem, please provide the minimal sample that I asked for above.

**Comment by spring-issuemaster** [comment] 2019-01-24 10:57
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-01-31 10:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-01-31 10:58 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
