### ISSUE TITLE
RelaxedDataBinder does not split Map keys with underscores

### ISSUE THREAD

**Issue by sfussenegger** [spring-projects/spring-boot#12136] opened 2018-02-20 14:50 UTC
When using relaxed property names (e.g. using POSIX compatible environment variables) the `RelaxedDataBinder` does not split `Map` keys correctly. 

I believe I've identified [RelaxedDataBinder.BeanPath.splitPath(String)](https://github.com/spring-projects/spring-boot/blob/25510452c39bbae794c3c840d39964270df34044/spring-boot/src/main/java/org/springframework/boot/bind/RelaxedDataBinder.java#L503) as the culprit. 

Example:

```
@Data
@ConfigurationProperties(value = "foo", ignoreUnknownFields = false)
public class RelaxedProperties {
	private Map<String, Value> bar;

	@Data
	public static class Value {
		private int qux;
		private String quux;
	}
}
```

this argument works `--foo.bar.baz.qux=42` while this environment variable won't: `foo_bar_baz_qux=42`:

```
    Property: foo_bar[baz_qux]
    Value: 42
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'org.example.RelaxedProperties$Value' for property 'bar[baz_qux]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.example.RelaxedProperties$Value' for property 'bar[baz_qux]': no matching editors or conversion strategy found
```

There's only one node returned by `splitPath(..)` for the environment variable while the CLI argument splits into three (withouth `foo`, the `@ConfigurationProperties` prefix)

**Comment by bclozel** [comment] 2018-02-20 15:16
[As mentioned in the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding), upper case format is recommended for environment variables, like `FOO_BAR_BAZ_QUX`. Could you confirm that this change works in your project?

Even if lower case might work in other instances, note that [as of Spring Boot 2.0, relaxed binding rules have been tightened](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#relaxed-binding). Adopting the preferred way right now should help.

**Comment by sfussenegger** [comment] 2018-02-20 15:34
Still the same problem: `RelaxedDataBinder.BeanPath(String path)` gets a path with `_` but only splits using `.`, therefore turning "BAZ_QUX" into the `Map` key

**Comment by bclozel** [comment] 2018-02-20 16:02
Ah indeed, sorry - this all comes down to mapping environment variables to Maps keys/values. Please [check out this comment](https://github.com/spring-projects/spring-boot/issues/9902#issuecomment-318848482) for more background on this.

You've pointed at the code line where this limitation is shown - OS might or might not support dots in env variables and designing a general rule for that mapping is hard.

As I've said, we've tightened those rules in Spring Boot 2.0 so your best choice is probably to use the solution described in that comment, or use `SPRING_APPLICATION_JSON` for complex configuration properties.

Let me know how things work out.

**Comment by sfussenegger** [comment] 2018-02-20 16:42
Thanks for your feedback. I understand that supporting map keys with underscores and relaxed binding causes this issue. There are certainly a bunch of ways around this limitation. We ended up customizing `SystemEnvironmentPropertySource` by simply replacing variable names with a known prefix.

**Comment by bclozel** [comment] 2018-02-21 08:50
Thanks for your feedback.
I'll close that as a duplicate of #9902.

**Closed by bclozel** 2018-02-21 08:50 UTC
Labels: status: feedback-provided, status: waiting-for-triage
