### ISSUE TITLE
Jackson configuration of date format doesn't seem to work

### ISSUE THREAD

**Issue by lazee** [spring-projects/spring-boot#2322] opened 2015-01-09 20:33 UTC
According to this documentation (http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) I should be able to configure the Jackson date format by configuring spring.jackson.date-format in application.properties. But this just doesn't seem to work.

**Comment by lazee** [comment] 2015-01-09 20:36
Forgot to mention that I'm running Boot 1.2.0. I will test on 1.2.1 now.

**Comment by lazee** [comment] 2015-01-09 21:38
Same issue with 1.2.1

These are the settings in my application.yml

spring:
  jackson:
    date-format: "YYYY-MM"

I have also tried with othere examples from the doc I linked to.

**Comment by wilkinsona** [comment] 2015-01-15 10:23
This seems similar to #2225. @lazee what dependencies does your app have where the date format configuration isn't working?

**Comment by wilkinsona** [comment] 2015-01-15 10:46
This works for me both with and without Spring HATEOAS/Spring Data REST on the classpath. @lazee Can you provide a small sample the reproduces the problem please?

**Comment by lazee** [comment] 2015-01-15 11:12
@wilkinsona Will do as soon as possible.

**Comment by wilkinsona** [comment] 2015-01-15 19:53
@lazee Are you, by any chance, trying to format of Joda `DateTime`?

**Comment by lazee** [comment] 2015-01-15 21:28
@wilkinsona No. I will try to reproduce it from a plain app now. It might be something in my project.

**Comment by wilkinsona** [comment] 2015-01-28 17:39
@lazee Any joy reproducing this will a plain app?

**Comment by wilkinsona** [comment] 2015-02-05 15:09
In the absence of an example of the failure, I'm going to close this. @lazee If you manage to reproduce this, please comment with the details and we'll re-open the issue.

**Closed by wilkinsona** 2015-02-05 15:09 UTC
Labels: waiting-for-feedback

**Comment by lazee** [comment] 2015-02-09 06:39
Hi @wilkinsona. Sorry that I haven't been following up on this one. I have done some testing now and I'm not able to reproduce the problem in a plain boot 1.2.1 setup. But I still have the problem in my original project. Really not sure what causes this, so I have to do some more testing. I will reopen this issue if I'm able to find what causes this.
