### ISSUE TITLE
Add property name of maven managed dependencies to documentation

### ISSUE THREAD

**Issue by mvitz** [spring-projects/spring-boot#19172] opened 2019-11-28 06:11 UTC
The current documentation contains a appendix with all current managed dependency versions at https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#dependency-versions

If there is the need to change one of these the current way, with maven, is to provide the matching property by yourself with the dedicated version. To find out the name of this property you have to look into the BOM POM. Maybe it would be a good idea to document the property names (or the algorithm) in the documentation as well.

If this sounds reasonable I'm willing to do the work and submit a PR.

**Comment by wilkinsona** [comment] 2019-11-28 07:08
Thanks for the suggestion. This is a duplicate of #16868.

**Closed by wilkinsona** 2019-11-28 07:08 UTC
Labels: status: waiting-for-triage
