### ISSUE TITLE
Fix code issues based on sonarcloud.io code quality metrics

### ISSUE THREAD

**Issue by igor-suhorukov** [spring-projects/spring-boot#11623] opened 2018-01-13 12:20 UTC
Do you use Continuous Code Quality tools like SonarQube in CI build? 

I try to inspect Spring Boot code with  [sonarcloud.io](https://sonarcloud.io/dashboard?id=org.springframework.boot%3Aspring-boot-build) and found some issues. Looks like possible resource leaks and so on.

**Comment by snicoll** [comment] 2018-01-13 14:24
Duplicate of #11624

**Closed by snicoll** 2018-01-13 14:24 UTC
Labels: status: waiting-for-triage
