### ISSUE TITLE
@EnableSpringDataWebSupport when using @WebMvcTest

### ISSUE THREAD

**Issue by jackstevenson** [spring-projects/spring-boot#9849] opened 2017-07-24 18:38 UTC
I have a controller and test that look like this:

```java
@Controller
public class IssueController {

    private final IssueRepository issueRepository;

    public IssueController(IssueRepository issueRepository) {
        this.issueRepository = issueRepository;
    }

    @GetMapping("/issues")
    public String listIssues(Pageable pageable, Model model) {
        model.addAttribute("issues", issueRepository.findAll(pageable));
        return "list-issues";
    }
}
```

```java
@RunWith(SpringRunner.class)
@WebMvcTest(IssueController.class)
public class IssueControllerTests {

    @Autowired
    private MockMvc mvc;

    @MockBean
    private IssueRepository issueRepository;

    @Test
    public void getIssuesPageShouldReturnOk() throws Exception {
        Page<Issue> issues = new PageImpl<Issue>(new ArrayList<Issue>(), new PageRequest(0, 10), 0);

        given(issueRepository.findAll(any(Pageable.class)))
                .willReturn(issues);

        mvc.perform(get("/issues"))
                .andExpect(status().isOk());
    }
}

```
and it's failing with the following exception:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is 
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.domain.Pageable]: Specified class is an interface
```

Unless I'm missing something--and I'm not sure if it's the recommended approach--but adding `@EnableSpringDataWebSupport` to the test class resolves the issue by configuring the `PageableHandlerMethodArgumentResolver`. It would be nice if this was auto-configured by the `@WebMvcTest` annotation in the same way that Spring Security is also auto-configured.

**Comment by wilkinsona** [comment] 2017-07-24 18:39
Duplicate of #9028

**Closed by wilkinsona** 2017-07-24 18:39 UTC
Labels: status: waiting-for-triage
