### ISSUE TITLE
Make run_user for the launch script configurable

### ISSUE THREAD

**Issue by obfischer** [spring-projects/spring-boot#10273] opened 2017-09-12 20:08 UTC
The run user (`run_user`) used in the launch script should be configurable.

I have some services written with Spring Boot (1.5.6) as an executable jar with an embedded launch script. The jar is owed by the root user (`root:root`) therefore the service runs as root.

Therefore should the user the application is running under be configurable.

**Comment by snicoll** [comment] 2017-09-12 20:37
Duplicate of #10275 - @obfischer no need to create an issue and a PR. A PR is enough, thanks!

**Closed by snicoll** 2017-09-12 20:37 UTC
Labels: status: waiting-for-triage
