### ISSUE TITLE
Spring cloud vault  Bootstrap configuration: Host must not be empty

### ISSUE THREAD

**Issue by heyitsaakash** [spring-projects/spring-boot#10389] opened 2017-09-23 09:28 UTC
I am getting an issue with Spring Vault Config. this is my boot strap file
spring.application.name=demo
spring.cloud.vault.host=localhost
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http
spring.cloud.vault.token=c8ad1dad-c7f9-7141-ffce-e1172b62dc70
spring.cloud.vault.uri=localhost:8200
spring.cloud.vault.connection-timeout=5000
spring.cloud.vault.read-timeout=15000

I ran the same thing fine for the Release 1.5, but for the current release i ran in the issue
eanInstantiationException: Failed to instantiate [org.springframework.cloud.vault.config.VaultBootstrapConfiguration$$EnhancerBySpringCGLIB$$3be9d21e]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Host must not be empty

Attaching the logs as well.
[Logs_Issue.txt](https://github.com/spring-projects/spring-boot/files/1326430/Logs_Issue.txt)

**Comment by wilkinsona** [comment] 2017-09-23 10:15
Please don't cross-post the same issue in two places. It just wastes people's time.

Duplicate of https://github.com/spring-cloud/spring-cloud-vault/issues/161.

**Closed by wilkinsona** 2017-09-23 10:15 UTC
Labels: status: waiting-for-triage

**Comment by heyitsaakash** [comment] 2017-09-23 10:55
sorry there we two different projects so i wasn't sure where to address the same.
