### ISSUE TITLE
Configure default transaction isolation when using hibernate

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#3301] opened 2015-06-21 13:55 UTC
Is it possible to have the equivalent of `spring.jta.bitronix.datasource.isolation-level` but with hibernate?

[EDIT: removed wrong link]

**Comment by snicoll** [comment] 2015-06-22 08:04
The problem is that we need to access the `HibernateJpaDialect` to inject the value. The only safe place to do so seems to be in `HibernateJpaVendorAdapter#createJpaVendorAdapter`

**Comment by arnosthavelka** [comment] 2015-07-01 13:01
Well I believe the correct place (to fix it) is `JpaProperties.Hibernate.getAdditionalProperties`. I will try to fix it...

**Comment by arnosthavelka** [comment] 2015-07-21 15:05
I played with this issue for a while and I believe this is not issue for Spring Boot (just to handle configuration properly), but for `spring-orm` project (JPA part). Adding configuration item "hibernate.connection.isolation" to `JpaProperties` (what I tried) is useless since it is not propagated to transaction (verified by tests and demo application).

The feature (configure isolation level for datasource) should be supported by ORM at the first place (as for Bitronix). SpringBoot has (for Bitronix) configuration bean `PoolingDataSourceBean` which extends `PoolingDataSource` from bitronix project (with such configuration option). It's not handled directly by SpringBoot.

So I recommend to close this issue and create new one in `spring-orm` project.

**Comment by Polve** [comment] 2015-07-21 15:19
It should be already supported: https://jira.spring.io/browse/SPR-11942

**Comment by arnosthavelka** [comment] 2015-07-24 15:35
@Polve The linked JIRA solve probably something else (correct transactional behavior regarding chosen isolation level). However I figured out how to solve this problem.The solution was quite easy and is usable for all JPA implementations since it is handled by `JpaTransactionManager` (and not `HibernateJpavendorAdapter`).

I created pull request #3598.

**Comment by snicoll** [comment] 2015-07-27 13:19
The related jira issue is to customize the isolation level on a per-transaction basis. It's not meant to be used to change the *default* isolation level (which is why is being asked here AFAIK).

Changing the default isolation level should be done at the connection pool level so I am afraid the PR does not go in the right direction.

**Comment by arnosthavelka** [comment] 2015-07-27 13:46
@snicoll Sorry, but I am confused from your last post.

To clarify it:
1. Is this request / issue correct? Therefore the request shall be fulfilled.
2. Is the "problem" is in my solution which is done on `TransactionManager` instead of `Datasource`? Therefore the fix shall be rewritten? I am OK with that (if suitable), it will be definitely more general solution. I was just trying to fix it in the JPA context (as the hint was `HibernateJpaDialect`).

**Comment by snicoll** [comment] 2015-07-27 13:50
I am not sure what @Polve wants to be honest. What I understand is a way to customize the default isolation level when Spring Boot auto-configures the connection pool. In that respect, the current PR is not right (and largely my fault since I (wrongly) pointed out to `HibernateJpaDialect` indeed).

**Comment by arnosthavelka** [comment] 2015-07-27 13:53
OK, then close/refuse my PR. I will try to fix it in the new proposed way.

**Comment by Polve** [comment] 2015-07-27 14:11
@snicoll Your understanding is correct: my goal is the ability to change the default transaction isolation application-wide

**Comment by snicoll** [comment] 2015-08-14 11:43
Can I suggest that we close this issue as each data-source implementation has a way to specify that value?

For instance, with the tomcat data-pool you'd do the following for `READ_UNCOMMITTED`:

```
spring.datasource.default-transaction-isolation-level=1
```

**Comment by arnosthavelka** [comment] 2015-08-15 13:33
@snicoll I honor spring for its simplicity, generalization, abstraction, etc. What are you proposing (as the reason for closing this issue) does not fit to this definition. 

I have an example:
1. developer is writing application to real AS (not just JAR with embedded web container)
2. therefore the production and stage have some AS (WLS, WAS, JBoss, etc.)
3. however the development environment can be just Tomcat (to enhance development speed)

So, does the developer really need to handle setting the default isolation level (for different environments and different datasource pools) himself?

I know that this is "not must" feature, but I think this is a pity to just throw it to trash.

Ad "...implementing DataSource is too extreme...") Well since Datasource is not extensible and does not support definition of this property than I chose wrapper pattern.

**Comment by snicoll** [comment] 2015-08-15 13:43
Take It easy. The issue is not closed. 

There is a way to specify the isolation level per datasource. There isn't a generic way and I am just wondering if we should offer a generic way of configuring that. 

What is the problem of using a data pool implementation setting ?

**Comment by arnosthavelka** [comment] 2015-08-17 10:53
Ad "What is the problem of using a data pool implementation setting?") I have several reasons:
1. The property is generated from sources (`org.apache.tomcat.jdbc.pool.DataSource` in our case). So it can be changed any time. I'm not sure where's the problem, but your example did not work for me. I had to use `spring.datasource.default-transaction-isolation=4` (without "-level" sufix)'.
2. I'm not sure what happens when configuration values is wrong (e.g. typo). Is it ignored/runtime failure/etc.?
3. **The developer has to investigate the solution for each connection pool. Your example is for Tomcat datasource. How is it for [Jetty](http://www.eclipse.org/jetty/documentation/current/jndi-datasource-examples.html) (8 examples for different Datasource Connection Pool),  WLS, WAS, etc.?**

Ad "I don't follow your example...") OK, my example was probably extreme. Honestly I would probably never set default isolation level in configuration at all (but rather use `@Transaction`). But someone may use this feature (as it is requested).

Ad "Take It easy...") No comment :smiley:

**Comment by philwebb** [comment] 2018-03-22 18:59
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Closed by philwebb** 2018-03-22 18:59 UTC
Labels: type: enhancement
