### ISSUE TITLE
JarLauncher failed to run the fat jar build with spring-boot-maven-plugin

### ISSUE THREAD

**Issue by zhenglinj** [spring-projects/spring-boot#9861] opened 2017-07-25 13:55 UTC
I create a self-defined jar named `ssgxftputils`. The effective pom like this:
```
<project ...>
	<parent>
		<groupId>com.ssgx</groupId>
		<artifactId>commons</artifactId>
		<version>1.0</version>
	</parent>
	<groupId>com.ssgx</groupId>
	<artifactId>ssgxftputils</artifactId>
	<version>1.0</version>

        <dependencies>
......
        </dependencies>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
		        <groupId>org.apache.maven.plugins</groupId>
		        <artifactId>maven-jar-plugin</artifactId>
		        <version>2.3.1</version>
		        <!-- <configuration>
		          <outputDirectory>${gxhub}\lib</outputDirectory>
		        </configuration> -->
		    </plugin>
        </plugins>
    </build>

</project>
```

And I use the jar package in my spring boot website project with pom.xml like this:
```
<project ...>
	<dependencies>
......
		<dependency>
			<groupId>com.ssgx</groupId>
			<artifactId>ssgxftputils</artifactId>
			<version>1.0</version>
		</dependency>
......
	</dependencies>

	<properties>
		<java.version>1.8</java.version>
		<start-class>com.ssgx.gxhubweb.Application</start-class>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>1.5.2.RELEASE</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
			</plugin>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

</project>
```

When I run the jar package `java -jar target\backend-1.0-SNAPSHOT.jar`, it throw the exception as below:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at org.springframework.boot.loader.jar.AsciiBytes.<init>(AsciiBytes.java:69)
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.load(CentralDirectoryFileHeader.java:95)
        at org.springframework.boot.loader.jar.CentralDirectoryParser.parseEntries(CentralDirectoryParser.java:68)
        at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:57)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:118)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:106)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:290)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by wilkinsona** [comment] 2017-07-25 14:58
This looks similar to #8707 which was caused by a corrupted jar file. I notice that you're using Spring Boot 1.5.2. In response to #8707, we improved the diagnostics in 1.5.3 (#8711).

Can you please try with the latest 1.5 release (1.5.4.RELEASE)? If that doesn't resolve your issue, please provide a small sample that reproduces the problem.

**Comment by zhenglinj** [comment] 2017-07-26 13:11
Yeah. I have read the problem #8707 and upgrade the spring-boot from 1.5.2.RELEASE to 1.5.4.RELEASE.

The custom jar ssgxftputils included the jar ssgxutils which include spark-assembly-*.jar package.

```
ssgxftputils --(include)--> ssgxutils --(include)--> spark-assembly-*.jar
``` 
The pom of ssgxutils as below.
```
<project ...>
	<parent>
		<groupId>com.ssgx</groupId>
		<artifactId>commons</artifactId>
		<version>1.0</version>
	</parent>
	<groupId>com.ssgx</groupId>
	<artifactId>ssgxutils</artifactId>
	<version>1.0</version>

        <dependencies>
......
        </dependencies>

</project>
```

When I run the jar package it throw execption as below.
```
$ java -jar target/backend-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/spark-assembly_2.10-1.6.0-cdh5.9.0.jar
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:109)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/spark-assembly_2.10-1.6.0-cdh5.9.0.jar'
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:252)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:104)
        ... 4 more
Caused by: java.lang.IllegalStateException: Zip64 archives are not supported
        at org.springframework.boot.loader.jar.CentralDirectoryEndRecord.getNumberOfRecords(CentralDirectoryEndRecord.java:124)
        at org.springframework.boot.loader.jar.JarFileEntries.visitStart(JarFileEntries.java:91)
        at org.springframework.boot.loader.jar.CentralDirectoryParser.visitStart(CentralDirectoryParser.java:88)
        at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:56)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:118)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:106)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:290)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
        ... 6 more
```

But the `BOOT-INF/lib/spark-assembly_2.10-1.6.0-cdh5.9.0.jar` is existing in the backend-1.0-SNAPSHOT.jar package.
```
$ jar tvf target/backend-1.0-SNAPSHOT.jar
......
107990653 Fri Oct 21 01:31:56 EDT 2016 BOOT-INF/lib/spark-assembly_2.10-1.6.0-cdh5.9.0.jar
......
```

**Comment by wilkinsona** [comment] 2017-07-26 13:40
Thanks. The reason for the failure is in the stack trace:

```
Caused by: java.lang.IllegalStateException: Zip64 archives are not supported
```

Unfortunately, Spark produces huge zip files that are in Zip64 format which Spring Boot doesn't support.

Duplicate of #2895

**Closed by wilkinsona** 2017-07-26 13:40 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by ibrahimkarayel** [comment] 2018-05-17 15:29
I have the similar issue. I'm using spring boot version 2 and spring boot maven plugin. 
for env, I'm working on windows.  When I call `java -jar myjarName` I get the below error.   I build my jar on a Linux env it also gave the same error.  But when I run with the `mvn spring-boot:run `or run in  IntelliJ IDEA  both work fine. I clean maven repo re-try it still failed.   
**decodeMsDosFormatDateTime**  throw exception because header value  return **0** for month.


`Exception in thread "main" java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
        at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
        at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
        at java.time.LocalDate.of(LocalDate.java:267)
        at java.time.LocalDateTime.of(LocalDateTime.java:336)
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.decodeMsDosFormatDateTime(CentralDirectoryFileHeader.java:130)
        at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.getTime(CentralDirectoryFileHeader.java:119)
        at org.springframework.boot.loader.jar.JarEntry.<init>(JarEntry.java:55)
        at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:252)
        at org.springframework.boot.loader.jar.JarFileEntries.access$400(JarFileEntries.java:45)
        at org.springframework.boot.loader.jar.JarFileEntries$EntryIterator.next(JarFileEntries.java:302)
        at org.springframework.boot.loader.jar.JarFileEntries$EntryIterator.next(JarFileEntries.java:286)
        at org.springframework.boot.loader.jar.JarFile$2.nextElement(JarFile.java:196)
        at org.springframework.boot.loader.jar.JarFile$2.nextElement(JarFile.java:187)
        at org.springframework.boot.loader.archive.JarFileArchive$EntryIterator.next(JarFileArchive.java:186)
        at org.springframework.boot.loader.archive.JarFileArchive$EntryIterator.next(JarFileArchive.java:171)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:84)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:70)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)`
