### ISSUE TITLE
Jolokia (or any @ServletEndpoint) does not work with EndpointRequest include/exclude

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#13089] opened 2018-05-07 21:20 UTC

**Comment by gmcouto** [comment] 2018-05-08 20:52
Sample
[defect-actuator-jolokia.zip](https://github.com/spring-projects/spring-boot/files/1985627/defect-actuator-jolokia.zip)

**Comment by gmcouto** [comment] 2018-05-08 20:53
If you have server.servlet.path property set on your application, all actuator endpoints will be moved to it accordingly, except the jolokia endpoints.

How the jolokia endpoint is:
http://host:port/context-path/actuator/jolokia

How the jolokia endpoint should be:
http://host:port/context-path/servlet-path/actuator/jolokia

Examples of other endpoints:
http://host:port/context-path/servlet-path/actuator/health
http://host:port/context-path/servlet-path/actuator/auditevents
http://host:port/context-path/servlet-path/actuator/beans

**Comment by gmcouto** [comment] 2018-05-09 16:09
this is a duplicate of:
https://github.com/spring-projects/spring-boot/issues/13106

Which I have made a pull request to fix it

**Comment by wilkinsona** [comment] 2018-05-09 16:40
This doesn't sound like a duplicate of #13106 to me. This issue is about `EndpointRequest` and configuring security for servlet endpoints. As I understand it, there's a problem with that code irrespective of the servlet path that's in use. #13106 concerns the servlet path not being considered by servlet endpoints.

**Closed as completed** 2018-05-09 19:05 UTC
Labels: type: bug
