### ISSUE TITLE
Depending on Jasper prevents resources from being loaded from META-INF/resources in nested jars

### ISSUE THREAD

**Issue by AlekseiMarkov** [spring-projects/spring-boot#2451] opened 2015-02-04 16:17 UTC
I have a very simple hello-world gradle application with spring boot and swagger-ui.
when I run an executable jar (java -jar test.jar) made by spring boot and try to reach the ui in browser, I got a bunch of FileNotFoundException:

```
ERROR 1621 --- [nio-1234-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.io.FileNotFoundException: Jar URL cannot be resolved to absolute file path because it does not reside in the file system: war:jar:file:/home/..../test/build/libs/test.jar!/lib/swagger-spring-mvc-ui-0.4.jar
    at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:212)
    at org.springframework.core.io.AbstractFileResolvingResource.getFileForLastModifiedCheck(AbstractFileResolvingResource.java:67)
    at org.springframework.core.io.AbstractResource.lastModified(AbstractResource.java:153)
    at org.springframework.core.io.AbstractFileResolvingResource.lastModified(AbstractFileResolvingResource.java:169)
    at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:229)
    at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
```

the application is located here https://github.com/AlekseiMarkov/swaggerSpringBootExample

**Comment by wilkinsona** [comment] 2015-02-04 16:45
What URL are you accessing to produce the `FileNotFoundException`? You application only appears to have a mapping for `/simple` and it only accepts `POST` requests. Accessing the root of the app (as it looks you've done in the output above) produces a 404.

**Comment by AlekseiMarkov** [comment] 2015-02-05 09:42
I start the application with 'java -jar test.jar --server.port=1234' and then tries to reach the application with 'http://localhost:1234/sdoc.jsp'. Browser shows the swagger page, so jsp is accessed, but all static js and css files are not loaded, because of FileNotFoundException I see in console of spring boot application

**Comment by pacey** [comment] 2015-02-05 10:36
I can confirm I am having the same issue:

java.io.FileNotFoundException: Jar URL cannot be resolved to absolute file path because it does not reside in the file system: war:jar:file:/home/james/Sandboxes/property-management/web/build/libs/property-management-web-1.3.3-SNAPSHOT.jar!/lib/swagger-spring-mvc-ui-0.4.jar

When I look in the built jar for my spring boot application the swagger-spring-mvc-ui jar exists where it is looking for it. Strange.

**Comment by wilkinsona** [comment] 2015-02-05 11:16
@AlekseiMarkov Thanks. That's the information I needed to reproduce the problem.

**Comment by wilkinsona** [comment] 2015-02-05 11:52
You should be aware that there are some [known limitations with using JSPs with an embedded container](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-jsp-limitations) and our [recommendation is to avoid using them](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-template-engines).

It looks to me like swagger-spring-mvc-ui-0.4 is intended to be a webjar. It'd [described as such](https://github.com/martypitt/swagger-springmvc#swagger-ui) in the README, however it's not packaged like a web jar. A web jar should be packaged with all of its resources beneath `META-INF/resources/webjars/{library}/{version}' whereas spring-mvc-ui has its content packaged in `META-INF/resources`. I suspect this isn't helping.

The root of the problem is that an attempt is being made to load a resource from a nested jar's `META-INF/resources` directory and it's failing as the nested jar can't be accessed directly on the file system. One way to work around this problem is to [configure Boot's loader to unpack the problematic jar](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-template-engines).

**Comment by AlekseiMarkov** [comment] 2015-02-05 12:09
Thank you for reply!
Yes, adding 
```
springBoot {
    requiresUnpack = ['org.ajar:swagger-spring-mvc-ui']
}
```
to build file solved the issue

**Comment by pacey** [comment] 2015-02-05 13:53
Thanks for the reply, this fixes the issue nicely!

**Comment by wilkinsona** [comment] 2015-02-05 14:06
When Jasper's on the classpath, `TomcatEmbeddedServletContainerFactory` configures Tomcat with `StoreMergedWebXmlListener`. This listener adds a `JarWarResourceSet` for each jar in the executable archives `lib` directory. This makes files in `META-INF/resources` of those jars available via the servlet context, however `AbstractFileResolvingResource` chokes on the URLs for such resources as it can't figure out what the underlying file is to query its last modified time.

**Comment by wilkinsona** [comment] 2015-02-05 14:35
Reproduction: https://github.com/spring-projects/spring-boot-issues/tree/master/gh-2451

**Comment by snicoll** [comment] 2017-01-12 15:01
The repro project works fine with 1.4 so I suggest to close this one.

**Closed by snicoll** 2017-01-12 15:01 UTC
