### ISSUE TITLE
Incomplete Jetty dependency management can lead to a mixture of versions being used

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#9010] opened 2017-04-26 19:12 UTC
http://stackoverflow.com/questions/43639508/nosuchmethoderror-org-eclipse-jetty-websocket-server-websocketserverfactory-in/43642662#43642662

**Comment by snicoll** [comment] 2017-05-03 10:25
@wilkinsona isn't that a duplicate of #9009 ?

**Comment by wilkinsona** [comment] 2017-05-03 11:07
This issue is Jetty and #9009 is Jersey

**Comment by wilkinsona** [comment] 2017-05-04 14:33
`jetty-monitor` doesn't exist in Jetty 9.4 so we need to drop the dependency management for it.

**Closed** 2017-05-04 14:38 UTC
Labels: priority: normal, type: bug
