### ISSUE TITLE
Migration guide missing crucial change

### ISSUE THREAD

**Issue by sanderino666** [spring-projects/spring-boot#11850] opened 2018-01-30 16:57 UTC
Hi guys,

We are trying out the Spring Boot migration from 1.5.9 to 2.0.0.M7 and we noticed a change in the documentation which isn't mentioned in the migration guide but is actually pretty substantial and worthy of mentioning.

**Spring boot 1.5.9**
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files

> When custom config locations are configured, they are used **in addition** to the default locations

**Spring boot 2.0.0**
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config-application-property-files

> When custom config locations are configured by using spring.config.location, they **replace** the default locations

It took us a while to figure out why our properties from the classpath aren't loaded when setting the `spring.config.location` so I would imagine other people will encounter the same problem.

BTW: Looking forward to the RC1 :). Spring boot rocks!

Regards,

Sander

**Comment by snicoll** [comment] 2018-01-30 17:00
It is actually described in [the release notes for M6](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M6-Release-Notes#configuration-location)

The migration guide is still in progress. Duplicate of #10313

**Closed by snicoll** 2018-01-30 17:00 UTC
Labels: status: duplicate

**Comment by bclozel** [comment] 2018-01-31 12:39
Done [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#configuration-location). Thanks for the reminder!
