### ISSUE TITLE
spring boot All version log output to file contents are incomplete at windows system

### ISSUE THREAD

**Issue by pog2g** [spring-projects/spring-boot#17629] opened 2019-07-25 08:10 UTC
The console print log content is inconsistent with the file record, and the file record log content is missing a lot, or even not output to a file

The log configuration:

```yml
logging:
  level:
    root: ${app.log-root-level:debug}
  file: logs/${spring.application.name}.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
debug: true
```

**Comment by snicoll** [comment] 2019-07-25 08:22
@pog2g your yaml configuration is not indented properly so it's hard to figure out what you've actually configured. I am not sure why Windows was mentioned nor what the inconsistency is. 

To help us move forward, please edit your description to indent the yaml file properly, you can use "```" at the beginning and the end to format it. Please share a concrete example of the inconsistency, a sample we can run ourselves would be ideal.

**Comment by philwebb** [comment] 2019-07-25 09:34
I've edited the original comment to apply formatting to YAML but I still thing we need a sample here to show exactly what you mean.

**Comment by pog2g** [comment] 2019-07-25 16:04
Console logs sometimes stop output to files on Windows systems, but Linux works fine. Here are the key parts of the configuration file(application.yaml):
```
# spring配置
spring:
  application:
    name: test
  datasource:
    url:  jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
  servlet:
    context-path: /test
# 日志配置
logging:
  level:
    root: debug
  file: logs/${spring.application.name}.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
debug: true
```

**Comment by philwebb** [comment] 2019-07-25 18:15
@pog2g Thanks for the extra information but without an actual sample application that we can run I fear we may end up not really understanding the issue. If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2019-08-01 18:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-08-08 18:16
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-08-08 18:16 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
