### ISSUE TITLE
Split autoconfiguration features (e.g. ConditionalOnProperty) in an independent module

### ISSUE THREAD

**Issue by abelsromero** [spring-projects/spring-boot#14342] opened 2018-09-07 08:57 UTC
_v 1.5.2_
We are building some custom modules following spring-boot conventions like:
* Provide `@EnableXXX` annotations with nice defaults.
* Use predefined property keys for configuration.
* Provide `enabled` flags in properties to disable certain components.

But to use things like `@ConditionalOnProperty(value = "my.feature.enabled", havingValue = "true")` we need to import `spring-boot-autoconfigure` which contains lots of preconfigurations (amqp, aop, batch, cache, cassandra, mongo...) that clash with other modules and are (imho) unrelated to the features that we need from the jar.

So, it would be nice if bean configuration features like `Conditional***` be available in a separated library.

**Comment by wilkinsona** [comment] 2018-09-07 09:02
This is a duplicate of https://github.com/spring-projects/spring-boot/issues/10628. Please comment on that issue if you would like use to reconsider.

**Closed by wilkinsona** 2018-09-07 09:02 UTC
Labels: status: waiting-for-triage
