### ISSUE TITLE
activiti and spring boot

### ISSUE THREAD

**Issue by jisqaqov** [spring-projects/spring-boot#8131] opened 2017-01-29 07:32 UTC
Good day. When i try to deploy my activiti diagram in spring boot i have got in OS windows the following error:

```
Caused by: org.xml.sax.SAXParseException; systemId: jar:file:/C:/BSB/work/Проекты/platform/code/spring-platform/build/libs/spring-platform-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/activiti-bpmn-converter-5.22.0.jar!/org/activiti/impl/bpmn/parser/BPMN20.xsd; lineNumber: 15; columnNumber: 70; src-resolve: Cannot resolve the name 'extension' to a(n) 'element declaration' component.
```

But in OS ubuntu i do not encounter such error. There is a bug in my opinion in spring boot tomcat configurations. Could you please consider my problem.

**Comment by wilkinsona** [comment] 2017-01-29 08:54
Why do you think it's a bug in how Spring Boot configures Tomcat? From what you've shown it's not clear that Tomcat is involved at all. If you'd like us to spend time considering your problem, please spend some time describing it in detail and providing a sample that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2017-02-05 08:56
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-02-12 08:56
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-02-12 08:56 UTC
Labels: status: waiting-for-triage
