### ISSUE TITLE
Health probes response changes when additional-path specified

### ISSUE THREAD

**Issue by igr** [spring-projects/spring-boot#42057] opened 2024-08-29 15:14 UTC
SpringBoot v3.3.3

I added actuator and have the following configuration:

```yaml
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
      group:
        live:
          additional-path: server:/healthz
```

It provides the following endpoints:

+ /actuator/health - returns the full health status
+ /healthz - same as above
+ /actuator/health/liveness - returns just liveness information
+ /actuator/health/readiness - returns just readiness information

This is ok. Now, I want to add additional paths for liveness and readiness probes:

```yaml
management:
  endpoint:
    health:
      group:
        live:
          additional-path: server:/healthz
        liveness:
          additional-path: server:/livez
        readiness:
          additional-path: server:/readyz
```

This configurations adds two endpoints: `/livez` and `/readyz`.

However, these new endpoints are now returning the **full** health status, just as the `health` endpoint.

Expected behaviour is of new additional paths is to return just the probes status.

**Comment by bclozel** [comment] 2024-08-29 15:31
I think this is a duplicate of #40268

**Closed by bclozel** 2024-08-29 15:31 UTC
Labels: status: waiting-for-triage

**Comment by igr** [comment] 2024-08-29 15:55
@bclozel 

Please note that the setting in the https://github.com/spring-projects/spring-boot/issues/40268 just _filters_ the output and still _changes_ it.

Before, with the first setting, the response of probes is:

```json
{
  "status": "UP"
}
```

After the probes configuration set as specified in the linked ticket, the response is:

```json
{
  "status": "UP",
  "components": {
    "livenessState": {
      "status": "UP"
    }
  }
}
```

This is NOT the same. If I configure a probe, I would not expect the output to change like this.

**Comment by igr** [comment] 2024-08-29 15:57
Using: `management.endpoint.health.probes.add-additional-paths=true` works as expected. Thanx
