### ISSUE TITLE
Make HibernateJpaConfiguration public

### ISSUE THREAD

**Issue by httpdigest** [spring-projects/spring-boot#11357] opened 2017-12-15 08:24 UTC
I have the use-case of setting a Hibernate Interceptor on the Hibernate Session Factory. This Interceptor must also be a Spring-managed bean (i.e. not just the class name for Hibernate to instantiate).
Searching for how to do this it looks like the EntityManagerFactory must be given the Interceptor Bean under the property "hibernate.ejb.interceptor".
Now, looking into how Spring Boot actually creates the EntityManagerFactory, it seems that it is doing so inside the `org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration` using the Bean definition method `entityManagerFactory()`. This class provides the basic implementation of the Bean and the implementation calls into a certain `customizeVendorProperties()` which can be overwritten. And it is being overwritten by `org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration` which is the actual class being used by Spring.

So I reckon that I would want to create a new `@Configuration` class extending from `org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration` in order to further augment the custom vendor properties by overriding `customizeVendorProperties()` and inserting my Hibernate Interceptor property. The only thing is: that class which I need to override is package-priate.

I could of course just as well override the base class `org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration` and override its `customizeVendorProperties()`. The downside of that however is, that I would miss out on all the good stuff done by the `org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration` subclass.

Of course, I can define my own `LocalContainerEntityManagerFactoryBean`, but that leads to a whole host of other problems, mainly being: I have to basically override _every_ single other bean as well and copy/paste code from the Spring-provided bean methods in order for the application to still work as before. Mind you that my actual _only_ use-case is to add that Hibernate Interceptor to an otherwise completely untouched configuration.

My preferred way of doing all of this would therefore be to be able to extend from `org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration` and simply override `customizeVendorProperties()`, but that is simply not possible because the class is package-private.

In our current implementation I ended up defining a custom class in the same package `org.springframework.boot.autoconfigure.orm.jpa`, looking like the following, but that surely should not be the solution:

```Java
@Configuration
public class CustomHibernateJpaConfiguration extends HibernateJpaConfiguration {
	CustomHibernateJpaConfiguration(DataSource dataSource, JpaProperties jpaProperties,
			ObjectProvider<JtaTransactionManager> jtaTransactionManager,
			ObjectProvider<TransactionManagerCustomizers> transactionManagerCustomizers,
			ObjectProvider<Collection<DataSourcePoolMetadataProvider>> metadataProviders,
			ObjectProvider<List<SchemaManagementProvider>> providers,
			ObjectProvider<PhysicalNamingStrategy> physicalNamingStrategy,
			ObjectProvider<ImplicitNamingStrategy> implicitNamingStrategy) {
		super(dataSource, jpaProperties, jtaTransactionManager, transactionManagerCustomizers, metadataProviders,
				providers, physicalNamingStrategy, implicitNamingStrategy);
	}
	@Autowired
	private MyCustomInterceptor myCustomInterceptor;
	protected void customizeVendorProperties(Map<String, Object> vendorProperties) {
		super.customizeVendorProperties(vendorProperties);
		vendorProperties.put("hibernate.ejb.interceptor", myCustomInterceptor);
	}
}
```

**Comment by snicoll** [comment] 2017-12-15 08:46
Duplicate of #11211

**Closed by snicoll** 2017-12-15 08:46 UTC
Labels: status: waiting-for-triage

**Comment by httpdigest** [comment] 2017-12-15 09:06
Sorry for double-posting and thanks for hinting to that issue!
