### ISSUE TITLE
@Transactional annotation in Spring

### ISSUE THREAD

**Issue by SwapnaRavi21** [spring-projects/spring-boot#21435] opened 2020-05-13 12:01 UTC
Hi
I have 2 transactions which accepts same input as below.

insert/update to Table A (int ID)
if above is success then insert to Table B (int ID)

If table B insert fails, the insert/updates to Table A should NOT roll back.
But if insert/update to table A fails, insert to table B should not happen.

How do I achieve with @transactional propagation & isolation levels?

Thanks
Swapna R

**Comment by wilkinsona** [comment] 2020-05-13 12:05
This looks to be a duplicate of https://github.com/spring-projects/spring-boot/issues/21430, just without the mention of MyBatis. As with #21430, this isn't the right place for this sort of question. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Closed by wilkinsona** 2020-05-13 12:05 UTC
