### ISSUE TITLE
Fat jar classloading issue with relative path

### ISSUE THREAD

**Issue by tblondeel** [spring-projects/spring-boot#8145] opened 2017-01-31 10:20 UTC
As of Spring Boot 1.4.2 (up to 1.5.1) it seems that loading a resource from the classpath via a relative path doesn't work with a fat jar.

I've created a sample application to illustrate the problem. Just execute the fat jar made with the Gradle plugin with Spring Boot 1.4.1 versus a newer version.
[fatjar.zip](https://github.com/spring-projects/spring-boot/files/741635/fatjar.zip)

**Comment by wilkinsona** [comment] 2017-02-02 13:54
This is a duplicate of #7581. See [this comment](https://github.com/spring-projects/spring-boot/issues/7581#issuecomment-265515992) in particular for an explanation of why the behaviour has changed and why we want to keep it the way it is now.

**Closed by wilkinsona** 2017-02-02 13:54 UTC
Labels: status: waiting-for-triage
