### ISSUE TITLE
Property binder does not allow special characters in map keys

### ISSUE THREAD

**Issue by jwbennet** [spring-projects/spring-boot#14017] opened 2018-08-08 14:12 UTC
We have noticed an issue in Spring Boot 2.x when we bind properties to an `@ConfigurationProperties` bean which is not working like we expect.  If we bind our configuration into a map it will strip special characters from the keys of the map.  Here's a minimal example:

### application.yml
```yml
demo.properties:
  foo+bar: baz
  foo@bar.com: qux
```

### DemoApplication.java
```java
@SpringBootApplication
@EnableConfigurationProperties(DemoApplication.DemoProperties.class)
public class DemoApplication implements CommandLineRunner {

    @Autowired
    private Environment environment;
    @Autowired
    private DemoProperties demoProperties;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("Environment foo+bar = " + environment.getProperty("demo.properties.foo+bar"));
        System.out.println("Environment foo@bar.com = " + environment.getProperty("demo.properties.foo@bar.com"));
        System.out.println("Property map = " + demoProperties.getProperties());
    }

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @ConfigurationProperties("demo")
    public static class DemoProperties {

        private Map<String, String> properties;

        public Map<String, String> getProperties() {
            return properties;
        }

        public void setProperties(Map<String, String> properties) {
            this.properties = properties;
        }
    }
}
```

If you run this with Boot 1.5.x the following is printed:

```
Environment foo+bar = baz
Environment foo@bar.com = qux
Property map = {foo+bar=baz, foo@bar.com=qux}
```

The last line above is the most important since it shows the difference when we run the same thing with Boot 2.0.4.RELEASE:

```
Environment foo+bar = baz
Environment foo@bar.com = qux
Property map = {foobar=baz, foobar.com=qux}
```

You can see the `+` and `@` symbols were stripped from the keys in the map.  The values are stored properly in the `Environment`, but are being stripped when they are bound into an `@ConfigurationProperties` bean.  Is this expected in the new version?

**Comment by mbhave** [comment] 2018-08-08 18:01
Duplicate of #13404. See [this comment](https://github.com/spring-projects/spring-boot/issues/13404#issuecomment-395307439) for adding map keys with special characters.

**Closed by mbhave** 2018-08-08 18:01 UTC
Labels: status: waiting-for-triage
