### ISSUE TITLE
LoggerContext changes when using Spring Cloud, eliminating Logback metrics

### ISSUE THREAD

**Issue by jkschneider** [spring-projects/spring-boot#13077] opened 2018-05-05 02:34 UTC
See https://github.com/micrometer-metrics/micrometer/issues/564.

It seems from the OP's description that every time the context is refreshed, the Logback turbo filter list is reset. His workaround is to rebind Logback metrics on each event in a `ApplicationListener<ContextRefreshedEvent>`.

Any thoughts?

**Comment by jkschneider** [comment] 2018-05-05 02:35
There's also a potentially related issue in sc-netflix: https://github.com/spring-cloud/spring-cloud-netflix/issues/2830.

cc / @spencergibb

**Comment by spencergibb** [comment] 2018-05-05 02:41
Doesn't even need refresh with spring cloud commons, just having spring cloud stream does it https://github.com/spring-cloud/spring-cloud-stream/issues/1355

**Comment by jkschneider** [comment] 2018-05-05 02:46
Yep, that seems to narrow the issue down to `LoggingApplicationListener`.

**Comment by philwebb** [comment] 2018-05-29 18:35
Is there any code to that replicates this issue?

**Comment by jkschneider** [comment] 2018-05-29 23:31
@philwebb A reproducible example is included in spring-cloud/spring-cloud-stream#1355

**Comment by vprudnikov** [comment] 2019-02-27 06:38
Any results on this? I followed all the related issues and all of them are closed so this is probably the one which is opened.

Anyway I would like to add some details that can be helpful:

> A spring cloud application with Spring Boot 2.1.3.RELEASE

I found out that first, LogbackMetrics registers a logback filter which should work fine:

```
LogbackMetrics
...
public void bindTo(MeterRegistry registry) {
    MetricsTurboFilter filter = new MetricsTurboFilter(registry, tags);
    metricsTurboFilters.put(registry, filter);
    loggerContext.addTurboFilter(filter); // <- this is the line
}
```

But then, LoggingApplicationListener receives a ApplicationEnvironmentPreparedEvent and re-initializes logging system:

```
LogbackLoggingSystem
...
public void initialize(LoggingInitializationContext initializationContext,
      String configLocation, LogFile logFile) {
   LoggerContext loggerContext = getLoggerContext();
   if (isAlreadyInitialized(loggerContext)) { // <- this returns FALSE
      return;
   }
   super.initialize(initializationContext, configLocation, logFile); // <- this is the line!
   loggerContext.getTurboFilterList().remove(FILTER);
.......
```
and LogbackLoggingSystem calls 'stopAndReset':

```
LogbackLoggingSystem
...
protected void loadDefaults(LoggingInitializationContext initializationContext,
      LogFile logFile) {
   LoggerContext context = getLoggerContext();
   stopAndReset(context); // <- this line leads to LoggerContext#resetTurboFilterList method invocation
...
```
**After that, the metrics filter is removed from the LoggerContext so metrics cannot be collected.**

**Comment by wilkinsona** [comment] 2019-09-19 07:41
I don't think there's much that we can do in Boot to fix this. The root of the problem is Cloud's reinitialisation of the logging system. I believe that this will stop being necessary if https://github.com/spring-cloud/spring-cloud-commons/issues/608 can be tackled. I'm going to close this in favour of the Cloud issue for now at least.

**Closed by wilkinsona** 2019-09-19 07:41 UTC
Labels: type: bug
