### ISSUE TITLE
External Configuration command line parameters precedence broken for list types.

### ISSUE THREAD

**Issue by minmay** [spring-projects/spring-boot#8572] opened 2017-03-10 23:41 UTC
If you create an application.yml or application.properties file with a list, such as:

```
application.paths:
  - one
  - two
  - three
```

and configuration property class such as:

```
@Component
@ConfigurationProperties("application")
public class PathProperties {

    private List<String> paths;

    public List<String> getPaths() {
        return paths;
    }

    public void setPaths(List<String> paths) {
        this.paths = paths;
    }
}
```

Spring Boot will not allow a command line parameters to override the yaml file list values.

For example, if you used the command line parameters:

```
--application.paths=five --application.paths=six --application.paths=seven --application.paths=eight
```

then the values in the list will be:  one, two, three, eight.

This breaks the command-line precedence that is advertised in 
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by philwebb** [comment] 2017-03-11 01:35
I think this is a duplicate of #7015. We're trying to improve the way that YAML lists are loaded in 2.0. For 1.5 you can support this by using comma-separated strings:

```
application.paths: one, two, three
```

```
--application.paths=five,six,seven
```

**Closed** 2017-03-11 01:35 UTC
Labels: status: duplicate

**Comment by minmay** [comment] 2017-03-13 16:31
Thank you. This workaround works for me.
