### ISSUE TITLE
Spring Data Solr depends on an old version of Woodstox

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#3489] opened 2015-07-14 15:09 UTC
So old, indeed, that you get AbstractMethodErrors when you use Jackson XML and Solr in the same app (or in the Actuator where they are both needed optionally).

**Comment by christophstrobl** [comment] 2015-07-15 14:38
@dsyer I tried to exclude woodstox completely from both solrj and the optional solr-core dependencies and SD-Solr builds fine not having them present.

**Comment by adrianosimoes** [comment] 2017-01-22 19:54
Is this still an issue?

**Comment by snicoll** [comment] 2017-01-23 07:36
Yes, and the dependencies hasn't been updated either. I wonder why `solr-solr4j` still brings it if that's not necessary...

ping @wilkinsona

**Comment by wilkinsona** [comment] 2017-01-23 08:44
Not sure why you are pinging me. I'd expect this to be taken care of in Spring Data Solr or lower. @christophstrobl Have you considered adding some exclusions to Spring Data Solr's pom?

**Comment by snicoll** [comment] 2017-01-23 08:56
I was looking for advice and got the confirmation that this should be done at the Spring Data level probably. Thanks!

**Comment by christophstrobl** [comment] 2017-01-23 09:04
@wilkinsona @snicoll I try to mess as little as possible with transitive dependencies the drivers for datastores come with. Spring Data for Apache Solr 2.x uses Solr 5 which comes with

```bash
org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
```
see [SOLR-6830](https://issues.apache.org/jira/browse/SOLR-6830).

There's another issue open on Apache Solr side (see [SOLR-2852](https://issues.apache.org/jira/browse/SOLR-2852) - aged already but reopened recently) demanding to remove the woodstox dependency.

I'd prefer this to be solved on Solr side.

**Comment by snicoll** [comment] 2017-04-12 10:02
Given the current analysis, this one is a duplicate of the Solr issue

**Closed by snicoll** 2017-04-12 10:02 UTC
Labels: type: bug
