### ISSUE TITLE
Spring Boot ActiveMQ based JmsListener fails on TextMessage

### ISSUE THREAD

**Issue by ascheman** [spring-projects/spring-boot#15827] opened 2019-02-01 14:19 UTC
Disclaimer: I have already raised this problem on Stackoverflow (cf. https://stackoverflow.com/questions/54419999/spring-boot-amqp-based-jmslistener-fails-on-textmessage/54421088#54421088) and consider it a bug in Spring (Boot or Framework) or the underlying ActiveMQ integration.

I have a Spring Boot application (based on 2.1.2.RELEASE) which has problems retrieving JMS messages of type `TextMessage` from an ActiveMQ broker.

If the consumer tries to retrieve messages from the broker it cannot automatically convert a message to `TextMessage` but treats it as `ByteMessage`. There is a JmsListener which should read the messages from the queue as TextMessage:

```
@JmsListener(destination = "foo")
public void jmsConsumer(TextMessage message) {
```

The `JmsListener` produces warnings like the following, and drops the messages:

```
org.springframework.jms.listener.adapter.ListenerExecutionFailedException: Listener method could not be invoked with incoming message
Endpoint handler details:
Method [public void net.aschemann.demo.springboot.jmsconsumer.JmsConsumer.jmsConsumer(javax.jms.TextMessage)]
Bean [net.aschemann.demo.springboot.jmsconsumer.JmsConsumer@4715f07]; nested exception is org.springframework.messaging.converter.MessageConversionException: Cannot convert from [[B] to [javax.jms.TextMessage] for org.springframework.jms.listener.adapter.AbstractAdaptableMessageListener$MessagingMessageConverterAdapter$LazyResolutionMessage@7c49d298, failedMessage=org.springframework.jms.listener.adapter.AbstractAdaptableMessageListener$MessagingMessageConverterAdapter$LazyResolutionMessage@7c49d298
    at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:118) ~[spring-jms-5.1.4.RELEASE.jar:5.1.4.RELEASE]
```

The producer uses Apache Camel to create JMS messages and they are stored in the Broker with `jms-msg-type=5` which is the right format (JMS TextMessage) according to https://www.oasis-open.org/committees/download.php/56418/amqp-bindmap-jms-v1.0-wd06.pdf.
Nevertheless the consumer does not extract a `TextMessage` object from the queue but considers it of type `ByteMessage`.

I have extracted a small sample application to debug the problem: https://github.com/ascheman/springboot-camel-jms

The producer in real life is a commercial application which makes use of Apache Camel. Hence, I can hardly change/customize the producer. I have tried to build a sample producer which shows the same behaviour.

**Comment by wilkinsona** [comment] 2019-02-01 15:15
Thanks for the sample, but I can't see any evidence that the problem is with Spring Boot. 

Looking at ActiveMQ's [AMQP documentation](https://activemq.apache.org/amqp.html), my understanding is that ActiveMQ is behaving as designed. The default for mapping to JMS is `direct` which means that the broker "wraps the bytes of the AMQP message into a JMS BytesMessage and maps the headers of the AMQP message to headers on the JMS message". It sounds like the behaviour that you want is `jms` where the broker "maps headers of the AMQP message to JMS message headers and the body of the AMQP message to the JMS body." This needs to be configured in the broker.

Given the above, and the lack of evidence that Spring Boot is causing the problem, we can't justify spending any more time investigating what I suspect to be a configuration error. I'm going to close this issue for now. If the above does not help and you are able to provide an example that works without Spring (Boot) involved but fails when Spring (Boot) is introduced we can re-open this issue and take another look.

**Closed by wilkinsona** 2019-02-01 15:15 UTC
Labels: status: waiting-for-triage
