### ISSUE TITLE
In Spring Boot 2.3.5 tests, @ActiveProfiles does not honor the given sequence of profiles any more

### ISSUE THREAD

**Issue by k6ps** [spring-projects/spring-boot#24037] opened 2020-11-04 17:56 UTC
In 2.3.4 and earlier, when multiple profiles are given with the `@ActiveProfiles` annotation, the sequence is honored. That means the property values from the last in the sequence active profile specific properties "win" over previous ones. However, in 2.3.5.RELEASE, the profiles given with `@ActiveProfiles` get reordered internally, possibly alphabetically. Therefore, values from some earlier profile-specific properties file could "win". I attached a little demo application.

[demo.zip](https://github.com/spring-projects/spring-boot/files/5489628/demo.zip)

**Comment by bclozel** [comment] 2020-11-04 18:01
Thanks for getting in touch, we've already transferred a similar issue to Spring Framework (and it's already fixed for the next release).

I'm closing this issue as a duplicate of spring-projects/spring-framework#26004

**Closed by bclozel** 2020-11-04 18:01 UTC
Labels: status: waiting-for-triage
