### ISSUE TITLE
Issue while ./mvnw clean build 

### ISSUE THREAD

**Issue by bhagatdinesh** [spring-projects/spring-boot#12998] opened 2018-04-30 07:23 UTC
cloned project and tried to build 
`$ ./mvnw clean install`
on mac osx
java version
> java version "1.8.0_162"
> Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

 Error logs:
```

[INFO] Reactor Summary:
[INFO]
[INFO] Spring Boot Build 2.1.0.BUILD-SNAPSHOT ............. SUCCESS [  0.293 s]
[INFO] Spring Boot Dependencies ........................... SUCCESS [  1.034 s]
[INFO] Spring Boot Parent ................................. SUCCESS [  2.038 s]
[INFO] Spring Boot Tools .................................. SUCCESS [  0.161 s]
[INFO] Spring Boot Testing Support ........................ SUCCESS [  2.489 s]
[INFO] Spring Boot Configuration Processor ................ SUCCESS [  2.238 s]
[INFO] Spring Boot ........................................ SUCCESS [ 18.612 s]
[INFO] Spring Boot Test ................................... SUCCESS [  5.287 s]
[INFO] Spring Boot Auto-Configure Annotation Processor .... SUCCESS [  0.355 s]
[INFO] Spring Boot AutoConfigure .......................... SUCCESS [ 26.943 s]
[INFO] Spring Boot Actuator ............................... SUCCESS [ 18.848 s]
[INFO] Spring Boot Actuator AutoConfigure ................. SUCCESS [01:01 min]
[INFO] Spring Boot Developer Tools ........................ SUCCESS [  1.876 s]
[INFO] Spring Boot Configuration Metadata ................. SUCCESS [  0.351 s]
[INFO] Spring Boot Starters ............................... SUCCESS [  0.588 s]
[INFO] Spring Boot Logging Starter ........................ SUCCESS [  0.619 s]
[INFO] Spring Boot Starter ................................ SUCCESS [  0.552 s]
[INFO] Spring Boot Test Auto-Configure .................... SUCCESS [  5.952 s]
[INFO] Spring Boot Test Starter ........................... SUCCESS [  0.530 s]
[INFO] Spring Boot Properties Migrator .................... SUCCESS [  0.303 s]
[INFO] Spring Boot Loader ................................. SUCCESS [  1.683 s]
[INFO] Spring Boot Loader Tools ........................... SUCCESS [  2.053 s]
[INFO] Spring Boot Antlib ................................. SUCCESS [  0.599 s]
[INFO] Spring Boot Gradle Plugin .......................... SUCCESS [ 51.326 s]
[INFO] Spring Boot Maven Plugin ........................... SUCCESS [  4.833 s]
[INFO] Spring Boot ActiveMQ Starter ....................... SUCCESS [  1.156 s]
[INFO] Spring Boot AMQP Starter ........................... SUCCESS [  0.260 s]
[INFO] Spring Boot AOP Starter ............................ SUCCESS [  0.199 s]
[INFO] Spring Boot Artemis Starter ........................ SUCCESS [  0.640 s]
[INFO] Spring Boot JDBC Starter ........................... SUCCESS [  0.164 s]
[INFO] Spring Boot Batch Starter .......................... SUCCESS [  0.322 s]
[INFO] Spring Boot Cache Starter .......................... SUCCESS [  0.126 s]
[INFO] Spring Boot Spring Cloud Connectors Starter ........ SUCCESS [  0.222 s]
[INFO] Spring Boot Data Cassandra Starter ................. SUCCESS [  0.477 s]
[INFO] Spring Boot Data Cassandra Reactive Starter ........ SUCCESS [  0.229 s]
[INFO] Spring Boot Data Couchbase Starter ................. SUCCESS [  0.466 s]
[INFO] Spring Boot Data Couchbase Reactive Starter ........ SUCCESS [  1.075 s]
[INFO] Spring Boot Data Elasticsearch Starter ............. SUCCESS [  1.696 s]
[INFO] Spring Boot Data JPA Starter ....................... SUCCESS [  0.561 s]
[INFO] Spring Boot Data LDAP Starter ...................... SUCCESS [  0.181 s]
[INFO] Spring Boot Data MongoDB Starter ................... SUCCESS [  0.353 s]
[INFO] Spring Boot Data MongoDB Reactive Starter .......... SUCCESS [  0.194 s]
[INFO] Spring Boot Data Neo4j Starter ..................... SUCCESS [  0.372 s]
[INFO] Spring Boot Data Redis Starter ..................... SUCCESS [  0.334 s]
[INFO] Spring Boot Data Redis Reactive Starter ............ SUCCESS [  0.242 s]
[INFO] Spring Boot Json Starter ........................... SUCCESS [  0.206 s]
[INFO] Spring Boot Tomcat Starter ......................... SUCCESS [  0.205 s]
[INFO] Spring Boot Web Starter ............................ SUCCESS [  0.401 s]
[INFO] Spring Boot Data REST Starter ...................... SUCCESS [  0.340 s]
[INFO] Spring Boot Data Solr Starter ...................... SUCCESS [  0.472 s]
[INFO] Spring Boot FreeMarker Starter ..................... SUCCESS [  0.183 s]
[INFO] Spring Boot Groovy Templates Starter ............... SUCCESS [  0.319 s]
[INFO] Spring Boot HATEOAS Starter ........................ SUCCESS [  0.202 s]
[INFO] Spring Boot Integration Starter .................... SUCCESS [  0.202 s]
[INFO] Spring Boot Validation Starter ..................... SUCCESS [  0.149 s]
[INFO] Spring Boot Jersey Starter ......................... SUCCESS [  1.663 s]
[INFO] Spring Boot Jetty Starter .......................... SUCCESS [  2.085 s]
[INFO] Spring Boot JOOQ Starter ........................... SUCCESS [  0.191 s]
[INFO] Spring Boot Atomikos JTA Starter ................... SUCCESS [  0.177 s]
[INFO] Spring Boot Bitronix JTA Starter ................... SUCCESS [  0.159 s]
[INFO] Spring Boot Narayana JTA Starter ................... SUCCESS [  0.254 s]
[INFO] Spring Boot Log4j 2 Starter ........................ SUCCESS [  0.171 s]
[INFO] Spring Boot Mail Starter ........................... SUCCESS [  0.135 s]
[INFO] Spring Boot Mustache Starter ....................... SUCCESS [  0.119 s]
[INFO] Spring Boot Actuator Starter ....................... SUCCESS [  0.304 s]
[INFO] Spring Boot Starter Parent ......................... SUCCESS [  0.035 s]
[INFO] Spring Boot Quartz Starter ......................... SUCCESS [  0.179 s]
[INFO] Spring Boot Reactor Netty Starter .................. SUCCESS [  0.208 s]
[INFO] Spring Boot Security Starter ....................... SUCCESS [  0.191 s]
[INFO] Spring Boot Thymeleaf Starter ...................... SUCCESS [  0.188 s]
[INFO] Spring Boot Undertow Starter ....................... SUCCESS [  0.282 s]
[INFO] Spring Boot WebFlux Starter ........................ SUCCESS [  0.303 s]
[INFO] Spring Boot WebSocket Starter ...................... SUCCESS [  0.186 s]
[INFO] Spring Boot Web Services Starter ................... SUCCESS [  0.222 s]
[INFO] Spring Boot CLI .................................... FAILURE [  5.227 s]
[INFO] Spring Boot Docs ................................... SKIPPED
[INFO] Spring Boot Build .................................. SKIPPED
[INFO] Spring Boot Samples Invoker ........................ SKIPPED
[INFO] Spring Boot Tests .................................. SKIPPED
[INFO] Spring Boot Integration Tests ...................... SKIPPED
[INFO] Spring Boot Configuration Processor Tests .......... SKIPPED
[INFO] Spring Boot DevTools Tests ......................... SKIPPED
[INFO] Spring Boot Server Tests ........................... SKIPPED
[INFO] Spring Boot Launch Script Integration Tests 2.1.0.BUILD-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:03 min
[INFO] Finished at: 2018-04-30T12:35:04+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (bin-package) on project spring-boot-cli: Execution bin-package of goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single failed: group id '1455977373' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR]
```

Checked [this](https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#tarFileModes) page but could not make it work.

**Comment by snicoll** [comment] 2018-04-30 07:32
Duplicate of #11290

**Closed by snicoll** 2018-04-30 07:32 UTC
Labels: status: waiting-for-triage
