### ISSUE TITLE
Server Side Compression not working when sending Accept-Encoding with multiple values separately

### ISSUE THREAD

**Issue by patan12** [spring-projects/spring-boot#18176] opened 2019-09-07 14:18 UTC
Server Side Compression not working when sending Accept-Encoding with multiple values separately

Here is my application yml

```
server:
  port: 8193
  servlet:
    context-path: /web
  compression:
    enabled: true
    min-response-size: 1024
```

When sending request as like this server compress response 

```
	Url: http://localhost:8193/web/demo/1

	Request Headers:
	Accept-Encoding:deflate, gzip, br


	Response Headers:
		
	KEY: VALUE
	Content-Type: application/json;charset=UTF-8
	Transfer-Encoding: chunked
	Content-Encoding: gzip
	Vary: Accept-Encoding
```

**But when sending request as separate gzip headers, then response is not compressed**

```
	Url: http://localhost:8193/web/demo/1

	Headers:
	Accept-Encoding:deflate
	Accept-Encoding:gzip

	Response Headers:

	KEY:VALUE
	Content-Type:application/json;charset=UTF-8
	Content-Length:8540
	Vary:Accept-Encoding

```

I have also attached sample project

Refer Here

[muzwebdemo.zip](https://github.com/spring-projects/spring-boot/files/3586668/muzwebdemo.zip)

**Comment by wilkinsona** [comment] 2019-09-07 19:30
Thanks for the sample. Spring Boot 2.0.x has reach the end of its life and is no longer supported. However, the problem still occurs with upgraded to 2.1.8.

The behaviour that you are seeing is due to Tomcat. When looking for an `Accept-Encoding` header it does not consider the possibility of the header appearing in the request multiple times. As a result, it only sees `deflate` as an accepted encoding and therefore does not gzip the response.

@markt-asf Multiple `Accept-Encoding` headers appears to be legal according to RFC2616 where it says the following:

>  Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

Should this be fixed in Tomcat? FWIW, the same problem occurs with Jetty, however it does not occur when using Undertow.

**Comment by markt-asf** [comment] 2019-09-07 19:50
RFC 7230 has the same text. Yes, Tomcat should handle this. Please open a Bugzilla issue.

**Comment by dreis2211** [comment] 2019-09-07 19:57
@wilkinsona I might be wrong, but [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.2) states:

>    A sender MUST NOT generate multiple header fields with the same field
>    name in a message unless either the entire field value for that
>    header field is defined as a comma-separated list [i.e., #(values)]
>    or the header field is a well-known exception (as noted below).

@markt-asf I was also looking into RFC 7230 as it obsoletes RFC 2616, but I couldn't find that exact same section. Could you point me to the place where you found this?

**Comment by dreis2211** [comment] 2019-09-07 20:01
@wilkinsona BTW: Jetty and Netty should be affected as well.

**Comment by dreis2211** [comment] 2019-09-07 23:49
For Jetty here's an attempt to fix this: https://github.com/eclipse/jetty.project/pull/4066

**Comment by wilkinsona** [comment] 2019-09-08 07:20
Thanks, @markt-asf. I've opened https://bz.apache.org/bugzilla/show_bug.cgi?id=63737.

Thanks for opening the Jetty PR, @dreis2211.

**Comment by wilkinsona** [comment] 2019-09-08 07:27
The problem when using Netty seems to be caused by Netty itself rather than Reactor Netty. It [only considers the first `AcceptEncoding` header](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java#L76). I'll leave this open until I've had a chance to create a minimal reproducer.

**Comment by wilkinsona** [comment] 2019-09-09 08:33
I've opened https://github.com/netty/netty/issues/9553 for the problem with Netty. The only changes required in Spring Boot are to update to versions of Jetty, Netty, and Tomcat that fix the `Accept-Encoding` header which will shall do in due course as part of our usual dependency upgrades.

**Closed by wilkinsona** 2019-09-09 08:33 UTC
Labels: status: waiting-for-triage

**Comment by patan12** [comment] 2019-09-10 17:19
@wilkinsona  Thanks for looking into it. Do you know which version of spring upgrade it will be part of ?

**Comment by wilkinsona** [comment] 2019-09-10 19:17
The changes are in external projects so it's out of our control. It will be whatever version of Spring Boot is released after a release of Jetty, Netty, or Tomcat that contains the required changes.
