### ISSUE TITLE
Provide patch level documentation for older patch versions

### ISSUE THREAD

**Issue by rupert-madden-abbott** [spring-projects/spring-boot#43446] opened 2024-12-09 16:01 UTC
If I go to this link (https://docs.spring.io/spring-boot/3.3.3/system-requirements.html), it redirects me to this link: https://docs.spring.io/spring-boot/3.3/system-requirements.html and the page gives me details that are only correct for the latest version of 3.3.X which, at time of writing is 3.3.6.

However, this documentation is not accurate for 3.3.3 (which was what I was wanting and trying to see).

To give a single, clear example, this page says "is compatible with versions up to and including Java 23" but that support was only added in 3.3.4 according to [this ticket](https://github.com/spring-projects/spring-boot/issues/42374). Therefore, if I am on a patch version other than the latest, I cannot use this page to reliably determine Java compatibility of my current patch version.

I believe patch level documentation for older patches used to be provided but now appears to have been removed so it would be great to have this back again, if possible.

Another good example of a page where I often want patch level information is [this one](https://docs.spring.io/spring-boot/3.3/appendix/dependency-versions/coordinates.html).

**Comment by philwebb** [comment] 2024-12-09 23:04
We made an intentional decision to only keep documentation for the latest patch version when we migrated our documentation to Antora. This is for a number of reasons, but primarily to keep search engines happy and to reduce the complexity of building our docs site.

We're not likely to reinstate full patch documentation, however, this request has been raised before. We have #43063 where we'd like to attach the version report somewhere. We also have #40894 for providing offline docs.

I've updated #43063 to include dependency versions.

I think this one is now pretty much a duplicate of those other issues.

**Closed by philwebb** 2024-12-09 23:04 UTC
Labels: status: waiting-for-triage
