### ISSUE TITLE
Spring Boot Reference has a bad TestRestTemplate example

### ISSUE THREAD

**Issue by martinanderssondotcom** [spring-projects/spring-boot#12298] opened 2018-03-01 15:05 UTC
[Spring Boot Reference][1] says:

> Alternatively, if you use the `@SpringBootTest` annotation with `WebEnvironment.RANDOM_PORT` or `WebEnvironment.DEFINED_PORT`, you can inject a fully configured `TestRestTemplate` and start using it. [...] as shown in the following example:

But the ensuing example does not use an embedded server. It uses all the defaults of `@SpringBootTest`, i.e., `WebEnvironment.MOCK`.

[1]: https://docs.spring.io/spring-boot/docs/2.0.0.RC2/reference/htmlsingle/#boot-features-rest-templates-test-utility

**Comment by wilkinsona** [comment] 2018-03-01 15:16
Duplicate of #12132

**Closed by wilkinsona** 2018-03-01 15:16 UTC
Labels: status: waiting-for-triage
