### ISSUE TITLE
When using Log4j2 log4j2.properties files are not detected

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#16236] opened 2019-03-15 08:24 UTC

**Comment by mrifni** [comment] 2019-03-15 08:45
Can i pick this up ?

**Comment by mbhave** [comment] 2019-03-18 22:27
@mrifni Sure, the issue is currently unassigned.

**Comment by mrifni** [comment] 2019-03-19 11:29
any suggestions on where to begin to make a fix for this ? A class entry point would be nice.

**Comment by wilkinsona** [comment] 2019-03-19 11:41
The files that are looked for are configured [here](https://github.com/spring-projects/spring-boot/blob/0611eb49c87f367d3e34a1a3bcf04eb70150d180/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/log4j2/Log4J2LoggingSystem.java#L113). Note that it will be important to consider `.properties` file in the same order as [Log4j2 normally uses](https://logging.apache.org/log4j/2.x/manual/configuration.html#AutomaticConfiguration), i.e. they should be considered first. [This test](https://github.com/spring-projects/spring-boot/blob/0611eb49c87f367d3e34a1a3bcf04eb70150d180/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/logging/log4j2/Log4J2LoggingSystemTests.java#L210-L214) will also have to be updated.

**Comment by mrifni** [comment] 2019-03-19 13:52
Not sure why the PR is failing with this error

```
[ERROR] Failures: 
[ERROR]   Log4J2LoggingSystemTests.springConfigLocations:243 expected:<["log4j2-spring.[]xml"]> but was:<["log4j2-spring.[properties", "log4j2-spring.]xml"]>
```

**Comment by mbhave** [comment] 2019-03-22 19:03
Closing in favor of PR #16262.

**Closed by mbhave** 2019-03-22 19:03 UTC
Labels: type: bug
