### ISSUE TITLE
Bad shade plugin dependency in spring-boot-starter-parent.pom

### ISSUE THREAD

**Issue by brodecap** [spring-projects/spring-boot#6547] opened 2016-08-03 12:59 UTC
On line 174 of the spring-boot-starter-parent POM, the dependency version for spring-boot-maven-plugin:1.4.0.BUILD-SNAPSHOT is present.  Instead, it should reference the released version.

The result of this issue is the following error when creating a shaded JAR:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (default) on project foo: Execution default of goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade failed: Plugin org.apache.maven.plugins:maven-shade-plugin:2.4.3 or one of its dependencies could not be resolved: Could not find artifact org.springframework.boot:spring-boot-maven-plugin:jar:1.4.0.BUILD-SNAPSHOT in spring-releases (https://repo.spring.io/libs-release) -> [Help 1]

As a temporary fix, the following has been added to my project's pom.xml:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-shade-plugin</artifactId>
	<dependencies>
	    **<!-- Remove this when bug is fixed. -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
			<version>1.4.0.RELEASE</version>
		</dependency>**
	</dependencies>
	<configuration>
		<transformers>
			<transformer
				implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
				<resource>META-INF/spring.handlers</resource>
			</transformer>
			<transformer
				implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
				<resource>META-INF/spring.schemas</resource>
			</transformer>
		</transformers>
	</configuration>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>shade</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by Dichotomia** [comment] 2016-08-03 13:08
I think it is a duplicate of https://github.com/spring-projects/spring-boot/issues/6527

**Comment by snicoll** [comment] 2016-08-03 14:59
Indeed.

**Closed by snicoll** 2016-08-03 14:59 UTC
Labels: waiting-for-triage
