### ISSUE TITLE
Fail fast if SPRING_CONFIG_LOCATION specifies a file with an extension that no PropertySourceLoader can read

### ISSUE THREAD

**Issue by swamikevala** [spring-projects/spring-boot#17241] opened 2019-06-18 12:36 UTC
setting the environment variable SPRING_CONFIG_LOCATION to a file which does not have .properties suffix does not work.

`SPRING_CONFIG_LOCATION=file:/etc/opt/myapp/myapp.conf`
does not work

`SPRING_CONFIG_LOCATION=file:/etc/opt/myapp/myapp.properties`
works

spring boot version 2.1.5

**Comment by wilkinsona** [comment] 2019-06-18 12:49
This is the expected behaviour so we probably need to clarify the documentation. The file extension is used to determine which `PropertySourceLoader` can load a `PropertySource` from the file and `.conf` is not a known extension. `PropertiesPropertySourceLoader` can load `.xml` and `.properties` files. `YamlPropertySourceLoader` can load `.yml` and `.yaml` files. 

If you want to be able to load configuration from files with extensions other than those described above, you can provide your own `PropertySourceLoader` implementation and register it via an entry in `META-INF/spring.factories` under the `org.springframework.boot.env.PropertySourceLoader` key.

**Comment by swamikevala** [comment] 2019-06-18 13:10
ok that's fine. docs are not clear

**Comment by wilkinsona** [comment] 2019-07-09 19:10
Perhaps we should fail or log a warning if `ConfigFileApplicationListener` tries to load a location and none of the known loaders handles the location's file extension.

**Comment by hdeadman** [comment] 2019-08-02 16:52
@wilkinsona Can't the spring.config.location contain directories? In that case there is no extension and the fix for this breaks startup due to missing extension. I was using ```--spring.config.additional-location=file:/opt/ext_config``` and now that is failing with current snapshot. If I am mistaken and directories aren't supported then maybe that was just bad config on my part that wasn't actually working. 

```
ERROR: org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: File extension of config file location 'file:/opt/ext_config' is not known to any PropertySourceLoader
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:456) ~[spring-boot-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$null$7(ConfigFileApplicationListener.java:443) ~[spring-boot-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
        at java.util.Collections$SingletonSet.forEach(Collections.java:4797) ~[?:?]
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$load$8(ConfigFileApplicationListener.java:443) ~[spring-boot-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
```

**Comment by philwebb** [comment] 2019-08-02 20:20
Thanks for spotting this @hdeadman. I think we'll need to either revert or refine the check.

**Comment by hdeadman** [comment] 2019-08-02 22:42
It looks like the code checks for folders by making sure they end in a slash:
```
boolean isFolder = location.endsWith("/");
```
It probably is documented somewhere that folders should end in a slash, and I wasn't actually relying on any config in that folder so it probably wasn't working due to my missing slash. The new exception did point at a problem with my config but the exception message could have been more helpful in pointing me at the cause. 

Maybe the fail fast needs to occur somewhere earlier and say if there is no supported extension and it doesn't end in a slash, then it isn't a valid location. 

If the requirement for a slash is allow for all the various extensions (yaml, property) to be applied to some base filename (i.e. no extension), then the current check is probably not allowing that either. If supported extensions are not automatically applied to a base filename then it could treat any path without a valid extension as a directory.

**Closed** 2019-08-03 10:38 UTC
Labels: type: blocker, type: enhancement

**Comment by philwebb** [comment] 2019-08-03 10:40
Thanks for the additional information @hdeadman. The '/' requirement is indeed documented in [section 24.3](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files) of the reference documentation but I've improved the error message as well now. I've also added a test to confirm that a `/` suffix doesn't trigger the exception.
