### ISSUE TITLE
JerseyAutoConfiguration causes classloader issues in a container

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#2672] opened 2015-03-17 15:46 UTC
Because it is a `WebApplicationInitializer` it will get loaded by the container and instantiated by Spring.

**Comment by dsyer** [comment] 2015-03-17 16:42
This appears not to be an issue in practice as none of the fields are referenced in the initializer method (it only uses the `ServletContext` and Strings). Since this issue was raised [by a user](http://stackoverflow.com/questions/29102977/exclude-certain-webapplicationinitializers-in-cloudfoundry-war-deploy/29103130?noredirect=1#comment46436466_29103130), I'll leave it open for a bit in case more detail about the actual problem is forthcoming.

**Comment by jghiloni** [comment] 2015-03-17 17:26
Per comments in StackOverflow: The concerns our architects have with the embedded servlet container have been, quite honestly, a bit ambiguous, but the one that comes up repeatedly is making outbound calls (via a `RestTemplate`) to secured microservices, either one-way auth to a service with a trust chain unknown to the JVM, or two-way auth (trust chain issues also there). Buildpack magic for session replication is also a big draw, though it looks like that can be worked around using custom code (spring-session, etc) if necessary.

**Comment by dsyer** [comment] 2015-03-17 17:33
That's kind of off topic for this issue, but thanks anyway. Do you know what they think is different about a `RestTemplate` in an embedded container (I really can't imagine)? If you are using certificates for authentication it's purely a Java SE issue AFAIK and no different if the container is embedded. Session replication is 1 line of code in a Spring Boot app, so I'm not sure I see the problem there either (it's better to be embedded in fact because you get to test the whole stack locally before you deploy).

Any more data on the Jersey problem that we can't reproduce?

**Comment by jghiloni** [comment] 2015-03-17 17:34
I should have that to you in the next couple of hours.

**Comment by jghiloni** [comment] 2015-03-18 17:13
Despite my best efforts, I can't reproduce this now (figures). We can go ahead and close this, and if it re-emerges, I'll open a new issue. Thanks for looking into it.

**Comment by wilkinsona** [comment] 2015-03-19 14:33
@jghiloni Thanks for trying. If it rears its ugly head again please let us know.

**Closed by wilkinsona** 2015-03-19 14:33 UTC
Labels: waiting-for-feedback
