### ISSUE TITLE
docker-java fails to connect to docker daemon with SB 3.1.7 release

### ISSUE THREAD

**Issue by azuenko** [spring-projects/spring-boot#38953] opened 2024-01-02 13:33 UTC
After the SB 3.1.6 -> 3.1.7 update we started to have an issue with `docker-java` library connecting to docker daemon:

```
org.apache.hc.client5.http.HttpHostConnectException: Connect to unix://localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused.
```

We haven't changed any configuration, we've been always using UNIX socket at `/var/run/docker.sock`.

Downgrading to 3.1.6 solved the issue.

Could also be due to an update of an external dependency.

More details:
https://github.com/docker-java/docker-java/issues/2290

**Comment by wilkinsona** [comment] 2024-01-02 13:50
Spring Boot doesn't use `docker-java` or manage its version so it's not clear why you believe that this is a Spring Boot problem. Olease provide the complete stack trace of the `HttpHostConnectException` and describe the steps that are required to reproduce it.

**Comment by wilkinsona** [comment] 2024-01-02 14:45
> This might be the reason why docker-java started to fail

That sounds likely. You could confirm by downgrading to 5.2.1 and seeing if the problem is resolved.

I'll close this one as I don't think there's anything we could or should do in Spring Boot.

**Closed by wilkinsona** 2024-01-02 14:45 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by SeBBBe** [comment] 2024-01-02 19:39
Hi! I can confirm that adding the following to the pom.xml resolves the issue:

```
    <dependencyManagement>
        <dependencies>
        ...
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>5.2.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by wilkinsona** [comment] 2024-01-03 09:39
That's useful info, @SeBBBe. Thank you.
