### ISSUE TITLE
All REST API 404 error after RSocket enabled with Websocket Transportation

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#16887] opened 2019-05-17 06:40 UTC
Spring Boot application with Webflux and rsocket-starter support, and enable RSocket with Websocket Transportation, and all REST API 404 error.  
The demo is here:  https://github.com/linux-china/rest-404-with-rsocket

**Comment by wilkinsona** [comment] 2019-05-17 08:01
Thanks for the report. This looks to be a duplicate of #16826.

**Closed by wilkinsona** 2019-05-17 08:01 UTC
Labels: status: waiting-for-triage
