### ISSUE TITLE
Devtools does not work with the `dynamic.classpath` in IntelliJ IDEA

### ISSUE THREAD

**Issue by vlastikcz** [spring-projects/spring-boot#5860] opened 2016-05-04 07:44 UTC
Steps:
 1) Open the `spring-boot-sample-devtools` (1.3.3.RELEASE) application in IntelliJ IDEA 15.0.5
 2) Create the `Run configuration` with the `Spring Boot` type and `sample.devtools.SampleDevToolsApplication` as the main class
 3) Open `workspace.xml`, find `<component name="PropertiesComponent">` and set `<property name="dynamic.classpath" value="true" />`
 4) Reload workspace
 5) Run application

Expected:
 - `LocalDevToolsAutoConfiguration` is applied and the Devtools are working

Actual:
 - `LocalDevToolsAutoConfiguration` is not initialized, because of the `ConditionalOnInitializedRestarter`. 

The `dynamic.classpath` changes the class loader to the `URLClassLoader`, which is not compatible with the `DefaultRestartInitializer`.

I even tried to create my own `DefaultRestartInitializer` without the `AppClassLoader` condition. The Devtools were initialized, but not working correctly because of the `InvocationTargetException` (see attached log [devtools_withURLClassLoader-1.3.3-RELEASE.log.txt](https://github.com/spring-projects/spring-boot/files/248314/devtools_withURLClassLoader-1.3.3-RELEASE.log.txt)).

The same result seems to be with Devtools master ([devtools_withURLClassLoader-master.log.txt](https://github.com/spring-projects/spring-boot/files/248324/devtools_withURLClassLoader-master.log.txt)).

**Comment by snicoll** [comment] 2016-05-04 08:22
Looks like a duplicate of #5127

**Comment by wilkinsona** [comment] 2016-05-04 08:26
> Looks like a duplicate of #5127

It does, but if it is it should work on master. I'll have a look.

**Comment by vlastikcz** [comment] 2016-05-04 08:32
Well, even in `master`, the `DefaultRestartInitializer#isMain` requires the `AppClassloader`, right? But if the `dynamic.classpath` is enabled, the `isMain` returns `false` (because of the `URLClassLoader`), which blocks the `LocalDevToolsAutoConfiguration`.

**Comment by vlastikcz** [comment] 2016-05-04 08:47
This is my test: https://github.com/vlastikcz/spring-boot/commit/24d6e0f8205c6c81dfed79c9888135ffb64262a0

It's possible, that there is some issue with the custom `MyRestartApplicationListener`, because even if it throws an exception during start, the reload seems to be working (e.g. changes in the `Message` class are reloaded correctly). So the only issue may be with the condition in `DefaultRestartInitializer`.

**Comment by wilkinsona** [comment] 2016-05-04 16:48
It's not the same as #5127. That issue was Windows' specific and I can reproduce this problem on OS X. It does, however, appear to be specific to running as `Spring Boot` – run as a plain `Application` the problem doesn't occur.

The only simple way for DevTools to fix this is to remove the check on the name of the ClassLoader's class. That'll affect everyone, and not just IDEA users with `dynamic.classpath` set to `true` so I'm not sure that it's a good idea.

@philwebb what do you think?

**Comment by snicoll** [comment] 2016-05-25 08:45
Currently discussing with the Jetbrains folks to see if we can use another hook to detect that mode.

**Comment by snicoll** [comment] 2016-06-30 09:59
@yanncebron just fixed it in `2016.2` so I assume the next EAP should have that fix.

**Closed by snicoll** 2016-06-30 09:59 UTC
Labels: duplicate

**Comment by YannCebron** [comment] 2016-06-30 10:05
https://youtrack.jetbrains.com/issue/IDEA-158050
Fix will be included in 2016.2.2 bugfix update
