### ISSUE TITLE
War deployment in standalone Tomcat causes memory leak (Metaspace)

### ISSUE THREAD

**Issue by AlexieKA** [spring-projects/spring-boot#27987] opened 2021-09-14 10:22 UTC
**Steps to reproduce:**
1. Create an empty application in https://start.spring.io/ with the following parameters:

- Spring Boot 2.5.4
- Packaging War
- Java 11
- Spring Web

2. Build the application (gradle build)
3. Deploy the resulting war in a standalone Tomcat
4. Perform several (5-10) restarts of the application with Tomcat manager
5. As a result, we observe a metaspace leak (if a value of XX:MaxMetaspaceSiz is set and was reached, we get an exception)

**Analysis**
1. Create Heap Dump (for example, using jvisualvm)
2. Open the dump file with jvisualvm or MemoryAnalyzer
3. Select all objects of ParallelWebappClassLoader type 
4. The number of objects is equal to the number of restarts plus active application instances in Tomcat
5. Select «Path to GC Root» for inactive ParallelWebappClassLoader 
6. We can see the Thread (reference to ParallelWebappClassLoader) is stored in ApplicationShutdownHooks. Because of this reference, the GC cannot delete this ParallelWebappClassLoader instance and free metaspace

**Causes**
1. The thread that holds ParallelWebappClassLoader is created in the constructor of the class SpringApplicationShutdownHook (line 74)
2. The object of SpringApplicationShutdownHook is created when loading the SpringApplication type (line 203)
3. Since every restart of the application (from the tomcat admin panel) create new classloader and initialize SpringApplication type, which causes memory leak.

**Comment by AlexieKA** [comment] 2021-09-14 10:30
If this line cannot be removed for the Web scenario, then it can be added to the SpringApplicationShutdownHook.run hook removal:

	@Override
	public void run() {
		Set<ConfigurableApplicationContext> contexts;
		Set<ConfigurableApplicationContext> closedContexts;
		Set<Runnable> actions;
		synchronized (SpringApplicationShutdownHook.class) {
			this.inProgress = true;
			contexts = new LinkedHashSet<>(this.contexts);
			closedContexts = new LinkedHashSet<>(this.closedContexts);
			actions = new LinkedHashSet<>(this.handlers.getActions());
		}
		contexts.forEach(this::closeAndWait);
		closedContexts.forEach(this::closeAndWait);
		actions.forEach(Runnable::run);
               
               **Runtime.getRuntime().removeShutdownHook()**
	}

**Comment by AlexieKA** [comment] 2021-09-14 10:51
Current workaround (kotlin):

```
@WebListener
internal class CleanupServletContextListener : ServletContextListener {

    override fun contextInitialized(sce: ServletContextEvent) {
    }

    override fun contextDestroyed(sce: ServletContextEvent) {
        clearSpringApplicationShutdownHook()
    }

    private fun clearSpringApplicationShutdownHook() {
        val clazz = Class.forName("java.lang.ApplicationShutdownHooks")
        val field: Field = clazz.getDeclaredField("hooks")
        field.isAccessible = true
        @Suppress("UNUSED_VARIABLE", "UNCHECKED_CAST")
        val hooks: IdentityHashMap<Thread, Thread> = field.get(null) as IdentityHashMap<Thread, Thread>

        val ghosts =
            hooks.entries.asSequence().filter { it.key.name == "SpringApplicationShutdownHook" }.map { it.key }.toList()
        ghosts.forEach { hooks.remove(it) }

        field.isAccessible = false
    }
}
```

**Comment by bclozel** [comment] 2021-09-14 14:17
Did you [set up your WAR deployment as documented in the reference docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.traditional-deployment)?

[The shutdown hook should not be registered for WAR deployments](https://github.com/spring-projects/spring-boot/blob/ef6ad16e895ffeaa2a8475556d6d7d7b9d6a1985/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/servlet/support/SpringBootServletInitializer.java#L154).

If you believe there's an issue, can you provide a sample application (that we can clone and compile) that reproduces the issue?

Thanks

**Comment by quaff** [comment] 2021-09-15 02:00
@bclozel I have a related question, I'm deploy war to standalone tomcat, spring context is not closing when tomcat shutdown (Ctrl+C), but `deregisterJdbcDrivers` is called, am I missing something?

**Comment by quaff** [comment] 2021-09-15 03:06
My application is deployed to standalone tomcat refer to https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.traditional-deployment
There are 2 problems:
1. log in `@PreDestroy` is not output because log system is shutdown too early  by`LoggingApplicationListener::onContextClosedEvent`
2. tomcat will wait 10s to finish shutdown
```
15-Sep-2021 10:57:52.426 INFO [Thread-8] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
15-Sep-2021 10:58:02.432 WARNING [Thread-8] org.apache.tomcat.util.net.Acceptor.stop The acceptor thread [http-nio-8080-Acceptor] did not stop cleanly
15-Sep-2021 10:58:02.436 INFO [Thread-8] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]

```

**Comment by wilkinsona** [comment] 2021-09-15 12:07
I've reproduced this while looking at #27996. The problem is that loading `SpringApplication` always triggers the creation of a `SpringApplicationShutdownHook` which registers a shutdown hook. This hook is then never unregistered. We don't need to register it at all because, as @bclozel notes above, use of the shutdown hook is disabled by default in war deployments. This is a regression introduced by https://github.com/spring-projects/spring-boot/issues/26660, the fix for another regression

I think we should delay registration of the hook until the first application context is registered.

**Closed** 2021-09-16 09:51 UTC
Labels: type: regression
