### ISSUE TITLE
Using Spring Cloud Sleuth 2.0.0.M6 causes cycle dependency failure while starting the application

### ISSUE THREAD

**Issue by mmeknowis** [spring-projects/spring-boot#12078] opened 2018-02-15 15:42 UTC
We upgraded from Spring Cloud Finchley M5 to Spring Cloud Finchley M6.

We experienced that our spring boot application is not longer starting. 

**Problem:**
```
***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context form a cycle:
   sampleController (field private org.springframework.web.client.RestTemplate spring.sample.SampleController.restTemplate)
┌─────┐
|  restTemplate defined in class path resource [spring/sample/SampleRestTemplateFactory.class]
↑     ↓
|  restTemplateBuilder defined in class path resource [org/springframework/boot/autoconfigure/web/client/RestTemplateAutoConfiguration.class]
↑     ↓
|  org.springframework.cloud.sleuth.instrument.web.client.TraceWebClientAutoConfiguration$RestTemplateConfig (field private java.util.Collection org.springframework.cloud.sleuth.instrument.web.client.TraceWebClientAutoConfiguration$RestTemplateConfig.restTemplates)
└─────┘
```
We created a very simple app to reproduce this issue:
[springboot_samples.zip](https://github.com/spring-projects/spring-boot/files/1728238/springboot_samples.zip)

The ZIP file contains two versions of the application (Working and Not working). The only difference is the pom.xml:

**Working:**
```xml
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Finchley.M5</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

**Not working:**
```xml
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Finchley.M6</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```
For us it seems that the problem could be that in the class `org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration`  the `restTemplateCustomizers` are needed for the Bean `restTemplateBuilder()` and in the class `org.springframework.cloud.sleuth.instrument.web.client.TraceWebClientAutoConfiguration.RestTemplateConfig` the Bean `traceRestTemplateCustomizer()` needs the `restTemplates`. Or are we doing something wrong?

**Comment by wilkinsona** [comment] 2018-02-15 15:51
Duplicate of https://github.com/spring-cloud/spring-cloud-sleuth/issues/852.

**Closed by wilkinsona** 2018-02-15 15:51 UTC
Labels: status: waiting-for-triage
