### ISSUE TITLE
ErrorController should produce problem details if spring.mvc.problemdetails.enabled=true

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-boot#34871] opened 2023-04-06 02:12 UTC
Currently `ErrorController` will produce traditional error response even if problem details is enabled, nobody want to mix two different style of error handling.
```java
    @RequestMapping("/")
    void home(HttpServletResponse response) throws IOException {
        response.sendError(HttpServletResponse.SC_BAD_REQUEST, "bad.request");
    }
```
```java
	@Test
	void sendErrorShouldProduceProblemDetails() {
		ResponseEntity<Map<String, Object>> resp = testRestTemplate.exchange(RequestEntity.method(GET, "/").build(),
				new ParameterizedTypeReference<Map<String, Object>>() {
				});
		assertThat(resp.getBody()).containsKey("detail");
	}
```
```
Expecting actual:
  {"error"="Bad Request", "message"="bad.request", "path"="/", "status"=400, "timestamp"="2023-04-06T02:01:46.401+00:00"}
to contain key:
  "detail"
```
Here is minimal project [problemdetails.zip](https://github.com/spring-projects/spring-boot/files/11165661/problemdetails.zip)

**Comment by snicoll** [comment] 2023-04-07 13:43
Thanks for the report, this is a duplicate of #33885

**Closed by snicoll** 2023-04-07 13:43 UTC
Labels: status: waiting-for-triage
