### ISSUE TITLE
Allow Gson to be configured declaratively

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#1946] opened 2014-11-18 13:21 UTC
`GsonBuilder` allows a custom `Gson` instance to be created. `GsonAutoConfiguration` could be updated to use `GsonBuilder` and configure it from `spring.gson.*` properties in much the same way as `JacksonAutoConfiguration` does with `spring.jackson.*` properties

**Comment by geoff-wasilwa** [comment] 2015-10-29 19:54
Hi @wilkinsona is this still being worked on?

**Comment by wilkinsona** [comment] 2015-10-29 20:23
Not to my knowledge. It's just a possible enhancement at the moment. Pull requests welcome.

**Comment by ioanngolovko** [comment] 2017-03-12 13:41
Hi @wilkinsona. I want to implement this as well as jackson.  I have an only one question.

In which branch to make a pull request?

**Comment by wilkinsona** [comment] 2017-03-13 09:52
@ioanngolovko Against the master branch, please.

**Comment by izeye** [comment] 2018-01-10 13:45
This looks resolved via https://github.com/spring-projects/spring-boot/pull/11498.

**Comment by snicoll** [comment] 2018-01-10 13:51
Indeed @izeye, thanks!

Duplicate of #11498

**Closed by snicoll** 2018-01-10 13:51 UTC
Labels: priority: normal, type: enhancement
