### ISSUE TITLE
Make excludeDevtools available as a user property in Maven (spring-boot-maven-plugin)

### ISSUE THREAD

**Issue by jvwilge** [spring-projects/spring-boot#16694] opened 2019-05-01 11:56 UTC
I'd like to be able to set the `excludeDevtools` as a user property (for `spring-boot-maven-plugin`) on the command line when building my project in Maven :

```
mvn clean verify -Dspring-boot.excludeDevtools=false
```

Right now you have to add a [configuration entry](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-remote) `<excludeDevtools>false</excludeDevtools>`
 to your `pom.xml`. This is code that you don't want to end up in your production code. When you add it via the command line the pom is kept clean.

I tried to create a pull request, but ran into trouble with our corporate Nexus and snapshot/milestones. I think the fix is quite easy (but wasn't able to verify it).

## How to implement the fix 

In `spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/RepackageMojo.java#189` (the line before `private boolean excludeDevtools = true;` should be replaced with :
```java
@Parameter(property = "spring-boot.excludeDevtools", defaultValue = "true")
```

I think the [docs](https://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html) are auto-generated, but when they're not the user property has to be added to it.

I kept the property name in line with ones used in the [other exclude properties](https://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html)

It would be nice if it could also be backported to version 2.1.x 

## Verify the fix

To verify the fix works create a sample project on https://start.spring.io/ with all the default settings.

In `pom.xml` add 
```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <optional>true</optional>
    </dependency>
```
to the `<dependencies>` section. 

Build the project with 
```
mvn clean package -Dspring-boot.excludeDevtools=false
```

Run

```
jar tf target/demo-0.0.1-SNAPSHOT.jar | grep dev
```
and you should see an entry  like `BOOT-INF/lib/spring-boot-devtools-2.1.4.RELEASE.jar`

Thanks!

**Comment by snicoll** [comment] 2019-05-01 17:50
@jvwilge I am not really against adding a property but that looks a bit unusual to me and you can achieve the same thing by creating a property of your own that you can handle the exact same way. Can you share why that route didn't work for you?

**Comment by jvwilge** [comment] 2019-05-01 18:22
Thanks for the quick reply! I hadn't thought of adding a placeholder: 
```
<excludeDevtools>${spring-boot.excludeDevtools}</excludeDevtools>
```
This behaves the same as my 'fix' 

I had some problems adding the spring repo's to our Nexus. I gave up after spring-data-releasetrain  couldn't be found. Right now I'm at home and things go a lot smoother, I think it has to do with an incorrect  mirror configuration on our side of some milestone libs.

So I have a nice solution for my problem, it would make our poms a bit cleaner if the property is added anyway. I can imagine other people might use it too, so it's more of a nice to have now.

**Comment by snicoll** [comment] 2019-05-01 18:27
> This behaves the same as my 'fix'

I wouldn't use a project placeholder with the same prefix as a plugin you don't control. Please use something specific to your project/company instead.

I've flagged this one for team attention to see what the rest of the team thinks.

**Comment by jvwilge** [comment] 2019-05-02 05:42
Good point, I'll replace it!

Thanks for your help. I'll keep an eye on this issue.

**Comment by snicoll** [comment] 2019-05-02 06:56
Duplicate of #16701

**Comment by jvwilge** [comment] 2019-05-02 06:56
I created a PR (and tested it locally with the commands I mentioned)

**Closed by snicoll** 2019-05-02 06:56 UTC
Labels: for: team-attention, status: waiting-for-triage
