### ISSUE TITLE
Problems deploying thymeleaf spring boot app to containeir

### ISSUE THREAD

**Issue by hm1rafael** [spring-projects/spring-boot#9885] opened 2017-07-27 18:02 UTC
Hi

When deploying a spring-boot application to tomcat 8.5.16 when autowiring `SpringTemplateEngine` to a configuration method Thymeleaf's `cacheManager` is `null`.

If running through main method it works as it should

I made a small web app to test this:
[x.tar.gz](https://github.com/spring-projects/spring-boot/files/1180826/x.tar.gz)

The Spring boot version is: 1.5.4.RELEASE

**Comment by philwebb** [comment] 2017-07-28 02:15
I've tried running this within Tomcat in the IDE and standalone. I can't replicate the problem I'm afraid:

```
2017-07-27 19:13:53.861  WARN 79078 --- [ost-startStop-1] org.thymeleaf.templatemode.TemplateMode  : [THYMELEAF][localhost-startStop-1] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
Everything is fine
2017-07-27 19:13:54.177  INFO 79078 --- [ost-startStop-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.Bas
```

Could it be something specific to your environment? What OS are you using?

**Comment by spring-issuemaster** [comment] 2017-08-04 02:19
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by hm1rafael** [comment] 2017-08-05 21:48
Hey, 

I'm using ubuntu 17.04, I downloaded a fresh vanilla tomcat (8.5.16) for testing.

Thanks

**Comment by wilkinsona** [comment] 2017-08-08 06:47
@hm1rafael Thank you. Unfortunately, that hasn't helped to reproduce the problem.

Looking at Thymeleaf's code, its cache manager will always be non-null unless something explicitly sets it to `null`. To help us figure out what's happening, it would be useful to know what, if anything, is calling, `setCacheManager(ICacheManager)` on `SpringTemplateEngine`. Can you place a breakpoint in that method and debug your application to find out please?

**Comment by hm1rafael** [comment] 2017-08-08 21:04
@wilkinsona Thanks for the feedback. I saw the Template constructor that by default sets the CacheManager to the StandardCacheManager implementation, I'm using the example project that I attached in the first post as well.  As you can see, there are no setCacheManager(null) references.

The following log is when I run deploying in a container:

```
2017-08-08 17:51:23.406  INFO 25268 --- [ost-startStop-1] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@26427476: startup date [Tue Aug 08 17:51:23 BRT 2017]; root of context hierarchy
2017-08-08 17:51:25.945  INFO 25268 --- [ost-startStop-1] o.a.c.c.C.[.[.[/x-0.0.1-SNAPSHOT]        : Initializing Spring embedded WebApplicationContext
2017-08-08 17:51:25.945  INFO 25268 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2539 ms
2017-08-08 17:51:26.995  INFO 25268 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-08-08 17:51:26.996  INFO 25268 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'errorPageFilter' to: [/*]
2017-08-08 17:51:26.997  INFO 25268 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-08-08 17:51:27.207  WARN 25268 --- [ost-startStop-1] .t.AbstractTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2017-08-08 17:51:27.225  WARN 25268 --- [ost-startStop-1] org.thymeleaf.templatemode.TemplateMode  : [THYMELEAF][localhost-startStop-1] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
Something wrong
2017-08-08 17:51:28.011  INFO 25268 --- [ost-startStop-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2017-08-08 17:51:28.015  INFO 25268 --- [ost-startStop-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2017-08-08 17:51:28.254  INFO 25268 --- [ost-startStop-1] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@26427476: startup date [Tue Aug 08 17:51:23 BRT 2017]; root of context hierarchy
2017-08-08 17:51:29.590  INFO 25268 --- [ost-startStop-1] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-08-08 17:51:29.624  INFO 25268 --- [ost-startStop-1] x.TemplateEngineModificationTest         : Started TemplateEngineModificationTest in 8.641 seconds (JVM running for 41.808)
2017-08-08 17:51:29.676  INFO 25268 --- [ost-startStop-1] org.apache.catalina.startup.HostConfig   : Deployment of web application archive [/home/mattos/dev/tomcat/apache-tomcat-8.5.16/webapps/x-0.0.1-SNAPSHOT.war] has finished in [11,591] ms
2017-08-08 17:51:29.678  INFO 25268 --- [ost-startStop-1] org.apache.catalina.startup.HostConfig   : Deploying web application directory [/home/mattos/dev/tomcat/apache-tomcat-8.5.16/webapps/examples]
2017-08-08 17:51:30.168  INFO 25268 --- [ost-startStop-1] o.a.c.c.C.[.[localhost].[/examples]      : ContextListener: contextInitialized()
2017-08-08 17:51:30.169  INFO 25268 --- [ost-startStop-1] o.a.c.c.C.[.[localhost].[/examples]      :
```
The next log is when I run through a main spring boot method.
```
2017-08-08 17:57:14.551  INFO 28808 --- [           main] x.TemplateEngineModificationTest         : Starting TemplateEngineModificationTest on mattos with PID 28808 (/home/mattos/dev/eclipse-workspace/x/target/classes started by mattos in /home/mattos/dev/eclipse-workspace/x)
2017-08-08 17:57:14.555  INFO 28808 --- [           main] x.TemplateEngineModificationTest         : No active profile set, falling back to default profiles: default
2017-08-08 17:57:14.849  INFO 28808 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@32cf48b7: startup date [Tue Aug 08 17:57:14 BRT 2017]; root of context hierarchy
2017-08-08 17:57:16.466  INFO 28808 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-08-08 17:57:16.486  INFO 28808 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-08-08 17:57:16.487  INFO 28808 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.15
2017-08-08 17:57:16.588  INFO 28808 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-08-08 17:57:16.588  INFO 28808 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1743 ms
2017-08-08 17:57:16.691  INFO 28808 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-08-08 17:57:16.696  INFO 28808 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-08-08 17:57:16.746  WARN 28808 --- [           main] .t.AbstractTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2017-08-08 17:57:16.755  WARN 28808 --- [           main] org.thymeleaf.templatemode.TemplateMode  : [THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
Everything is fine
2017-08-08 17:57:17.144  INFO 28808 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2017-08-08 17:57:17.145  INFO 28808 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2017-08-08 17:57:17.206  INFO 28808 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@32cf48b7: startup date [Tue Aug 08 17:57:14 BRT 2017]; root of context hierarchy
2017-08-08 17:57:17.598  INFO 28808 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-08-08 17:57:17.702  INFO 28808 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-08-08 17:57:17.705  INFO 28808 --- [           main] x.TemplateEngineModificationTest         : Started TemplateEngineModificationTest in 3.474 seconds (JVM running for 3.934)
```
I agree with @philwebb  , It's probably something  in my machine, I tought it was a bug  because of other users in my company reporting this.
At first I thought It was the thymeleaf jar, but since both running methods use the same maven repo, I discarded this hypothesis. I'll check it out further.

Thanks

**Comment by wilkinsona** [comment] 2017-08-09 07:21
The only other thing that I can think this might be is that the `SpringTemplateEngine` instance is being proxied for some reason. We've seen a vaguely similar problem in the past that was related to proxying. What's the `Class` (result of calling `getClass()`) of `SpringTemplateEngine` in the two cases?

**Comment by hm1rafael** [comment] 2017-08-09 13:34
No proxies. Class org.thymeleaf.spring4.SpringTemplateEngine in both cases.

**Comment by wilkinsona** [comment] 2017-08-09 13:54
Thanks for trying that. I'm running out of suggestions now. One last thing to try: put a watchpoint on the `cacheManager` field of `TemplateEngine`. You should see the field being set when `SpringTemplateEngine` is constructed and then, presumably, something (although I have no idea what) setting it back to `null`. It may also be interesting to have a breakpoint on the constructor of `SpringTemplateEngine` at the same time to step through it being created and calling `setCacheManager()`.

**Comment by spring-issuemaster** [comment] 2017-08-25 19:29
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-09-01 19:08
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-09-01 19:08 UTC
