### ISSUE TITLE
LocaleResolver (MVC) and LocaleContextResolver (WebFlux) beans will back off if a user provides a bean of the same type and a custom name but Framework will then use its own default

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#24209] opened 2020-11-19 10:08 UTC
While looking at #24207, I noticed that our overrides of the  `localeResolver()` (MVC) and `localeContextResolver()` (WebFlux) methods will back off if any `LocaleResolver` or `LocaleContextResolver` bean is present (they're annotated with a plain `@ConditionalOnMissingBean`) but Framework consumes these beans using a specific name. This means that a user may provide a custom bean with a non-standard name and our auto-configuration will back off, but Framework will then use its default rather than the user's bean. If you're trying to figure out what's happened, the condition evaluation report won't help much as it'll show that the auto-configured resolver backed off in favour of the user-provided resolver but won't explain why the user-provided resolver wasn't used.

I am wondering if our auto-configured beans should only back off when a bean of the name that Framework looks for is defined:

```java
@ConditionalOnMissingBean(name = WebHttpHandlerBuilder.LOCALE_CONTEXT_RESOLVER_BEAN_NAME)
```

```java
@ConditionalOnMissingBean(name = DispatcherServlet.LOCALE_RESOLVER_BEAN_NAME)
```

This would make the condition evaluation report more useful as it will show that the auto-configured bean was configured as no bean with a specific name was found in the context.

**Comment by philwebb** [comment] 2020-11-19 15:54
I think we probably should. I'd even say this is a bug and should perhaps be fixed in 2.2.x

**Comment by wilkinsona** [comment] 2020-11-20 07:43
The `LocaleContextResolver` problem is specific to 2.4.0. I'll fix the MVC side of things in 2.2.x and 2.3.x and both in 2.4.x.

**Comment by wilkinsona** [comment] 2020-11-20 09:21
In 2.2 and 2.3 the auto-configured `LocaleResolver` is `@ConditionalOnProperty(prefix = "spring.mvc", name = "locale")`. For the problem described above to occur, you'd have to set the `spring.mvc.locale` property and provide a custom `LocaleResolver` bean that isn't named `localeResolver()`. I think that's sufficiently unlikely to happen that the risk of the fix isn't worth the marginal improvement. 

In 2.4.0 things are different as both the `LocaleResolver` and `LocaleContextResolver` beans are not `@ConditionalOnProperty`.

**Closed** 2020-11-20 11:06 UTC
Labels: type: bug

**Comment by theHilikus** [comment] 2021-01-11 21:51
@wilkinsona we are having a regression related to localeResolver and i'm wondering if it's related to this ticket or an actual regression in Spring

We are using mvc and we localize our ui using thymeleaf. Since updating to 2.4.1 (tested with 2.4.0 and the problem is there. but it is NOT there in 2.3.7) our application doesn't start and gives the error

```
20:07.617  WARN 93032 --- [  restartedMain] gServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'localeResolver' defined in class path resource [com/foo/ui/config/UiConfig.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=uiConfig; factoryMethodName=localeResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/foo/ui/config/UiConfig.class]] for bean 'localeResolver': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration; factoryMethodName=localeResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/web/servlet/config/annotation/DelegatingWebMvcConfiguration.class]] bound.
```

The error is misleading. I was able to find the conflicting bean in `org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport`, not in `DelegatingWebMvcConfiguration` like the error says. But in any case, shouldn't that bean back off when i register my own LocaleResolver?

I haven't been able to find official documentation to configure a localizationResolver. I just followed [this article](https://www.baeldung.com/spring-boot-internationalization) which instructs to create the bean like this

```java
@Bean
public LocaleResolver localeResolver() {
    SessionLocaleResolver slr = new SessionLocaleResolver();
    slr.setDefaultLocale(Locale.US);
    return slr;
}
```

But again, such a bean collides with the one in WebMvcConfigurationSupport and if renamed it is not used by `org.springframework.web.servlet.DispatcherServlet#initLocaleResolver`, which does

```java
this.localeResolver = context.getBean(LOCALE_RESOLVER_BEAN_NAME, LocaleResolver.class);
```

I see that 2.3.X WebMvcConfigurationSupport doesn't create a `localeResolver` bean

Should I open a new ticket or am I missing something?

**Comment by philwebb** [comment] 2021-01-12 00:07
@theHilikus That sounds like a bug. The `localeResolver` in our `EnableWebMvcConfiguration` class is `@ConditionalOnMissingBean` so it should back off.

Could you check that you've not got an `@EnableWebMvc` annotation in your app? If you haven't, could we please have a new issue with a sample that shows the error.

**Comment by theHilikus** [comment] 2021-01-12 03:18
ah. i did have @EnableWebMvc. Once i removed that, the problem was gone

Thank you for the info @philwebb

**Comment by snturk** [comment] 2023-07-17 12:57
I'm now dealing with the same problem as @theHilikus, without using `@EnableWebMvc` annotation, I get the following error when my application starts:

```
The bean 'localeResolver', defined in class path resource [path/to/MyConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class] and overriding is disabled.
```

However, I cannot override that bean without using `spring.allow-bean-definition-overriding` property set to true. It's not an okey solution for me.

**Comment by mychalvlcek** [comment] 2024-04-11 05:38
@snturk have you found anything to this?

**Comment by snturk** [comment] 2024-04-12 20:44
> @snturk have you found anything to this?

No, unfortunately.

**Comment by wilkinsona** [comment] 2024-04-13 07:11
@mychalvlcek @snturk In this case, Phil has already suggested what to do next:

> Could you check that you've not got an `@EnableWebMvc` annotation in your app? If you haven't, could we please have a new issue with a sample that shows the error.

**Comment by mychalvlcek** [comment] 2024-04-13 07:38
dont have this annotation.. my setup is following, multi-module maven project, where multiple multiple configuration classes with implementing `WebMvcConfigurer` interface are used.. 

originally i've had direct usage of componentScan like following

```
@ComponentScan(basePackages = {
        "module1",
        "module2" // LocaleResolver bean is configured here
})
```

once I want to remove this component scan and switch just to autoconfiguration approach (module2 has autoconfiguration), it stops to work.. so I guess it is connected to order of execution of all configurations (especially those implementing `WebMvcConfigurer` where spring-configured LocaleResolver will be automatically created earlier)

**Comment by wilkinsona** [comment] 2024-04-13 08:05
Yes, it sounds like your auto-configuration is ordered incorrectly. The auto-configuration that defines your custom `LocaleResolver` bean must be ordered before `WebMvcAutoConfiguration` (which is `@AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE + 10`) otherwise `WebMvcAutoConfiguration` won't be able to see your `LocaleResolver` bean and it won't back off.
