### ISSUE TITLE
Gradle builds fail using Spring Boot 2.0.0.M4 and JDK9

### ISSUE THREAD

**Issue by danieldietrich** [spring-projects/spring-boot#10510] opened 2017-10-04 08:22 UTC
## Bug report

Gradle builds fail using the recent Spring Boot 2.0.0.M4 and JDK9 (on a Mac). 

**Versions used to reproduce the error:**

* macOS Sierra 10.12.6
* Gradle 4.2.1
* JDK9 (build 9+181)
* Spring Boot 2.0.0.M4

**Steps performed to reproduce the error:**

1. Visit https://start.spring.io
2. Generate Project (Gradle / Java / Spring Boot 2.0.0.M4)
3. Unzip `demo.zip`, cd into that directory and run `./gradlew build`

**Output:**

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.springframework.boot:spring-boot-starter-actuator:.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-actuator//spring-boot-starter-actuator-.pom
      https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-actuator//spring-boot-starter-actuator-.jar
      https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-actuator//spring-boot-starter-actuator-.pom
      https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-actuator//spring-boot-starter-actuator-.jar
      https://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-actuator//spring-boot-starter-actuator-.pom
      https://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-actuator//spring-boot-starter-actuator-.jar
  Required by:
      project :
> Could not find org.springframework.boot:spring-boot-starter-data-jpa:.
  Required by:
      project :
> Could not find org.springframework.boot:spring-boot-starter-security:.
  Required by:
      project :
> Could not find org.springframework.boot:spring-boot-starter-web:.
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
1 actionable task: 1 executed
```

**Comment by wilkinsona** [comment] 2017-10-04 08:26
Duplicate of #10049.

**Closed by wilkinsona** 2017-10-04 08:26 UTC
Labels: status: waiting-for-triage
