### ISSUE TITLE
Inconsistent precedence of properties imported by PropertySourcesPlaceholderConfigurer#setLocations in Spring Boot 2.0.4

### ISSUE THREAD

**Issue by bianjp** [spring-projects/spring-boot#14055] opened 2018-08-14 09:40 UTC
**Version:** Spring Boot 2.0.4
**Sample project:** https://github.com/bianjp/spring-examples/tree/master/properties-precedence
**Problem:** Properties imported by `PropertySourcesPlaceholderConfigurer#setLocations` has different precedence according to where they are used,  while the behavior in Spring Boot 1.5.14 is consistent.

When using `PropertySourcesPlaceholderConfigurer#setLocations` to load custom properties files that don't follow Spring Boot naming convention, the imported properties have different precedence according to where they are used:

* For `@ConfigurationProperties`, they always have highest precedence, even higher than system properties
* For `@Value` bindings, they always have lowest precedence. Works in the same way as Spring Boot 1.5.14
* For XML property placeholder:
  * If there is just one bean of the same type, they work in the same way as `@Value`
  * If there is also a `@ConfigurationProperties` bean, they work in the same way as `@ConfigurationProperties`

In Spring Boot 1.5.14, the behavior is consistent and the imported properties always have lowest precedence (just like `@PropertySource`).

I didn't find anywhere documenting the precedence of `PropertySourcesPlaceholderConfigurer#setLocations`, but I think the behavior in 1.5.14 should be expected.

**Comment by wilkinsona** [comment] 2018-08-14 13:07
Thanks for the sample. It allowed me to confirm that this is a duplicate of https://github.com/spring-projects/spring-boot/issues/13738 that @mbhave has already fixed.

**Closed by wilkinsona** 2018-08-14 13:07 UTC
Labels: status: waiting-for-triage
