### ISSUE TITLE
change from spring boot 2.0.6 to 2.1.0 breaks web app

### ISSUE THREAD

**Issue by Ed42** [spring-projects/spring-boot#15052] opened 2018-10-31 23:54 UTC
Conflict between WebMvc and Jersey auto config (bean overriding disallowed):

```
Exception encountered during context initialization - cancelling refresh attempt: 
org.springframework.beans.factory.support.BeanDefinitionOverrideException:
Invalid bean definition with name 'requestContextFilter' defined in class path resource
[org/springframework/boot/autoconfigure/web/servlet/*WebMvcAutoConfiguration*$WebMvcAutoConfigurationAdapter.class]:
Cannot register bean definition [Root bean: class
[org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter];
scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true;
primary=false; factoryBeanName=null; factoryMethodName=requestContextFilter;
initMethodName=null; destroyMethodName=(inferred); defined in class path resource
[org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
for bean 'requestContextFilter': There is already [Root bean: class [null]; scope=; abstract=false;
lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false;
factoryBeanName=org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration;
factoryMethodName=requestContextFilter; initMethodName=null;
destroyMethodName=(inferred); defined in class path resource
[org/springframework/boot/autoconfigure/jersey/*JerseyAutoConfiguration.class*]] bound.
```

**Comment by snicoll** [comment] 2018-11-01 01:17
Duplicate of #15048

**Closed by snicoll** 2018-11-01 01:17 UTC
Labels: status: waiting-for-triage
