### ISSUE TITLE
Upgrading Spring boot 1.5.x to latest Spring Kafka 1.3.x

### ISSUE THREAD

**Issue by shivangshah** [spring-projects/spring-boot#14129] opened 2018-08-17 21:25 UTC
## Enhancement/Upgrade Request

Currently, 1.5.x is running on 1.1.8.RELEASE of Spring Kafka. There have been significant improvements and feature adds since then and the latest version fo Spring Kafka is at 1.3.6.RELEASE. 

Workaround as of now is to explicitly provide the spring-kafka version when using 1.5.x version of spring boot. This will a nice to have in Spring Boot 1.5.x BOM so developers can get these features out-of-the-box. 

Have created a pull request here for the same  - https://github.com/spring-projects/spring-boot/pull/14128

**Comment by mbhave** [comment] 2018-08-17 21:37
Closing as duplicate of #14128.

**Closed by mbhave** 2018-08-17 21:37 UTC
Labels: status: waiting-for-triage
