### ISSUE TITLE
2.0.2 - breaking change in profile activation

### ISSUE THREAD

**Issue by peterdnight** [spring-projects/spring-boot#13166] opened 2018-05-14 14:34 UTC
Summary:
Change in profile order - introduced in 2.0.2 - means it is no longer possible to override include profiles. Spring boot 2.0.1/.0 - profile includes are very useful for setting up shared behaviors in common libraries used by many spring boot apps. App developers can all rely on common settings from the includes - and then selectively override using their custom profiles and activating them (and overriding).

Suggestions on how to regain this with 2.0.2 would be very welcome.

Setup:
- sts - new project. Add the following:

```
spring:
  profiles: 
    active: d,e,f
    include: 
    - a
    - b
    - c
```
Boot 2.0.1/.0 output:
```
14-05-2018 10:04:40.973 [restartedMain] INFO  (SpringApplication.java:663) o.springframework.boot.SpringApplication.logStartupProfileInfo 
==> The following profiles are active: a,b,c,d,e,f 
```

Boot 2.0.2 output:
```
14-05-2018 10:01:44.711 [restartedMain] INFO  (SpringApplication.java:663) o.springframework.boot.SpringApplication.logStartupProfileInfo 
==> The following profiles are active: d,e,f,a,b,c
```

**Comment by wilkinsona** [comment] 2018-05-14 15:05
Duplicate of #13151.

**Closed by wilkinsona** 2018-05-14 15:05 UTC
Labels: status: waiting-for-triage
