### ISSUE TITLE
repo.spring.io/milestones differs from Maven Central - <repositories> missing

### ISSUE THREAD

**Issue by nealeu** [spring-projects/spring-boot#12598] opened 2018-03-22 16:24 UTC
Hi,

I've just had a poor soul finding that the build server is doing fine, but his local build is failing with not being able to get milestone releases.

On digging I discovered that these two differ in that his `spring-boot-dependencies:2.0.0.RELEASE` POM is from http://repo.spring.io/milestone/org/springframework/boot/spring-boot-dependencies/2.0.0.RELEASE/, and doesn't have <repositories> defined.

However the public release does: http://central.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.0.0.RELEASE/spring-boot-dependencies-2.0.0.RELEASE.pom

The workaround is to remove the contents of `.m2/org/springframework.boot/spring-boot-dependencies/2.0.0.RELEASE/` folder and try again.

Is it possible that this might also happen with the 2.0.1 release?

I think it would be advisable to remove/replace the inconsistent one in the Spring Milestones repository to at least prevent more users suffering the same issue.

**Comment by snicoll** [comment] 2018-03-22 16:35
Thanks for the report. Duplicate of #12378

**Closed by snicoll** 2018-03-22 16:35 UTC
Labels: status: waiting-for-triage

**Comment by nealeu** [comment] 2018-03-22 17:09
Thanks.  My search clearly wasn't exhaustive enough.

So for clarity for everyone else who ends up here, I read it that the Milestone repositories one is correct, and the Maven Central one was a one off mistake that has now been proactively fixed for 2.0.1.
