### ISSUE TITLE
Allow the auto-configuration of ContentNegotiatingViewResolver to be disabled

### ISSUE THREAD

**Issue by yoshikawaa** [spring-projects/spring-boot#9498] opened 2017-06-13 05:01 UTC
Hi, I have a problem with view resolution.

[Spring Boot provides auto-configuration for Spring MVC](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-auto-configuration) that include `BeanNameViewResolver` bean.
However, using `spring-boot-starter-thymeleaf`, `BeanNameViewResolver` is disabled.

I hope to enable `BeanNameViewResolver`, and to be resolved view name before thymeleaf.

## using version
spring-boot 1.5.4.RELEASE and maven build.

## problem detail
Setting as follows.
* pom.xml
```xml
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.4.RELEASE</version>
</parent>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-thymeleaf</artifactId>
	</dependency>
    <!-- omitted. -->
```
* view
```java
@Component("exampleView")
public class ExampleView extends AbstractXlsxView {
  // omitted.
```
* controller
```java
@PostMapping
public String view(Model model) {
    // omitted.
    return "exampleView";
}
```
Getting the error.
```console
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "exampleView", template might not exist or might not be accessible by any of the configured Template Resolvers
```
## Now, workaround
* Exclude view bean from view names to be resolved by thymeleaf.
    ```yml
    spring.thymeleaf.excluded-view-names : exampleView
    ```
    But getting the error yet...
    ```console
    javax.servlet.ServletException: Could not resolve view with name 'exampleView' in servlet with name 'dispatcherServlet'
    ````
* And, configure bean name view resolver.
    ````java
    @Override
    public void configureViewResolvers(ViewResolverRegistry registry) {
        registry.beanName();
    }
    ````
    Finally resolved bean!

**Comment by wilkinsona** [comment] 2017-06-13 14:40
@yoshikawaa A `BeanNameViewResolver` should always be auto-configured unless the context already contains a `BeanNameViewResolver` bean. It's configured with slightly higher precedence than the Thymeleaf view resolver (`LOWEST_PRECEDENCE - 10` versus `LOWEST_PRECEDENCE - 5`) so it should be called before Thymeleaf is asked to resolve the view. In short, I think what you have described should work and I can't tell from your description why that's apparently not the case. Can you please provide a small sample yet complete (something that we can unzip or git clone and then run) that illustrates the behaviour you've described?

**Comment by yoshikawaa** [comment] 2017-06-14 07:38
@wilkinsona 
Thanks for your reply.
As a result of careful verification, I thought that this problem caused by `AbstractXlsView` and `ViewController`. I made a simple program that will be caused it. Please check it and advise me.
https://github.com/yoshikawaa/spring-boot-issue-9498

**Comment by wilkinsona** [comment] 2017-06-14 09:20
@yoshikawaa Unfortunately, the sample that you have shared does not reproduce the problem. The simple and excel views both work for me with the default profile active. You two other profiles, `view-controller` and `workaround` both use `EnableWebMvc` which switches off Spring Boot's auto-configuration of the bean name view resolver.

As far as I can tell there isn't a bug here so I am going to close this issue. If you can profile a sample that reproduces the problem that we can re-open this issue and take another look.

**Comment by kazuki43zoo** [comment] 2017-06-14 16:29
Hi @yoshikawaa and @wilkinsona ,

This issue depends on Accept Header value that submit by user-agent(e.g. Web Browser, curl, etc...).
Probably, this error is occurred on access via web browser.

e.g.)

* `Accept: */*` -> 👍 
* `Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/html` -> 👍 
* `Accept: text/html,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` -> 👎 

Note: This behaviors are control by the `ContentNegotiatingViewResolver`.

@wilkinsona 
I will propose to provide a option for prevent auto-registration of `ContentNegotiatingViewResolver` using properties file. What do you think ?

**Comment by wilkinsona** [comment] 2017-06-14 16:56
That looks like the missing piece. Thank you, @kazuki43zoo. I'm not sure about an option to disable `ContentNegotiationViewResolver`. That feels like quite a drastic solution. I'll re-open this so that we can consider what the alternatives might be. @bclozel may have some suggestions.

**Comment by kazuki43zoo** [comment] 2017-06-14 17:05
>  I'll re-open this so that we can consider what the alternatives might be. 

Thanks !!

**Comment by wilkinsona** [comment] 2017-06-14 17:19
Thinking about this so more, I think the problem really lies with the controller. Its request mapping is claiming that `/excel` can produce any content type. That lets content negotiation kick in at which point the `text/html` response of `InternalResourceViewResolver` is preferred to the `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` response from `ExcelView` as the browser prefers `text/html`.

Rather than disabling content negotiation completely, I think it would be better for the controller to more accurately describe what it is capable of producing:

```java
@RequestMapping(path="excel", produces="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
public String view2() {
    return "excelView";
}
```

**Comment by kazuki43zoo** [comment] 2017-06-14 17:30
I think it is good advice. @yoshikawaa What do you think ?

**Comment by kazuki43zoo** [comment] 2017-06-15 01:36
Hi @wilkinsona ,
If we want to disable the `ContentNegotiatingViewResolver`, does need to define a dummy `ViewResolver` as follow ?

```java
@Bean
ViewResolver viewResolver() {
	return (viewName, locale) -> null;
}
```

What do you think for above method ?
I want to know recommended method for this.

Thanks.

**Comment by yoshikawaa** [comment] 2017-06-15 03:50
@kazuki43zoo @wilkinsona 
I could understand this reason and solution so I felt refreshed.

I think that it's good to encourage the Reference Guide to pay special attention to the relationship between the view's content type and the controller's `produce` attribute if using auto-configuration.
Also, since it is not necessarily the case that you want to resolve view by content negotiation, it would be better to provide an option to disable the `ContentNegotiatingViewResolver`.

Thanks.

**Comment by wilkinsona** [comment] 2017-06-15 10:14
@kazuki43zoo Yes, that will work. You may want to explicitly order it with LOWEST_PRECEDENCE just to make the intent clear. The alternative at the moment is to use `@EnableWebMvc` and take complete control over Spring MVC's configuration.

> I think that it's good to encourage the Reference Guide to pay special attention to the relationship between the view's content type and the controller's produce attribute if using auto-configuration.

It's not really about using auto-configuration, it's about using `ContentNegotiatingViewResolver` and we already document that the auto-configuration switches that on. Documentation of best practices for request mappings when using `ContentNegotiatingViewResolver` belong in Spring Framework's documentation, IMO.

> Also, since it is not necessarily the case that you want to resolve view by content negotiation, it would be better to provide an option to disable the ContentNegotiatingViewResolver

We can use this issue to consider offering a property for that.

**Comment by bclozel** [comment] 2017-06-21 15:56
I think @wilkinsona is right on that one - disabling the `ContentNegotiatingViewResolver` is a strong signal that you want to take things into your own hands, and in that case `@EnableWebMvc` makes a lot of sense.

Since adding the appropriate information on your endpoint does solve the problem (and in fact seeing that this will make your application consistent with content negotiation), I'm tempted to leave things as they are.

Feel free to reopen this issue if you come up with more use cases where this should be a more common configuration choice. In any case, this issue and our discussions around it should be useful to others!

Thanks!

**Closed by bclozel** 2017-06-21 15:56 UTC
Labels: type: enhancement
