### ISSUE TITLE
Caches that are created dynamically do not have published metrics

### ISSUE THREAD

**Issue by tkvangorder** [spring-projects/spring-boot#14702] opened 2018-10-05 17:48 UTC
The current auto-configuration for cache metrics will only bind caches that are known at start-up. This means that in the case where developers are using @Cacheable, any cache that is created "on-the-fly" will not have its metrics bound to the MeterRegistry.

This is surprising behavior and it seems reasonable to expect all caches, dynamic or otherwise, to have  their metrics exposed through micrometer.

This is actually a tricky problem because each CacheManager implementation must be meter-aware. Specifically, a cache should be bound to the registry when `CacheManager.getCache(String name)` is called. The best place to do this would be in the `AbstractCacheManager` (in the core Spring Framework), however, the `CacheMetricsRegistrar` (used to bind a cache to the `MeterRegistry`) is in the Spring Boot Actuator project.

I can think of two ways to make this work correctly, such that when the actuator library is added to the classpath all caches have their metrics bound to the `MeterRegistry` :

- Publish a `CacheCreatedEvent` from within `AbstractCacheManager`. Given the internals of the registrar, this event would have to have both the cache name and the cache manager from which it was created. This would allow a listener to be defined in the actuator library to wire up each cache to the meter registry. This approach would also mean that it is no longer necessary to have a `@PostConstruct` method in the `CacheMetricsRegistrar` to bind known caches on startup, as all caches would trigger a call to `getCache`. This approach would mean changes to both the core Spring library's Cache and then changes to SpringBoot's actuator.

- Create an Aspect that is bound to `CacheManager.getCache(String name)`. This aspect will use the Registrar to bind the cache to the `MeterRegistry`. This approach also makes it unneccesary to have a separate `@PostConstruct` to regsiter known caches and will only require changes in the actuator library.

**Comment by wilkinsona** [comment] 2018-10-05 17:57
Duplicate of #14576.

**Closed by wilkinsona** 2018-10-05 17:57 UTC
Labels: status: waiting-for-triage

**Comment by tkvangorder** [comment] 2018-10-05 18:07
@wilkinsona By closing this issue as a duplicate of an issue that is also closed, does that mean that both of the approaches I have outlined in this issue are not going to be considered? I would be willing to add a PR to fix this issue, but I would like some direction on which approach would be preferred.

**Comment by wilkinsona** [comment] 2018-10-05 18:13
I’m not sure yet, but I’d like to keep the discussion in one place. Can you please comment on #14576? I prefer the first of your two suggestions, but we should get @snicoll’s opinion as he’s more knowledgable in this area than I am.

**Comment by tkvangorder** [comment] 2018-10-05 18:43
Perfect, I will move my comment over there. I found that issue before creating this one, but I was not sure if it was ok to add additions to a closed issue. I will try to keep them consolidated in the future. Thanks!
