### ISSUE TITLE
Source file must be provided failure when running spring-boot:repackage from the command-line

### ISSUE THREAD

**Issue by ninjubohra** [spring-projects/spring-boot#19055] opened 2019-11-19 17:35 UTC
**Issue:**

Getting the following error when running `mvn spring-boot:repackage` **as standalone command**

```
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.2.1.RELEASE:repackage (default-cli) on project ce360-manager-service: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.2.1.RELEASE:repackage failed: Source file must be provided
```

**Steps to reproduce**
Have a Spring boot application that successfully builds when using the command
`mvn clean package spring-boot:repackage`
Try running the commands in separate invocation
`mvn clean`
`mvn package`
`mvn spring-boot:repackage`

Spring boot version 2.2.1.RELEASE

λ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: C:\tools\apache-maven-3.3.9
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: C:\tools\jdk1.8.0_162\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

I have console logs to show more detail but I am unable to attach files to the issue (fetch-json.js:16 POST https://github.com/upload/policies/assets 503 (Service Unavailable)) so I will provide them in-line if needed

**Comment by philwebb** [comment] 2019-11-19 17:53
Can you please run the build with `-X` and attach the stack trace.

**Comment by ninjubohra** [comment] 2019-11-19 19:54
> Can you please run the build with `-X` and attach the stack trace.

I will try to attach the logs

**Comment by ninjubohra** [comment] 2019-11-19 22:11
Attached please find two files
failure.log (running each goal as a separate command)
success.log (running all goals as part of a single command)
[success.log](https://github.com/spring-projects/spring-boot/files/3866303/success.log)
[failure.log](https://github.com/spring-projects/spring-boot/files/3866304/failure.log)

**Comment by snicoll** [comment] 2019-11-20 07:11
@ninjubohra regardless of the issue here I am curious why you invoke those goals separately. That's very much tied to the lifecycle of the packaging so invoking the goal isolated feels a bit odd to me.

**Comment by spring-issuemaster** [comment] 2019-11-27 07:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-12-04 07:13
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-12-04 07:13 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by jmaasing** [comment] 2020-07-12 08:20
> @ninjubohra thanks for the feedback. Regardless of the issue here I am curious why you invoke those goals separately. That's very much tied to the lifecycle of the packaging so invoking the goal isolated feels a bit odd to me.

I'm having the same issue on version 2.3.1-RELEASE

running `mvn spring-boot:repackage -X`

Does not work and gives

`[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.1.RELEASE:repackage (default-cli) on project landscape-web: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.3.1.RELEASE:repackage failed: Source file must not be null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.1.RELEASE:repackage (default-cli) on project landscape-web: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.3.1.RELEASE:repackage failed: Source file must not be null
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.3.1.RELEASE:repackage failed: Source file must not be null
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.IllegalArgumentException: Source file must not be null
    at org.springframework.util.Assert.notNull (Assert.java:198)
    at org.springframework.boot.loader.tools.Packager.<init> (Packager.java:95)
    at org.springframework.boot.loader.tools.Repackager.<init> (Repackager.java:46)
    at org.springframework.boot.loader.tools.Repackager.<init> (Repackager.java:42)
    at org.springframework.boot.maven.RepackageMojo.lambda$getRepackager$0 (RepackageMojo.java:237)
    at org.springframework.boot.maven.AbstractPackagerMojo.getConfiguredPackager (AbstractPackagerMojo.java:130)
    at org.springframework.boot.maven.RepackageMojo.getRepackager (RepackageMojo.java:237)
    at org.springframework.boot.maven.RepackageMojo.repackage (RepackageMojo.java:171)
    at org.springframework.boot.maven.RepackageMojo.execute (RepackageMojo.java:165)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)`

**Comment by wilkinsona** [comment] 2020-07-13 09:31
@jmaasing Thanks. As far as we know this should work and, indeed, when invoked like that it was working for @ninjubohra. If you'd like us to investigate why it's not working for you, please open a new issue with a minimal sample that reproduces the problem.

**Comment by wilkinsona** [comment] 2020-07-13 16:00
Superseded by #22317.
