### ISSUE TITLE
Upgrade to Jetty 9.4.21.v20190926

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#18494] opened 2019-10-03 07:11 UTC

**Comment by wilkinsona** [comment] 2019-10-03 08:14
9.4.21 appears to contain some changes in behaviour that cause some test failures:

```
[ERROR] Failures: 
[ERROR]   JettyServletWebServerFactoryTests>AbstractServletWebServerFactoryTests.errorPage:339 
Expecting:
 <"<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 java.lang.RuntimeException: Planned</title>
</head>
<body><h2>HTTP ERROR 500 java.lang.RuntimeException: Planned</h2>
<table>
<tr><th>URI:</th><td>/bang</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>java.lang.RuntimeException: Planned</td></tr>
<tr><th>SERVLET:</th><td>error</td></tr>
<tr><th>CAUSED BY:</th><td>java.lang.RuntimeException: Planned</td></tr>
</table>
<pre>java.lang.RuntimeException: Planned
	at org.springframework.boot.web.servlet.server.AbstractServletWebServerFactoryTests$4.service(AbstractServletWebServerFactoryTests.java:1109)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1589)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1559)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:560)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:914)
	at java.lang.Thread.run(Thread.java:748)
</pre>

</body>
</html>
">
to be equal to:
 <"Hello World">
but was not.
[ERROR]   JettyServletWebServerFactoryTests>AbstractServletWebServerFactoryTests.errorPageFromPutRequest:349 
Expecting:
 <"">
to be equal to:
 <"Hello World">
but was not.
[ERROR]   JettyServletWebServerFactoryTests>AbstractServletWebServerFactoryTests.persistSession:652 [Session error s1=null:1570086848108 s2=null:1570086848116 s3=null:1570086848227] 
Expecting:
 <"null">
to be equal to:
 <"1570086848108">
but was not.
```

Further investigation is needed to see if we can work around things in Boot or if there's a regression in Jetty that will need to be fixed there.

**Comment by dreis2211** [comment] 2019-10-03 12:45
If it helps: I think the changes that make the errorPage tests fail are likely located in this commit: https://github.com/eclipse/jetty.project/commit/bde86467f4e5df595773ab11ed5e80c615b741f3. I didn't get to the exact root cause yet, but Boot's `JettyEmbeddedErrorHandler` isn't functional anymore at least and I can trace this back to the mentioned commit. I tried overwriting `errorPageForMethod` to allow for PUT requests again, but it still breaks the current tests.

I didn't get to the session tests yet, but unlike before a new session seems to be created every time which breaks the logic in [AbstractServletWebServerFactoryTests.java#L1124](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/web/servlet/server/AbstractServletWebServerFactoryTests.java#L1124) as it can't find the session attribute anymore. I haven't found the commit yet that causes it, but there were definitely changes in the session handling (e.g. https://github.com/eclipse/jetty.project/pull/4049)

I initially hoped to fix the issue, but wanted to at least share the findings.

**Comment by wilkinsona** [comment] 2019-10-03 13:20
Thanks very much for sharing your analysis, @dreis2211.

**Comment by dreis2211** [comment] 2019-10-03 15:05
With the following patch I get the error page related tests to run again:
```
--- a/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/jetty/JettyEmbeddedErrorHandler.java
+++ b/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/web/embedded/jetty/JettyEmbeddedErrorHandler.java
@@ -26,6 +26,7 @@ import javax.servlet.http.HttpServletResponse;
 import org.eclipse.jetty.http.HttpMethod;
 import org.eclipse.jetty.server.Request;
 import org.eclipse.jetty.server.handler.ErrorHandler;
+import org.eclipse.jetty.server.handler.ErrorHandler.ErrorPageMapper;

 /**
  * Variation of Jetty's {@link ErrorHandler} that supports all {@link HttpMethod
@@ -36,7 +37,7 @@ import org.eclipse.jetty.server.handler.ErrorHandler;
  *
  * @author Phillip Webb
  */
-class JettyEmbeddedErrorHandler extends ErrorHandler {
+class JettyEmbeddedErrorHandler extends ErrorHandler implements ErrorPageMapper {

        private final ErrorHandler delegate;

@@ -54,6 +55,19 @@ class JettyEmbeddedErrorHandler extends ErrorHandler {
                this.delegate.handle(target, baseRequest, request, response);
        }

+       @Override
+       public boolean errorPageForMethod(String method) {
+               return true;
+       }
+
+       @Override
+       public String getErrorPage(HttpServletRequest request) {
+               if (this.delegate instanceof ErrorPageMapper) {
+                       return ((ErrorPageMapper) this.delegate).getErrorPage(request);
+               }
+               return null;
+       }
+
        private static class ErrorHttpServletRequest extends HttpServletRequestWrapper {

                private boolean simulateGetMethod = true;
```

That leaves us with `persistSession` to fix.

**Comment by dreis2211** [comment] 2019-10-04 08:40
For the error page stuff there is an issue already that might be of interest: https://github.com/eclipse/jetty.project/issues/4154

**Comment by wilkinsona** [comment] 2019-10-04 08:55
Thanks again, @dreis2211. The session problem may well be worth reporting. Let me see if I can find some time to dig into it a bit so that we have something concrete to report. Next week's SpringOne Platform is looming large at the moment so it may take a little while.

**Comment by dreis2211** [comment] 2019-10-04 10:36
Have fun at SpringOne Platform then. At some point I hope we can meet up at one of those conferences and have a chat in person.

**Comment by dreis2211** [comment] 2019-10-05 07:53
There was a bug opened at Jetty that seemed interesting enough as it's also a regression in the session handling. Unfortunately, when building the branch and testing the proposed fix this doesn't have an impact on the `persistSession` test - it still fails. For full reference though: https://github.com/eclipse/jetty.project/issues/4156

**Comment by dreis2211** [comment] 2019-10-05 12:07
I could finally reproduce the behavior change (which appears to be connected to using a cookie with a JSESSIONID). I reported this already to Jetty and hope that's okay. Let's see what comes out of it.

**Comment by wilkinsona** [comment] 2019-10-07 13:07
Thanks again, @dreis2211. Judging by the Jetty team's response, it looks reasonable to me to just update our tests not to set the `JSESSIONID=123` `Cookie` header. It was added in https://github.com/spring-projects/spring-boot/commit/08d1f6daf5b29af880de214e31543debe49a33f1#diff-cad85c99cd5100a102ff8195b58caa73R679 for https://github.com/spring-projects/spring-boot/issues/2490 but I don't believe it's needed.

**Comment by dreis2211** [comment] 2019-10-07 13:17
Already tried it before reporting this to Jetty and it's indeed not needed (hence my comment that I at least found a fix already). ;-) There's still a request for feedback if that change was intentional, so I'd suggest to wait a bit still before finishing this up. But I can already provide a PR with the necessary changes, if you want me to.

**Comment by dreis2211** [comment] 2019-10-07 14:19
As the change in the error page handling is likely not working for versions <= 9.4.20 (because of the unknown `errorPageForMethod` method) I'm currently thinking if we should provide a `JettyEmbeddedLegacyErrorHandler` to provide a smooth upgrade path for people. What do you think?

**Comment by dreis2211** [comment] 2019-10-08 12:33
I opened a PR, so it's easier to talk about potential code changes.

**Comment by philwebb** [comment] 2019-10-22 21:54
Closing in favor of PR #18536

**Closed by philwebb** 2019-10-22 21:54 UTC
Labels: type: dependency-upgrade
