### ISSUE TITLE
Enhancement: Proxied @ConfigurableProperties that allow for dynamic resolution of placeholders (templating properties)

### ISSUE THREAD

**Issue by nightswimmings** [spring-projects/spring-boot#24799] opened 2021-01-13 10:44 UTC
I think the framework could benefit a lot with something like the following: 

`my.application.templated-property="baseValueWith${myDynamicValue:}injected"`

```
System.out.println(myApplicationProperties.getTemplatedProperty()); //Prints "baseValueWithInjected"
System.setProperties("myDynamicValue","MyProperty");
System.out.println(myApplicationProperties.getTemplatedProperty()); //Prints "baseValueWithMyPropertyInjected"
System.setProperties("myDynamicValue","MyProperty2");
System.out.println(myApplicationProperties.getTemplatedProperty()); //Prints "baseValueWithMyProperty2Injected"
```
Is this feasible or doable in an easy way by means of an existent framework trick?

**Comment by wilkinsona** [comment] 2021-01-13 10:51
Thanks for the suggestion. This is a duplicate of #259.

**Closed by wilkinsona** 2021-01-13 10:51 UTC
Labels: status: waiting-for-triage

**Comment by nightswimmings** [comment] 2021-01-13 10:58
Ah cool!!! Thanks Andy!
