### ISSUE TITLE
Application sometimes fails to start after upgrading to Spring Boot RC1

### ISSUE THREAD

**Issue by iNikem** [spring-projects/spring-boot#12201] opened 2018-02-23 18:35 UTC
After we upgraded to Spring Boot RC1 our application sometimes fails to start. It happens roughly one time in ten with the following error:

```
2018-02-23 18:29:15.750 ERROR 1 --- [main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.ConsoleAppender[console] - Appender [console] failed to append. java.lang.NullPointerException
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:166)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:82)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:115)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:263)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:236)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:199)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
        at eu.plumbr.probe.processing.ProbeProcessor.main(ProbeProcessor.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

When we restart it, everything works. Some race happens?

**Comment by iNikem** [comment] 2018-02-23 18:39
I don't know if this is related, but we have the following in the logs as well:

```
18:30:04.225 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.console' in any property source
18:30:04.230 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.file' in any property source
18:30:04.230 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.file.max-history' in any property source
18:30:04.230 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.file.max-size' in any property source
18:30:04.230 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.level' in any property source
18:30:04.231 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.dateformat' in any property source
```

**Comment by philwebb** [comment] 2018-02-23 18:40
@iNikem Is there anything special about your app? Are you able to replicate the problem with a sample you can share?

**Comment by philwebb** [comment] 2018-02-23 18:42
Looking at the history 0679d4369cc99f4e26655a65398ae995fc6a36b0 or 844782b20bf1de0ca22b031fd2874a55a483044e might be related.

**Comment by iNikem** [comment] 2018-02-23 18:43
Nothing special that I am aware of that could influence logging. Spring Cloud Stream application talking to kafka.

And no simple reproducer atm.

**Comment by iNikem** [comment] 2018-02-23 18:44
But we have a custom `logback-spring.xml` file to have time-based rolling:

```
<configuration>

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${LOG_FILE}</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>${LOG_FILE}.%d{yyyyMMdd}.gz</fileNamePattern>
            <maxHistory>45</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>${FILE_LOG_PATTERN}</pattern>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="FILE"/>
    </root>
</configuration>
```

**Comment by iNikem** [comment] 2018-02-23 18:45
A. Problem never happens when run with `gradle bootRun`. It happens only when packaged and run as a Docker container.

**Comment by iNikem** [comment] 2018-02-23 18:49
Trying now to reproduce I got the following log:

```
18:47:53.092 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.exception-conversion-word' in any property source
18:47:53.098 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.console' in any property source
18:47:53.096 [background-preinit] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Log4j2LoggerProvider
18:47:53.102 [background-preinit] INFO org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.7.Final
18:47:53.106 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.file' in any property source
18:47:53.106 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.file.max-history' in any property source
18:47:53.108 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.file.max-size' in any property source
18:47:53.108 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.level' in any property source
18:47:53.109 [main] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'logging.pattern.dateformat' in any property source
```

This is printed before Spring Boot banner.

**Comment by philwebb** [comment] 2018-02-23 18:50
It would be good if we could get a stack trace for that NPE. It looks like `UnsynchronizedAppenderBase` is the class that actually captures the original exception.

**Comment by iNikem** [comment] 2018-02-23 18:52
Any suggestions how I could get that?

**Comment by philwebb** [comment] 2018-02-23 18:53
You might be able to add something like this in a catch block on your main method:

```java
ILoggerFactory factory = StaticLoggerBinder.getSingleton().getLoggerFactory();
LoggerContext context = (LoggerContext) factory;
List<Status> statuses = loggerContext.getStatusManager().getCopyOfStatusList();
for (Status status : statuses) {
    Throwable cause = status.getThrowable();
    if (cause != null) {
        cause.printStracTrace();
    }
}
```

**Comment by iNikem** [comment] 2018-02-23 19:22
Nope, no luck. `statuses` is always empty list.

**Comment by philwebb** [comment] 2018-02-23 19:27
Any way to share your app (or a version of it) along with the docker steps needed to replicate the problem?

**Comment by iNikem** [comment] 2018-02-23 19:33
I can share the whole docker image, yes, but will this be of use without source code?

But in the meantime I have tried to upgrade to RC2. After this those strange logs from `PropertySourcesPropertyResolver` have disappeared. And I am unable to reproduce the original problem as well :) So it seems like RC2 solves my issue. I will continue testing and either will close this issue or will share the application in a couple of days.

**Comment by philwebb** [comment] 2018-02-23 19:46
Oh interesting. The debug logging is probably #11761. I'll close this for now, but please report back if you can reproduce it with the latest release.

**Closed by philwebb** 2018-02-23 19:46 UTC
Labels: for: team-attention, status: waiting-for-triage
