### ISSUE TITLE
Using @SpyBean leads to running a separate Tomcat instance per each test

### ISSUE THREAD

**Issue by OleksandrSankin** [spring-projects/spring-boot#22771] opened 2020-08-06 17:07 UTC
Please take a look at this small project https://github.com/OleksandrSankin/spring-boot-bug 
Build it via "mvn clean install" and you will see that three Tomcat instances will be running (project contains three tests)

What I figured out: 
- this issue started from spring-boot version 2.2.9 and is reproduced in latest 2.3.2
- if downgrade version till 2.2.8 - issue will disappear
- if ignore the line at com.bug.AbstractTest:18 - issue will disappear

Why is this issue for me? 

At work I have 600+ tests which runs against the standalone database (postgres). Running a separate Tomcat per each test cause the connection pool overflow at postgres side and failing the tests at the end. So I am not able to upgrade project from version 2.2.8 till the latest. Yep - I can rewrite the tests avoid using spybean but its a quite huge job.

Also after debugging I was able to find the point that can be useful - DefaultCacheAwareContextLoaderDelegate:121 (here makes a decision - create new context or not for test)
 
I've attached the screenshot - hope it would help

![Screen Shot 2020-08-06 at 19 24 34](https://user-images.githubusercontent.com/19478239/89560935-78797400-d820-11ea-940e-00e73dfd8139.png)

**Comment by dreis2211** [comment] 2020-08-06 17:15
Likely a duplicate of #22566

**Comment by wilkinsona** [comment] 2020-08-06 17:19
Indeed. Thanks, @dreis2211.

**Closed by wilkinsona** 2020-08-06 17:19 UTC
Labels: status: waiting-for-triage
