### ISSUE TITLE
ManagementWebServerFactoryCustomizer should not always add ErrorPage

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#17951] opened 2019-08-23 23:25 UTC
Currently `ManagementWebServerFactoryCustomizer` always adds an `ErrorPage`, however, in Jersey applications we don't have an endpoint for them so the application returns 404 for all errors. We should probably mirror `ErrorMvcAutoConfiguration.ErrorPageCustomizer` somehow and only register them for MVC.

**Comment by philwebb** [comment] 2019-08-23 23:25
See #17912

**Comment by mbhave** [comment] 2019-08-24 01:08
@philwebb I think this is a duplicate of #17938

**Closed** 2019-08-24 18:29 UTC
Labels: type: bug
