### ISSUE TITLE
cassandra

### ISSUE THREAD

**Issue by ken4ward** [spring-projects/spring-boot#26413] opened 2021-05-07 13:07 UTC

**Comment by ken4ward** [comment] 2021-05-07 13:07
This is not working at all. I wonder why a simple config our of the box will create an unreliable problem. I have been one this issue for over 36 hours with not solution. I only added this lib, and added the properties yet the problem has refused to go. This is just so annoying. I'm using Spring-boot 2.4.5,
spring.data.cassandra.contact-points=127.0.0.1
spring.data.cassandra.username=cassandra
spring.data.cassandra.password=cassandra
spring.data.cassandra.keyspace=accountservicedb
spring.data.cassandra.port=9042
spring.data.cassandra.schema-action=NONE
spring.data.cassandra.local-datacenter=datacenter1

**Comment by snicoll** [comment] 2021-05-07 13:19
Duplicate of #26413 and https://github.com/spring-projects/spring-boot/issues/19779#issuecomment-834365162

**Closed** 2021-05-07 13:19 UTC
Labels: status: duplicate
