### ISSUE TITLE
high memory usage for spring boot Path variable api

### ISSUE THREAD

**Issue by rahulsingh336** [spring-projects/spring-boot#23323] opened 2020-09-15 18:05 UTC
We have created one microservice with single endpoint. This api consist of single path variable and it is just returning OK response.
In real time, it will have different processing mechanism but for testing and POC purpose we have kept it simple.
Now, When we generate load with jmeter for this particular api and pass in random path variable values using random variable in jmeter then we have observed that memory is constantly increasing over a period of time and objects are not getting GC.

spring boot version:- 2.3.1 RELEASE
dependencies:- spring-boot-starter-web, spring-boot-starter-security, spring-boot-starter-actuator

Sample api:- /app/ping/{id} GET

Jmeter :- path = /app/ping/${random_var}   - random_var having value in between 1 - 100000
               Number of Threads:- 60
               Ramp Up Seconds:- 1
               Loop Count:- Forever
Spring boot app configuration:- -Xmx150m
Heap Dump:- Attached
VisvualVM screenshot:- Attached

Leak Suspect: Attached

![image](https://user-images.githubusercontent.com/20011592/93247282-afda2980-f7ab-11ea-8fd0-98277206e221.png)

[heapdump-1600192132939_Leak_Suspects.zip](https://github.com/spring-projects/spring-boot/files/5226847/heapdump-1600192132939_Leak_Suspects.zip)

[heapdump-1600192132939.zip](https://github.com/spring-projects/spring-boot/files/5226849/heapdump-1600192132939.zip)

![image](https://user-images.githubusercontent.com/20011592/93247502-00518700-f7ac-11ea-98a3-8321b57deba4.png)

Please let me know If I am missing something.

**Comment by bclozel** [comment] 2020-09-15 18:40
Could you share your sample application?

I'm seeing a lot of `ConcurrentHashMap$Node` instances held by Tomcat `CachedResource` entries.

![image](https://user-images.githubusercontent.com/103264/93250595-549c3d00-f793-11ea-814e-9127d50b4389.png)

Requests to Spring endpoints should not create such cache entries - those are usually only linked to static resources served by Tomcat.

**Comment by rahulsingh336** [comment] 2020-09-15 19:26
attach below for reference:-
1.) sample application
2.) current heap dump
3.) memory leak - suspect zip
4.) visvual vm screen shot

[demomemory.zip](https://github.com/spring-projects/spring-boot/files/5227273/demomemory.zip)
[heapdump-1600197736545.zip](https://github.com/spring-projects/spring-boot/files/5227274/heapdump-1600197736545.zip)
[heapdump-1600197736545_Leak_Suspects.zip](https://github.com/spring-projects/spring-boot/files/5227275/heapdump-1600197736545_Leak_Suspects.zip)

![image](https://user-images.githubusercontent.com/20011592/93255365-73acc600-f7b7-11ea-8730-77a21872a85d.png)

**Comment by bclozel** [comment] 2020-09-15 19:53
Are you sure this is the right application?

The application you've sent doesn't build because the POM is broken (it's importing `spring-boot-starter-parent` instead of `spring-boot-parent`) and it's also using `1.5.18.RELEASE`, which is not maintained anymore.

I've fixed the POM and changed the version to `2.3.1 RELEASE` (the version noted in your original report) and I can't reproduce the behavior here. I'm running a lot of requests on that endpoint, as explained in your report and yourkit doesn't event show the cached entries in the object explorer.

Could you check again your sample app and make sure that you're running Yourkit against the actual sample and not some other deployed application?

**Comment by rahul-singh-incontact** [comment] 2020-09-16 03:21
Sorry in original question version marked seems incorrect . Issue is on version "1.5.18.RELEASE".
Please try with version "1.5.18.RELEASE".
And what do you mean by POM is broken? The sample app was generated from "https://start.spring.io/" and version was changed.
Please help me in understanding if I am missing some thing.

**Comment by rahulsingh336** [comment] 2020-09-16 03:23
Sorry in original question version marked seems incorrect . Issue is on version "1.5.18.RELEASE".
Please try with version "1.5.18.RELEASE".
And what do you mean by POM is broken? The sample app was generated from "https://start.spring.io/" and version was changed.
Please help me in understanding if I am missing some thing.

**Comment by rahulsingh336** [comment] 2020-09-16 03:55
attached your
[DemoApplication-2020-09-16.zip](https://github.com/spring-projects/spring-boot/files/5229544/DemoApplication-2020-09-16.zip)
kit memory snapshot
![image](https://user-images.githubusercontent.com/20011592/93290543-97dfc580-f7fe-11ea-9a92-9ce0d6422599.png)

**Comment by rahulsingh336** [comment] 2020-09-16 06:44
HeapHero shows below:-
![image](https://user-images.githubusercontent.com/20011592/93301469-227fef00-f816-11ea-96f0-f74697c9aec5.png)

**Comment by bclozel** [comment] 2020-09-16 07:47
Sorry about the `spring-boot-starter-parent` note, you're right.

Unfortunately `1.5.18.RELEASE` is not maintained anymore, so I'm closing this issue - if you can reproduce this on a supported version we'd be happy to take a look. For what it's worth, those objects should not leak as they have a TTL associated with them and they should be collected by the GC.

Thanks!

**Closed by bclozel** 2020-09-16 07:47 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by rahulsingh336** [comment] 2020-09-16 07:50
I have done test for spring boot 2.3.1 Release again and attached demo application. Memory grows in this case too but not in that much faced paced.

Attached :- 1.) Sample application with spring boot 2.3.1 release
                   2.) yourkit memory snapshot
                   3.) Visual VM screen shot
                    4.) Heap Dump Visual VM

[demomemory_2.3_1.zip](https://github.com/spring-projects/spring-boot/files/5230632/demomemory_2.3_1.zip)
[DemoApplication-Latest_yourKit_Memory.zip](https://github.com/spring-projects/spring-boot/files/5230637/DemoApplication-Latest_yourKit_Memory.zip)

![image](https://user-images.githubusercontent.com/20011592/93307878-25331200-f81f-11ea-920f-eb3977fbdff2.png)

[heapdump-1600242531158.zip](https://github.com/spring-projects/spring-boot/files/5230656/heapdump-1600242531158.zip)

**Comment by bclozel** [comment] 2020-09-16 08:13
Unlike your previous report, I'm not seeing Tomcat `CachedResource` entries in the "biggest objects" tab, nor any evidence of memory leak. Could you elaborate on where the leak is in this case?

I ran a local benchmark as well and could not find any leak.

To make sure there's a memory leak, could you run your benchmark, then once it's done force a GC with the profiler and take a memory snapshot. If the heap looks fine and the snapshot doesn't show any problem, this just means that the application is creating short-lived objects and that they'll be collected by the GC. This is not a memory leak but standard JVM behavior given the memory it's been allocated.

**Comment by rahulsingh336** [comment] 2020-09-16 08:23
I agree to your point. I will get back to you for benchmark results.

One question though:- Heap memory is rising and after certain level GC kicks in and it settles down. But what kind of these short objects are in this case?
