### ISSUE TITLE
Spring boot version greater than 2.1.5 causes a memory leak working with Atmosphere

### ISSUE THREAD

**Issue by frankivillalba** [spring-projects/spring-boot#18475] opened 2019-10-02 09:08 UTC
Hi,

We have currently a Spring boot project (2.1.5) working with Atmosphere (websockets) version 2.4.30.
After upgrading Spring boot to 2.1.8 (I don't know if it could be from the version 2.1.6), it causes a memory leak with Atmosphere sessions.

We can see in these images the same product with both versions:

Version 2.1.8 after 4-5 hours working:
![Screenshot 2019-10-02 at 11 01 24](https://user-images.githubusercontent.com/15781188/66031658-267f0800-e504-11e9-80b1-0285e5168667.png)

Version 2.1.5:
![Screenshot 2019-10-02 at 11 01 33](https://user-images.githubusercontent.com/15781188/66031663-28e16200-e504-11e9-8616-cd79d897b020.png)

Any help would be great!

Many thanks :).

PS: if it should be in other section, please let me know.

**Comment by wilkinsona** [comment] 2019-10-02 09:37
We're happy to try and help but we'll need more information to be able to do so. If you would like us to spend time investigating, please spend some time to providing a complete and minimal sample that reproduces the problem in the form of a zipped project attached to this issue.

Before doing that, you may want to try and narrow things down by looking at the changes in dependency versions between 2.1.5 and 2.1.8. For example, the classes in the heap suggest that you're using Jetty. Spring Boot 2.1.5 uses Jetty 9.4.18.v20190429 and Spring Boot 2.1.8 uses 9.4.19.v20190610.

**Comment by frankivillalba** [comment] 2019-10-02 09:55
Thank you for your soon feedback. Our current project is huge and I would have to extract the issue  to a small project and try to reproduce the issue. I will ask with the team, but I'm afraid that we won't have time to go for it. Any update I will let you know. I will check the dependencies as you say for Jetty, etc. between these Spring boot versions.

Many thanks!

**Comment by spring-issuemaster** [comment] 2019-10-09 10:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-10-16 10:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-10-16 10:31 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
