### ISSUE TITLE
Weblogic 12.2.1.3.0 Caused By: javax.naming.NameNotFoundException: While trying to look up /jms/MyCF in /app/webapp/myapp.war/923245655.; remaining name '/jms/MyCF'

### ISSUE THREAD

**Issue by zelenooq** [spring-projects/spring-boot#21990] opened 2020-06-16 20:56 UTC
Hi,
regarding this page:
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-jms-jndi
It should autoconfigure JmsTemplate.
By default,  it will look at  java:/JmsXA and java:/XAConnectionFactory. But, I changed this with this property:
spring.jms.jndi-name=java:/jms/MyCF

And I get this exception:

 Caused By: javax.naming.NameNotFoundException: While trying to look up /jms/MyCF in /app/webapp/myapp.war/923245655.; remaining name '/jms/MyCF'
	at weblogic.jndi.internal.BasicNamingNode.newNameNotFoundException(BasicNamingNode.java:1292)
	at weblogic.jndi.internal.ApplicationNamingNode.lookup(ApplicationNamingNode.java:144)
	at weblogic.jndi.internal.WLEventContextImpl.lookup(WLEventContextImpl.java:307)
	at weblogic.jndi.internal.WLContextImpl.lookup(WLContextImpl.java:435)
	at weblogic.jndi.factories.java.ReadOnlyContextWrapper.lookup(ReadOnlyContextWrapper.java:45)
	Truncated. see log file for complete stacktrace

I am using spring-boot 2.2.6.RELEASE

**Comment by mbhave** [comment] 2020-06-17 00:15
The exception appears to be coming from Weblogic and I'm not sure if there's anything we can do about this in Spring Boot. 

@zelenooq Please attach a minimal sample that we can run to reproduce the issue. Note that the latest version in the Spring Boot 2.2.x line is 2.2.8 so please consider upgrading to that.

**Comment by spring-issuemaster** [comment] 2020-06-24 00:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-07-01 00:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-07-01 00:20 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
