### ISSUE TITLE
Document that test slices should not be combined

### ISSUE THREAD

**Issue by G-Lem** [spring-projects/spring-boot#14981] opened 2018-10-27 19:57 UTC
Could you have a look at this issue ?
https://stackoverflow.com/questions/52527394/in-spring-boot-2-1-many-test-slices-are-not-allowed-anymore-due-to-multiple-boo?noredirect=1#

**Comment by philwebb** [comment] 2018-10-28 04:04
To summarize the stackoverflow question, the following test:

```java
@RunWith(SpringRunner.class)
@JdbcTest
@JsonTest
public class MyTest {

	@Test
	public void test() {
		System.out.println("Hello, World !");
	}

}
```

Fails with Spring Boot 2.1 due to:

```
java.lang.IllegalStateException: Configuration error: found multiple declarations of @BootstrapWith for test class [scratch.MyTest]: [@org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.autoconfigure.jdbc.JdbcTestContextBootstrapper), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.autoconfigure.json.JsonTestContextBootstrapper)]
	at org.springframework.test.context.BootstrapUtils.resolveExplicitTestContextBootstrapper(BootstrapUtils.java:166)
	at org.springframework.test.context.BootstrapUtils.resolveTestContextBootstrapper(BootstrapUtils.java:127)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:124)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTestContextManager(SpringJUnit4ClassRunner.java:151)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<init>(SpringJUnit4ClassRunner.java:142)
	at org.springframework.test.context.junit4.SpringRunner.<init>(SpringRunner.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:87)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:73)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```

**Comment by philwebb** [comment] 2018-10-28 04:06
The root cause is the change made for #14052 which means we now have two different bootstrap classes.

**Comment by philwebb** [comment] 2018-10-28 04:14
I wonder if we can meta-annotate `@JdbcTest` with `@SpringBootTest` and use `@AliasFor` to get the properties.

**Comment by dreis2211** [comment] 2018-10-28 09:59
Your idea works, but not for `@WebMvcTest` and `@WebFluxTest` because they already have dedicated bootstrap classes. Any thoughts? E.g. fixing it for the others with your idea and document the shortcomings of the other two?

**Comment by philwebb** [comment] 2018-10-28 15:12
> I wonder if multiple slices are supported at all officially.

@dreis2211 Thinking about this some more, I'm of the opinion that it worked by luck last time and it isn't something we should officially support. It's going to add a lot of complexity if we let people compose these annotations. For example, how would be combine the new `properties` attributes.

I'll switch this one to a documentation issue.

**Comment by philwebb** [comment] 2018-10-28 15:16
@G-Lem I just posted an answer to the stackoverflow question https://stackoverflow.com/a/53033018/1526192

**Comment by dreis2211** [comment] 2018-10-28 16:17
@philwebb For learning purposes I made a best effort implementation that seems to be working. If you're interested: https://github.com/spring-projects/spring-boot/compare/master...dreis2211:gh-14981

This also already includes a change in the documentation, which I'm happy to isolate in a dedicated PR if necessary.

Let me know what you think,

**Comment by wilkinsona** [comment] 2018-11-27 15:22
@dreis2211 A pull request of that documentation change would be great please, perhaps reworded slightly to make it sounds more definite. Perhaps by removing "officially" and replacing "you can pick" with "pick"?

**Comment by wilkinsona** [comment] 2018-11-27 15:46
Wow, the was fast! Thank you, @dreis2211. Closing in favour of #15310.

**Closed by wilkinsona** 2018-11-27 15:46 UTC
Labels: type: documentation
