### ISSUE TITLE
Binding to collection fails with unbound elements error if collection overridden in another property source

### ISSUE THREAD

**Issue by mschallar** [spring-projects/spring-boot#16290] opened 2019-03-22 09:32 UTC
Hello,

after migrated from Spring Boot 1.5.3.RELEASE to 2.1.3.RELEASE we've encountered a bug(?) with property binding.

The example code can be found [here](https://github.com/mschallar/spring-boot-configurationproperties-bug). It's a simple application with one property class that receives values from the application.yml via the @ConfigurationProperties annotation.

Starting the DemoApplication works fine.

But starting the simple DemoApplicationTests does not work, as the demo uses "test" profile and therefore the property class receives it's values from "application-test.yml".

The excepton does NOT occur if "ignoreUnknownFields" is NOT present (i.e., set to true).

```
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'demo-properties' to com.example.demo.DemoApplication$DemoProperties
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:249) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:225) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:208) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:190) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:83) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	... 43 common frames omitted
Caused by: org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException: The elements [demo-properties.data[2]] were left unbound.
	at org.springframework.boot.context.properties.bind.handler.NoUnboundElementsBindHandler.checkNoUnboundElements(NoUnboundElementsBindHandler.java:88) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.handler.NoUnboundElementsBindHandler.onFinish(NoUnboundElementsBindHandler.java:73) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.handleBindResult(Binder.java:235) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:222) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	... 47 common frames omitted
```

The bug does only appear when the list in application-test.yml is SMALLER than the list in application.yml.

Regards,
Manuel

**Comment by snicoll** [comment] 2019-03-22 09:41
Thanks for the sample, that is very useful. 

We've tighten the mechanism to merge complex types, see [the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-complex-type-merge).

I am not sure if we intended to throw an exception if you combine that with `ignoreUnknownFields`. If I add a `string6` in the test profile, the exception goes away as the full list has been replaced. This shouldn't be necessary IMO.

**Comment by mschallar** [comment] 2019-03-22 09:57
Correct, I've forgot to mention if you remove "ignoreUnknownFields" (--> will be set to true) from the ConfigurationProperties annotation, no exception will occur.

**Comment by mbhave** [comment] 2019-03-22 18:13
I think it's a bug and we shouldn't throw an exception since the list is completely overridden.

**Comment by rhamedy** [comment] 2019-03-23 15:03
I would be happy to work on this issue should the `team` decide that it should be fixed 🙂

**Comment by mbhave** [comment] 2019-03-25 20:31
Thanks for the offer @rhamedy but I'm already looking into this.

**Closed** 2019-03-25 23:04 UTC
Labels: type: bug

**Comment by anatoliy-balakirev** [comment] 2020-02-11 12:58
We're getting exactly the same issue with spring boot 2.2.4. Based on tags here, it looks like it was fixed in 2.1.4 and 2.3.0. Is that correct? Is it planned to be fixed in some 2.2.x as well?

**Comment by snicoll** [comment] 2020-02-11 13:05
@anatoliy-balakirev all fixes are merged forward. This is fixed in 2.1, 2.2 and master. If you believe you've found an issue with Spring Boot, please build a small sample (a zip or a link to a github repo) with a test that shows the problem and create a new issue.

**Comment by anatoliy-balakirev** [comment] 2020-02-11 17:36
@snicoll thanks for info!
IMO, an issue I mentioned is not some new one, but rather just a bit different flavor of the current. The only difference is that in my case properties are not plain strings, but rather some object with a field. I've forked an original sample repo and adjusted it to use the latest spring boot / config with a nested property:
https://github.com/anatoliy-balakirev/spring-boot-configurationproperties-bug
just run `mvn clean test` and you'll get:
```
[ERROR] contextLoads  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'demoApplication.DemoProperties': Could not bind properties to 'DemoApplication.DemoProperties' : prefix=demo-properties, ignoreInvalidFields=false, ignoreUnknownFields=false; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'demo-properties' to com.example.demo.DemoApplication$DemoProperties
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'demo-properties' to com.example.demo.DemoApplication$DemoProperties
Caused by: org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException: The elements [demo-properties.nested-data[0].data,demo-properties.nested-data[1].data,demo-properties.nested-data[2].data] were left unbound.
```

**Comment by snicoll** [comment] 2020-02-11 17:37
@anatoliy-balakirev this issue is closed in `2.1.4` so we're not going to reopen it. Can you please move that comment to a new issue?

**Comment by snicoll** [comment] 2020-02-11 18:45
@anatoliy-balakirev before you do, please review the comments I've added to your sample. I believe it is wrong and the exception is legit and doesn't reproduce this issue.

**Comment by anatoliy-balakirev** [comment] 2020-02-11 20:44
@snicoll sorry, I might be missing something, but which comments you mean?

**Comment by mbhave** [comment] 2020-02-11 22:18
@anatoliy-balakirev I think Stephane is talking about [these comments](https://github.com/anatoliy-balakirev/spring-boot-configurationproperties-bug/commit/12bbbc9df9b123fa711e8e992435270265622f8f#r37236571) he added to your sample.

**Comment by anatoliy-balakirev** [comment] 2020-02-12 06:09
@mbhave thanks! not using github that often these days.

@snicoll you are right, I was trying to create something really quick yesterday after work and generated some rubbish, sorry (we have this same error with our real project, so I didn't test that `DemoApplication` properly). Adjusted it now. Still, problem is there: `DemoApplication` can be started, while `DemoApplicationTests` fails with:
```
Caused by: org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException: The elements [demo-properties.nested-data[2].data] were left unbound.
	at org.springframework.boot.context.properties.bind.handler.NoUnboundElementsBindHandler.checkNoUnboundElements(NoUnboundElementsBindHandler.java:83)
	at org.springframework.boot.context.properties.bind.handler.NoUnboundElementsBindHandler.onFinish(NoUnboundElementsBindHandler.java:71)
	at org.springframework.boot.context.properties.bind.Binder.handleBindResult(Binder.java:340)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:321)
	... 47 more
```

**Comment by anatoliy-balakirev** [comment] 2020-02-12 06:22
As discussed, created a dedicated issue for that: https://github.com/spring-projects/spring-boot/issues/20134
