### ISSUE TITLE
Urgent !!! Both @Autowried and @Resource cannot be injected

### ISSUE THREAD

**Issue by puyongqqq** [spring-projects/spring-boot#25791] opened 2021-03-25 02:27 UTC
Hello. My project A split out project B, project B introduced part of project A module, and then added B to A to start, and then the following error message appeared. SpringBoot version is 5.1.5

> org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'kaasPropertyAttrDaoService' is expected to be of type 'com.koalii.kaas.system.service.KaasPropertyAttrDaoService' but was actually of type 'com.koalii.kaas.system.service.KaasPropertyAttrDaoService'

But in my Application class into the 'KaasPropertyAttrDaoService, can print the object.

>   ------ com.koalii.kaas.system.service.KaasPropertyAttrDaoService@6be9617e

**Comment by bclozel** [comment] 2021-03-25 06:04
Closing as a duplicate of spring-projects/spring-framework#26723

**Closed** 2021-03-25 06:04 UTC
Labels: for: external-project, status: invalid
