### ISSUE TITLE
Make switching to json log format easier

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-boot#22117] opened 2020-06-26 08:41 UTC
Imho it is quite a common practice to have logs in json format, so it can be easily digested by logstash, graylog, splunk, etc.

I think would be nice If spring boot would provide a simple option to switch the log format to json (and disable the banner at the same time).
Currently you need to add some dependencies and override the entire log configuration. It would be nice to have a starter and a switch for it.

**Comment by wilkinsona** [comment] 2020-06-26 10:12
Thanks for the suggestion, @joshiste. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/5479. Can you please comment on that issue with some more details about how you are manually configuring things. We can then consider what, if anything, we feel that we could do to simplify it.

**Closed by wilkinsona** 2020-06-26 10:12 UTC
Labels: status: waiting-for-triage

**Comment by joshiste** [comment] 2020-06-26 11:39
Hmm I did a quick search but didn't found that one. I'll stick to that.
