### ISSUE TITLE
Jetty 9.4 logs DefaultSessionIdManager configuration at startup even if Spring Session is used

### ISSUE THREAD

**Issue by okohub** [spring-projects/spring-boot#8258] opened 2017-02-10 19:14 UTC
We are using Spring Boot in 1.5.1 in our applications and session management is handled by Spring Session. After migrating to Jetty 9.4 with Boot, we saw some interesting logs like this:

```
INFO 1448 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
INFO 1448 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
INFO 1448 --- [           main] org.eclipse.jetty.server.session         : Scavenging every 600000ms
```

Is it an expected behaviour? We are not using Jetty based session management, and before this upgrades there were no logs like this.

Thanks in advance.

**Comment by bclozel** [comment] 2017-02-10 20:47
In 9.4, the Jetty team [significantly rewrote their session management support](https://www.eclipse.org/jetty/documentation/current/session-management.html#_changes_in_session_architecture). So it wouldn't be surprising if the logging behavior changed.

Is Spring Session still working as expected?
Is there something not working properly?

**Comment by spring-issuemaster** [comment] 2017-02-17 20:48
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-02-24 20:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by okohub** [comment] 2017-02-25 15:12
Sorry for the late response :) @bclozel 

cc @philwebb 

I just added a simple application that demonstrates situation. here: 

https://github.com/okohub/jetty94-session-demo

You should check tests for problem. I think Jetty Session Manager shouldnt be configured when I use Spring Session.

**Comment by cemo** [comment] 2017-02-26 00:01
Jetty Session Manager must be never configured. It was before disabled by necessary configurations. Current regression can cause some serious problems. Memory leaks etc...

**Comment by bclozel** [comment] 2017-02-27 10:57
@okohub I'm certainly not the team member with the most experience in Jetty and Spring Session, but I've got a few questions:

* Could you explain the rationale behind this use case? Why map an error back to that Controller instead of using the regular error page mechanism in Boot. I get that this is a repro test case, but anything that describes the problem you actually encountered really helps.
* Back to my original question - is Spring Session still working as expected? Is there something not working properly?

I've tried the same example with Spring Boot 1.4.4 and Jetty 9.3, and this has the same behavior.
The `SessionRepositoryFilter` is indeed configured by default to `FORWARD, INCLUDE, REQUEST, ASYNC`. So the filter is not involved in ERROR dispatches and this is probably why your sample is showing that behavior.
We recently aligned our configuration to Spring Session's with gh-8288; which means that the filter is now registered for `REQUEST, ASYNC, ERROR`.

@cemo Can you point to the part that disabled previously the Session Manager configuration in Jetty 9.3? Can you elaborate on the potential issues you're describing? Wouldn't that be true for all Servlet containers then (i.e. should session management be disabled for all containers when Spring Session is enabled and why?).

**Comment by cemo** [comment] 2017-02-27 11:26
@bclozel I have unfortunately could not be sure about that but here is the [relevant part]. 
The problem is that jetty native map session can easily consume all heap space. The worst part is that in case a combination with a non sticky session load balancer, requests are distributed equally in different servers. In this case user's session is invalidated for each request and for each request a new session is created. (I came across this situation.)  

I believe that user must explicitly enable native session managers. In case a Spring Session dependency, native session must be completely disabled as Spring Session has already superior in memory session features.

[relevant part]: https://github.com/spring-projects/spring-boot/blob/v1.4.4.RELEASE/spring-boot/src/main/java/org/springframework/boot/context/embedded/jetty/JettyEmbeddedServletContainerFactory.java#L377

**Comment by rwinch** [comment] 2017-03-08 03:59
@cemo I don't this this is a problem.

In ever Spring Session application, native session handling continues to be enabled. However, Spring Session's `SessionRepositoryFilter` will override the implementation of `HttpSession` so that the native session handling is never used. This means that the heap will not get consumed when more `HttpSession` instances are created (because the native session manager will not think a session was ever created).

The only way I see this being an issue is if for some reason the native session manager is actually creating sessions. However, this should not be the case given we override the `HttpSession` on `HttpServletRequest`.

**Comment by cemo** [comment] 2017-03-08 06:50
But if it is not used, why it is not disabled at all when spring session is available?

**Comment by bclozel** [comment] 2017-03-08 09:21
@cemo How could we disable that session manager since [Jetty is defining one by default anyway](https://www.eclipse.org/jetty/documentation/current/sessions-details.html#_sessionidmanager). We could replace it by a no-op manager but I don't see the point of doing that, since as @rwinch pointed out, this session manager is never used.

I've just renamed the issue, which boils down to:
* Jetty 9.4 changed its session architecture and is logging its configuration at startup
* Spring Session is registered with `FORWARD, INCLUDE, REQUEST, ASYNC` dispatcher types and is not involved in ERROR dispatches (at least until gh-8288)

I don't see any problem with the current situation so I'm closing this issue now.
Feel free to reopen this issue if you've got a repro project that demonstrates an actual memory issue or bug in the current behavior.

**Closed by bclozel** 2017-03-08 09:21 UTC
Labels: for: team-attention, status: feedback-provided
