### ISSUE TITLE
Gradle plugin: dependencies with duplicated artifact name

### ISSUE THREAD

**Issue by vforchi** [spring-projects/spring-boot#20039] opened 2020-02-05 10:30 UTC
I am not sure whether this is a bug, but I noticed an inconsistency between the output of the bootJar task in gradle and the equivalent maven artifact.

I have a gradle project that includes two dependencies with the same name (`client-1.0.jar`): the gradle plugin puts them in the same location in the jar file (`BOOT-INF/lib`) and when I try to run the jar file I get a `NoClassDefFound` exception. If I build the same project with maven it works.

The maven plugin looks for duplicated dependency names, and renames them if necessary (See [here](https://github.com/spring-projects/spring-boot/blob/7cb13eb16eb93dec16fc08146795c7f28d1e351b/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/ArtifactsLibraries.java#L76)). 

Would it be possible to do the same in the gradle plugin?

**Comment by bclozel** [comment] 2020-02-05 10:45
Closing as a duplicate of #16241

**Closed by bclozel** 2020-02-05 10:45 UTC
Labels: status: waiting-for-triage
