### ISSUE TITLE
Document that @Order cannot be used on a Filter's @Bean method to set the Filter's order

### ISSUE THREAD

**Issue by joca-bt** [spring-projects/spring-boot#18266] opened 2019-09-18 07:57 UTC
We've defined our custom filters (`javax.servlet.Filter`) through `@Bean`s in a `@Configuration` class. Something like:

```
@Configuration
public class MyWebMvcConfigurer implements WebMvcConfigurer {
    ...
    @Bean @Order(200)
    public Filter1 filter1() {
        return new Filter1();
    }
    @Bean @Order(100)
    public Filter2 filter2() {
        return new Filter2();
    }
    ...
}
```

However, the filters are being called in the order they appear in the code (Filter1 then Filter2) instead of the order defined by the annotations (Filter2 then Filter1). For other types of objects (non `javax.servlet.Filter`) the `@Order`s are being respected when the beans are injected.

If we define the filter and their ordering using `@Component` + `@Order` on the filter classes themselves or via `@Bean`s of type `FilterRegistrationBean` + `FilterRegistrationBean.setOrder()` then the order is respected.

Is this anything specific to filters? Is this documented somewhere and we've missed that? Or is this an issue?

**Comment by wilkinsona** [comment] 2019-09-18 08:20
This is a duplicate of #18210. Let's use this to clarify the documentation.

**Comment by Petros0** [comment] 2019-09-30 12:13
Hello,

how and where should be it documented?
Should it be a Javadoc comment at the Order annotation?

**Comment by wilkinsona** [comment] 2019-10-01 14:24
Somewhere in Spring Boot's reference documentation, probably in [this section](https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/htmlsingle/#boot-features-embedded-container-servlets-filters-listeners-beans).

**Closed** 2019-11-05 10:09 UTC
Labels: type: documentation
