### ISSUE TITLE
Consider initialization of multiple datasources

### ISSUE THREAD

**Issue by krabaey** [spring-projects/spring-boot#13417] opened 2018-06-07 21:19 UTC
Sample project in attach with failing test cases, run via mvnw test

Two datasources are configured, each with a schema and data init file, however only the schema and data initialization from the primary datasource is executed.

I would have expected the data/schema init files both would be executed in their respective configured datasource.

Main reason seems to be that the spring `DataSourceInitializerPostProcessor` requests a `DataSourceInitializerInvoker` singleton which will then only execute intialization once.

A second issue seems to be that the `DataSourceInitializerInvoker` does not check the DataSourceSchemaCreatedEvent source to match the current datasource, so it might react to the wrong one.

Issue seems to be present from at least Spring Boot 2.0.0
[demo.zip](https://github.com/spring-projects/spring-boot/files/2082087/demo.zip)

**Comment by philwebb** [comment] 2018-06-07 21:57
This is the expected behavior with the current implementation. The initializer currently only works with the `@Primary` datasource. The reason that `foo-schema.sql` is used is because you're also registering a `DataSourceProperties` bean as `@Primary` which will replace the usual `spring.datasource` properties.

So multiple datasource you'll currently need to use `ResourceDatabasePopulator` directly.

**Comment by philwebb** [comment] 2018-06-07 21:58
See also #9528

**Comment by snicoll** [comment] 2018-06-08 04:55
We have discussed the possibility to auto-configure multiple data sources and didn’t execute on it. For that reason, I think this issue should be closed.

**Comment by wilkinsona** [comment] 2018-06-08 11:34
But with #9528 we may end up with an API that can be used to register a DataSource for initialisation. We'd then use that API for the auto-configured DataSource and make it available to users for use with their own, manually configured data sources. If anything, I could see this being or becoming a duplicate of #9528.

**Comment by yhjlsy123** [comment] 2019-01-29 09:33
package com.xy.bist.config;

import org.springframework.batch.core.configuration.annotation.BatchConfigurer;
import org.springframework.batch.core.configuration.annotation.DefaultBatchConfigurer;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.jdbc.DataSourceProperties;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.JdbcTemplate;

import com.zaxxer.hikari.HikariDataSource;

@Configuration
public class DataSourceConfig {

	@Bean
	@Primary
	@ConfigurationProperties("spring.datasource.master")
	public DataSourceProperties firstDataSourceProperties() {
		return new DataSourceProperties();
	}

	@Bean(name = "master")
	@Qualifier("master")
	@Primary
	@ConfigurationProperties(prefix = "spring.datasource.master")
	public HikariDataSource primaryDataSource() {
		return firstDataSourceProperties().initializeDataSourceBuilder().type(HikariDataSource.class).build();

	}

	@Bean
	@ConfigurationProperties("spring.datasource.slave")
	public DataSourceProperties secondarytDataSourceProperties() {
		return new DataSourceProperties();
	}

	@Bean(name = "slave")
	@Qualifier("slave")
	@ConfigurationProperties(prefix = "spring.datasource.slave")
	public HikariDataSource secondaryDataSource() {
		return secondarytDataSourceProperties().initializeDataSourceBuilder().type(HikariDataSource.class).build();
	}

	@Primary
	@Bean
	public JdbcTemplate originalJdbcTemplate(@Qualifier("master") HikariDataSource datasurce) {
		return new JdbcTemplate(datasurce);
	}

	@Bean
	public JdbcTemplate destJdbcTemplate(@Qualifier("slave") HikariDataSource datasurce) {
		return new JdbcTemplate(datasurce);
	}

	@Bean
	BatchConfigurer configurer(HikariDataSource dataSource) {
		return new DefaultBatchConfigurer(dataSource);
	}

}
erro:
Caused by: java.lang.IllegalStateException: To use the default TaskConfigurer the context must contain no more than one DataSource, found 2

**Comment by yhjlsy123** [comment] 2019-01-29 09:34
What should I do about it？

**Comment by snicoll** [comment] 2019-01-29 09:37
@yhjlsy123 do not hijack the issue tracker with your questions: .as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by philwebb** [comment] 2019-06-14 15:58
See #15732

**Comment by philwebb** [comment] 2019-06-14 16:00
Closing in favor of ##9528

**Closed by philwebb** 2019-06-14 16:00 UTC
Labels: status: superseded
