### ISSUE TITLE
Add RabbitMQ Connection Factory Type

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-boot#21284] opened 2020-04-30 22:15 UTC
Spring AMQP has two new connection factories in its next release

(This issue should be scheduled for Boot 2.4; I am not releasing Spring AMQP 2.3 until later in the year but I didn't want to forget about it).

[Docs here](https://docs.spring.io/spring-amqp/docs/2.3.0.BUILD-SNAPSHOT/reference/html/#choosing-factory).

`spring.rabbitmq.connection-factory-type`

`pooledChannel`
`threadChannel`
`caching`

Consider defaulting to `pooledChannel` unless any `cache.*` properties are explicitly set or the `publisher-confirm-type=correlated`.

**Comment by iliasmentz** [comment] 2020-06-09 12:42
Hello, 

is this still up for grabs? Can I give it a try?

**Comment by snicoll** [comment] 2020-06-09 12:44
It is. Please go ahead @iliasmentz and let us know how it goes.

**Comment by snicoll** [comment] 2020-09-11 14:08
@iliasmentz how is it going? We're approaching our next milestone soon and I'd like to make sure this one is resolved. Given you're assigned to this issue, can you please give us an update? Thanks!

**Comment by iliasmentz** [comment] 2020-09-15 11:58
hey @snicoll, apologies for my late response.
to be honest I was kind of lost when I tried to implement it, as I couldn't understand how the properties should decide on which factory should be used because many of them have default values.
I would love to give it another try but I would hate to be the bottleneck for the next milestone.

Please let me know how would do you think.

**Comment by snicoll** [comment] 2020-09-15 12:51
@iliasmentz thank you for the feedback. The problem is that I didn't really looked at the issue and assumed you had before asking if you could contribute to it. 

Looking at it more closely, it isn't certainly easy. I am going to remove the assignment for now. If you find another issue, please let us know and we'll do our best to assist.

@garyrussell this `connection-factory` is quite impactful as we always assumed `CachingConnectionFactory` and some configuration properties are specific to this implementation. This leaves us with an odd situation where some properties don't make sense anymore if you chose a different implementation. What we should do there is probably move them to a sub-namespace and deprecate the specific ones in the root namespace.

For instance `is-publisher-returns` and `publisher-confirm-type` are on the root. This makes sense considering there is a default method but only 1 implementation out of 3 actually allow to tune that setting. Introducing auto-configuration for the other 2 could be quite misleading with the current arrangement. Thoughts?

**Comment by garyrussell** [comment] 2020-09-15 13:01
@snicoll I see - yes; agreed - let's just close this; if someone wants to use one of the new factories they can just define it as a `@Bean` (disabling auto-config for the default factory).

**Comment by snicoll** [comment] 2020-09-15 13:56
Alright. I am going to close this and we can revisit if necessary.

**Closed by snicoll** 2020-09-15 13:56 UTC
Labels: type: enhancement
