### ISSUE TITLE
Jersey doesn't always work with Spring Boot fat jars

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#1468] opened 2014-08-29 02:44 UTC
See https://java.net/jira/browse/JERSEY-2085

We might be able to create a workaround locally

**Comment by nick-pww** [comment] 2015-03-20 19:32
It looks like there are also issues with packaged WAR files and trying to find any classes in, not just those inside a jar file:


    Caused by: java.io.FileNotFoundException: /Users/nick/Development/frontend-app/target/frontend-app.war!/WEB-INF/classes (No such file or directory)
                at java.io.FileInputStream.open(Native Method)
                at java.io.FileInputStream.<init>(FileInputStream.java:138)
                at java.io.FileInputStream.<init>(FileInputStream.java:93)
                at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
                at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
                at java.net.URL.openStream(URL.java:1038)
                at org.glassfish.jersey.server.internal.scanning.JarZipSchemeResourceFinderFactory.getInputStream(JarZipSchemeResourceFinderFactory.java:173)
                at org.glassfish.jersey.server.internal.scanning.JarZipSchemeResourceFinderFactory.create(JarZipSchemeResourceFinderFactory.java:84)

The WEB-INF/classes folder is inside the war file. 

Also, the app does work when just running from the maven plugin.

**Comment by wuqunfei** [comment] 2015-09-02 10:19
Is there any solution about this bug now?

**Comment by wilkinsona** [comment] 2015-09-02 11:03
@wuqunfei The bug is in Jersey. There's an [updated pull request](https://github.com/jersey/jersey/pull/135) but it's yet to be merged by the Jersey team. In the meantime you can use the [workaround described here](https://github.com/spring-projects/spring-boot/issues/1345#issuecomment-51502294)

**Comment by wuqunfei** [comment] 2015-09-14 09:36
I fix it, I have arlreay test on my local, @wilkinsona 
https://github.com/alexleigh/jersey/commit/198687f9f00404cb2a81e0b8edd230959baea18b
If we could merge into Jersey 2.14, this quesiton could close.

**Comment by wilkinsona** [comment] 2015-09-14 10:37
Thanks. Judging by the branches in the repository, it doesn't look like the Jersey team are maintaining 2.14 anymore. If you believe the existing PR is defective, a new PR against master (currently building 2.22) is probably the best bet. The Jersey team are best placed to then decide if and how it should be backported to earlier versions.

**Comment by wuqunfei** [comment] 2015-09-14 11:55
I make a pull request into 2.21.x branch to jesery, https://github.com/jersey/jersey/pull/196 now, we are waiting now.

**Comment by driverpt** [comment] 2016-11-12 12:28
@philwebb , i think it's best to make a Rest Easy Spring Boot available. Jersey maintainers aren't interested to solve this issue.

**Comment by driverpt** [comment] 2016-12-06 11:32
I found out that there is a problem with the way Jersey does ClassPath Scanning. It works well with "Standard" Jars. Otherwise, it won't work. I'll keep investigating the alternatives.

**Comment by driverpt** [comment] 2016-12-12 16:49
Created an PR in Jersey Repository that will allow us to implement a Custom Scanner for Spring Boot Jars.

Reference: https://github.com/jersey/jersey/pull/250

**Comment by mjschuurman** [comment] 2016-12-15 15:25
I had the same issue, for me it worked by changing spring-boot dependency from 1.4.2.RELEASE to 1.3.8.RELEASE. Hopefully they fix it in a future release version.

**Comment by driverpt** [comment] 2016-12-15 15:26
@mjschuurman , problem is limitations with the JarFile/JarEntry Class path scanning within the Jars, needs custom implementation for Spring Boot

**Comment by mjschuurman** [comment] 2016-12-15 15:35
@driverpt oke, but then why does it work for the 1.3.8.RELEASE version?

**Comment by driverpt** [comment] 2016-12-15 15:38
Because Spring Boot 1.4 changed the internal Jar Structure to facilitate the Spring Boot bootstrap process.

**Comment by driverpt** [comment] 2017-01-05 10:40
@zhishengzhang , That means that your "core code" needs to be in a separate Jar.

**Comment by driverpt** [comment] 2017-01-10 13:39
I've been trying to create a workaround for the `packages()` method.

So far i came up with this:

```
ClassPathScanningCandidateComponentProvider provider = new ClassPathScanningCandidateComponentProvider(false);
    provider.addIncludeFilter(new RegexPatternTypeFilter(Pattern.compile(".*")));
    Set<BeanDefinition> candidateComponents = provider.findCandidateComponents("foo.bar.baz");
    for (BeanDefinition candidateComponent : candidateComponents) {
      register(ClassUtils.resolveClassName(candidateComponent.getBeanClassName(), ClassUtils.getDefaultClassLoader()));
    }
```

It still throws a couple of warnings for some classes, but i'll try to improve this code.

**Comment by mihu86** [comment] 2017-02-16 18:29
My solution was silimar (maybe replacing Class.forName() with ClassUtils is a good point):

```java
ClassPathScanningCandidateComponentProvider scanner = new ClassPathScanningCandidateComponentProvider(false);
scanner.addIncludeFilter(new AnnotationTypeFilter(Provider.class));
scanner.addIncludeFilter(new AnnotationTypeFilter(Path.class));
// add more annotation filters if you need
config.registerClasses(scanner.findCandidateComponents("your.package.to.scan")
    .stream().map(beanDefinition -> {
        try {
            return Class.forName(beanDefinition.getBeanClassName());
        } catch (ClassNotFoundException e) {
            throw new IllegalStateException("Cannot load REST implementation classes.");
        }
    }).collect(Collectors.toSet()));
```

**Closed as completed** 2018-03-22 15:05 UTC

**Comment by Tapan2064** [comment] 2019-11-21 12:23
I have faced the same problem. Workaround solution to it.

  The class which extends the ResourceConfig class must contain `@Component` annotation, At run time when spring will create the object of that class, it will load the default constructor of that class and then jersey will register all the provided class. But here is a catch, all the class must have `@Component` annotation, else Spring will not able to create the object of that related class and at the end, the jersey will not able to register that class.  
 **NOTE:** To register the class in Jersey, use the `register` method, `packages` method is not working in this workaround. 

    
    @Component
    @ApplicationPath("/api")
    public class ABCJersey extends ResourceConfig {
    
    	public ResourceManagerJersey() {
    		// packages("com.currentobject.ABCObject ");
    		// packages("com.currentobject.exceptionmapper");
    
    		// Controller-resource layer
    		register(ABCResources.class);
    		register(ABCCredential.class);
    	
    	}
    
    }
    
    @Component("ABCResources ")
    @Path("/rm")
    public class ABCResources {
    ----
    }

**Comment by landy8530** [comment] 2019-11-30 10:02
I found this issue today when I integrated Sprint Boot and Jersey project as well, thanks for [mihu86 ](https://github.com/mihu86)'s solution, and the problem has been fixed now.
In addition, I would ask Spring Boot owner, when this issue can be fixed through below solution?
```java
@Component
@ApplicationPath("xhf/api")
public class JerseyConfig extends ResourceConfig {
    public JerseyConfig() {
        packages("com.xhf.erp.web.rest");
    }
}
```
If this issue has been fixed ,please help tell me the issue number or version no. I appreciate with your all support.
Thanks.

**Comment by wilkinsona** [comment] 2019-11-30 10:55
@landy8530 The fix needs to be made in Jersey. There are Is an issue and a PR mentioned above. For ease of reference, they are:

- https://github.com/jersey/jersey/issues/2357
- https://github.com/eclipse-ee4j/jersey/pull/3818

At the time of writing, they have yet to be fixed/merged.
