### ISSUE TITLE
No dependency management is provided for Mockito's new mockito-junit-jupiter module

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#14973] opened 2018-10-26 17:34 UTC
Would it make sense to manage  mockito-junit-jupiter - since you already manage mockito and junit versions? Then it is easier to add this dependency and have the version harmonize with boot

**Comment by bclozel** [comment] 2018-10-26 19:07
I believe this is a duplicate of #14716 and #14736. I'm closing this now.

**Comment by nishantraut** [comment] 2018-10-27 14:31
Hi @wilkinsona Can you please guide on this, would like to work on it. Thanks

**Comment by philwebb** [comment] 2018-10-27 17:31
@nishantraut Thanks for the offer, but this is a fairly simple dependency addition so there's no need for a PR.

**Comment by wilkinsona** [comment] 2018-10-29 10:35
We've had dependency management for the new module since 2.1 M1.

Duplicate of #12890.

**Closed by wilkinsona** 2018-10-29 10:35 UTC
Labels: type: bug
