### ISSUE TITLE
The Maven Assembly plugin should handle aop.xml in a better way

### ISSUE THREAD

**Issue by Gilead** [spring-projects/spring-boot#10717] opened 2017-10-20 15:47 UTC
It seems that as a result of #7587 aop.xml is being moved out of the META-INF package by the Spring Boot Maven Assembly plugin. I'm sure it was causing issues but the result is that, from what I see, AspectJ doesn't recognise it under the BOOT-INF/... at all.

I just spent an entire day fighting with the plugin to put it in a place visible to AspectJ. I finally found out that using Maven resource plugin to manually copy aop.xml to org.aspectj package works and the file is finally seen by AspectJ.

If leaving aop.xml in META-INF is not viable for some reason then perhaps the assembly plugin should move META-INF/aop.xml to BOOT-INF/classes/org/aspectj/aop.xml where it is actually seen by AspectJ.

As a test case please consider this simple configuration file:
`
<aspectj>
    <weaver options="-verbose">
        <dump within="com.example..*" />
    </weaver>
</aspectj>
`

If you put that file into META-INF it'll be moved to BOOT-INF where it does nothing. If you include it manually in the org.aspectj package then AspectJ does see the file and acts accordingly.

**Comment by wilkinsona** [comment] 2017-10-20 18:39
Unfortunately a single line of XML isn’t enough for us to diagnose the problem. If you would like us to spend some time investigating, please spend the time to produce a complete sample that reproduces the behaviour you have described.

**Comment by Gilead** [comment] 2017-10-20 22:45
I will create a sample repo on Monday; in two flavours - vanilla and
infused with Maven resource plugin copying the file separately.

On 20 Oct 2017 19:40, "Andy Wilkinson" <notifications@github.com> wrote:

Unfortunately a single line of XML isn’t enough for us to diagnose the
problem. If you would like us to spend some time investigating, please
spend the time to produce a complete sample that reproduces the behaviour
you have described.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spring-projects/spring-boot/issues/10717#issuecomment-338289756>,
or mute the thread

**Comment by spring-issuemaster** [comment] 2017-10-28 05:54
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-11-04 05:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-11-04 05:54 UTC
