### ISSUE TITLE
Update Production Ready Features documentation to reflect that endpoint IDs are no longer configurable

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#10862] opened 2017-11-01 10:34 UTC

**Comment by snicoll** [comment] 2017-11-02 08:58
Isn't that, to some extend, a duplicate of #10001 ?

**Comment by wilkinsona** [comment] 2017-11-02 09:59
Yeah, it could be. I wanted to make sure it wasn’t missed. This issue is for correcting existing documentation that’s now incorrect rather than adding new documentation.

**Comment by snicoll** [comment] 2017-11-02 10:03
Fair enough, let's keep it

**Closed** 2017-11-12 10:54 UTC
Labels: priority: normal, type: documentation
