### ISSUE TITLE
Spring boot and Websphere liberty profile transaction manager

### ISSUE THREAD

**Issue by mmbouraoui** [spring-projects/spring-boot#14178] opened 2018-08-23 08:42 UTC
With the following confiuration :
WLP : wlp-javaee8-18.0.0.2
Spring boot : 2.0.4.RELEASE
I see that HibernateJPAConfiguration is selecting the org.hibernate.engine.transaction.jta.platform.internal.WebSphereExtendedJtaPlatform which did not work for me.
Caused by: java.lang.UnsupportedOperationException
	at org.hibernate.engine.transaction.jta.platform.internal.WebSphereExtendedJtaPlatform$TransactionManagerAdapter.suspend(WebSphereExtendedJtaPlatform.java:131)
	at org.hibernate.resource.transaction.backend.jta.internal.DdlTransactionIsolatorJtaImpl.<init>(DdlTransactionIsolatorJtaImpl.java:51)

Changing to org.hibernate.engine.transaction.jta.platform.internal.WebSphereLibertyJtaPlatform worked.
Thans kor your help.

**Comment by snicoll** [comment] 2018-08-23 08:47
Duplicate of #8926

**Closed by snicoll** 2018-08-23 08:47 UTC
Labels: status: waiting-for-triage
