### ISSUE TITLE
Spring Boot + Spring Data failfast rules when db server not available

### ISSUE THREAD

**Issue by yuranos** [spring-projects/spring-boot#13486] opened 2018-06-15 07:35 UTC
Hi,

I've been working with Boot + Data for multiple DB types and I noticed that it's not properly documented anywhere on where Spring Boot will draw the line and refuse to start.
This is a very important concept in CI/CD environment where the deployment is fully automated under the hood. A lot of orchestration is usually reliant on pinging running processes or reacting to exit codes. 

Now, let me describe with some usecases what I mean:

- I have 2 mongo db-based apps. I'm starting them to make sure everything is Ok. However, I forgot that I haven't started mongo server yet. And yet one app will fail to start and another one will print a connection error stacktrace but keep on running. It took me a while to figure out that the one that fails had a `@Document` with `@Index` in it, while the other one didn't. So, by just adding/deleting `@Index` annotation I can significantly impact the way Spring Boot react to mongo DB availability.

- For MySql-based apps, the behavior is different. There, if there's not a single `@Table/@Entity`, the app will start, but once you added at least one entity, the app will fail to start;

- For Cassandra-based apps, it seems that the server connection is absolutely mandatory, even if there's not a single line of code associated with the DB layer.

I think it's clear what I'm trying to convey.
Does anyone have an idea on how this can be systematized? Maybe, there just need to be a flag to always failfast if DB is not available regardless of its type.

**Comment by wilkinsona** [comment] 2018-06-15 08:22
Thanks for the detailed report, @yuranos. This is (largely) a duplicate of #11325. Can you please add your findings about the differences in behaviour when you use `@Index` or have an entity to that issue?

**Closed by wilkinsona** 2018-06-15 08:22 UTC
Labels: status: waiting-for-triage

**Comment by yuranos** [comment] 2018-06-15 08:34
Hi @wilkinsona ,
Thanks for the ref, seems very similar to what I'm experiencing indeed!
Most our services are mongo-db based, so I've tried a multitude of apps, but was never able to pinpoint a rootcause, so I was desparately trying different examples I found online and wrote myself, and accidentally stumbled upon mkyong's post https://www.mkyong.com/spring-boot/spring-boot-spring-data-mongodb-example/ and that's when it downed on me.
The entity is as follows:
```
@Document(collection = "domain")
public class Domain {

    @Id
    private long id;

    //If I leave it like this, an app fails to start, if I comment the next line, it starts up successfully.
    @Indexed(unique = true)
    private String domain;

    private boolean displayAds;

}
```
