### ISSUE TITLE
Duplicate core names in Solr Url in Spring Boot 1.5.1

### ISSUE THREAD

**Issue by mintster** [spring-projects/spring-boot#8327] opened 2017-02-18 22:45 UTC
This issue was posted to StackOverflow in this post:

[duplicate cores in url sent to solr from spring boot solr data](http://stackoverflow.com/questions/41989663/duplicate-cores-in-url-sent-to-solr-from-spring-boot-solr-data) 

It describes the Solr Url duplicate core name issue pretty well. 

I have encountered the same issue moving to Spring Boot 1.5.1 from 1.4.4 without resolution. The only things I can add to this issue are

1) This problem occurs with `@EnableSolrRepositories` `multicoreSupport` property true or false
2) `@SolrDocument` present or not on a Model class makes no difference
3) Seems when the original SolrServer Url contains the core name ex: `http://localhost:8983/solr/corename` that core name will be duplicated in the SolrJ URL
4) I went back several versions of `org.apache.solr:solr-core` and the problem persists. Like the SO poster I also went to Solr Core 6.3.0 without success. The only fix was going back to Spring Boot 1.4.x.

I plan on staying with v1.5.1 so my only remedy was going with a Solr Embedded configuration until a solution is found.

Thanks!

**Comment by wilkinsona** [comment] 2017-02-19 07:45
I don't recall any changes to Boot's Solr support in 1.5. Have you tried using a different version of Spring Data Solr? The best was to do that is to override the `spring-data-releasetrain.version` property. A sample that reproduces the problem would also be useful.

/cc @christophstrobl

**Comment by mintster** [comment] 2017-02-19 15:22
Andy, thank you for the quick response and the suggestion to override the `spring-data-releasetrain.version` property. That indeed solved my problem, though the Spring Boot 1.5.1 Duplicate Core Name in Solr I think still exists.

You asked for a sample that reproduces the problem so I put one together from the Spring Boot Data Solr Sample. You will [find that here.](https://github.com/mintster/spring-boot-sample-data-solr)

In brief, when you run the tests in the Sample Project you'll see "collection1/collection1" in the url.

```html

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/collection1/collection1/update. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

Thanks!

**Comment by wilkinsona** [comment] 2017-02-20 12:42
Thanks, @minster

The duplicate collection in the URL is a result of [this change in Spring Data Solr](https://github.com/spring-projects/spring-data-solr/commit/0c2156d8d9c652a478313f57d3bb13d8143f0736).

This looks like a bug in Spring Data Solr to me. @christophstrobl can you please take a look?

**Comment by philwebb** [comment] 2017-03-01 22:08
I've raise [DATASOLR-364](https://jira.spring.io/browse/DATASOLR-364) for @christophstrobl or someone else from the team to look at. I'll close this since it's not really a Spring Boot issue.

**Closed by philwebb** 2017-03-01 22:08 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by christophstrobl** [comment] 2017-03-02 12:51
Sorry for long silence - thanks @mintster for setting up the test project. I've just pushed some changes for [DATASOLR-364](https://jira.spring.io/browse/DATASOLR-364). Snapshot builds (`spring-data-solr:2.2.0.DATASOLR-364-SNAPSHOT`) should be available shortly via _repo.spring.io_ in case you want to give them a try.

**Comment by philwebb** [comment] 2017-03-02 19:16
@christophstrobl Any plans to backport to 2.1.x? We can't pick up 2.2.0 in Boot 1.5.x

**Comment by christophstrobl** [comment] 2017-03-02 20:15
@philwebb yes - will be back ported to 2.1.x. but won't be in the Ingalls SR1.

**Comment by w32blaster** [comment] 2017-03-24 19:19
I also faced with this issue and spend a lot of time to investigate it. :disappointed:  As a temporarily solution the @christophstrobl 's advice works fine for me (build.gradle):
```
compile('org.springframework.data:spring-data-solr:2.2.0.DATASOLR-364-SNAPSHOT')
```
Thank you!

**Comment by valeriucraciun** [comment] 2017-03-29 09:27
hey .. any plans for 2.1.2? this issue blocked me!

**Comment by philwebb** [comment] 2017-04-04 22:53
@valeriucraciun [DATASOLR-364](https://jira.spring.io/browse/DATASOLR-364) has been resolved but there is no release available for us to pick up yet.

**Comment by avn** [comment] 2017-04-08 11:19
Hi, i encountered with this bug today.
I solved it with workaround:
- first we need to extend class HttpSolrClient with the same simple class name. it is necessary due to logic in org.springframework.data.solr.server.support.SolrClientUtils.clone(T, String).
- than create bean of our new extended HttpSolrClient in spring application.

the our extended class of HttpSolrClient
`
package ru.avn;

import java.io.IOException;

import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpRequestBase;
import org.apache.solr.client.solrj.ResponseParser;
import org.apache.solr.client.solrj.SolrRequest;
import org.apache.solr.client.solrj.SolrServerException;

public class HttpSolrClient extends  org.apache.solr.client.solrj.impl.HttpSolrClient {
    private static final long serialVersionUID = 1973496789131415484L;

    
    public HttpSolrClient(String baseURL,
                          HttpClient client,
                          ResponseParser parser) {
        super(baseURL, client, parser);
    }


    public HttpSolrClient(String baseURL, HttpClient client) {
        super(baseURL, client);
    }


    public HttpSolrClient(String baseURL) {
        super(baseURL);
    }


    @SuppressWarnings("rawtypes")
    @Override
    protected HttpRequestBase createMethod(SolrRequest request,
                                           String collection) throws IOException, SolrServerException {
        String col = getBaseURL().endsWith(collection) ? null : collection; 
        return super.createMethod(request, col);
    }
}
`

Spring application config
`

    static final String SOLR_HOST = "solr.host";

    @Resource private Environment environment;

    @Bean
    public SolrClient solrClient() {
        String solrHost = environment.getRequiredProperty(SOLR_HOST);
        return new ru.avn.HttpSolrClient(solrHost);
    }

`
