### ISSUE TITLE
1.4.0.M3 - web environment in tests breaks package scoped Mockito mocks.

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-projects/spring-boot#6054] opened 2016-05-27 10:49 UTC
In Spring Boot 1.4.M3 if there is any test class with `webEnvironment` set to `RANDOM_PORT` or `DEFINED_PORT`, Mockito fails in all following tests to create Mocks for **package scoped classes** or fail to mock **package scoped methods**.

Example: 
There is an empty Spring Boot application with a test that sets up web environment:
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class DemoApplicationTests {

	@Test
	public void contextLoads() {
	}

}
```

Sample class - there is no bean of this class in Spring context.
```
/**
 * Package scoped class with package scoped method.
 */
class BarService {
    String bar() {
        return "bar";
    }
}
```

Two exactly the same tests - first's name starts with "B" to make JUnit run first **before** `DemoApplicationTests` and the second one with "T" to run it **after**. 

```
public class BarServiceTest {
    private BarService barService = mock(BarService.class);

    @Test
    public void testBar() {
        when(barService.bar()).thenReturn("bar-mocked");

        assertThat(barService.bar()).isEqualTo("bar-mocked");
    }
}
```

```
public class TarServiceTest {
    private BarService barService = mock(BarService.class);

    @Test
    public void testBar() {
        when(barService.bar()).thenReturn("bar-mocked");

        assertThat(barService.bar()).isEqualTo("bar-mocked");
    }
}
```
If tests run independently - all pass. If run all at once, no matter if from Maven command line or Intellij, `TarServiceTest` fails with exception:

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.example.BarService
Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

	at com.example.TarServiceTest.<init>(TarServiceTest.java:17)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.mockito.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:238)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:123)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mockito.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:385)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:220)
	... 45 more
Caused by: java.lang.IllegalAccessError: class com.example.BarService$$EnhancerByMockitoWithCGLIB$$223b9f55 cannot access its superclass com.example.BarService
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	... 50 more
```

If `webEnvironment` is set to `NONE` - all tests pass.
If I downgrade to Spring Boot 1.3.5 - all test pass.

I am not sure if it's related to Boot itself or rather Spring 4.3.

Sample project reproducing this problem: https://github.com/maciejwalkowiak/spring-boot-issue-6054

**Comment by wilkinsona** [comment] 2016-05-27 11:07
Thanks for the detailed analysis. This is a duplicate of #6053.

**Closed by wilkinsona** 2016-05-27 11:07 UTC
Labels: waiting-for-triage
