### ISSUE TITLE
Configuration Annotation Processor for List of Object

### ISSUE THREAD

**Issue by zzt93** [spring-projects/spring-boot#12417] opened 2018-03-09 02:36 UTC
We have some relative complex configurations which is written in yml and we want to provide some code completion as it is did by other spring boot lib's configurations.

As this official document shows, we can add ConfigurationProperties and use configuration-processor to generate json to let IDE assist config. But it seems that no support for list of objects' assist? i.e. like the following, it can only prompt to tests, but I want it to also assist each item's fields and possible choice:
```yml
tests:
    - a: ..
      b: ..
    - a: ..
      b: ..
```
I have tried some configurations like this but not work (it not prompt list item but prompt tests[0].a):
```java
public class XXX {

  @ConfigurationProperties("tests")
  public List<Test> getTests() {
    return tests;
  }
}

@ConfigurationProperties("tests[0]")
public class Test {

  public A getA() {
    return xx;
  }
}
```
Any suggestions?

**Comment by snicoll** [comment] 2018-03-09 06:48
Duplicate of #9945

There is partial support for list of objects and map of objects depending on the IDE that you are using and the configuration format that you're using. YAML is generally less supported than properties.

**Closed by snicoll** 2018-03-09 06:48 UTC
Labels: status: waiting-for-triage
