### ISSUE TITLE
Spring Integration listeners fail after devtools restart

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#4134] opened 2015-10-09 12:39 UTC
Spring Integration uses SpEL a lot to invoke methods. If you restart an app with devtools all the method calls fail because SpEL can't resolve the method any more (the parent class is different, even though its name is the same).

**Comment by wilkinsona** [comment] 2015-10-14 13:13
I'm unable to reproduce this. I've tried using `spring-boot-sample-integration` and also [`zipkin-collector-server`](https://github.com/dsyer/zipkin-collector-server) which is where Dave saw the problem. Lacking the expertise to fully set up the latter, I resorted to adding the following to `ZipkinCollectorLauncherApplication`:

```java
	@Autowired
	@Qualifier("sleuth")
	private MessageChannel channel;

	@PostConstruct
	public void sendStuff() {
		new Thread(new Runnable() {
			public void run() {
				System.out.println("Sleeping");
				try {
					Thread.sleep(5000);
				} catch (InterruptedException ex) {
				}
				while (true) {
					try {
						Thread.sleep(500);
					} catch (InterruptedException ex) {

					}
					channel.send(
							MessageBuilder
									.withPayload(new Spans(new Host("test", "localhost", 12345),
											Arrays.asList(new MilliSpan(1, 2, "test", "traceId",
													Collections.<String> emptyList(), "spanId", false, "processId"))))
							.build());
					System.out.println("Send complete");
				}
			}
		}).start();
	}
```

It happily sends messages across restarts. The only failure I see is during shutdown when the thread tries to send a message but the channel has no subscribers. I haven't seen any SpEL related failures.

**Comment by wilkinsona** [comment] 2016-01-18 11:30
I still can't reproduce this so I'm going to close it for now. If the problem crops up again we can reopen it.

**Closed by wilkinsona** 2016-01-18 11:30 UTC
Labels: bug
