### ISSUE TITLE
Veracode pre scan fails on corrupt spring boot executable version > 2.5.9

### ISSUE THREAD

**Issue by tbowley2** [spring-projects/spring-boot#31673] opened 2022-07-11 16:02 UTC
Veracode fails to pre scan spring boot version > 2.5.9 executables - in our case, spring boot version is 2.6.4.
Veracode fails pre scan and module(s) cannot be selected.

These error messages are displayed on the Veracode Select Modules screen:
Corrupt Header - 1 File
Support Issue: Fatal - 1 File
Support Issue (fatal): <executable artifact>.jar may have been corrupted by buggy version of spring boot (2.6.x).  Please use version 2.5.9 (or earlier) or provide us with a non-executable jar/war (see the official Spring documentation).

We consulted with Veracode on July 6, they indicted this is a spring boot issue and suggested we open an issue here.  Veracode has had a significant number of support call in the past month or so regarding this issue.  It is a known, common issue with Veracode customers
Veracode states a script is added in the exec, and when the script gets removed, the length of the artifact is not properly adjusted (the executable byte length).  It effectively makes the artifact corrupt for Veracode scanning.

Is this a known spring boot issue, if so, when will it be fixed?

**Comment by wilkinsona** [comment] 2022-07-11 16:09
This isn't a known issue. If you would like us to investigate, please provide a complete yet minimal sample that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-07-18 16:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-07-25 16:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-07-25 16:10 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
