### ISSUE TITLE
Upgrade from 2.5.7 to 2.6.x breaks use of RequestMappingHandlerMapping in Filters

### ISSUE THREAD

**Issue by william00179** [spring-projects/spring-boot#28874] opened 2021-12-01 01:55 UTC
Hi,

Working version: 2.5.7
Broken version: 2.6.x

I have a Filter that will check if the matched handler method has a particular annotation and wrap the servlet response if that is the case. 

In 2.6.x `requestMappingHandlerMapping.getHandler(httpServletRequest)` throws

```
java.lang.IllegalArgumentException: Expected parsed RequestPath in request attribute "org.springframework.web.util.ServletRequestPathUtils.PATH".
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.13.jar!/:5.3.13]
	at org.springframework.web.util.ServletRequestPathUtils.getParsedRequestPath(ServletRequestPathUtils.java:77) ~[spring-web-5.3.13.jar!/:5.3.13]
	at org.springframework.web.servlet.handler.AbstractHandlerMapping.initLookupPath(AbstractHandlerMapping.java:574) ~[spring-webmvc-5.3.13.jar!/:5.3.13]
 	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:380) ~[spring-webmvc-5.3.13.jar!/:5.3.13]
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:125) ~[spring-webmvc-5.3.13.jar!/:5.3.13]
 	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:67) ~[spring-webmvc-5.3.13.jar!/:5.3.13]
	at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:498) ~[spring-webmvc-5.3.13.jar!/:5.3.13]
```
A minimal example of how we are using this code

```
@Component
@ConditionalOnWebApplication
public class DataFilter implements Filter {

 @Autowired
    private RequestMappingHandlerMapping requestMappingHandlerMapping;
    
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {

        HttpServletRequest httpServletRequest = (HttpServletRequest) request;
        HttpServletResponse httpServletResponse = (HttpServletResponse) response;
        try {
            Optional<HandlerExecutionChain> handlerExecutionChain = Optional.ofNullable(requestMappingHandlerMapping.getHandler(httpServletRequest));
            if (handlerExecutionChain.isPresent()) {
                HandlerMethod handlerMethod = (HandlerMethod) handlerExecutionChain.get().getHandler();
                if (handlerMethod.getMethod().isAnnotationPresent(MonitorData.class)) {
                    //wrap the response
                    chain.doFilter(request, wrappedResponse);
                    }
       ...
                   
```

I that the default matching strategy has been changed in #24805, but I've been unable to resolve this issue in my codebase.

**Comment by william00179** [comment] 2021-12-01 05:20
Rolling back to the old behaviour by setting `spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER` works around this issue in the mean time.

**Comment by zifnab87** [comment] 2021-12-01 09:48
> This indeed is a workaround to the problem but using rest-assured with those endpoints that involve filters is still failing the tests even with this setting in my application-test.yaml . 

The issue is replicated in this simple example

```java
@Component
@RequiredArgsConstructor
public class ChatBotAuthenticationFilter extends OncePerRequestFilter {

    private final RequestMappingHandlerMapping reqMap;

    @Override
    protected void doFilterInternal(HttpServletRequest req, HttpServletResponse res, FilterChain chain) throws IOException, ServletException {
        boolean isChatBotOnly = isEndpointChatBotOnly(req);
        //[...] custom logic
        chain.doFilter(req, res);
    }

    private boolean isEndpointChatBotOnly(HttpServletRequest req) {
        HandlerMethod method;
        try {
            // this call of reqMap.getHandler(req) throws the aforementioned exception
            method = (HandlerMethod) reqMap.getHandler(req).getHandler();
        } catch (Exception e) {
            return false;
        }

        return method.getMethod().isAnnotationPresent(ChatbotOnlyEndpoint.class);
    }
}

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ChatbotOnlyEndpoint {
}
```

Here I am annotating some controller endpoints with `@ChatbotOnlyEndpoint` to enforce some kind of authorization filtering based on the headers that are being submitted (tokens/ids etc)

**Comment by bclozel** [comment] 2021-12-01 10:18
This path matching strategy has been available since Spring Framework 5.3 and Spring Boot 2.4 (as an option first, in #21694). This strategy will also become the new default in Spring Framework.

The problem here is that those custom Servlet filters are leveraging the `RequestMappingHandlerMapping` without adapting to the changes made in Spring Framework 5.3.

To avoid parsing the request path (for efficient matching) multiple times per request, this is done once and cached as a request attribute. At the time those filters process the request, this hasn't been done yet. This is usually done by the `DispatcherServlet` itself or by a `ServletRequestPathFilter`, as [explained in `AbsractHandlerMapping`'s javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/handler/AbstractHandlerMapping.html#setPatternParser-org.springframework.web.util.pattern.PathPatternParser-).

I'd suggest to ways to fix the filter implementation:
* check if the new path matching is configured with `org.springframework.web.servlet.handler.AbstractHandlerMapping#getPatternParser` and manually populate the cached request path with `org.springframework.web.util.ServletRequestPathUtils#parseAndCache` in your filter
* or simply declare a `ServletRequestPathFilter` ahead of your filter

This issue is really about adapting custom code to the new path matching - changing the default in Spring Boot merely brought an existing problem to your attention. I'm closing this issue as a result. Thanks!

**Closed by bclozel** 2021-12-01 10:18 UTC
Labels: status: waiting-for-triage

**Comment by bclozel** [comment] 2021-12-01 11:38
As an additional comment, I'd like to add that `RequestMappingHandlerMapping` is really a strategy for the `DispatcherServlet`, so using it outside of that scope is not supported and considered as a bad practice. The solution I've provided in my previous comment is really a workaround and further changes should be considered in custom filters doing this.

Without knowing more about the use case, it's hard to point to alternatives. Maybe a `org.springframework.web.servlet.HandlerInterceptor` would be a better choice? In the interest of keeping questions outside of the Spring Boot issue tracker, feel free to ask questions on StackOverflow and report the link back here.

**Comment by zifnab87** [comment] 2021-12-28 10:47
@bclozel Can you please provide a way to detect if a method is annotated with an @interface as in my example  above https://github.com/spring-projects/spring-boot/issues/28874#issuecomment-983467912 without using  RequestMappingHandlerMapping reqMap or some alternative way?

Thanks in advance!

**Comment by bclozel** [comment] 2022-01-18 08:10
Sorry for the late reply @zifnab87 
This looks ok to me. The performance problem here is really about performing the matching process twice (once in this filter, and another time for the actual handling). Looking up/setting a request attribute is really cheap compared to that.

**Comment by orubel** [comment] 2023-05-20 20:51
[bclozel](https://github.com/bclozel) I still seem to be having this issue and it occurs when you use other supported Mappings like SimpleUrlHandlerMapping with CorsFilter. Even thopugh you can establish a corsConfiguration with SimpleUrlHandlerMapping, the CorsFilter will STILL USE RequestMappingHandlerMapping for routing requests

**Comment by orubel** [comment] 2023-05-23 15:52
So a followup...
All my tests pass from a shell perspective (and have been for sometime) but when testing with CORS, I noticed that it is **defaulting to ResourceHttpRequestHandler** :

08:25:28.708 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - Mapped to ResourceHttpRequestHandler [classpath [META-INF/resources/], classpath [resources/], classpath [static/], classpath [public/], ServletContext [/]]
08:25:28.715 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.web.servlet.DispatcherServlet - GET "/v1.0/hook/getServices?_=1684855528179", parameters={masked}
08:25:28.720 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - Mapped to ResourceHttpRequestHandler [classpath [META-INF/resources/], classpath [resources/], classpath [static/], classpath [public/], ServletContext [/]]
08:25:28.722 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.w.s.r.ResourceHttpRequestHandler - Resource not found
08:25:28.723 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.web.servlet.DispatcherServlet - Completed 404 NOT_FOUND
08:25:28.724 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.web.servlet.DispatcherServlet - GET "/v1.0/hook/getServices?_=1684855528179", parameters={masked}
08:25:28.724 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.w.s.h.SimpleUrlHandlerMapping - Mapped to ResourceHttpRequestHandler [classpath [META-INF/resources/], classpath [resources/], classpath [static/], classpath [public/], ServletContext [/]]
08:25:28.725 [http-nio-127.0.0.1-8080-exec-2] DEBUG o.s.w.s.r.ResourceHttpRequestHandler - Resource not found

This should not be occurring since I set the ORDER for SimpleUrlHandlerMapping to **mapping.setOrder(Integer.MAX_VALUE - 2);** to override that behaviour

And again, this ONLY happens when using CORS and is throwing the following error:

Caused by: java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
	at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:472)
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:129)
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:129)
	at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:129)
	at org.springframework.security.web.util.OnCommittedResponseWrapper.sendError(OnCommittedResponseWrapper.java:116)
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:561)
	at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

**Comment by bclozel** [comment] 2023-05-23 17:01
The fact that the request is considered with the `ResourceHttpRequestHandler` indicates that this was not a match for the previous handlers. Maybe the request doesn't qualify as a CORS request and is ignored by the CORS support. Maybe debug through `CorsUtils.isCorsRequest`? In any case, a sample application showing the problem would be really helpful. If you believe this is a bug in Spring Framework, please raise an issue there.

**Comment by orubel** [comment] 2023-05-23 17:14
@bclozel Thanks a mill. Yeah that passed with flying colors. Just to be sure. This goes to **HTTPSecurity**??

**Comment by bclozel** [comment] 2023-05-23 17:43
@orubel, no CORS support is in Spring Framework, see [CorsUtils](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/cors/CorsUtils.java) and related classes.
