### ISSUE TITLE
"Let's" should be expanded to "Let us"

### ISSUE THREAD

**Issue by tony21921** [spring-projects/spring-boot#30013] opened 2022-03-01 07:11 UTC
As described in [Edit documentation for consistency #27895](https://github.com/spring-projects/spring-boot/issues/27895)

I will work on this and submit PR later

**Comment by bclozel** [comment] 2022-03-01 07:35
Closing as a duplicate of #27895.
No need to create a placeholder issue, a PR is perfectly valid.
Thanks!

**Closed** 2022-03-01 07:35 UTC
Labels: status: duplicate
