### ISSUE TITLE
RelaxedPropertyResolver does not honor property source precedence

### ISSUE THREAD

**Issue by fdutton** [spring-projects/spring-boot#15284] opened 2018-11-26 01:03 UTC
`RelaxedPropertyResolver` iterates through property sources before it iterates through property name variants. This can cause a lower precedence value to be selected before a high-precedence value when the property naming scheme changes over property sources. For example, `EurekaClientAutoConfiguration` resolves property values like `healthCheckUrlPath` using camelCase. If one defines `eureka.instance.healthCheckUrlPath` in `application.yml` and `eureka.instance.health-check-url-path` in `application-dev.yml`, `RelaxedPropertyResolver` will find the value from `application.yml `before it finds the value from `application-dev.yml` and use it.

I found this with the recent addition of `DefaultManagementMetadataProvider`. Previously, one had to define `healthCheckUrlPath` as `${management.context-path}/health` if one changed the value of `management.context-path`. `DefaultManagementMetadataProvider` now prefaces `healthCheckUrlPath` with the value from `management.context-path` automatically and this caused Spring Boot to advertise my health-check endpoint at `${management.context-path}/${management.context-path}/health`.

I am using Archaius and have the following property source structure:
- `<config-service>/${spring.profiles.active}/${spring.application.name}.yml`
- `<config-service>/${spring.profiles.active}/application.yml`
- `<config-service>/${spring.application.name}.yml`
- `<config-service>/application.yml`
- `<classpath>/application.yml`
- `<classpath>/bootstrap.yml`

When attempting to correct this, I found that `<config-service>/application.yml` uses `eureka.instance.healthCheckUrlPath` while `<config-service>/${spring.profiles.active}/${spring.application.name}.yml` uses `eureka.instance.health-check-url-path` so `DefaultManagementMetadataProvider` used the value from `<config-service>/application.yml` over anything I added to` <config-service>/${spring.profiles.active}/${spring.application.name}.yml`.

I can resolve this by ensuring I have a consistent naming scheme in all my property sources. However, this can be problematic given that I may have to update the embedded YAML files in dozens of services, rebuild and deploy them. I am simply trying to upgrade one service at a time.

Based on my reading of the documentation, it would be more appropriate for `RelaxedPropertyResolver` to try all name variants against all property sources in order of precedence.

**Comment by wilkinsona** [comment] 2018-11-26 12:04
Thanks for the report and analysis of the problem. Here's a test that, I believe, reproduces it:

```
	@Test
	public void propertySourcePrecedence() {
		StandardEnvironment environment = new StandardEnvironment();
		MutablePropertySources sources = environment.getPropertySources();
		sources.addLast(new MapPropertySource("one",
				Collections.singletonMap("a.b.charlie_delta", "one")));
		sources.addLast(new MapPropertySource("two",
				Collections.singletonMap("a.b.charlie-delta", "two")));
		assertThat(new RelaxedPropertyResolver(environment, "a.b.")
				.getProperty("charlie-delta")).isEqualTo("one");
	}
```

It will fail as property source `two` is queried for `a.b.charlie-delta` before property source `one` is queried for `a.b.charlie_delta` so the property's value is `two` when it's expected to be `one`.

While the behaviour's unfortunate, and I think it may be possible to fix it (although it would require `RelaxedPropertyResolver` to be much more than the `PropertyResolver` decorator that it currently is), I am not sure that we should do so at this late stage in 1.5. Fixing it will result in a change in behaviour and people may be relying on the current behaviour.

Let's see what the rest of the team thinks.

**Comment by philwebb** [comment] 2018-11-28 17:51
I'm quite reluctant to make changes in 1.5.x given that we're now very much in maintenance mode. Since there's a workaround for the issue (albeit a little painful), I'm going to close this one. Making significant changes in 1.5.x at this late stage doesn't seem wise.

@fdutton You might want to consider upgrading to Spring Boot 2.x which shouldn't have this issue.

**Closed by philwebb** 2018-11-28 17:51 UTC
Labels: for: team-attention, status: waiting-for-triage
