### ISSUE TITLE
An error occurred while registering beans using two classloaders

### ISSUE THREAD

**Issue by houxinlin** [spring-projects/spring-boot#30208] opened 2022-03-14 14:49 UTC
Is this a bug?
```java
fun main(args: Array<String>) {
    var application =
        runApplication<SpringDemoApplication>(*args) as AnnotationConfigServletWebServerApplicationContext
    var urls = arrayOf(File("/home/HouXinLin/project/java/GradleDemo/build/libs/GradleDemo-1.0-SNAPSHOT.jar").toURI().toURL())
  
    var urlClassLoader_1 = URLClassLoader(urls)
    var urlClassLoader_2 = URLClassLoader(urls)

    var testClass1 = urlClassLoader_1.loadClass("com.hxl.test.TestClass")
    application.registerBean(testClass1, BeanDefinitionCustomizer {  })
    println(application.getBean(testClass1))//ok

    application.removeBeanDefinition("com.hxl.test.TestClass")
    var testClass2 = urlClassLoader_2.loadClass("com.hxl.test.TestClass")
    application.registerBean(testClass2, BeanDefinitionCustomizer {  })
    println(application.getBean(testClass2))// No qualifying bean of type 'com.hxl.test.TestClass' available
}
```

Why did this error occur？Is it my code problem? Or spring internal reasons
```java
 No qualifying bean of type 'com.hxl.test.TestClass' available
```

**Comment by bclozel** [comment] 2022-03-15 08:36
Duplicate of spring-projects/spring-framework#28178
Please don't cross post issues.

**Closed by bclozel** 2022-03-15 08:36 UTC
Labels: status: waiting-for-triage
