### ISSUE TITLE
Too many open files error is occurring with 2.3.1.RELEASE 

### ISSUE THREAD

**Issue by pandiyan90** [spring-projects/spring-boot#22779] opened 2020-08-07 08:20 UTC
I have been facing 'Too many open files' issue with this version. I am using external tomcat to deploy. We have even updated the ulimits but no use. My dependencies are web & socket.

**Comment by bclozel** [comment] 2020-08-07 08:33
This looks like a duplicate of #21934 - could you check this issue and report back if upgrading fixes the problem?

**Comment by pandiyan90** [comment] 2020-08-07 08:42
Thanks for the reply. It's addressed in 2.3.2.RELEASE. I am using Webclient too. Is it happening because of webclient? Looks like this issue has occurred @ 2.2.8. So will it occur again?

**Comment by bclozel** [comment] 2020-08-07 09:31
Thanks for confirming that it's been fixed in 2.3.2.RELEASE - I'm closing this issue as a duplicate of #21934.

This was actually a bug in reactor-netty (so not Spring Boot) and both Spring Boot 2.2.x and 2.3.x depend on the same reactor-netty generation. I can't say this type of issues will never happen again, but in this case the same bug affected two different Spring Boot versions because of a common dependency.

Thanks for this report!

**Closed by bclozel** 2020-08-07 09:31 UTC
Labels: status: feedback-provided, status: waiting-for-triage
