### ISSUE TITLE
MetricsEndpoint sorting

### ISSUE THREAD

**Issue by Aloren** [spring-projects/spring-boot#6321] opened 2016-07-05 10:28 UTC
Currently in our spring-boot applications there are already a lot of metrics and most of them have common prefix, but they are not sorted by key in /metrics endpoint. For example, hystrix command exposes a bunch of metrics and in /metrics endpoint they are not grouped together. I have implemented simple solution for this issue:
```
public class SortedMetricsEndpoint extends MetricsEndpoint {

    public SortedMetricsEndpoint(Collection<PublicMetrics> publicMetrics) {
        super(publicMetrics);
    }

    public SortedMetricsEndpoint(PublicMetrics publicMetrics) {
        super(publicMetrics);
    }

    @Override
    public Map<String, Object> invoke() {
        Map<String, Object> metrics = super.invoke();
        TreeMap<String, Object> sorted = new TreeMap<>();
        sorted.putAll(metrics);
        return sorted;
    }
}
```
I would like to know your opinion and if my solution is worth contributing i will create pull request. Thanks.

**Comment by wilkinsona** [comment] 2016-07-05 10:35
This is (pretty much) a duplicate of #3761. There's already some discussion there so I think we should use that issue to continue the discussion on this topic and close this one.

I think your approach of addressing sorting it in the endpoint is a better approach than ordering the registry as 3761 originally proposed. Rather than a separate endpoint, it could perhaps be a query parameter (for example `/metrics?sort=ascending`). That said, I'm still not entirely convinced that sorting shouldn't only be a client-side concern.

@Aloren Can you please comment on #3761 and we can take things from there?

**Closed** 2016-07-05 10:36 UTC
Labels: duplicate
