### ISSUE TITLE
logging.config in config/application.yml not picked up

### ISSUE THREAD

**Issue by ceefour** [spring-projects/spring-boot#9931] opened 2017-08-01 22:48 UTC
Contents of `config/application.yml` :

```
logging:
  config: config/logback.xml
```

If launched simply with: (this doesn't work, all I get is Spring Boot default logging)

    java -Djava.awt.headless -jar satukancinta-server-3.0.0-SNAPSHOT.jar

However this works:

    java -Djava.awt.headless -Dlogging.config=config/logback.xml -jar satukancinta-server-3.0.0-SNAPSHOT.jar

So the `logging.config` configuration in `config/application.yml` is useless.

Spring Boot 1.5.4.

Probably related to #7099.

**Comment by wilkinsona** [comment] 2017-08-03 05:52
@ceefour For 7099 to be related you would have to be using Spring Cloud and you've made no mention of it in the description. You'd also have to be using an old version of It. To remove any doubt can you please provide a sample that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2017-08-10 05:53
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-08-17 05:54
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-08-17 05:54 UTC

**Comment by madamovych** [comment] 2021-11-08 10:37
"provide a sample that reproduces the problem?" - wasn't it provided for you? Have you made a try with yaml config like provided and was not able to reproduced the problem? Because I can reproduce the same with 2.4.0

**Comment by philwebb** [comment] 2021-11-08 19:51
@madamovych we never received a sample. If you have a project that replaces the problem can you can please share it on GitHub or attach it as zip file to this issue.
