### ISSUE TITLE
Spring Boot 3.2.1 fails with java.lang.ClassNotFoundException: org.hibernate.dialect.Oracle12cDialect

### ISSUE THREAD

**Issue by syedyusufh** [spring-projects/spring-boot#39044] opened 2024-01-05 17:27 UTC
Configuring the below database setting in **application.properties** fails the application startup as `Oracle12cDialect` has been removed in the managed dependency of `hibernate-core`

`spring.jpa.database: oracle`

```
Caused by: java.lang.NoClassDefFoundError: org/hibernate/dialect/Oracle12cDialect
	at org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter.determineDatabaseDialectClass(HibernateJpaVendorAdapter.java:204) ~[spring-orm-6.1.2.jar:6.1.2]
	at org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter.buildJpaPropertyMap(HibernateJpaVendorAdapter.java:148) ~[spring-orm-6.1.2.jar:6.1.2]
	at org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter.getJpaPropertyMap(HibernateJpaVendorAdapter.java:132) ~[spring-orm-6.1.2.jar:6.1.2]
```

**Comment by bclozel** [comment] 2024-01-05 17:36
This is a duplicate of https://github.com/spring-projects/spring-framework/issues/31892

**Closed by bclozel** 2024-01-05 17:36 UTC
Labels: status: waiting-for-triage
