### ISSUE TITLE
Maven plugin - exclude dependencies - Doesn't work transitively 

### ISSUE THREAD

**Issue by tenstriker** [spring-projects/spring-boot#3602] opened 2015-07-25 02:07 UTC
I tried following to exclude all the artifacts under following groups 

                     <configuration>
		            <excludeGroupIds>org.apache.hadoop</excludeGroupIds>
		            <excludeGroupIds>org.apache.hbase</excludeGroupIds>
		        </configuration>

But it still left me with some jars . It should work same as maven-shade plugin artifactSet -> excludes in my opinion.

**Comment by wilkinsona** [comment] 2015-07-25 15:40
Duplicates #3426

**Comment by tenstriker** [comment] 2015-07-25 16:52
Why not? In what scenario one would want child dependencies in their project when they don't want parents? Can there be a flag to exclude it conditionally at least? 
Please re-open of give justifiable reason.

**Comment by tenstriker** [comment] 2015-07-25 17:09
In my case I use 'excludeGroupIds' which should excludes all the artifacts under that group but that's is no happening.

<img width="554" alt="screen shot 2015-07-25 at 10 05 05 am" src="https://cloud.githubusercontent.com/assets/5257103/8890411/acdcfb84-32b4-11e5-8898-dbe66c3d4630.png">
e.g. hadoop-mapreduce-client-core, hadoop-yarn-common etc are all under same group id. If you can't exclude them then what is the point. I would happily use shade plugin but that plugin has its own issue as well working with spring-boot jars.

**Comment by wilkinsona** [comment] 2015-07-25 17:21
Ah, I see. That wasn't at all clear from the original description

**Comment by snicoll** [comment] 2015-07-27 07:06
The [doc states](http://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html#excludeGroupIds):

> Comma separated list of groupId names to exclude (exact match).

Can you fix your configuration first please?

```xml
<configuration>
    <excludeGroupIds>org.apache.hadoop,org.apache.hbase</excludeGroupIds>
</configuration>
```

**Comment by wilkinsona** [comment] 2015-10-12 12:53
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.

**Closed by wilkinsona** 2015-10-12 12:53 UTC
Labels: waiting-for-feedback

**Comment by tenstriker** [comment] 2015-10-12 17:23
@wilkinsona I tried comma-separated list of group ids. It still doesn't exclude child dependencies.

**Comment by wilkinsona** [comment] 2015-10-13 08:40
As explained in #3426, the exclusions are not applied transitively and it will only exclude artifacts with a group id that matches those specified in `<excludeGroupIds>`. I've just packaged an application and verified that all dependencies with a group id of `org.apache.hadoop` or `org.apache.hbase` are excluded, i.e. this is working as designed.

**Comment by zhuanqizhirou** [comment] 2018-07-27 06:45
mvn dependency:copy-dependencies copy all jars to target/dependency;

mvn dependency:tree,  get all groupIds, then it works.

**Comment by Aaaaaaron** [comment] 2019-01-07 10:48
Can anyone reopen this issue? What's the point that if I want to just exclude a dependence without its dependence?

**Comment by snicoll** [comment] 2019-01-07 10:51
@Aaaaaaron please stop adding several comments on the same topic. If you have a question, ask on StackOverflow or chat with the community on Gitter.
