### ISSUE TITLE
Duplicate httpmessageconverter

### ISSUE THREAD

**Issue by brucelwl** [spring-projects/spring-boot#29792] opened 2022-02-14 12:16 UTC
Duplicate ``HttpMessageConverter`` after calling ``org.springframework.boot.autoconfigure.http.HttpMessageConverters#getCombinedConverters`` method

https://github.com/spring-projects/spring-boot/blob/5282d4e0f2/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/http/HttpMessageConverters.java#L118-L138

``converters``
1. org.springframework.http.converter.StringHttpMessageConverter
2. org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter
3. org.springframework.http.converter.json.MappingJackson2HttpMessageConverter

``defaultConverters``
1. org.springframework.http.converter.ByteArrayHttpMessageConverter
2. org.springframework.http.converter.StringHttpMessageConverter
3. org.springframework.http.converter.ResourceHttpMessageConverter
4. org.springframework.http.converter.xml.SourceHttpMessageConverter
5. org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
6. org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter

``combined``
1. org.springframework.http.converter.ByteArrayHttpMessageConverter
2. org.springframework.http.converter.StringHttpMessageConverter
3. org.springframework.http.converter.StringHttpMessageConverter
4. org.springframework.http.converter.ResourceHttpMessageConverter
5. org.springframework.http.converter.xml.SourceHttpMessageConverter
6. org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
7. org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
8. org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter
9. org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter

**The following is repeated:**
3. org.springframework.http.converter.StringHttpMessageConverter
7. org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
9. org.springframework.http.converter.xml.MappingJackson2XmlHttpMessageConverter

**Comment by wilkinsona** [comment] 2022-02-14 12:24
@brucelwl Please take a moment to search for existing issues. This is a duplicate of #21374 which you raised a couple of years ago. It has also been covered more recently in https://github.com/spring-projects/spring-boot/issues/27319, for example.

**Closed by wilkinsona** 2022-02-14 12:24 UTC
Labels: status: waiting-for-triage
