### ISSUE TITLE
Missing javax-websocket-client-impl in boot-dependencies

### ISSUE THREAD

**Issue by blasd** [spring-projects/spring-boot#9988] opened 2017-08-10 13:08 UTC
Hello,

The boot-dependencies bom provides a version for javax-websocket-server-impl but not for javax-websocket-client-impl

**Comment by wilkinsona** [comment] 2017-08-10 13:27
Duplicate of #9989. @blasd If you intend to open a pull request straight away, there's no need for a separate issue as well.

**Comment by wilkinsona** [comment] 2017-08-10 13:28
Duplicate of #9989

**Closed by wilkinsona** 2017-08-10 13:27 UTC
Labels: status: waiting-for-triage
