### ISSUE TITLE
Spring boot 2.4.X with Cloud Config Legacy properties - actuator/refresh is Not working

### ISSUE THREAD

**Issue by shivudu** [spring-projects/spring-boot#25370] opened 2021-02-19 08:38 UTC
- We have upgraded from sprig version 2.1.x to 2.4.X and cloud - Greenwich to 2020.0.X.
 - Included spring boot spring-cloud-starter-bootstrap to load properties.. its working fine on app initial startup.
 - However actuator/refresh isn't working... 
 - **Upon debugging further found out that - Its not taking name from spring.application.name while connecting to cloud config server - application name defaulted to** '**application**'
 
 https://github.com/spring-cloud/spring-cloud-config/blob/63e0a99f898fe28bf09bb1e1d5f88be19dd01d0f/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L214

**Comment by wilkinsona** [comment] 2021-02-19 08:45
Did you mean to open this in the Spring Boot issue tracker? The code that you have linked to is part of spring-cloud-config-client and actuator/refresh is a Spring Cloud feature. If you believe this is a Spring Boot issue and you would like us to spend some time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by shivudu** [comment] 2021-02-19 08:49
Got you. I thought all these comes under the cap of spring boot so opened here. Can you help me with the link - to open this defect @cloud config ?

Thanks

**Comment by wilkinsona** [comment] 2021-02-19 08:52
Spring Cloud config issues are managed here: https://github.com/spring-cloud/spring-cloud-config/issues. I'll close this one for now. We can re-open it if it turns out to be a Spring Boot problem after all.

**Comment by shivudu** [comment] 2021-02-19 08:53
sounds Good thanks

**Closed by wilkinsona** 2021-02-19 08:52 UTC
Labels: status: feedback-provided, status: waiting-for-triage
