### ISSUE TITLE
Setting LOG_FOLDER in sturtup script doesn't redirect output.

### ISSUE THREAD

**Issue by holub** [spring-projects/spring-boot#4285] opened 2015-10-23 13:03 UTC
I'm setting LOG_FOLDER for the startup script. The folder exists and has write permission.
No any files can be found in the folder.
The output is still writing to TMP folder as spring.log

**Comment by shakuzen** [comment] 2015-10-23 13:40
Works for me. Can you provide more information? Is your JAR named `spring.jar`? What operating system, Spring Boot version, init.d or systemd? You can see in [the launch script](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader-tools/src/main/resources/org/springframework/boot/loader/tools/launch.script#L50) that it sets the `LOG_FOLDER` to `/tmp` if the set `LOG_FOLDER` does not exist or is not executable.

**Comment by wilkinsona** [comment] 2015-10-23 13:44
@holub Isn't this a duplicate of #4277? `LOG_FOLDER` controls the location to which System.out and System.err are redirected. Your application's logging will still go to whatever location you've configured.

**Comment by holub** [comment] 2015-10-23 13:49
@wilkinsona That's the same issue. But the answer doesn't solve/explain the issue and it was closed.

**Comment by holub** [comment] 2015-10-23 13:50
@shakuzen No jar name is different from spring.jar and the folder exists.

**Comment by wilkinsona** [comment] 2015-10-23 13:50
You can still comment on a closed issue, and doing so is preferable to opening a duplicate. Perhaps you can comment on #4277 and explain why @vpavic's comment didn't help?

**Closed by wilkinsona** 2015-10-23 13:50 UTC
Labels: waiting-for-feedback

**Comment by holub** [comment] 2015-10-23 13:56
@wilkinsona I disagree this is the duplicate. #4277 just point to misfit between two different sections of the documentation. As you and @vpavic decided everything is fine with documentation I need to solve real usecase.
