### ISSUE TITLE
The maven repackaged file name not right

### ISSUE THREAD

**Issue by songxinqiang** [spring-projects/spring-boot#16487] opened 2019-04-08 10:19 UTC
i have configed my pom build as:
```xml
 <build>
        <finalName>myapp-${project.version}_${current_time}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>timestamp-property</id>
                        <goals>
                            <goal>timestamp-property</goal>
                        </goals>
                        <configuration>
                            <name>current_time</name>
                            <pattern>yyyyMMddHHmmss</pattern>
                            <timeZone>GMT+8</timeZone>
                            <locale>zh_CN</locale>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
i hope to get repackaged file as name like `myapp-3.2.0-beta4_20190408181002.jar` and `origin` file `myapp-3.2.0-beta4_20190408181002.jar.original`,and it works very well with 2.1.3.release or before version, but when i upgrade to version 2.1.4.release,i get file  `myapp-3.2.0-beta4_${current_time}.jar`.and the `origin` file is correct `myapp-3.2.0-beta4_20190408181207.jar`
i think this is an issue because the name of origin file is correct.

**Comment by snicoll** [comment] 2019-04-08 10:27
Duplicate of #16456

**Closed by snicoll** 2019-04-08 10:27 UTC
Labels: status: waiting-for-triage
