### ISSUE TITLE
SpringBoot v2.2.0.M4 returns 'application/json;charset=UTF-8', but also deprecated MediaType

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-boot#17527] opened 2019-07-16 02:05 UTC
Using SpringBoot v2.2.0.M4, the `org.springframework.http.MediaType` contains two values that are deprecated (`APPLICATION_JSON_UTF8` and `APPLICATION_JSON_UTF8_VALUE`), but also returns errors that contain the `;charset=UTF-8` when a URL parameter is missing. Here's an example:

This RestController:
```java
@RestController
public class MyRestController {

  @PostMapping(
      path = "/test",
      params = "type"
  )
  Mono<String> test(@RequestParam("type") String type) {

    return Mono.just("type=" + type);

  }

}
```

which should be fine, but causes the following test to fail:
```java
@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT
)
@AutoConfigureWebTestClient
class CharsetExampleApplicationTests {

    @Autowired
    protected WebTestClient webTestClient;

    @Test
    void testParamErrorCharset(){

        webTestClient
            .post()
            .uri("/test")
	    .exchange()
            .expectStatus().isBadRequest()
            .expectHeader().contentType(MediaType.APPLICATION_JSON);

	}

}
```

**Comment by wilkinsona** [comment] 2019-07-16 06:13
Thanks for the report. This is a duplicate of #17023.

**Closed by wilkinsona** 2019-07-16 06:13 UTC
Labels: status: waiting-for-triage
