### ISSUE TITLE
The @IntegrationTest properties should have the highest precedence

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-boot#5530] opened 2016-03-30 00:26 UTC
According to the existing Spring Boot logic in the `SpringApplicationContextLoader`:
````java
private void addProperties(ConfigurableEnvironment environment,
		Map<String, Object> properties) {
	// @IntegrationTest properties go before external configuration and after system
	environment.getPropertySources().addAfter(
			StandardEnvironment.SYSTEM_ENVIRONMENT_PROPERTY_SOURCE_NAME,
			new MapPropertySource("integrationTest", properties));
}
````
The ENV and System variables override the expectations and make the unit-test useless.

**Comment by wilkinsona** [comment] 2016-03-30 06:19
I think this is a duplicate of #4828

**Comment by snicoll** [comment] 2016-03-30 07:13
More context on slack, it looks like a `lang` property (no namespace) is set using that mechanism (which is the actual issue IMO)

**Comment by dsyer** [comment] 2016-03-30 08:35
It looks like #4828 is a near duplicate, but there the argument also brings in `@TestPropertySource` (which has the wrong defaults IMO, and that's partly why we never adopted it fully in Spring Boot and have our own, quite similar feature). I believe `@IntegrationTest` has a reasonable default behaviour, so the discussion should be about whether we should allow the user to control the order of property sources from the annotation. We are targeting a new API for property sources (can't find the issue right now), so it might be better to consider that at the same time.

**Comment by artembilan** [comment] 2016-03-30 13:01
@dsyer: , thank you very much for the explanation in Slack! Fair enough! Quoting here you for consistency and history:
>  the integration property source is added that way intentionally so it can be overridden from env vars / sys props (e.g. if you want to run the same test twice with different values from your build or IDE).

> The fact that one of the stream modules has a config property called "lang" is pathological, and that's what led to this discussion.

> I believe the stream team are committed to adding proper prefixes for all the module properties (at which point the issue goes away)

@snicoll , thank you for the pointer! Yes, looks like that is a plan :smile: 

Feel free, guys, to close the issue as "duplicate" or introduce the `precedence` option. Everything in your hands! And I go to fix that `@ConfigurationProperties` for the `prefix`.

**Closed** 2016-03-30 16:17 UTC
