### ISSUE TITLE
Clarify precedence between yml and properties files on the same level

### ISSUE THREAD

**Issue by leonard84** [spring-projects/spring-boot#25121] opened 2021-02-05 16:23 UTC
In [4.2. Externalized Configuration](https://docs.spring.io/spring-boot/docs/2.4.2/reference/htmlsingle/#boot-features-external-config) (Spring Boot 2.4.2) it states that 

> Config data files are considered in the following order:
> 1. Application properties packaged inside your jar (application.properties and YAML variants).
> 2. Profile-specific application properties packaged inside your jar (application-{profile}.properties and YAML variants).
> 3. Application properties outside of your packaged jar (application.properties and YAML variants).
> 4. Profile-specific application properties outside of your packaged jar (application-{profile}.properties and YAML variants).

However, what is unclear is which config values wins if you have both `application.yml` and `application.properties` on the same level. We'd like to use **Variant 1** (see below), which seems to work, but relies on undocumented behavior that could easily change, so it would be great if the precedence handling could be added to the docs and checked with tests, if that is not already the case.

### In SB <2.4 we used:
* `src/main/application.yml` to store profiles
* `src/main/application-default.properties` to set `spring.profiles.include=stage-workstation` to activate a profile if nothing was activated via ENV/systemproperty. (We used the properties file as this key is invalid in yml, but using this file makes it also easy to override for test)
*  `src/test/application-default.properties` to set `spring.profiles.include=stage-workstation, test` to activate the test profile
* `src/main/application-test.yml` with profile in the name to avoid overriding the `application.yml`

### For SB 2.4.x
We are evaluating two solutions

#### Variant 1
* `src/main/application.yml` to store profiles and use `spring.profiles.group.default=stage-workstation`
* `src/test/application.properties` to set `spring.profiles.group.default=stage-workstation,test` to activate the test profile and use properties instead of yml to avoid overriding the `application.yml`
* `src/main/application-test.yml` with profile in the name to avoid overriding the `application.yml`

#### Variant 2
* `src/main/application.yml` to store profiles and use `spring.profiles.group.default=stage-workstation`
* `src/test/application.yml` that uses `spring.config.import=file:${user.dir}/src/main/resources/application.yml` and overrides the `spring.profiles.group.default=stage-workstation,test` (IMHO it is rather brittle to rely on `${user.dir}` to be set to the correct location)

**Comment by philwebb** [comment] 2021-02-05 18:51
See #24719 for a recent regression where the order did change between Boot 2.3 and 2.4. Although it's still undocumented, we do at least now [have a test](https://github.com/spring-projects/spring-boot/blob/ceff47afbad04826c2763afa0f64000bca764dac/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/context/config/ConfigDataEnvironmentPostProcessorIntegrationTests.java#L138-L143)

**Comment by mbhave** [comment] 2021-02-08 18:57
The reason I think this isn't documented is because we thought people might stick with one format (either `.yml` or `.properties`) and not combine both. The use case described above is interesting because it lets you override `spring.profiles.group` since that is no longer allowed in profile-specific file. I think we should document that `.properties` will win in such a scenario.

**Comment by snicoll** [comment] 2021-03-01 09:36
Closing in favor of PR #25300

**Closed by snicoll** 2021-03-01 09:36 UTC
Labels: type: documentation
