### ISSUE TITLE
Using RedisTemplate in a MeterBinder causes a circular dependency

### ISSUE THREAD

**Issue by Kurok1** [spring-projects/spring-boot#33488] opened 2022-12-08 01:40 UTC
#### Spring Boot Version
2.6.0+

#### How to Reproduce
Implments `MeterBinder` and inject `RedisTemplate`

```java
@Service
public class InMemoryUserRegistrationService implements UserRegistrationService, MeterBinder {


    @Autowired
    private RedisTemplate redisTemplate;
    
    @Override
    public void bindTo(MeterRegistry registry) {

    }
}
```

Then I just launch the application, and Circular-References are created

#### Errors Output
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   webMvcMetricsFilter defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/web/servlet/WebMvcMetricsAutoConfiguration.class]
┌─────┐
|  prometheusMeterRegistry defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/export/prometheus/PrometheusMetricsExportAutoConfiguration.class]
↑     ↓
|  userRegistrationService (field private org.springframework.data.redis.core.RedisTemplate com.xxx.biz.web.service.InMemoryUserRegistrationService.redisTemplate)
↑     ↓
|  redisTemplate defined in class path resource [org/springframework/boot/autoconfigure/data/redis/RedisAutoConfiguration.class]
↑     ↓
|  redisConnectionFactory defined in class path resource [org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.class]
↑     ↓
|  lettuceClientResources defined in class path resource [org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.class]
↑     ↓
|  lettuceMetrics defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/redis/LettuceMetricsAutoConfiguration.class]
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

```
I ended up having RedisTemplate injected into my business code using `@Lazy`

**Comment by mhalbritter** [comment] 2022-12-08 09:27
Your issue is titled `RestTemplate` but your code uses `RedisTemplate`. I assume you mean `RedisTemplate` in the title too?

**Comment by Kurok1** [comment] 2022-12-08 11:27
I have create a [complete minimal sample](https://github.com/Kurok1/Circular-References-Demo)) on GitHub. You can direct run `DemoApplication` and error will be occurred.

**Comment by mhalbritter** [comment] 2022-12-08 12:12
Your example uses Spring Boot 2.6.9, which is [no longer supported](https://spring.io/projects/spring-boot#support).

But this problem still persists in 2.7.6. It's working with Spring Boot 3.0.0

**Comment by Kurok1** [comment] 2022-12-08 12:14
thanks

**Comment by philwebb** [comment] 2022-12-10 21:10
I suspect #30636 is the reason this works in 3.0 but I'm not sure we can backport that fix to 2.x

**Comment by Kurok1** [comment] 2022-12-11 11:54
Well, I have noticed that in version 3.0 `MeterRegistryPostProcessor` implementation of change.
But I think most people will not upgrade to the new version quickly, so we have to use `ObjectProvider` or `@Lazy` to solve this kind of problem

**Comment by ClaudenirFreitas** [comment] 2022-12-23 11:10
Approach to fix this incident:
```
# application.properties file
spring.main.allow-circular-references=true
```

See [Circular References Prohibited by Default](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#circular-references-prohibited-by-default).

**Comment by philwebb** [comment] 2023-01-09 17:56
I'm going to mark this one as a duplicate of #30636 but unfortunately we don't think we can safely backport the fix for that. Users on Spring Boot 2.x should use the workaround documented above.

**Closed by philwebb** 2023-01-09 17:56 UTC
Labels: type: bug, for: team-meeting
