### ISSUE TITLE
Liveness and readiness probes return down when lazy initialization is enabled

### ISSUE THREAD

**Issue by Storje** [spring-projects/spring-boot#35161] opened 2023-04-25 13:07 UTC
Since Spring Boot 3.0.6, Liveness and Readiness probes return 503 (DOWN)

With this configuration :
```yaml
spring:
  main:
    lazy-initialization: true
    cloud-platform: KUBERNETES
management:
  security:
    enabled: false
  endpoints:
    web.exposure.include: info,health,prometheus
```

The following test is red :
```kotlin
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureObservability
class SupervisionIntegrationTest {

    @Autowired
    lateinit var restTemplate: TestRestTemplate

    @Test
    fun livenessProbe() {
        val response = restTemplate.getForEntity("/actuator/health/liveness", String::class.java)
        assertThat(response.statusCode).isEqualTo(HttpStatus.OK)
    }

    @Test
    fun readinessProbe() {
        val response = restTemplate.getForEntity("/actuator/health/readiness", String::class.java)
        assertThat(response.statusCode).isEqualTo(HttpStatus.OK)
    }

}
```

The same test with Spring Boot 3.0.5 is ok.
With 3.0.6, if `spring.main.cloud-platform` is removed, the health probe is ok. When k8s probes are added, the health becomes down.

**Comment by quaff** [comment] 2023-04-26 03:49
I cannot reproduce it.

**Comment by wilkinsona** [comment] 2023-04-26 07:04
Thanks for trying, @quaff.

@Storje, if you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue. Unless the problem is specific to Kotlin, the sample should ideally be written in Java as it removes one possible source of problems.

**Comment by marcoranica94** [comment] 2023-04-26 09:07
> Since Spring Boot 3.0.6, Liveness and Readiness probes return 503 (DOWN)
> 
> With this configuration :
> 
> ```yaml
> spring.main.cloud-platform: KUBERNETES
> management:
>   security:
>     enabled: false
>   endpoints:
>     web.exposure.include: info,health,prometheus
> ```
> 
> The following test is red :
> 
> ```kotlin
> @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
> @AutoConfigureObservability
> class SupervisionIntegrationTest {
> 
>     @Autowired
>     lateinit var restTemplate: TestRestTemplate
> 
>     @Test
>     fun livenessProbe() {
>         val response = restTemplate.getForEntity("/actuator/health/liveness", String::class.java)
>         assertThat(response.statusCode).isEqualTo(HttpStatus.OK)
>     }
> 
>     @Test
>     fun readinessProbe() {
>         val response = restTemplate.getForEntity("/actuator/health/readiness", String::class.java)
>         assertThat(response.statusCode).isEqualTo(HttpStatus.OK)
>     }
> 
> }
> ```
> 
> The same test with Spring Boot 3.0.5 is ok. With 3.0.6, if `spring.main.cloud-platform` is removed, the health probe is ok. When k8s probes are added, the health becomes down.

Hi, we have updated spring 3.0.6 and appeared to us same problem.

**Comment by Storje** [comment] 2023-04-26 09:22
The issue is when lazy init is enable. 
The configuration in first message is updated with the right configuration.

**Comment by quaff** [comment] 2023-04-26 09:26
I verified `spring.main.lazy-initialization: true` cause health down.

**Comment by marcorotondi** [comment] 2023-04-26 09:56
Since Spring-Boot 3.0.6 and Spring-Clound 2022.0.2 The problem occurs randomly.

On the same service released in a docker environment, one service returns DOWN while the other returns UP
by entering 

`spring.main.cloud-platform=none`

The problem no longer occurs.
The only difference from other services is the activation
of lazy-loading:

`spring.main. lazy-initialization=true`

it seems that lazy-initialization does not lead to the creation of the necessary beans

Problem solved with:
`spring.main. lazy-initialization=false` and without this:
`spring.main.cloud-platform=none`

**Comment by Storje** [comment] 2023-04-26 12:47
@wilkinsona here is a sample to reproduce the issue 
[demo.zip](https://github.com/spring-projects/spring-boot/files/11332911/demo.zip)

**Comment by wilkinsona** [comment] 2023-04-26 14:52
Thanks, @Storje. I've yet to figure out why it makes a difference, but the problem can be worked around by preventing the `ApplicationAvailability` bean from being marked as lazy:

```java
@Bean
fun eagerApplicationAvailabilityBean(): LazyInitializationExcludeFilter {
	return LazyInitializationExcludeFilter.forBeanTypes(ApplicationAvailability::class.java)
}
```

**Comment by wilkinsona** [comment] 2023-04-26 19:29
This is a regression caused by the changes for https://github.com/spring-projects/spring-boot/pull/34347. The return type of the `@Bean` method has changed from `ApplicationAvailabilityBean` to `ApplicationAvailability`. This means that type information is lost and the bean factory cannot tell that it's an `ApplicationListener`.

**Closed** 2023-05-02 15:20 UTC
Labels: type: regression
