### ISSUE TITLE
Gradle project can't depend on sibling project with Spring Boot Gradle Plugin applied

### ISSUE THREAD

**Issue by Sineaggi** [spring-projects/spring-boot#17806] opened 2019-08-07 16:22 UTC
If the spring boot plugin is applied to a project, a sibling project cannot depend on that project. When the plugin is applied neither the project classes nor the dependencies are available on the classpath.
Example of a subproject depending on the parent project. 
```gradle
dependencies {
    implementation(rootProject)
}
```
Example compilation failure
```
> Task :subproject:compileKotlin FAILED
e: .../subproject/src/main/kotlin/demo/subproject/SubApp.kt: (3, 13): Unresolved reference: App
e: .../subproject/src/main/kotlin/demo/subproject/SubApp.kt: (7, 13): Unresolved reference: App
```

This is when using spring-boot version 2.2.0.M4.

**Comment by snicoll** [comment] 2019-08-09 09:01
@Sineaggi it's hard to know for sure what is going with the information that you've provided but it looks like [this section of the documentation](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-and-normal) should help you. If your project generates an executable archive, it does not provide a standard library and therefore you can use it as a dependency.

Please review the documentation and update your project accordingly. I am going to close this now but if after a review of the documentation the problem persists, feel free to share a small sample that reproduces the problem you're experiencing and we can reopen this issue.

**Closed by snicoll** 2019-08-09 09:01 UTC
Labels: status: waiting-for-triage
