### ISSUE TITLE
spring boot actuator httpTrace error

### ISSUE THREAD

**Issue by shoadowboy** [spring-projects/spring-boot#14794] opened 2018-10-12 06:48 UTC
i use spring-boot-starter-actuator 2.0.0  in my project, when the url contains '|'  there occurs exception at org.springframework.boot.actuate.trace.http.HttpTrace。I have set tomcat to allow | in url。the url is  http://localhost:8080/query?messageId=B9639287170BEF9AB97CB6A9346D4FE1|1539320749190$$1

	at java.net.URI.create(URI.java:852)
	at org.springframework.boot.actuate.web.trace.servlet.TraceableHttpServletRequest.getUri(TraceableHttpServletRequest.java:56)
	at org.springframework.boot.actuate.trace.http.HttpExchangeTracer$FilteredTraceableRequest.getUri(HttpExchangeTracer.java:130)
	at org.springframework.boot.actuate.trace.http.HttpTrace$Request.<init>(HttpTrace.java:111)
	at org.springframework.boot.actuate.trace.http.HttpTrace$Request.<init>(HttpTrace.java:99)
	at org.springframework.boot.actuate.trace.http.HttpTrace.<init>(HttpTrace.java:49)
	at org.springframework.boot.actuate.trace.http.HttpExchangeTracer.receivedRequest(HttpExchangeTracer.java:58)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

**Comment by wilkinsona** [comment] 2018-10-12 06:51
Before raising an issue, please take a moment to try an up-to-date version to see if the problem's already been fixed. In this case, this problem was fixed by https://github.com/spring-projects/spring-boot/issues/13273 which is in Spring Boot 2.0.3 and later.

Duplicate of #13273.

**Closed by wilkinsona** 2018-10-12 06:51 UTC
