### ISSUE TITLE
@DataJpaTest test slice doesn't working with container created in @TestConfiguration

### ISSUE THREAD

**Issue by piotrooo** [spring-projects/spring-boot#36239] opened 2023-07-05 10:13 UTC
For the following containers configuration:

```java
@TestConfiguration(proxyBeanMethods = false)
public class ContainersConfiguration {
    @Bean
    @ServiceConnection
    @RestartScope
    PostgreSQLContainer<?> postgresContainer() {
        return new PostgreSQLContainer<>("postgres:13");
    }

    @Bean
    @ServiceConnection
    @RestartScope
    RabbitMQContainer rabbitContainer() {
        return new RabbitMQContainer("rabbitmq:3.11");
    }
}
```
When I try to use it in the repository tests (which are using a slice test annotation `@DataJpaTest`) containers aren't reused and configured correctly.

```java
@DataJpaTest
@Testcontainers
@Import(ContainersConfiguration.class)
@AutoConfigureTestDatabase(replace = NONE)
class RepositoryItTest {
    // tests
}
````

Declare properties in the `@DataJpaTest` works (creates only slice of the context without rabbit), but that seems to be a duplication.

```java
@DataJpaTest(properties = {
        "spring.datasource.url=jdbc:p6spy:tc:postgresql:13://service-test"
})
@Testcontainers
@AutoConfigureTestDatabase(replace = NONE)
class RepositoryItTest {
}
```

Using an annotation `@SpringBootTest`, make this test working but it's create a whole context, which containers (rabbit) which aren't necessary for run them.

```java
@SpringBootTest(webEnvironment = RANDOM_PORT)
@Testcontainers
@Import(ContainersConfiguration.class)
@AutoConfigureTestDatabase(replace = NONE)
class RepositoryItTest {
    // tests
}
```

Spring Boot: 3.1.1

Possible related with #35253.

**Comment by wilkinsona** [comment] 2023-07-05 10:44
Thanks for the report. I am pretty sure that this is a duplicate of https://github.com/spring-projects/spring-boot/issues/35252.

**Closed by wilkinsona** 2023-07-05 10:44 UTC
Labels: status: waiting-for-triage
