### ISSUE TITLE
gradle plugin org.springframework.boot overrides gradle dependencySubstitution

### ISSUE THREAD

**Issue by svatos-jirka** [spring-projects/spring-boot#17267] opened 2019-06-19 11:56 UTC
Hi,

gradle plugin  `org.springframework.boot` doesnt work correctly with gradle dependency substitution.

For example:

```groovy
ext {
    springBootVersion = '2.0.1.RELEASE'
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
}

configurations.all.resolutionStrategy.dependencySubstitution {
    substitute(module("org.springframework.boot:spring-boot"))
            .because("OSS clearence")
            .with(module("org.springframework.boot:spring-boot:2.0.1-oss.RELEASE"))
```

the oss version is not used.

**Comment by wilkinsona** [comment] 2019-06-19 12:08
It seems to work for me with Gradle 5.4.1. Here's a complete `build.gradle`:

```
plugins {
	id 'org.springframework.boot' version '2.1.6.RELEASE'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

configurations.all {
	resolutionStrategy.dependencySubstitution {
		substitute(module("org.springframework.boot:spring-boot"))
				.because("OSS clearence")
				.with(module("org.springframework.boot:spring-boot:2.0.1-oss.RELEASE"))
	}
}
```

I can then see the substitution occurring in the output from `dependencies`:

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- org.springframework.boot:spring-boot-starter-data-jpa -> 2.1.6.RELEASE
|    +--- org.springframework.boot:spring-boot-starter-aop:2.1.6.RELEASE
|    |    +--- org.springframework.boot:spring-boot-starter:2.1.6.RELEASE
|    |    |    +--- org.springframework.boot:spring-boot:2.1.6.RELEASE -> 2.0.1-oss.RELEASE FAILED
|    |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.1.6.RELEASE
|    |    |    |    \--- org.springframework.boot:spring-boot:2.1.6.RELEASE -> 2.0.1-oss.RELEASE FAILED
|    |    |    +--- org.springframework.boot:spring-boot-starter-logging:2.1.6.RELEASE
```

It is listed `FAILED` because the `2.0.1-oss.RELEASE` version isn't available in the configured repositories.

If you would like us to spend some more time investigating, can you please spend some time describing how you believe the OSS version is not being used. A complete sample that reproduces the problem would also be very useful.

**Comment by svatos-jirka** [comment] 2019-06-20 07:22
It looked for me fine too in output of dependencies. But the jar wasnt
replaced in release jar/.../lib

**Comment by wilkinsona** [comment] 2019-06-20 09:34
That works for me too. If I modify the substitution to use a jar that I do have access to:

```
configurations.all {
	resolutionStrategy.dependencySubstitution {
		substitute(module("org.springframework.boot:spring-boot"))
				.because("OSS clearence")
				.with(module("org.springframework.boot:spring-boot:2.0.0.RELEASE"))
	}
}
```

Then the substituted jar is packaged in the resulting fat jar:

```
unzip -l build/libs/gh-17267-0.0.1-SNAPSHOT.jar | grep spring-boot-2.0.0.RELEASE.jar
922427  06-20-2019 10:31   BOOT-INF/lib/spring-boot-2.0.0.RELEASE.jar
```

If you want us to spend any more time on this, you will need to provide detailed instructions or a minimal sample that reproduces the problem. A small Gradle project zipped and attached to this issue or in a separate repository on GitHub would be ideal.

**Comment by spring-issuemaster** [comment] 2019-06-27 09:35
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-04 09:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-04 09:35 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
