### ISSUE TITLE
Hateos HandlerInstantiator overrides Jackson's HandlerInstantiator

### ISSUE THREAD

**Issue by countrogue** [spring-projects/spring-boot#3979] opened 2015-09-18 05:13 UTC
Im trying to autowire my JsonSerializer/JsonDeserializer.
```java
    return new Jackson2ObjectMapperBuilder()
                          .deserializerByType(ObjectX.class, objectXDeserializerBean)
                          .applicationContext(applicationContext);
```
It works with the global deserializer objectXDeserializerBean(above), but when deserializing specific fields like the following(below) it doesn't work:
```java
class ObjectY {
    @JsonDeserialize(using = ObjectZDeserializer.class)
    private ObjectZ myField;
}
```

The problem is that HypermediaAutoConfiguration is overriding the HandlerInstantiator in jackson2ObjectMapper so the only work around i can do right now is to set **spring.hateoas.apply-to-primary-object-mapper=false**. WIth that i was forced to abandon hateos in my responses. Can anyone help me with this?

**Comment by philwebb** [comment] 2015-09-21 19:11
@countrogue What version of Spring Boot are you using? @wilkinsona Does this sound like a duplicate of one of the existing Jackson issues you've already dealt with?

**Comment by countrogue** [comment] 2015-09-22 08:31
@philwebb im using spring-boot v1.2.5.RELEASE

**Comment by wilkinsona** [comment] 2015-09-22 08:36
@philwebb I haven't already dealt with it, but it might turn out to be a duplicate of #3891. However, at the moment at least, I'm only planning to tackle #3891 in 1.3 as I think it might require some changes that are larger when we'd want to ship in 1.2.x.

**Comment by wilkinsona** [comment] 2015-09-24 10:13
@countrogue I'm struggling to reproduce this. Can you please put together a small sample that reproduces the problem?

**Comment by countrogue** [comment] 2015-09-28 11:24
@wilkinsona Hi you can download the sample project from [here](https://github.com/countrogue/spring-boot-issue-3979).

**Comment by wilkinsona** [comment] 2015-10-01 12:33
Thanks for the sample. It didn't appear to reproduce the problem, but it was sufficient for the penny to drop about what you're trying to do.

Unfortunately, Jackson only allows an `ObjectMapper` to be configured with a single `HandlerInstantiator` which means that Spring HATEOAS's `HalHandlerInstantiator` and Spring Framework's `SpringHandlerInstantiator` cannot be easily used together. In other words, out of the box, you have to choose between having HAL formatted responses or being about to use dependency injection in your serializers, deserializers, etc.

You could create and use your own `HandlerInstantiator` that delegates to `HalHandlerInstantiator` and, if it returns `null`, delegate to `SpringHandlerInstantiator` instead. Unfortunately, @olivergierke considers `HalHandlerInstantiator` to be private API in Spring HATEOAS so I wouldn't recommend depending on it directly.

In summary, this isn't a problem that's specific to Spring Boot and I think it needs to be addressed in Spring HATEOAS. Two possible solutions are:

 - Make `HalHandlerInstantiator` part of the supported API so that users can implement a delegating `HandlerInstantiator` as described above
 - Make it possible for Spring HATEOAS to be configured with a `HandlerInstantiator` that `HalHandlerInstantiator` will delegate to.

Unfortunately, GitHub doesn't allow me to move this issue to another repository. You may want to open a [Spring HATEOAS issue](https://github.com/spring-projects/spring-hateoas/issues). This [existing issue[(https://github.com/spring-projects/spring-hateoas/issues/288) may also be of interest. It appears that others are already writing code that depends on `HalHandlerInstantiator` and would benefit from it being part of the public API where backwards compatibility is maintained, etc.

**Closed by wilkinsona** 2015-10-01 12:33 UTC
Labels: waiting-for-feedback

**Comment by countrogue** [comment] 2015-10-02 02:13
Ok thanks @wilkinsona
