### ISSUE TITLE
Executable Jar issues on systems with LastLogin enabled.

### ISSUE THREAD

**Issue by Dye357** [spring-projects/spring-boot#6134] opened 2016-06-09 18:09 UTC
System: Centos 6.7 w. LastLogin enabled.
SpringBoot 1.3

Launch Script Fails when `motd/LastLogin/Etc` is enabled. (`START_STOP_DAEMON`) is not available in Centos 6.

My proposed fix would be to change Line 165 (on `master`) (163 on `1.3.x`) in `Launch.Script`

from:
```
su -s /bin/sh -c "$javaexe $(printf "\"%s\" " "${arguments[@]}") >> \"$log_file\" 2>&1 & echo \$!" "$run_user" > "$pid_file" 
```

to:

```
su -s /bin/sh -c "$javaexe $(printf "\"%s\" " "${arguments[@]}") >> \"$log_file\" 2>&1 & echo \$! > $pid_file" "$run_user" 
```

This ensures the pid file is always populated with the output of echo `$!`, the existing way has the risk that `motd`, Last Login or anything printing in a user's `bashrc` would cause the PID file to contain additional text which will cause the status & stop methods to fail. 

Steps to reproduce:

1. Create an executable `spring-boot.jar` file configured to run as a service.
2. Create a user which that jar will run under.
3. Create a sym-link from the jar to `/etc/init.d`
4. Add echo "test" to the service users `bashrc` as a quick way to simulate an `motd` or last login print out.
5. `$ service <jarName> start`
6. `$ service jarName status`

You should see: 
```
Not running (process 1234 hello not found)
```

The pid file should look like:
```
1234
hello
```

Unfortunately some server OS's appear to not respect a `~/.hushlogin` file.

**Comment by wilkinsona** [comment] 2016-06-13 10:51
We should add an integration test for this too

**Comment by wilkinsona** [comment] 2016-06-30 12:33
I don't think the proposed fix will work. It means that the pid file is now being written as the service's user rather than the user that is starting the service.

**Comment by wilkinsona** [comment] 2016-06-30 14:34
I also can't reproduce the problem. I have a `.bashrc` configured to echo `Test` for the user that's going to run the service (which is the user I'm logged in as). Here's the output from opening a new shell (note that `Test` is echoed) and then switching to root and starting and stopping a Boot app:

```
Test
bash-4.1$ su
Password:
[root@centos awilkinson]# service boot-app status
Not running
[root@centos awilkinson]# service boot-app start
Started [41759]
[root@centos awilkinson]# service boot-app stop
Stopped [41759]
```

@Dye357 I'm tempted to close this, particularly as I can't reproduce the problem. If you'd like me to dig into it some more, can you please provide some updated instructions to reproduce the issue.

**Comment by spring-issuemaster** [comment] 2016-07-07 14:38
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-07-14 14:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-07-14 14:38 UTC
