### ISSUE TITLE
@Cacheable with condition not working after upgrading from Spring Boot 2.7 to 3.2.2 with Java 21

### ISSUE THREAD

**Issue by samragu** [spring-projects/spring-boot#39580] opened 2024-02-14 21:21 UTC
This snippet of code worked fine in 2.7 but not caching in 3.2.2

```
    @Cacheable(condition = "#objectId != null")
    public String getObject(String objectId) {
    	if (objectId == null) {
    		return null;
    	}
    	System.out.println("Fetching object for objectId " + objectId);
    	return "some value";
    }
```

However, if I remove the condition, the cache seems to work.

Expected output from junit

```
Fetching object for objectId xyz
Fetching object for objectId abc
```

However, seeing
```
Fetching object for objectId xyz
Fetching object for objectId xyz
Fetching object for objectId abc
Fetching object for objectId abc
```

Attaching a sample project
[ehcache.zip](https://github.com/spring-projects/spring-boot/files/14288641/ehcache.zip)

**Comment by scottfrederick** [comment] 2024-02-14 22:01
This is a duplicate of https://github.com/spring-projects/spring-framework/issues/32117. Starting with Spring Framework 6,1, your code must be compiled with `-parameters` for the condition to take effect (Spring Boot has nothing to do with this issue except that Spring Boot 3.2 depends on Spring Framework 6.1). 

If you inherit the Spring Boot partent POM, then `-parameters` will be added to the compile configuration automatically. If you don't inherit from Spring Boot then you can manually configure the compiler with something like this in your `pom.xml`: 

```xml
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<parameters>true</parameters>
				</configuration>
			</plugin>
```

**Closed by scottfrederick** 2024-02-14 22:01 UTC
Labels: status: waiting-for-triage
