### ISSUE TITLE
MeterRegistryConfigurers should be applied to the MeterRegistry before it becomes injectable

### ISSUE THREAD

**Issue by alex859** [spring-projects/spring-boot#11317] opened 2017-12-11 21:51 UTC
This is the same issue already fixed in [micrometer-spring-legacy](https://github.com/micrometer-metrics/micrometer/issues/158). 
When injecting a `MeterRegistry`, custom configurations have not been applied yet.

Those configurations should be applied when creating the default `MeterRegistry` in `MetricsAutoConfiguration`. 
I'll add a pull request for this.

**Comment by bclozel** [comment] 2017-12-12 15:03
Duplicate of #11319

**Closed by bclozel** 2017-12-12 15:03 UTC
Labels: status: duplicate
