### ISSUE TITLE
Unable to use a custom BeanFactory with EmbeddedWebApplicationContext and its subclasses

### ISSUE THREAD

**Issue by slyoldfox** [spring-projects/spring-boot#11153] opened 2017-11-26 09:37 UTC
Enhancement

When specifying an applicationContextClass in SpringApplication with (or .contextClass when using SpringApplicationBuilder):

springApplication.setApplicationContextClass(CustomClass.class);

One is unable to use a custom BeanFactory if this CustomClass extends from either EmbeddedWebApplicationContext, AnnotationConfigEmbeddedWebApplicationContext, XmlEmbeddedWebApplicationContext.

This is because GenericApplicationContext, defines beanFactory as final. All spring-context libraries provide a decent extension point in the constructors. But all spring-boot classes that inherit from EmbeddedWebApplicationContext downwards expose an endpoint where BeanFactory may be passed in the constructor.

The end result is one has to resort to copying these Spring Boot ApplicationContext classes if we wish to use them in an Embedded Application Container - not even shadowing the beanFactory field in the CustomBeanFactory is possible. Since the getBeanFactory cannot be overriden (it is final as well).

The fix is quite trivial (unfortunately a bit bloaty). Providing constructors in EmbeddedWebApplicationContext, AnnotationConfigEmbeddedWebApplicationContext, XmlEmbeddedWebApplicationContext with an additional argument so it can reach GenericApplicationContext with the BeanFactory. Ideally it would be nice to have the following code snippet working:

```
@SpringBootApplication
public class MyApplication
{
    public static void main(String[] args) {
        new SpringApplicationBuilder(MyApplication.class).contextClass(MyApplication.CustomApplicationContext.class).run();
    }

    public static class CustomApplicationContext extends AnnotationConfigEmbeddedWebApplicationContext {
        public CustomApplicationContext() {
            super(new CustomBeanFactory());
        }
    }

    public static class CustomBeanFactory extends DefaultListableBeanFactory {
        // custom beanfactory stuff
    }
}

```
This is for spring-boot 1.5.x - in 2.0.0 these classes were renamed, but is also applies there.

**Comment by wilkinsona** [comment] 2017-11-26 09:44
Duplicate of #8547.

**Closed by wilkinsona** 2017-11-26 09:44 UTC
Labels: status: waiting-for-triage

**Comment by slyoldfox** [comment] 2017-11-26 10:26
@wilkinsona thanks for this. I did search for this :/. What a speedy update. Lovely it made it in 2.0.0!
