### ISSUE TITLE
Exception stating that "Database column not found", While it is defined.

### ISSUE THREAD

**Issue by ravigill** [spring-projects/spring-boot#2095] opened 2014-12-09 15:47 UTC
Hi, My issue MIGHT be related to a previously fixed issue: #253 however not entirely sure.

Spring-boot version: 1.2.0.RC2. Gradle config is stated below.

I have the following Entity beans defined.  "UserRole" has a index defined for columns "username" and "role";

```
@Table(name="USER_ROLES", indexes = {@Index(name="role_user_idx", columnList="username, role")})
public class UserRole {	
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer id;
	
	@Column(name = "role", nullable = false, length = 45)
	private String role;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	private User user;
        ....
}

@Entity
@Table(name="USERS")
public class User{
	
	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	private String username;
        ...
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);
        ...
}
```

However this fails during runtime / tests with the following exception and i have no idea where this might be coming from. All help is appreciated!

```
16:25:55.711 [DEBUG] [TestEventLogger] nl.masked.ApplicationTests > contextLoads STARTED
16:25:55.745 [QUIET] [system.out] 16:25:55.745 [DEBUG] [org.gradle.process.internal.child.ActionExecutionWorker] Stopping client connection.
16:25:55.747 [DEBUG] [TestEventLogger] 
16:25:55.747 [DEBUG] [TestEventLogger] nl.masked.ApplicationTests > contextLoads FAILED
16:25:55.748 [DEBUG] [TestEventLogger]     java.lang.IllegalStateException: Failed to load ApplicationContext
16:25:55.748 [DEBUG] [TestEventLogger]         at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:94)
16:25:55.748 [DEBUG] [TestEventLogger]         at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:72)
16:25:55.748 [DEBUG] [TestEventLogger]         at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:170)
16:25:55.748 [DEBUG] [TestEventLogger]         at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:110)
16:25:55.748 [DEBUG] [TestEventLogger]         at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212)
16:25:55.748 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:200)
16:25:55.748 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:252)
16:25:55.748 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:254)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:217)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
16:25:55.749 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
16:25:55.750 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:25:55.750 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
16:25:55.750 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:25:55.750 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:606)
16:25:55.750 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
16:25:55.750 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
16:25:55.750 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
16:25:55.750 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
16:25:55.750 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
16:25:55.750 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
16:25:55.750 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:25:55.750 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
16:25:55.750 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:25:55.750 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:606)
16:25:55.751 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
16:25:55.751 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
16:25:55.751 [DEBUG] [TestEventLogger]         at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
16:25:55.751 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
16:25:55.751 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
16:25:55.751 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
16:25:55.751 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:745)
16:25:55.751 [DEBUG] [TestEventLogger] 
16:25:55.751 [DEBUG] [TestEventLogger]         Caused by:
16:25:55.751 [DEBUG] [TestEventLogger]         org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
16:25:55.751 [DEBUG] [TestEventLogger]             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:540)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:956)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:747)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
16:25:55.752 [DEBUG] [TestEventLogger]             at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
16:25:55.753 [DEBUG] [TestEventLogger]             at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
16:25:55.753 [DEBUG] [TestEventLogger]             at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:105)
16:25:55.753 [DEBUG] [TestEventLogger]             at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:68)
16:25:55.753 [DEBUG] [TestEventLogger]             at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:86)
16:25:55.753 [DEBUG] [TestEventLogger]             ... 44 more
16:25:55.753 [DEBUG] [TestEventLogger] 
16:25:55.753 [DEBUG] [TestEventLogger]             Caused by:
16:25:55.753 [DEBUG] [TestEventLogger]             javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
16:25:55.753 [DEBUG] [TestEventLogger]                 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1239)
16:25:55.753 [DEBUG] [TestEventLogger]                 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.access$600(EntityManagerFactoryBuilderImpl.java:120)
16:25:55.753 [DEBUG] [TestEventLogger]                 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:855)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:845)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1627)
16:25:55.754 [DEBUG] [TestEventLogger]                 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1564)
16:25:55.754 [DEBUG] [TestEventLogger]                 ... 58 more
16:25:55.754 [DEBUG] [TestEventLogger] 
16:25:55.754 [DEBUG] [TestEventLogger]                 Caused by:
16:25:55.755 [DEBUG] [TestEventLogger]                 org.hibernate.AnnotationException: Unable to create unique key constraint (username, role) on table user_roles: database column 'role' not found. Make sure that you use the correct column name which depends on the naming strategy in use (it may not be the same as the property name in the entity, especially for relational types)
16:25:55.755 [DEBUG] [TestEventLogger]                     at org.hibernate.cfg.Configuration.buildUniqueKeyFromColumnNames(Configuration.java:1684)
16:25:55.755 [DEBUG] [TestEventLogger]                     at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1459)
16:25:55.755 [DEBUG] [TestEventLogger]                     at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
16:25:55.755 [DEBUG] [TestEventLogger]                     at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
16:25:55.755 [DEBUG] [TestEventLogger]                     ... 66 more
```

Gradle config:

```
buildscript {
    ext {
        springBootVersion = '1.2.0.RC2'
    }
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }

    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot' 

jar {
    baseName = 'issue-reproduction'
    version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.7
targetCompatibility = 1.7

repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }

}


dependencies {
    compile("org.springframework.boot:spring-boot-starter-security")
    compile("org.springframework.boot:spring-boot-starter-aop")
    compile("org.springframework.boot:spring-boot-starter-jdbc")
    compile("org.springframework.boot:spring-boot-starter-data-jpa")
    compile("org.springframework.boot:spring-boot-starter-data-elasticsearch")
    compile("org.springframework.boot:spring-boot-starter-websocket")
    compile("org.springframework.boot:spring-boot-starter-thymeleaf")
    compile("org.springframework.social:spring-social-security")
    compile("org.springframework.social:spring-social-facebook-web")
    compile("org.springframework.boot:spring-boot-starter-social-facebook")
    compile("org.springframework.boot:spring-boot-starter-social-linkedin")
    compile("org.springframework.boot:spring-boot-starter-social-twitter")
    compile("org.springframework.boot:spring-boot-starter-actuator")
    compile("org.springframework.boot:spring-boot-starter-remote-shell")
    compile("mysql:mysql-connector-java:5.1.28")
    testCompile("org.springframework.boot:spring-boot-starter-test")
}

eclipse {
    classpath {
         containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
         containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7'
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '1.12'
}
```

**Comment by ravigill** [comment] 2015-02-03 22:41
Hi Phill,

I have been out for a while, but i had a look at this issue again today with the latest release 1.2.1 and its still there.

**Comment by philwebb** [comment] 2015-02-04 01:08
I think you have a number of different issues with your application:

1) ElasticSearch repositories are trying to handle JPA entities

With the sample I get the error `No id property found for class nl.reproduction.issue2095.model.User!`. This is because the `UserRepository` is being treated as an elastic search repository. You either need to disabled this by adding `spring.data.elasticsearch.repositories.enabled=false` to you properties or define explicit `@EnableJpaRepositories` and `@EnableElasticsearchRepositories` annotations with different `basePackages` (note you need to have at least one each type of `Repoistory` otherwise auto-configuration kicks in). You should also remove the `@Repository` interface from `UserRepository`.

2) The `User` class is a `@MappedSuperclass`

The user class is marked as `@MappedSuperclass` but I don't see any subclasses. I needed to change this annotation to `@Entity` in order for boot to find it.

3) You have `spring.jpa.properties.hibernate.globally_quoted_identifiers=true`

You have enabled a hibernate setting that will backtick quote identifiers. This means that the unique constraint on `UserRole` won't work. You need to change it to:

```
@UniqueConstraint(columnNames = { "username", "`role`"}))
```

**Closed by philwebb** 2015-02-04 01:08 UTC

**Comment by ravigill** [comment] 2015-02-04 01:43
Hi Philips,

I didn't notice that the MappedSuperclass was left in there. 

Thank you for all the help! its working now and keep up the good work.

Ravi
