### ISSUE TITLE
Data initialization occurs before JPA entities are created.

### ISSUE THREAD

**Issue by srinivasnagesh** [spring-projects/spring-boot#10365] opened 2017-09-20 20:26 UTC
data.sql is executed before JPA entities are created which is specified by 

<spring.jpa.generate-ddl=true>

Working example highlighting the issue can be found here [git.io/v5SWx](url)

I have tried asking this as a question on StackOverflow and looked at other similar threads but couldn't get a answer. Here is the link to SO post:
[https://stackoverflow.com/questions/46066575/spring-boot-data-initialization](url)

**Comment by wilkinsona** [comment] 2017-09-21 04:49
Duplicate of #9048

**Closed by wilkinsona** 2017-09-21 04:49 UTC
Labels: status: waiting-for-triage
