### ISSUE TITLE
spring.config.location content is loaded after @ConditionalOnProperty is evaluated

### ISSUE THREAD

**Issue by horalstvo** [spring-projects/spring-boot#4963] opened 2016-01-18 17:59 UTC
I've stumbled upon following problem today. 

We have a class H2DbMigration which is annotated with @ConditionalOnProperty(value = "runH2DbMigration", havingValue = "true"). In its constructor we do the database migration. The default application.properties file has the property set to true and the database URL there is for H2.

Our Selenium tests need to run with PostgreSQL. So I created another configuration file for Selenium and provided it to the application using 'spring.config.location' as a program argument in Idea run configuration. The file configures the database URL and also sets the runH2DbMigration property to 'false'.

Now I would expect that my new property file is added to the list of files as last and overrides everything before that. Surprisingly, the app created the H2DbMigration class and ran db migration which complained that the underlying database is PostgreSQL. That looks like the properties were half resolved.

I debugged and as far as I can tell here is what happened: 
a) SpringBoot loads the default properties - here application.properties. 
b) It creates the context - goes through beans and evaluates if they should be created (the @ConditionalOnProperty)
c) It resolves the additional file under the property spring.config.location.
d) Runs constructor with all properties.

I would expect different behavior. The spring.config.location should be evaluated and the properties should be loaded before evaluation of @ConditionalOnProperty. I consider it a bug.

Also the documentation is not clear about what the order of the property files listed in the spring.config.location will be. Will the last one have the highest priority or the first one?

For the record, I ended up using a profile. I think the behavior described above is confusing and I don't see how can I confidently use 'spring.config.location'.

We use Spring Boot 1.3.0.

**Comment by wilkinsona** [comment] 2016-01-18 19:08
> The spring.config.location should be evaluated and the properties should be loaded before evaluation of @ConditionalOnProperty. I consider it a bug.

That's what happens. All config files are loaded at the same time by `ConfigFileApplicationListener`

> Also the documentation is not clear about what the order of the property files listed in the spring.config.location will be. Will the last one have the highest priority or the first one?

As [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files), files in custom locations override those in default locations. It sounds like the behaviour you have observed is the opposite of that. Correct?

The documentation doesn't say what order multiple custom locations are processed in. We should fix that.

**Comment by wilkinsona** [comment] 2016-01-18 20:12
I've just tested this and the behaviour matches the documentation. Configuration read from a file in a custom config location overrides the configuration from a file in one of the default locations. 

When you specify multiple custom config locations the last location wins. I've opened #4964 to update the documentation.

This standalone app illustrates the behaviour:

```
package com.example;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Gh4963Application {

	public static void main(String[] args) throws IOException {
		writeApplicationProperties(new File("target/classes"), "default");
		writeApplicationProperties(new File("target/classes/custom-one"), "one");
		writeApplicationProperties(new File("target/classes/custom-two"), "two");
		String property = SpringApplication
				.run(Gh4963Application.class,
						"--spring.config.location=classpath:/custom-one/,classpath:/custom-two/")
				.getEnvironment().getProperty("test");
		System.out.println(property);
	}

	private static void writeApplicationProperties(File dir, String value)
			throws IOException {
		dir.mkdirs();
		FileWriter writer = new FileWriter(new File(dir, "application.properties"));
		writer.append("test=" + value);
		writer.close();
	}
}
```

When run it outputs "two":

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.1.RELEASE)

2016-01-18 20:09:43.614  INFO 10575 --- [           main] com.example.Gh4963Application            : Starting Gh4963Application on aw-rmbp.home with PID 10575 (/Users/awilkinson/dev/workspaces/spring/spring-boot/gh-4963/target/classes started by awilkinson in /Users/awilkinson/dev/workspaces/spring/spring-boot/gh-4963)
2016-01-18 20:09:43.616  INFO 10575 --- [           main] com.example.Gh4963Application            : No active profile set, falling back to default profiles: default
2016-01-18 20:09:43.651  INFO 10575 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7276c8cd: startup date [Mon Jan 18 20:09:43 GMT 2016]; root of context hierarchy
2016-01-18 20:09:44.093  INFO 10575 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-01-18 20:09:44.102  INFO 10575 --- [           main] com.example.Gh4963Application            : Started Gh4963Application in 0.674 seconds (JVM running for 0.932)
two
2016-01-18 20:09:44.103  INFO 10575 --- [       Thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7276c8cd: startup date [Mon Jan 18 20:09:43 GMT 2016]; root of context hierarchy
2016-01-18 20:09:44.104  INFO 10575 --- [       Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

If you believe that you're seeing something that's different to the above, please provide a small sample application which reproduces the problem.

**Comment by spring-issuemaster** [comment] 2016-01-25 19:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-02-01 19:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-02-01 19:10 UTC
