### ISSUE TITLE
ClassCastExceptiom when using DevTools and Spring Session Data Redis

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#11537] opened 2018-01-08 07:48 UTC
It reportedly works with 1.5.x but fails with 2.0.0.M7. This commit on GitHub should reproduce the problem: https://github.com/tomoTaka01/redis-session-sample/commit/10694480b890dfd60686554a3cf615088cf91f21. Without DevTools [the problem does not occur](https://twitter.com/tomo_taka01/status/950155990422274048).

**Comment by snicoll** [comment] 2018-01-11 13:54
I've chased it down to a regression in Spring Session. 

Duplicate of https://github.com/spring-projects/spring-session/issues/968

**Closed by snicoll** 2018-01-11 13:54 UTC
Labels: priority: high, type: bug
