### ISSUE TITLE
AtomikosJtaConfiguration userTransactionService change destroyMethod to "shutdownWait"

### ISSUE THREAD

**Issue by pascalleclercq** [spring-projects/spring-boot#11137] opened 2017-11-24 14:04 UTC
Hello booters !

`userTransactionService` Factory method inside `org.springframework.boot.autoconfigure.transaction.jta.AtomikosJtaConfiguration` is configured with `destroyMethod="shutdownForce"` which gives no time for active transactions to terminate properly, this uselessly increases the need for recovery.

We suggest to change It to `destroyMethod="shutdownWait"`. In 4.0.5 It's possible to configure the `com.atomikos.icatch.default_max_wait_time_on_shutdown property` to set a custom max wait delay.

**Comment by philwebb** [comment] 2017-11-24 17:46
Seems like a sensible change to make in Boot 2.0

**Comment by nklmish** [comment] 2017-11-28 19:01
I can take this issue. Initial thoughts, we can change `destroyMethod=shutDownWait` in [AtomikosJtaConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/transaction/jta/AtomikosJtaConfiguration.java#L75) and introduce a new property `defaultMaxWaitTimeOnShutdown` in [AtomikosProperties](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jta/atomikos/AtomikosProperties.java). If sounds good, I can push the PR

**Comment by snicoll** [comment] 2017-12-01 08:44
@nklmish I think the property is there automatically as we bind to the factory. If you're willing to do this in the coming days, please do so.

**Comment by nklmish** [comment] 2017-12-01 09:15
@snicoll 
> I think the property is there automatically as we bind to the factory

May be I am missing something but In order to provide a user with the possibility to configure custom `default_max_wait_time_on_shutdown`, shouldn't we add a new property 
`private long defaultMaxWaitTimeOnShutdown = Long.MAX_VALUE;`

and use it in [asProperties()](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jta/atomikos/AtomikosProperties.java#L308)
`set(properties, "default_max_wait_time_on_shutdown", getDefaultMaxWaitTimeOnShutdown());`

Otherwise the user will always have `Long.MAX_VALUE` for `default_max_wait_time_on_shutdown`. 

Thank you

**Comment by snicoll** [comment] 2017-12-01 09:25
@nklmish Right, I forgot we had that. Carry on :)

**Comment by nklmish** [comment] 2017-12-01 09:29
@snicoll PR on the way :)

**Comment by snicoll** [comment] 2017-12-11 12:42
Closing in favour of PR #11245

**Closed by snicoll** 2017-12-11 12:42 UTC
Labels: priority: normal, type: enhancement

**Comment by GuyPardon** [comment] 2018-04-27 08:25
Hi,

What exactly is the status of this issue? Has it been implemented?

The status has been marked as duplicate of PR #11245 - which seems an unrelated issue?

Thanks

**Comment by snicoll** [comment] 2018-04-27 08:27
I just made a typo, you can see the commit right above your comments. It was pr #11237
