### ISSUE TITLE
Improve the package structure documented in the "Structuring your code" section

### ISSUE THREAD

**Issue by ShawnTuatara** [spring-projects/spring-boot#9886] opened 2017-07-27 19:45 UTC
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/using-spring-boot.adoc#structuring-your-code

I was wanting to share examples of good package structure based on feature and not by service layer. This was inspired by Mike Gehard's presentation around moving from a monolith to microservices (Step 2 - https://youtu.be/Tx5h3hdvjfw?t=15m33s). I am thinking it would be good to show the same type of structure within the Spring Boot docs to inform developers of that type of structure.

Another reference for this was the java practices page: http://www.javapractices.com/topic/TopicAction.do?Id=205

**Comment by philwebb** [comment] 2017-07-28 02:01
Changing the "Here is a typical layout" tree would probably be a nice idea.

**Comment by renjithgr** [comment] 2017-07-29 20:18
Replaced the existing sample to this one. 
----
	com
	 +- example
	     +- myApplication
	         +- Application.java
	         |
	         +- customer
	         |   +- Customer.java
	         |   +- CustomerController.java
	         |   +- CustomerService.java
		 |   +- CustomerRepository.java
	         |
	         +- order
		 |   +- Order.java
	         |   +- OrderController.java
		 |   +- OrderService.java
		 |   +- OrderRepository.java
----

**Comment by wilkinsona** [comment] 2017-07-31 11:19
Duplicate of #9907

**Closed by wilkinsona** 2017-07-31 11:19 UTC
Labels: priority: normal, status: ideal-for-contribution, type: documentation
