### ISSUE TITLE
Provide hateoas discoverabilty of actuator endpoints without spring-hateoas

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#6887] opened 2016-09-14 22:45 UTC
It would be nice if the current `/actuator` endpoint worked even if spring-hateoas isn't in use. Particularly if systems are in place that want to know what endpoints are available without hitting each one individually.

**Comment by philwebb** [comment] 2016-09-14 22:45
Related to #6886 which would be the obvious place to put this endpoint.

**Comment by mbhave** [comment] 2016-12-06 22:23
Done as part of #7108. The  `CloudFoundryDiscoveryEndpoint` returns a HAL response for the Cloud Foundry actuators even when spring-hateoas is not in use.

**Comment by philwebb** [comment] 2016-12-07 19:13
I think we only did this for the `CloudFoundryDiscoveryEndpoint`, we should consider if we want it also for the regular actuators endpoint.

**Comment by mbhave** [comment] 2016-12-07 20:22
Good point. I suppose we can add support for this in the `HalJsonMvcEndpoint`. The `HalBrowserMvcEndpoint`, I think, would still require spring-hateoas.

**Comment by wilkinsona** [comment] 2017-07-29 20:10
Duplicate of #9901

**Closed by wilkinsona** 2017-07-29 20:10 UTC
Labels: priority: normal, type: enhancement
