### ISSUE TITLE
Add configuration option to configure Kafka Listener's onlyLogRecordMetadata

### ISSUE THREAD

**Issue by jjathman** [spring-projects/spring-boot#24568] opened 2020-12-19 00:09 UTC
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
When configuring a Kafka listener, it is possible to suppress the entire record from being written to the log when retries are being attempted.
This feature is not supported by the auto-configuration.

## Solution
A new `onlyLogRecordMetadata` property should be added to [KafkaProperties#Listener](https://github.com/spring-projects/spring-boot/blob/5fe5dc486038f44d223561763181ed60351e5875/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L915) with the relevant description of the property on the field's javadoc.

Once the property is exposed, it should be mapped by the auto-configuration.
This happens in [ConcurrentKafkaListenerContainerFactoryConfigurer#configureContainer](https://github.com/spring-projects/spring-boot/blob/5fe5dc486038f44d223561763181ed60351e5875/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/ConcurrentKafkaListenerContainerFactoryConfigurer.java#L178)

Finally, the existing tests in `KafkaAutoConfigurationTests` should be updated to execises the new `spring.kafka.listener.only-log-record-metadata` property (see `listenerProperties`).

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by snicoll** [comment] 2020-12-19 07:13
paging @garyrussell as `ContainerProperties` is only used to configure the listener and I don't see any constant for that property in `ConsumerConfig`.

**Comment by garyrussell** [comment] 2020-12-21 15:00
It is, indeed a `spring.kafka.listener...` property (on `ContainerProperties`) not `spring.kafka.consumer...`.

**Comment by martindacos** [comment] 2020-12-21 16:40
I will take a look to my first issue :)

**Comment by snicoll** [comment] 2020-12-21 17:00
Alright @martindacos, the issue is yours and please let us know if you have any questions.

**Comment by martindacos** [comment] 2020-12-21 20:05
Hi @snicoll, the PR is ready for review. Let me know if I have to change something.

**Comment by mbhave** [comment] 2020-12-21 22:53
Closing in favor of #24582.

**Closed by mbhave** 2020-12-21 22:53 UTC
Labels: status: first-timers-only, type: enhancement
