### ISSUE TITLE
add spring-boot version and possibly other library versions in actuator info endpoint

### ISSUE THREAD

**Issue by BigMichi1** [spring-projects/spring-boot#31856] opened 2022-07-25 09:26 UTC
currently, the `actuator/info` endpoint returns detailed information about the Java Runtime Environment, like vendor and version and also some basic information for the OS.
it would be nice if also more information about the currently used dependencies would be added as an additional info contributor.

would I'm looking for is a list of dependencies used by the application with their current version similar to this:
```
{
  "libraries": {
    ...

    "org.springframework.amqp:spring-rabbit" : "2.4.6",
    "org.springframework.boot:spring-boot" : "2.7.2",
    "org.springframework.boot:spring-boot-actuator" : "2.7.2"

    ...
  }
}
```

a more advanced version might be including a grouping of artefacts/dependencies that is configurable via properties, e.g.

```
{
  "libraries": {
    ...
    "org.springframework" : {
      "org.springframework.amqp:spring-rabbit" : "2.4.6",
      "org.springframework.boot:spring-boot" : "2.7.2",
      "org.springframework.boot:spring-boot-actuator" : "2.7.2"
    },
    "org.apache" : {
      ...
    },
    "*" : {
      ...
    }
    ...
  }
}
```

the reason behind that request is if there are running dozens of services in an environment, sometimes it is hard to figure out which service runs which version (especially if there are services deployed that are not so often changed). by adding this information to the `actuator/info` endpoint, it will become automatically visible in tools like `codecentric's Spring Boot Admin` or can be retrieved via direct requests on the endpoint to perform additional things, like creating an overview/excel sheet with all applications and their dependency versions

as this might expose some security-related information this information should be an opt-in

**Comment by wilkinsona** [comment] 2022-07-25 09:32
Thanks for the suggestion. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/22924.

**Closed by wilkinsona** 2022-07-25 09:32 UTC
Labels: status: waiting-for-triage
