### ISSUE TITLE
With spring boot 2.3.4 loggers/ROOT GET call is returning 404 error response

### ISSUE THREAD

**Issue by balajikrb** [spring-projects/spring-boot#24116] opened 2020-11-11 08:05 UTC
With previous spring boot version this seemed to be working fine. However, in 2.3.4 I see this is no more working. Has GET call on loggers/ROOT has been removed ? or is it a bug ?
Note, loggers still returns successful response with all underlying endpoints log levels.,

**Comment by snicoll** [comment] 2020-11-11 08:09
Duplicate of #24117

**Closed by snicoll** 2020-11-11 08:09 UTC
