### ISSUE TITLE
TOC Highlighting Incorrect Section

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#24405] opened 2020-12-08 22:59 UTC
The Spring Boot reference toc doesn't highlight the correct section.

* Navigate to https://docs.spring.io/spring-boot/docs/2.4.0/reference/htmlsingle/
* Ctrl+F FilterRegistrationBean and until you get to the `Registering Servlets, Filters, and Listeners as Spring Beans` section
* The result is that section `4.10.2` is highlighted, but the page is viewing section `4.7.4`

Here is a screenshot of what I see

![boot-reference-scrolling](https://user-images.githubusercontent.com/362503/101551355-7d893400-3976-11eb-8208-dbbc55b2ab5c.png)

**Comment by izeye** [comment] 2020-12-08 23:19
This seems to be a duplicate of https://github.com/spring-projects/spring-boot/issues/24146, and 2.4.1-SNAPSHOT seems to be okay.

See https://docs.spring.io/spring-boot/docs/2.4.1-SNAPSHOT/reference/htmlsingle/

**Comment by philwebb** [comment] 2020-12-09 00:18
Thanks @izeye, I agree. I think this is a duplicate of #24146 which picked up the fix for  spring-io/spring-doc-resources#65

**Closed by philwebb** 2020-12-09 00:18 UTC
Labels: status: waiting-for-triage
