### ISSUE TITLE
infinite request for property crashes jvm

### ISSUE THREAD

**Issue by daniv** [spring-projects/spring-boot#11858] opened 2018-01-31 06:44 UTC
```
19755 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_server_PORT' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19755 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_server_PORT' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19755 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_server_PORT' in PropertySource 'defaultProperties'
19755 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local_server_PORT' in any property source
19757 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'configurationProperties'
19757 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'commandLineArgs'
19757 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'systemProperties'
19758 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'systemEnvironment'
19758 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'random'
19758 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19758 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19758 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'pomProperties'
19759 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19759 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19759 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.port' in PropertySource 'defaultProperties'
19759 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local.SERVER.port' in any property source
19761 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'configurationProperties'
19761 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'commandLineArgs'
19761 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'systemProperties'
19762 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'systemEnvironment'
19762 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'random'
19762 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19762 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19762 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'pomProperties'
19763 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19763 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19763 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.port' in PropertySource 'defaultProperties'
19763 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local_SERVER.port' in any property source
19765 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'configurationProperties'
19765 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'commandLineArgs'
19765 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'systemProperties'
19765 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'systemEnvironment'
19766 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'random'
19766 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19766 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19766 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'pomProperties'
19767 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19767 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19767 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_port' in PropertySource 'defaultProperties'
19767 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local.SERVER_port' in any property source
19768 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'configurationProperties'
19768 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'commandLineArgs'
19768 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'systemProperties'
19769 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'systemEnvironment'
19769 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'random'
19769 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19769 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19769 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'pomProperties'
19770 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19770 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19770 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_port' in PropertySource 'defaultProperties'
19770 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local_SERVER_port' in any property source
19772 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'configurationProperties'
19772 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'commandLineArgs'
19772 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'systemProperties'
19772 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'systemEnvironment'
19773 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'random'
19773 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19773 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19773 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'pomProperties'
19774 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19774 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19774 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER.PORT' in PropertySource 'defaultProperties'
19774 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local.SERVER.PORT' in any property source
19775 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'configurationProperties'
19776 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'commandLineArgs'
19776 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'systemProperties'
19776 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'systemEnvironment'
19777 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'random'
19777 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19777 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19777 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'pomProperties'
19777 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19778 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19778 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER.PORT' in PropertySource 'defaultProperties'
19778 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local_SERVER.PORT' in any property source
19780 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'configurationProperties'
19780 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'commandLineArgs'
19781 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'systemProperties'
19781 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'systemEnvironment'
19781 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'random'
19782 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19782 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19782 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'pomProperties'
19782 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19783 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19783 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local.SERVER_PORT' in PropertySource 'defaultProperties'
19783 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local.SERVER_PORT' in any property source
19785 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'configurationProperties'
19785 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'commandLineArgs'
19785 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'systemProperties'
19786 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'systemEnvironment'
19786 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'random'
19786 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'applicationConfig: [classpath:/application-fx.properties]'
19786 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'applicationConfig: [classpath:/application.properties]'
19786 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'pomProperties'
19787 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'class path resource [config/application-seleniumBoot.properties]'
19787 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'class path resource [selenium/boot/fx/ui/icon.properties]'
19787 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'local_SERVER_PORT' in PropertySource 'defaultProperties'
19787 | selenium-boot | DEBUG |  PropertySourcesPropertyResolver      |  getProperty : 96  --- Could not find key 'local_SERVER_PORT' in any property source
19789 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'LOCAL.server.port' in PropertySource 'configurationProperties'
19789 | selenium-boot | TRACE |  PropertySourcesPropertyResolver      |  getProperty : 82  --- Searching for key 'LOCAL.server.port' in PropertySource 'commandLineArgs'
```

**Comment by wilkinsona** [comment] 2018-01-31 07:16
It’s not clear from the trace log that the request is infinite or that the JVM has crashed. Can you please describe the problem in more detail? A sample that reproduces it would be ideal.

**Comment by daniv** [comment] 2018-01-31 07:24
hi. wow , fast response.
what i sent is part of the log . every line in code "wakes up" another process and i see hundreds of the same PropertySourcesPropertyResolver until my IDE freeeze and u have to stop.  i debuged SpringApplication and it starts to happend as soon the refresh ends. of course i will organize a little demo .... to reporduce the issue

**Comment by daniv** [comment] 2018-02-03 07:16
hi

i still have the same issue. i can say that is caused by one of the autocanfigurations, io am using WebType.NONE on the SpeingApplicationBuilder, removing @SpringBootApplication from my main class solved the problem ( disabled auto configuration )

**Comment by philwebb** [comment] 2018-02-05 17:41
@daniv We're unable to proceed with this issue without a sample that we can run and debug.

**Comment by spring-issuemaster** [comment] 2018-02-11 08:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-02-18 08:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-02-18 08:31 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
