### ISSUE TITLE
Support WebTestClient in AutoConfigureRestDocs

### ISSUE THREAD

**Issue by zaynetro** [spring-projects/spring-boot#10967] opened 2017-11-09 15:11 UTC
At the moment `@AutoConfigureRestDocs` only supports Mock MVC and REST Assured. It would be nice to have WebTestClient (webflux) support there too.

Spring boot version: v2.0.6.M6

**Comment by zaynetro** [comment] 2017-11-09 15:18
I am willing to take a look at resolving this if someone is willing to guide me through the process.

If I understand correctly I may simply add the similar conditional static class as in (https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/restdocs/RestDocsAutoConfiguration.java) but for web test client configuration (https://docs.spring.io/spring-restdocs/docs/2.0.0.RC1/api/).

The question then is where should I place a test for this new configuration option?

**Comment by wilkinsona** [comment] 2017-11-17 11:48
Duplicate of #10969.

**Closed** 2017-11-17 14:59 UTC
Labels: status: duplicate
