### ISSUE TITLE
spring boot unable to interpolate message for jsr-303 validation

### ISSUE THREAD

**Issue by Zane-XY** [spring-projects/spring-boot#3071] opened 2015-05-31 02:25 UTC
if I define the following validation messages,

``` java
@Size(min = 3, message = "{validation.account.name}")
private String name;
```

I expect spring boot would read from `messages*.properties` from classpath and find the `validation.account.name` key to interpolate the message, but it just shows `{validation.account.name}` on the page.

This https://github.com/Zane-XY/springboot-i18n-problem demos the problems.

**Comment by snicoll** [comment] 2015-06-01 12:00
We don't support that. Spring Framework does support it but only with the Hibernate validator implementation. That's interesting.

**Comment by php-coder** [comment] 2015-06-01 12:47
IMHO it should be easy to implement, like this:

```java
public class MvcConfig extends WebMvcConfigurerAdapter {

    @Inject
    private MessageSource messageSource;

	@Override
	public Validator getValidator() {
		LocalValidatorFactoryBean factory = new LocalValidatorFactoryBean();
		factory.setValidationMessageSource(messageSource);
		return factory;
	}
}
```

**Comment by Zane-XY** [comment] 2015-06-02 08:50
Why this isn't part of https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/MessageSourceAutoConfiguration.java? at least Springboot documentation/references should mention what `MessageSourceAutoConfiguration` has done, and how to enable reading from message sources.

**Comment by pete-experimenter** [comment] 2016-01-11 14:07
Good question. Is there an answer? And how do you make use of the MessageSourceAutoConfiguration?

**Comment by bigfatsea** [comment] 2016-05-24 17:12
I believe it's still an open issue https://jira.spring.io/browse/SPR-6380

**Comment by philwebb** [comment] 2017-01-09 17:42
Possibly relates to #7598

**Comment by selimok** [comment] 2017-01-11 16:13
It works.

To get it worked I have to move validation keys into the file ValidationMessages.properties while all oder messages reside in messages.properties.

And simple configured the validation beans as follows:

	@Bean
	public MethodValidationPostProcessor getMethodValidationPostProcessor() {
	    final MethodValidationPostProcessor methodValidationPostProcessor = new MethodValidationPostProcessor();
	    methodValidationPostProcessor.setValidator(getValidator());
	    return methodValidationPostProcessor;
	}
	
	@Bean
	public LocalValidatorFactoryBean getValidator() {
		LocalValidatorFactoryBean validator = new LocalValidatorFactoryBean();
		return validator;
	}

FYI.

**Comment by snicoll** [comment] 2017-01-11 17:45
@selimok thanks for the feedback! FYI, you can remove all that code in 1.5 as we do that automatically.

**Comment by selimok** [comment] 2017-01-11 17:55
@snicoll removed :)

**Comment by ben3000** [comment] 2017-02-09 08:43
@snicoll I have upgraded my app to Spring Boot 1.5.1.RELEASE, but my validator messages are still only interpolated if I follow @selimok's solution. Have I missed something?

**Comment by snicoll** [comment] 2017-02-09 08:50
@ben3000 that the issue is still open?

**Comment by ben3000** [comment] 2017-02-09 08:52
OK, I thought as much. What does "FYI, you can remove all that code in 1.5 as we do that automatically." refer to?

**Comment by snicoll** [comment] 2017-02-09 08:55
A comment that, unfortunately, @selimok has removed (the creation of the validator if I remember) after I told him it was not longer necessary.

**Comment by JWebDev** [comment] 2017-02-10 13:20
I use Spring Boot 1.5.1.RELEASE and have the same problem. Tell me please, where I can look at a working solution? Thanks.

**Comment by jackstevenson** [comment] 2017-02-12 20:27
Overriding the auto-configured `Validator` and setting the `MessageSource` works for me.

ValidationConfig.java
```java
@Configuration
public class ValidationConfig {

    @Bean
    public Validator validator(MessageSource messageSource) {
        LocalValidatorFactoryBean factory = new LocalValidatorFactoryBean();
        factory.setValidationMessageSource(messageSource);
        return factory;
    }
}
```

Person.java
```java
public class Person {
    @NotNull
    private String name;
}
```

messages.properties
```properties
NotNull.person.name=Name must not be null
```

**Comment by philwebb** [comment] 2017-03-02 01:41
I have a feeling #8223 may have improved the MVC support but we probably still don't pick up `messages.properties`. The docs for `LocalValidatorFactoryBean` state that you can't specify both a `validationMessageSource` and a `messageInterpolator`. With #7598 we added a custom `MessageInterpolator` so we can't just set the `messageSource` directly.

**Comment by snicoll** [comment] 2017-03-02 09:25
Argh, that's quite bad news isn't it?

**Comment by gemunet** [comment] 2017-03-03 20:46
it work!

`NotNull.person.name=Name must not be null`

the class name (ex. person) must start with lowercase

**Comment by AaricChen** [comment] 2017-03-23 04:34
Solved by add ```ValidationMessages.properties``` in classpath. this file is used by JSR303 implementation.

**Comment by szgaljic** [comment] 2018-03-27 19:10
@gemunet or @jackstevenson can you provide a full example of showing that this actually works? LocalValidatorFactoryBean does not help map the Spring Valdaiton codes (i.e., NotNull.*), it will only allow mapping to full javax.validation constraints default message (i.e., javax.validation.constraints.NotNull.message)

SO:
https://stackoverflow.com/questions/49499891/spring-boot-mapping-validation-codes-to-messagesource-message

**Comment by juanalvarez123** [comment] 2018-07-17 22:00
If you are using the `WebMvcConfigurerAdapter ` see this post: https://stackoverflow.com/questions/45692179/spring-boot-validation-message-is-not-being-resolved

It says: 

> In case of extending WebMvcConfigurerAdapter you will have to provide validator by overriding getValidator() method from parent class:

```
@Configuration
@EnableWebMvc
public class WebMvcConfiguration extends WebMvcConfigurerAdapter {

    @Bean(name = "validationMessageResource")
    public MessageSource getReloadableResourceBundleValidationMessageSource() {
        ReloadableResourceBundleMessageSource reloadableResourceBundleMessageSource = new ReloadableResourceBundleMessageSource();
        reloadableResourceBundleMessageSource.setBasename("classpath:exceptionmessages");
        reloadableResourceBundleMessageSource.setDefaultEncoding("UTF-8");
        return reloadableResourceBundleMessageSource;
    }

    @Bean(name = "validator")
    @Override
    public LocalValidatorFactoryBean getValidator() {
        final LocalValidatorFactoryBean localValidatorFactoryBean = new LocalValidatorFactoryBean();
       localValidatorFactoryBean.setValidationMessageSource(getReloadableResourceBundleValidationMessageSource());
        return localValidatorFactoryBean;
    }
}
```

This is super important. Previously I was defining the `validator` in a different bean. That was causing that the `validator` that I wanted to use never was setting as default. Then, I moved the `validator` bean where the `WebMvcConfigurerAdapter` was extending, overridden the `getValidator()` method, and it worked.

**Comment by wilkinsona** [comment] 2018-07-18 08:12
@juanalvarez123 Thanks for trying to help people out. One word of caution, though. It's unusual to have `@EnableWebMvc` in a Spring Boot application as it will switch off all of Boot's auto-configuration of Spring MVC. A `WebMvcConfigurer` without `@EnableWebMvc` is much more common.

**Comment by drenda** [comment] 2019-04-26 09:32
Hi, I'm trying to figure out what is the current situation about this issue. I'm using Spring Boot 2.1.4 and I'm struggling on this topic.
I'm using this config right now:

```
@Configuration
@EnableRetry
@EnableTransactionManagement
@EnableJpaAuditing(auditorAwareRef = "springSecurityAuditorAware")
public class CustomConfiguration {

 @Bean
    public MessageSource messageSource() {
        ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
        messageSource.setBasenames("classpath:/i18n/messages");
        messageSource.setUseCodeAsDefaultMessage(false);
        messageSource.setCacheSeconds((int) TimeUnit.HOURS.toSeconds(1));
        messageSource.setFallbackToSystemLocale(false);
        return messageSource;
    }

    @Bean
    public MessageSourceAccessor messageSourceAccessor() {
        return new MessageSourceAccessor(messageSource());
    }

    
    @Bean
    public Validator validator() {
        LocalValidatorFactoryBean factoryBean = new LocalValidatorFactoryBean();
        factoryBean.setValidationMessageSource(messageSource());
        return factoryBean;
    }
```

and

```
@Configuration
@EnableHypermediaSupport(type = {HypermediaType.HAL})
public class WebMvcConfiguration implements WebMvcConfigurer {
 
    private Validator validator;

    @Autowired
    public WebMvcConfiguration(Validator validator) {
        this.validator = validator;
    }

    @Override
    public Validator getValidator() {
        return validator;
    }

```

but still I've to follow @selimok hint: I have to move all validation keys in `ValidationMessages.properties` and all other keys in `messages.properties`.

Is this the indented behaviour? Can someone point out what is the "right" way to do this right now, until this issues is not resolved?
Thanks

**Comment by Muyangmin** [comment] 2019-08-02 08:12
I'm using SpringBoot `2.1.6.RELEASE` and met this problem too. It only works with @selimok 's solution(Use hardcoded `ValidationMessages.properties` file).

What I'm very confused is that: why `messageSource.getMessage("{prop}")` is OK but `@Min(message="{prop}")` not ?

Thanks for any advise or explaination.

**Comment by IonasSoftwareLtd** [comment] 2019-10-07 22:11
My problem was with parameter interpolation:

https://stackoverflow.com/questions/58257635/message-parameters-not-resolved-in-localized-spring-boot-validation-messages/58277267

Is lack of parameter interpolation in BindingResult's default message the expected behaviour?

**Comment by spc16670** [comment] 2019-10-07 22:14
My problem was with parameter interpolation:

https://stackoverflow.com/questions/58257635/message-parameters-not-resolved-in-localized-spring-boot-validation-messages/58277267

Is lack of parameter interpolation in BindingResult's default message the expected behaviour?

**Comment by farukonfly** [comment] 2021-07-02 10:34
> I'm using SpringBoot `2.1.6.RELEASE` and met this problem too. It only works with @selimok 's solution(use hardcoded `ValidationMessages.properties` file).
> 
> What I'm very confused is that: why `messageSource.getMessage("{prop}")` is OK but `@Min(message="{prop}")` not ?
> 
> Thanks for any advise or explaination.

only works with @selimok 's solution
_**Is there any other better solution in the new version?**_

**Comment by wilkinsona** [comment] 2021-07-21 13:02
Closing in favor of #17530.

**Closed by wilkinsona** 2021-07-21 13:02 UTC
Labels: type: enhancement

**Comment by onlinefavorites** [comment] 2021-08-02 07:46
If someone still has the same issue, you can override Hibernate's validator configuration as following:

@Configuration
public class CustomBeanConfiguration {
    @Bean
    public Validator getValidator() {
        return Validation.byDefaultProvider()
                .configure()
                .messageInterpolator(
                        new ResourceBundleMessageInterpolator(
                                new AggregateResourceBundleLocator(
                                        Arrays.asList(
                                                "messages",
                                                "config/error-messages",
                                                "config/another-error-messages"
                                        )
                                )
                        )
                )
                .buildValidatorFactory()
                .getValidator();
    }
}

**Comment by onlinefavorites** [comment] 2021-08-02 07:57
> I'm using SpringBoot `2.1.6.RELEASE` and met this problem too. It only works with @selimok 's solution(use hardcoded `ValidationMessages.properties` file).
> 
> What I'm very confused is that: why `messageSource.getMessage("{prop}")` is OK but `@Min(message="{prop}")` not ?
> 
> Thanks for any advise or explaination.

`messageSource.getMessage("{prop}")` is inside spring configuration context, when you are using hibernate Validator to validate `@Min(message="{prop}")` you have to configure Hibernate's validator as:  [https://github.com/spring-projects/spring-boot/issues/3071#issuecomment-890801555](described here)
