### ISSUE TITLE
Provide metrics on each individual healthindicator

### ISSUE THREAD

**Issue by wyfrel** [spring-projects/spring-boot#28523] opened 2021-11-03 11:07 UTC
I'm using the spring-boot healthIdicator to monitor the dependencies (mail, datasource, ldaps) of my application.

I would be a great enhancement to have metrics on the success / failure of each individual healthindicator to build an history graph of wich has failled when.

Currently i only have a warn message in applications logs or i need to call each health indicator separately.
 
thx for your feedback :-)

**Comment by mbhave** [comment] 2021-11-05 23:18
This looks like a duplicate of $14087. As mentioned in [this comment](https://github.com/spring-projects/spring-boot/issues/14087#issuecomment-851589743), there is a dedicated slack channel to discuss this. 

@shakuzen Was there any consensus on this in the Micrometer channel?

**Comment by shakuzen** [comment] 2021-11-11 11:03
> Was there any consensus on this in the Micrometer channel?

We have the `#health-metrics` channel in the Micrometer slack, and a number of people in the channel, but so far there hasn't been any discussion about the topic there yet. We'd be happy to have that discussion, though!

> I would be a great enhancement to have metrics on the success / failure of each individual healthindicator to build an history graph of wich has failled when.

If you have metrics on the things monitored by the health indicators, then you already can track success/failure of those things with alerts/queries based on those metrics. It seems more roundabout to make additional metrics from the health indicators' statuses for things you already have metrics on. I'd be happy to discuss this more, though.

**Comment by snicoll** [comment] 2021-11-15 14:01
I am going to close this now as a duplicate of #14807. If the conversation in #health-metrics led to some changes in Spring Boot, we can reopen this or use another issue.

**Closed by snicoll** 2021-11-15 14:01 UTC
Labels: status: waiting-for-triage, status: waiting-for-internal-feedback
