### ISSUE TITLE
Consider removing configuration properties import selector 

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#16679] opened 2019-04-28 21:00 UTC
`EnableConfigurationPropertiesImportSelector` imports two `ImportBeanDefinitionRegistrar`s. This intermediate step seems unnecessary and we could just do a 
```
@Import({ConfigurationPropertiesBeanRegistrar,ConfigurationPropertiesBindingPostProcessorRegistrar})
```

**Comment by mrifni** [comment] 2019-04-29 15:42
HI, can I pick up this task ?

**Comment by snicoll** [comment] 2019-04-29 16:29
@mrifni thanks for the offer but the issue is assigned to @mbhave.

**Closed** 2019-04-30 01:01 UTC
Labels: type: task
