### ISSUE TITLE
kotlinx.serialization config override

### ISSUE THREAD

**Issue by jamesward** [spring-projects/spring-boot#29181] opened 2021-12-28 22:26 UTC
Spring Boot 2.6.2

There isn't an easy way to override the config for kotlinx.serialization (like there is for Jackson).  I did:

```kotlin
@Configuration(proxyBeanMethods = false)
class InitConfiguration {

    @ExperimentalSerializationApi
    @Bean
    fun kotlinSerializationJsonDecoder() = KotlinSerializationJsonDecoder(Json {
        explicitNulls = false
    })

}

@ExperimentalSerializationApi
@Configuration
class WebConfig(val decoder: KotlinSerializationJsonDecoder) : WebFluxConfigurer {
    override fun configureHttpMessageCodecs(configurer: ServerCodecConfigurer) {
        super.configureHttpMessageCodecs(configurer)
        configurer.defaultCodecs().kotlinSerializationJsonDecoder(decoder)
    }
}
```

**Comment by snicoll** [comment] 2021-12-29 09:46
There is no auto-configuration for kotlinx.serialization and there's an issue that's covering this ask already.

Duplicate of #24238

**Closed by snicoll** 2021-12-29 09:46 UTC

**Comment by jamesward** [comment] 2021-12-29 16:37
Ah, sorry I didn't see that one.  Thank you.
