### ISSUE TITLE
The all SpyBean members is null

### ISSUE THREAD

**Issue by VasilyBorisovich** [spring-projects/spring-boot#32944] opened 2022-11-01 14:43 UTC
Hello,

I am trying to do a Delegate test on class with SpyBean dependency,

```
    Delegate {
        @Inject
	 A a;
	      
          execute() {
	     a.execute();
	}
     }
```
	
```
   class TestSetUp {
        @SpyBean A a;
	@SpyBean B b;
		
	@Before
        public void setUp() {
          MockitoAnnotations.openMocks(this);
	}
  }
   class Test extended TestSetUp {
	  @Resource
          @InjectMocks
	  Delegate delegate;
	  
	  @Test
	  public void testDelegate() {
	    delegate.execute();
	  }
   }
  
```

In real implementation the class A inject class B and another classes.
```
    class A {
	    @Inject 
		B b;
		@Inject 
		C c;
		...
	}
```

In the test scenario I expected that the spy class A will contain a spybean object B, but all members of class a are null.
The spy object b in the Test is not null.
Why are all the members of the spy object a in the Test class is null?

```
versions used
spring-boot-test-2.6.4.jar
mockito-core-4.0.0.jar
mockito-junit-jupiter-4.0.0.jar
```

**Comment by wilkinsona** [comment] 2022-11-01 14:59
I suspect that there's no existing `A` or `B` beans. When the instances are created for the spies no dependency injection is performed so their fields are left as null. That said, it's rather hard to tell what's happing from a few snippets of source code. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by VasilyBorisovich** [comment] 2022-11-01 15:36
The bean existing
I'm do inject for SpyBean B in the Test class, it's ok ( first picture)
The SpyBean A also exist but all members (and SpyBean B) are null (secondary picture)
![SpyBeanExisted](https://user-images.githubusercontent.com/33516500/199273303-32445c31-e615-4749-a15e-013dec2b56ba.png)
![SpyMockExist_memeber_isNull](https://user-images.githubusercontent.com/33516500/199273310-115f2291-5251-4b81-aebf-50380f3fc411.png)

**Comment by wilkinsona** [comment] 2022-11-01 16:12
Unfortunately, a screenshot doesn't really help. As I said above, if you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem.

**Comment by mdeinum** [comment] 2022-11-01 17:18
Your test uses mockito to create the mocks/spies (the `@Before` annotated method). The `@SpyBean` is a Spring Boot annotation which should be processed by Spring Boot and not Mockito. You need one of the Spring Boot test annotations for the `@SpyBean` or `@MockBean` to work and not plain Mockito.

**Comment by spring-projects-issues** [comment] 2022-11-08 17:35
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-11-15 17:33
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-11-15 17:33 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
