### ISSUE TITLE
Compilation error EndpointHandlerMapping

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-boot#2908] opened 2015-05-04 15:20 UTC
Method `registerHandlerMethod` in `AbstractHandlerMethodMapping` change from protected to public

The following error is throwing

```
[ERROR] COMPILATION ERROR : 
[ERROR] /Users/eddumelendez/Documents/GitHub/spring-boot/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/mvc/EndpointHandlerMapping.java:[92,24] registerHandlerMethod(java.lang.Object,java.lang.reflect.Method,org.springframework.web.servlet.mvc.method.RequestMappingInfo) in org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping cannot override registerHandlerMethod(java.lang.Object,java.lang.reflect.Method,T) in org.springframework.web.servlet.handler.AbstractHandlerMethodMapping
  attempting to assign weaker access privileges; was public
```

**Comment by rstoyanchev** [comment] 2015-05-04 18:52
This is caused by changes for https://jira.spring.io/browse/SPR-11541. The ticket has been re-opened so you can track that instead.

**Comment by rstoyanchev** [comment] 2015-05-04 21:34
I've pushed a fix to the Spring Framework. A new snapshot should become available soon. Closing for now but feel free to re-open if necessary.

**Closed by rstoyanchev** 2015-05-04 21:34 UTC
