### ISSUE TITLE
Redis components instantiated when not required 

### ISSUE THREAD

**Issue by dimazig** [spring-projects/spring-boot#13109] opened 2018-05-09 05:16 UTC
I've notice change in behavior how Redis components are instantiated  in Spring Boot 2
So in maven I define 

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
```

This instruction automatically causes RedisHealthIndicator to be instantiated even though spring.redis.* are not defined in application.properties so my health checker shows that System is DOWN which not correct as I want Redis usage to be conditional depending on environment.
Also presence of an empty  spring.redis.host= in application.properties causes automatic redisConnectionFactoryinstantiation with an error 
`
Caused by: java.lang.IllegalArgumentException: Host must not be empty
`

So ideally Redis components should not be instantiated until some value is defined in  spring.redis.host=

**Comment by wilkinsona** [comment] 2018-05-09 05:26
Duplicate of #11325.

**Closed by wilkinsona** 2018-05-09 05:26 UTC
Labels: status: waiting-for-triage
