### ISSUE TITLE
AWS S3 The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by brettcooper** [spring-projects/spring-boot#17085] opened 2019-06-07 16:22 UTC
When upgrading from Spring Boot 2.0.8.RELEASE to 2.0.9.RELEASE, the AWS SDK breaks when trying to store objects into S3 due to an invalid signature being calculated.  

```
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 73DD5232A3ED3E3C; S3 Extended Request ID: OLfKsmsFqbfhGiElABtnGVcYbZuwMSLRcWk8aXmWgHLbC/GW3/quxAtT/3ykoWn93l7nHXaoFks=)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4920)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4866)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:389)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5800)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1789)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1749)
	at com.unific.rfm.exporter.RFMExporterService.syncSaveToS3(RFMExporterService.java:348)
	at com.unific.rfm.exporter.RFMExporterService.syncCalculate(RFMExporterService.java:257)
	at com.unific.rfm.exporter.RFMExporterService.lambda$calculate$1(RFMExporterService.java:164)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
After doing some digging, I found this StackOverflow article describing the same issue: https://stackoverflow.com/questions/34625812/signaturedoesnotmatch-in-aws-java-sdk-for-s3.  It sounds like the http client being used in version 2.0.9.RELEASE of Spring Boot breaks S3 signature validation.  As soon as I rolled back to 2.0.8.RELEASE, the issue went away.  I have since upgraded back to 2.0.9.RELEASE, but had to downgrade the http client, core to the versions used in 2.0.8.RELEASE and the latest version of netty.  Doing this also gets rid of the issue.

```
<!-- Overrode Http client versions because versions in Spring Boot 2.0.9.RELEASE break S3 signature validation -->
<httpclient.version>4.5.6</httpclient.version>
<httpcore.version>4.4.10</httpcore.version>
<netty.version>4.1.36.Final</netty.version>
```

Spring Boot: 2.0.9.RELEASE
Spring Data DynamoDB Version: 5.0.3 (2.0)
Spring Data Version: 2.0.14.RELEASE
AWS SDK Version: 1.11.565
Java Version: 10.0.2 - OpenJDK 64-Bit Server VM 10.0.2+13-Debian-2
Platform Details: Linux 4.14.77-69.57.amzn1.x86_64

**Comment by wilkinsona** [comment] 2019-06-07 16:33
Duplicate of #16336

**Closed by wilkinsona** 2019-06-07 16:33 UTC
Labels: status: waiting-for-triage

**Comment by brettcooper** [comment] 2019-06-07 17:55
Thanks for the info @wilkinsona.
