### ISSUE TITLE
@EnableConfigurationProperties fails with ImportBeanDefinitionRegistrar and FactoryBean

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-boot#8569] opened 2017-03-10 18:44 UTC
Issue project https://github.com/spring-projects/spring-boot-issues/pull/65

`MyImportBeanDefinitionRegistrar` registers `myBean2` via `MyBean2FactoryBean` which uses reference to `MyBean1` created in `MyConfiguration`. Problem comes when I tried to autowire `MyConfigurationProperties` in `MyConfiguration` to use config props.

```
2017-03-10 18:34:18.307  WARN 5659 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt:
 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myBean1' defined in class path resource [com/example/MyConfiguration.class]: 
Unsatisfied dependency expressed through method 'myBean1' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'myBean2': Cannot resolve reference to bean 'myBean1' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: 
Error creating bean with name 'myBean1': Requested bean is currently in creation: Is there an unresolvable circular reference?

┌─────┐
|  myBean1 defined in class path resource [com/example/MyConfiguration.class]
↑     ↓
|  myBean2
└─────┘

```

This should work and really doesn't make no sense as `myBean1` don't know anything about `myBean2`.

1. Tried some older boot versions(1.4.x/1.5.x) and those failed as well.
2. In `MyImportBeanDefinitionRegistrar` if I skip FactoryBean and create bean reference directly with `MyBean2` everything works.
3. If I do not pass `MyConfigurationProperties` to `myBean1` everything works.
4. I can autowire `MyConfigurationProperties` to other classes(i.e. main boot class).

For PR'd project just run `./gradlew clean build`.

**Comment by philwebb** [comment] 2017-03-13 19:17
Your `MyImportBeanDefinitionRegistrar` should not be annotated with `@Configuration`. Does removing that fix the issue?

**Comment by jvalkeal** [comment] 2017-03-13 20:26
Nope, it doesn't help anything. There is probably something more funky stuff going on behind a scenes as from where I took this this actually partially worked. If I created one bean from `ImportBeanDefinitionRegistrar` it worked but when I registered two bean then I got a cycle errors. For some reason when I extracted this simplified sample I got error even with one registered bean.

It's a little unclear if this fails because of spring-framework or because of spring-boot as I'm not familiar what `@EnableConfigurationProperties` does internally.

**Comment by philwebb** [comment] 2017-03-13 21:51
I've tried following what's going on, but without any luck. It's not a Boot issue AFAICT, the `BeanCurrentlyInCreationException` is thrown from Spring Framework and it's the root cause.

The logic appears to be:
* `myBean1` is created first (from `preInstantiateSingletons`)
* Since `myBean1` needs a `MyConfigurationProperties` a `getBeanNamesForType` method is called

```
Thread [main] (Suspended (breakpoint at line 346 in DefaultSingletonBeanRegistry))	
	owns: ConcurrentHashMap<K,V>  (id=84)	
	owns: Object  (id=85)	
	DefaultListableBeanFactory(DefaultSingletonBeanRegistry).beforeSingletonCreation(String) line: 346	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).getSingletonFactoryBeanForTypeCheck(String, RootBeanDefinition) line: 919	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).getTypeForFactoryBean(String, RootBeanDefinition) line: 804	
	DefaultListableBeanFactory(AbstractBeanFactory).isTypeMatch(String, ResolvableType) line: 558	
	DefaultListableBeanFactory.doGetBeanNamesForType(ResolvableType, boolean, boolean) line: 432	
	DefaultListableBeanFactory.getBeanNamesForType(Class<?>, boolean, boolean) line: 403	
	BeanFactoryUtils.beanNamesForTypeIncludingAncestors(ListableBeanFactory, Class<?>, boolean, boolean) line: 220	
	DefaultListableBeanFactory.findAutowireCandidates(String, Class<?>, DependencyDescriptor) line: 1260	
	DefaultListableBeanFactory.doResolveDependency(DependencyDescriptor, String, Set<String>, TypeConverter) line: 1101	
	DefaultListableBeanFactory.resolveDependency(DependencyDescriptor, String, Set<String>, TypeConverter) line: 1066	
	ConstructorResolver.resolveAutowiredArgument(MethodParameter, String, Set<String>, TypeConverter) line: 835	
	ConstructorResolver.createArgumentArray(String, RootBeanDefinition, ConstructorArgumentValues, BeanWrapper, Class<?>[], String[], Object, boolean) line: 741	
	ConstructorResolver.instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[]) line: 467	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[]) line: 1173	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).createBeanInstance(String, RootBeanDefinition, Object[]) line: 1067	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).doCreateBean(String, RootBeanDefinition, Object[]) line: 513	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).createBean(String, RootBeanDefinition, Object[]) line: 483	
	AbstractBeanFactory$1.getObject() line: 306	
	DefaultListableBeanFactory(DefaultSingletonBeanRegistry).getSingleton(String, ObjectFactory<?>) line: 230	
	DefaultListableBeanFactory(AbstractBeanFactory).doGetBean(String, Class<T>, Object[], boolean) line: 302	
	DefaultListableBeanFactory(AbstractBeanFactory).getBean(String) line: 197	
	DefaultListableBeanFactory.preInstantiateSingletons() line: 761	
	AnnotationConfigApplicationContext(AbstractApplicationContext).finishBeanFactoryInitialization(ConfigurableListableBeanFactory) line: 866	
	AnnotationConfigApplicationContext(AbstractApplicationContext).refresh() line: 542	
	SpringApplication.refresh(ApplicationContext) line: 737	
	SpringApplication.refreshContext(ConfigurableApplicationContext) line: 370	
	SpringApplication.run(String...) line: 314	
	SpringApplication.run(Object[], String[]) line: 1162	
	SpringApplication.run(Object, String...) line: 1151	
	IssueApplication.main(String[]) line: 10	
```

* The `getTypeForFactoryBean` method now attempts to look at the `FactoryBean`:

```java
		// Let's obtain a shortcut instance for an early getObjectType() call...
		FactoryBean<?> fb = (mbd.isSingleton() ?
				getSingletonFactoryBeanForTypeCheck(beanName, mbd) :
				getNonSingletonFactoryBeanForTypeCheck(beanName, mbd));
```

```
Thread [main] (Suspended (breakpoint at line 346 in DefaultSingletonBeanRegistry))	
	owns: ConcurrentHashMap<K,V>  (id=84)	
	owns: Object  (id=85)	
	DefaultListableBeanFactory(DefaultSingletonBeanRegistry).beforeSingletonCreation(String) line: 346	
	DefaultListableBeanFactory(DefaultSingletonBeanRegistry).getSingleton(String, ObjectFactory<?>) line: 223	
	DefaultListableBeanFactory(AbstractBeanFactory).doGetBean(String, Class<T>, Object[], boolean) line: 302	
	DefaultListableBeanFactory(AbstractBeanFactory).getBean(String) line: 197	
	BeanDefinitionValueResolver.resolveReference(Object, RuntimeBeanReference) line: 351	
	BeanDefinitionValueResolver.resolveValueIfNecessary(Object, Object) line: 108	
	ConstructorResolver.resolveConstructorArguments(String, RootBeanDefinition, BeanWrapper, ConstructorArgumentValues, ConstructorArgumentValues) line: 634	
	ConstructorResolver.autowireConstructor(String, RootBeanDefinition, Constructor<?>[], Object[]) line: 145	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).autowireConstructor(String, RootBeanDefinition, Constructor<?>[], Object[]) line: 1193	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).createBeanInstance(String, RootBeanDefinition, Object[]) line: 1095	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).getSingletonFactoryBeanForTypeCheck(String, RootBeanDefinition) line: 923	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).getTypeForFactoryBean(String, RootBeanDefinition) line: 804	
	DefaultListableBeanFactory(AbstractBeanFactory).isTypeMatch(String, ResolvableType) line: 558	
	DefaultListableBeanFactory.doGetBeanNamesForType(ResolvableType, boolean, boolean) line: 432	
	DefaultListableBeanFactory.getBeanNamesForType(Class<?>, boolean, boolean) line: 403	
	BeanFactoryUtils.beanNamesForTypeIncludingAncestors(ListableBeanFactory, Class<?>, boolean, boolean) line: 220	
	DefaultListableBeanFactory.findAutowireCandidates(String, Class<?>, DependencyDescriptor) line: 1260	
	DefaultListableBeanFactory.doResolveDependency(DependencyDescriptor, String, Set<String>, TypeConverter) line: 1101	
	DefaultListableBeanFactory.resolveDependency(DependencyDescriptor, String, Set<String>, TypeConverter) line: 1066	
	ConstructorResolver.resolveAutowiredArgument(MethodParameter, String, Set<String>, TypeConverter) line: 835	
	ConstructorResolver.createArgumentArray(String, RootBeanDefinition, ConstructorArgumentValues, BeanWrapper, Class<?>[], String[], Object, boolean) line: 741	
	ConstructorResolver.instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[]) line: 467	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[]) line: 1173	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).createBeanInstance(String, RootBeanDefinition, Object[]) line: 1067	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).doCreateBean(String, RootBeanDefinition, Object[]) line: 513	
	DefaultListableBeanFactory(AbstractAutowireCapableBeanFactory).createBean(String, RootBeanDefinition, Object[]) line: 483	
	AbstractBeanFactory$1.getObject() line: 306	
	DefaultListableBeanFactory(DefaultSingletonBeanRegistry).getSingleton(String, ObjectFactory<?>) line: 230	
	DefaultListableBeanFactory(AbstractBeanFactory).doGetBean(String, Class<T>, Object[], boolean) line: 302	
	DefaultListableBeanFactory(AbstractBeanFactory).getBean(String) line: 197	
	DefaultListableBeanFactory.preInstantiateSingletons() line: 761	
	AnnotationConfigApplicationContext(AbstractApplicationContext).finishBeanFactoryInitialization(ConfigurableListableBeanFactory) line: 866	
	AnnotationConfigApplicationContext(AbstractApplicationContext).refresh() line: 542	
	SpringApplication.refresh(ApplicationContext) line: 737	
	SpringApplication.refreshContext(ConfigurableApplicationContext) line: 370	
	SpringApplication.run(String...) line: 314	
	SpringApplication.run(Object[], String[]) line: 1162	
	SpringApplication.run(Object, String...) line: 1151	
	IssueApplication.main(String[]) line: 10	
```

* The factory bean tries to get `myBean1` and the exception is thrown.

**Comment by philwebb** [comment] 2017-03-13 21:53
I've merged the PR into https://github.com/spring-projects/spring-boot-issues. Perhaps @jhoeller can shed some light as to why the exception is thrown.

**Comment by jvalkeal** [comment] 2017-03-13 22:57
Thx @philwebb your analysis actually gave me an idea of a workaround which seem to work
```
	@Override
	public void registerBeanDefinitions(AnnotationMetadata metadata, BeanDefinitionRegistry registry) {
		BeanDefinitionBuilder bdb = BeanDefinitionBuilder.rootBeanDefinition(MyBean2FactoryBean.class);
		bdb.addConstructorArgReference("myBean1");
		
//		registry.registerBeanDefinition("myBean2", bdb.getBeanDefinition());
		
		// add explicit target type
		AbstractBeanDefinition beanDefinition = bdb.getBeanDefinition();
		if (beanDefinition instanceof RootBeanDefinition) {
			((RootBeanDefinition)beanDefinition).setTargetType(MyBean2.class);
		}
		registry.registerBeanDefinition("myBean2", beanDefinition);
	}
```
Looks like framework gets confused. I know about type erasure but I thought if type is kept in `AbstractFactoryBean<MyBean2>`, it's still in bytecode and framework might be able to see it. Thought still I don't understand why the cycle. It'd be good to know if it worth to create SPR jira for this.

**Comment by philwebb** [comment] 2017-03-14 03:21
It's probably getting some feedback from the Spring Framework team. I'll close this issue since it's not a Boot problem. If you do raise a framework JIRA, could you drop a link back in this issue?

**Closed by philwebb** 2017-03-14 03:21 UTC
Labels: status: feedback-provided, status: waiting-for-triage
