### ISSUE TITLE
Support properties for RabbitMQ autoconfiguration with NIO

### ISSUE THREAD

**Issue by Vsevolod123** [spring-projects/spring-boot#25554] opened 2021-03-09 02:39 UTC
It would be nice to autoconfigure rabbit connection factory with NIO

**Comment by mbhave** [comment] 2021-03-09 18:04
Related #6719 which is about providing a customizer for the `RabbitConnectionFactoryBean`.

**Comment by philwebb** [comment] 2021-03-10 15:48
The customizer approach suggested in #6719 seems like the best way to offer support for this. The `com.rabbitmq.client.impl.nio.NioParams` class seems too complex to be bound with properties anyway. We'll mark this one as a duplicate of #6719.

**Closed by philwebb** 2021-03-10 15:48 UTC
Labels: type: enhancement
