### ISSUE TITLE
Consider using ForwardedHeaderFilter

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#5677] opened 2016-04-13 15:00 UTC
Spring 4.3 added [ForwardedHeaderFilter](https://jira.spring.io/browse/SPR-13614) which provides a cross container independent way to support X-Forwarded-\* headers. 

This is nice because not all containers provide the same support. For example, [Tomcat does not support X-Forwarded-Host](https://bz.apache.org/bugzilla/show_bug.cgi?id=57665). Another benefit is that `ForwardedHeaderFilter` allows overriding the context root of the application in the event the proxy uses a different context root than the application. This is helpful to ensure links are rendered correctly.

**Comment by philwebb** [comment] 2016-04-15 01:36
I'm not sure that we should change the current `server.use-forward-headers` property to use the filter. Since it's currently supported for Tomcat, Undertow and Jetty I'd rather just see the Tomcat bug fixed.

**Comment by rwinch** [comment] 2016-04-15 13:45
@philwebb Thanks for the feedback. I think there are a few advantages to using Spring's ForwardedHeaderFilter:

* You can support overriding the context root. I have seen this requirement for quite a few Pivotal Labs clients. (I have also experienced this need in the past)
* It will be available right away
* I'm guessing it will simplify the codebase since you can do the same thing for every container rather than having to adapt to each container specific implementation

**Comment by philwebb** [comment] 2016-04-15 18:47
@rwinch Are there any downsides? Filter ordering for example? or performance?

**Comment by rwinch** [comment] 2016-04-15 19:13
I doubt that performance would be an issue. 

The only limitation I can think of is that a Filter would not wrap a `ServletRequestListener`. However, we already have lots of limitations around listeners.

**Comment by wilkinsona** [comment] 2016-04-23 08:15
I am against this, for now at least. When Undertow's native support is used, the `HttpExchange` is marked as secure which has the knock-on effect of marking the request as secure. Anything in Undertow that looks at the exchange will get the wrong answer if we move to the filter-based approach.

**Comment by rwinch** [comment] 2016-04-25 13:40
@wilkinsona What is looking at the `HttpExchange` vs the `HttpServletRequest` (which is correctly overridden)?

**Comment by wilkinsona** [comment] 2016-04-25 14:46
Nothing in Undertow itself, other than its `MarkSecureHandler` which marks every request as secure by configuring an attachment on the exchange. The problem is that we have no way of knowing what other code might be looking in the "wrong" place. For that code, moving to `ForwardedHeaderFilter` would be a breaking change.

**Comment by philwebb** [comment] 2016-05-19 15:05
Sorry, but we feel the current approach is probably better overall.

**Comment by kakawait** [comment] 2016-06-16 09:38
Why not adding `server.use-forward-headers-strategy` with `Enum` (can find better name for value) like `NATIVE` (or `CONTAINER`), `FILTER`? As @rwinch explain `ForwardedHeaderFilter` can be useful for some use cases.

**Comment by bclozel** [comment] 2019-01-16 17:21
We've decided to reconsider this option and allow this use case with a enum, as suggested by @kakawait.
We should probably deprecate the existing `server.use-forward-headers` option and only use the enum option.

**Closed** 2019-04-12 17:38 UTC
Labels: type: enhancement
