### ISSUE TITLE
Skip scoped targets when determining endpoint beans

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-boot#15063] opened 2018-11-01 20:31 UTC
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background

The `@Endpoint` annotation identifies a type as being an actuator endpoint. Spring Boot's actuator infrastructure looks for beans that have this annotation.  

## Problem

When Spring Cloud's `@RefreshScope` is used on an `@Endpoint` bean, it registers another bean for that endpoint with the bean name prefixed by `scopedTarget`. Spring Boot discovers this bean as well when looking for `@Endpoint` beans an fails because it finds two endpoint beans with the same ID.           

## Solution

We should filter out the `scopedTarget.` version of the endpoint bean using `ScopedProxyUtils.isScopedTarget(name)` as was done for a different type of bean in [this commit](
https://github.com/spring-projects/spring-boot/commit/4919c6f30ce1f6842f40c24e8cb697d7a075f0e).

The code for discovering endpoint beans can be found [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/annotation/EndpointDiscoverer.java#L129).

The [test](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/endpoint/annotation/EndpointDiscovererTests.java) can register two beans for the same `@Endpoint` class, one with the name prefixed by `scopedTarget.` and assert that only the original `@Endpoint` bean is discovered.

## Steps to Fix 
 
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by vpondala** [comment] 2018-11-01 22:33
I want to work on this please.

**Comment by mbhave** [comment] 2018-11-01 22:37
@vpondala Cool! Please feel free to ask any questions you have. We'll look forward to your pull request.

**Comment by jbresesti** [comment] 2018-11-03 22:58
Try on this issue, first time.

**Comment by wilkinsona** [comment] 2018-11-03 23:36
Thank you, @jbresesti, but @vpondala has already claimed this issue. Please keep an eye out for another first-timers-only and we’d be delighted to guide you through the process then.

**Comment by jbresesti** [comment] 2018-11-04 01:49
> Thank you, @jbresesti, but @vpondala has already claimed this issue. Please keep an eye out for another first-timers-only and we’d be delighted to guide you through the process then.

Can I follow this process in any way to learn?, How?, thank you.

**Comment by wilkinsona** [comment] 2018-11-04 07:13
The process is described in this issue’s description including links with information on setting up a local copy of the Boot repository and importing the code into your IDE.

To avoid dragging this issue further off topic, please follow up on Gitter with any further questions.

**Comment by wilkinsona** [comment] 2018-11-08 12:34
How are you getting on @vpondala? If there's anything we can do to help please don't hesitate to ask.

**Comment by vpondala** [comment] 2018-11-10 11:03
Apologies for the delay here @wilkinsona. I will be submitting PR in a day or so.

**Comment by vpondala** [comment] 2018-11-13 10:45
@wilkinsona @mbhave My sincere apologies. I am unable to work on this at the moment. Please reassign this to anyone else interested in contributing. Apologies again.

**Comment by vahundos** [comment] 2018-11-13 11:04
I would like to work on this issues if @jbresesti will not.

**Comment by rahul404** [comment] 2018-11-13 21:08
Can I solve this issue?

**Comment by rahul404** [comment] 2018-11-13 21:11
Also, Is there a sample project which i can use to reproduce the error and also to test it ?

**Comment by tranjith** [comment] 2018-11-13 21:34
I want to work on this please

**Comment by mbhave** [comment] 2018-11-13 22:38
According to the order of the comments, @jbresesti expressed interest first. 

@jbresesti Please let us know if you are still interested in working on this issue? If not, we can let @rahul404 claim it.

**Comment by rahul404** [comment] 2018-11-15 08:29
Hi, can I claim this issue now?

**Comment by wilkinsona** [comment] 2018-11-15 09:17
@rahul404 It's all yours. Thank you. If you need us, we're here to answer any questions you have while working on the changes.

**Comment by rahul404** [comment] 2018-11-15 11:35
Hi, is there a code snipped which I can use to reproduce the error.

**Comment by wilkinsona** [comment] 2018-11-15 11:46
There are some details about how to reproduce the problem in @mbhave's description above:

> register two beans for the same `@Endpoint class`, one with the name prefixed by `scopedTarget.`

This would look something like this:

```java
@Configuration
static class ScopedTargetEndpointConfiguration {

	@Bean
	public TestEndpoint testEndpoint() {
		return new TestEndpoint();
	}

	@Bean(name = "scopedTarget.testEndpoint")
	public TestEndpoint scopedTargetTestEndpoint() {
		return new TestEndpoint();
	}

}
```

I would add a configuration class like this to `EndpointDiscovererTests` and then add a test that loads `ScopedTargetEndpointConfiguration`, creates a `TestEndpointDiscoverer` using the loaded context, calls `getEndpoints()` and asserts that only one endpoint is returned.

Before you make any changes to `EndpointDiscoverer` this test will fail as `getEndpoints()` will throw an exception due to both `TestEndpoint` beans being discovered.

**Comment by rahul404** [comment] 2018-11-15 12:02
Ok got it.
Maybe I misunderstood the directions,  I did the following to reproduce the issue
```java
@Configuration
@ImportAutoConfiguration(RefreshAutoConfiguration.class)
	static class RefreshEndpointClashingConfiguration{
		@Bean
		@RefreshScope
		public RefreshScopeTestEndpoint refreshScopeTestEndpoint() {
			return new RefreshScopeTestEndpoint();
		}
	}

@Endpoint(id = "refreshTest")
	static class RefreshScopeTestEndpoint{

	}
```

I will make use of above snippet instead. 
But just to confirm, is my code an improper way of reproducing it?

**Comment by wilkinsona** [comment] 2018-11-15 12:31
No, that's a fine way to reproduce it and is what caused the problem that was originally reported. The recommendation to use the snippet above is because `@RefreshScope` is part of Spring Cloud. Spring Cloud depends on Spring Boot so we can't depend upon it in Spring Boot, even in a test, as doing so would create a circular dependency between the two projects.

Under the covers, `@RefreshScope` causes an extra bean to be created with `scopedTarget.` added to name of the original bean. `ScopedTargetEndpointConfiguration` is simulating what `@RefreshScope` does so that we can reproduced the problem with a dependency on Spring Cloud.

**Comment by rahul404** [comment] 2018-11-15 14:03
I have solved the issue but I am stuck at one of the test cases.
Following is the test case I have written.

```java
@Test
	public void getEndpointsWhenEndpointsArePrefixedWithScopedTargetShouldRegisterOnlyOneEndpoint() {
		load(ScopedTargetEndpointConfiguration.class, (
				context) -> {
			Collection<TestExposableEndpoint> collection =
					new TestEndpointDiscoverer(context).getEndpoints();
			assertThat(collection).hasSize(1);
			TestExposableEndpoint endpoint = collection.iterator().next();
		});
	}
``` 

I want to include a test case as follows :

```java
assertThat(beanName).doesNotStartWith("scopedTarget");
```java

But the collection.iterator().next().getEndpointBean() returns object of type Object

Is there a way of getting bean name?

**Comment by javacodecreeks** [comment] 2018-11-15 14:05
>The process is described in this issue’s description including links with information on setting up a local copy of the Boot repository and importing the code into your IDE. ...

@wilkinsona 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wilkinsona** [comment] 2018-11-15 17:14
Thanks very much for the PR, @rahul404. I'll close this one in favour of it.

**Closed by wilkinsona** 2018-11-15 17:14 UTC
Labels: status: first-timers-only, type: bug

**Comment by rahul404** [comment] 2018-11-15 19:10
Thank you. You were a great help. I look forward to making more contributions.
