### ISSUE TITLE
Spring boot Conectivty for intelij ide

### ISSUE THREAD

**Issue by madilraza** [spring-projects/spring-boot#19551] opened 2020-01-07 11:24 UTC

**Comment by bclozel** [comment] 2020-01-07 13:15
I don't understand the problem here. Could you edit this issue to explain the bug or the requested feature? If it's a bug, a minimal Spring Boot application reproducing the issue is really helpful.

Thanks,

**Comment by spring-issuemaster** [comment] 2020-01-14 13:16
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-01-21 13:17
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-01-21 13:17 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
