### ISSUE TITLE
Jersey Rest Service failing after upgrading to Boot 1.3 Release

### ISSUE THREAD

**Issue by nandhusriram** [spring-projects/spring-boot#4518] opened 2015-11-17 00:54 UTC
Jersey Version 2.22.1
Spring Boot 1.3.0.Release

I upgraded my spring boot application from 1.2.7 to 1.3.0 and my jersey services throwing the following error when running the tests.
```
java.lang.NullPointerException
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.createInflector(RuntimeModelBuilder.java:128)
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.createMethodRouter(RuntimeModelBuilder.java:115)
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.createResourceMethodRouters(RuntimeModelBuilder.java:309)
	at org.glassfish.jersey.server.internal.routing.RuntimeModelBuilder.buildModel(RuntimeModelBuilder.java:173)
	at org.glassfish.jersey.server.internal.routing.Routing$Builder.buildStage(Routing.java:196)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:587)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184)
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350)
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:311)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:337)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory
```

**Comment by wilkinsona** [comment] 2015-11-17 07:04
@nandhusriram Can you please provide a sample that reproduces the problem?

**Comment by nandhusriram** [comment] 2015-11-17 16:34
Here is my sample , if needed I can upload the whole project.

Application Class

@SpringBootApplication

public class Application {

	public static void main(String[] args) {
		
        SpringApplication.run(Application.class, args)
        .addApplicationListener(new org.springframework.boot.actuate.system.ApplicationPidFileWriter());
       
    }
}


Jersey Config

@Component
@ApplicationPath("/apis")
public class JerseyApiConfig  extends ResourceConfig
{

	public JerseyApiConfig() 
	{
		packages("com.test.endpoints");
	
    }
}


Endpoint Class

package com.test.endpoints;

@Component
@Path("test")

public class ServiceManagerResource
{
		@GET
	public String hello()
	{
		return "I am alive";
		
	}
}

Test Class

public class MyTestCase extends JerseyTest {

	
	@Override
	protected Application configure() {
		enable(TestProperties.LOG_TRAFFIC);
		enable(TestProperties.DUMP_ENTITY);		
		forceSet(TestProperties.CONTAINER_PORT, "0");		
	;
		
		ApplicationContext context = new AnnotationConfigApplicationContext(Application.class,ApplicationConfig.class);
		return new JerseyApiConfig().property("contextConfig", context);
	}

	@Override
	protected TestContainerFactory getTestContainerFactory()
			throws TestContainerException {		
		return new GrizzlyTestContainerFactory();
	}

@Test
	public void ping()
	{
		String ping=target().path("incident").request(MediaType.TEXT_PLAIN_TYPE)
		.accept(MediaType.TEXT_PLAIN_TYPE).buildGet().invoke(String.class);
		Assert.assertNotNull(ping);
	}
}

**Comment by snicoll** [comment] 2015-11-17 16:39
@nandhusriram  it's much more useful to share a repo url (or zip file) than dumping code here since we'll have to move that to a project anyway. Can you share a zip or a github repo url? Thanks!

**Comment by nandhusriram** [comment] 2015-11-18 03:24
Thanks will create a sample project and share the url , after some more debugging it looks like when I use packages to register endpoints  , rather than individual endpoints classes causing the issue.

**Comment by spring-issuemaster** [comment] 2015-12-15 11:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2015-12-22 11:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2015-12-22 11:05 UTC
