### ISSUE TITLE
Can no longer use ContextConfiguration initializer in 2.1.0 to assign random server port

### ISSUE THREAD

**Issue by arahlf** [spring-projects/spring-boot#15399] opened 2018-12-06 16:55 UTC
Perhaps this is somewhat of an obscure use case, but in my projects I've been using a custom PropertySource + initializer to set the server port in tests, primarily so that I can refer to the placeholder values in yaml profiles, without having to write code that can bind to ${local.server.port} when that eventually becomes available. Same thing also happens if I were to try and use the RandomValuePropertySource directly, so it doesn't seem specific to my custom PropertySource.

This worked fine in Spring Boot 1.5.x and Spring Boot 2 (up to 2.0.7), but as of 2.1.0, this idiom no longer works.

It would seem that the ContextConfiguration initializer now runs later in the process overall, and the server port is getting processed too early or something, and application startup fails with an exception:

    Caused by: java.lang.NumberFormatException: For input string: "${randomPort.app}"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:569)
        at java.lang.Integer.valueOf(Integer.java:766)

I've attached a sample application that works, and if you simply bump the Spring Boot version to 2.1.0 it'll start to fail.

[demo.zip](https://github.com/spring-projects/spring-boot/files/2654040/demo.zip)

Any ideas?

Thanks

**Comment by mbhave** [comment] 2018-12-06 16:58
Duplicate of #15354.

**Closed by mbhave** 2018-12-06 16:58 UTC
Labels: status: duplicate

**Comment by arahlf** [comment] 2018-12-06 19:56
Sorry for the duplicate, tried searching for similar ones but didn't stumble across that. Any ideas on a rough ETA when this might get fixed?

Thanks

**Comment by mbhave** [comment] 2018-12-06 21:39
No worries about the duplicate. It's assigned to the `2.1.x` milestone and it should be fixed in the next `2.1` maintenance release which is `2.1.2`.

If you have any further questions, feel free to ask them on gitter.
