### ISSUE TITLE
Better support for spring.profiles.active in yaml configuration

### ISSUE THREAD

**Issue by jgogstad** [spring-projects/spring-boot#5442] opened 2016-03-18 12:08 UTC
Parsing of the current active profiles could be better:
Doesn't work:
```yaml
---
spring:
  profiles:
    active:
      - dev
      - healthcheck
```

Doesn't work:
```yaml
---
spring:
  profiles:
    active: dev, healthcheck
```

Works (notice the space missing after comma):
```yaml
---
spring:
  profiles:
    active: dev,healthcheck
```

**Comment by snicoll** [comment] 2016-03-18 12:18
Good catch. That property is advertized as a String so it makes sense that the first example doesn't work (your IDE should warn you about that in theory). But we can do better I guess. 

Wen you say "doesn't work do you mean that it's trying to enable " healthcheck" instead of "healthcheck"?

**Comment by jgogstad** [comment] 2016-03-18 22:21
Most likely. It fails with an error message that the property can't be found. 

Regarding the first example, I guess you're right. I like the yaml syntax for representing lists, and I find it logical to use for properties like this, but it will probably look wierd in a property file.

**Comment by eddumelendez** [comment] 2016-04-04 06:00
I have submitted a PR. I tried to support the first scenario mentioned by @jgogstad 

```yaml
---
spring:
  profiles:
    active:
      - dev
      - healthcheck
```

But, in order to get the property we should access to `spring.profiles.active[0]` and `spring.profiles.active[1]` in the `propertySource`.

**Comment by snicoll** [comment] 2016-04-05 13:31
Closing in favour of the PR #5561

I had a quick look and using a list seems challenging at this point. As the property is advertized as a string value, this makes clear you can't use a list with it.

**Closed by snicoll** 2016-04-05 13:31 UTC
Labels: enhancement, ideal-for-contribution

**Comment by jgogstad** [comment] 2016-04-05 17:28
I believe fixing the space-bug goes a long way, although yaml lists would be nice.

I.e. make sure the following works:

    ---
    spring:
      profiles:
        active: dev, healthcheck

**Comment by wilkinsona** [comment] 2016-04-05 18:09
@jgogstad That works now that the PR from @eddumelendez has been merged. There's a test in https://github.com/spring-projects/spring-boot/commit/4353963df6d6b7af1c8f6a8620370b3fed23dfb2 which verifies it.

**Comment by anakidkin** [comment] 2019-01-26 09:40
Hi team!
Can we repeat the solution for the spring.profiles.include?

**Comment by wilkinsona** [comment] 2019-01-28 10:12
@anakidkin Things have moved on quite a bit in the almost 3 years since this change was made. AFAIK, `spring.profiles.include` and `spring.profiles.active` are now bound using the same logic and should, therefore, work in the same way. If you believe that's not the case, please open a new issue with a minimal sample (something that we can unzip or git clone and run) that reproduces the problem.
