### ISSUE TITLE
Conflicting dependencies in spring-boot-dependencies 3.1.0

### ISSUE THREAD

**Issue by rixterd2** [spring-projects/spring-boot#40371] opened 2024-04-16 12:46 UTC
Hello, 

My team noticed that in spring-boot-dependencies you're using Hibernate 6.2.2+
https://github.com/spring-projects/spring-boot/blob/bf97f6ca3cad6181e93e48a2db4b54905d51b5e4/spring-boot-project/spring-boot-dependencies/build.gradle#L368

However in spring-orm you're still using old 5.6.x version of hibernate.
https://github.com/spring-projects/spring-framework/blob/6.0.x/framework-platform/framework-platform.gradle#L125

This creates runtime errors due to Hibernate changed signature of Configuration class to https://github.com/hibernate/hibernate-orm/blob/6.2/hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java#L1020 from https://github.com/hibernate/hibernate-orm/blob/6.1/hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java#L816

This is just one example, I believe there could be more.

**Comment by bclozel** [comment] 2024-04-16 12:55
Could you share a concrete exception stacktrace, or error happening at runtime with this arrangement?

Spring Framework compiles against one version but [is forward compatible with multiple Hiberate versions](https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x#data-access-and-transactions-2). The Spring Boot CI contains multiple tests against this, so a concrete sample application would help here.

**Comment by rixterd2** [comment] 2024-04-16 12:59
> Could you share a concrete exception stacktrace, or error happening at runtime with this arrangement?
> 
> Spring Framework compiles against one version but [is forward compatible with multiple Hiberate versions](https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x#data-access-and-transactions-2). The Spring Boot CI contains multiple tests against this, so a concrete sample application would help here.

'JPA support for [Hibernate ORM 6.1](https://hibernate.org/orm/releases/6.1/) (retaining compatibility with Hibernate ORM 5.6).'

But spring-boot-dependencies offer `6.2.24.Final` version of Hibernate

**Comment by bclozel** [comment] 2024-04-16 13:04
> 'JPA support for [Hibernate ORM 6.1](https://hibernate.org/orm/releases/6.1/) (retaining compatibility with Hibernate ORM 5.6).'
> But spring-boot-dependencies offer 6.2.24.Final version of Hibernate

https://github.com/spring-projects/spring-framework/issues/29736

**Comment by bclozel** [comment] 2024-04-16 16:34
Thanks for the sample, closing as a duplicate of https://github.com/spring-projects/spring-framework/issues/31515#issuecomment-1782954634

**Closed by bclozel** 2024-04-16 16:34 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by rixterd2** [comment] 2024-04-16 18:33
You're definitely right about the error I've showcased. 

However that's not what I tried to show. To my mind the issue is bigger. We have spring framework 6 compiled against hibernate 5.6.x https://github.com/spring-projects/spring-framework/blob/6.0.x/framework-platform/framework-platform.gradle#L125

After that we offer Hibernate 6.2.24 in spring-boot-dependencies https://github.com/spring-projects/spring-boot/blob/bf97f6ca3cad6181e93e48a2db4b54905d51b5e4/spring-boot-project/spring-boot-dependencies/build.gradle#L368

Results could be unpredicatable for those who's based on these dependencies. Am I right ?

**Comment by wilkinsona** [comment] 2024-04-16 18:40
> Am I right?

No, I'm afraid not. As Brian already explained above, while Spring Framework compiles against Hibernate 5.6.x, it's also forwards compatible with multiple more recent Hibernate versions. That includes support for 6.2.x that was added in https://github.com/spring-projects/spring-framework/issues/29736.
