### ISSUE TITLE
Not fully consistent ordering in spring-configuration-metadata.json

### ISSUE THREAD

**Issue by zeldigas** [spring-projects/spring-boot#26217] opened 2021-04-23 08:14 UTC
[Current comparator implementation](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-tools/spring-boot-configuration-processor/src/main/java/org/springframework/boot/configurationprocessor/metadata/JsonConverter.java#L161-L189) produces not consistent order for special case, when a codebase contains multiple classes that shares same "namespace" and (optionally) same properties.

Consider this example:
```java
package com.example;

@ConfigurationProperties("app.section")
public class Foo {
  private int val;
}

@ConfigurationProperties("app.section")
public class Bar {
  private boolean flag;
  private int val;
}
```
As both classes share same section (and it works in runtime just fine), this leads to multiple outcomes in `groups` sections, as well as in `properties` section:
```json5
  "groups": [
    {
      "name": "app.section",                          // order can be swapped!
      "type": "com.example.Foo",
      "sourceType": "com.example.Foo"
    },
    {
      "name": "app.section",
      "type": "com.example.Bar",
      "sourceType": "com.example.Bar""
    }
  ],
```

Same is applied for `val` in this exampe, as name is same, but type/sourceType is different.

I understand that this is extreme example, but it is valid in terms of spring support, so I think that adding sort stage for type can solve this problem:
```java
private final Comparator<ItemMetadata> propertyComparator = Comparator.<ItemMetadata, Boolean>comparing(ItemMetadata::isDeprecated)
                .thenComparing(ItemMetadata::getName)
                .thenComparing(ItemMetadata::getType);
private final Comparator<ItemMetadata> groupComparator = Comparator.<ItemMetadata, String>comparing(ItemMetadata::getName).thenComparing(ItemMetadata::getType);
```

**Comment by snicoll** [comment] 2021-04-23 10:00
@zeldigas thanks for the suggestion. Curious what problem this causes for you concretely?

**Comment by zeldigas** [comment] 2021-04-23 10:24
@snicoll We are managing a set of libraries that we build in reproducible fashion using https://zlika.github.io/reproducible-build-maven-plugin/. One of the library has described setup - multiple beans sharing single section. When we changed build agents, we'd bump into this problem. With this issue fixed, we'd be able to get properly reproducible artifact.

**Comment by zeldigas** [comment] 2021-04-23 14:16
If you are fine with the proposed change, I'm ready to work on PR. Just let me know what branch to send (I think it'd make sense to fix it not just in master, but in earlier versions as well)

**Comment by philwebb** [comment] 2021-04-23 16:58
@zeldigas Thanks for the offer the PR. Submitting against master/main should be fine, we can rebase it onto any older branch when we merge. It would be helpful if there was a test to go along with the change. Thanks!

**Comment by zeldigas** [comment] 2021-04-23 19:17
Deal. I'm going to work on PR this weekend.

**Comment by zeldigas** [comment] 2021-04-25 10:03
PR is opened with small correction to original proposed fix - instead of Type, i'm using SourceType as it looks like `type` describes type of fields for properties, that will not provide good ordering compared to `sourceType` that identifies location.

**Comment by snicoll** [comment] 2021-04-25 11:28
Closing in favor of PR #26230

**Closed by snicoll** 2021-04-25 11:28 UTC
Labels: type: bug

**Comment by zeldigas** [comment] 2021-04-25 13:00
@snicoll could you please clarify, what's the purpose of closing issue if PR is not merged yet?

**Comment by snicoll** [comment] 2021-04-25 13:30
The issue is now superseded by the PR, as indicated by the label I've added.

**Comment by zeldigas** [comment] 2021-04-25 14:07
OK, looks like I need to get familiar with the process better, sorry.
