### ISSUE TITLE
problem with database health check

### ISSUE THREAD

**Issue by jevel0per** [spring-projects/spring-boot#10361] opened 2017-09-20 10:36 UTC
Hi!
We are using sprinng-boot 1.5.6.RELEASE with spring-boot-starter-actuator in our microservices.
The second one provides standarted health checks, and one of them is "checking DB connectivity".

Here is our bootstrap configuration:

```
  driverClassName : org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/....
  username: ...
  password: ...
```
  
In case DB is up, it works fine.
But in case DB is unavailable (stopped, or wrong url in configuration), we got 
`{"timestamp":1505405886998,"status":500,"error":"Internal Server Error","exception":"java.net.SocketTimeoutException","message":"Read timed out"}`
requesting url: /health instead of "DOWN" state.

Is it an issue in spring-boot-starter-actuator or we are dong something wrong?

**Comment by wilkinsona** [comment] 2017-09-20 10:47
> Is it an issue in spring-boot-starter-actuator or we are dong something wrong?

It's impossible to tell for sure based on the information you've provided. `DataSourceHealthIndicator` catches `Exception` and maps it to `DOWN` so it's not clear where the `SocketTimeoutException` is coming from. Can you please provide a minimal sample and the steps to follow to reproduce the behaviour you are seeing?

**Comment by spring-issuemaster** [comment] 2017-09-27 10:51
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-10-04 10:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-10-04 10:49 UTC
