### ISSUE TITLE
Spring boot Version - 2.0.3.RELEASE With Spel - Performance

### ISSUE THREAD

**Issue by ankurfintellix** [spring-projects/spring-boot#13641] opened 2018-07-03 12:23 UTC
Hi, 
Spring boot Version - 2.0.3.RELEASE

When trying to use SPEL for evaluating expressions, Threads are getting blocked.
This happens after multiple iterations. (Around 50 *4 iterations). 
Each iteration we have 10000 evaluations. 
50 Concurrent Thread and 4 Runs.  

The application performance deteriorates after the 4th run and only restart helps. 

Any suggestion will be helpful. 

```
SimpleAsyncTaskExecutor-7 - priority:5 - threadId:0x00007f6c88003000 - nativeId:0x1e369 - state:BLOCKED
stackTrace:
java.lang.Thread.State: BLOCKED (on object monitor)
at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:66)
- waiting to lock <0x000000070a180b50> (a java.lang.Object)
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1136)
at org.springframework.util.ClassUtils.forName(ClassUtils.java:274)
at org.springframework.expression.spel.support.StandardTypeLocator.findType(StandardTypeLocator.java:103)
at org.springframework.expression.spel.support.ReflectiveConstructorResolver.resolve(ReflectiveConstructorResolver.java:59)
at org.springframework.expression.spel.ast.ConstructorReference.findExecutorForConstructor(ConstructorReference.java:191)
at org.springframework.expression.spel.ast.ConstructorReference.createNewInstance(ConstructorReference.java:158)
at org.springframework.expression.spel.ast.ConstructorReference.getValueInternal(ConstructorReference.java:100)
at org.springframework.expression.spel.ast.OpLE.getValueInternal(OpLE.java:48)
at org.springframework.expression.spel.ast.OpLE.getValueInternal(OpLE.java:37)
at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:116)
at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:306)
```

**Comment by wilkinsona** [comment] 2018-07-03 12:30
It's difficult to make suggestions with only a stack trace and no information about the expression that is being evaluated. If you'd like us to spend some time trying to suggest something, please take the time to provide a minimal sample (something that we can unzip or git clone and run) that reproduces the behaviour you have described.

**Comment by spring-issuemaster** [comment] 2018-07-10 12:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-07-17 12:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-07-17 12:35 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
