### ISSUE TITLE
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured

### ISSUE THREAD

**Issue by oselene** [spring-projects/spring-boot#15758] opened 2019-01-22 12:01 UTC
i keep getting the error message on my title
here is my pom.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>Eventar</groupId>
	<artifactId>Eventar</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>report</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.5.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!-- Jackson -->
		<dependency> <groupId>com.fasterxml.jackson.core</groupId> <artifactId>jackson-databind</artifactId> 
			</dependency>
		<!-- <dependency> <groupId>org.apache.tomcat.embed</groupId> <artifactId>tomcat-embed-jasper</artifactId> 
			<scope>provided</scope> </dependency> -->

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
		<!-- <dependency> <groupId>com.h2database</groupId> <artifactId>h2</artifactId> 
			<scope>runtime</scope> </dependency> -->
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>

		</dependency>
		<!-- Jackson -->
		<!-- <dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency> -->

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>


		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
		</dependency>


		<!-- Database Connection Pooling -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-dbcp2</artifactId>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
         <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- Hibernate Dependency -->
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.6</version>
		</dependency>

		<!-- <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency> -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

my application.properties is

```properties
server.port = 8085                       
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/eventar?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
server.error.whitelabel.enabled=false
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
```

please how can i resolve this issue

**Comment by oselene** [comment] 2019-01-22 12:02
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by oselene** [comment] 2019-01-22 12:04
i also get this error when i run maven test or build

URLClassPath$JarLoader.getJarFile(URL) line: not available in spring

**Comment by wilkinsona** [comment] 2019-01-22 13:09
I can't see anything that's obviously wrong from what you've shared thus far. There are a few things that are unusual (use of Jasper with war packaging, use of provided on the Data JPA dependency, etc) but none that should cause the problem that you're seeing.

Can you please share a complete, minimal project that reproduces the problem? That should be something that we can attachment that unzip or a Git repository that we can clone and then build with Maven.

**Comment by spring-issuemaster** [comment] 2019-01-29 13:11
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-05 13:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-05 13:12 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by mguilhermetavares** [comment] 2020-01-20 12:20
any news?

**Comment by snicoll** [comment] 2020-01-20 12:24
@mguilhermetavares this issue is closed as we didn't get the [sample that we requested](https://github.com/spring-projects/spring-boot/issues/15758#issuecomment-456393379). If you're having a problem, feel free to create a separate issue with the requested sample.

**Comment by jometho** [comment] 2020-03-30 05:58
@oselene how did you resolve this? I'm facing the same issue

**Comment by salambrosalam** [comment] 2020-04-17 20:26
Yeees i have the same problem ... Well i gonna return to Eclipse )))

**Comment by break-ke** [comment] 2021-07-12 06:26
I  need help

**Comment by snicoll** [comment] 2021-07-12 06:28
@break-ke there is a [section about that](https://github.com/spring-projects/spring-boot/#getting-help) in the README of this repository. Please follow-up on StackOverflow or come chat with the community on Gitter.

**Comment by juxuny** [comment] 2023-04-29 17:54
> ```
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
> 
> Reason: Failed to determine a suitable driver class
> 
> 
> Action:
> 
> Consider the following:
> 	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
> 	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
> ```

I also get this error when I run `maven install` with orcale open JDK 1.8.
Then, I switch to corretto open JDK 1.8, every thing work well.
