### ISSUE TITLE
DevTools hot reload crashes when instantiating an entity with properties declared as interfaces from spring data repository

### ISSUE THREAD

**Issue by saljuama** [spring-projects/spring-boot#5098] opened 2016-02-05 21:26 UTC
I've managed to get dev tools hot reloads to crash, in the following scenario: 
A project, with Spring Data MongoDB, with a `@Document` class, that includes a property declared as an interface, and then using the spring data repository of that class in a `CommandLineRunner`

It works fine and as intended, application restarts are successful, but hot reloads with dev tools fail.

I've asked in StackOverflow this [question](http://stackoverflow.com/q/35225408/4207875) before opening this ticket, and now I've created a project to demonstrate and reproduce the issue found [here] (https://github.com/saljuama/devtols-hotreload-crash-demo).

**Comment by wilkinsona** [comment] 2016-02-08 16:48
Thank you for putting together a sample project. I've reproduced the problem.

**Comment by wilkinsona** [comment] 2016-02-08 17:23
The problem's caused by Spring Data's `SimpleTypeInformationMapper`. It holds a static cache of `String` -> `ClassTypeInformation` with the latter holding `Class` objects.

**Comment by wilkinsona** [comment] 2016-02-08 17:48
I have a workaround that implements a `RestartListener` to clear the cache, but I wonder if it wouldn't be better to fix this in Spring Data. As things stand, `SimpleTypeInformationMapper` will cache stale data in any environment where it's loaded in one class loader and the types that its caching are loaded in another. One example, as seen here, is DevTools. Another would be in a servlet container with Spring Data installed as a library that's shared between multiple web applications.

What's you take on this please, @olivergierke?

**Comment by wilkinsona** [comment] 2016-02-08 17:50
The aforementioned workaround is available in [this branch](https://github.com/wilkinsona/spring-boot/tree/gh-5098) of my fork.

**Comment by olivergierke** [comment] 2016-02-08 19:44
I'll have that fixed by tomorrow morning.

**Comment by olivergierke** [comment] 2016-02-09 13:24
I've filed and fixed [DATACMNS-815](https://jira.spring.io/browse/DATACMNS-815).

**Comment by wilkinsona** [comment] 2016-02-10 11:39
Thanks, @olivergierke. I've opened #5119 to track our upgrade to Gosling SR3.

@saljuama I'm going to close this as it'll be addressed in 1.3.3 by #5119

**Closed by wilkinsona** 2016-02-10 11:39 UTC
Labels: bug

**Comment by saljuama** [comment] 2016-02-10 12:04
You guys are awesome, that was really quick!
