### ISSUE TITLE
Be able to exclude dependencies by scope

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#16657] opened 2019-04-25 14:04 UTC
https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/exclude-dependency.html

Having to exclude provided dependencies "by hand", rather than just having a flag for excluding any provided scope is fragile and tedious as you have to handle each dependency rather than by scope.

I suggest a flag to ignore provided dependencies from the packaging.

**Comment by snicoll** [comment] 2019-04-25 14:13
> 🎁 Enhancement (do not copy/paste)

There is a "do not copy paste" section there so please don't. We don't need an issue type, the purpose of the template is to give a check list depending on what you aim to report.

**Comment by snicoll** [comment] 2019-04-25 14:15
Duplicate of #13289

**Closed by snicoll** 2019-04-25 14:15 UTC
Labels: status: waiting-for-triage
