### ISSUE TITLE
Add optional sort parameter to metrics endpoint

### ISSUE THREAD

**Issue by ST-DDT** [spring-projects/spring-boot#14266] opened 2018-08-31 09:01 UTC
Based on #3761 (Actuator v1)

I use the actuator v2 metrics to monitor my applications using Prometheus and Grafana.
However if I try to setup a new dashboard and search for a metric that was provided by a specific application, then I'm mostly in the dark which metrics will be provided by which application.

In that case I use the metrics endpoint to search for important metrics. Some applications have jdbc, kafka or even custom metrics. Currently that list has no specific order, it would be easier to search that list, if it was sorted.

In #3761 it was mentioned that sorting that list all the time is a waste of performance, but sorting that list on demand would be a nice feature.

It might be possible to do it similar to this:

````java
@ReadOperation
// GET /actuator/metrics?sort=true
public ListNamesResponse listNames(@Nullable Boolean sort) {
	final Set<String> names;
	if (sort != null && sort) {
		names = new TreeSet<>();
	} else {
		names = new LinkedHashSet<>();
	}
	collectNames(names, this.registry);
	return new ListNamesResponse(names);
}
````

In previous versions it was possible to use browser options to sort that list, but that is no longer easily possible because the data are now contained in a json-list.

**Considered alternatives**

* Download metrics list and sort it manually (ugly).
   ` curl --silent https://<server>/actuator/metrics | jq .names | grep "\"" | sed -e 's/^...//' -e 's/..$//' | sort`
* Detect human visitors/their browsers automatically (much more overhead).
* Add a new file format (CSV?/TXT) that exposes an ordered variant (much more overhead).

**Environment**

* Spring Boot 2
  * spring-boot-starter-actuator
* Spring 5
* micrometer-registry-prometheus
* Java 8
* Maven 3.5

**Comment by mitchellirvin** [comment] 2018-08-31 18:08
@snicoll Is this issue a good one for somebody who's new to open source? Would like to contribute to Spring Boot if possible, been using it a ton!

**Comment by snicoll** [comment] 2018-08-31 18:31
Thanks for offering to help but we haven’t triaged this issue yet (see the status label). There is an ideal for contribution label with some candidate issues though.

**Comment by wilkinsona** [comment] 2018-09-03 10:54
Thanks for the suggestion. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/6321. My opinion remains that, particularly as the response isn't paged, sorting is a client-side concern.

> However if I try to setup a new dashboard and search for a metric that was provided by a specific application, then I'm mostly in the dark which metrics will be provided by which application.

Given that this is, apparently, the underlying problem. I would recommend using a tag on all metrics to identify the application from which they originate.

**Closed by wilkinsona** 2018-09-03 10:54 UTC
Labels: status: waiting-for-triage
