### ISSUE TITLE
Broken Link in Documentation - Spring Boot JPA

### ISSUE THREAD

**Issue by Helicer** [spring-projects/spring-boot#12585] opened 2018-03-21 19:35 UTC
There is a broken link in the section "29.3.2 Spring Data JPA Repositories" of the Spring Boot documentation. 

Renders as:
"{http://projects.spring.io/spring-data-jpa/}[Spring Data JPA] repositories are interfaces that you can define to access data. "

Link to document: 
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-data-jpa-repositories

**Comment by wilkinsona** [comment] 2018-03-21 20:06
Thanks for the report. This is a duplicate of https://github.com/spring-projects/spring-boot/pull/12342.

**Closed by wilkinsona** 2018-03-21 20:06 UTC
Labels: status: waiting-for-triage
