### ISSUE TITLE
VMError$HostedError with Spring Boot 3.0.6 and AOT

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#35335] opened 2023-05-06 10:36 UTC
The attached testcase results in the stacktrace below when using Spring Boot _3.0.6_, but works fine with _3.0.5_. Just invoke `.\gradlew clean nativeCompile --rerun-tasks`. You can switch between Spring Boot versions in `gradle/libs.versions.toml`. Additionally, you can change the Gradle version to be used in `gradle/wrapper/gradle-wrapper.properties`. The testcase and the whole output are attached.
```
>.\gradlew clean nativeCompile --rerun-tasks
...
[7/7] Creating image...                                                                                  (0,0s @ 4,80GB)
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.VMError$HostedError: Registering type as reachable after analysis: AnalysisType<org.springframework.plugin.core.Plugin[], allocated: 0, inHeap: 0, reachable: 0>
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:696)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.svm.core.util.VMError$HostedError: Registering type as reachable after analysis: AnalysisType<org.springframework.plugin.core.Plugin[], allocated: 0, inHeap: 0, reachable: 0>
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.registerAsReachable(AnalysisConstantReflectionProvider.java:252)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.HostedDynamicHubFeature.replace(HostedDynamicHubFeature.java:52)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:595)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addArrayElements(NativeImageHeap.java:576)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObjectToImageHeap(NativeImageHeap.java:473)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:295)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:598)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:198)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:678)
        ... 4 more
```
[output.txt](https://github.com/spring-projects/spring-boot/files/11412121/output.txt)
[testcase.zip](https://github.com/spring-projects/spring-boot/files/11412122/testcase.zip)

**Comment by snicoll** [comment] 2023-05-06 11:23
Thanks for the test case. This is a duplicate of https://github.com/spring-projects/spring-framework/issues/30407

**Closed by snicoll** 2023-05-06 11:23 UTC
Labels: status: waiting-for-triage
