### ISSUE TITLE
Incorrect detection of Amazon Redshift

### ISSUE THREAD

**Issue by lbruun** [spring-projects/spring-boot#25128] opened 2021-02-07 22:05 UTC
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem
Detection of Amazon Redshift in [org.springframework.boot.jdbc.DataBaseDriver](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/DatabaseDriver.java#L73) is incorrect.  The Redshift JDBC driver returns [`Redshift` as the `productName`](https://github.com/aws/amazon-redshift-jdbc-driver/blob/3c337cb9bb6590fe23a1aa9f5f121a7e29a3655e/src/main/java/com/amazon/redshift/jdbc/RedshiftDatabaseMetaData.java#L153) but we are using `Amazon Redshift` as the `productName`.

## Solution
Update the [`DatabaseDriver`](https://github.com/spring-projects/spring-boot/blob/301e80be8c4da73dd734d93f915088de4997c88c/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/jdbc/DatabaseDriver.java) enum with the right value for the `productName` for `Redshift`.

Update [the tests](https://github.com/spring-projects/spring-boot/blob/301e80be8c4da73dd734d93f915088de4997c88c/spring-boot-project/spring-boot/src/test/java/org/springframework/boot/jdbc/DatabaseDriverTests.java) to ensure that the right `DatabaseDriver.fromProductName()` works for `Redshift`.

## Steps to Fix 
 
- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by anudeepg** [comment] 2021-02-10 16:43
@scottfrederick  As I am fixing similar issue of MariaDB https://github.com/spring-projects/spring-boot/issues/25127 
Can i claim this issue as well to fix ?

**Comment by philwebb** [comment] 2021-02-10 20:03
@anudeepg Thanks for the offer, but can we give someone else a chance to do this one. We're keen to get as many first-timers as possible.

**Comment by anudeepg** [comment] 2021-02-10 20:21
> @anudeepg Thanks for the offer, but can we give someone else a chance to do this one. We're keen to get as many first-timers as possible.

**Comment by anudeepg** [comment] 2021-02-10 20:24
Sure, thanks for giving chance to first-timers. I will check any other issues if I can contribute.

**Comment by melburne** [comment] 2021-02-12 16:40
Hi @philwebb , Can I pick this one up if no one else is working on it?

**Comment by snicoll** [comment] 2021-02-13 08:30
@melburne the issue is all yours, let us know if you have any questions.

**Comment by snicoll** [comment] 2021-02-15 16:10
Closing in favor of PR #25265

**Closed by snicoll** 2021-02-15 16:10 UTC
Labels: status: first-timers-only, type: bug
