### ISSUE TITLE
spring-boot-starter-webflux can't start multiple listeners

### ISSUE THREAD

**Issue by baiyangliu** [spring-projects/spring-boot#13188] opened 2018-05-16 06:39 UTC
pom.xml
```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>2.0.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
    </dependencies>
```

application.properties
```properties
server.port=0
```

```java
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory;
import org.springframework.context.annotation.Bean;

import java.util.Collections;

@SpringBootApplication
public class TestApplication {
    @Bean
    public NettyReactiveWebServerFactory nettyReactiveWebServerFactory(@Value("${server.port.secondary:9999}") int port) {
        NettyReactiveWebServerFactory factory = new NettyReactiveWebServerFactory();
        factory.setServerCustomizers(Collections.singleton(builder -> builder.port(port)));
        return factory;
    }

    public static void main(String[] args) {
        SpringApplication.run(TestApplication.class, args);
    }
}
```

But,port 9999 not work,here is the output log.
```text
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.2.RELEASE)

2018-05-16 14:33:21.878  INFO 5644 --- [           main] com.huawei.test_webflux.TestApplication  : Starting TestApplication on x with PID 5644 (x\target\classes started by x in x)
2018-05-16 14:33:21.882  INFO 5644 --- [           main] com.huawei.test_webflux.TestApplication  : No active profile set, falling back to default profiles: default
2018-05-16 14:33:21.927  INFO 5644 --- [           main] onfigReactiveWebServerApplicationContext : Refreshing org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@7d9f158f: startup date [Wed May 16 14:33:21 CST 2018]; root of context hierarchy
2018-05-16 14:33:22.688  INFO 5644 --- [           main] o.s.w.r.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.reactive.resource.ResourceWebHandler]
2018-05-16 14:33:22.688  INFO 5644 --- [           main] o.s.w.r.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.reactive.resource.ResourceWebHandler]
2018-05-16 14:33:22.760  INFO 5644 --- [           main] o.s.w.r.r.m.a.ControllerMethodResolver   : Looking for @ControllerAdvice: org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@7d9f158f: startup date [Wed May 16 14:33:21 CST 2018]; root of context hierarchy
2018-05-16 14:33:23.029  INFO 5644 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-05-16 14:33:23.139  INFO 5644 --- [ctor-http-nio-1] r.ipc.netty.tcp.BlockingNettyContext     : Started HttpServer on /0:0:0:0:0:0:0:0:15195
2018-05-16 14:33:23.140  INFO 5644 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 15195
2018-05-16 14:33:23.144  INFO 5644 --- [           main] com.huawei.test_webflux.TestApplication  : Started TestApplication in 1.562 seconds (JVM running for 2.119)
```

**Comment by wilkinsona** [comment] 2018-05-16 06:45
Duplicate of #12035

**Closed by wilkinsona** 2018-05-16 06:45 UTC
Labels: status: waiting-for-triage

**Comment by baiyangliu** [comment] 2018-05-16 07:27
and this works!

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>2.0.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>
    </dependencies>
```

```text
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.2.RELEASE)

2018-05-16 15:25:04.174  INFO 14020 --- [           main] com.huawei.test_webflux.TestApplication  : Starting TestApplication on x with PID 14020 (x started by l00411972 in x)
2018-05-16 15:25:04.178  INFO 14020 --- [           main] com.huawei.test_webflux.TestApplication  : No active profile set, falling back to default profiles: default
2018-05-16 15:25:04.228  INFO 14020 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@4a07d605: startup date [Wed May 16 15:25:04 CST 2018]; root of context hierarchy
2018-05-16 15:25:10.435  INFO 14020 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2018-05-16 15:25:10.451  INFO 14020 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2018-05-16 15:25:10.477  WARN 14020 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2018-05-16 15:25:10.478  WARN 14020 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2018-05-16 15:25:10.495  INFO 14020 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2018-05-16 15:25:10.496  INFO 14020 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6271 ms
2018-05-16 15:25:10.570  INFO 14020 --- [           main] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-05-16 15:25:10.574  INFO 14020 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-05-16 15:25:10.574  INFO 14020 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-05-16 15:25:10.575  INFO 14020 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-05-16 15:25:10.575  INFO 14020 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-05-16 15:25:10.667  INFO 14020 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-05-16 15:25:10.825  INFO 14020 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@4a07d605: startup date [Wed May 16 15:25:04 CST 2018]; root of context hierarchy
2018-05-16 15:25:10.869  INFO 14020 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2018-05-16 15:25:10.870  INFO 14020 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-05-16 15:25:10.892  INFO 14020 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-05-16 15:25:10.892  INFO 14020 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-05-16 15:25:11.005  INFO 14020 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-05-16 15:25:11.052  INFO 14020 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 21492 (http) 9999 (http) with context path ''
2018-05-16 15:25:11.054  INFO 14020 --- [           main] com.huawei.test_webflux.TestApplication  : Started TestApplication in 7.16 seconds (JVM running for 7.713)
```

**Comment by wilkinsona** [comment] 2018-05-16 07:30
You've created a custom `UndertowServletWebServerFactory`. For a WebFlux app, it's a `UndertowReactiveWebServerFactory` that's used.

**Comment by baiyangliu** [comment] 2018-05-16 07:59
it doesn't work.
```java
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.embedded.undertow.UndertowBuilderCustomizer;
import org.springframework.boot.web.embedded.undertow.UndertowReactiveWebServerFactory;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class TestApplication {
    @Bean
    public UndertowReactiveWebServerFactory undertowReactiveWebServerFactory(@Value("${server.port.secondary:9999}") int port) {
        UndertowReactiveWebServerFactory factory = new UndertowReactiveWebServerFactory();
        factory.addBuilderCustomizers((UndertowBuilderCustomizer) builder -> builder.addHttpListener(port, "0.0.0.0"));
        return factory;
    }

    public static void main(String[] args) {
        SpringApplication.run(TestApplication.class, args);
    }
}
```

```text
...
2018-05-16 15:58:02.843  INFO 5920 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 25301 (http) with context path ''
2018-05-16 15:58:02.846  INFO 5920 --- [           main] com.huawei.test_webflux.TestApplication  : Started TestApplication in 1.7 seconds (JVM running for 2.264)
```

**Comment by baiyangliu** [comment] 2018-05-16 08:02
@wilkinsona It works!Thank you very much!

**Comment by emvidi** [comment] 2018-05-21 15:08
Is there a way to have this working with netty as well? I have tried the above NettyReactiveWebServerFactory but it does not work.

**Comment by wilkinsona** [comment] 2018-05-21 15:13
@emvidi No, not yet. Please see https://github.com/spring-projects/spring-boot/issues/12035 which is already referenced above.

**Comment by emvidi** [comment] 2018-05-21 15:18
Ok, my mistake, thank you Andy.

**Comment by liuzwei** [comment] 2019-09-29 06:09
spring cloud gateway not support listen both http and https?

**Comment by snicoll** [comment] 2019-09-29 08:02
@liuzwei please don't ask question on closed issues, as mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. There is a #spring-cloud Gitter channel if you want to chat with the community or you can ask on StackOverflow.
