### ISSUE TITLE
spring-boot jersey based application : can not start without errors using java -jar

### ISSUE THREAD

**Issue by wuqunfei** [spring-projects/spring-boot#3958] opened 2015-09-14 09:06 UTC
@wilkinsona, I fix this probem. But I don't know which jesery version I can make a pull request. Because spring boot using jesery 2.14, but on github jesery does not have 2.14 branch, just have 2.10.x version. I hope we could merge my change at once.

**Comment by wuqunfei** [comment] 2015-09-14 09:14
https://github.com/alexleigh/jersey/commit/198687f9f00404cb2a81e0b8edd230959baea18b
And this code changes is not working in fact, I test on local and make new changes as follow. 

```
    private InputStream getInputStream(String jarUrlString) throws IOException {
        try {
            InputStream inputStream = null;
            if (jarUrlString.contains("!")) {
                jarUrlString = jarUrlString.replace("file:", "");
                inputStream = getInnerJarInputStream(jarUrlString, inputStream);
            } else {
                inputStream = new URL(jarUrlString).openStream();
            }
            if (inputStream == null) {
                new RuntimeException("input stream is empty from " + jarUrlString);
            }
            return inputStream;

        } catch (MalformedURLException e) {
            return new FileInputStream(
                    UriComponent.decode(jarUrlString, UriComponent.Type.PATH));
        }
    }

    private InputStream getInnerJarInputStream(String jarUrlString, InputStream inputStream) throws IOException {
        String jars[] = jarUrlString.split("!");
        if (jars.length == 2) {
            inputStream = readInnerJar(inputStream, jars);
        }
        return inputStream;
    }

    private InputStream readInnerJar(InputStream inputStream, String[] jars) throws IOException {
        String jarFileName = jars[0];
        String libFileName = jars[1].substring(1);
        if (this.isLibraryFile(jarFileName) && this.isLibraryFile(libFileName)) {
            ZipFile zip = new ZipFile(jarFileName);
            inputStream = zip.getInputStream(new ZipEntry(libFileName));
        }
        return inputStream;
    }

    private boolean isLibraryFile(String fileName) {
        boolean flag = false;
        Iterator iterator = this.getSchemes().iterator();
        while (iterator.hasNext()) {
            String fileType = "." + iterator.next();
            if (fileName.contains(fileType)) {
                flag = true;
                break;
            }
        }
        return flag;
    }

```
@wilkinsona , my jesery branch from jesery 2.14 tag is here https://github.com/wuqunfei/jersey/commit/2effce3fea521dee026a9d7103ee4e7099d9dbf9. Please tell me which jesery branch I can pull request to them, then spring boot could use it.

**Comment by wilkinsona** [comment] 2015-09-14 10:38
This is a duplicate of #1468 which you have already commented on. I have replied there.

**Closed by wilkinsona** 2015-09-14 10:38 UTC
