### ISSUE TITLE
Enhance documentation for log4j and gradle users

### ISSUE THREAD

**Issue by MALPI** [spring-projects/spring-boot#13462] opened 2018-06-13 09:44 UTC
I was adding `spring-boot-starter-log4j2` as dependency to one of my projects. I was following the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html#howto-configure-log4j-for-logging). Though I missed that maven handles exlusions different then gradle. In maven the exclude happens globally whereas in gradle it needs to be done per artifact or by global configuration. 

Therefore my stack was running into `StackoverflowException`. By adding an explicit gradle example, this confusion could be avoid:

```
configurations {
    all*.exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
}
```
Best

**Comment by wilkinsona** [comment] 2018-06-13 09:57
Duplicate of #12729.

**Closed by wilkinsona** 2018-06-13 09:57 UTC
Labels: type: documentation
