### ISSUE TITLE
PropertiesLauncher does not take into account nested libraries in modules

### ISSUE THREAD

**Issue by dcoraboeuf** [spring-projects/spring-boot#9853] opened 2017-07-25 06:53 UTC
Hi, I'm using Spring Boot 1.5.4 with JDK 1.8.0_121.

I'm using the `PropertiesLauncher` on the main application (ZIP layout) and point to a local `extensions` directory containing JAR files packaged with the `MODULE` layout (or a custom layout doing the same thing to prepare for 2.0). This extension JAR has itself a third-party dependency included in its `lib` directory.

This can be summarised by:

```
application.jar
lib/
   |-- module.jar
            |-- my/classes
            |-- lib/
                   |-- third-party.jar
```

When I launch the application using:

```bash
java -Dloader.path=lib -jar application.jar
```

The `module.jar` is correctly included in the classpath, but not the `third-party.jar` nested dependency.

When looking at the `PropertiesLauncher` code, I see that indeed the nested libraries are not resolved in a recursive way.

Best regards,
Damien.

**Comment by wilkinsona** [comment] 2017-07-25 07:27
This is already supported (see https://github.com/spring-projects/spring-boot/issues/8334) and the functionality is [described in the documentation](http://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#executable-jar-property-launcher-features) for configuring `loader.path`:

> `loader.path` can contain directories (scanned recursively for jar and zip files), archive paths, a directory within an archive that is scanned for jar files (for example, `dependencies.jar!/lib`), or wildcard patterns (for the default JVM behavior). Archive paths can be relative to `loader.home`, or anywhere in the file system with a `jar:file:` prefix.

**Comment by wilkinsona** [comment] 2017-07-25 07:28
Duplicate of #8334

**Closed by wilkinsona** 2017-07-25 07:27 UTC
Labels: status: waiting-for-triage

**Comment by LiuXiaoJie** [comment] 2017-09-04 11:48
@wilkinsona Could “!/lib” work with wildcard？Using “*!/lib” throw “File must exist” error.

**Comment by wilkinsona** [comment] 2017-09-04 12:37
@LiuXiaoJie I'd rather not make the launcher any more complicated than it already is.

**Comment by LiuXiaoJie** [comment] 2017-09-04 16:26
@wilkinsona Understood. But this is really useful for some plugin modules, I will try some other ways. Thanks for your reply.
