### ISSUE TITLE
Make it clearer that, when using `@AutoConfigureTestEntityManager` outside of `@DataJpaTest`, any tests using the test entity manager must be `@Transactional`

### ISSUE THREAD

**Issue by rd-malte-mauelshagen** [spring-projects/spring-boot#28067] opened 2021-09-20 15:48 UTC
Spring Boot Version: 2.5.4

I am having the problem to use a `TestEntityManager` in a `SpringBootTest`. Basically, I followed the instruction from [here](https://docs.spring.io/spring-boot/docs/2.5.4/reference/htmlsingle/#features.testing.spring-boot-applications.autoconfigured-spring-data-jpa)  where it says:

> If you want to use `TestEntityManager` outside of `@DataJpaTest` instances, you can also use the `@AutoConfigureTestEntityManager` annotation. 

This seems to be the same issue as #27146 which had been closed due to inactivity though.

I attached a zip with a minimal example. The error message can be reproduced by running the DemoApplicationTests.
[spring-test-problem.zip](https://github.com/spring-projects/spring-boot/files/7196932/spring-test-problem.zip)

Error message: `java.lang.IllegalStateException: No transactional EntityManager found `

Note: I am using JUnit 4 and h2 database. Is this a problem?

**Comment by wilkinsona** [comment] 2021-09-20 16:37
Thanks for providing a sample. The problem is occurring because your tests are not `@Transactional`. Annotating your test class or method with `org.springframework.transaction.annotation.Transactional` will fix it. We can use this issue to clarify the documentation.

**Comment by wilkinsona** [comment] 2021-09-20 16:40
We could maybe also improve the message in the assertion in TestEntityManager.getEntityManager()`. It currently says "No transactional EntityManager found". Perhaps we should say something like "No transactional EntityManager found. Are your tests annotated with @Transactional?" instead.

**Comment by rd-malte-mauelshagen** [comment] 2021-09-20 17:08
Yes that would be great!
Also, while you are at it, you could improve the documentation [here](https://docs.spring.io/spring-boot/docs/2.5.4/reference/htmlsingle/#features.testing.spring-boot-applications.autoconfigured-spring-data-jpa) because in the code snippet the method is NOT annotated with `@Transactional`. I guess it is because it's a JPA Test and not a SpringBootTest? Either way, some more information there would be helpful!

**Comment by wilkinsona** [comment] 2021-09-20 17:16
`@DataJpaTest` is itself annotated with `@Transactional` so any class annotated with `@DataJpaTest` is implicitly `@Transactional` as well. It's only when you're using `@SpringBootTest` (where tests are not transactional by default) and `@AutoConfigureTestEntityManager` that you need to explicitly use `@Transactional` as well.

**Comment by wilkinsona** [comment] 2021-09-22 08:09
Closing in favor of #28086.

**Closed by wilkinsona** 2021-09-22 08:09 UTC
Labels: type: documentation
