### ISSUE TITLE
Document that profiles activated in ~/.spring-boot-devtools.properties will not affect loading of profile-specific configuration files

### ISSUE THREAD

**Issue by michaldo** [spring-projects/spring-boot#15151] opened 2018-11-11 10:31 UTC
## Config
File | Content
------------ | -------------
application-z.properties | foo=baz
.spring-boot-devtools.properties | spring.profiles.active: z

## App

```java
public class MyApp {
	public static void main(String[] args) {
		SpringApplication.run(MyApp.class, args);
                System.out.println("********");
		SpringApplication.run(MyApp.class, "--spring.profiles.include=z");
	}
	
	@Value("${foo:bar}")
	String foo;
	
	@PostConstruct
	void printFoo() {
		System.out.println(foo);
	}
}
```

## Output

>
 :: Spring Boot ::        (v2.1.0.RELEASE)

2018-11-11 11:20:56.473  INFO 10934 --- [  restartedMain] devproftest.MyApp                        : The following profiles are active: z
bar
********
 :: Spring Boot ::        (v2.1.0.RELEASE)
2018-11-11 11:20:56.586  INFO 10934 --- [  restartedMain] devproftest.MyApp                        : The following profiles are active: z
baz

## Expected output

`baz`, as defined in profile `z` should be displayed twice

PS. The order of running apps is important - if reverted `baz` is correctly displayed twice. Please do not be confused by double running - it is used only to have clear test scenario

**Comment by wilkinsona** [comment] 2018-11-12 09:52
Thanks for the report. The problem is that `org.springframework.boot.devtools.env.DevToolsHomePropertiesPostProcessor` is unordered so it runs after `ConfigFileApplicationListener`. As a result, the activation of the `z` profile is missed when `ConfigFileApplicationListener` is determining from which files properties should be loaded.

We should be able to fix the problem by ordering `DevToolsHomePropertiesPostProcessor` with tiger precedence than `ConfigFileApplicationListener`. I am a little wary of unanticipated side effects though. Flagging for team attention to decrease the likelihood of something being overlooked.

**Comment by mbhave** [comment] 2018-11-13 00:19
Closing as a duplicate of #13875. @wilkinsona I've carried over the `for: team-attention` to the other one but feel free to remove it.

**Comment by wilkinsona** [comment] 2018-11-14 09:30
Thanks, @mbhave. I'd completely forgotten about #13875.

**Comment by wilkinsona** [comment] 2018-11-14 16:29
We're going to use this issue to document the current limitation. We'll use #13875 to hopefully remove the limitation in 2.2.

**Closed** 2018-11-27 12:12 UTC
Labels: type: documentation
