### ISSUE TITLE
Configuration processor does not handle parent abstract class

### ISSUE THREAD

**Issue by qwazer** [spring-projects/spring-boot#15936] opened 2019-02-13 07:39 UTC
Given
```java
public abstract class FlowProperties {
    /**
     * Enable flow 
     */
    protected boolean enabled = true;
    /**
     * Number of worker threads
     */
    protected int threadCount = 4;
//getter, setters
}
```

```java
@ConfigurationProperties(prefix = "account.flow")
@Validated
@Component
public class AccountFlowProperties extends FlowProperties
```

The generated metadata is

```json

    {
      "name": "account.flow.enabled",
      "type": "java.lang.Boolean",
      "sourceType": "acme.AccountFlowProperties"
    },

    {
      "name": "account.flow.thread-count",
      "type": "java.lang.Integer",
      "sourceType": "acme.AccountFlowProperties"
    },
```

But should be

```json

    {
      "name": "account.flow.enabled",
      "type": "java.lang.Boolean",
      "description": "Enable flow",
      "sourceType": "acme.AccountFlowProperties",
      "defaultValue": true
    },

    {
      "name": "account.flow.thread-count",
      "type": "java.lang.Integer",
      "description": "Number of worker threads",
      "sourceType": "acme.AccountFlowProperties",
      "defaultValue": 4
    },
```

Possibly can be improved with #15850

**Comment by snicoll** [comment] 2019-02-13 07:47
Duplicate of #3485

**Closed by snicoll** 2019-02-13 07:47 UTC
Labels: status: waiting-for-triage

**Comment by snicoll** [comment] 2019-02-13 07:48
@qwazer for the record, if you don't get javadoc either that's probably because the parent is defined in another module. If you've defined that in another module the annotation processor does not have access to the source model (it's not the same compilation unit) and we have no way to read that source level information so even if #3485 is resolved, it won't work for that use case.

**Comment by qwazer** [comment] 2019-02-13 08:08
@snicoll , Thanks for the comment. It's my case. I moved the common parent class to a separate module.

**Comment by snicoll** [comment] 2019-02-13 08:09
@qwazer thanks for the quick confirmation. Please note that there is nothing we can do in that case, it's not strictly related to that code being in the parent as I've explained above.
