### ISSUE TITLE
Error Hibernate-Core: InvalidDataAccessApiUsageException (Parameter value)

### ISSUE THREAD

**Issue by diegoporfirio** [spring-projects/spring-boot#30563] opened 2022-04-06 16:36 UTC
Hi, 

Spring boot 2.6.5 and 2.6.6 cause error in hibernate-core:

`org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [\] did not match expected type [com.domain.User (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [\] did not match expected type [com.domain.User (n/a)]`

If in Spring boot 2.6.6 set version hibernate-core 5.6.5 in pom.xml 

           
		<dependency>
		    <groupId>org.hibernate</groupId>
		    <artifactId>hibernate-core</artifactId>
		    <version>5.6.5.Final</version>
		</dependency>

The error does not appear. The problem is in the 5.6.6.Final and 5.6.7.Final

**Comment by scottfrederick** [comment] 2022-04-06 16:39
Duplicate of #30421

**Closed** 2022-04-06 17:36 UTC
Labels: status: duplicate, for: external-project
