### ISSUE TITLE
Default value for configuration property 'spring.mvc.pathmatch.matching-strategy' is not up to date in the reference documentation v2.6

### ISSUE THREAD

**Issue by ghusta** [spring-projects/spring-boot#29091] opened 2021-12-16 21:33 UTC
The default value for `spring.mvc.pathmatch.matching-strategy` should be `path-pattern-parser` since Spring Boot 2.6 (see [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#pathpattern-based-path-matching-strategy-for-spring-mvc)), but it's still the old value (`ant-path-matcher`) in the reference documentation.

It is incorrect in this document : https://docs.spring.io/spring-boot/docs/2.6.x/reference/html/application-properties.html#application-properties.web.spring.mvc.pathmatch.matching-strategy

However in the metadata file, the default value is correct (https://github.com/spring-projects/spring-boot/blob/2.6.x/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L1634).

**Comment by scottfrederick** [comment] 2021-12-16 21:43
Thanks for the report. This is a duplicate of #28936.

**Closed by scottfrederick** 2021-12-16 21:43 UTC
Labels: status: waiting-for-triage

**Comment by ghusta** [comment] 2021-12-17 09:23
Oh sorry !
