### ISSUE TITLE
defaultValidator could not be found when upgrading from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by illingtonFlex** [spring-projects/spring-boot#13233] opened 2018-05-22 19:39 UTC
My application will start up correctly when using Spring Boot 2.0.0, but will not start when using 2.0.1.

The error message is as below:

> Parameter 0 of method setValidator in my.company.util.SvcController required a bean of type 'javax.validation.Validator' that could not be found.
        - Bean method 'defaultValidator' not loaded because @ConditionalOnResource did not find resource 'classpath:META-INF/services/javax.validation.spi.ValidationProvider'

I have the following in the SvcController class:

```
    @Autowired
    public void setValidator(Validator validator) {
        this.validator = validator;
    }

    protected Validator getValidator() {
        return this.validator;
    }
```
I can break and fix this app by switching Spring-Boot versions back and forth. 

One interesting thing I notice is when I unzip -l the contents of the executable Jar file, and grep for "alid", I see this with the 2.0.1 version:

>      594  05-22-2018 14:11   BOOT-INF/lib/spring-boot-starter-validation-2.0.1.RELEASE.jar
>      1800  05-22-2018 14:11   BOOT-INF/lib/hibernate-validator-6.0.9.Final.jar
>      1130724  05-22-2018 14:11   BOOT-INF/lib/hibernate-validator-6.0.9.Final.jar
>      93107  05-22-2018 14:11   BOOT-INF/lib/validation-api-2.0.1.Final.jar

That's two apparently identical entries for hibernate-validator-6.0.9.Final.jar.

When I do the same thing with the 2.0.0 version of the jar, I see this:

>      594  05-22-2018 14:28   BOOT-INF/lib/spring-boot-starter-validation-2.0.0.RELEASE.jar
>      1800  05-22-2018 14:28   BOOT-INF/lib/hibernate-validator-6.0.9.Final.jar
>      1117582  05-22-2018 14:28   BOOT-INF/lib/hibernate-validator-6.0.7.Final.jar
>      93107  05-22-2018 14:28   BOOT-INF/lib/validation-api-2.0.1.Final.jar

So that one apparently contains 6.0.9.Final and 6.0.7.Final.

Also, apparently the app is working with Spring-Boot 2.0.2, but I don't think I can use that yet because I'm using Spring-Cloud Finchley, which is at the moment intended for 2.0.1.

**Comment by snicoll** [comment] 2018-05-23 07:51
I am guessing you are using Gradle. Can you please paste a simple project that reproduces the problem you are experiencing?

**Comment by spring-issuemaster** [comment] 2018-05-30 07:54
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-06-06 07:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-06-06 07:55 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
