### ISSUE TITLE
Duplicate property values in Spring Actuator /env endpoint

### ISSUE THREAD

**Issue by aritzbastida** [spring-projects/spring-boot#10883] opened 2017-11-02 10:59 UTC
Hello, 

I think there is a bug in Spring Boot Actuator 1.5.8 /env endpoint. This endpoint shows all the property sources in precedence order, listing the available properties in each. 

However, when the same property key is available in several property sources, the value shown is always the one with highest priority, showing an incorrect value in lower precedence property sources. This can be quite confusing, as shown next:

```
applicationConfig: [classpath:/config/application.yml]: {
   global.t3.environment: "APPLICATION-DEV",
},
applicationConfig: [classpath:/config/bootstrap-dev.yml]: {
   global.t3.environment: "APPLICATION-DEV"
},
applicationConfig: [classpath:/config/bootstrap.yml]: {
   global.t3.environment: "APPLICATION-DEV"
},
```

Thank you and regards,
Aritz

**Comment by dsyer** [comment] 2017-11-02 15:02
Actually, the endpoint does not show the property sources in precedence order (it used to by Jackson changed their serialization a while ago, so there is no order any more). But the other thing is probably a bug (duplicate values) - it's easy to see where it comes from.

**Comment by wilkinsona** [comment] 2017-11-03 12:51
AFAIK, the map is populated in precedence order (and it's a linked hash map so the order is preserved on the server side). The problem is that there's no guarantee that the client will preserve that order. This is one of the problems with the endpoint that we've fixed in 2.0 by using a list for the property sources so that the ordering is preserved.

**Comment by dsyer** [comment] 2017-11-03 13:55
> there's no guarantee that the client will preserve that order

It's worse than that. It is actually serialized unordered in the server. I don't think there's anything we can do about it if we only support producing JSON (JSON is unordered according to the spec)..

**Comment by wilkinsona** [comment] 2017-11-03 14:37
> I don't think there's anything we can do about it if we only support producing JSON (JSON is unordered according to the spec)..

In 2.0 we use an array as, [per the spec](https://tools.ietf.org/html/rfc7159#section-1), an array is ordered:

> An array is an ordered sequence of zero or more values.

**Closed** 2017-11-23 13:15 UTC
Labels: priority: normal, type: bug
