### ISSUE TITLE
NPE when using NarayanaDataSourceBean

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-boot#7152] opened 2016-10-12 09:30 UTC
NarayanaDataSourceBean can cause a NPE in the underlying ConnectionManager.
Typically user/pw is configured on the underlying proper real-life datasource which NDSB is wrapping, and not on the calling software (for instance the dao etc), and hence user/pw is not availble for narayana, which uses this to do some comparison checks etc.

The other way to go about it is to be able to influence the pooling (e.g. turn it off, and rely on the underlying datasource capabilities for pooling) - if pooling is turned off it will never enter the block where the equals checks are done (in Narayana):

```
if(tx1 != null && tx1.equals(tx2) && connControl.url().equals(dbUrl) && connControl.user().equals(user) && connControl.password().equals(passwd) && connControl.dynamicClass().equals(dynamic)) 
```

This is preferrable since the pooling capabilities of Narayana are not good compared to functionality in for instance the Oracle datasource itself. (set max, min, idle timeouts etc)

Spring-boot version: 1.4.1

Stack trace:

```
11:18:06 Caused by: java.lang.NullPointerException: null
11:18:06    at com.arjuna.ats.internal.jdbc.ConnectionManager.create(ConnectionManager.java:91)
11:18:06    at org.springframework.boot.jta.narayana.NarayanaDataSourceBean.getConnection(NarayanaDataSourceBean.java:59)
11:18:06    at org.springframework.jdbc.datasource.DelegatingDataSource.getConnection(DelegatingDataSource.java:86)
```

Code:

``` java
  @Override
        public Connection getConnection() throws SQLException { //this method should be able to set a username/pw, like the other one, preferrably by having user/pw properties on the bean
                Properties properties = new Properties(); 
                properties.put(TransactionalDriver.XADataSource, this.xaDataSource);
                return ConnectionManager.create(null, properties);
        }

        @Override
        public Connection getConnection(String username, String password)
                        throws SQLException {
                Properties properties = new Properties();
                properties.put(TransactionalDriver.XADataSource, this.xaDataSource);
                properties.put(TransactionalDriver.userName, username);
                properties.put(TransactionalDriver.password, password);
                return ConnectionManager.create(null, properties);
        }

```

**Comment by snicoll** [comment] 2017-01-09 22:07
I think I got your analysis but I am a bit surprised by the side effect here. Can you please share a sample that reproduces the issue?

**Comment by davidkarlsen** [comment] 2017-01-09 23:54
The posted code should be enough to be able to reproduce.

**Comment by snicoll** [comment] 2017-01-10 02:14
What posted code? I am not following.

**Comment by davidkarlsen** [comment] 2017-01-10 20:09
@snicoll The code fragments reported in the issue...

**Comment by wilkinsona** [comment] 2017-01-10 20:27
@davidkarlsen Thanks, but the code fragments above are just a copy of something from Boot aren't they? They don't really tell us what we need to run to reproduce the problem.

Above, you said that "NarayanaDataSourceBean can cause a NPE in the underlying ConnectionManager". We're looking for a sample that reproduces the NPE.

**Comment by spring-issuemaster** [comment] 2017-01-17 20:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-01-24 20:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-01-24 20:31 UTC
Labels: status: waiting-for-triage
