### ISSUE TITLE
Bug : CSS Related issue in Documentation

### ISSUE THREAD

**Issue by AlFahimBinFaruk** [spring-projects/spring-boot#39411] opened 2024-02-06 05:45 UTC
### Issue
In the documentation the content section is always scrollable. I think this is annoying to the readers.

### Solution
However if we add : 

```css
.doc #content {
    margin: 0 2rem;
    padding: 0 1rem;
}
body.toc-left #doc {
    overflow: visible;
}
```
this will resolve the issue for desktop-mode and will add more to the user experience.
### Before
![Screenshot from 2024-02-06 14-07-18](https://github.com/spring-projects/spring-boot/assets/85015121/db40dff3-8964-4f01-a090-21d395c5cdc0)

### After
![Screenshot from 2024-02-06 14-09-31](https://github.com/spring-projects/spring-boot/assets/85015121/9d6946d0-31e6-47b4-b1d8-6d7f9ee1593f)

In here you can see that the sections are much more readable after adding the following css.

* I am using Ubuntu 22 as my OS and Chrome as my browser.

**Comment by philwebb** [comment] 2024-02-06 05:59
Could you please provide some before/after screenshots to show what you mean? What operating system and browser are you using?

**Comment by AlFahimBinFaruk** [comment] 2024-02-06 08:13
> Could you please provide some before/after screenshots to show what you mean? What operating system and browser are you using?

I have updated the issue..

**Comment by wilkinsona** [comment] 2024-02-06 10:39
Thanks. The only difference that I can see is in the wrapping of the text. For example, in section 7.1 in the before image "in many situations" is split over two lines and where it wraps onto the second line the "y" in "many" is hidden and the n is only partially visible. In the after image, all letters are visible. Is this the problem that you're referring to? Interestingly, it does not occur for me in Chrome on macOS.

**Comment by AlFahimBinFaruk** [comment] 2024-02-07 05:00
> Thanks. The only difference that I can see is in the wrapping of the text. For example, in section 7.1 in the before image "in many situations" is split over two lines and where it wraps onto the second line the "y" in "many" is hidden and the n is only partially visible. In the after image, all letters are visible. Is this the problem that you're referring to? Interestingly, it does not occur for me in Chrome on macOS.

Yes. That's the problem i am referring to. Most of the section with long description have the issue where some letters are hidden.
And i have also tried zooming in out the screen the issue remains the same..

**Comment by wilkinsona** [comment] 2024-02-09 10:41
@mhalbritter @scottfrederick do you see this on Linux?

**Comment by mhalbritter** [comment] 2024-02-09 10:49
Nope.

![image](https://github.com/spring-projects/spring-boot/assets/98899556/8b506c56-6939-4df7-8d91-45d28bdbfc0a)

Fedora 39, Chrome `Version 121.0.6167.160 (Official Build) (64-bit)`.

**Comment by scottfrederick** [comment] 2024-02-09 13:53
Mine looks like Moritz's on Ubuntu and Chrome. It responds appropriately to changes in window size also.

**Comment by wilkinsona** [comment] 2024-02-09 14:51
Thanks, both.

Looking more closely at this, even if we could reproduce it, I don't think padding the content is a good idea. Given that there's already a left and right margin of 2rem, adding padding of 1rem introduces unwanted extra whitespace. Furthermore, it leaves the content out of line with the heading at the top of each page.

@AlFahimBinFaruk I'm going to close this one as we cannot reproduce it and, unless we can do so, it won't be possible to figure out the right fix for it. If you can narrow down the problem and identify the circumstances that we'd need to reproduce the problem, please open an issue https://github.com/spring-io/spring-asciidoctor-backends where the CSS is maintained and we can take another look.

**Closed by wilkinsona** 2024-02-09 14:51 UTC
Labels: status: waiting-for-triage
