### ISSUE TITLE
PropertiesLauncher loader.path - Strange classloading issue

### ISSUE THREAD

**Issue by tenstriker** [spring-projects/spring-boot#5086] opened 2016-02-03 20:27 UTC
Hi, I have a spring boot application that loads external jars during class loading via loader.path. Yes I do use `ZIP` layout in maven plugin configuration.
Here's snippet from my MANIFEST

```
Start-Class: com.myapp.Application
Build-Revision-Number: 19ffdcb2ee38050c3a5fXX0c71e876078a
Created-By: Apache Maven 3.2.5
Spring-Boot-Version: 1.3.2.RELEASE
Main-Class: org.springframework.boot.loader.PropertiesLauncher
```

I have two versions of certain external jar both of which contains a class that I am looking for. However, one version keeps throwing ClassNotFoundError

Here's the one that works:

```
java -Dloader.path=target/myapp.jar,/opt/spark/spark-1.3.1/lib -XX:PermSize=512m -XX:MaxPermSize=512m -Xms2048m -Xmx4096m -Dspring.profiles.active=dev -Dlogging.config=file:logback.xml -jar target/myapp.jar
```

This one throws error:

```
java -Dloader.path=target/myapp.jar,/opt/spark/spark-1.5.2/lib -XX:PermSize=512m -XX:MaxPermSize=512m -Xms2048m -Xmx4096m -Dspring.profiles.active=dev -Dlogging.config=file:logback.xml -jar target/myapp.jar
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/api/java/JavaSparkContext
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
	at java.lang.Class.getDeclaredMethod(Class.java:2002)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.api.java.JavaSparkContext
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 5 more
```

As I said both jar contains the class. However they are built with different JVM. spark-1.3.1/lib jars are all built with `1.6.0_45` and spark-1.5.2/lib jars are built with `1.7.0_80`. And my local java version is `1.7.0_51`

**Comment by wilkinsona** [comment] 2016-02-05 15:44
I would guess that one of the jars in `/opt/spark/spark-1.5.2/lib` is corrupted. Have you verified that a normal non-Boot application can load `org.apache.spark.api.java.JavaSparkContext` from the Spark 1.5.2 jars?

**Comment by tenstriker** [comment] 2016-02-05 18:58
Yes, I could load it in normal eclipse java project. I added all the jars from `/opt/spark/spark-1.5.2/lib` on classpath and just tried to instantiate JavaSparkContext which worked.

**Comment by wilkinsona** [comment] 2016-02-05 19:37
Sorry, that was the best guess that I had, and you haven't supplied enough information for anything more than educated guesses. If you'd like us to investigate further, please provide a small sample that reproduces the problem.

**Comment by tenstriker** [comment] 2016-02-05 20:47
ok give me some time to compose a small maven spring-boot project and to attach spark lib folder

**Comment by tenstriker** [comment] 2016-02-09 01:46
Some updates while I was trying to setup new spring-boot maven project. With spark1.3.1 libs it does work but with spark 1.5.2 I see following trace from verbose output. But it doesn't say which jar causing it. Also is there a program to validate jars? I tried extracting them all using ZipEntry in another sample project and that worked.

[Loaded org.springframework.boot.loader.jar.JarEntryData from jar:file:/Users/npatel/ws/springbootloader/target/springbootloader-0.0.1-SNAPSHOT.jar!/]
[Loaded org.springframework.boot.loader.jar.JarFile$1 from jar:file:/Users/npatel/ws/springbootloader/target/springbootloader-0.0.1-SNAPSHOT.jar!/]
2016-02-08 17:40:40.368 ERROR 40809 --- [cat-startStop-1] org.apache.catalina.core.ContainerBase   : A child container failed during start

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	... 6 common frames omitted
**Caused by: java.lang.IllegalArgumentException: invalid compression method**
	at java.util.zip.ZipEntry.setMethod(ZipEntry.java:203)
	at org.springframework.boot.loader.jar.JarEntryData.asJarEntry(JarEntryData.java:126)
	at org.springframework.boot.loader.jar.JarFile$1.nextElement(JarFile.java:236)
	at org.springframework.boot.loader.jar.JarFile$1.nextElement(JarFile.java:227)
	at org.apache.tomcat.util.scan.JarFileUrlJar.nextEntry(JarFileUrlJar.java:122)
	at org.apache.jasper.servlet.TldScanner$TldScannerCallback.scan(TldScanner.java:303)
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:306)
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:244)
	at org.apache.jasper.servlet.TldScanner.scanJars(TldScanner.java:262)
	at org.apache.jasper.servlet.TldScanner.scan(TldScanner.java:106)
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:103)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5156)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 common frames omitted

2016-02-08 17:40:40.369 ERROR 40809 --- [           main] org.apache.catalina.core.ContainerBase   : A child container failed during start

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:439)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:769)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:337)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:88)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:75)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:378)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:155)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:157)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:687)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:967)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:956)
	at org.myapp.springbootloader.Application.main(Application.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	... 1 common frames omitted
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:924)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 common frames omitted

**Comment by tenstriker** [comment] 2016-02-09 01:56
Actually it's not clear if its a Jar issue. It may be related to this.
https://issues.apache.org/jira/browse/TIKA-346

[springbootloader.tar.gz](https://github.com/spring-projects/spring-boot/files/122485/springbootloader.tar.gz)

Spark 1.5.2 lib is too big to attach here. I can share via dropbox if you need them or you can get it via installing rpm from http://package.mapr.com/releases/ecosystem-4.x/redhat/

**Comment by tenstriker** [comment] 2016-02-09 02:08
I tried upgrading spring-boot version from 1.2.6 to 1.3.2. Now I'm seeing following.

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:191)
	at org.myapp.springbootloader.Application.main(Application.java:21)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 8 more
Caused by: java.util.zip.ZipException: invalid stored block lengths
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:444)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	... 15 more

**Comment by wilkinsona** [comment] 2016-02-09 10:11
Thanks for the information.

Two of the zip files in the Spark rpm appear to be faulty:

```
$ unzip -l spark-assembly-1.5.2-mapr-1512-hadoop2.7.0-mapr-1509.jar
…
error:  expected central file header signature not found (file #96120).
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

```
$ unzip -l spark-examples-1.5.2-mapr-1512-hadoop2.7.0-mapr-1509.jar
…
error:  expected central file header signature not found (file #67549).
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

There's some discussion of this problem in [SPARK-1520](https://issues.apache.org/jira/browse/SPARK-1520). That issue also suggests that the jars are in Zip64 format. Spring Boot doesn't support Zip64 at the moment. See #2895.

I'm going to close this one as it's either a problem with Spark (the broken zip files) or a duplicate of #2895.

**Closed by wilkinsona** 2016-02-09 10:11 UTC
Labels: feedback-provided

**Comment by tenstriker** [comment] 2016-02-09 16:17
Thank you. We use JRE 1.7 and Jar is also built with 1.7 but I will more look into it. Meanwhile is there a timeline to support Zip64 in springboot loader because nesting so many jars may not be an option for us. It's a spark/hadoop heavy project return both in java and scala.
