### ISSUE TITLE
build-info doesn't support seconds since the epoch from project.build.outputTimestamp

### ISSUE THREAD

**Issue by ahoehma** [spring-projects/spring-boot#42871] opened 2024-10-24 09:41 UTC
I'm trying to enable https://maven.apache.org/guides/mini/guide-reproducible-builds.html for my springboot project.

I'm using maven-git-version-extension. And found that springboot can't handle seconds,

```
Caused by: java.time.format.DateTimeParseException: Text '1729757074' could not be parsed at index 0
    at java.time.format.DateTimeFormatter.parseResolved0 (DateTimeFormatter.java:2052)
    at java.time.format.DateTimeFormatter.parse (DateTimeFormatter.java:1954)
    at java.time.Instant.parse (Instant.java:397)
    at org.springframework.boot.maven.BuildInfoMojo.getBuildTime (BuildInfoMojo.java:157)
    at org.springframework.boot.maven.BuildInfoMojo.getProjectDetails (BuildInfoMojo.java:131)
    at org.springframework.boot.maven.BuildInfoMojo.execute (BuildInfoMojo.java:114)
```

See for details https://github.com/qoomon/maven-git-versioning-extension/issues/340.

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/BuildInfoMojo.java#L149

A alternative round of parsing for the epoch seconds would be an improvement.

**Comment by wilkinsona** [comment] 2024-10-24 10:04
We [document `time`](https://docs.spring.io/spring-boot/maven-plugin/build-info.html#build-info.build-info-goal.parameter-details.time) as "the value used for the build.time property in a form suitable for Instant#parse(CharSequence)" so, on the one hand this is working as designed. On the other hand, we [document](https://docs.spring.io/spring-boot/maven-plugin/build-info.html#build-info.build-info-goal.optional-parameters) that it defaults to `${project.build.outputTimestamp}` and the [spec](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318#Reproducible/VerifiableBuilds-OutputArchiveEntriesTimestamp) isn't clear that ISO-8601 is the only valid format as it says "with an ISO 8601 formatted date+time" in one place but also shows an example that supports both ISO 8601 and seconds since the epoch. On balance, I think it's worth us adding a fallback to try seconds since the epoch if parsing as ISO 8601 fails.

**Comment by ahoehma** [comment] 2024-10-24 10:08
I would like to provide a fix for this? If this is okay for you? I already forked springboot.

**Comment by ahoehma** [comment] 2024-10-28 13:41
@wilkinsona does it make sense to reuse org.springframework.boot.maven.MavenBuildOutputTimestamp inside org.springframework.boot.maven.BuildInfoMojo? Because then the support for epoch seconds will be automatically :)

**Comment by philwebb** [comment] 2024-10-28 15:26
@ahoehma We could try that approach if there's reusable code. We might need to rename that class, but it's package private so that's not a problem. We can take care of that part later if necessary.

**Comment by ahoehma** [comment] 2024-10-28 16:56
@philwebb exactly :-) From my point of view the MavenBuildOutputTimestamp have already a good name.

**Comment by ahoehma** [comment] 2024-10-29 08:22
I need some more help ... not for the fix itself ... but for the eclipse / gradle setup :-)

I followed the eclipse installation steps ... and for the first time everything worked fine. I had all the spring boot projects up and running (no  problems) in a brand new eclipse installation (I' using 2024-09 instead of 2021-03 which is the current suggested version in https://github.com/spring-projects/spring-boot/wiki/Working-with-the-Code#importing-into-eclipse).

But today ... all the projects are red and have thousands of compiler errors and I don't know why.

Gradle output looks fine to me:

```
Working Directory: D:\Dev\git\privat\spring-boot
Gradle user home: D:\Dev\gradle_stuff
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 8.10.2
Java Home: D:\Dev\Java\jdk-17.0.4
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :spring-boot-system-tests:spring-boot-deployment-tests:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-static:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-jetty-jsp:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-traditional:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-jsp:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-servlet:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-tomcat-jsp:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-war:cleanEclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-servlet:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-jetty-jsp:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-war:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-tomcat-jsp:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-traditional:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-tomcat-jsp:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-static:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-servlet:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-static:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-system-tests:spring-boot-deployment-tests:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-jsp:cleanEclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-traditional:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-jetty-jsp:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-system-tests:spring-boot-deployment-tests:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-jsp:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-war:cleanEclipseWtp UP-TO-DATE
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-servlet:eclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-tomcat-jsp:eclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-static:eclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-war:eclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-jetty-jsp:eclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-jsp:eclipseWtpComponent
> Task :spring-boot-system-tests:spring-boot-deployment-tests:eclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-static:eclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-static:eclipseWtp
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-war:eclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-servlet:eclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-jetty-jsp:eclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-servlet:eclipseWtp
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-jetty-jsp:eclipseWtp
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-war:eclipseWtp
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-jsp:eclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-web-jsp:eclipseWtp
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-tomcat-jsp:eclipseWtpFacet
> Task :spring-boot-system-tests:spring-boot-deployment-tests:eclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-tomcat-jsp:eclipseWtp
> Task :spring-boot-system-tests:spring-boot-deployment-tests:eclipseWtp
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-traditional:eclipseWtpComponent
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-traditional:eclipseWtpFacet
> Task :spring-boot-tests:spring-boot-smoke-tests:spring-boot-smoke-test-traditional:eclipseWtp

BUILD SUCCESSFUL in 17s
44 actionable tasks: 32 executed, 12 up-to-date
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE

CONFIGURE SUCCESSFUL in 41s
4 actionable tasks: 4 up-to-date
```

![image](https://github.com/user-attachments/assets/93581fe7-a0c4-442f-9fe3-6901343cbdc4)

Is there anything I missed?

**Comment by wilkinsona** [comment] 2024-10-29 08:59
Sorry for the trouble with Eclipse. The `buildSrc` thing is due to JPMS, split packages, and how Buildship configures the problem on import. See https://github.com/spring-projects/spring-boot/issues/41285 for a manual fix that we hope to make automatic.

**Comment by wilkinsona** [comment] 2024-10-29 15:08
Closing in favor of #42922. Thanks for the PR, @ahoehma.

**Closed by wilkinsona** 2024-10-29 15:08 UTC
Labels: type: bug
