### ISSUE TITLE
HazelcastAutoConfiguration conflict with @EnableCaching

### ISSUE THREAD

**Issue by neilstevenson** [spring-projects/spring-boot#8275] opened 2017-02-13 10:02 UTC
See http://stackoverflow.com/questions/42151600/hazelcast-and-jcache-in-spring-boot-creates-two-instances?noredirect=1#comment71527698_42151600

If `@EnableCaching` is used with Hazelcast as the caching provider, a Hazelcast instance is created. Spring Boot's `HazelcastAutoConfiguration` should not then create another.

Possible fix might be to test for a `JCacheCacheManager` bean being a Hazelcast instance.

Example code to reproduce, https://github.com/hazelcast/hazelcast-code-samples/tree/stackoverflow42151600/hazelcast-integration/springboot-caching-jcache and run the `startBootifulMember.sh` script.

**Comment by snicoll** [comment] 2017-02-13 11:02
There is no way for us to know. One one hand, `Hazelcast` is configured (plain hazelcast that is) and after that a `JCache` provider is required. How would be able to bind the standard JCache bootstrap with the fact an existing hazelcast instance is available?

**Comment by spring-issuemaster** [comment] 2017-02-20 11:06
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by dirkvanrensburg** [comment] 2017-02-21 01:56
I found that if I disable the `HazelcastAutoConfiguration` then one one Hazelcast instance is created and caching works as expected BUT the instance cannot be injected directly. Attempting to autowire `HazelcastInstance` results in the application context complaining that there is no such bean to inject. This leads me to think that the instance created by the caching layer is not registered with the application context.

In other words, I think that if the original instance created during the cache setup is registered with the application context then the `HazelcastAutoConfiguration` will be disabled due to the `@ConditionalOnMissingBean` and not ask Hazelcast for another instance.

To work around this issue I explicitly look up the instance using Hazelcast's factory. The `HazelcastAutoconfiguration` is disabled and the application context becomes aware of the injectable instance. 

    @Bean
    public HazelcastInstance getInstance() {
        return Hazelcast.getHazelcastInstanceByName("name-as-in-hazelcast-config");
    }

**Comment by snicoll** [comment] 2017-02-21 08:52
As I've told you on Twitter, you can't expect to wire an `HazelcastInstance` when you are configuring a `JCache`cache manager. The bootstrap phase and what happens behinds the scenes is entirely internal to the cache library implementation. I also think that is wrong: if you want to use JCache, you shouldn't tie your code to an `HazelcastInstance`, it sounds like the wrong level of abstraction to me.

If you want to use the standard `JCache` annotation, I remind you you can do so, even with a plain `Hazelcast` cache manager. 

I don't like that this issue is turning into a stackoverflow thread but I have to ask: why are you using JCache if you want to access the `HazelcastInstance`? If you don't do anything with your setup (no cache property I mean), the existing `HAzelcastInstance` is going to be found by the auto-config and we'll use that transparently. What's the drawback with that?

**Comment by dirkvanrensburg** [comment] 2017-02-21 10:11
Thanks @snicoll for replying both here and on Twitter. I get what you are saying: The cache abstraction should not be aware of the idiosyncrasies of the implementation and I agree it would great if Hazelcast could just realise that there is another instance with the same name and config and then not create a new one.

It really wasn't my intention to turn this into a stackoverflow thread. I commented here after you mentioned the issue to me on Twitter and before you replied the second time. I am happy with naming the `HazelcastInstance` and telling the application context about it.

To answer your question about using `JCache` annotations and accessing the `HazelcastInstance`. Hazelcast is not a pure cache like ehcache, but an in memory data grid so there are lots of other things you can do with it. In my case I want to use it as a cache to for responses for calls to my API, but internally I want to use the distributed grid to store data in memory and share it between the various instances of a particular micro-service.

**Comment by snicoll** [comment] 2017-02-21 10:15
@dirkvanrensburg can you please join gitter and mention me because Spring Boot supports all that but async communication doesn't seem to work. I know what Hazelcast is. In the meantime I am closing this one as invalid and will chat with the Hazelcast team to see if that can be improved.

**Comment by snicoll** [comment] 2017-02-21 10:55
I was finally able to get around this one with a sample I built to show what I mean to Dirk and it turns out something isn't right.

**Comment by snicoll** [comment] 2017-02-21 12:18
Sorry for the back and forth. [This sample](https://github.com/snicoll-scratches/test-hazelcast-jcache) summarizes the issue and shows how you can easily have a working a solution. @neilstevenson I think the problem is in Hazelcast (or you need to tell us what we are doing wrong). I've created [this issue](https://github.com/hazelcast/hazelcast/issues/9958) to discuss that with you and the rest of the Hazelcast team

**Comment by snicoll** [comment] 2017-03-01 17:28
okay, I got some interesting ideas in that related issue and I believe I should be able to make things work.

**Comment by snicoll** [comment] 2017-03-02 13:21
@neilstevenson I am not going to fix your sample. As far as I can see there is zero instructions there so you're relying on the default detection (`hazelcast.xml` at the root of the classpath). As described in https://github.com/hazelcast/hazelcast/issues/9958#issuecomment-282999078, I understand that #9973 shows a current limitation that Hazelcast doesn't realize that the URI is the same and therefore it should not create another instance.

I am, however, going to create a way for the user to pass the instance to use via a dedicated property. It's a shame that you can't detect the URI because that's pretty much the only standard way and I really don't want to start dealing with Hazelcast classes in the JCache auto-configuration.

**Comment by snicoll** [comment] 2017-03-02 14:06
Looking at the sample @dirkvanrensburg has provided, I can see what the original problem is (see #8467) for a better description. If the instance name is set we will reconciliate the two instance and the fact you don't get that from the URI is a limitation in Hazelcast. So I am going to close this issue again. The issue Dirk has is real but I don't think your sample is legit, given the current limitation in Hazelcast. Let me know if I've missed anything.

**Closed by snicoll** 2017-03-02 14:06 UTC
Labels: type: enhancement

**Comment by andreacomo** [comment] 2017-03-27 19:30
Just my two cents: adding `<instance-name>` in `hazelcast.xml` and `spring.hazelcast.config` in `application.yml` worked for me (Spring Boot 1.4.1.RELEASE, Hazelcast 3.8)

**Comment by snicoll** [comment] 2017-03-28 05:26
@andreacomo what was fixed here is the (indirect) link between an existing `HazelcastInstance` and the JCache bootstrap. If you're having a default `hazelcast.xml`, you don't need the property at all.

**Comment by andreacomo** [comment] 2017-03-28 06:43
@snicoll I have a custom hazelcast config file: without Spring property, Hazelcast try to create a new instance. Thanks to this conversation I've found a way out.

**Comment by snicoll** [comment] 2017-03-28 06:50
That does not sound right. If you have a sample to share please report a new issue.

**Comment by andreacomo** [comment] 2017-03-28 20:30
I don't know if it's an issue or a configuration matter. I just created a new repo, if you want to have a look, reproducing this behavior (I tagged significant commits). 
https://github.com/coding-jam/spring-hazelcast-jcache-poc

**Comment by snicoll** [comment] 2017-03-29 07:16
@andreacomo  you are using jcache so that issue exactly fixed what you reported.

**Comment by asarkar** [comment] 2017-06-02 06:41
@snicoll I understand this ticket is closed, but using Hazelcast 3.8.2 with JCache, which https://github.com/hazelcast/hazelcast/pull/9973 was supposedly backported to, 2 instances are created. The test that you provided in that ticket fails. I've attached a Gradle project to demonstrate the issue with 2 test classes.
[demo.zip](https://github.com/spring-projects/spring-boot/files/1046878/demo.zip)

**Comment by snicoll** [comment] 2017-06-02 07:35
> I understand this ticket is closed

@asarkar if you do please do not comment on it. If you believe you've found an issue and you have a sample to prove it, open a new issue with the reference to it.

Thanks for building a sample. Unfortunately the error is in your own code: you are creating a `CacheManager` yourself in `DemoApplication`. By doing so you are completely by-passing the mechanism that Spring Boot applies to ensure that only one instance is created. As soon as a comment out the `@Bean` definition the test pass.

You yaml is wrong as well, only this is necessary:

```yaml
spring:
  hazelcast:
    config: classpath:/hazelcast-demo.xml
```

(You can of course be explicit about the type of cache provider you want but passing the same config file as the hazelcast config is asking for trouble, really. If you are asking us to initialize Hazelcast via `spring.hazelcast.config` there is no need to tell us to init jcache with a dedicated config file. The whole purpose of this issue is that we're smart enough to figure out that there is an `HazelcastInstance` around and to reuse that).

If you have more questions, please use stackoverflow or gitter.

**Comment by asarkar** [comment] 2017-06-02 07:59
@snicoll Thanks for the response. The reason I didn't open a new ticket was to avoid the quintessential "duplicate" and closure. I've yet to do some research on this matter; if I don't find the answers I'm looking for, I'll use Stackoverflow, or open a question in this project (seems to be preferred over SO in some other Spring projects).

**Comment by snicoll** [comment] 2017-06-02 08:04
> If you have more questions, please use stackoverflow or gitter.

@asarkar we don't use the tracker for questions which explains why we'd like to avoid noise on closed issues as well.
