### ISSUE TITLE
actuator returns 200 even if there are DOWN healthchecks if it runs on different port

### ISSUE THREAD

**Issue by nkonev** [spring-projects/spring-boot#11462] opened 2018-01-01 20:56 UTC
I provided [demo project](https://github.com/nkonev/demo-fail-actuator) with spring-boot-starter-mail.
There are incorrect email login and password.

If I run project without change management port - all ok
```
curl -v http://127.0.0.1:8080/actuator/health
```
responds 50x

But if I set
```
management:
  server:
    port: 3010
```
```
curl -v http://127.0.0.1:3010/actuator/health
```
Responds 200. 

I expect 50x

**Comment by snicoll** [comment] 2018-01-02 07:36
Duplicate of #11285

**Closed by snicoll** 2018-01-02 07:36 UTC
Labels: status: waiting-for-triage
