### ISSUE TITLE
Maven plugin barfs if you ask it for help

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#21715] opened 2020-06-05 09:34 UTC
```
$ ./mvnw spring-boot:help
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.206 s
[INFO] Finished at: 2020-06-05T09:30:54Z
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "ide" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.3.0.BUILD-SNAPSHOT:help (default-cli) on project demo: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.3.0.BUILD-SNAPSHOT:help failed: Unable to load the mojo 'help' in the plugin 'org.springframework.boot:spring-boot-maven-plugin:2.3.0.BUILD-SNAPSHOT'. A required class is missing: org.springframework.boot.maven.HelpMojo
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.springframework.boot:spring-boot-maven-plugin:2.3.0.BUILD-SNAPSHOT
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/dsyer/.m2/repository/org/springframework/boot/spring-boot-maven-plugin/2.3.0.BUILD-SNAPSHOT/spring-boot-maven-plugin-2.3.0.BUILD-SNAPSHOT.jar
...
```

Probably an issue with the way the Maven artifacts are synthesized from the gradle build (I never saw this with a Maven plugin built with Maven)?

**Comment by snicoll** [comment] 2020-06-05 09:35
Duplicate of #21556

**Closed by snicoll** 2020-06-05 09:35 UTC
