### ISSUE TITLE
Fix typo in import - plexus-util

### ISSUE THREAD

**Issue by slachiewicz** [spring-projects/spring-boot#11188] opened 2017-11-28 20:56 UTC
Fix typo in AbstractEmbeddedServletContainerIntegrationTests import of org.codehaus.plexus.util.StringUtils -> should be org.springframework.util.StringUtils

**Comment by snicoll** [comment] 2017-11-28 21:02
@slachiewicz thanks. FYI there is no need to open an issue and a PR. A PR is enough.

**Comment by snicoll** [comment] 2017-11-28 21:02
Duplicate of #11189

**Closed by snicoll** 2017-11-28 21:02 UTC
Labels: status: waiting-for-triage
