### ISSUE TITLE
 Webflux application hanging with "Mixed pooled connection operations between..."

### ISSUE THREAD

**Issue by martin-drozdik** [spring-projects/spring-boot#11467] opened 2018-01-02 11:32 UTC
I encountered a problem when using the WebClient (which is a part of the reactive Webflux component) to communicate with a WebFlux server. 

### Spring Boot Version

The problem is present in **2.0.0.M6** and in **2.0.0.M7**, but *not* in **2.0.0.M5**.

### Steps to reproduce

I made a project containing a minimal working example:

https://github.com/martin-drozdik/netty-bug

  **1. Start the ServerApplication.**

This is nothing but a simple CRUD (without the UD) application, where users authenticate themselves using basic auth and their passwords are encoded with BCrypt. I tried to remove this functionality since it should be a MWE after all, but as it turns out, the problem goes away for unsecured applications. 

  **2. Start the ClientApplication**

After the application has started, you should start the ClientApplication. This uses the netty-based WebClient to query the API provided by ServerApplication, alternating between two valid user credentials (The application takes longer to halt with only one user). 

  **3. Wait about 30 seconds.**

ServerApplication will hang and its last words will be:

```
2017-12-27 16:56:29.995 DEBUG 10410 --- [ctor-http-nio-2] r.i.n.http.server.HttpServerOperations   : Increasing pending responses, now 1
2017-12-27 16:56:29.995 DEBUG 10410 --- [ctor-http-nio-2] r.ipc.netty.channel.ContextHandler       : [id: 0x181164b1, L:/127.0.0.1:8080 - R:/127.0.0.1:56468]Mixed pooled connection operations between GET:/api/person/jim - and a previous one GET:/api/person/jim
2017-12-27 16:56:29.995 DEBUG 10410 --- [ctor-http-nio-2] r.ipc.netty.http.server.HttpServer       : [id: 0x181164b1, L:/127.0.0.1:8080 - R:/127.0.0.1:56468] USER_EVENT: [Handler Terminated]
2017-12-27 16:56:29.995 DEBUG 10410 --- [ctor-http-nio-2] r.i.n.channel.ChannelOperationsHandler   : [id: 0x181164b1, L:/127.0.0.1:8080 - R:/127.0.0.1:56468] Disposing context reactor.ipc.netty.channel.ServerContextHandler@17906bb4
2017-12-27 16:56:29.995 DEBUG 10410 --- [ctor-http-nio-2] r.ipc.netty.http.server.HttpServer       : [id: 0x181164b1, L:/127.0.0.1:8080 - R:/127.0.0.1:56468] READ COMPLETE
```

I give special significance to the line:
`
Mixed pooled connection operations between ...`

since its first appearance in the log marks the doom of the ServerApplication. That is, after it is reported for the first time, things fall to pieces.

If you would like more information, please do not hesitate to contact me. I will be more than happy to assist in any way I can.

### JVM version

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version

Ubuntu 17.10 64 bit

**Comment by bclozel** [comment] 2018-01-03 13:22
I've tried to reproduce this issue but couldn't (I ran the sample app many times, for 5+ minutes).

Two things tell me that this is not related to Spring Boot anyway:

* this points to a client connection pooling issue; the client might not read properly the whole server response, which leads to an inconsistent state for the current pooled connection. A few related issues were recently fixed in reactor-netty.
* removing the Spring Security config "solves" the issue. This is rather strange, as I don't think it has anything to do with the described issue.

Now a couple of pointers:

Disabling the connection pooling option on the client might isolate or show the underlying issue.

```
private val client = WebClient.builder()
            .clientConnector(ReactorClientHttpConnector({ it.disablePool() }))
            .baseUrl("http://localhost:8080").build()
```

Also, the debug logs with the requests/responses might show if an exchange was incomplete or if the client failed in some sort. 

In `SecurityConfiguration`, you should not try to inject a component created by a bean method from the same configuration class. This can lead to strange issues.

If you want your client app to not start a server, you should use the appropriate configuration property: `spring.main.web-application-type=none`, the former one is deprecated.

Please try to isolate more the underlying issue or come up with something that is easier to reproduce.

Thanks!

**Closed by bclozel** 2018-01-03 13:22 UTC
Labels: status: waiting-for-triage

**Comment by rstoyanchev** [comment] 2018-01-03 14:05
> removing the Spring Security config "solves" the issue. This is rather strange, as I don't think it has anything to do with the described issue.

It might very well be though because Spring Security switches threads when storing/encoding passwords and there is a known issue in such a scenario https://github.com/reactor/reactor-netty/issues/248.

**Comment by martin-drozdik** [comment] 2018-01-08 17:16
Thank you all for the valuable feedback! I learned a lot from your answers.

Interestingly, disabling the pooling:

```
private val client = WebClient.builder()
            .clientConnector(ReactorClientHttpConnector({ it.disablePool() }))
            .baseUrl("http://localhost:8080").build()
```

Has caused the problem to disappear for me. 

On the other hand, with pooling enabled I get this issue 10 out of 10 times.

I will update the issue if I discover the cause of this problem.

**Comment by bclozel** [comment] 2018-01-08 17:25
This points to actual reactor-netty issue - the reason I couldn't reproduce this is that it is probably linked to the Epoll support in Reactor Netty (Linux based OS only). We'll keep this issue closed as there's nothing we can do in Spring Boot.

**Comment by martin-drozdik** [comment] 2018-01-19 00:22
@bclozel Dear Brian, thank you for all your advice. 

I would just like to ask one small thing. You mentioned:

> In SecurityConfiguration, you should not try to inject a component created by a bean method from the same configuration class. This can lead to strange issues.

Please, could you give me some more explanation on why this may be a problem?

I did my research and I actually found some contradicting evidence, such as this StackOverflow post:

https://stackoverflow.com/a/3330685/1097451

or this usage in the official Spring documentation:

https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo-template.instantiating

Any pointers or reference to documentation are most welcome.

**Comment by bclozel** [comment] 2018-01-19 08:10
@martin-drozdik I was referring to this:

```
    @Bean // requires a ReactiveAuthenticationManager bean
    fun configure(manager: ReactiveAuthenticationManager): SecurityWebFilterChain
   
    @Bean // create a ReactiveAuthenticationManager bean
    fun manager(udr: UserDetailsRepositoryImpl): ReactiveAuthenticationManager
   
```

Using configuration methods like in the examples you pointed to is fine; relying on method parameter injection can be brittle.
