### ISSUE TITLE
inner class SharedMetadataReaderFactoryBean method getObject is not instance of getObjectType

### ISSUE THREAD

**Issue by zxm812** [spring-projects/spring-boot#20000] opened 2020-02-01 11:44 UTC
inner class SharedMetadataReaderFactoryBean of SharedMetadataReaderFactoryContextInitializer implement interface FactoryBean.
 the method of getObject() return type {ConcurrentReferenceCachingMetadataReaderFactory} is not instance of getObjectType() return type {CachingMetadataReaderFactory};

```
@Override
public ConcurrentReferenceCachingMetadataReaderFactory getObject() {
	return this.metadataReaderFactory;
}

@Override
public Class<?> getObjectType() {
	return CachingMetadataReaderFactory.class;
}
```

**Comment by wilkinsona** [comment] 2020-02-01 13:32
Thanks for the report. Unfortunately, you haven’t provided enough information for me to understand the problem. Can you please let us know what version of Spring Boot you are using and what we need to do to reproduce the problem. A minimal sample attached as a zip to this issue or pushed to a separate repository on GitHub would be ideal.

**Comment by spring-issuemaster** [comment] 2020-02-08 13:35
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-02-15 13:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-02-15 13:35 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
