### ISSUE TITLE
Add a property to configure Spring Data JDBC's dialect

### ISSUE THREAD

**Issue by mcnuca** [spring-projects/spring-boot#28847] opened 2021-11-22 10:41 UTC
The default behaviour of `JdbcRepositoriesAutoConfiguration` does not allow an application to start if the datasource connection is not valid. It's because the `DefaultDialectProvider` needs a valid connection in order to auto-detect and provide a `Dialect`. Of course, this behaviour can be changed by implementing a `JdbcDialectProvider` or by overwriting `AbstractJdbcConfiguration.jdbcDialect(NamedParameterJdbcOperations)`, as specified in the documentation. Both solutions involve writing code, though.  

A proposed solution for configuring directly a `Dialect` is to have a new property. For example: `spring.data.jdbc.repositories.dialect`, similar with the JPA property [spring.jpa.database-platform](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.jpa.database-platform)

**Comment by wilkinsona** [comment] 2021-12-06 10:29
There's some similarity to https://github.com/spring-projects/spring-boot/issues/28842. Even without a property, we may be able to use Boot's `DatabaseDriver` to provide the dialect without relying upon a connection. However, with Spring JDBC, I'm not sure how helpful this would be or if it would allow the application to start while the database is down.

**Comment by schauder** [comment] 2021-12-07 14:28
Except for the current Dialect detection Spring Data JDBC shouldn't access the database before it actually gets asked to load or persist something.

**Comment by snicoll** [comment] 2022-01-10 11:38
As far as I can see, the dialect supported by Spring Data JDBC are [hard-coded](https://github.com/spring-projects/spring-data-jdbc/blob/0388315ea5f9f03621473a8f54c4aa37471e13d6/spring-data-jdbc/src/main/java/org/springframework/data/jdbc/repository/config/DialectResolver.java#L118-L141) in the implementation that relies on the connection. We'll have to write a mapping from `DatabaseDriver` to the dialect implementation but it feels to me that an enum in Spring Data JDBC would be beneficiary. For instance a `protected DialectId` dialectId()` in `AbstractJdbcConfiguration` that would return `null` and that can be overridden by configuration?

**Comment by wilkinsona** [comment] 2022-01-19 11:56
I'd envisaged overriding `AbstractJdbcConfiguration.jdbcDialect(NamedParameterJdbcOperations)` in `SpringBootJdbcConfiguration` that returns the dialect that has been configured via a property. However, I'd overlooked the complexity of the MySQL dialect that needs an `IdentifierProcessing` instance and, therefore, doesn't lend itself to property-based configuration.

I don't think there's anything that we can do in Boot without Spring Data JDBC provided a simpler dialect configuration mechanism. @mcnuca, if this is something that you'd still like to see, please open a Spring Data JDBC issue and comment here with a link to it.

**Comment by mcnuca** [comment] 2022-01-20 09:13
@wilkinsona I have created the issue because a Spring Boot application using Spring Data JDBC (and no custom code) does not start if the database is unavailable. The request is very similar with #4779.
I'm sorry if I was not clear enough in the original comment. Setting up a `Dialect` with a property was just a proposal I came up with, but not a request. The problem is still there and maybe it can be solved in a different way.

**Comment by wilkinsona** [comment] 2022-01-20 09:36
Thanks for the clarification. In that case, I'll close this as a duplicate of #4779. If you're interested in pursuing a Spring Data JDBC-specific solution, please open a Spring Data JDBC issue as I don't think we can do anything in Boot without a change in Data JDBC.

**Closed by wilkinsona** 2022-01-20 09:36 UTC
Labels: type: enhancement, status: waiting-for-triage, status: feedback-provided

**Comment by mcnuca** [comment] 2022-01-20 09:45
@wilkinsona The issue has been originally opened in Spring Data JDBC and transferred later to Spring Boot by @odrotbohm

**Comment by wilkinsona** [comment] 2022-01-20 10:00
I realise that. The issue as written was clearly about Spring Boot as it mentioned Boot's `JdbcRepositoriesAutoConfiguration` in its opening sentence so it's entirely understandable that Ollie transferred it to us to investigate.

After the investigation above, it's become clear that there's nothing that we can do for Spring Data JDBC specifically without a change in Spring Data JDBC. I am recommending that you open a Spring Data JDBC issue that doesn't mention Boot at all but instead proposes making it easier to configure Data JDBC's dialect for everyone, not just Spring Boot's users. For example, if the [mechanism that maps between String IDs and dialect instances was public](https://github.com/spring-projects/spring-data-jdbc/blob/eee773ea829403f0a3802aad046177e559903ea4/spring-data-jdbc/src/main/java/org/springframework/data/jdbc/repository/config/DialectResolver.java#L112-L145), Spring Data JDBC could be passed an ID and then use the corresponding dialect without need for a `Connection` to the database. Spring Boot could then add a property that's used to supply the ID that's passed into Spring Data JDBC to configure its dialect.
