### ISSUE TITLE
Returning Mono.empty causes controller to halt

### ISSUE THREAD

**Issue by bazusaladra** [spring-projects/spring-boot#15214] opened 2018-11-19 12:57 UTC
The following code used to work on SpringBoot 2.0.2
```
    @GetMapping(path = "search")
    public Mono<String> search(@RequestParam(value = "query") String query) {
        if (Objects.isNull(query) || query.isEmpty()) {
            return Mono.empty();
        }
        return Mono.just("result: " + query);
    }
```
After upgrading to SpringBoot 2.1.0 calling
```
String actualEmptyResult = restTemplate.getForObject("/api/search?query=", String.class);
```
causes any subsequent requests to this endpoint to be stalled.
Please check out test `org.springtest.EmptyMonoFailureTest#testMono` in repository https://github.com/bazusaladra/spring-mono-test.
Please advice, to which module this issue may be related to.

**Comment by bclozel** [comment] 2018-11-19 14:07
When changing the server from reactor-netty to Tomcat, I can't reproduce the bug anymore:

```groovy
compile('org.springframework.boot:spring-boot-starter-tomcat')
```

Also, updating to the latest `2.1.1.BUILD-SNAPSHOT`

```groovy
buildscript {

    ext {
        //springBootVersion = '2.0.2.RELEASE' // works
        springBootVersion = '2.1.1.BUILD-SNAPSHOT' // error
    }

    repositories {
        mavenCentral()
        maven {
          url "https://repo.spring.io/libs-snapshot"
        }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}


mainClassName = 'org.springtest.MonoTestApplication'

repositories {
    mavenCentral()
    maven {
      url "https://repo.spring.io/libs-snapshot"
    }
}
```

The issue seems to be resolved. I think it might be a reactor Netty issue, although I can't pinpoint exactly which one - they were several changes in that area recently.

I'm closing this issue as it doesn't seem to be a Spring Boot issue and it's been resolved already. In the meantime, you can use Tomcat as a server.

Thanks!

**Closed by bclozel** 2018-11-19 14:07 UTC
Labels: status: waiting-for-triage
