### ISSUE TITLE
Ability to exclude some endpoints from being traced

### ISSUE THREAD

**Issue by fatihdogmus** [spring-projects/spring-boot#33875] opened 2023-01-18 13:53 UTC
Hello,

I've basically scoured the internet and the source codes, but couldn't find a way to exclude some URL patterns from being traced.

We use micrometer with otel bridge and zipkin exporter to get the trace data. Our use case is that there are a lot of traces regarding actuator, for both health and prometheus endpoints, so we want to filter out those requests.

I've asked the question in micrometer tracing, but they said to open an issue here.
An application properties to filter out some URLs to not trace would be great to get rid of all the health checks and other unnecessary traces.

I've hacked a solution and posted it in this issue in micrometer repo: https://github.com/micrometer-metrics/tracing/issues/148#issuecomment-1387101720

But it would be great to have this natively.

Thank you.

**Comment by bclozel** [comment] 2023-01-18 14:00
Closing as a duplicate of #13435, also see spring-projects/spring-framework#29210 which should help with this.

**Closed by bclozel** 2023-01-18 14:00 UTC
Labels: status: waiting-for-triage
