### ISSUE TITLE
It is unclear that server.tomcat.max-http-post-size and server.jetty.max-http-post-size only apply to POSTed form content

### ISSUE THREAD

**Issue by fg8dgrdh** [spring-projects/spring-boot#18521] opened 2019-10-06 17:46 UTC
The [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) describes the following:

```
server.tomcat.max-http-post-size=2MB # Maximum size of the HTTP post content.
```

However this setting only affects post requests with FORM content, not all post requests. This can lead to confusion for myself and others (as per stackoverflow questions). A more precise description would be helpful, such as:

```
server.tomcat.max-http-post-size=2MB # Maximum size of the FORM content in an HTTP post request. Non-FORM post requests are unaffected by this property.
```

**Comment by rhamedy** [comment] 2019-10-06 21:00
@snicoll can I make a PR for this?

**Comment by snicoll** [comment] 2019-10-06 21:04
Thanks for the offer. The issue has been triaged and isn't assigned at the moment so feel free to do it

**Comment by rhamedy** [comment] 2019-10-06 23:49
Updated the Javadoc in the `ServerProperties.java`, not sure if there is anything else that needs to be done.

**Comment by wilkinsona** [comment] 2019-10-07 16:19
We have a similar problem with Jetty. The property, `server.jetty.max-http-post-size`, is described as "Maximum size of the HTTP post or put content" but it maps onto `setMaxFormContentSize` and is specific to POSTed form content. As far as I can tell, content sent as a `PUT` is not affected.

Undertow is also affected but the problem is different. The property, `server.undertow.max-http-post-size`, is described as "Maximum size of the HTTP post content. When the value is -1, the default, the size is unlimited". It maps onto `Undertow.MAX_ENTITY_SIZE` which isn't limited to form content but also isn't limited to POST requests. The property would be better named something like `server.undertow.max-http-entity-size`.

Given that we need to deprecate `server.undertow.max-http-post-size` and provide a replacement. I wonder if we should do similar for `server.jetty.max-http-post-size` and `server.tomcat.max-http-post-size`. `max-http-form-post-size` would perhaps be a more accurate name.

**Comment by fg8dgrdh** [comment] 2019-10-09 00:25
@sbrannen Sorry about opening the issue in the wrong project, I'll try and be more careful next time.

@snicoll Thanks for transferring the ticket, I appreciate it.

@rhamedy Thanks for the PR!

@wilkinsona I like the max-http-form-post-size idea

**Comment by rhamedy** [comment] 2019-10-09 15:47
IMO, deprecation seem to be the more suiting fix based on wikinsona’s explanation.

Regardless, I would be happy to re-purpose the PR should the scope of this issue change 👌

**Comment by wilkinsona** [comment] 2019-10-10 17:24
https://github.com/spring-projects/spring-boot/issues/18555 is related to, or maybe even a duplicate of, the Undertow aspects of this.

**Comment by wilkinsona** [comment] 2019-10-11 18:05
We're going to introduce new properties in 2.1.x:

- `server.jetty.max-http-post-size`
- `server.tomcat.max-http-post-size`

We'll deprecate the old, misleadingly named properties at the same time.

We'll use #18555 to figure out the Undertow side of this once we know if the multipart config element behaviour is intentional or a bug.

**Comment by rhamedy** [comment] 2019-10-12 02:04
@wilkinsona aren't they already named that way? 😕 
```
// server.jetty.max-http-post-size
private DataSize maxHttpPostSize = DataSize.ofBytes(200000);

// server.tomcat.max-http-post-size
private DataSize maxHttpPostSize = DataSize.ofMegabytes(2); //tomcat
```
I could update my PR and base it off `2.1.x` branch 🙂

**Comment by wilkinsona** [comment] 2019-10-12 11:16
Sorry, I meant to include `form` in the new names. I've updated my comment above.

**Comment by wilkinsona** [comment] 2019-10-14 10:58
Closing in favour of #18566.

**Closed by wilkinsona** 2019-10-14 10:58 UTC
Labels: type: bug

**Comment by HimanshuChugh2** [comment] 2020-08-03 20:38
Hello,

i have tried writing this 

```
@Bean  
    public TomcatServletWebServerFactory tomcatEmbedded() {  

		TomcatServletWebServerFactory tomcat = new TomcatServletWebServerFactory();  

        tomcat.addConnectorCustomizers((TomcatConnectorCustomizer) connector -> {  
            if ((connector.getProtocolHandler() instanceof AbstractHttp11Protocol<?>)) {  
                //-1 means unlimited  
                ((AbstractHttp11Protocol<?>) connector.getProtocolHandler()).setMaxSwallowSize(100000000);  
                
                ((AbstractHttp11Protocol<?>) connector.getProtocolHandler()).setMaxSavePostSize(100000000);
            }  
        });  

        return tomcat;  
    }
	
```


and this in application.properties file


```
# Server properties
server.tomcat.max-http-post-size=100000000
server.tomcat.max-swallow-size=100000000
```

it is still not passing text(json which includes base64 text too) of more then 2MB from html to controller.

Why is this happening?

Please help

**Comment by wilkinsona** [comment] 2020-08-04 08:04
Unfortunately, I can't say why it's happening from a couple of code snippets. We need to see more of your application – for example exactly how the browser is sending the information to the controller – but a closed issue isn't the right place. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. If you believe that you've found a bug, and you would like us to spend some more time investigating, please open a new issue and spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to the issue that you open.

**Comment by HimanshuChugh2** [comment] 2020-08-04 12:54
Hello sir @wilkinsona ,

i have created a new issue(https://github.com/spring-projects/spring-boot/issues/22724), kindly requesting you to take a look.

Thank you so much in advance.

**Comment by benjaminxie02** [comment] 2026-08-11 13:40
For anyone that finds this, know that the setting was changed to include 
"form" in its name at least since v3.3

https://docs.spring.io/spring-boot/3.3/appendix/application-properties/index.html#application-properties.server.server.tomcat.max-http-form-post-size
