### ISSUE TITLE
Maven plugin (spring-boot:run) produces NPE when empty argument is passed in plugin config

### ISSUE THREAD

**Issue by alan-czajkowski** [spring-projects/spring-boot#9713] opened 2017-07-10 19:20 UTC
The Maven plugin needs to have much more robust/defensive code. It is way too easy to produce a NPE with ```mvn spring-boot:run``` by just doing this:
```xml
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <arguments>
      <argument></argument>
    </arguments>
  </configuration>
</plugin>
```

**Comment by wilkinsona** [comment] 2017-07-10 21:00
This looks like a bug in Maven to me that we'll probably need to work around. It appears to translate `<argument></argument>` into `null`. I'd expect an empty string instead.

@alan-czajkowski What version of Maven are you using?

**Comment by alan-czajkowski** [comment] 2017-07-10 21:18
@wilkinsona I wouldn't blame Maven for this, this can easily be expected behaviour, and I don't necessarily agree that an empty String would result from that, what needs to happen is that the code needs to be very defensive, you can very easily check for a non-blank value using:
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-

I'm using Maven 3.5 (but that should be irrelevant)

**Comment by wilkinsona** [comment] 2017-07-10 21:25
Thanks, but I'm well aware of how to check if a String is null or empty. I can even do it without using a third-party library.

**Comment by alan-czajkowski** [comment] 2017-07-10 21:25
@wilkinsona I wasn't trying to offend, I just like using 3rd-party libraries because they make the code nicer to read, that is all

**Comment by snicoll** [comment] 2017-09-19 12:38
Duplicate of #9916

**Closed by snicoll** 2017-09-19 12:38 UTC
Labels: priority: low, status: ideal-for-contribution, type: bug
