### ISSUE TITLE
Spring boot 2.3.7.RELEASE is not deleting TMP file after they are not needed anymore 

### ISSUE THREAD

**Issue by mindej** [spring-projects/spring-boot#24853] opened 2021-01-15 15:04 UTC
Spring boot 2.3.7.RELEASE is not deleting TMP file after they are not needed anymore thus pods get evicted all the time.

To reproduce:

1) Configure TMP dir

`spring.servlet.multipart.location=/tmp/test`

2) Upload multi-part files to spring boot
3) Test directory contents.

**Comment by wilkinsona** [comment] 2021-01-15 15:12
Thanks for the report but you haven't provided enough information for us to diagnose the problem. For example, you haven't told us which embedded container you're using. If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-projects-issues** [comment] 2021-01-22 15:15
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mindej** [comment] 2021-01-22 15:30
The embedded container is the default witch is coming with Spring boot 2.3.7.RELEASE

**Comment by wilkinsona** [comment] 2021-01-22 16:02
Thanks, but we need a bit more than that. As I said above, if you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-projects-issues** [comment] 2021-01-29 16:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-02-05 16:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-02-05 16:07 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
