### ISSUE TITLE
Leverage the CompositeCacheManager with CacheManagerCustomizer

### ISSUE THREAD

**Issue by celcius112** [spring-projects/spring-boot#16808] opened 2019-05-09 13:43 UTC
Hello everyone,

I have a library defining a **Caffeine** cache and a project using this library that also defines a cache, but this time a **Redis** one.

We define our caffeine cache as such:
```java
    @Bean
    public CacheManagerCustomizer<CaffeineCacheManager> customizeCaffeine() {
        return cacheManager -> cacheManager
                .setCaffeine(Caffeine.newBuilder().maximumSize(10));
    }
```
so that Spring Boot can handle the CacheManager itself, which gives us access to utilities such as the property `spring.cache.type` (useful to deactivate the cache in the tests) and `@AutoConfigureCache`.

However as soon as we want to configure our Redis cache it becomes much more difficult. `RedisCacheManager` is immutable and as such not configurable with `CacheManagerCustomizer`. Also, we cannot define a bean of type `RedisCache` since it is not visible (however I'm not sure this solution would be viable here). So the only solution I see is to define our own `RedisCacheManager` bean, but as soon as we do that disabling the cache with `spring.cache.type=none` (as per the [documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-none)) would not work since there already is a `CacheManager` bean defined in the context.

One solution would be to let the `RedisCacheManager` being more flexible, as `CaffeineCacheManager` or `CouchbaseCacheManager` are. I saw this [issue](https://github.com/spring-projects/spring-boot/issues/15960), but I do not think the actual commit would provide a more flexible customization. 
Another solution I see would be to leverage the `CompositeCacheManager` with something like this:
```java
    // Config in library
    @Bean
    public CacheManagerCustomizer<CompositeCacheManager> caffeineCache() {
        CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
        caffeineCacheManager.setCaffeine(Caffeine.newBuilder().maximumSize(10));
        return composite -> composite.addCache(caffeineCacheManager);
    }

    // Config in application
    @Bean
    public CacheManagerCustomizer<CompositeCacheManager> redisCache(RedisConnectionFactory redisConnectionFactory) {
        RedisCacheManager redisCacheManager = RedisCacheManager.RedisCacheManagerBuilder
                .fromConnectionFactory(redisConnectionFactory)
                .build();
        return composite -> composite.addCache(redisCacheManager);
    }
```
with the `CompositeCacheManager` being able to handle whether we want to disable caching altogether or not.

**Comment by snicoll** [comment] 2019-05-09 14:01
> I saw this issue, but I do not think the actual commit would provide a more flexible customization.

Yet, that's the route we need to explore I am afraid. `RedisCacheManager` took the route of immutability and therefore you can't really use the customizer pattern with that one.

I've clarified the issue you've referenced in that sense.

Using a `CompositeCacheManager` is not an option I am keen to explore as I believe the cache auto-configuration is already too involved at this point.

Duplicate of #15960

**Closed by snicoll** 2019-05-09 14:01 UTC
Labels: status: waiting-for-triage

**Comment by celcius112** [comment] 2019-05-10 16:02
@snicoll Re-hi,

After playing a bit with the different `CacheManager` implementations I realized that even having different `CacheManagerCustomizer<>` for different type of CacheManager would still not work, which is quite understandable since the `@ConditionalOnMissingBean(CacheManager.class)` on the different cache configurations prevent the instantiation of multiple `CacheManager`s.
For instance
```java
    // Config in library 
    @Bean
    public CacheManagerCustomizer<CaffeineCacheManager> caffeineCacheManager() {
        return cacheManager -> {...};
    }

    // Config in application
    @Bean
    public CacheManagerCustomizer<ConcurrentMapCacheManager> cacheManagerCustomizer() {
        return cacheManager -> {...};
    }
```
would only instantiate a `CaffeineCacheManager` because of its higher priority in `CacheConfigurations`.

So I might be asking for the 🌕, but wouldn't letting Spring Boot customize a `CompositeCacheManager` be the right way here ?

**Comment by snicoll** [comment] 2019-05-10 16:05
> but wouldn't letting Spring Boot customize a CompositeCacheManager be the right way here ?

The auto-configuration does not handle multi cache libraries implementation via the `CompositeCacheManager`. As I've already mentioned, I am not keen to bring that extra amount of check/complexity.

**Comment by celcius112** [comment] 2019-05-10 16:09
Hmmm ok fair enough, thank you for the quick answers. We'll try to implement something answering this need in our project, but of course less powerful than if you'd implement it 😉
