### ISSUE TITLE
@ConfigurationProperties bind field so slow

### ISSUE THREAD

**Issue by martintalor** [spring-projects/spring-boot#31666] opened 2022-07-11 07:15 UTC
I implements PropertySourceFactory return PropertiesPropertySource but yaml is so large，in yaml have a list more then 10 size 。then will be sort question
![image](https://user-images.githubusercontent.com/30927383/178208970-e96b2b60-a36f-4d0b-a441-833a20275656.png)

1 then 10  but want 2

**Comment by wilkinsona** [comment] 2022-07-11 07:25
Thanks for the report. Unfortunately, I don't understand what the problem is or what it is that is slow. Can you please provide a complete yet minimal example that reproduces the slowness? You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by martintalor** [comment] 2022-07-11 09:40
sorry，this code can not out，but this mean that i use @ConfigurationProperties and @PropertySource create a configurebean。when the yaml is too large bind field too slow  yaml like this
AA:
   BB:
     - XX:
       BB:
            -XX:
              BB:
                  -XX:
                    BB:
     - XX:
       BB:
 - XX:
   BB:
 - XX:
   BB:
 - XX:
   BB:
 - XX:
   BB:

the last I want bind to list<BB>

**Comment by wilkinsona** [comment] 2022-07-11 11:02
Unfortunately, we cannot investigate a performance problem that we cannot reproduce.  If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. It doesn't have to be your application's code, it just needs to be enough to reproduce the problem.

**Comment by spring-projects-issues** [comment] 2022-07-18 11:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-07-25 11:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-07-25 11:05 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
