### ISSUE TITLE
Why after i used actuator-api Evict All Caches，i alose can use actuator-api Retrieving All Caches，am i wrong?

### ISSUE THREAD

**Issue by HellLiang** [spring-projects/spring-boot#32116] opened 2022-08-19 08:38 UTC
1、i use actuator-api like following:
![1](https://user-images.githubusercontent.com/64981240/185579436-792df8d0-50b3-48e7-a586-c5ad3e9caef1.png)

![2](https://user-images.githubusercontent.com/64981240/185579451-0478c2f0-6cfe-49ed-8ad3-27bdb6c979dd.png)

2、after a evict caches success，but i can also use actuator-api like following:
![3](https://user-images.githubusercontent.com/64981240/185579740-02a9b7a4-fb6c-427e-bf21-d5c68733390e.png)

![4](https://user-images.githubusercontent.com/64981240/185579775-fe65af16-2929-41a8-b184-368404e02111.png)

**Comment by snicoll** [comment] 2022-08-19 09:12
Duplicate of #32115

**Closed by snicoll** 2022-08-19 09:12 UTC
Labels: status: waiting-for-triage
