### ISSUE TITLE
HTTP response header X-Application-Context ignores spring.application.name property value

### ISSUE THREAD

**Issue by tobiasschaefer** [spring-projects/spring-boot#14468] opened 2018-09-14 09:44 UTC
**Scenario:**
- Using: Spring Boot 2.0.5.RELEASE
- set management.server.add-application-context-header=true in application.properties
- set spring.application.name=myapp in application.properties

**Expected:**
HTTP Response Headers should include the value "myapp" in the X-Application-Context response header.

**Actual Response:**
HTTP Response Header X-Application-Context has the value "application-1" (instead of expceted value "myapp-1")

**First analysis:**
I looked at https://github.com/spring-projects/spring-boot/blob/v2.0.5.RELEASE/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/ContextIdApplicationContextInitializer.java and see that "application" is the default value if the property value of spring.application.name is empty.
Maybe the properties haven't been loaded yet and that is why the value is not being used.

Note: In Spring Boot 1.5.16 the default of management.add-application-context-header (slightly different name without "server") is true and its returning spring.application.name correctly in the X-Application-Context response header.

**Comment by wilkinsona** [comment] 2018-09-14 10:34
Thanks for the report, but I can't reproduce the behaviour you have described. With `spring.application.name` set to `my-app` the `X-Application-Context` header has a value of `my-app`:

```
$  curl -i localhost:8080/actuator/info
HTTP/1.1 200 
X-Application-Context: my-app
Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 14 Sep 2018 10:33:42 GMT

{"example":{"someKey":"someValue"}}
```

If you would like us to spend some more time investigating, please provide a minimal sample that reproduces the problem.

**Comment by tobiasschaefer** [comment] 2018-09-14 11:15
Thanks for your fast response. I managed to isolate it even more.

To reproduce
* Create an empty project with the https://start.spring.io/ only with the "Web" dependency
* set management.server.add-application-context-header=true in application.properties
* set spring.application.name=myapp in application.properties
* call http://localhost:8080 or http://localhost:8080/does-not-exist 

This will not return the X-Application-Context response header and of course both with HTTP Status 404.

The same applies if you add an endpoint with
`@RestController
	public static class Resource {
		@RequestMapping(path = "/hello")
		public String hello() {
			return "hello";
		}
	}`
This will then return HTTP Status 200 but without the X-Application-Context response header.

However, as soon as you include the Spring Actuator Dependency it will work. That is probably why it worked in your case.

Strangely, the project I noticed this misbehavior includes the Spring Actuator Dependency and it does not work. So there seems to be one more issue which I cannot isolate yet.

However, I hope you can now reproduce this.

**Comment by wilkinsona** [comment] 2018-09-14 11:52
> However, as soon as you include the Spring Actuator Dependency it will work. That is probably why it worked in your case.

As with all `management.*` properties, you need to be using Actuator for them to take effect. It's Actuator that auto-configures the Filter that adds the header. If you're not using Actuator and you haven't configured the Filter (`ApplicationContextHeaderFilter`) yourself, you won't get the header.

> Strangely, the project I noticed this misbehavior includes the Spring Actuator Dependency and it does not work.

This should work. Please provide a sample that reproduces this behaviour and we can take a look.

**Comment by tobiasschaefer** [comment] 2018-09-19 10:32
Thanks for that fast response again.

I narrowed it down more: the behavior can be reproduced only if the dependency "spring-cloud-starter-netflix-hystrix" is included.

`
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>

	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
	</dependency>
</dependencies>

<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>Finchley.SR1</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
`

**Comment by wilkinsona** [comment] 2018-09-19 13:06
The behaviour is another unfortunate side-effect of Spring Cloud's bootstrap context. When the bootstrap context is initialized, a `ContextId` bean is added to it by `ContextIdApplicationContextInitializer`. It uses the ID `application` (the default) because the configuration of `spring.application.name` is not visible to the bootstrap context. When the main application context is created it is a child of the bootstrap context. When the context's ID is being determined, the `ContextId` bean in the parent is found and it's used to derive the context's ID. This results in it being `application-1` rather than the expected `myapp-1`.

Given that Spring Boot does not and should not know anything about Spring Cloud's Bootstrap context, I think this needs be fixed in Spring Cloud. I have opened https://github.com/spring-cloud/spring-cloud-commons/issues/416.

**Closed by wilkinsona** 2018-09-19 13:06 UTC
Labels: status: feedback-provided, status: waiting-for-triage
