### ISSUE TITLE
mvn javadoc:javadoc fails if using spring-boot-starter-batch

### ISSUE THREAD

**Issue by megascus** [spring-projects/spring-boot#2677] opened 2015-03-18 06:47 UTC
mvn javadoc:javadoc fails because javax.interceptor is not found.
I correspond by adding the following  to pom.xml.
```
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-el</artifactId>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by snicoll** [comment] 2015-03-18 08:12
I am confused, there is no code in `spring-boot-starter-batch` - why would you want to run javadoc there anyway?

**Comment by megascus** [comment] 2015-03-18 08:55
sorry, this is the story of my project that depends on spring-boot-starter-batch.

**Comment by snicoll** [comment] 2015-03-18 08:59
This is actually a duplicate of #2293 - you need to add that dependency yourself.

**Comment by wilkinsona** [comment] 2015-03-18 09:28
@sncioll I don't think this is a duplicate of #2293. That issue's about EL dependencies and the `javax.interceptor` package has nothing to do with EL.

@megascus I can run `mvn javadoc:javadoc` successfully against `spring-boot-sample-batch` which depends on `spring-boot-starter-batch` so the problem is more subtle than you've described. This was with Java 8. I don't think we want to add a provided dependency to the starter as it may lead to people accidentally using it in their code and then getting a failure at runtime because the class cannot be found.

**Comment by megascus** [comment] 2015-03-18 09:34
Thank you for checking.
I will try to find it again.

**Comment by snicoll** [comment] 2015-03-18 09:34
My bad, thanks andy!

**Comment by megascus** [comment] 2015-03-18 09:58
Sorry, it's problem of javac version...

in Java 1.8.0_25(Windows 7)
failture.
---
javadoc: エラー - com.sun.tools.doclets.internal.toolkit.util.DocletAbortExcepti
on: com.sun.tools.javac.code.Symbol$CompletionFailure: javax.interceptor.Interce
ptorBindingのクラス・ファイルが見つかりません

Command line was: "C:\Program Files\Java\jdk1.8.0_25\jre\..\bin\javadoc.exe" -J-
Dhttp.proxySet=true -J-Dhttp.proxyHost=172.24.1.50 -J-Dhttp.proxyPort=80 @option
s @packages

Refer to the generated Javadoc files in 'C:\Users\2568.BBS\Documents\NetBeansPro
jects\jobtool\jobtool-batch\target\site\apidocs' dir.

        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeJavadocCom
mandLine(AbstractJavadocMojo.java:5063)
        at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(Abs
tractJavadocMojo.java:2004)
        at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.
java:130)
        at org.apache.maven.plugin.javadoc.JavadocReport.execute(JavadocReport.j
ava:315)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

in Java 1.7.0_75(Windows 7)
success.

**Comment by philwebb** [comment] 2015-03-24 21:12
I don't seem to be able to replicate with Java 1.8.0_40. If you're able to put together a sample application and the steps to reproduce the problem then please reopen this issue.

**Closed by philwebb** 2015-03-24 21:12 UTC
Labels: invalid
