### ISSUE TITLE
Make WebMvcAutoConfigurationAdapter.FaviconRequestHandler package private

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#16233] opened 2019-03-14 18:00 UTC
There's a new private class in `spring-boot-autoconfigure`. Can I ask that `WebMvcAutoConfigurationAdapter.FaviconRequestHandler` be package private please?

**Comment by mrifni** [comment] 2019-03-15 08:45
Can I pick this up please ?

**Comment by snicoll** [comment] 2019-03-15 09:31
@mrifni please go ahead, the issue is not assigned.

**Comment by mrifni** [comment] 2019-03-15 09:44
sure doing it..

**Comment by snicoll** [comment] 2019-03-17 08:26
Closing in favour of PR #16250

**Comment by mrifni** [comment] 2019-03-17 08:26
@snicoll please find the simple PR for this task [here](https://github.com/spring-projects/spring-boot/pull/16250).

Happy to contrtibute.
@pkostrzewa thanks.

**Closed by snicoll** 2019-03-17 08:26 UTC
Labels: type: task
