### ISSUE TITLE
Redis connection leak in cloudfoundry

### ISSUE THREAD

**Issue by mrkk** [spring-projects/spring-boot#16932] opened 2019-05-21 23:00 UTC
Trying to use spring data redis and default lettuce configuration under cloudfoundry causes resource leak - I am using spring-boot-starter-data-redis 2.0.6

```java
@Configuration
@Profile("cloud")
public class RedisCloudConfig extends AbstractCloudConfig {

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        return connectionFactory().redisConnectionFactory("redis-pcf-service");
    }

    @Bean
    RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory factory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(factory);
        redisTemplate.setDefaultSerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setHashKeySerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
        return redisTemplate;
    }

    @Bean
    public RedisCacheManager redisCacheManager(RedisConnectionFactory factory) {
        return RedisCacheManager.builder(factory).cacheDefaults(
                RedisCacheConfiguration.defaultCacheConfig()
                        .serializeValuesWith(RedisSerializationContext.SerializationPair.fromSerializer(
                                new GenericJackson2JsonRedisSerializer())))
                .build();
    }
```

```
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT                 LEAK: HashedWheelTimer.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT Recent access records:
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT Created at:
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:272)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:216)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:195)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:177)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:161)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:163)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:461)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:229)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:96)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.lettuce.core.RedisClient.<init>(RedisClient.java:86)
   2019-05-21T17:13:34.85-0500 [APP/PROC/WEB/0] OUT     io.lettuce.core.RedisClient.create(RedisClient.java:123)
```

**Comment by mrkk** [comment] 2019-05-21 23:00
also https://stackoverflow.com/questions/55710319/resource-leak-detected-when-using-spring-data-redis-on-cloud-foundry

**Comment by wilkinsona** [comment] 2019-05-22 07:12
This looks like a Spring Data Redis or Lettuce issue to me. @mp911de, can you please advise?

**Comment by mp911de** [comment] 2019-05-22 08:27
This message typically occurs when creating `io.lettuce.core.RedisClient` without shutting down the client. A common case would be when `RedisClient` gets created twice and only one of the two are used. I'm not sure which component creates the second (probably undesired) `RedisClient` instance.

Is the buildpack's auto-reconfiguration probably kicking in?

**Comment by mrkk** [comment] 2019-05-22 15:33
I am trying to read LettuceConnectionConfiguration

It depends on RedisClient already being created
And then creates DefaultClientResources if missing

That is upside-down

You need DefaultClientResources in lettuce world to create a RedisClient!?

**Comment by wilkinsona** [comment] 2019-05-22 15:41
> It depends on RedisClient already being created

Why do you say that? `LettuceConnectionConfiguration` is conditional on `RedisClient.class` being on the classpath. It does not require a `RedisClient` instance to have been created, however. The `RedisClient` instance is not created until `afterPropertiesSet()` is called on the `LettuceConnectionFactory` bean that's defined by `LettuceConnectionConfiguration`.

Can you please answer Mark's question regarding the use of the buildpack's auto-reconfiguration?

**Comment by mrkk** [comment] 2019-05-22 16:38
how do I know if auto reconfiguration is happening

BTW I had to do this for the stacktrace to go away, but before this change I could have pretended that I know nothing about lettuce.

`    @Bean(destroyMethod = "shutdown")
    public DefaultClientResources lettuceClientResources() {
        return DefaultClientResources.create();
    }

    @SuppressWarnings("unused")
    @Bean
    public RedisConnectionFactory redisConnectionFactory(DefaultClientResources dependency) {
        return connectionFactory().redisConnectionFactory("redis-pcf-service");
    }`

**Comment by wilkinsona** [comment] 2019-05-22 16:49
You can learn more about auto-reconfiguration in the [documentation](https://docs.run.pivotal.io/buildpacks/java/configuring-service-connections/spring-service-bindings.html). It's impossible for me tell if it's involved at the moment as you haven't shared enough information about your application.

If you would like us to spend some more time trying to help you, I think it would be most productive if you spent some time providing a complete and minimal sample that reproduces the problem. A project attached as a zip to this issue or in a separate repository on GitHub would be ideal.

**Comment by spring-issuemaster** [comment] 2019-05-29 16:53
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-05 16:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-05 16:52 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
