### ISSUE TITLE
Enable `ConfigurationProperties` validation with `@Validated` on the factory method

### ISSUE THREAD

**Issue by romainmoreau** [spring-projects/spring-boot#10803] opened 2017-10-28 17:30 UTC
I identified two cases when I believe it's unjustified:
1. Third party component
```java
	@Bean
	@Validated
	@ConfigurationProperties("third-party-bar")
	public ThirdPartyBarComponent thirdPartyBarComponent() {
		return new ThirdPartyBarComponent();
	}
```
`2017-10-28 19:15:32.318  WARN 16592 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class fr.romainmoreau.validatedwarning.ThirdPartyBarComponent contains validation constraints but had not been annotated with @Validated.`

2. Nested bean
```java
@Component
@Validated
@ConfigurationProperties("bar")
public class BarComponent {
	@Valid
	private List<NestedBar> nestedBars;
```
`2017-10-28 19:15:32.217  WARN 16592 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class fr.romainmoreau.validatedwarning.NestedBar contains validation constraints but had not been annotated with @Validated.`

The complete demo project can be found here: https://github.com/romainmoreau/validated-warning

**Comment by snicoll** [comment] 2017-10-29 07:03
The [documentation] refers to classes, not factory method so the 1st case isn't supported at the moment (but I agree it would be nice if we did).

**Comment by wilkinsona** [comment] 2017-11-06 09:53
I think we'll need to support the 1st case for Boot 2.0. Right now, the warning is gone, but you won't get any validation.

The second case feels like a bug to me and should be fixed in 1.5.x. I've opened https://github.com/spring-projects/spring-boot/issues/10931.

**Comment by snicoll** [comment] 2017-11-06 11:06
@wilkinsona thanks. I agree and I've requalified the issue.

**Comment by snicoll** [comment] 2017-11-14 09:11
It looks like the constraint to have `@Validated` on the target class is actually backed in the binding as well. @philwebb is that intended? How do you enable validation for a class you don't control? 

I've started to work on something at the `@ConfigurationProperties` level that should work (see 
14ff2a8) but the test does not pass  because `ValidateBindHandler` [has an additional hard-coded check](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/validation/ValidationBindHandler.java#L70-L74).

**Comment by snicoll** [comment] 2018-01-23 14:24
I have rebased my initial proposal and I am not looking for a way to tell the binder it should look for a `@Validated` annotation on the class.

**Comment by snicoll** [comment] 2018-01-24 17:05
There is a regression that is due to [this change](https://github.com/snicoll/spring-boot/commit/b8e535b603a1983360c4a3f6d2daf9c820df2705#diff-e74ae7292f139cd9b8ff5da11fba2c0bR42). If I restore it, the previous test is passing again but the new test I've introduced for the bean factory case doesn't. 

So we need to carry this check in that object as well. If we fail to do so, the `@Validated` is not  found (since it's only present on the factory method) and validation doesn't kick in at all.

I am not aware of any other scenario where `@Valid` is set on the factory method so perhaps that's something we do not support at the moment?

**Comment by snicoll** [comment] 2018-01-25 14:00
@mbhave and I reviewed the code this morning and came up with an alternative (see https://github.com/snicoll/spring-boot/commit/e672022ce46692f928d619da9d9daa2ce8b7d46d). Unfortunately, it does not work for the same reason. 

Deep down, the validation is checking if the target type is supported and that  goes through a check on the presence of `@Validated` again. We could fix this if we had a way to make that  check for nested object but not the main one (in practice the first check is a bit weird considering the `ValidationBindHandler` instance has been created for the very purpose of validating the object).

**Closed** 2018-02-17 02:12 UTC
Labels: priority: high, type: enhancement
