### ISSUE TITLE
TraceId and spanId are getting null

### ISSUE THREAD

**Issue by tadlakha9** [spring-projects/spring-boot#34599] opened 2023-03-14 13:31 UTC
Bug report
Hi, using latest Spring versions (6.0.4 ) while hitting an API in a microservice, traceId and spanId are not logged properly(getting blank) after migrating to spring boot 3 with spring boot 2 it is working fine.

Thank you

**Comment by wilkinsona** [comment] 2023-03-14 14:03
Thanks for the report. Unfortunately it does not contain enough information for us to be able to help you. It may be a duplicate of https://github.com/spring-projects/spring-boot/issues/33372 but I don't know if you're using WebFlux.

Please upgrade to the latest version of Spring Boot or even try snapshots that are available from https://repo.spring.io/snapshot. If the problem remains and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by tadlakha9** [comment] 2023-03-15 05:59
yes we are using the webflux, i think #33372 will help

Thanks

**Closed** 2023-03-15 08:16 UTC
Labels: status: waiting-for-triage, status: feedback-provided
