### ISSUE TITLE
Trying to exclude dependencies from a repackaged JAR using [`<excludes>`] still includes transitive dependencies.

### ISSUE THREAD

**Issue by chanseokoh** [spring-projects/spring-boot#22981] opened 2020-08-17 13:49 UTC
Excluding dependencies from a repackaged JAR using [`<excludes>`](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/html/#repackage-example-exclude-dependency) should exclude transitive dependencies as well. More details are in #13289.

For more context, this is from the hidden comment (https://github.com/spring-projects/spring-boot/issues/13289#issuecomment-674882306) marked as off-topic in #13289:

> The following hidden comments (https://github.com/spring-projects/spring-boot/issues/13289#issuecomment-498153907, https://github.com/spring-projects/spring-boot/issues/13289#issuecomment-519075075) marked as off-topic seems to be very informative and vital for those who would like to exclude `provided`-scoped dependencies as a workaround.
> 
> > @brianwhu `exclude` works for single dependency only; any transitive still packaged
> 
> > Bad news: `<excludes>` excludes only a specific artifact, but includes all its transitive dependencies!
> 
> I do not understand why someone has hidden such helpful information as off-topic, but I hope this comment does not get hidden as well. If I were the repo maintainer, I would not hide them.

For example, in #13289, the issue talks about the Spring Boot plugin behavior that includes `provided`-scoped dependencies in the repackaged JAR (not that this is a problem). As a workaround, one can use `<excludes>` to exclude these dependencies, for example. However, it is counter-intuitive that it still packages all the transitive dependencies.

**Comment by snicoll** [comment] 2020-08-17 13:58
Thanks for the report but this is the documented behaviour for now and there is already an issue to revisit the situation. 

Duplicate of #16563

**Closed by snicoll** 2020-08-17 13:58 UTC
Labels: status: waiting-for-triage
