### ISSUE TITLE
Builds are going very slow after migrating spring application to spring boot

### ISSUE THREAD

**Issue by mohit27** [spring-projects/spring-boot#15172] opened 2018-11-14 07:20 UTC
Hi All,

We have migrated our Spring MVC application to Spring boot 2 , and now Maven builds are going slow.
Builds and tests cases are taking a lot more time then older application.

Does any one suggest what can be done to tune this.

ex : 
Few modules build time comparison here
Branch before spring boot :

```
19:46:47 [INFO] dao-module ( having database logic and tests )  .................................. SUCCESS [16:55 min]
19:46:47 [INFO] service-module ( having service logic and tests )   ............................... SUCCESS [16:24 min]
19:46:47 [INFO] batch-module ( having spring batch logic and tests )  ..................................... SUCCESS [11:22 min]
```

Branch after spring boot :

```
19:21:55 [INFO] dao-module ( having database logic and tests )  .................................. SUCCESS [20:06 min] 3 min
19:21:55 [INFO] service-module ( having service logic and tests ) ............................... SUCCESS [21:09 min] 5 min
19:21:55 [INFO] batch-module ( having spring batch logic and tests ) ..................................... SUCCESS [35:23 min] 24 min
```

**Comment by wilkinsona** [comment] 2018-11-14 07:44
Thanks for the report, but it’s impossible to make any suggestions without seeing before and after examples of the change in build time as there are too many moving parts. The change could be due to a problem in Boot, a comparison that isn’t apples-to-apples, particular usage of Boot’s testing support, etc.

If you would like us to spend some time investigating, please take the time to create and share an example that reproduces the problem. That doesn’t have to be your application’s code (and ideally would not be). All we need as a minimal example that is representative of your actual code and exhibits the same change in build time.

**Comment by mohit27** [comment] 2018-11-14 08:08
@wilkinsona Thanks for reply.

Our code is huge application with large number of code and test files. With sample application it would bot be possible to showcase the difference.

My Intention was to ask does there any points need to take care while migrating application to boot which can cause slowness in build ?

**Comment by spring-issuemaster** [comment] 2018-11-21 08:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-11-28 08:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-11-28 08:32 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
