### ISSUE TITLE
[maven-plugin]Provide information on which file must exists when available when it is not the case in Repackager

### ISSUE THREAD

**Issue by apupier** [spring-projects/spring-boot#10128] opened 2017-08-31 14:50 UTC
I have this error sporadically:

> [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:repackage (default) on project camel-ose-springboot-xml: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:repackage failed: Source must refer to an existing file -> [Help 1]

it would be nice if the error message is precising if:
- there is no value for the source file (null)
- there is a value and it doesn't exist (and display what is the value)

**Comment by snicoll** [comment] 2017-08-31 15:49
Duplicate of #10128

@apupier an issue is not required if you intend to create a PR, thanks!

**Closed by snicoll** 2017-08-31 15:49 UTC
Labels: status: waiting-for-triage
