### ISSUE TITLE
Make dependency configuration easier for people using Stomp

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#4522] opened 2015-11-17 08:17 UTC
http://info.michael-simons.eu/2015/11/17/spring-4-2-x-spring-boot-and-the-stomp-broker-relay/

I'm not sure that the dependencies should go in the WebSocket starter, but a Stomp starter might be useful

**Comment by michael-simons** [comment] 2015-11-17 08:25
Stomp starter would be fine as well, sure!

**Comment by snicoll** [comment] 2018-03-23 20:56
Duplicate of #6359

**Closed by snicoll** 2018-03-23 20:56 UTC
Labels: type: enhancement
