### ISSUE TITLE
Is there any way to handle NoHandlerFoundException?

### ISSUE THREAD

**Issue by ankit8051** [spring-projects/spring-boot#6832] opened 2016-09-07 09:37 UTC
Hi Team,
I am using spring boot 1.4.0 release in my rest application and implemented **_@ControllerAdvice_** to global exception handling.

My goal is to handle the **_NoHandlerFoundException_** if no requestion mapping is available for the requested url.

I have added below properties in the properties file.

```
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

```

Here is my code for global exception handler.

```
@ControllerAdvice
public class GlobalExceptionHandlingController {

private static final transient Logger LOGGER = LoggerFactory.getLogger(GlobalExceptionHandlingController.class);

@ExceptionHandler(value = NoHandlerFoundException.class)
    public @ResponseBody ErrorJSON
    handleNoHandlerFoundException(HttpServletResponse httpResponse, Exception ex) throws Exception {
        LOGGER.error("No Handler found for request url.",ex);
        ErrorJSON errorJSON = new ErrorJSON();
        errorJSON.addError(Constants.URL_INVALID.name(),null,
        		"Invalid rest endpoint.",
        		"Invalid rest endpoint.", null);
        httpResponse.setStatus(HttpServletResponse.SC_BAD_REQUEST);
        httpResponse.setContentType("application/json");
        return  errorJSON;
    }
}	

```
It was working before i have added below property in the properties file.

`server.context-path=/payment-api`

After adding above property system always gives https status "404 Not Found" without any exception.

Please let me know if I am missing anything.

Thanks in advance.

**Comment by bclozel** [comment] 2016-09-07 09:43
I guess since you're mapping the servlet to `/payment-api/**`, your exception handler is only called if the request path starts with `/payment-api`.

I'd say this is expected behavior, and I'll close it if you confirm that `/something` gives 404 while `/payment-api` sill works.

Anyway, unless you've got a repro project demonstrating an issue, I'd open a question on StackOverflow for this.

Thanks!

**Comment by ankit8051** [comment] 2016-09-08 04:25
Yes, Brian that it was doing right now.

But I am hoping that _/something_ will also be handled by my above mechanism.

**Comment by bclozel** [comment] 2016-09-08 07:58
If it did, that should be considered as a bug, because setting the context path explicitly asks Spring to register its servlet on that path and not handle other requests, for example in case you want to deploy another servlet.

In your case, it probably means you want to prefix your REST API with some path but still want to handle all incoming requests with Spring. In that case, I wouldn't use the context path but rather annotate my Controllers with `@RequestMapping("payment-api")` or even come up with my custom meta-annotation `@PaymentApiMapping` that does use `@RequestMapping("payment-api")` itself.

If you want to limit exception handling to some Controllers, don't forget `@ControllerAdvice` allows you to specify a package or even an annotation (in your case, `@PaymentApiMapping`!) to restrict it to the Controllers you want.

Thanks!

**Closed by bclozel** 2016-09-08 07:58 UTC
Labels: feedback-provided
