### ISSUE TITLE
Provide properties to set the number of threads of spring TaskScheduler

### ISSUE THREAD

**Issue by smartwjw** [spring-projects/spring-boot#1397] opened 2014-08-19 08:31 UTC
By default, it use `Executors.newSingleThreadScheduledExecutor()` to create executor, and it only have one thread.
But when I config the executor manually:

```
    @Bean
    public ConcurrentTaskScheduler taskScheduler() {
        ConcurrentTaskScheduler taskScheduler = new ConcurrentTaskScheduler();
        taskScheduler.setScheduledExecutor(executorService());
        return taskScheduler;
    }

    @Bean
    public ScheduledExecutorService executorService() {
        ScheduledExecutorFactoryBean bean = new ScheduledExecutorFactoryBean();
        bean.setThreadNamePrefix("schedule");
        bean.setPoolSize(10);
        return bean.getObject();
    }
```

Exception occurs:

```
Exception in thread "main" java.lang.IllegalStateException: More than one TaskScheduler and/or ScheduledExecutorService  exist within the context.
```

**Comment by philwebb** [comment] 2018-03-22 15:02
Duplicate #1563.

**Comment by snicoll** [comment] 2018-08-06 08:24
That's not a duplicate of #1563 - #1563 is about `TaskExecutor` and this one is about `TaskScheduler`. Those are two completely separate contracts.

**Closed** 2018-08-16 12:56 UTC
Labels: type: enhancement
