### ISSUE TITLE
 defined error page does not work in spring boot project

### ISSUE THREAD

**Issue by 7000014349** [spring-projects/spring-boot#15367] opened 2018-12-03 05:52 UTC
Question:I want to define my own error page ,but the request to non-existent resource returned 200 instead of 404.

I define the error page in the directory :resources/static/error/404.html
when I use maven command to deploy war ,input the link to non-existent resource:
https://contractdev.azurewebsites.net/menu/init1234566
The page is a blank page,the status is 200 not 404
![capture](https://user-images.githubusercontent.com/37426005/49355432-8a794a00-f702-11e8-9668-4e85cc95c3f5.JPG)
what causes the problem and how to solve this problem

**Comment by wilkinsona** [comment] 2018-12-03 07:36
Duplicate of #15339

**Closed by wilkinsona** 2018-12-03 07:36 UTC
Labels: status: waiting-for-triage
