### ISSUE TITLE
<springProperty> in logback configurations. Error...

### ISSUE THREAD

**Issue by succour** [spring-projects/spring-boot#4959] opened 2016-01-17 10:15 UTC
I saw the commit that 
https://github.com/spring-projects/spring-boot/commit/055ace37f006120b0006956b03c7f358d5f3729f

I use the spring-cloud+spring boot.
But when I started the application, some errors are appeared.

Here's my logback-spring.xml:
![logback-spring](https://cloud.githubusercontent.com/assets/4241950/12376947/bb7dd808-bd46-11e5-8352-3218304fa976.png)

Here's the logs:

```
[16-01-17 17:58:39.140] user-service-provider [cloud-user-service-provider] [main] INFO  tv.acfun.cloud.service.user.UserServiceApplication - Starting UserServiceApplication on Succour-QG with PID 43716 (E:\AcFun\cloud-service\user-service\user-service-provider\build\classes\main started by Succour in E:\AcFun\cloud-service\user-service\user-service-provider)
[16-01-17 17:58:39.144] user-service-provider [cloud-user-service-provider] [main] INFO  tv.acfun.cloud.service.user.UserServiceApplication - No active profile set, falling back to default profiles: default
[16-01-17 17:58:39.216] user-service-provider [cloud-user-service-provider] [main] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3315d2d7: startup date [Sun Jan 17 17:58:39 CST 2016]; root of context hierarchy
[16-01-17 17:58:39.540] user-service-provider [cloud-user-service-provider] [main] INFO  org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
[16-01-17 17:58:39.568] user-service-provider [cloud-user-service-provider] [main] INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$cbd919f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[16-01-17 17:58:39.972] user-service-provider [cloud-user-service-provider] [main] INFO  tv.acfun.cloud.service.user.UserServiceApplication - Started UserServiceApplication in 1.828 seconds (JVM running for 2.841)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.1.RELEASE)

[16-01-17 17:58:40.226] appName_IS_UNDEFINED [cloud-user-service-provider] [main] INFO  org.springframework.cloud.config.client.ConfigServicePropertySourceLocator - Fetching config from server at: http://conf.cloud.acfun.tv:8888
[16-01-17 17:58:40.911] appName_IS_UNDEFINED [cloud-user-service-provider] [main] INFO  org.springframework.cloud.config.client.ConfigServicePropertySourceLocator - Located environment: name=user-service-provider, profiles=[default], label=libin, version=null
[16-01-17 17:58:40.912] appName_IS_UNDEFINED [cloud-user-service-provider] [main] INFO  org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration - Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name='http://git.acfun.tv/cloud/cloud-config.git/user-service-provider.yml'], MapPropertySource [name='http://git.acfun.tv/cloud/cloud-config.git/application.yml']]]
[16-01-17 17:58:40.924] appName_IS_UNDEFINED [cloud-user-service-provider] [main] WARN  org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration - Logging config file location 'logback-spring.xml' cannot be opened and will be ignored
```

I discoved that before spring-boot started, the ${appName} is correct. but after spring-boot started, it came to appName_IS_UNDEFINED... 
I want to know what happend...and how to resolve it..
My English is bad...Please don't mind...
Thank you very much.

**Comment by wilkinsona** [comment] 2016-01-18 16:19
@succour It works for me in a basic 1.3.1 Spring Boot app. `${appName}` is resolved correctly both before and after Spring Boot is started. If you'd like us to investigate further, please provide a small sample project that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2016-01-25 16:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-02-01 16:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-02-01 16:20 UTC
