### ISSUE TITLE
Attempting to use WebTestClient to test a Jersey-based app causes the app to switch to WebFlux

### ISSUE THREAD

**Issue by helmbold** [spring-projects/spring-boot#13521] opened 2018-06-19 07:22 UTC
Spring Boot / Jersey can not find a handler method when the application is startet and accessed from a test. If I start the application separately and access `http://localhost:8080/demo` with a browser everything is fine.

The log says: "Did not find handler method for [/demo]". The relevant logging output:

    2018-06-18 17:04:31.071 DEBUG 7628 --- [nio-8080-exec-1] o.s.web.reactive.DispatcherHandler       : Processing GET request for [http://localhost:8080/demo]
    2018-06-18 17:04:31.083 DEBUG 7628 --- [nio-8080-exec-1] s.w.r.r.m.a.RequestMappingHandlerMapping : Looking up handler method for path /demo
    2018-06-18 17:04:31.085 DEBUG 7628 --- [nio-8080-exec-1] s.w.r.r.m.a.RequestMappingHandlerMapping : Did not find handler method for [/demo]
    2018-06-18 17:04:31.087 DEBUG 7628 --- [nio-8080-exec-1] o.s.w.r.handler.SimpleUrlHandlerMapping  : Matching pattern for request [[path='/demo']] is /**

The application consists of the following classes (written in Kotlin):

Resource
   
```java
import org.springframework.stereotype.Component
import javax.ws.rs.GET
import javax.ws.rs.Path
import javax.ws.rs.core.Response

@Component
@Path("/")
class Resource {

    @GET
    @Path("demo")
    fun test() = Response.ok("Hi!").encoding("UTF-8").build()
}
```

JerseyConfig

```java
import org.glassfish.jersey.server.ResourceConfig
import org.springframework.stereotype.Component

@Component
class JerseyConfig : ResourceConfig() {

    init {
        register(Resource::class.java)
    }
}
```

App:

```java
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class App

fun main(args: Array<String>) {
    runApplication<App>(*args)
}
```

The failing test:

```java
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import org.junit.jupiter.api.extension.ExtendWith
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.junit.jupiter.SpringExtension
import org.springframework.test.web.reactive.server.WebTestClient

@ExtendWith(SpringExtension::class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
class ResourceTest {

    @Autowired
    lateinit var client: WebTestClient

    @Test
    fun getTest() {
        client.get().uri("demo").exchange().expectStatus().isOk
    }
}
```

I get the same error, if I use the Jersey client for testing:

```java
@Test
fun testWithJersey() {
    val client = ClientBuilder.newClient()
    val response = client.target("http://localhost:8080/demo").request().get()
    assertThat(response.status).isEqualTo(200)
}
```

build.gradle:

```gradle
buildscript {
    ext {
        kotlinVersion = '1.2.50'
        springBootVersion = '2.0.3.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
        classpath("org.jetbrains.kotlin:kotlin-allopen:${kotlinVersion}")
    }
}

apply plugin: 'kotlin'
apply plugin: 'kotlin-spring'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

compileKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjsr305=strict"]
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        freeCompilerArgs = ["-Xjsr305=strict"]
        jvmTarget = "1.8"
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    compile("org.jetbrains.kotlin:kotlin-reflect")
    compile('org.springframework.boot:spring-boot-starter-jersey')
    testCompile("org.springframework.boot:spring-boot-starter-test") {
        exclude group: "junit", module: "junit"
    }
    testCompile('org.springframework.boot:spring-boot-starter-webflux')
    testCompile("org.junit.jupiter:junit-jupiter-api")
    testRuntime("org.junit.jupiter:junit-jupiter-engine")
}
```

The test code itself seems to be ok, since when I replace the body of the test method with `Thread.sleep(...)` and then access the server from a browser, I get the same error (404 due to "Did not find handler method for [/demo]").

**Comment by wilkinsona** [comment] 2018-06-19 07:36
I suspect the problem is the test dependency on the WebFlux starter. I suspect it will cause the tests to auto-configure WebFlux which then clashes with Jersey. As requested by @snicoll, a sample that we can clone and run will allow us to verify.

**Comment by helmbold** [comment] 2018-06-19 08:20
I get the same error without the WebFlux dependency.

I've created an [example](https://github.com/helmbold/jerseydemo).

**Comment by snicoll** [comment] 2018-06-19 08:28
> I get the same error without the WebFlux dependency.

Something is very weird in your sample. You're still using `WebTestClient` and that definitely requires WebFlux.

**Comment by wilkinsona** [comment] 2018-06-19 08:37
You get the same problem on the command line if you upgrade Gradle to a version that supports JUnit Jupiter and configure the test task to use it.

**Comment by wilkinsona** [comment] 2018-06-19 09:41
Thanks for following up. I think that makes this a duplicate of https://github.com/spring-projects/spring-boot/issues/12973. I'll add some details to that issue describing this particular variant of the problem.

**Comment by wilkinsona** [comment] 2018-06-19 09:44
As I was writing things up on #12973, a came to the conclusion that this is probably a bug. In 2.0.x when both Spring MVC and WebFlux are on the classpath, we favour Spring MVC. For consistency I think we should do the same for Jersey. If we did so, adding the test dependency on `spring-boot-starter-webflux` would allow you to use `WebTestClient` while still having the application use Jersey rather than unexpectedly flipping to a WebFlux-based stack.

**Comment by helmbold** [comment] 2018-06-20 07:00
Is there some log statement I've overlooked that explains what was going on? If not, I'd suggest to issue a warning.

**Comment by snicoll** [comment] 2018-06-20 07:10
@helmbold that issue has been reopened and we intend to fix something so that your sample just works.

**Closed** 2018-06-20 09:12 UTC
Labels: type: bug
