### ISSUE TITLE
@AutoConfigureMockMvc with @EnableResourceServer seems to be broken

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#8329] opened 2017-02-19 11:09 UTC
The app starts up fine and works, but tests with `@AutoConfigureMockMvc` fail like this:

```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.provider.token.ResourceServerTokenServices' available: expected single matching bean but found 3: remoteTokenServices,consumerTokenServices,defaultAuthorizationServerTokenServices
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1041) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
```

A sample you can try this with: https://github.com/spring-guides/tut-spring-boot-oauth2/tree/master/auth-server. Here's the test that fails:

```
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest
@AutoConfigureMockMvc
public class SocialApplicationTests {
	
	@Test
	public void contextLoads() throws Exception {
	}

}
```

**Comment by wilkinsona** [comment] 2017-02-19 22:03
There are three beans involved:

 - `consumerTokenServices`
- `defaultAuthorizationServerTokenServices`
 - `remoteTokenServices`

All three are present in the context in both cases. Without `@AutoConfigureMockMvc`, only `remoteTokenServices` is found as a type match for `ResourceServerTokenServices`. With `@AutoConfigureMockMvc`, all three beans match `ResourceServerTokenServices`.

`remoteTokenServices` is the only bean where the definition reveals that the bean is an instance `ResourceServerTokenServices` – the `remoteTokenServices` bean method returns `RemoteTokenServices` which implements `ResourceServerTokenServices`. The `consumerTokenServices` and `defaultAuthorizationServerTokenServices` bean methods return `ConsumerTokenServices` and `AuthorizationServerTokenServices` both of which are plain interfaces, revealing no further type information.

During start up in both cases, `remoteTokenServices` is cached as the name of the only bean that implements `ResourceServerTokenServices`. In the working case, this cache entry persists until after `SsoSecurityConfigurer` attempts to retrieves a single `ResourceServerTokenServices` bean. In the failing case, the cache entry is cleared when `SpringBootMockMvcBuilderCustomizer.DeferredLinesWriter` registers itself as a singleton. This happens before `SsoSecurityConfigurer` attempts to retrieves a single `ResourceServerTokenServices` bean and it fails because it finds all three beans. All three beans are found at this point as they have been instantiated and, therefore, more type information is available.

This problem can be created without `@AutoConfigureMockMvc` and also without Spring Boot:

```java
package com.example;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;
import org.springframework.security.oauth2.provider.token.ResourceServerTokenServices;

@EnableAuthorizationServer
@EnableWebSecurity
public class BrokenOAuthApplication extends AuthorizationServerConfigurerAdapter {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(BrokenOAuthApplication.class);
		context.getBeanFactory().registerSingleton("test", "Test");
		context.getBean(ResourceServerTokenServices.class);
	}

}
```

@dsyer I think this needs to be fixed in Spring Security OAuth. Can you please open an issue over there. I'll close this one for now. If it turns out we need to do something in Boot as well once a fix is in place in Spring Security OAuth we can reopen.

**Comment by dsyer** [comment] 2017-02-19 22:26
Great analysis, thanks. Reopening until there is a thread to follow somewhere else.

**Comment by dsyer** [comment] 2017-02-21 08:34
I think maybe some strange choices have been made in the OAuth2 project (there are 3 flavours of `TokenServices` and only one of them is designed for extension by the user setting up a `@Bean`, which is what we do in Spring Boot). Probably the way that Spring resolves the beans has changed since that was implemented even. It's hard to justify a change there now though - it's always been like that for one thing - and the problem manifests itself in a way that seems very specific to the MockMvc setup in Spring Boot, so I'd rather look for a solution here really.

**Comment by wilkinsona** [comment] 2017-02-21 09:17
> the problem manifests itself in a way that seems very specific to the MockMvc setup in Spring Boot, so I'd rather look for a solution here really.

As I've [shown above](https://github.com/spring-projects/spring-boot/issues/8329#issuecomment-280953128) that's demonstrably not the case. The problem can be reproduced with no involvement at all from Boot. Anything the registers a singleton after `ResourceServerTokenServices` has been looked up by type will break Spring Security OAuth.

> It's actually the combination of `@EnableOAuth2Sso` and `@EnableAuthorizationServer` in the same app that pushes this over the line into a state where you can't use `@AutoConfigureMockMvc`

That's not the case. I can reproduce this with `BrokenOAuthApplication` from above and this test class:

```java
package com.example;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.oauth2.provider.token.ResourceServerTokenServices;
import org.springframework.test.context.junit4.SpringRunner;

@AutoConfigureMockMvc
@SpringBootTest(classes=BrokenOAuthApplication.class)
@RunWith(SpringRunner.class)
public class BrokenOAuthApplicationTests {

	@Autowired
	private ResourceServerTokenServices tokenServices;

	@Test
	public void contextLoads() {

	}

}
```

> the problem manifests itself in a way that seems very specific to the MockMvc setup in Spring Boot

The problem manifests itself whenever a singleton is registered programatically. `@AutoConfigureMockMvc` is one example of something that does so, but there may be many others. Any change in Boot will be a point solution (the probably makes Boot more complex than it needs to be) and that leaves the underlying problem in place to cause difficulties for others.

> , so I'd rather look for a solution here really.

I'd rather that it was fixed at source so that everyone can benefit rather

**Comment by wilkinsona** [comment] 2017-02-21 11:40
You don't even need to register a singleton. This blows up too:

```java
package com.example;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;
import org.springframework.security.oauth2.provider.token.ResourceServerTokenServices;

@EnableAuthorizationServer
@EnableWebSecurity
public class BrokenOAuthApplication extends AuthorizationServerConfigurerAdapter {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(BrokenOAuthApplication.class);
		context.getBean(ResourceServerTokenServices.class);
		context.close();
	}

}
```

I've opened https://github.com/spring-projects/spring-security-oauth/issues/984.

**Closed by wilkinsona** 2017-02-21 11:40 UTC
