### ISSUE TITLE
Freemarker and content type

### ISSUE THREAD

**Issue by JulianWorldline** [spring-projects/spring-boot#6210] opened 2016-06-23 14:42 UTC
When I set "application/xml" or "application/voicexml+xml" in the property spring.freemarker.content-type, I have an error :
javax.servlet.ServletException: Circular view path [XXX]: would dispatch back to the current handler URL [/YYY/XXX] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)

If I don't set this property, I work.

**Comment by wilkinsona** [comment] 2016-06-23 14:51
You haven't given us a lot to go on, for example you haven't even said which version of Spring Boot you're using. I just tried it with our Freemarker sample and it appears to work. If you'd like us to spend some time investigating your problem, please take the time to accurately describe what you're doing. A sample project that reproduces your problem would be ideal.

**Comment by JulianWorldline** [comment] 2016-06-23 15:28
Sorry. I test in 1.3.5-RELEASE and 1.4.0.M3 versions.
My freemarker configurations is : 
```
  freemarker.suffix: .vxml
  freemarker.template-loader-path: /templates/
  freemarker.content-type: application/xhtml+xml
  freemarker.charset: ISO-8859-1
```

I call a spring controller and return a object which extends ModelAndView class to respond on vxml page : 

**DynamicController.java**
```
@RestController
@RequestMapping(value = "/dynamic")
public class DynamicController {

    private static final Logger LOGGER = LoggerFactory.getLogger(DynamicController.class);

    @Autowired
    private GiftManager manager;

    @RequestMapping(value = "/initApplication", method = RequestMethod.GET)
    @ResponseStatus(HttpStatus.OK)
    public ModelAndView initApplication(@RequestParam(value = "sessionId") String sessionId) throws IOException {
        Assert.hasLength(sessionId, MessageFormat.format("''{0}'' is not a valid ressource (null or empty)", sessionId));
        LOGGER.trace("Input initApplication (sessionId:{})", sessionId);

        DefaultModelAndView genericResponse = new DefaultModelAndView("initApplication");
        genericResponse.setResponseContext(new ResponseContext.Builder().setHttpStatus(HttpStatus.OK).build());
        genericResponse.addElementToContent("sessionId", sessionId);
        return genericResponse;
    }
```

**DefaultModelAndView.java**
```
public class DefaultModelAndView extends ModelAndView {

    public static final String RESPONSE_CONTEXT_NAME = "responseContext";
    public static final String CONTENT_NAME = "content";
    public static final String JSON_HELP = "JsonHelper";
    public static final String STRING_ESCAPE_UTILS = "StringEscapeUtils";

    private final Map<String, Object> elements = new HashMap<String, Object>();

    public DefaultModelAndView(String templateName) {
        super(templateName);
        super.addObject(JSON_HELP, JsonHelper.class);
        super.addObject(STRING_ESCAPE_UTILS, StringEscapeUtils.class);
        super.addObject(RESPONSE_CONTEXT_NAME, new ResponseContext(HttpStatus.INTERNAL_SERVER_ERROR));

    }
```

**initApplication.vxml**
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<vxml version="2.1" xmlns="http://www.w3.org/2001/vxml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3.org/2001/vxml http://www.w3.org/TR/voicexml21/vxml.xsd" application="/static/root/application.vxml">

    <form id="helloTestFreeMaker">
        <block>
            <log>${responseContext.httpStatus}, ${content.sessionId}</log>
        </block>
    </form>
</vxml>
```

**Comment by bclozel** [comment] 2016-06-24 13:10
First, it seems that there are a few typos in your properties file (missing `spring` prefixes) and that you redefined keys with their default values, so I removed those:

```properties
spring.freemarker.suffix=.vxml
spring.freemarker.content-type=application/xhtml+xml
spring.freemarker.charset=ISO-8859-1
```

Also, the Controller is returning a view, so it should be a `@RestController`. I also find a bit strange to do that dance with the `ModelAndView` when you can just return the view name and add things to the model.
You can also check `@ModelAttributes` methods in `@ControllerAdvice` components in the Spring reference documentation if you wish to add some "context" to the model.

```java
@Controller
@RequestMapping("/dynamic")
public class DynamicController {

	private static final Logger LOGGER = LoggerFactory.getLogger(DynamicController.class);

	@RequestMapping("/initApplication")
	public String initApplication(
			@RequestParam(value = "sessionId") String sessionId,
			Model model) throws IOException {
		Assert.hasLength(sessionId, MessageFormat.format("''{0}'' is not a valid ressource (null or empty)", sessionId));
		LOGGER.trace("Input initApplication (sessionId:{})", sessionId);
		model.addAttribute("sessionId", sessionId);
		return "initApplication";
	}

}
```

Note that you can also add infrastructure stuff in your model by customizing the attributes map in the view resolver like this, instead of inheriting from `ModelAndView` and defining your own:

```java
@Component
public class FreemarkerViewResolverCustomizer {

	private final FreeMarkerViewResolver viewResolver;

	@Autowired
	public FreemarkerViewResolverCustomizer(FreeMarkerViewResolver viewResolver) {
		this.viewResolver = viewResolver;
	}

	@PostConstruct
	public void customizeViewResolver() {
		Map<String, Object> attributesMap = new HashMap<>();
		// things to be added to all model instances
		this.viewResolver.setAttributesMap(attributesMap);
	}

}
```

Now I believe the core issue is that when resolving the `"initApplication"`, you're getting two candidate views. The first is the Freemarker view and the second is backed by the `InternalResourceViewResolver` (usually for JSPs) with the same file. Your Freemarker view has the content-type `"application/xhtml+xml"` while the other one is `"text/html"`. So the internal view is selected, throws an error while rendering, etc.

Your client is probably sending an Accept header which is something like `"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"`. When trying to find the best view, the first content-type is selected and so is the first view.

Here are a few ideas:

* make sure that your HTTP client is asking for `"application/xhtml+xml"` only/in priority, by configuring it or by adding a Servlet filter to change the incoming request headers
* prevent the `InternalResourceViewResolver` from being registered in the first place, although I don't see an obvious way to do that at the moment. It's also a bad idea to do that if you're using JSPs in your application.

Was this working in a previous Spring Boot version?

**Comment by JulianWorldline** [comment] 2016-06-24 13:55
Thanks for this explicaiton;
I confirm I have the spring prefix in my freemarker keys.

My real content-type is : application/voicexml+xml (I test with application/xhtml+xml too because voicexml+xml is not known).
We have a server which use this content-type to run. 

In my configuration, I have : 
```
@Configuration
public class WebConfig implements EmbeddedServletContainerCustomizer {

    @Override
    public void customize(ConfigurableEmbeddedServletContainer container) {
        MimeMappings mappings = new MimeMappings(MimeMappings.DEFAULT);
        mappings.add("vxml", "application/voicexml+xml");
        container.setMimeMappings(mappings);
    }
}
```

I merge my project to spring boot, so my configuration never run in spring boot.

**Comment by bclozel** [comment] 2016-06-24 14:00
What about setting this at the MVC level instead of the container itself?

```properties
spring.mvc.media-types.vxml="application/voicexml+xml"
```

**Comment by bclozel** [comment] 2016-06-24 14:17
Since it seems there's no bug related to Spring Boot itself, I'm closing this issue.
Feel free to ask a question on StackOverflow once you've narrowed down the scope of your issue, or to re-open this if you've got a clear repro project demonstrating a problem with Boot.

Thanks!

**Closed by bclozel** 2016-06-24 14:17 UTC
Labels: feedback-provided
