### ISSUE TITLE
Enhancement: give classloader precedence to BOOT_INF/classes over BOOT_INF/lib

### ISSUE THREAD

**Issue by MrBuddyCasino** [spring-projects/spring-boot#12263] opened 2018-02-27 16:47 UTC
It is very hard to override/patch classes of dependencies right now. See https://dzone.com/articles/spring-boot-classloader-and-class-override for details.

If the /classes got precedence, it would suddenly get very easy. Is there a chance we get that?

**Comment by wilkinsona** [comment] 2018-02-27 16:59
It's already available in 2.0 RC2. Duplicate of https://github.com/spring-projects/spring-boot/issues/11696.

**Closed by wilkinsona** 2018-02-27 16:59 UTC
Labels: status: waiting-for-triage
