### ISSUE TITLE
@WebMvcTest should register PageableHandlerMethodArgumentResolver

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#13730] opened 2018-07-09 01:42 UTC
I tried to return a `Page`  from my controller and wrote a `@WebMvcTest` tests, and inject a `MockMvc`, I found it does not work as expected.

I have to switch `@SpringBootTest` and use `MockMVcBuilders` to  register `PageableHandlerMethodArgumentResolver` and build a `MockMvc` manually  to make it work.

**Comment by wilkinsona** [comment] 2018-07-09 05:33
Duplicate of #13066

**Closed** 2018-07-09 05:33 UTC
Labels: status: waiting-for-triage
