### ISSUE TITLE
JAR produced of bootJar has SLF4J conflict at runtime with Gradle 5.0-rc-1

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-boot#15133] opened 2018-11-08 15:37 UTC
When I use _Gradle 5.0-rc-1_ and _Spring Boot 2.1.0.RELEASE_ I get the following stacktrace with the JAR file produced by `gradle bootJar`:

```
> java -jar build/libs/kunde-1.0.jar --spring.profiles.active=dev
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/ziju0001/IdeaProjects/kunde1/build/libs/kunde-1.0.jar!/BOOT-INF/lib/gradle-api-5.0-rc-1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/ziju0001/IdeaProjects/kunde1/build/libs/kunde-1.0.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext loaded from jar:file:/C:/Users/ziju0001/IdeaProjects/kunde1/build/libs/kunde-1.0.jar!/BOOT-INF/lib/gradle-api-5.0-rc-1.jar!/). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext
        at org.springframework.util.Assert.instanceCheckFailed(Assert.java:655)
        at org.springframework.util.Assert.isInstanceOf(Assert.java:555)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:286)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:102)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:217)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:196)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at de.hska.kunde.ApplicationKt.main(Application.kt:64)
        ... 8 more
```

**Comment by wilkinsona** [comment] 2018-11-08 18:49
The problem's occurring because Gradle's API jar is packaged in your Boot jar and it contains an SLF4J binding. By default, `bootJar` packages everything on the runtime classpath of the main source set. This shouldn't include Gradle's API by default and the only way I've been able to reproduce the problem is by adding a dependency on the API:

```
dependencies {
    compile gradleApi()
    // …
}     
```

The application then fails to start with the same exception as shown above, and that is to be expected. The same behaviour also occurs with Gradle 4.10.2 so this isn't something, as far as I can tell, that has changed in Gradle 5.

In the absence of a sample that provides evidence to the contrary, I'm going to close this issue as it appears to be due to user error. If you disagree, please provide a minimal sample that reproduces the problem and we can re-open this issue and take another look.

**Closed by wilkinsona** 2018-11-08 18:49 UTC
Labels: status: waiting-for-triage
