### ISSUE TITLE
Issue when using actuator health endpoint reporting UP on the non-default port before the main spring application context is ready

### ISSUE THREAD

**Issue by mbazos** [spring-projects/spring-boot#16405] opened 2019-04-02 02:34 UTC
Seems like there could be an issue when running the actuator management server on a different port than the one running to serve application traffic. Basically when configuring the following property:
```
management.server.port=8081
```

You will see in the logs below that there are two `WebApplicationContext`'s created one for the application and one for the management port. The problem I ran into seems to be the following:
If you don't add any additional health indicators to your application and you have the management endpoint configured on a different port it will report `UP` when the context running on port 8080 might not be ready for traffic.

Logs (based on a vanilla spring boot initializer project with spring-mvc and actuator configured on a different port)
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2019-04-01 22:03:28.349  INFO 51884 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication on CT1-88728-M with PID 51884 (/Users/mbazos/Downloads/demo/target/classes started by mbazos in /Users/mbazos/Downloads/demo)
2019-04-01 22:03:28.353  INFO 51884 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to default profiles: default
2019-04-01 22:03:29.341  INFO 51884 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2019-04-01 22:03:29.358  INFO 51884 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-04-01 22:03:29.358  INFO 51884 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2019-04-01 22:03:29.363  INFO 51884 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/mbazos/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2019-04-01 22:03:29.412  INFO 51884 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-04-01 22:03:29.412  INFO 51884 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1000 ms
2019-04-01 22:03:29.677  INFO 51884 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-04-01 22:03:30.027  INFO 51884 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2019-04-01 22:03:30.028  INFO 51884 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-04-01 22:03:30.028  INFO 51884 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2019-04-01 22:03:30.038  INFO 51884 --- [           main] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring embedded WebApplicationContext
2019-04-01 22:03:30.038  INFO 51884 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 59 ms
2019-04-01 22:03:30.055  INFO 51884 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 15 endpoint(s) beneath base path '/actuator'
2019-04-01 22:03:30.114  INFO 51884 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2019-04-01 22:03:30.123  INFO 51884 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2019-04-01 22:03:30.126  INFO 51884 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 2.031 seconds (JVM running for 2.611)
```

The fix that worked was to add to the default `org.springframework.boot.actuate.health.ApplicationHealthIndicator` an application listener `ApplicationReadyEvent` for the default health to only report `UP` when it's received the ApplicationReadyEvent. This will allow the management endpoint to be served up on a different port but report `DOWN` until `ApplicationReadyEvent` is fired. If this seems like a reasonable fix I can work on a pull request:

```
package org.springframework.boot.actuate.health;

import org.springframework.boot.actuate.health.AbstractHealthIndicator;
import org.springframework.boot.actuate.health.Health;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.ApplicationListener;

public class ApplicationHealthIndicator extends AbstractHealthIndicator implements ApplicationListener<ApplicationReadyEvent> {

    private volatile boolean ready;

    public ApplicationHealthIndicator() {
        super("Application health check failed");
    }

    @Override
    protected void doHealthCheck(Health.Builder builder) {
        if (ready) {
            builder.up();
        } else {
            builder.down();
        }
    }

    @Override
    public void onApplicationEvent(ApplicationReadyEvent applicationReadyEvent) {
        this.ready = true;
    }
}

```

**Comment by wilkinsona** [comment] 2019-04-02 06:06
Duplicate of #15378.

**Closed by wilkinsona** 2019-04-02 06:06 UTC
Labels: status: waiting-for-triage

**Comment by mbazos** [comment] 2019-04-02 13:39
Thanks for the quick reply.
