### ISSUE TITLE
spring-boot-gradle-plugin does not work with gradle-dependency-lock-plugin

### ISSUE THREAD

**Issue by marvertin** [spring-projects/spring-boot#8875] opened 2017-04-10 09:13 UTC
Spring-boot-gradle-plugin unconditionally apply dependency-management-plugin.
But the dependency-management-plugin is in conflict with gradle-dependency-lock-plugin. I would like to use the later one.

I suggest to introduce option for spring-boot-gradle-plugin which switch off applying the dependency-management-plugin.

I am using spring boot 2.0.0. [Test case is here](https://github.com/marvertin/nebula-dependency-lock-not-work-withspringboot).

**Comment by wilkinsona** [comment] 2017-04-10 09:23
Your sample project is using Spring Boot 1.5.2. The option you are requesting is available in Spring Boot 2.0 snapshots and is a duplicate of #3164.

**Closed by wilkinsona** 2017-04-10 09:23 UTC
Labels: status: waiting-for-triage
