### ISSUE TITLE
Create a cache actuator endpoint.

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-boot#2625] opened 2015-03-10 15:27 UTC
Hi,

I'd like to have a `/cache` actuator endpoint that will list all the cache regions will all the statistics for each cache region. More specifically:

```
GET /cache
[{
  "id" : "simpleCMSWidgetData",
  "stats" : {
    "AverageGetTime" : 0.0,
    "CacheHitPercentage" : 77.27273,
    "CacheEvictions" : 0,
    "AverageRemoveTime" : 0.0,
    "CacheMisses" : 30,
    "AveragePutTime" : 35.89833,
    "CacheMissPercentage" : 22.727274,
    "CacheHits" : 102,
    "CacheRemovals" : 0,
    "CachePuts" : 30,
    "CacheGets" : 132
  }
}, {
  "id" : "productData",
  "stats" : {
    "AverageGetTime" : 0.0,
    "CacheHitPercentage" : 50.0,
    "CacheEvictions" : 0,
    "AverageRemoveTime" : 0.0,
    "CacheMisses" : 1,
    "AveragePutTime" : 33.119,
    "CacheMissPercentage" : 50.0,
    "CacheHits" : 1,
    "CacheRemovals" : 0,
    "CachePuts" : 1,
    "CacheGets" : 2
  }
} ]
```

and 

```
GET /cache/productData
{
  "id" : "productData",
  "stats" : {
    "AverageGetTime" : 0.0,
    "CacheHitPercentage" : 50.0,
    "CacheEvictions" : 0,
    "AverageRemoveTime" : 0.0,
    "CacheMisses" : 1,
    "AveragePutTime" : 33.119,
    "CacheMissPercentage" : 50.0,
    "CacheHits" : 1,
    "CacheRemovals" : 0,
    "CachePuts" : 1,
    "CacheGets" : 2
  }
}
```

and 

```
DELETE /cache
```

would clear all the cache

and 

```
DELETE /cache/productData
```

would clear the given cache region.

**Comment by snicoll** [comment] 2015-03-10 15:55
I think @olivergierke has some concerns regarding `DELETE` on a Collection.

**Comment by philwebb** [comment] 2015-03-17 06:11
@paranoiabla What cache library do you currently use?

**Comment by paranoiabla** [comment] 2015-03-17 10:31
@philwebb I use jcache abstraction, but underneath is hazelcast.

**Comment by snicoll** [comment] 2015-04-16 09:55
So we have added the cache metrics in the actuator as part of #2633 - As far as the management endpoint to actually clear caches, I am not sure how we would do that.

**Comment by maximede** [comment] 2015-12-09 21:49
Hello, I just created a WIP branch for the clear cache endpoint. ( see https://github.com/maximede/spring-boot/commit/77ebbd17fcd2bac5e589f6acba8fd5228861b5c7 ) 
It still needs a bit of work ( like showing all the cleared cache in the response, adding a few test) but I wanted to see if this was something that could be useful (it would be for me) , and if it's the correct way to do it.

I'm basically calling ```cache.clear()``` on all available caches. It should work with any cache who implement ```org.springframework.cache.Cache#clear```

A nice improvement would be to be able to choose which cache(s) we want to clear.

Let me know what you think

**Comment by maximede** [comment] 2016-02-03 20:50
Any insight about my commit ?

**Comment by snicoll** [comment] 2018-03-22 15:16
Duplicate of #12216

**Closed by snicoll** 2018-03-22 15:16 UTC
Labels: type: enhancement

**Comment by cdalexndr** [comment] 2021-03-03 17:46
Missing documentation for this feature: https://docs.spring.io/spring-boot/docs/2.4.3/reference/html/production-ready-features.html#production-ready-endpoints
Is it still present in recent versions?

**Comment by snicoll** [comment] 2021-03-03 17:49
I don't understand any of that. The link you provided has an entry for the cache endpoint. This section links to additional details for each endpoint including the caches endpoint: https://docs.spring.io/spring-boot/docs/2.4.3/actuator-api/htmlsingle/#caches

**Comment by cdalexndr** [comment] 2021-03-03 17:58
@snicoll I opened docs from [Spring Boot Reference Documentation](https://docs.spring.io/spring-boot/docs/2.4.3/reference/html/ ) where is only one entry for [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/2.4.3/reference/html/production-ready-features.html#production-ready) so I thought it contains the whole docs for actuator.
Didn't bother to read through whole docs, so I searched `cache` keyword and didn't found any info about this feature.
It seems that there are more stacked doc pages, thanks.
