### ISSUE TITLE
The FileNotFoundException thrown from StandardJarScanner when using layered JARs isn't very helpful

### ISSUE THREAD

**Issue by maxxedev** [spring-projects/spring-boot#23139] opened 2020-08-30 22:18 UTC
Given a spring-boot application with jsp and layered jar, starting it according to blog post instructions produces FileNotFoundException from Tomcat's StandardJarScanner:

```
2020-08-30 15:07:26.578  WARN 16958 --- [           main] o.a.tomcat.util.scan.StandardJarScanner  :
Failed to scan [file:/path/to/spring-petclinic/target/bug-report/HikariCP-3.4.5.jar] from classloader hierarchy
java.io.FileNotFoundException: /path/to/spring-petclinic/target/bug-report/HikariCP-3.4.5.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_242]
        at java.util.zip.ZipFile.<init>(ZipFile.java:230) ~[na:1.8.0_242]
        at java.util.zip.ZipFile.<init>(ZipFile.java:160) ~[na:1.8.0_242]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_242]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_242]
        at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:221) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:383) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.util.scan.StandardJarScanner.processURLs(StandardJarScanner.java:318) [tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.util.scan.StandardJarScanner.doScanClassPath(StandardJarScanner.java:270) [tomcat-embed-core-9.0.37.jar:9.0.37]
```

Tested under: spring-petclinic with spring-boot 2.3.3 release.
You can find a [reproducible example here](https://github.com/maxxedev/spring-petclinic/commit/11e59e3b5387452b2570f6cb8a2858b28ce4ad8b). Run test.sh script

The problem appears to be that `JarLauncher` adds entries from classpath.idx:
```
file:/path/to/spring-petclinic/target/bug-report/BOOT-INF/classes/
file:/path/to/spring-petclinic/target/bug-report/BOOT-INF/lib/HdrHistogram-2.1.12.jar
file:/path/to/spring-petclinic/target/bug-report/BOOT-INF/lib/HikariCP-3.4.5.jar
[...]
file:/path/to/spring-petclinic/target/bug-report/HdrHistogram-2.1.12.jar
file:/path/to/spring-petclinic/target/bug-report/HikariCP-3.4.5.jar
```

**Comment by maxxedev** [comment] 2020-08-30 22:20
blog posts:
https://spring.io/blog/2020/01/27/creating-docker-images-with-spring-boot-2-3-0-m1
https://spring.io/blog/2020/08/14/creating-efficient-docker-images-with-spring-boot-2-3

**Comment by philwebb** [comment] 2020-08-31 17:07
JSPs [cannot be used with JAR files](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-jsp-limitations) and unfortunately layered wars are not yet supported (issue #22195 is tracking that request).

The current error message isn't very helpful, so I'd like to dig into it a little more to see if we can't provide something better.

**Comment by aprantl** [comment] 2020-09-10 13:27
I am having this issue too since updating to 2.3.3. It actually does not only affect layered JARs. I get the same warning messages in the log once the (layered or non-layered) JAR is exploded and executed with `java org.springframework.boot.loader.JarLauncher --cp my-application-root`. According to the message `BOOT-INF\lib` is missing in the URL path lookup. The warn If I execute the JAR directly, there are no warnings.

**Comment by scottfrederick** [comment] 2021-01-06 19:37
The root cause of this issue was identified by @wilkinsona in [a separate issue](https://github.com/spring-projects/spring-boot/issues/24192#issuecomment-729563423). The [output from the provided sample app](https://github.com/maxxedev/spring-petclinic/commit/11e59e3b5387452b2570f6cb8a2858b28ce4ad8b#diff-61a34d2eb8b46c49bf1c4cf94166054d12b0769a8464dda7b4c5e244e33ce149R37-R39) shows the same duplicate entries for each jar in the classloader, with a valid jar entry in `BOOT-INF/lib/` and an invalid entry pointing to the local file system.

**Comment by scottfrederick** [comment] 2021-01-06 19:44
Closing this as a duplicate of #24192 since the other issue identifies the root cause.

**Closed by scottfrederick** 2021-01-06 19:44 UTC
Labels: type: bug
