### ISSUE TITLE
build-image with reactor-tools

### ISSUE THREAD

**Issue by driverpt** [spring-projects/spring-boot#25122] opened 2021-02-05 17:37 UTC
Hey team, i don't know if this is the expected behaviour, but I'm getting the following error:

```
ERROR  [main][o.s.boot.SpringApplication] Application run failed
java.lang.RuntimeException: Failed to init Reactor's debug agent
	at org.springframework.boot.reactor.DebugAgentEnvironmentPostProcessor.postProcessEnvironment(DebugAgentEnvironmentPostProcessor.java:52)
```

The container is being built with the default build pack

```
mvn spring-boot:build-image
```

Is this a bug?

Thanks

**Comment by philwebb** [comment] 2021-02-05 18:36
@driverpt Do you have complete stacktrace that you can add? I'm curious what was the cause of the failure.

Even better would be a sample application that shows the problem.

**Comment by driverpt** [comment] 2021-02-07 12:47
Hey, yes, here it is

```
ERROR  [main][o.s.boot.SpringApplication] Application run failed
java.lang.RuntimeException: Failed to init Reactor's debug agent
	at org.springframework.boot.reactor.DebugAgentEnvironmentPostProcessor.postProcessEnvironment(DebugAgentEnvironmentPostProcessor.java:52)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:203)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:191)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:212)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at <package>.<Application>.main(<Application>.java:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.reactor.DebugAgentEnvironmentPostProcessor.postProcessEnvironment(DebugAgentEnvironmentPostProcessor.java:49)
	... 33 common frames omitted
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:602)
	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:586)
	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:538)
	at reactor.tools.shaded.net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:515)
	at reactor.tools.agent.ReactorDebugAgent.init(ReactorDebugAgent.java:56)
	... 38 common frames omitted
```

Current Maven Configuration:
```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <name>.....omitted.....</name>
                    </image>
                    <layers>
                        <enabled>true</enabled>
                    </layers>
                    <excludeDevtools>true</excludeDevtools>
                    <excludes>
                        <exclude>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
```

and using the Layered Jar Dockerfile as in the Reference Manual:

```
FROM adoptopenjdk:11-jre-hotspot as builder
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM adoptopenjdk:11-jre-hotspot
COPY --from=builder dependencies/ ./
COPY --from=builder spring-boot-loader/ ./
COPY --from=builder snapshot-dependencies/ ./
COPY --from=builder application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
```

**Comment by bclozel** [comment] 2021-02-07 20:35
Looks similar to https://github.com/reactor/BlockHound/issues/151

**Comment by driverpt** [comment] 2021-02-08 09:02
We're not using Blockhound in Production

**Comment by wilkinsona** [comment] 2021-02-08 09:06
@driverpt That doesn't matter. The point is that the underlying failure is the same in each case and the Blockhound issue explains the likely cause:

> Yes, since Liberica's JVM comes with the attachment module removed, you need to add the JNA dependency for ByteBuddy's self attachment implementation

If that is the problem, it also describes the solution which is to add a dependency on `net.java.dev.jna:jna`.

**Comment by driverpt** [comment] 2021-02-08 09:37
Will this also cause issues with NewRelic Agent ?

**Comment by wilkinsona** [comment] 2021-02-08 09:57
You'd have to ask New Relic. It entirely depends on how New Relic's agent attaches to the JVM.

Please let us know if adding the JNA dependency addresses your problem with `reactor-tools`. If it doesn't, and you would like us to spend some more time investigating, please provide a complete and minimal example that reproduces the problem.

**Comment by driverpt** [comment] 2021-02-08 10:58
How can we add NewRelic to `spring-boot:build-image` target ?

**Comment by scottfrederick** [comment] 2021-02-08 15:35
Attaching an agent to the JVM is typically done using a buildpack. Paketo includes an [Azure Application Insights Buildpack](https://github.com/paketo-buildpacks/azure-application-insights) and a [Google Stackdriver Buildpack](https://github.com/paketo-buildpacks/google-stackdriver) that do the setup for those APM solutions. The best way to add the NewRelic agent would be to use the same pattern to download, install, and configure the agent in a buildpack.

**Comment by spring-projects-issues** [comment] 2021-02-15 18:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-02-22 18:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-02-22 18:02 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
