### ISSUE TITLE
Can't run app with devtools and java 9

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#7565] opened 2016-12-05 12:04 UTC
```
Exception in thread "main" java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader (in module: java.base) cannot be cast to java.net.URLClassLoader (in module: java.base)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:93)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:56)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:137)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:528)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartedEvent(RestartApplicationListener.java:68)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:63)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at demo.ConfigServerApplication.main(ConfigServerApplication.java:12)
```

**Comment by snicoll** [comment] 2016-12-05 12:31
I am not too surprised. Would it be ok to close this one as a duplicate of #7226?

**Comment by dsyer** [comment] 2016-12-05 12:41
It's not really the same issue is it? I don't need to build Spring Boot to run an app with Java 9.

**Comment by dsyer** [comment] 2016-12-05 12:41
I have other Java 9 issues. Should I pile them all in here? Here's another:

```
aused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:999)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:172)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:539)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:79)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:441)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:477)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:129)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:96)
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:31)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$LocalValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:441)
```

**Comment by snicoll** [comment] 2016-12-05 12:47
> It's not really the same issue is it?

Well, if the code does not even compile with JDK9 and all the tests aren't passing I am not sure it makes much sense to pretend you can use it at runtime. That first exception is actually thrown  by a test failure with the JDK9 build (well we're not going that far OOTB yet because of the remote debug port discovery).

**Comment by dsyer** [comment] 2016-12-05 12:50
There are all sorts of reasons why the project build might be broken with Java 9 that do not affect the ability to run apps. I suppose if we fix #7226 you might expect it will be easier to fix this one, but it doesn't have to be the only way to support Java 9.

**Comment by snicoll** [comment] 2016-12-05 12:54
It's a duplicate effort IMO and I really see no benefit to have that in two places.

**Closed** 2016-12-05 12:55 UTC

**Comment by Glamdring** [comment] 2017-10-03 07:45
Running spring boot 2.0.0.RC4 and the issue still persists.

**Comment by snicoll** [comment] 2017-10-03 07:55
@Glamdring there's no such thing as `2.0.0.RC4`. Please look at the linked issue (there is a reference in this very issue). And try a SNAPSHOT or wait for `2.0.0.M5`.

**Comment by Glamdring** [comment] 2017-10-03 14:23
@snicoll sorry, meant M4. Ok, will wait, it's not a showstopper

**Comment by Usualminds** [comment] 2018-03-22 10:09
is this question still exits?how to solve it ,i met it again

**Comment by wilkinsona** [comment] 2018-03-22 11:04
@Usualminds As far as we know, everything works fine now with Java 9. Please take a look at [this page](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-Java-9) on the wiki for some advice on using Spring Boot with Java 9.
