### ISSUE TITLE
Actuator performance degradation for Jersey apps with non-static URLs

### ISSUE THREAD

**Issue by renarsg** [spring-projects/spring-boot#13281] opened 2018-05-28 19:23 UTC
Issue observed with 2.0.1.RELEASE and 2.0.2.RELEASE.

When a Jersey application with actuator contains a URL with a parameter in the path that is not static, over time the performance degrades.

Locally using a simple test server performance goes from 0.2ms down to 45ms per request in 10 minutes or so (it may take a while for the problem to appear).

build.gradle:
```
buildscript {
	ext {
		springBootVersion = '2.0.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = ''
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}


dependencies {
	compile("org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}")
	compile("org.springframework.boot:spring-boot-starter-web:${springBootVersion}")
        compile "org.springframework.boot:spring-boot-starter-jersey:${springBootVersion}"
}
```
Endpoint definition:
```
@Component
@Path("/test")
public class Endpoint {

	@GET
        @Path("/{id}")
	public String message(@PathParam("id") String id) {
		return "Hello " + id;
	}

}
```
Test client to observe the issue:
```
public class TestClient {
  OkHttpClient client = new OkHttpClient();

  String get(String url) throws IOException {
    Request request = new Request.Builder()
        .url(url)
        .build();

    try (Response response = client.newCall(request).execute()) {
      return response.body().string();
    }
  }

  public static void main(final String[] args)  throws IOException {
    TestClient client = new TestClient();
    while(true) {
      long start = System.currentTimeMillis();
      for (int i = 0; i < 1000; i++) {
        client.get("http://localhost:8080/test/" + UUID.randomUUID().toString());
      }
      long end = System.currentTimeMillis();
      System.out.println("Time for 1000 requests: " + (end - start));
    }
  }
}
```

Here is the full code of test server and client:
[test-server.zip](https://github.com/spring-projects/spring-boot/files/2045974/test-server.zip)
[test-client.zip](https://github.com/spring-projects/spring-boot/files/2045975/test-client.zip)

**Comment by wilkinsona** [comment] 2018-05-29 06:05
I’m pretty sure that this is a duplicate of #12447 but need to double check.

**Comment by wilkinsona** [comment] 2018-06-04 14:16
Thanks very much for the sample. It allowed to both reproduce the problem and to confirm that this is indeed a duplicate of #12447. I imaging it will also come in handy when verifying the fix for that issue.

**Closed by wilkinsona** 2018-06-04 14:16 UTC
Labels: status: waiting-for-triage
