### ISSUE TITLE
java.util.zip.ZipException when running Files.walk on /BOOT-INF/classes

### ISSUE THREAD

**Issue by semeiser** [spring-projects/spring-boot#6630] opened 2016-08-12 08:28 UTC
Hello,

we're getting the following Exception when trying to do a Files.walk on the /BOOT-INF/classes directory in an executable jar on Sping Boot 1.4.0:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Caused by: java.io.UncheckedIOException: java.util.zip.ZipException: loc: wrong sig ->20746168
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.example.FilesWalkJarExceptionApplication.main(FilesWalkJarExceptionApplication.java:17)
	... 8 more
Caused by: java.util.zip.ZipException: loc: wrong sig ->20746168
	at com.sun.nio.zipfs.ZipFileSystem$Entry.readExtra(ZipFileSystem.java:2277)
	at com.sun.nio.zipfs.ZipFileSystem$Entry.cen(ZipFileSystem.java:1903)
	at com.sun.nio.zipfs.ZipFileSystem$Entry.readCEN(ZipFileSystem.java:1871)
	at com.sun.nio.zipfs.ZipFileSystem.getEntry0(ZipFileSystem.java:1329)
	at com.sun.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:317)
	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:664)
	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
	... 18 more
```
The same code works with Spring Boot 1.3.X and the error only appears with an executable jar, non-executable jar works fine. Also /BOOT-INF/lib and /org/... directories can be traversed. A stripped down example can be found here https://github.com/semeiser/spring-boot-14-jarexception.

The original intent of the code is to recursivly walk down a resource directory, filter the entries and get the path from the resource root for every entry. The solution with Files.walk might be a bit naive, so if you can point me in a better direction I'll gladly change the code. But as the code worked with the previous versions of Spring Boot I thought I'd report it.

**Comment by wilkinsona** [comment] 2016-08-12 09:01
It looks to be due to a combination of the repackaging moving classes from `/` to `/BOOT-INF/classes` and the jar being fully executable. If I comment out `<executable>true</executable>` the problem goes away.

Also, zipinfo -v has no problem processing the entire jar even when its fully executable.

@semeiser I'd like to fix this, but I'm not sure how yet. In the meantime, can you provide some more details about the paths from the resource roots that you need? I suspect it may be possible to re-use some of Spring Framework's class path scanning logic.

**Comment by wilkinsona** [comment] 2016-08-12 09:03
Here's an addition to `RepackagerTests` that reproduces the problem:

```
	@Test
	public void repackagedJarCanBeWalked() throws Exception {
		this.testJarFile.addClass("A.class", ClassWithMainMethod.class);
		File source = this.testJarFile.getFile();
		File dest = this.temporaryFolder.newFile("dest.jar");
		Repackager repackager = new Repackager(source);
		LaunchScript script = new MockLauncherScript("ABC");
		repackager.repackage(dest, NO_LIBRARIES, script);
		FileSystem fileSystem = FileSystems.newFileSystem(dest.toPath(),
				getClass().getClassLoader());
		Files.walk(fileSystem.getPath("/")).forEach(System.out::println);
	}
```

**Comment by semeiser** [comment] 2016-08-12 09:18
Thanks for looking into this.
We have a source layout like the following tree. What we'd like to achieve after the app has started is to copy the files/directories below the input directory to some filesystem directory preserving the directory structure. And we'd like to filter some files which shouldn't be copied based on some predicates.
```
src
|-main
|--resources
|---input
|----sub
|-----subsub
|------shoudlnotbecopied.file
|------subsub.file
|-----sub.file
|----input.file
```

**Comment by wilkinsona** [comment] 2016-08-12 09:19
It looks like a bug in `ZipFileSystem`. Based on the test above, creating a `ZipFile` from `dest` and iterating over the entry enumeration allows every entry in the jar to be processed.

The bug can be avoided if `RenamingEntryTransformer` is updated so that it doesn't set the last modified time on the renamed entries. I'm not sure that we should do that though.

**Comment by semeiser** [comment] 2016-08-12 09:30
Regarding the `ZipFileSystem` there is a OpenJDK bug ticket for a similar issue https://bugs.openjdk.java.net/browse/JDK-8160436 which was closed.

**Comment by wilkinsona** [comment] 2016-08-12 09:37
That's interesting, thank you. It looks like you'll need to steer clear of `ZipFileSystem` when using a fully-executable jar as, judging by the comment on that bug, they're not interested in supporting a zip with and preamble.

**Comment by wilkinsona** [comment] 2016-08-12 09:40
Here's an alternative to your `Files.walk`-based solution:

```java
package com.example;

import java.io.IOException;
import java.util.Arrays;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

@SpringBootApplication
public class Gh6630Application {

	public static void main(String[] args) throws IOException {
		SpringApplication.run(Gh6630Application.class, args);

		PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver(Gh6630Application.class.getClassLoader());
		Arrays.asList(resolver.getResources("classpath*:/input/**"))
				.stream()
				.filter(r -> !r.getFilename().contains("not"))
				.forEach(System.out::println);
	}
}
```

By using `PathMatchingResourcePatternResolver` you're isolated from the layout of an executable jar. It's just scanning the class path for anything beneath `/input`. That also means it'll find files in nested jars too (which I realise may or may not be what you want). Run with the example files and directory structure you shared above, it produces this output:

```
$ java -jar gh-6630-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2016-08-12 10:35:08.421  INFO 77415 --- [           main] com.example.Gh6630Application            : Starting Gh6630Application v0.0.1-SNAPSHOT on aw-rmbp.home with PID 77415 (/Users/awilkinson/dev/temp/gh-6630-0.0.1-SNAPSHOT.jar started by awilkinson in /Users/awilkinson/dev/temp)
2016-08-12 10:35:08.424  INFO 77415 --- [           main] com.example.Gh6630Application            : No active profile set, falling back to default profiles: default
2016-08-12 10:35:08.471  INFO 77415 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5a2e4553: startup date [Fri Aug 12 10:35:08 BST 2016]; root of context hierarchy
2016-08-12 10:35:09.009  INFO 77415 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-08-12 10:35:09.020  INFO 77415 --- [           main] com.example.Gh6630Application            : Started Gh6630Application in 0.888 seconds (JVM running for 1.263)
URL [jar:file:/Users/awilkinson/dev/temp/gh-6630-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/input/]
URL [jar:file:/Users/awilkinson/dev/temp/gh-6630-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/input/sub/]
URL [jar:file:/Users/awilkinson/dev/temp/gh-6630-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/input/sub/subsub/]
URL [jar:file:/Users/awilkinson/dev/temp/gh-6630-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/input/input.file]
URL [jar:file:/Users/awilkinson/dev/temp/gh-6630-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/input/sub/sub.file]
URL [jar:file:/Users/awilkinson/dev/temp/gh-6630-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/input/sub/subsub/subsub.file]
2016-08-12 10:35:09.026  INFO 77415 --- [       Thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@5a2e4553: startup date [Fri Aug 12 10:35:08 BST 2016]; root of context hierarchy
2016-08-12 10:35:09.027  INFO 77415 --- [       Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

**Comment by semeiser** [comment] 2016-08-12 12:21
Thank you very much for your help, got everything working using your solution.

**Comment by wilkinsona** [comment] 2016-08-12 12:27
@semeiser Excellent, thanks for letting us know. Given the response to the OpenJDK issue you opened above, I'm going to close this. I don't think we should jump through any hoops to get `ZipFileSystem` to work with fully-executable jars.

**Closed** 2016-08-12 12:27 UTC
