### ISSUE TITLE
i18n by lang URL parameter on error page

### ISSUE THREAD

**Issue by BeRoots** [spring-projects/spring-boot#19937] opened 2020-01-26 22:26 UTC
Hello.

It seems that there is no translation management from the error pages. I currently have a spring-boot 2.2.2 application that works very well and uses the default language change method using the URL parameter "lang". I implemented a 404 page as described in the documentation by simply adding an html page in the static resourses in an "error" folder. It also works wonderfully, except that my menu on this page always offers the change of language. If I use it for the URL /error of this 404 (**/error?lang=en_GB**), it does not work and returns a Whitelabel Error Page.

The error says: "This application has no mapping for / error, so you are seeing this as a fallback.
There was an unexpected error (type = None, status = 999).
No message available "

Thank you in advance for your feedback.

**Comment by wilkinsona** [comment] 2020-01-27 08:13
Thanks for the report. I'm not sure I understand exactly what you're trying to do or why a `lang` query parameter would have the described effect. Can you please create a small sample project that reproduces the behaviour you have described? You can share it with us a zip attached to this issue or in a separate repository on GitHub.

**Comment by spring-issuemaster** [comment] 2020-02-03 08:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-02-10 08:15
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-02-10 08:15 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
