### ISSUE TITLE
Fetch @column name values from application.properties

### ISSUE THREAD

**Issue by shwetasm** [spring-projects/spring-boot#9961] opened 2017-08-06 22:45 UTC
I have two data-source profiles for my project (setup with Spring-boot, JPA Repositories, QueryDsl, Hibernate, existing Oracle DB) and I want to pass column names to @Entity class based on which profile is selected.
@column(name=.....)
private String name;

**Comment by wilkinsona** [comment] 2017-08-08 08:54
Thanks for the suggestion but this is a duplicate of #829. I don't think anything's changed since that issue was closed in terms of the difficulty of implementing this and how brittle it would be.

**Closed by wilkinsona** 2017-08-08 08:54 UTC
Labels: status: waiting-for-triage
