### ISSUE TITLE
autoconfig causes the hibernate dialect to be set to MySQL instead of what its configured as.

### ISSUE THREAD

**Issue by jeacott** [spring-projects/spring-boot#2882] opened 2015-04-27 07:57 UTC
I have a spring boot-batch application where I would ideally like batch to use hsqldb,
 and the batch jobs to interact with a postgres database via spring data repositories.

my basic dataSource setup looks like this:

```
    @Bean
    @Primary
    @ConfigurationProperties(prefix = "datasource.batch")
    public DataSource batchDataSource() {
        return DataSourceBuilder.create().build();
    }
    
     @Bean(name="pgDataSource")
     @ConfigurationProperties(prefix = "datasource.db")
     public DataSource pgDataSource() {
         return DataSourceBuilder.create().build();
     }
```

no matter what I try (I have tried a lot of things), it seems that if I have @EnableAutoConfiguration enabled at all, then the datasources are set correctly, but the hibernate dialect is always set as MySQL.
 
```
Registering named strategy selector [org.hibernate.dialect.Dialect] : [MySQL5] -> [org.hibernate.dialect.MySQL5Dialect] (replacing [org.hibernate.dialect.MySQL5Dialect])
2015-04-27 11:06:29.978 DEBUG 16188 --- [           main] o.h.b.r.s.internal.StrategySelectorImpl  : Registering named strategy selector [org.hibernate.dialect.Dialect] : [MySQL5InnoDB] -> [org.hibernate.dialect.MySQL5InnoDBDialect] (replacing [org.hibernate.dialect.MySQL5InnoDBDialect])
2015-04-27 11:06:30.183  INFO 16188 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {4.3.8.Final}
```

the postgres database driver, and database are both correctly identified and installed in the logs too.

i have set the dialect everywhere I can think of.
I have tried completely replacing and manually creating the entityManager, TxManager, JpaVendorAdapter, and setting hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
everywhere I can think of. alas to no avail. 

disabling autoconfig instantly restores hibernate to its senses.

I can also get both hibernate AND batch to use the same postgres db and the dialect is correctly configured.

the side effects are many for the MySQL dialect being chosen, not least of which is a very large time delay (many minutes) between the application startup, and a job actually getting data.

there's quite a bit online regarding a (I suspect mostly related) long connection time with postgres,
 and a few entries regarding the bad dialect but no solutions.

I've tried just disabling the autoConfigurers that look like they might be involved but no joy:
@EnableAutoConfiguration(exclude={JpaRepositoriesAutoConfiguration.class,
		DataSourceAutoConfiguration.class,
		DataSourceTransactionManagerAutoConfiguration.class,
		BatchAutoConfiguration.class})

I'm really hoping someone has some ideas.

Cheers

**Comment by wilkinsona** [comment] 2015-04-27 08:23
Can you share a small project that illustrates the problem?

**Comment by weaselmetal** [comment] 2015-08-14 08:59
Having the exactly same issue. Should be easily reproducible I think. My spring boot app is pretty bare bone right now. Adding the line 
`spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.mysql.MySQLSpatial5InnoDBDialect`
to application properties results in this app start up log:
```
INFO 5148 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatial5InnoDBDialect
INFO 5148 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
```
So my setting is applied but overwritten it seems.

**Comment by snicoll** [comment] 2015-08-14 09:10
I am afraid you're in the wrong place. For one, Spring Boot has no notion of spatial dialects so my best guess is that Hibernate is overriding that itself.

**Comment by weaselmetal** [comment] 2015-08-14 09:19
Doesn't Spring Boot try to derive the right dialect to use? It appeared to me that the setting is read, but right after that spring derives something different. So that's not the case?
If I configure nothing in application.properties, I get 
`Using dialect: org.hibernate.dialect.MySQL5Dialect` at start up, and I thought that's spring doing.

**Comment by snicoll** [comment] 2015-08-14 09:26
> Doesn't Spring Boot try to derive the right dialect to use?

No.

**Comment by weaselmetal** [comment] 2015-08-14 10:52
Thanks for looking into it.

**Comment by wilkinsona** [comment] 2015-10-12 12:59
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.

**Closed by wilkinsona** 2015-10-12 12:59 UTC
