### ISSUE TITLE
Enable reproducibleFileOrder by default on bootJar and bootWar tasks

### ISSUE THREAD

**Issue by icuxika** [spring-projects/spring-boot#27411] opened 2021-07-20 06:30 UTC
### System
OS: macOS 11.4
JDK: AdoptOpenJDK-16.0.1+9
Gradle: 7.1.1
Spring Boot: 2.5.2

### Demo
[demo(GitHub)](https://github.com/icuxika/spring-boot-package-bug-on-mac.git)

### Run
`gradle bootJar`
`java -jar build/libs/demo-0.0.1-SNAPSHOT.jar`

### Error
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSecurityConfig': Unsatisfied dependency expressed through method 'setContentNegotationStrategy' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webConfig': Unsatisfied dependency expressed through field 'requestMappingHandlerAdapter'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Unsatisfied dependency expressed through method 'requestMappingHandlerAdapter' parameter 0; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'mvcContentNegotiationManager': Requested bean is currently in creation: Is there an unresolvable circular reference?

```

**Comment by wilkinsona** [comment] 2021-07-20 09:54
When Spring Framework is resolving resources from jar files, it honours the ordering of the entries in the jar file and, by default, Gradle writes the files into the jar file in the order that they're provided to it by the file system. I believe this explains the different behaviour on macOS and Windows – the file systems on the two OSs are presenting the files to Gradle in two different orders so Gradle writes them into the jar files in two different orders. As a result, they're processed by Spring Framework in two different orders.

The difference between `bootRun` and `java -jar` on macOS is due to Spring Framework behaving differently when resolving resources from the file system, as it is in the `bootRun` case. In this situation, [its `PathMatchingResourcePatternResolver` sorts the files in each directory by their names](https://github.com/spring-projects/spring-framework/blob/9c0825629b715949b7082201bbcd90bfbf9d660b/spring-core/src/main/java/org/springframework/core/io/support/PathMatchingResourcePatternResolver.java#L824-L834):

```java
protected File[] listDirectory(File dir) {
	File[] files = dir.listFiles();
	if (files == null) {
		if (logger.isInfoEnabled()) {
			logger.info("Could not retrieve contents of directory [" + dir.getAbsolutePath() + "]");
		}
		return new File[0];
	}
	Arrays.sort(files, Comparator.comparing(File::getName));
	return files;
}
```

In the example application, this causes `WebConfig` to be processed before `WebSecurityConfigurer` which is the reverse of the filesystem's default ordering of the two files.

You can make the behaviour more consistent by configuring Gradle to use a reproducible order for the files in the jar:

```
bootJar {
    reproducibleFileOrder = true
}
```

This sorts `BOOT-INF/classes` by path and `WebConfig.class` therefore appears in the jar before `WebSecurityConfig.class`. This isn't identical to Spring Framework's file system-based ordering but it's very close. It will also guarantee the same ordering of entries in jars built on different operating systems.

I think we should enable `reproducibleFileOrder` by default for `bootJar` but probably only in 2.6. There is a small chance that it will be a breaking change for those with circular dependencies that are relying on the current ordering for the cycle to be breakable.

I don't think this problem applies to Maven. Its jars are reproducible by default as of version 3.2.0 of the jar plugin.

**Comment by icuxika** [comment] 2021-07-20 10:13
@wilkinsona Thanks for your patience. I have tried to apply this configuration on my project and it works well now. Your reply will help me learn Spring Framework better.

**Comment by wilkinsona** [comment] 2021-07-20 10:25
@icuxika You're welcome. I've re-opened the issue as I'd like to use it to enable reproducible ordering by default.

**Comment by wilkinsona** [comment] 2021-07-20 12:03
> I don't think this problem applies to Maven. Its jars are reproducible by default as of version 3.2.0 of the jar plugin.

I was mistaken here. You have to opt in with Maven by setting `project.build.outputTimestamp`.

**Comment by wilkinsona** [comment] 2021-07-21 16:41
We discussed this today and described not to do anything by default. https://github.com/spring-projects/spring-boot/issues/27436 has been opened to align the behaviour of a repackaged fat jar with Maven's war plugin.

**Closed** 2021-07-21 16:42 UTC
Labels: status: declined, type: enhancement
