### ISSUE TITLE
Immutable configuration properties not shown by Actuator

### ISSUE THREAD

**Issue by AlexFalappa** [spring-projects/spring-boot#18636] opened 2019-10-17 13:27 UTC
From my initial test drive of the freshly released Spring Boot _2.2.0.RELEASE_ it seems that `@ConfigurationProperties` beans declared as immutable with `@ConstructorBinding` show up empty in the Actuator `configprops` endpoint.
Example:

```
"ftp-af.FtpProperties": {
  "prefix": "ftp",
  "properties": {}
}
```

The beans are however correctly bound and their use in other beans is not impacted.

Normal, mutable beans are correctly displayed with their attributes.
Example:
```
"ftp-af.FtpProperties": {
  "prefix": "ftp",
  "properties": {
    "host": "andromeda",
    "dir": "/path/to/files",
    "user": "JohnSmith",
    "port": 2121,
    "passw": "Unknown"
  }
}
```

**Comment by snicoll** [comment] 2019-10-17 13:31
Oops. Thanks for the report!

**Comment by rhamedy** [comment] 2019-10-18 00:16
@snicoll is this feasible for contribution? 

I have used actuator endpoint before; however, I don't know how it works under the hood. I am curious how complicated is this task? If open for contribution, I would love to give it a shot. I would appreciate some direction in the form of guidance, previous issues/PRs I could look into, materials, classes, etc.

**Comment by snicoll** [comment] 2019-10-18 08:20
@rhamedy it's really hard to answer such question without looking at the actual problem and often we have the solution by the time we're experimenting. This one is extra special as it's assigned to `2.0.1` which we intend to release relatively soon-ish and I really would like to get that fixed.

If you have time short term, I believe the problem is [this method](https://github.com/spring-projects/spring-boot/blob/a7de27c5d3a687e43cda946720dbc58700f832bb/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/context/properties/ConfigurationPropertiesReportEndpoint.java#L122-L138) that serializes the content of the configuration properties instance. For some reason that doesn't work if there isn't a setter? Wild guess, I haven't looked at it in more details.

**Comment by polarbear567** [comment] 2019-10-18 09:11
@snicoll I think we can use other conversion methods here.

**Comment by rhamedy** [comment] 2019-10-21 17:49
Thank you both (`snicoll` and `wilkinsona`) for the comment. If not mistaken, @polarbear567 seems to have already made a PR for this issue https://github.com/spring-projects/spring-boot/pull/18659. If the PR is not related, then apologies for linking it. 

I think `snicoll` made some good points about `complexity` and `urgency`. It would be best for me to await another opportunity to work on `Actuator` 🤞

**Comment by snicoll** [comment] 2019-10-22 14:39
I've started to hack on something in 353a30f and I've discovered some potential improvements in constructor binding in the process (#18685). I have something somewhat satisfactory except that nested types are not processed. It looks like Jackson decides that there is nothing do as there are no properties or something like that? There is a test failing on that commit.

**Closed** 2019-10-24 12:46 UTC
Labels: type: bug
