### ISSUE TITLE
ConfigurationProperties relaxed binding from env var is broken in 2.0.0.M6

### ISSUE THREAD

**Issue by asarkar** [spring-projects/spring-boot#11194] opened 2017-11-28 23:43 UTC
In Boot 2.0.0.M6, a property `k8s.baseUrl` doesn't bind to env var `K8S_BASE_URL`; `k8s.namespace` binds as expected to `K8S_NAMESPACE`, so the issue seems to be with camel-case conversion. I've not verified the other formats supported by relaxed binding.

FWIW, this issue doesn't seem to be present in 2.0.0.BUILD-SNAPSHOT.

**Comment by mbhave** [comment] 2017-11-29 01:28
Duplicate of #10832 which has already been fixed.

**Closed by mbhave** 2017-11-29 01:28 UTC
Labels: status: waiting-for-triage

**Comment by asarkar** [comment] 2017-11-29 02:55
@mbhave How's this a dup? https://github.com/spring-projects/spring-boot/issues/10832 seems to be completely irrelevant, unless you're saying that both are caused by the same issue, in which case, they are not dup.

**Comment by spencergibb** [comment] 2017-11-29 02:57
She put the wrong number in, but it is a duplicate that's been fixed. You even said it's not a problem anymore in snapshots where the fix was made.

**Comment by asarkar** [comment] 2017-11-29 03:05
@spencergibb Yes it's not a problem in SNAPSHOT, but SNAPSHOT doesn't count, so I wanted to follow up with a ticket. Thanks for your response.
That said, perhaps instead of rushing to close tickets with random references, it should be checked that if the reference even made sense. 10832 is just as relevant as today's weather report.

**Comment by spencergibb** [comment] 2017-11-29 03:19
Bug fixes happen in snapshots until the next release. She made a mistake with the wrong issue. #10873 No need to get snippy about it.

**Comment by mbhave** [comment] 2017-11-29 03:27
yes, that's the issue I meant to reference. Sorry for the confusion and thanks for correcting the issue number @spencergibb.
