### ISSUE TITLE
Generate or provide metadata for externally provided configuration properties used with variable prefixes

### ISSUE THREAD

**Issue by cachescrubber** [spring-projects/spring-boot#19500] opened 2019-12-31 10:20 UTC
I use the configuration properties feature to bind properties multiple times using different prefixes which are dynamic in nature.

`````java
@ConfigurationProperties(prefix = "client-a")
@Bean
public MyClientProperties clientAproperties() {
  return new  MyClientProperties();
}

@ConfigurationProperties(prefix = "client-b")
@Bean
public MyClientProperties clientBproperties() {
  return new  MyClientProperties();
}
`````

As long as the `MyClientProperties` class is local to my spring-boot project, the `spring-boot-configuration-processor` is able to generate metadata for each prefix I use. In particular, the `description` and `defaultValue` metatdata is extracted from the field level javadoc of the class:

`````java
public class MyClientProperties {
  /**
   * Web service remote endpoint url
   */
  public String endpoint = "http://localhost:8080/services";
...
}
`````

The generated metadata

````json
    {
      "name": "client-a.endpoint",
      "type": "java.lang.String",
      "description": "Web service remote endpoint url",
      "sourceType": "com.example.client.MyClientProperties",
      "defaultValue": "http:\/\/localhost:8080\/services"
    },
...
    {
      "name": "client-b.endpoint",
      "type": "java.lang.String",
      "description": "Web service remote endpoint url",
      "sourceType": "com.example.client.MyClientProperties",
      "defaultValue": "http:\/\/localhost:8080\/services"
    },

````

This changes as soon as the class is moved to an external jar dependency in order to be shared among several projects and the `spring-boot-configuration-processor` has no access to the source code of the properties type. The `description` and `defaultValue` metadata is no longer available. 

````json
    {
      "name": "client-a.endpoint",
      "type": "java.lang.String",
      "sourceType": "com.example.client.MyClientProperties"
    },
...
    {
      "name": "client-b.endpoint",
      "type": "java.lang.String",
      "sourceType": "com.example.client.MyClientProperties"
    },
````

If `MyClientProperties` would be used with a fixed prefix only, I could run the `spring-boot-configuration-processor` within the external jar module and package the generated metatdata.json file. The generated metadata would be visible in the context of the consuming spring-boot application under the `my-client` prefix.

````java
@@ConfigurationProperties(prefix = "my-client")
public class MyClientProperties {
...
}
````

What I need is a mechanism to access the `description` and `defaultValue` metatdata from the externally provided properties class below the dynamic prefixes chosen by the consuming spring-boot application.

Note: I submited a [question](https://stackoverflow.com/questions/59519978/spring-boot-configuration-processor-how-to-generate-or-provide-metadata-for-ext) at StackOverflow, but in the meantime I think this is most likely an enhancement request.

**Comment by cachescrubber** [comment] 2019-12-31 10:53
nested configuration properties are another use-case.

````java
public class MyApplicationProperties {

  @NestedConfigurationProperty
  private MyClientProperties client;
````

**Comment by knoobie** [comment] 2019-12-31 12:35
Please take a look at the official documentation, it's well written [there](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-configuration-metadata.html#configuration-metadata-annotation-processor).

**Comment by snicoll** [comment] 2019-12-31 12:44
@knoobie thanks for trying to help but @cachescrubber is trying to generate metadata content from an external jar.

This is effectively a duplicate of #18366

**Closed by snicoll** 2019-12-31 12:44 UTC
Labels: status: waiting-for-triage

**Comment by cachescrubber** [comment] 2019-12-31 13:06
@snicoll Thx. My bad, I missed #18366. I'll update StackOverflow accordingly.
