### ISSUE TITLE
Spring Boot and Spring Data Rest - java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by EugenMaysyuk** [spring-projects/spring-boot#9911] opened 2017-07-30 20:51 UTC
Under WildFly 10.1.0.Final I am getting:

```
java.lang.IllegalAccessError: class org.springframework.data.rest.webmvc.RepositoryEntityController cannot access its superclass org.springframework.data.rest.webmvc.AbstractRepositoryRestController
```

This issue started to happen when I added Spring Data Rest configuration with all the necessary dependencies into the project.

I noticed that issue cannot be reproduced when I comment` <context:load-time-weaver /> `tag inside the  `applicationContext.xml`.

This is a sample app that reproduces the problem:
https://github.com/EugenMaysyuk/spring-boot-data-rest

**Comment by EugenMaysyuk** [comment] 2017-07-30 21:17
I have prepared additional sample project that demonstrates that issue doesn't occur while using traditional xml configuration (without Spring Boot):

https://github.com/EugenMaysyuk/spring-data-rest-xml-config

**Comment by philwebb** [comment] 2017-07-31 18:28
Do you have a complete stack trace from the "cannot access its superclass" error that you can attach?

**Comment by wilkinsona** [comment] 2017-07-31 18:34
I've seen this happen in the past, but only when there are two class loaders.

When a package is defined it's associated with a particular class loader. If two class loaders define the same package they're not actually the same and anything that's package-private in a class loaded by one class loader won't be visible to a class loaded by another class loader even thought the classes appear to be in the same package.

**Comment by EugenMaysyuk** [comment] 2017-08-01 12:13
@philwebb 
The attached file is a complete stack trace.
[log.txt](https://github.com/spring-projects/spring-boot/files/1190531/log.txt)

**Comment by EugenMaysyuk** [comment] 2017-08-01 12:51
@wilkinsona you are absolutely right.

I have found a root cause of this issue.

https://github.com/spring-projects/spring-framework/blob/v4.3.7.RELEASE/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L655

> At this place Spring sets ContextTypeMatchClassLoader as a temp classLoader

...

https://github.com/spring-projects/spring-framework/blob/v4.3.7.RELEASE/spring-core/src/main/java/org/springframework/core/type/classreading/SimpleMetadataReaderFactory.java#L98

> this.resourceLoader.getClassLoader returns JBoss classLoader (**not temporarily ContextTypeMatchClassLoader**)

https://github.com/spring-projects/spring-framework/blob/v4.3.7.RELEASE/spring-core/src/main/java/org/springframework/core/type/classreading/SimpleMetadataReader.java#L63						 

> SimpleMetadataReader passes JBoss classloader into AnnotationMetadataReadingVisitor object

https://github.com/spring-projects/spring-framework/blob/v4.3.7.RELEASE/spring-core/src/main/java/org/springframework/core/type/classreading/AnnotationMetadataReadingVisitor.java#L134

> AnnotationMetadataReadingVisitor passes wrong class loader to AnnotationReadingVisitorUtils

https://github.com/spring-projects/spring-framework/blob/v4.3.7.RELEASE/spring-core/src/main/java/org/springframework/core/type/classreading/AnnotationReadingVisitorUtils.java#L78

> Spring uses wrong classLoader to load org.springframework.data.rest.webmvc.RepositoryRestController and its parent org.springframework.data.rest.webmvc.AbstractRepositoryRestController and defines package for AbstractRepositoryRestController

...
https://github.com/spring-projects/spring-framework/blob/v4.3.7.RELEASE/spring-context/src/main/java/org/springframework/context/support/ContextTypeMatchClassLoader.java#L72

> ContextTypeMatchClassLoader tries to load org.springframework.data.rest.webmvc.RepositoryEntityController and cannot find its superclass since its package has been defined using JBoss classloader

**Comment by EugenMaysyuk** [comment] 2017-08-01 12:57
I think SimpleMetadataReaderFactory.java have to be refactored to use tempClassLoader from BeanFactory (if it is not null) and resource class loader in other case.

**Comment by EugenMaysyuk** [comment] 2017-08-01 13:05
I have found an open bug (may the same) under Spring Framework Jira:
https://jira.spring.io/browse/SPR-10206

**Comment by jhoeller** [comment] 2017-08-01 13:11
Let's reuse SPR-10206 for our purposes here. It does indeed hint at the same issue.

We actually intentionally use the standard `ClassLoader` here since we do not expect annotation types to be weaved... so we naively assumed that they can always be loaded in the factory's regular `ClassLoader`. It seems that this can cause conflicts with the same package split across the standard and the temp loader here?

**Comment by wilkinsona** [comment] 2017-08-01 13:41
Thanks for the analysis, @EugenMaysyuk. I'll close this one as a duplicate of SPR-10206 which I'm now watching.

**Closed by wilkinsona** 2017-08-01 13:41 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by shenyu1997** [comment] 2018-12-06 04:02
I met this issue and resolve it by removing
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
        </dependency>
```
