### ISSUE TITLE
Add XMLUnit as a managed dependency and possibly to the test starter

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9695] opened 2017-07-06 19:18 UTC
It might be nice to add this by default. See #9691 for an example of the current problems when using `xml()` in Mock MVC.

**Comment by andrew-j-cohen** [comment] 2017-07-09 22:14
Hi @philwebb,

This is my first contribution to the project. I was looking for an appropriate place to add a unit test for this, but I'm not sure where that would be or if its even warranted. Any feedback you have is most welcome. As a long time avid user of spring boot, I'm looking forward to more contributions in the future.

Thanks!
-Andrew

**Comment by snicoll** [comment] 2017-09-01 15:59
Duplicate of #9709

**Closed by snicoll** 2017-09-01 15:59 UTC
Labels: for: team-attention, priority: normal, type: enhancement
