### ISSUE TITLE
Issues related to building an image using spring-boot:build-image

### ISSUE THREAD

**Issue by WvvvWv** [spring-projects/spring-boot#34176] opened 2023-02-14 04:01 UTC
spring-boot version:2.5.12
jdk version:temurin-1.8
As shown below:
![image](https://user-images.githubusercontent.com/40822202/218636380-5fe6a734-37c5-4d1e-a22a-30b134996600.png)
He would get stuck and occasionally succeed.
I don't know what caused it, please help me, thank you.

**Comment by WvvvWv** [comment] 2023-02-14 09:11
> 



> Hi! Is this an M1 or M2 mac or an otherwise ARM based system? If yes, you need to use an [alternative builder](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-with-GraalVM#building-container-images).

Thank you for your reply.
My operating system is win10, cpu is i7-8750h, and I use docker for win wsl2.

**Comment by mhalbritter** [comment] 2023-02-14 09:14
So I see you're using Spring Boot 2.5.12, which is no longer in OSS support. Please upgrade to at least 2.7.x and report back if that has fixed the problem.

**Comment by WvvvWv** [comment] 2023-02-14 09:24
> So I see you're using Spring Boot 2.5.12, which is no longer in OSS support. Please upgrade to at least 2.7.x and report back if that has fixed the problem.

Ok, thank you. I'll upgrade to 2.7x and try again.

**Comment by wilkinsona** [comment] 2023-02-14 11:26
This looks like it may be a duplicate of https://github.com/paketo-buildpacks/spring-boot/issues/312.

**Comment by spring-projects-issues** [comment] 2023-02-21 11:27
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by WvvvWv** [comment] 2023-02-24 09:20
> So I see you're using Spring Boot 2.5.12, which is no longer in OSS support. Please upgrade to at least 2.7.x and report back if that has fixed the problem.

Hello, after I upgraded the spring-boot to 2.7.8, I still occasionally encountered the problem of saving stuck after several days of use. On the contrary, I did not encounter this problem when I packaged with dockerfile.

**Comment by wilkinsona** [comment] 2023-02-24 09:39
@WvvvWv Thanks for trying 2.7.x. Given that you're using Windows and without any evidence to the contrary, I'm going to close this is a duplicate of https://github.com/paketo-buildpacks/spring-boot/issues/312. Please follow up there.

**Closed by wilkinsona** 2023-02-24 09:39 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by WvvvWv** [comment] 2023-02-24 09:58
I had the same problem:
OS: WIN10
docker for win version: 4.16.3 (96739)
No other logs came out after saving, so I had to restart the wsl. On the contrary, I built the image with dockerfile and did not encounter this problem.
