### ISSUE TITLE
Include DispatcherServlets only exposed as a ServletRegistrationBean in the mappings endpoint

### ISSUE THREAD

**Issue by filiphr** [spring-projects/spring-boot#13186] opened 2018-05-15 20:24 UTC
When a `DispatcherServlet` is registered via:

```
@Bean
public ServletRegistrationBean<DispatcherServlet> idmServlet(MyProperties properties) {
    return registerServlet(properties.getServlet(), IdmEngineRestConfiguration.class);
}
```

Then when the `mappings` endpoint is invoked then the 
`context.application.mappings.servlet` correctly contains that servlet information. However, under `context.application.mappings.dispatcherServlets` only the `dispatcherServlet` and not my custom servlet mappings are displayed.

It would be good if `ServletRegistrationBean`(s) are also considered as part of the `MappingsEndpoint`

**Comment by philwebb** [comment] 2018-05-24 17:35
Closing in favor of PR #13211

**Comment by filiphr** [comment] 2018-05-27 18:50
@philwebb just out of my curiosity (want to understand how your labels are working). You closed this in favor of the PR (this part I get). You then marked it as duplicate, I assume a duplicate of the PR, but the PR is actually a fix for this issue.

**Comment by snicoll** [comment] 2018-05-27 19:08
github doesn’t make a difference between an issue and a PR. We’ll use the PR to track the issue described here so this issue becomes a duplicate of it.

**Closed** 2018-07-10 15:08 UTC
Labels: type: bug
