### ISSUE TITLE
spring data redis starter exception

### ISSUE THREAD

**Issue by niugege** [spring-projects/spring-boot#3957] opened 2015-09-14 08:57 UTC
this is the bug that reported and fixed by spring data redis, can find here:

https://jira.spring.io/browse/DATAREDIS/fixforversion/15278/?selectedTab=com.atlassian.jira.plugins.jira-development-integration-plugin:release-report-tabpanel

https://jira.spring.io/browse/DATAREDIS-421

since it already fixed, pls,  fix in redis starter

**Comment by snicoll** [comment] 2015-09-14 09:25
No need to report that back to us. We've upgraded master to Gosling a while back already and we constantly align Boot's dependencies. 

The issue is fixed in `1.3.0.M5`.

**Comment by snicoll** [comment] 2015-09-14 09:25
Duplicates #3860

**Closed by snicoll** 2015-09-14 09:25 UTC
