### ISSUE TITLE
Servlet filter order with annotation

### ISSUE THREAD

**Issue by fred84** [spring-projects/spring-boot#11637] opened 2018-01-15 16:09 UTC
Filters can be registered on 2 ways:
1) with ```@WebFilter```
2) with ```@Bean public FilterRegistrationBean createFilter()``` configuration.

Second option also allows us to specify filter order. I think it will be useful to add support for  ```@Order``` annotation for filters to simplify setting order.

**Comment by wilkinsona** [comment] 2018-01-15 16:19
Duplicate of #8276.

**Closed by wilkinsona** 2018-01-15 16:19 UTC
Labels: status: waiting-for-triage
