### ISSUE TITLE
Executable jar fails when started by root if log_file does not exist

### ISSUE THREAD

**Issue by cataling** [spring-projects/spring-boot#12188] opened 2018-02-23 00:03 UTC
Reproduced with: 2.0.0RC1

Steps to reproduce: 

1. package a spring boot application as executable jar owned by a non-root user
2. make sure the log file does not exist
3. start the executable jar as root (`./app.jar start`)
Result: `sh: <<logfile>>: Permission denied`
Expected: application should start, process owner should be the owner of the executable jar file.

The cause seems to be that helper function `checkPermissions` does a touch on both `$pid_file` and `$log_file`. In the scenario above, this will cause both files to be created and owned by root. 

While this is ok for the pid file, it's not ok for the log file because in `do_start()` the application process is started with `su -s /bin/sh -c "$javaexe $(printf "\"%s\" " "${arguments[@]}") >> \"$log_file\" 2>&1 & echo \$!" "$run_user" > "$pid_file"`, which essentially starts a process as `$run_user` with stdout redirected to `$log_file` which is now owned by root. 

The issues seems to have been introduced by https://github.com/spring-projects/spring-boot/commit/886b39293c17d04167108af59f935261ff44aa5d which removed the line `chown "$run_user" "$log_file"`

**Comment by philwebb** [comment] 2018-02-23 00:57
@cataling I think this is a duplicate of #11951. Could you try the latest 2.0.0 SNAPSHOT and let us know if it's fixed?

**Comment by spring-issuemaster** [comment] 2018-03-02 01:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-03-09 01:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-03-09 01:03 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
