### ISSUE TITLE
Spring Boot 3.2 is not compatible with older versions of Liquibase

### ISSUE THREAD

**Issue by ebussieres** [spring-projects/spring-boot#38522] opened 2023-11-23 18:14 UTC
Spring-boot 3.2.0 seems to have introduced a regression. I am using liquibase with a liquibase parameters in a sql script.

When setting the flag `test-rollback-on-update` to true, there's a checksum validation error when performing the rollback step. It seems to be related when you use a liquibase parameter in a sql script (see [here](https://github.com/ebussieres/spring-liquibase-bug/blob/master/src/main/resources/application.properties#L2) and [here](https://github.com/ebussieres/spring-liquibase-bug/blob/master/src/main/resources/db/changelog/testWithParams.sql))

There's a [demo ](https://github.com/ebussieres/spring-liquibase-bug) available here which demonstrate the regression. Just run the [test ](https://github.com/ebussieres/spring-liquibase-bug/blob/master/src/test/java/com/example/demo/DemoApplicationTests.java)to see the problem.

If you change the spring boot version to 3.1.6, eveything's working fine.

**Comment by wilkinsona** [comment] 2023-11-23 19:05
I don't think this is a Spring Boot regression. The same problem occurs with Spring Boot 3.1.6 if you use Liquibase 4.24.0 (the default version in Spring Boot 3.2) or 4.25.0 (the latest version at the time of writing). Please report the problem to the Liquibase team.

Unfortunately, you cannot downgrading Liquibase to 4.23.3 with Spring Boot 3.2 (the default version of Spring Boot 3.1.6) as it does not contain the `liquibase.UpdateSummaryOutputEnum` class [upon which Spring Boot now depends](https://github.com/spring-projects/spring-boot/pull/38274).

**Comment by ebussieres** [comment] 2023-11-23 19:46
I've opened an [issue](https://github.com/liquibase/liquibase/issues/5278) to the Liquibase team too

**Comment by wilkinsona** [comment] 2023-11-24 06:57
Thanks, @ebussieres. It looks like it's going to be fixed on the Liquibase side. I'll leave this one open for now though as I think we should consider making a change to `LiquibaseProperties` so that it doesn't directly rely upon the recently introduced Liquibase enums.

**Comment by EvaristeGalois11** [comment] 2023-11-25 01:07
> it does not contain the liquibase.UpdateSummaryOutputEnum class upon which Spring Boot now depends.

> we should consider making a change to LiquibaseProperties so that it doesn't directly rely upon the recently introduced Liquibase enums.

If you are interested @wilkinsona I still have the patch of my first attempt at introducing those two properties where I used some local enums in `LiquibaseProperties` and converted them in `LiquibaseAutoConfiguration`. This doesn't get rid of the enums, but move them to another class. I can tidy it up a bit and submit it as a PR to discuss it further. 

I'm not sure if this is what you mean with not having `LiquibaseProperties` rely upon the two enums or you were talking more in general though.

**Comment by philwebb** [comment] 2023-11-27 16:54
We're going to look at duplicating the enums in our code (with tests to keep them in sync) so that folks can downgrade. 

@EvaristeGalois11 thanks for the offer of a PR, but this one should be pretty easy for us to take care of ourselves.

**Closed** 2023-11-28 17:44 UTC
Labels: type: bug

**Comment by radarsh** [comment] 2024-10-14 10:37
This is quite a significant change from Liquibase and warrants a mention in the Spring Boot 3.2 release notes. Also, if they fix the backwards compatibility issue on Liquibase, possibly including it the upcoming Spring 3.4 release.
