### ISSUE TITLE
Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

### ISSUE THREAD

**Issue by LUCKYZHOUSTAR** [spring-projects/spring-boot#18757] opened 2019-10-27 10:25 UTC
hi，when user the des encrypt, meet the error.

Firstly,when I just test the dncrpty method using main method, that is ok

```java
@Test
public void test1() {

    for (int i = 0; i < 100; i++) {
        System.out.println(DESCryptography.dncrypt("F62AC256E0778C87"));

    }

}
```

but , unhappily ,when I start my spring boot web ,just write this:

```
public static void main(String... args) {

    ApplicationContext context = SpringApplication.run(WalletDriver.class, args);

    for (int i = 0; i < 100; i++) {
        System.out.println(DESCryptography.dncrypt("F62AC256E0778C87"));
    }
}
```

I meet the error：
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
at java.base/com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314)
at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)

Until now,i can not found how to resolve the problem

**Comment by wilkinsona** [comment] 2019-10-27 10:44
Thanks for the report. Unfortunately, it's not clear to me why you think this is a problem with Spring Boot. It's also not clear what versions of Java and Spring Boot you are using or where the class `DesCryptography` comes from. If you would like us to spend some more time investigating, please spend some time creating a complete and minimal sample that reproduces the problem and then share it with us by zipping it up and attaching it to this issue.

**Comment by spring-issuemaster** [comment] 2019-11-03 10:45
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-11-10 10:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-11-10 10:46 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
