### ISSUE TITLE
Auto configure tracing spans for @Scheduled tasks

### ISSUE THREAD

**Issue by tzhao11** [spring-projects/spring-boot#35669] opened 2023-05-29 12:37 UTC
`@Scheduled` tasks do not create new spans by default after migrating from Spring Cloud Sleuth to Spring Boot 3. This also causes the traceId and spanId to disappear from logs. There are some workarounds, such as the one suggested here: https://stackoverflow.com/questions/75030590/tracing-of-logs-with-scheduled-in-spring-boot-3-0. However, it would be much more convenient if Spring Boot could handle this automatically.

**Comment by vpavic** [comment] 2023-05-31 13:43
This seems to be a duplicate of https://github.com/spring-projects/spring-framework/issues/29883.

**Comment by wilkinsona** [comment] 2023-05-31 14:13
Indeed it is. Thanks, Vedran.

**Closed by wilkinsona** 2023-05-31 14:13 UTC
Labels: status: waiting-for-triage, theme: observability
