### ISSUE TITLE
Auto-configured MultipartConfigElement prevents CommonsMultipartResolver from resolving request parts

### ISSUE THREAD

**Issue by peilongwu** [spring-projects/spring-boot#7735] opened 2016-12-23 01:58 UTC
I used Spring Boot 1.2.6 before, So I want to upgrade Spring Boot to 1.4.2 and upgrade Spring Framework to 4.3.5, when I changed my maven pom, The Apache Commons FileUpload parseRequest() returning no items.  Then I changed Spring Boot to 1.3.8  and Spring Framework to 4.2.8, the Apache Commons FileUpload can work. I don't know why. The following is my maven pom and my code.

## Maven pom

```
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot</artifactId>
        <version>1.3.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
        <version>1.3.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-tomcat</artifactId>
        <scope>provided</scope>
        <version>1.3.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-logging</artifactId>
        <version>1.3.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-log4j</artifactId>
        <version>1.3.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-autoconfigure</artifactId>
        <version>1.3.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-ws</artifactId>
        <version>1.3.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-webmvc</artifactId>
        <version>4.2.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-test</artifactId>
        <version>4.2.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-context-support</artifactId>
        <version>4.2.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-expression</artifactId>
        <version>4.2.8.RELEASE</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-ldap</artifactId>
        <version>4.2.0.RELEASE</version>
      </dependency>
```

## Code 

```
   DiskFileItemFactory factory = new DiskFileItemFactory();
    factory.setSizeThreshold(1 * 1024 * 1024);
    File tmpDir = new File("tempfile");
    if (!tmpDir.exists()) {
      tmpDir.mkdir();
    }
    File uploadtmp = new File("uploadtmp");
    if (!uploadtmp.exists()) {
      uploadtmp.mkdir();
    }
    factory.setRepository(tmpDir);
    ServletFileUpload sfu = new ServletFileUpload(factory);
    sfu.setFileSizeMax(-1);
    sfu.setSizeMax(-1);
    sfu.setHeaderEncoding("UTF-8");
    List<FileItem> fileItems = (List<FileItem>) sfu.parseRequest(request);
```

When I use Spring Boot 1.4.2 and Spring Framework 4.3.5, the fileItems is empty.

**Comment by qiuxiaoj** [comment] 2016-12-23 02:34
The same to me. I had bean give up when try my best to debug.

**Comment by philwebb** [comment] 2016-12-23 04:00
@qiuxiaoj or @peilongwu do either of you have a sample project that we can try?

**Comment by spring-issuemaster** [comment] 2016-12-30 04:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-01-06 04:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by TheSentinel454** [comment] 2017-02-07 18:19
I'm having this same issue, and have example code reproducing the issue.

**Comment by TheSentinel454** [comment] 2017-02-07 18:20
@philwebb I'm having this same issue, and have an example application that reproduces the issue.  Do you want to re-open this issue, or should I open a new one?

**Comment by TheSentinel454** [comment] 2017-02-07 18:27
Example code can be found here:
https://github.com/TheSentinel454/spring-boot-apache-upload-issue

**Comment by snicoll** [comment] 2017-02-07 19:20
@TheSentinel454 how is Swagger relevant to the issue?

**Comment by martin-g** [comment] 2017-02-07 19:42
@TheSentinel454 Try with the following
```java
@EnableAutoConfiguration(exclude = {
    MultipartAutoConfiguration.class  // excluded so that the application uses commons-fileupload instead of Servlet 3 Multipart support
})
```
in YourSpringBootApplication.
This will disable Servlet 3.x multipart support. Maybe the data has been read before commons-fileupload had a chance to do it.

**Comment by TheSentinel454** [comment] 2017-02-07 19:49
@snicoll Swagger is not relevant (I'll remove it now).  I was originally using that to do the upload, but decided to resort to using a rest client.

**Comment by TheSentinel454** [comment] 2017-02-07 19:54
@martin-g That fixed it, thanks!

**Comment by martin-g** [comment] 2017-02-07 19:58
@snicoll Is it a good idea to not enable Servlet 3 Multipart auto configuration if commons-fileupload is on the classpath ?

**Comment by ulrichwinter** [comment] 2018-06-14 11:41
@snicoll 
here is a project which reproduces this issue with the current spring boot version 2.0.2.RELEASE:
https://github.com/ulrichwinter/gs-uploading-files/tree/master/complete

I also had this same issue within a project just after upgrade from 1.4.4.RELEASE to 1.5.12.RELEASE.
But unfortunately I was not able to reproduce it with 1.5.12 in the demo project.

(the demo is based on the fileupload guide project from spring boot).

**Comment by wilkinsona** [comment] 2018-06-19 11:37
Thanks for the sample, @ulrichwinter.

I think we need to make the auto-configuration of `MultipartConfigElement` back off when there's a `CommonsFileUploadResolver` bean available. If we don't, the use of the `MultipartConfigElement` prevents Commons File Upload from working. It needs to specifically be a `CommonsFileUploadResolver` bean that causes the auto-configuration to back off as doing so for any `MultipartResolver` would regress #2538.

> But unfortunately I was not able to reproduce it with 1.5.12 in the demo project.

The problem doesn't occur with 1.5 as you have the following in `application.properties`:

```
spring.http.multipart.enabled=false
```

This has the same effect as excluding the auto-configuration. The equivalent property on 2.0 is `spring.servlet.multipart.enabled=false`.

**Closed** 2018-06-20 12:57 UTC
Labels: type: bug
