### ISSUE TITLE
Confusing error when custom endpoint is given camel-cased id

### ISSUE THREAD

**Issue by shabino** [spring-projects/spring-boot#11223] opened 2017-11-30 18:08 UTC
I just upgraded from M6 to M7. Previously, I had defined a custom endpoint with a camel-cased name: `@Endpoint(id = "fooBar")`.  Under M7, I got the following error upon app start-up:

```
APPLICATION FAILED TO START
***************************

Description:

Configuration property name 'management.endpoint.fooBar.cache.time-to-live' is not valid:

    Invalid characters: 'B'
    Bean: jmxMBeanExporter
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'management.endpoint.fooBar.cache.time-to-live' so that it conforms to the canonical names requirements.
```

This was confusing because I had not explicitly defined `management.endpoint.fooBar.cache.time-to-live`.  Changing the `id` to `foo-bar` solved the problem.  If it's necessary that endpoint ids not contain capital letters (which is fine by me), a more direct error message ought to be provided.

[Minor] Also, please consider making `id` the default value for the `@Endpoint` annotation so that one doesn't have to add `id =` explicitly.

**Comment by snicoll** [comment] 2017-11-30 18:54
Duplicate of #11107

**Closed by snicoll** 2017-11-30 18:54 UTC
Labels: status: waiting-for-triage
