### ISSUE TITLE
Section Anchors are not Visible in Reference

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#24406] opened 2020-12-08 23:04 UTC
If I visit https://docs.spring.io/spring-boot/docs/2.4.0/reference/htmlsingle/ and hover over sections, the anchors links are not visible. If I visit https://docs.spring.io/spring-boot/docs/2.2.x/reference/htmlsingle/ and hover over sections the anchor link is visible and can be used to copy a link.

**Comment by izeye** [comment] 2020-12-08 23:19
This also seems to be a duplicate of https://github.com/spring-projects/spring-boot/issues/24146, and 2.4.1-SNAPSHOT seems to be okay.

See https://docs.spring.io/spring-boot/docs/2.4.1-SNAPSHOT/reference/htmlsingle/

**Comment by philwebb** [comment] 2020-12-09 00:18
Thanks @izeye, I agree. I think this is a duplicate of #24146 which picked up the fix for  spring-io/spring-doc-resources#65

**Closed by philwebb** 2020-12-09 00:18 UTC
Labels: status: waiting-for-triage
