### ISSUE TITLE
Provide support for SLF4J 2.0 

### ISSUE THREAD

**Issue by jkuipers** [spring-projects/spring-boot#32182] opened 2022-08-29 08:49 UTC
SLF4J 2.0.0 has been released, together with Logback 1.3.0 (JavaEE javax APIs) and 1.4.0 (Jakarta APIs). 
Although the API is backwards compatible, the new SLF4J no longer ships with the `org.slf4j.impl.StaticLoggerBinder` class and now [relies on a service loader mechanism instead](https://www.slf4j.org/faq.html#changesInVersion200). 
This breaks Boot's `LogbackLoggingSystem` class, which expects this class to be present. 

I didn't see a ticket yet to add 2.0 support and also saw that the `LogbackLoggingSystem.java` file on the main branch seems to have the same issue as the version in the last stable release, so I figured I'd create an issue for this. 
At first sight it seems relatively straightforward to check for the class's presence and fallback to the new service loader mechanism if it's missing, but I haven't actually attempted to update the code myself yet; please let me know if you'd like me to contribute a fix, or if you'd prefer to tackle this one within the team.

**Comment by vpavic** [comment] 2022-08-29 09:21
There's already #12649 that tracks this.

**Comment by bclozel** [comment] 2022-08-29 09:21
Closing as a duplicate of #12649

**Closed by bclozel** 2022-08-29 09:21 UTC
Labels: status: waiting-for-triage

**Comment by jkuipers** [comment] 2022-08-29 09:52
Check, sorry for missing the existing issue: it's so old already that it didn't show up in my search results for SLF4J
