### ISSUE TITLE
Jarfilewrapper produces many FinalReference

### ISSUE THREAD

**Issue by yong24huang** [spring-projects/spring-boot#23505] opened 2020-09-27 06:44 UTC
@philwebb, I have already tried the same app with `2.2.10.BUILD-SNAPSHOT` and it looks much better. There is a number of `wrappers` in the heap, but I do not think it will cause problems.

In any case, thank you for the resolution, and I will keep you updated after I get this version live (but it will take me some time).

_Originally posted by @alexey-anufriev in https://github.com/spring-projects/spring-boot/issues/22991#issuecomment-675750350_

Hello, I would like to ask why there are so many FinalReference of jarFileWrapper?
I see that we have a lot of FinalReference to jarFileWrapper, which causes YGC to take more than 100 milliseconds.
![image](https://user-images.githubusercontent.com/33472932/94361117-8f339d00-00e4-11eb-8371-b53a78d83f3a.png)
![image](https://user-images.githubusercontent.com/33472932/94361119-93f85100-00e4-11eb-9835-dca65243c7c5.png)

![image](https://user-images.githubusercontent.com/33472932/94357901-576e2a80-00cf-11eb-9dc3-0e848304c939.png)
After we downgraded the spring boot version, YGC only took more than 10 milliseconds

**Comment by blindarcheology** [comment] 2020-09-27 08:57
Chinese in pictures...

**Comment by yong24huang** [comment] 2020-09-27 09:14
> Chinese in pictures...

Sorry,The picture has been modified. Software is Java Mission Control

**Comment by wilkinsona** [comment] 2020-09-27 10:07
> After we downgraded the spring boot version, YGC only took more than 10 milliseconds

What version were you using and what version did you downgrade to?

Can you provide a small sample that we can use the reproduce the problem?

**Comment by spring-issuemaster** [comment] 2020-10-04 10:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-10-11 10:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-10-11 10:10 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
