### ISSUE TITLE
Spring ErrorWrapperResponse sendErrorIfNecessary in getWriter cause committed response error in standalone container

### ISSUE THREAD

**Issue by kk580kk** [spring-projects/spring-boot#17568] opened 2019-07-18 08:57 UTC
When accessing a missing page in webapp deployed in standalone container (Tomcat), after the calling of `ErrorPageFilter.doFilter` which passes the `ErrorWrapperResponse` and in the `ApplicationDispatcher` which calls the `response.getWriter` trigger from `doForward`, the `response.getWriter` will trigger `ErrorWrapperResponse.getWriter` which calls the `sendErrorIfNecessary` that triggers the container `sendError` and committed the response which will cause the `handleErrorStatus` in `ErrorPageFilter` to fail when check
response is committed or not and prompt the error "Cannot forward to error page for request XXX as the response has already been committed. ...".

In the old version of `ErrorWrapperResponse` , there is no override of the `getWriter`, which won't trigger the `sendError` that cause the committed response to happen early and can forward the error response to the custom error controller.

For now, when accessing a missing page in webapp, the tomcat generic error page will be displayed with the committed response error message instead of forwarding to the custom error controller.

Please fix the `ErrorWrapperResponse.getWriter`.

https://github.com/spring-projects/spring-boot/issues/13951 says

> So if we need customise error controller then we can't override configureDefaultServletHandling with configurer.enable. This problem will only occurred in Spring Boot 1.5.X with Apache Tomcat 8.5.X, while in Spring Boot 1.2.8 with Apache Tomcat 8.0.X, it won't happen.

not work for me.

spring-boot 2.1.3.RELEASE
tomcat 9.0.21
and I hadn't override `DefaultServletHandlerConfigurer` with `configurer.enable`.

**Comment by bclozel** [comment] 2019-07-18 09:11
As mentioned in #13951, please provide a sample application (a github repository or a zipped project) that we can compile and run. This is the best and fastest way to find and solve such problems.

**Comment by kk580kk** [comment] 2019-07-18 14:46
@bclozel  https://github.com/kk580kk/spring-mvc-response-alreadycommited 
this is demo project, please read the readme, follow the instruction, then you can see the error.

**Comment by bclozel** [comment] 2019-07-19 09:36
Hello @kk580kk [I've sent a PR to your repro project](https://github.com/kk580kk/spring-mvc-response-alreadycommited/pull/1), trying to eliminate noise and focus on the error page issue - I've used https://start.spring.io to get a proper maven structure for WAR projects and looked at the [JSP sample for inspiration as well](https://github.com/spring-projects/spring-boot/tree/v2.1.6.RELEASE/spring-boot-samples/spring-boot-sample-web-jsp/).
After those changes I couldn't reproduce the problem anymore.

Could you take another look and let me know how to reproduce the issue now?

**Comment by kk580kk** [comment] 2019-07-21 07:18
Thanks for your support. @bclozel 
The project is much more simple than before.

But not working as except.
Browser http://localhost:8080/ , I can see the right error page is working, that I customized.
Browser http://localhost:8080/data/1  still can  see the problems, when the JSP file is not found, error page is not working as expect.  This is a tomcat's 404 page, not mine.
'''
HTTP Status 404 ? Not Found

Type Status Report

Message /WEB-INF/jsp//grid/grid.jsp

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/9.0.1
'''

This is log 
'''
/Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1/bin/catalina.sh run
[2019-07-21 03:11:50,795] Artifact spring-mvc-response-alreadycommited:war exploded: Waiting for server connection to start artifact deployment...
21-Jul-2019 15:11:52.835 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/9.0.1
21-Jul-2019 15:11:52.842 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 27 2017 17:31:52 UTC
21-Jul-2019 15:11:52.842 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         9.0.1.0
21-Jul-2019 15:11:52.842 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
21-Jul-2019 15:11:52.843 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.15
21-Jul-2019 15:11:52.843 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
21-Jul-2019 15:11:52.843 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
21-Jul-2019 15:11:52.843 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_181-b13
21-Jul-2019 15:11:52.843 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
21-Jul-2019 15:11:52.843 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /Users/huangjie/Library/Caches/IntelliJIdea2018.2/tomcat/Unnamed_spring-mvc-response-alreadycommited
21-Jul-2019 15:11:52.844 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1
21-Jul-2019 15:11:52.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/Users/huangjie/Library/Caches/IntelliJIdea2018.2/tomcat/Unnamed_spring-mvc-response-alreadycommited/conf/logging.properties
21-Jul-2019 15:11:52.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
21-Jul-2019 15:11:52.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote=
21-Jul-2019 15:11:52.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=1099
21-Jul-2019 15:11:52.845 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
21-Jul-2019 15:11:52.846 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.password.file=/Users/huangjie/Library/Caches/IntelliJIdea2018.2/tomcat/Unnamed_spring-mvc-response-alreadycommited/jmxremote.password
21-Jul-2019 15:11:52.846 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.access.file=/Users/huangjie/Library/Caches/IntelliJIdea2018.2/tomcat/Unnamed_spring-mvc-response-alreadycommited/jmxremote.access
21-Jul-2019 15:11:52.846 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=127.0.0.1
21-Jul-2019 15:11:52.846 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
21-Jul-2019 15:11:52.846 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
21-Jul-2019 15:11:52.846 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/Users/huangjie/Library/Caches/IntelliJIdea2018.2/tomcat/Unnamed_spring-mvc-response-alreadycommited
21-Jul-2019 15:11:52.846 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1
21-Jul-2019 15:11:52.847 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1/temp
21-Jul-2019 15:11:52.847 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/huangjie/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
21-Jul-2019 15:11:53.195 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
21-Jul-2019 15:11:53.236 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
21-Jul-2019 15:11:53.274 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
21-Jul-2019 15:11:53.276 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
21-Jul-2019 15:11:53.277 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1287 ms
21-Jul-2019 15:11:53.328 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
21-Jul-2019 15:11:53.329 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/9.0.1
21-Jul-2019 15:11:53.342 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
21-Jul-2019 15:11:53.361 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
21-Jul-2019 15:11:53.365 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 88 ms
Connected to server
[2019-07-21 03:11:53,488] Artifact spring-mvc-response-alreadycommited:war exploded: Artifact is being deployed, please wait...
21-Jul-2019 15:11:56.995 INFO [RMI TCP Connection(2)-127.0.0.1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.6.RELEASE)

2019-07-21 15:11:59.268  INFO 3166 --- [on(2)-127.0.0.1] c.b.errrorreport.ServletInitializer      : Starting ServletInitializer v0.0.1-SNAPSHOT on huangjiedeMacBook-Pro.local with PID 3166 (/Volumes/Transcend/Workspace/github.com/kk580kk/spring-mvc-response-alreadycommited/target/spring-mvc-response-alreadycommited-0.0.1-SNAPSHOT/WEB-INF/classes started by huangjie in /Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1/bin)
2019-07-21 15:11:59.281  INFO 3166 --- [on(2)-127.0.0.1] c.b.errrorreport.ServletInitializer      : No active profile set, falling back to default profiles: default
2019-07-21 15:12:01.965  INFO 3166 --- [on(2)-127.0.0.1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2501 ms
2019-07-21 15:12:03.109  INFO 3166 --- [on(2)-127.0.0.1] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
21-Jul-2019 15:12:03.346 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1/webapps/manager]
21-Jul-2019 15:12:03.423 INFO [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1/webapps/manager] has finished in [77] ms
2019-07-21 15:12:03.755  INFO 3166 --- [on(2)-127.0.0.1] c.b.errrorreport.ServletInitializer      : Started ServletInitializer in 6.206 seconds (JVM running for 13.229)
[2019-07-21 03:12:03,796] Artifact spring-mvc-response-alreadycommited:war exploded: Artifact is deployed successfully
[2019-07-21 03:12:03,796] Artifact spring-mvc-response-alreadycommited:war exploded: Deploy took 10,309 milliseconds
2019-07-21 15:12:04.224  INFO 3166 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-07-21 15:12:04.244  INFO 3166 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 19 ms
2019-07-21 15:12:12.627 ERROR 3166 --- [nio-8080-exec-5] o.s.b.w.servlet.support.ErrorPageFilter  : Cannot forward to error page for request [/data/1] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
2019-07-21 15:12:15.805 ERROR 3166 --- [nio-8080-exec-6] o.s.b.w.servlet.support.ErrorPageFilter  : Cannot forward to error page for request [/data/1] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
/Volumes/Transcend/Applications/tomcat/apache-tomcat-9.0.1/bin/catalina.sh stop
Disconnected from server
'''

**Comment by bclozel** [comment] 2019-07-22 07:48
I believe this is now working as expected. Clients requesting an unknown resource will get the Spring Boot error page with a 404 as expected.

You're pointing at the fact that when forwarding a request to the Servlet container for rendering a JSP that doesn't exist, the Servlet container will send an error and mark the response as committed for `"Disabling the response for further output"` (here, tomcat will get the response writer and close it).

I believe https://github.com/spring-projects/spring-boot/issues/11814#issuecomment-361314265 was exactly fixing that case - before that fix, the HTTP response status would be "200 OK" instead of 404. But we can't expect the Spring Boot error page to be rendered when the underlying request handler might have written to the response: at that point, we can't change the response status and writing to the body might result with a garbled response.

**Closed by bclozel** 2019-07-22 07:48 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by kk580kk** [comment] 2019-07-23 07:59
> when forwarding a request to the Servlet container for rendering a JSP that doesn't exist, the Servlet container will send an error and mark the response as committed

@bclozel 
Em, Maybe tomcat-render-404-page  is a typical engineer answer . But not a user-friendly method . I thought this is not a good solution.

ErrorPageFilter is not possibly replaced by other by @Configration annotation, Please  add @BeanIsNotExist or other condition to let me change the implementation .

**Comment by philwebb** [comment] 2019-07-24 08:13
> ErrorPageFilter is not possibly replaced by other by @Configration annotation, Please add @BeanIsNotExist or other condition to let me change the implementation .

I'm afraid that's not possible because the bean is created early. You can use `setRegisterErrorPageFilter(false)` in your `SpringBootServletInitializer` class.
