### ISSUE TITLE
actuator endpoint /actuator/logfile empty when using Spring Cloud Config

### ISSUE THREAD

**Issue by agustinventura** [spring-projects/spring-boot#20795] opened 2020-04-01 15:36 UTC
Hi all,

First, thank you for your great job, I've been a Spring user for 12 years and Spring Boot user for 5 and this is my first issue. I think that says all about the incredible work you do.

Seems like this issue is related somehow to #18191 but slightly different. 
I'm using Spring Boot 2.2.6.RELEASE and spring-cloud Hoxton.SR3. My application.properties is hosted in Spring Cloud Config Server and includes logfile name as:
logging.file.name=logs/${spring.application.name}.log

However, when I access /actuator/logfile I get a 404 response. Setting actuate logger to trace shows this error:
`
o.s.b.a.logging.LogFileWebEndpoint       : Missing 'logging.file.name' or 'logging.file.path' properties
`

If I add to bootstrap.yml following configuration:
`
logging:
  file:
    name: logs/${spring.application.name}.log
`
Endpoint starts working as expected, so it is as if /actuator/logfile is configured before resolving properties from Config Server.

Sorry if this isn't the right place to open the issue, I will be happy to report it to the Spring Cloud team.

Thank you.

**Comment by wilkinsona** [comment] 2020-04-01 15:48
Thanks for the report. I think this is a duplicate of #18191 as the behaviour you have describes matches the behaviour described in [this comment](https://github.com/spring-projects/spring-boot/issues/18191#issuecomment-529901025):

When I retrieve the properties through Spring Cloud Config Server, the 404 error occurs, when I put the same properties in application.yml, everything works fine.

https://github.com/spring-cloud/spring-cloud-commons/issues/608 is tracking a change to Spring Cloud that will fix this.

**Closed by wilkinsona** 2020-04-01 15:48 UTC
Labels: status: waiting-for-triage
