### ISSUE TITLE
Quartz Scheduler name not set by the spring.quartz.properties.org.quartz.scheduler.instanceName property

### ISSUE THREAD

**Issue by davem-foreflight** [spring-projects/spring-boot#14243] opened 2018-08-29 22:06 UTC
## Summary:

The spring boot QuartzProperties configuration property: `spring.quartz.properties.org.quartz.scheduler.instanceName` Is not picked up when  the quartz factory is created resulting in the quartz scheduler having the beanName as the scheduler name.

##  Possible Fix

Perhaps QuartzAutoConfiguration could be enhanced to look for the StdSchedulerFactory properties utilized by the SchedulerFactoryBean initSchedulerFactory() method.  

OR

QuartzProperties could simply add a property `schedularName` that would be applied to the new factory rather then relying on the properties.

## Workaround

Implement `SchedulerFactoryBeanCustomizer` and set the name via the `customize()` method. 
   

## More Details

Issue has been raised in:  https://jira.spring.io/browse/SPR-16884

**Comment by snicoll** [comment] 2018-08-30 06:34
I've left a comment on the related Jira issue. Let's see what happens there first.

**Comment by hiirage** [comment] 2018-09-18 07:10
Quartz prefix has been cut off after `QuartzProperties` loading process, then those properties without prefix "org.quartz" cannot be handled properly by `SchedulerFactoryBean`.

**Comment by snicoll** [comment] 2018-09-19 10:19
I've managed to discuss this with Jurgen and we're going to fix that in framework (see [SPR-16884](https://jira.spring.io/browse/SPR-16884) for more details). We'll update to this version in due course.

Duplicate of #14481

**Comment by snicoll** [comment] 2018-09-20 09:18
It turns out that the framework change is shadowed by the fact we always call `setSchedulerName` as the dedicated property has a default. 

We should rather not set it if no value is set and let the default bean name do its job. If someone has configured the name using the quartz property in such scenario it will be taken into account.

**Closed** 2018-09-20 09:28 UTC
Labels: type: bug
