### ISSUE TITLE
Use ObjectProvider<Validator> instead of @Lazy in `ValidationAutoConfiguration`

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-boot#32133] opened 2022-08-22 12:23 UTC
As suggested by @jhoeller [here](https://github.com/spring-projects/spring-framework/issues/28980#issuecomment-1222263665), could it be possible to update `ValidationAutoConfiguration` to change `@Lazy` to `ObjectProvider<Validator>` [here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.java#L72)?

See more details on https://github.com/spring-projects/spring-framework/issues/28990.

**Comment by snicoll** [comment] 2022-08-22 12:45
Sorry I haven't see this and I created an issue as well.

Duplicate of #32134

**Closed by snicoll** 2022-08-22 12:45 UTC
Labels: status: waiting-for-triage
