### ISSUE TITLE
Add workaround for containers' handling of async timeouts and custom error pages

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#4799] opened 2015-12-17 14:09 UTC
See https://jira.spring.io/browse/SPR-12764
Affects spring-boot 1.3.

Starting from a fresh spring-boot-starter-web application, add the following controller:

```
@Controller
public class TestController {
    @RequestMapping("/timeout")
    public ListenableFuture<String> timeout() {
        return new SettableListenableFuture<>();
    }
}
```

Start the application and send a GET to /timeout.

If using Tomcat, no response is served:

```
2015-12-17 13:04:30.139 ERROR 3152 --- [nio-8080-exec-4] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]

java.lang.IllegalStateException: Cannot forward after response has been committed
at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:328) ~[tomcat-embed-core-8.0.28.jar:8.0.28]
```

If using Jetty then a 503 is served:

```
2015-12-17 13:10:23.914  WARN 5736 --- [tp2049837144-18] org.eclipse.jetty.server.HttpChannel     : /timeout

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: STREAM
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
...

2015-12-17 13:58:34.105  WARN 9116 --- [qtp555136651-21] org.eclipse.jetty.server.HttpChannel     : Could not send response error 500: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: STREAM
```

I was expecting to see the whitelabel error page with the details of a timeout exception.

**Comment by wilkinsona** [comment] 2015-12-17 15:46
Tomcat serves a 500 with no content:

```
curl -v localhost:8080/timeout
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Server: Apache-Coyote/1.1
< Transfer-Encoding: chunked
< Date: Thu, 17 Dec 2015 15:41:11 GMT
< Connection: close
<
* Closing connection 0
```

Jetty serves a 503 with some of its own HTML:

```
 curl -v localhost:8080/timeout
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Date: Thu, 17 Dec 2015 15:43:14 GMT
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html; charset=ISO-8859-1
< Content-Length: 295
< Server: Jetty(9.2.14.v20151106)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 503 </title>
</head>
<body>
<h2>HTTP ERROR: 503</h2>
<p>Problem accessing /timeout. Reason:
<pre>    Service Unavailable</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
* Connection #0 to host localhost left intact
```

Undertow serves a 503 with no content:

```
curl -v localhost:8080/timeout
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Connection: keep-alive
< Content-Length: 0
< Date: Thu, 17 Dec 2015 15:45:11 GMT
<
* Connection #0 to host localhost left intact
```

**Comment by wilkinsona** [comment] 2015-12-17 16:17
On Tomcat a failure occurs while it's trying to route the request to Boot's custom error page. It uses a forward which fails due to the response already being committed (despite an earlier check that the response isn't committed). Boot hasn't got a look in at this point. This looks like a Tomcat bug to me.

Things get a little further on Jetty. The request is passed to Boot's error controller (via its error page registration). It hands the request successfully and returns. For whatever reason, Jetty then discards the response from the error controller and returns its own. This looks like a Jetty bug to me.

Undertow's similar to Tomcat in that things appear to go wrong before Boot's custom error controller gets a chance to do anything. It logs the following exception to System.err before returning the 503:

```
Exception in thread "XNIO-2 task-2" java.lang.IllegalStateException: UT010025: Async request already dispatched
	at io.undertow.servlet.spec.AsyncContextImpl.dispatch(AsyncContextImpl.java:148)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:123)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:347)
	at org.springframework.web.context.request.async.WebAsyncManager.access$200(WebAsyncManager.java:57)
	at org.springframework.web.context.request.async.WebAsyncManager$5.run(WebAsyncManager.java:389)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:143)
	at io.undertow.servlet.spec.AsyncContextImpl.onAsyncTimeout(AsyncContextImpl.java:620)
	at io.undertow.servlet.spec.AsyncContextImpl.access$800(AsyncContextImpl.java:71)
	at io.undertow.servlet.spec.AsyncContextImpl$TimeoutTask$1.run(AsyncContextImpl.java:494)
	at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:580)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Given that the other two containers don't appear to have this problem, this looks like an Undertow bug to me. @rstoyanchev This error is happening in Spring MVC's async handling. Do you agree that this looks like Undertow's misbehaving?

**Comment by wilkinsona** [comment] 2015-12-17 17:20
This sample reproduces the failure on Tomcat. It's pure Tomcat, i.e. there's no Spring MVC or Spring Boot involved. The key to triggering the problem is calling `sendError` when the listener is notified of the timeout:

```
package com.example;

import java.io.File;
import java.io.IOException;

import javax.servlet.AsyncContext;
import javax.servlet.AsyncEvent;
import javax.servlet.AsyncListener;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.catalina.Context;
import org.apache.catalina.startup.Tomcat;
import org.apache.tomcat.util.descriptor.web.ErrorPage;

public class TomcatAsyncTimeout {

	public static void main(String[] args) throws Exception {
		Tomcat tomcat = new Tomcat();
		tomcat.setPort(8080);
		Context context = tomcat.addContext("",
				new File(System.getProperty("java.io.tmpdir")).getAbsolutePath());
		tomcat.addServlet("", "timeout", AsyncServlet.class.getName())
				.setAsyncSupported(true);
		tomcat.addServlet("", "error", ErrorServlet.class.getName());
		context.addServletMapping("/timeout", "timeout");
		context.addServletMapping("/error", "error");
		ErrorPage errorPage = new ErrorPage();
		errorPage.setLocation("/error");
		context.addErrorPage(errorPage);
		tomcat.start();
		while (true) {
			Thread.sleep(1000);
		}
	}

	public static class AsyncServlet extends HttpServlet {

		@Override
		protected void doGet(HttpServletRequest req, HttpServletResponse resp)
				throws ServletException, IOException {
			AsyncContext context = req.startAsync();
			context.setTimeout(5000);
			context.addListener(new AsyncListener() {

				@Override
				public void onTimeout(AsyncEvent event) throws IOException {
					((HttpServletResponse) event.getSuppliedResponse()).sendError(503);
				}

				@Override
				public void onStartAsync(AsyncEvent event) throws IOException {
				}

				@Override
				public void onError(AsyncEvent event) throws IOException {
				}

				@Override
				public void onComplete(AsyncEvent event) throws IOException {
				}
			});
		}

	}

	public static class ErrorServlet extends HttpServlet {

		@Override
		protected void doGet(HttpServletRequest req, HttpServletResponse resp)
				throws ServletException, IOException {
			resp.getWriter().println("Boom");
		}

	}

}
```

**Comment by rstoyanchev** [comment] 2015-12-17 17:45
Indeed  that sums it up. Spring MVC has default timeout handling in `TimeoutDeferredResultProcessingInterceptor` which calls `sendError` with 503. 

The response should be done at that point and Tomcat should not be forwarding to "/error" as far as I can see. For that it does it as an ASYNC dispatch and not as an ERROR dispatch which is yet another twist.

Undertow also does an ERROR dispatch to "/error". That gets to Spring MVC but fails because  `request.isAsyncStarted` returns `true` and essentially the illegal state check is working as expected:
````
java.lang.IllegalStateException: Can't set AsyncWebRequest with concurrent handling in progress
	at org.springframework.util.Assert.state(Assert.java:392) ~[spring-core-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.context.request.async.WebAsyncManager.setAsyncWebRequest(WebAsyncManager.java:107) ~[spring-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
````

Jetty also forwards to "/error" but at least `request.isAsyncStarted` returns `false` so we get through there but again it makes no sense to be even going into "/error".

**Comment by wilkinsona** [comment] 2015-12-17 17:48
On Jetty, I've observed that if `sendError` is not called, the contents of the custom error page are returned in a 500 response. If a call to `sendError(503)` is made, the response status is set to 503 but the custom error page is lost and Jetty's default response is returned instead. I've opened a [Jetty bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484600).

**Comment by OrangeDog** [comment] 2015-12-17 17:50
So every possible servlet provider has it's own bug, and there's nothing spring-boot can do to configure things so that they work out of the box?

**Comment by wilkinsona** [comment] 2015-12-17 17:50
@markt-asf What's your take on the behaviour in Tomcat that I've [described above](https://github.com/spring-projects/spring-boot/issues/4799#issuecomment-165519733)?

**Comment by wilkinsona** [comment] 2015-12-17 17:51
@OrangeDog Based in my current understanding, that's an accurate summary of the situation.

**Comment by wilkinsona** [comment] 2015-12-17 18:02
@rstoyanchev Undertow's interesting. In my sample I don't have the `isAsyncStarted` check and that allows me to get a 503 response that contains my custom error page:

```
package com.example;

import java.io.IOException;

import javax.servlet.AsyncContext;
import javax.servlet.AsyncEvent;
import javax.servlet.AsyncListener;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import io.undertow.Undertow;
import io.undertow.servlet.Servlets;
import io.undertow.servlet.api.DeploymentInfo;
import io.undertow.servlet.api.DeploymentManager;
import io.undertow.servlet.api.ErrorPage;

public class UndertowAsyncTimeout {

	public static void main(String[] args) throws ServletException {
		DeploymentInfo servletBuilder = Servlets.deployment()
				.setClassLoader(UndertowAsyncTimeout.class.getClassLoader())
				.setContextPath("/").setDeploymentName("test.war")
				.addErrorPage(new ErrorPage("/error")).addServlets(
						Servlets.servlet("AsyncServlet", AsyncServlet.class)
								.setAsyncSupported(true).addMapping("/timeout"),
						Servlets.servlet("ErrorServlet", ErrorServlet.class)
								.setAsyncSupported(true).addMapping("/error"));
		DeploymentManager manager = Servlets.defaultContainer()
				.addDeployment(servletBuilder);
		manager.deploy();
		Undertow server = Undertow.builder().addHttpListener(8080, "localhost")
				.setHandler(manager.start()).build();
		server.start();
	}

	public static class AsyncServlet extends HttpServlet {

		@Override
		protected void doGet(HttpServletRequest req, HttpServletResponse resp)
				throws ServletException, IOException {
			AsyncContext context = req.startAsync();
			context.setTimeout(5000);
			context.addListener(new AsyncListener() {

				@Override
				public void onTimeout(AsyncEvent event) throws IOException {
					HttpServletResponse response = (HttpServletResponse) event
							.getSuppliedResponse();
					if (!response.isCommitted()) {
						response.sendError(503);
					}
				}

				@Override
				public void onStartAsync(AsyncEvent event) throws IOException {
				}

				@Override
				public void onError(AsyncEvent event) throws IOException {
				}

				@Override
				public void onComplete(AsyncEvent event) throws IOException {
				}
			});
		}

	}

	public static class ErrorServlet extends HttpServlet {

		@Override
		protected void doGet(HttpServletRequest req, HttpServletResponse resp)
				throws ServletException, IOException {
			resp.getWriter().println("Error!");
		}

	}

}
```

```
$ curl -i localhost:8080/timeout
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Content-Length: 7
Date: Thu, 17 Dec 2015 17:59:54 GMT

Error!
```

**Comment by rstoyanchev** [comment] 2015-12-17 18:38
After a call to `response.sendError` the response is committed. It looks like containers make an ERROR dispatch still even if you can't (or shouldn't be able to) change the response any more. 

Whether `request.isAsyncStarted` should return true or false at that point is a bit of a grey area and it seems Jetty and Undertow behave differently. From a Spring Framework perspective the illegal state check basically says we expect asyncStarted to be set as a result of invoking the controller method and  we don't expect it to be `true` prior to that. 

I think it may be possible for Boot to provide some better default configuration that would make things more explicit. I tried the following:
````java
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }


    @Configuration
    static class WebConfig extends WebMvcConfigurerAdapter {

        @Override
        public void configureAsyncSupport(AsyncSupportConfigurer configurer) {
            configurer.registerDeferredResultInterceptors(
                    new DeferredResultProcessingInterceptorAdapter() {
                        
                        @Override
                        public <T> boolean handleTimeout(NativeWebRequest request, DeferredResult<T> result) {
                            result.setErrorResult(new ServiceUnavailableException());
                            return false;
                        }
                    });
        }
    }

    @ResponseStatus(HttpStatus.SERVICE_UNAVAILABLE)
    static class ServiceUnavailableException extends Exception { }
}
````
This dispatches back into the container with an @ResponseStatus Exception which is then handled as usual. Seems to work fine on Jetty and Undertow. On Tomcat the response status is 503 but it fails to write the custom response body with a BrokenPipe exception. Not sure what that's about but I think this the path to follow.

One more note that Boot would have to be careful to register the above interceptor at the end. This could probably be done by overriding `configureAsyncSupport` from `EnableWebMvcConfiguration` and calling super first.

**Comment by wilkinsona** [comment] 2015-12-17 19:09
> After a call to response.sendError the response is committed. It looks like containers make an ERROR dispatch still even if you can't (or shouldn't be able to) change the response any more.

I think that's happening because it's a custom error page to which the request is being dispatched. For that to work it has to perform a dispatch after `sendError` has been called.

**Comment by markt-asf** [comment] 2015-12-17 19:56
Error handling in the async case isn't as well defined in the spec as it could be and has evolved over time as users identify different use cases (custom error pages, errors on non-container threads, application error handling etc.). We already have some test cases in Tomcat for this area and it looks like you have a suitable test case for this so open a BZ entry and someone will take a look.

**Comment by wilkinsona** [comment] 2015-12-18 11:02
Thanks, @markt-asf. I've opened https://bz.apache.org/bugzilla/show_bug.cgi?id=58751.

**Comment by wilkinsona** [comment] 2015-12-18 11:17
@rstoyanchev Thanks for the suggestion. As you said above, it works well on Jetty and Undertow.

@OrangeDog I'd recommend using Rossen's suggestion with Jetty or Undertow for now. We'll probably add it, or something very similar to Boot, but I'd prefer to do so once the Tomcat bug that I have opened has been resolved so that it works on all three containers that we support.

**Comment by andrashatvani** [comment] 2016-08-02 08:03
I see the same error occurring with Spring Boot 1.4.0:
`java.lang.IllegalStateException: Can't set AsyncWebRequest with concurrent handling in progress`. 
What's the tl;dr of this issue? Can I switch to 1.4 despite this issue?

**Comment by OrangeDog** [comment] 2016-08-02 10:17
@andrashatvani all servlet containers have a different bug here.
The least broken appears to be Jetty, while the most broken is Tomcat.

**Comment by gregw** [comment] 2016-10-21 04:33
Note that in the soon to be release jetty-9.4.0 we have revisited the whole area of async error handling and believe we have further improved the interpretation of the vague spec, whilst reducing differences with Tomcat et al.   So worthwhile retesting this once a 9.4.0 RC is available (next week) to see if we have made jetty more or less broken :)

**Comment by rstoyanchev** [comment] 2016-10-21 13:17
@andrashatvani that was fixed recently on the Spring Framework side https://jira.spring.io/browse/SPR-14444.

**Comment by rstoyanchev** [comment] 2016-10-21 13:26
@wilkinsona note that there was one more recent Spring Framework fix [SPR-14669](https://jira.spring.io/browse/SPR-14669) adapting to the more recent behavior of Servlet containers which do an ERROR dispatch following timeout even if the listener called `sendError`. As a result of the change the default handling of timeouts should be more reliable.

**Comment by philwebb** [comment] 2018-07-27 15:47
A lot has changed in Spring Framework since this bug was originally raised so we'll need to run another round of tests to see if there's still and issue.

**Comment by wilkinsona** [comment] 2018-09-19 11:35
Here's the current state of play with Spring Boot 2.0.5.RELEASE:

Jetty:

```
$ curl -v localhost:8080/timeout
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Date: Wed, 19 Sep 2018 11:30:37 GMT
< Content-Type: application/json;charset=utf-8
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"timestamp":"2018-09-19T11:31:07.662+0000","status":503,"error":"Service Unavailable","message":"Service Unavailable","path":"/timeout"}
```

Tomcat:

```
$ curl -v localhost:8080/timeout
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 19 Sep 2018 11:29:22 GMT
< Connection: close
< 
* Closing connection 0
{"timestamp":"2018-09-19T11:29:22.889+0000","status":503,"error":"Service Unavailable","message":"No message available","path":"/timeout"}
```

Undertow:

```
$ curl -v localhost:8080/timeout
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Connection: keep-alive
< Transfer-Encoding: chunked
< Content-Type: application/json;charset=UTF-8
< Date: Wed, 19 Sep 2018 11:32:39 GMT
< 
* Connection #0 to host localhost left intact
{"timestamp":"2018-09-19T11:32:39.156+0000","status":503,"error":"Service Unavailable","message":"Service Unavailable","path":"/timeout"}
```

All three containers are now consistent and are producing the desired response.

**Comment by wilkinsona** [comment] 2018-09-19 12:33
And with 1.5.16.RELEASE

Jetty:

```
curl -v localhost:8080/timeout
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Date: Wed, 19 Sep 2018 12:27:38 GMT
< Content-Type: application/json;charset=utf-8
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"timestamp":1537360088100,"status":503,"error":"Service Unavailable","exception":"org.springframework.web.context.request.async.AsyncRequestTimeoutException","message":"Service Unavailable","path":"/timeout"}
```

Tomcat:

```
 curl -v localhost:8080/timeout
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 19 Sep 2018 12:29:56 GMT
< Connection: close
< 
* Closing connection 0
{"timestamp":1537360196088,"status":503,"error":"Service Unavailable","exception":"org.springframework.web.context.request.async.AsyncRequestTimeoutException","message":"No message available","path":"/timeout"}
```

Undertow:

```
curl -v localhost:8080/timeout
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /timeout HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Connection: keep-alive
< Transfer-Encoding: chunked
< Content-Type: application/json;charset=UTF-8
< Date: Wed, 19 Sep 2018 12:26:19 GMT
< 
* Connection #0 to host localhost left intact
{"timestamp":1537359978983,"status":503,"error":"Service Unavailable","exception":"org.springframework.web.context.request.async.AsyncRequestTimeoutException","message":"Service Unavailable","path":"/timeout"}
```

This looks good too. Closing.

**Closed by wilkinsona** 2018-09-19 12:33 UTC
Labels: status: waiting-for-triage
