### ISSUE TITLE
javax.validation.ValidationException: HV000183 when using exploded jar

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-boot#16397] opened 2019-03-31 21:10 UTC
Spring boot 2.1.3

If I start application from jar (`java -jar app.jar`) everything works perfecly. However, using exploded jar (separation between dependencies and application resources as sugested here: https://spring.io/guides/gs/spring-boot-docker) I get such exception:
```
Caused by: javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:123) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:47) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolator(ConfigurationImpl.java:474) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(ConfigurationImpl.java:650) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getMessageInterpolator(ConfigurationImpl.java:397) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:183) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:364) ~[hibernate-validator-6.0.14.Final.jar:6.0.14.Final]
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103) ~[validation-api-2.0.1.Final.jar:na]
	at org.springframework.validation.beanvalidation.CustomValidatorBean.afterPropertiesSet(CustomValidatorBean.java:75) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cloud.stream.binding.BindingService.<init>(BindingService.java:85) ~[spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.stream.config.BindingServiceConfiguration.bindingService(BindingServiceConfiguration.java:204) ~[spring-cloud-stream-2.1.2.RELEASE.jar:2.1.2.RELEASE]
```

**Comment by wilkinsona** [comment] 2019-04-01 06:24
It looks like the EL API or implementation has been lost. I can’t tell how without some more information. Can you please provide a minimal example that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2019-04-08 06:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-15 06:25
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-15 06:25 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
