### ISSUE TITLE
Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by ghsatpute** [spring-projects/spring-boot#13796] opened 2018-07-17 12:16 UTC
Spring Boot Version: `2.0.3.RELEASE`

`application.properties`
```
###--- Database   ---###
spring.datasource.url = jdbc:mysql://localhost:3306/mydb
spring.datasource.username = root
spring.datasource.password = password
spring.datasource.platform = mysql
spring.datasource.driver-class-name = com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = create
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
```

Pom.xml contains 
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.3.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    ... 
        <!-- Database dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
    </dependencies>

```

When I run my application, I get following error 

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-07-17 12:31:12.528 ERROR 15387 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

```

After searching for a bit, I found that if I use earlier versions like `1.5.13.RELEASE` this doesn't happen.

**Comment by snicoll** [comment] 2018-07-17 12:23
Failure analysis doesn't match the bits of configuration you've shared. It's a bit unclear at this point where the problem can be. Rather than pasting code in text, please share a sample we can clone and run that reproduces the problem.

**Comment by MustaphaCh** [comment] 2018-07-25 10:15
Hello , 
I have the same issue using the version 2.0.0.RELEASE of spring boot  using the configuration bellow :
`spring:
  dao:
    exceptiontranslation:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:35432/db?binaryTransferEnable=142
    hikari:
      pool-name: junit-pool
      username: username
      password: password
      driver-class-name: org.postgresql.Driver  `

**Comment by snicoll** [comment] 2018-07-25 11:02
@MustaphaCh thank you for trying to help but that's not a sample we can clone and run ourselves. If you have one, we're more than happy to have a look.

**Comment by MustaphaCh** [comment] 2018-07-25 11:31
@snicoll   i attach the application.yml you can check my configuration
[application.zip](https://github.com/spring-projects/spring-boot/files/2227704/application.zip)

**Comment by snicoll** [comment] 2018-07-25 11:43
@MustaphaCh thanks again but a configuration file is not a sample that we can run ourselves.

**Comment by MustaphaCh** [comment] 2018-07-25 13:10
@snicoll sorry the problem is fixed it was related to a profile.

**Comment by spring-issuemaster** [comment] 2018-08-09 11:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-08-09 11:38 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by schawla3** [comment] 2018-08-15 18:44
I have the same error but I'm not able to figure out what's the issue.

**Comment by schawla3** [comment] 2018-08-15 18:44
Is there a solution for it, I m using mysql connector in a spring boot app and its running into similar error 
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class

**Comment by ghsatpute** [comment] 2018-08-15 19:46
Apologies for replying late. I was not able to isolate the issue. 

My application organization looked like below
 ```
  Commons 
         |
         ↓
     Module1
 ```
`Commons` was parent to `Module1`. 

I had created a `BaseEntity` having JPA annotations in my commons module. In commons dependency was specified as 

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
```

Once I added the `<scope>provided</scope>`
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<scope>provided</scope>
		</dependency>
```

The issue got resolved for me. Unfortunately, I'm not able to do further analysis nor I can share the code.

**Comment by darm191065** [comment] 2018-08-26 01:51
the same issue worked for me on the same release

Thank for the fix mate

**Comment by amitshrivastava97** [comment] 2018-08-27 19:31
hi

**Comment by abhishekkarigar** [comment] 2018-10-21 08:51
make sure the mysql is started , 
and update the application,properties

**Comment by Tsakirogf** [comment] 2018-12-15 12:17
This fix worked for me aswell. Well done @ghsatpute however I would like to put my experience. My project was working perfectly with Eclipse. I didn't had a problem with it before I move the project to intellij. Going back to eclipse and removing your fix, works.

**Comment by ghsatpute** [comment] 2018-12-15 15:53
@Tsakirogf always happy to help. 
For me, it did work on IntelliJ after the fix.

**Comment by Tsakirogf** [comment] 2018-12-15 18:58
Yes as I said, it worked for me.What I wanted to spot is that without the fix it was working for Eclipse.

**Comment by oselene** [comment] 2019-01-22 11:58
please can you explain where i can find the commons and module1 you identified in your explanation

**Comment by ghsatpute** [comment] 2019-01-22 15:43
@oselene Those are my projects and taken here as an example. For you, those modules would be different.

**Comment by premierDE** [comment] 2019-02-12 15:34
Hello,
I am facing the same issue with Spring boot 2.1.2 release

**Comment by snicoll** [comment] 2019-02-12 15:37
@premierDE that comment is not very helpful. If you need help, please consider asking a question on StackOverflow or join the community on Gitter. If you believe you've found a bug in Spring Boot, attach a minimal sample we can run ourselves and we can reopen this issue.

**Comment by trantienduchn** [comment] 2019-02-19 16:18
I got the same problem with spring-boot 2.1.3 RELEASE. I marked my project with `<packaging>pom</packaging>` (stupid) so It didn't work, removing this resolved my issue.

**Comment by shaileshoptimizeq** [comment] 2019-02-27 07:30
<packaging>jar</packaging>
<packaging>war</packaging>
choose any of the above if you don't have any sub module in project.
