### ISSUE TITLE
Metadata for "logging.level.values" should be upper case

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-boot#5327] opened 2016-03-03 17:56 UTC
See https://issuetracker.springsource.com/browse/STS-4336
for details.

**Comment by wilkinsona** [comment] 2016-03-04 07:42
I don't think we should change the metadata, at least not without exploring the possibility of removing the case sensitivity from our logging system.

**Comment by wilkinsona** [comment] 2016-03-04 07:57
Spring Boot is [already case insensitive](https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot/src/main/java/org/springframework/boot/logging/LoggingApplicationListener.java#L370) so the metadata matches Boot's own capabilities.

Looking at the error reported in the STS issue, the issue is actually in Spring Cloud's `LoggingRebinder`. Unlike Spring Boot, [it is case sensitive](https://github.com/spring-cloud/spring-cloud-commons/blob/v1.1.0.RC1/spring-cloud-context/src/main/java/org/springframework/cloud/logging/LoggingRebinder.java#L67-L79). I think this needs to be fixed in Spring Cloud Commons.

/cc @dsyer

**Closed by wilkinsona** 2016-03-04 07:57 UTC
Labels: waiting-for-triage

**Comment by dsyer** [comment] 2016-03-04 08:53
Why do we publish metadata with lower case values though? They are always upper case in console logs.

**Comment by wilkinsona** [comment] 2016-03-04 09:00
> Why do we publish metadata with lower case values though?

Why not? It's consistent with everything else and is also easier to type. We support both and Logback for one (I haven't checked Log4j2) [uses both lower- and upper-case in its documentation](http://logback.qos.ch/manual/configuration.html).

> They are always upper case in console logs

I suspect that's just a function of the logging level pattern

**Comment by snicoll** [comment] 2016-03-04 09:04
Our canonical format is lower case hyphen, I see no reason to deviate from that. And it's upper case only because it's backed by an enum and the standard for an enum value is to be upper case. That's really no reason to put the value in upper case in our doc.

**Comment by kdvolder** [comment] 2016-03-04 16:17
It would be good to have some consistency and clarity about what the tools
(and metadata authors) are supposed to do re upper/lower case for
'valueHints' in general. I don't think that this is even mentioned in the
docs about the metadata format.

In the current metadata, I found that there are some metadata that provide
value hints in upper-case (e.g. 'management.health.status.order') and some
in lowercase (e.g. logging.level). As I assumed that the valueHints are
manually provided and depend on some 'ad-hoc' implemented behavior rather
than the same binding mechanics used by the automatically inferred from
annotations, I naturally assumed that these values are to be types 'as is'
as they might not follow the same 'relaxed naming' rules.

If hints are supposed to be subject to relaxed name conversions, fine make
that clear. However, I do wonder what mechanism is there then to ensure
that whatever library ends up interpreting the values will actually accept
all the different 'aliases' of a relaxed name as equivalent?

Kris
