### ISSUE TITLE
Migration guide 2.0.x to 2.1.x

### ISSUE THREAD

**Issue by snuyanzin** [spring-projects/spring-boot#17532] opened 2019-07-16 10:07 UTC
Where I could find migration 2.0.x to 2.1.x guide?
I tried to update versions (2.0.9 to 2.1.6) and faced with 
```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1658)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1217)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 89 more

```
I guess there could be more issues. It would be nice to look at a guide

**Comment by wilkinsona** [comment] 2019-07-16 10:17
We don't provide migration guides for minor releases. We do, however, publish release notes on the wiki. The release notes for 2.1 are [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes).

If you've encountered something that isn't covered by the release notes, then please let us know and we can take a look. We'll need more details than a stack trace to be able to diagnose the problem. A minimal sample that reproduces it, either zipped and attached to this issue or in a separate repository, would be ideal.

**Comment by spring-issuemaster** [comment] 2019-07-23 10:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-30 10:18
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-30 10:18 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
