### ISSUE TITLE
Provide a means to append to list config via properties as opposed to overwriting

### ISSUE THREAD

**Issue by adriancole** [spring-projects/spring-boot#16394] opened 2019-03-31 13:46 UTC
Right now, I can override a property root which is defined in a profile, even if it includes nested lists. For example, I can do the following to open two ports for an Armeria test. I'd like to be able to just append to the list as opposed to redefining it. For example, removing the `armeria.ports[0]` entries below as they are already in the yaml. If I do that, though, it results in an unbound exception.

```java
@SpringBootTest(
  classes = ZipkinServer.class,
  webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
  properties = {
    "spring.config.name=zipkin-server",
    "armeria.ssl.enabled=true",
    "armeria.ports[0].port=${server.port}",
    "armeria.ports[0].protocols[0]=http",
    "armeria.ports[1].port=0",
    "armeria.ports[1].protocols[0]=https"
  })
```

```
Caused by: org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException: The elements [armeria.ports[1].port,armeria.ports[1].protocols[0]] were left unbound.
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.assertNoUnboundChildren(IndexedElementsBinder.java:147) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:120) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:89) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.IndexedElementsBinder.bindIndexed(IndexedElementsBinder.java:71) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.CollectionBinder.bindAggregate(CollectionBinder.java:51) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:58) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
```

**Comment by wilkinsona** [comment] 2019-03-31 17:08
This is, largely, a duplicate of #9137. I am still of the opinion that we should not support this as it’s too brittle. Let’s see what the rest of the team thinks.

**Comment by adriancole** [comment] 2019-04-01 00:58
thanks.. overnight I considered that ideally if we did this, we'd want to contribute to the list vs depend on strict ordinals. ex `armeria.ports[++].port=0`. Seems brittle in a different way.

In my own example I can see how when you have multiple branches in an element that could be tricky.. and only some sort of relative numbering would work, as we have two properties to set at the same place.

```
    "armeria.ports[1].port=0",
    "armeria.ports[1].protocols[0]=https"
```

**Comment by mbhave** [comment] 2019-04-01 18:23
For me, it still comes down to Andy's point in [this comment](https://github.com/spring-projects/spring-boot/issues/9137#issuecomment-301166294). If we do decide to do this, we need a way to avoid the repetition when modifying a list without hurting the ease with which a list can be overridden.

**Comment by adriancole** [comment] 2019-04-02 05:13
I agree this is largely a repeat of #9137.

The only thing I might clarify is if "append only" makes something easier here. For example, in this case I'm not interested in overriding any property, just appending.

If this doesn't clarify in a way that makes things less dangerous, and as this is the only time I've run into it, I'm not pushing hard on this one.

**Comment by philwebb** [comment] 2019-04-05 16:51
Even with the append only idea there's a lot of additional complexity that this will introduce and I'm not keen to open that can of worms again. I wonder if there's another approach where a bean post processor could be used in the test to append the additional items programmatically?

**Comment by philwebb** [comment] 2019-04-05 16:52
I'm going to close this one as a duplicate of #9137.

**Closed by philwebb** 2019-04-05 16:52 UTC
Labels: for: team-attention, status: waiting-for-triage

**Comment by adriancole** [comment] 2019-04-05 23:40
fair enough. thanks
