### ISSUE TITLE
Adding jackson dataformat xml  should not change output format to xml automatically

### ISSUE THREAD

**Issue by NotFound403** [spring-projects/spring-boot#32647] opened 2022-10-10 01:45 UTC
## Version
- Spring Boot 2.7.4
- Spring MVC
- Jackson-dataformat-xml
## Question
When I add `jackson-dataformat-xml` to my `pom.xml`, all the MVC api output format becames `xml` instead of `json`. I think introducing a dependency is an autonomous action, maybe it's not intended to change the output format and shouldn't be triggered automatically.

**Comment by bclozel** [comment] 2022-10-10 05:26
Closing as a duplicate of #32494
We're still missing a sample application for that issue. Could you contribute one please?

**Closed** 2022-10-10 05:26 UTC
Labels: status: duplicate
