### ISSUE TITLE
2.3.0.RC1 - RSocket over Websocket transport - requestStream - produces additional request(255)

### ISSUE THREAD

**Issue by maxim-bandurko-lsvt** [spring-projects/spring-boot#21360] opened 2020-05-08 03:20 UTC
With latest 2.3.0.RC1 RSocket "requestStream" started producing additional request to Flux inside controller with quantity 255.

Configuration to reproduce the issue:

1. Spring Boot 2.3.0.RC1
2. RSocket plugged to server
3. Transport - Websockets
4. Using @MessageMapping controller
5. RSocket connection with Composite Metadata ('message/x.rsocket.composite-metadata.v0'), Binary MimeType ('application/octet-stream') and Buffer encoders
6. Tested with javascript RSocket client v0.0.19.

Previous version of Spring Boot 2.3.0.M4 hasn't such issue.

**Comment by bclozel** [comment] 2020-05-08 05:56
We didn’t change anything specific in our RSocket support besides upgrading in #21208. This looks like an internal change to me or a mismatch with the JS library version?

In any case I’m closing this issue in favor of the one you opened with RSocket Java. Note that your current report isn’t enough and the RSocket team will probably need a sample application to reproduce the issue and more details about the problem. Thanks!

**Closed by bclozel** 2020-05-08 05:56 UTC
Labels: for: external-project, status: superseded

**Comment by maxim-bandurko-lsvt** [comment] 2020-05-10 02:34
@bclozel It was an issue on Java RSocket side, that will be resolved with PR.

Thank you.
