### ISSUE TITLE
Optimize JUL logging

### ISSUE THREAD

**Issue by romainmoreau** [spring-projects/spring-boot#2585] opened 2015-03-02 20:47 UTC
As stated in http://www.slf4j.org/legacy.html#jul-to-slf4j, the jul-to-slf4j bridge has some performance issues with disabled logging statements.
Since the jul-to-slf4j bridge is activated by default in the spring-boot-starter-logging pom, install a LevelChangePropagator will enhance the performances when the logging system used by the application is JUL and when there are some dependencies using JUL.

**Comment by farrault** [comment] 2015-05-06 19:44
In the current default setup, I don't think there is a big performance impact, as only INFO or higher JUL log events are sent to SLF4JBridgeHandler

I created a ticket #2923 to allow the configuration of JUL levels sent to SLF4JBridgeHandler

See also the discussion here http://stackoverflow.com/questions/25364913/spring-boot-set-logging-level-of-external-jar-which-is-using-java-util-logging/30085782#30085782

**Comment by philwebb** [comment] 2016-01-08 09:39
See #3924 which solved something similar for Logback. We should still handle other SLF4J implementations.

**Comment by wilkinsona** [comment] 2018-03-22 16:22
This is, I think, a duplicate of 2983. We also [recently documented](https://github.com/spring-projects/spring-boot/issues/11660) how to configure Log4j2 so that it handles all output from JUL.

**Closed by wilkinsona** 2018-03-22 16:22 UTC
Labels: type: enhancement
