### ISSUE TITLE
Maybe an enhancement for spring-boot-starter-jooq

### ISSUE THREAD

**Issue by tamaro-skaljic** [spring-projects/spring-boot#20904] opened 2020-04-09 23:38 UTC
Hello Spring Boot Team,

I migrated today from JOOQ 3.13.1 (`org.jooq`: `jooq`, `jooq-meta` and `jooq-codegen`) to `spring-boot-starter-jooq` from the `spring-boot-starter-parent` 2.2.5.RELEASE, This caused the problem that I had to adjust my configuration because the codegen-plugin suddenly generated `java.sql.*` types instead of `java.time.*` types.

Is this an opinionated default?

This helped:
https://www.jooq.org/doc/3.13/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-java-time-types/

**Comment by snicoll** [comment] 2020-04-10 07:55
@tamaro-skaljic I am not sure what you're reporting here. What do you mean by "adjust my configuration"?

**Comment by tamaro-skaljic** [comment] 2020-04-10 11:56
@snicoll Either I would have had to rewrite my code to use java.sql.Date instead of java.time.LocalDate, or I would have had to change something in my pom.xml.

```
<generate>
      <javaTimeTypes>true</javaTimeTypes>
    </generate>
```

**Comment by snicoll** [comment] 2020-04-10 11:59
@tamaro-skaljic Maven plugin configuration is unrelated to the concept of starter so I am afraid that doesn't really help me understand what is there to improve. 

The way I understood your report, you mentioned that you were using explicit dependencies and then switch to `spring-boot-starter-jooq`. That doesn't have anything to do with the maven configuration. What am I missing?

**Comment by tamaro-skaljic** [comment] 2020-04-10 19:29
@snicoll Well, the dependencies are written to the pom.xml as well as the configuration of the JOOQ code-gen Maven plugin. However, I just replaced the explicit dependencies with the Spring Boot JOOQ Starter (which consists of several dependencies, including JOOQ's) and the next build failed because the code generator did something different, even though the versions should work the same, didn't they?

**Comment by snicoll** [comment] 2020-04-10 20:50
Rather than guessing we’ll need a small sample that reproduces the problem you’ve described. No code in text but a zip or a link to a github repo.

**Comment by spring-issuemaster** [comment] 2020-04-17 20:54
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-04-24 20:53
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-04-24 20:53 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
