### ISSUE TITLE
Servlet.service() NPE

### ISSUE THREAD

**Issue by glibovet** [spring-projects/spring-boot#26758] opened 2021-06-04 11:53 UTC
Spring Boot 2.1.4.RELEASE from time to time, receiving error:
2021-06-03 08:12:51.663 ERROR 3601 --- [10001-exec-2223] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null

And that is all. No stack trace.
We use Log4j2 logging with params:
logging.level.root=error
logging.level.org.springframework.boot=error
logging.level.org.springframework.web=error

It is Rest application. All controllers have integration tests.

**Comment by snicoll** [comment] 2021-06-04 12:01
Spring Boot `2.1.4.RELEASE` is EOL so please upgrade to a supported version at your earliest convenience. Putting the logs in `ERROR` reduces the chance of getting additional context. You should try `DEBUG` on the web package at least. If you can reproduce the problem with a supported version of Spring Boot, please share the additional logs.

**Comment by spring-projects-issues** [comment] 2021-06-11 12:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-06-18 12:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-06-18 12:02 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
