### ISSUE TITLE
2.3.2.RELEASE breaking Couchbase Reactive 

### ISSUE THREAD

**Issue by anoophp777** [spring-projects/spring-boot#23163] opened 2020-09-02 09:39 UTC
I upgraded Spring Boot from 2.2.7.RELEASE to 2.3.2.RELEASE. I have a Reactive App which connects to Couchbase DB using Spring Data Reactive Library. 

Only when I upgrade, I get the below error. I works fine on 2.2.7.RELEASE:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field buildingRepository in com.cb.springdata.sample.BuildingController required a bean named 'reactiveCouchbaseRepositoryOperationsMapping' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'reactiveCouchbaseRepositoryOperationsMapping' in 'CouchbaseReactiveDataConfiguration' not loaded because @ConditionalOnSingleCandidate (types: org.springframework.data.couchbase.CouchbaseClientFactory; SearchStrategy: all) did not find any beans


Action:

Consider revisiting the entries above or defining a bean named 'reactiveCouchbaseRepositoryOperationsMapping' in your configuration.
```

How to get my app working on the 2.3.*? Any ideas?

**Comment by wilkinsona** [comment] 2020-09-02 10:02
There's a [section in the release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#couchbase) that describes what's necessary to use the new versions of Couchbase and Spring Data Couchbase. Please take a look at those and see if it helps. If it does not and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-issuemaster** [comment] 2020-09-09 10:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-09-16 10:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-09-16 10:07 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
