### ISSUE TITLE
TestRestTemplate does the url encoding twice if I pass the URI as a string

### ISSUE THREAD

**Issue by Selindek** [spring-projects/spring-boot#8888] opened 2017-04-12 07:41 UTC
Controller:
```
@RestController
@RequestMapping(value = "/uritest")
public class TestController {

    @RequestMapping(method = { RequestMethod.GET })
    public ResponseEntity<Void> endpoint(@RequestParam(required = true) String param) {
        System.out.println(param);
        return new ResponseEntity<>(HttpStatus.OK);
    }
}
```
Integration Test:

```
@ActiveProfiles("test")
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
public class ControllerTest {

    @Autowired
    private TestRestTemplate testRestTemplate;

    @Rule
    public WireMockRule wireMockRule = new WireMockRule();

    HttpHeaders headers;

    @Test
    public void testGivenExistingStateRequestWhenCallGetStateThenReturnOkStatusAndProperBody() throws Exception {
        final UriComponentsBuilder uriBuilder = UriComponentsBuilder.fromPath("/uritest");

        uriBuilder.queryParam("param", "\"\\%");

        final HttpEntity<String> entity = new HttpEntity<>(null, headers);

        final URI uri = uriBuilder.build().toUri();

        testRestTemplate.exchange(uri, HttpMethod.GET, entity, String.class);
        testRestTemplate.exchange(uri.toString(), HttpMethod.GET, entity, String.class);

    }
}

```
Output:

```
"\%
%22%5C%25
```
There is already a closed issue about this bug: [https://github.com/spring-projects/spring-boot/issues/8163](https://github.com/spring-projects/spring-boot/issues/8163)

I checked the fix there and it adds a root to the URI if the URI was relative. This issue also happens if the provided string describes a relative URI. I assume the same check should be applied to all of the other methods too where the first parameter is a String instead of an URI.

**Comment by mbhave** [comment] 2017-04-24 21:48
@Selindek this seems to be happening because the String that gets passed to `exchange` is already encoded (which causes the double encoding as @wilkinsona mentioned [here].(https://github.com/spring-projects/spring-boot/issues/8163#issuecomment-292998635) Instead of using the `uri.toString()`, if `"/uritest?param=\"\\%"` is passed, the encoding works fine.

**Comment by spring-issuemaster** [comment] 2017-05-01 21:51
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-05-08 21:50
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by stego39** [comment] 2017-10-26 18:43
running into this same issue as well...

Spring 4.3.11 .. using RestTemplate and setting a rootURI using RestTemplateBuilder... the rootURI doesnt get applied when the RestTemplate methods are called (eg getForObject ) when using the URI object... have to use the string version of the URI.. but then we run into the double encoding issue.

A workaround is to simply build the uri string manually and use it directly in the RestTemplate call... seems using URI object encodes the URI at some point... before it's used as a string parameter in the RestTemplate method call.

**Comment by georgmittendorfer** [comment] 2018-06-11 12:59
Same issue in spring-boot 2.0.2. 

- `uriBuilder.toUriString()` encodes space as `%2520` (it does: `build(false).encode().toUriString()`).
- `uriBuilder.build(false).toUriString()` encodes space as `%20`

**Comment by philwebb** [comment] 2018-06-11 17:00
@georgmittendorfer Could you provide a small sample to show the problem?

**Comment by georgmittendorfer** [comment] 2018-06-11 17:39
Small sample (not very sophisticated):
```
String uriString = UriComponentsBuilder
                .fromUriString("http://localhost:1234")
                .queryParam("foo", "some value")
                .toUriString();
assertTrue(uriString, uriString.contains("foo=some%20value"));
restTemplate.getForEntity(uriString, String.class);
```
Listening with `netcat -s localhost -l -p 1234` will show that `%20` is encoded a second time to `%2520`:
```
netcat -s localhost -l -p 1234
GET /?foo=some%2520value HTTP/1.1
```
Slightly offtopic: another issue (not sure if this is bug) might be the encoding of `+` of the UriComponentsBuilder:
```
//.queryParam("bar", "some+value")
//assertTrue(uriString, uriString.toLowerCase().contains("bar=some%2bvalue")); // fails: uri string still contains some+value (not encoded)
```

**Comment by georgmittendorfer** [comment] 2018-06-11 17:50
Slightly offtopic: another issue (not sure if this is bug) might be the encoding of `+`. Neither TestRestTemplate nor UriComponentsBuilder encode it but leave it:

```
//.queryParam("bar", "some+value")
//assertTrue(uriString, uriString.toLowerCase().contains("bar=some%2bvalue")); // fails: still some+value
```

**Comment by bclozel** [comment] 2018-06-11 20:23
Hi @georgmittendorfer,
I think this is the expected behavior in Spring Framework (see [SPR-16202](https://jira.spring.io/browse/SPR-16202) and [SPR-14828](https://jira.spring.io/browse/SPR-14828) for some background on this).

As a general rule, providing a URI String to `RestTemplate` means that this String should be expanded (using optional method parameters) and then encoded. If you want to take full control over the encoding, you should then use the method variant taking a `URI` as a parameter.

The Spring Framework team recently added [some more documentation on the subject of URI encoding](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#web-uri-encoding). Does that help?

**Comment by georgmittendorfer** [comment] 2018-06-11 20:43
Yes, thank you, that helps. The API is slightly confusing on first contact, though.

**Comment by bclozel** [comment] 2018-06-12 08:43
Ok thanks!

**Closed by bclozel** 2018-06-12 08:43 UTC
Labels: status: feedback-provided

**Comment by mathewjustin** [comment] 2018-06-25 14:09
@georgmittendorfer  Thanks👍

**Comment by Fenzland** [comment] 2022-05-26 09:24
> Hi @georgmittendorfer, I think this is the expected behavior in Spring Framework (see [SPR-16202](https://jira.spring.io/browse/SPR-16202) and [SPR-14828](https://jira.spring.io/browse/SPR-14828) for some background on this).
> 
> As a general rule, providing a URI String to `RestTemplate` means that this String should be expanded (using optional method parameters) and then encoded. If you want to take full control over the encoding, you should then use the method variant taking a `URI` as a parameter.
> 
> The Spring Framework team recently added [some more documentation on the subject of URI encoding](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web.html#web-uri-encoding). Does that help?

That's really not a considered feature, you can never send a request with RestTemplate like this:
```
http://example.org/foo?param=%26
```

If you pass `"http://example.org/foo?param=%26"` or `new URI("http://example.org/foo?param=%26")` to RestTemplate, you got `http://example.org/foo?param=%2526`. But if you pass `"http://example.org/foo?param=&"`, you just got `http://example.org/foo?param=&`
