### ISSUE TITLE
404 error occurs with RequestMapping(path="")

### ISSUE THREAD

**Issue by koki8** [spring-projects/spring-boot#33499] opened 2022-12-09 08:15 UTC
# Used version
SpringBoot3.0.0 GA  

# Occurrence event
When I specify an empty string in Controller's RequestMapping (@RequestMappint(path="")) and access the root path, 
The mapping doesn't work properly and I get 404. I  could find the endpoint is created at startup, but the request never reaches the Controller.
This event does not occur in SpringBoot3.0.0 M3. It has occurred since M4.

# Reproduction steps below

1. Create SampleController
``` Java
@RestController
public class SampleController {

    @RequestMapping(path = "")
    public String demo(){
        return "test";
    }
}
```

2. Request to the following URL
- 「http://localhost:8080/」
- 「http://localhost:8080」

3. Check result
- Expected value  
The string of 「Test」 is displayed  
Status：200  

- Actual  
Status：404

# Supplement
- If any character is present in the @RequestMapping of the class or method, it will be successfully mapped.

- Confirmed for the following versions

|SpringBoot version | Result |
| :---| ----|
| 2.7.6 | OK |
| 3.0.0 M3 | OK |
| 3.0.0 M4 | NG |
| 3.0.0 GA | NG |

**Comment by bclozel** [comment] 2022-12-09 08:18
Closing as a duplicate of spring-projects/spring-framework#29625

**Closed by bclozel** 2022-12-09 08:18 UTC
Labels: status: waiting-for-triage

**Comment by koki8** [comment] 2023-04-05 08:11
@bclozel   
It looks like the contents of this issue are not fixed.  
I checked with SpringBoot 3.0.5 and the same issue occurred.   

https://github.com/spring-projects/spring-framework/issues/29625  
404 occurred when using @GetMapping as well as the above Controller.  

# See below for reproduction procedure
1. create SampleController
```
@RestController
public class SampleController {

    @RequestMapping(path = "")
    public String demo(){
        return "test";
    }
}
```


2. request the following URL
- 「http://localhost:8080」
- 「http://localhost:8080/」

3. confirmation result
- Expected value  
  - The string "test" is displayed.   
  - Status：200
- Actual result   
  - Status：404


# Supplementation
## Occurrence Conditions
### case SpringBoot ver2.7.10
| request | mapping | expected | actual | OK/NG |
| :--- | :---: | :---: | :---: | :---: |
| localhost |  @RequestMapping | 200 | 200 | OK |  
| localhost/ |  @RequestMapping | 200 | 200 | OK | 
| localhost |  @RequestMapping(path = "") | 200 | 200 | OK |
| localhost/ |  @RequestMapping(path = "") | 200 | 200 | OK |
| localhost |  @RequestMapping(path = "/") | 200 | 200 | OK |
| localhost/ |  @RequestMapping(path = "/") | 200 | 200 | OK |


### case SpringBoot ver3.0.5
| request | mapping | expected | actual | OK/NG |
| :--- | :---: | :---: | :---: | :---: |
| localhost |  @RequestMapping | 200 | 404 | NG |  
| localhost/ |  @RequestMapping | 200 | 404 | NG | 
| localhost |  @RequestMapping(path = "") | 200 | 404 | NG |
| localhost/ |  @RequestMapping(path = "") | 200 | 404 | NG |
| localhost |  @RequestMapping(path = "/") | 200 | 200 | OK |
| localhost/ |  @RequestMapping(path = "/") | 200 | 200 | OK |

※The same phenomenon occurs with `@GetMapping`

## Versions confirmed to work
- Confirmed with the following version

|SpringBoot version | Result |
| :---| ----|
| 2.7.6 | OK |
| 2.7.10 | OK |
| 3.0.0 M3 | OK |
| 3.0.0 M4 | NG |
| 3.0.0 GA | NG |
| 3.0.2    | NG |
| 3.0.3    | NG |
| 3.0.4    | NG |
| 3.0.5    | NG |

**Comment by bclozel** [comment] 2023-04-05 08:47
@koki8 This issue is a duplicate of a Spring Framework issue that is not fixed yet. So this is expected.

**Comment by koki8** [comment] 2023-04-06 03:08
@bclozel
https://github.com/spring-projects/spring-framework/issues/29625
The duplicated SpringFramework issue is already closed, can you tell me which issue you are talking about?

**Comment by bclozel** [comment] 2023-04-06 07:34
Apologies I thought it was not done yet. It looks like the enhancement is incomplete, I've opened spring-projects/spring-framework#30293 to fix that.
