### ISSUE TITLE
spring-boot-devtools's ClassLoader will affect the normal use of the function

### ISSUE THREAD

**Issue by guoyk1217** [spring-projects/spring-boot#12241] opened 2018-02-27 06:48 UTC
When you use spring-boot-devtools,  you create a new object, The class loader is RestartClassLoader.RestartClassLoader extends URLClassLoader。
However, the object that is acquired from session is APPClassLoader, which results in the failure of strong typing.

My usage scenario is as follows：
```
    @RequestMapping("login")
    public JSONObject login(@RequestBody User user, HttpServletRequest request){
        if(StringUtil.isEmpty(user.getCode()) || StringUtil.isEmpty(user.getPwd())){
            throw new MyException(ErrorMsg.PARAM_VALID_EXCEPTION);
        }
        ··· 
        HttpSession session = request.getSession();
        session.setAttribute("user", user);
        return JSONObject.fromObject(user);
    }

    @RequestMapping("logout")
    public JSONObject logout(HttpServletRequest request){
        HttpSession session = request.getSession();
        User user = (User) session.getAttribute("user");
        ···
        return JSONObject.fromObject(user);
    }
```

use spring-boot-devtools:

    in  User user = (User) session.getAttribute("user"); 
    will be throw java.lang.ClassCastException.
    com.idark.domain.user.User cannot be cast to com.idark.domain.user.User

It's normal when you don't use it。And then you'll find that the ClassLoader they use are different。

Personal English is limited, please forgive me。

**Comment by wilkinsona** [comment] 2018-02-27 10:46
I suspect the problem here is due to serialisation and deserialisation of the `User` object when it's stored in and retrieved from the `HttpSession`. This problem will occur if the deserialisation is using the wrong class loader. The code that performs that deserialisation will depend on the Servlet container you're using and whether or not any custom session management (such as the use of Spring Session) has been configured.

Can you please provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) so that we can investigate?

**Comment by guoyk1217** [comment] 2018-03-01 04:10
I did use springsession, and this problem appears in the process of deserialisation. 
Then I tidy up a simple demo in https://github.com/guoyk1217/admin-idark.git 

Thanks for your response!

**Comment by snicoll** [comment] 2018-03-01 09:51
Duplicate of #11537

**Closed by snicoll** 2018-03-01 09:51 UTC
Labels: status: feedback-provided, status: waiting-for-triage
