### ISSUE TITLE
Startup time 2.5 times slower with executable WAR than in Eclipse

### ISSUE THREAD

**Issue by stefanocke** [spring-projects/spring-boot#6177] opened 2016-06-16 13:56 UTC
Spring Boot 1.3.5.Release
OS: Windows 7 (but no different results with Linux)

I have a Spring Boot Application with some REST Endpoints and Spring Data JPA for Persistence.
When running in Spring Tool Suite, it starts within about **11 seconds**. When running as executable war with "java -jar", it needs **29 seconds** to start.  
- The application is packaged as war. 
- Spring Boot plugin is called with goal "repackage". 
- Spring-Boot-starter-tomcat is included as provided dependency.

I did some sampling with JVisualVM for both cases. In the following, the diff of the hotspot mehtods is shown. It seems that accessing the WAR/JAR entries seems to be quite slow, but I am not sure.
Please ignore the difference for Thread.sleep(). (I have added this)

![image](https://cloud.githubusercontent.com/assets/7280950/16119175/a2474738-33da-11e6-94a8-4026791987b1.png)

Is there anything that can be done to improve war startup time? (Other packaging options etc)

I have the same experience with other spring boot apps packaged the same way. So I guess it does not depend too much on the details of the application...

**Comment by wilkinsona** [comment] 2016-06-16 14:45
An executable jar will always be a bit slower than running directly in your IDE, but I wouldn't expect the difference to be so large. For example, our Freemarker sample starts in 2.603 seconds in Eclipse and 2.818 seconds when using `java -jar`. The latter is 108.3% of the former compared with 263% in your case.

Can you please share your application or a representative sample? I'm interested to see exactly what it's doing and why there's such a dramatic difference.

**Comment by stefanocke** [comment] 2016-06-16 15:02
@snicoll : Thanks for correct title. I just tried to change from WAR to JAR and now its 18 seconds. This is better but still about 160% compared to Eclipse.

@wilkinsona : Thanks for feedback. Currently I cannot share, but maybe I can prepare something in the next days. Perhaps it halps to know that the JAR / WAR is quite big (50 MB) since Spring Cloud is used also  (Eureka Client and Config Client).

**Comment by snicoll** [comment] 2016-06-16 15:18
> When running in Spring Tool Suite,

@stefanocke what are you doing in STS? Are you running the main method or something else? 

11s to 18s is not a ~10% increase so something extra is going on. But the key thing here is that running as an executable war makes things way worse it seems.

**Comment by stefanocke** [comment] 2016-06-16 15:35
@snicoll In STS, I use the "Boot Dashboard" and there "(Re)start".  I guess that is quite the same as running the main method.

**Comment by stefanocke** [comment] 2016-06-16 16:00
Steps to reproduce: 

1.  In STS choose New Spring Starter Project
2. Choose "war" packaging type
2. Choose at least Config Client, Cloud Bootstrap, Clous Security, Eureka Discovery, Security, Actuator and Web
3. Run the generated application in STS Boot Dashboard  (on my notebook: 5.1s)
4. mvn install
5. Go to target dir and run  java -jar  name-of-application.war  (on my notebook: 12,2 s)

**Comment by wilkinsona** [comment] 2016-06-16 17:00
That's very helpful, thanks.

I created such an app and gathered some timings (on OS X Yosemite running on a retina Macbook Pro):

Packaging | 1.4.0.BUILD-SNAPSHOT | 1.3.5.RELEASE | 1.3.5.RELEASE with Spring Framework 4.3.0.RELEASE
------------ | --------- | ---------- | ---------
War | 7.6 | 6.7 | 7.3
Jar | 6.6 | 5.6 | 6.1
IDE | 4.4 | 3.9 | 4.2

The differences are nowhere near as marked as you're seeing, but they are there. The difference between war and jar packaging is of particular interest.

**Comment by wilkinsona** [comment] 2016-06-16 19:05
An executable war has a document root, whereas an executable jar does not. A patched version of 1.4.0.BUILD-SNAPSHOT that returns `null` from `AbstractEmbeddedServletContainer.getValidDocumentRoot()` starts in 6.7 to 6.8 seconds, accounting for almost all of the difference between a jar and a war.

**Comment by philwebb** [comment] 2016-06-20 23:48
The 1 second difference between 1.3.5 and 1.4.0 is quite concerning.

**Comment by wilkinsona** [comment] 2016-06-21 08:26
It's due, in part at least, to the new annotation synthesis in Spring Framework 4.3

**Comment by philwebb** [comment] 2016-06-21 17:58
@jhoeller Any ideas for annotation synthesis optimizations? Perhaps synthesis could be skipped for some annotations?

**Comment by stefanocke** [comment] 2016-06-21 18:52
Thanks for all your attention for this issue. Maybe, for the difference between 1.3.5 and 1.4.0, a new one should be created...

**Comment by davidmelia** [comment] 2016-06-22 15:53
Hi,

I've noticed exactly the same with a WAR project which is almost exactly 2.5x slower. I think one issue here is to do with the JAR scanner in tomcat which seems to double up when you run on the command line and it's easy to recreate.  
 

1. Create a spring boot web project in eclipse
2. include tomcat-embed-jasper 
3. enable logback tomcat JAR scanning logging:   logger name="org.apache.tomcat.util.scan" level="DEBUG"/>

then you seem to get duplicate entries (notice how the jars are scanned twice each)

2016-06-22 16:45:30,156 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [/WEB-INF/lib/spring-web-4.3.0.RC2.jar] from /WEB-INF/lib
2016-06-22 16:45:30,187 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [/WEB-INF/lib/tomcat-embed-websocket-8.0.33.jar] from /WEB-INF/lib
2016-06-22 16:45:30,202 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [/WEB-INF/lib/spring-webmvc-4.3.0.RC2.jar] from /WEB-INF/lib
2016-06-22 16:45:30,327 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [jar:file:/C:/Users/MELIAD2/Documents/workspace-spring-boot/demo/target/demo-0.0.1-SNAPSHOT.war!/WEB-INF/lib/spring-web-4.3.0.RC2.jar!/] from classpath
2016-06-22 16:45:30,452 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [jar:file:/C:/Users/MELIAD2/Documents/workspace-spring-boot/demo/target/demo-0.0.1-SNAPSHOT.war!/WEB-INF/lib/spring-webmvc-4.3.0.RC2.jar!/] from classpath
2016-06-22 16:45:30,562 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [jar:file:/C:/Users/MELIAD2/Documents/workspace-spring-boot/demo/target/demo-0.0.1-SNAPSHOT.war!/WEB-INF/lib/tomcat-embed-websocket-8.0.33.jar!/] from classpath
2016-06-22 16:45:30,593 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [jar:file:/C:/Users/MELIAD2/Documents/workspace-spring-boot/demo/target/demo-0.0.1-SNAPSHOT.war!/WEB-INF/lib-provided/tomcat-embed-jasper-8.0.33.jar!/] from classpath

In eclipse you only get one scanning

2016-06-22 16:44:17,766 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [file:/C:/Users/MELIAD2/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.0.33/tomcat-embed-websocket-8.0.33.jar] from classpath
2016-06-22 16:44:17,766 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [file:/C:/Users/MELIAD2/.m2/repository/org/springframework/spring-web/4.3.0.RC2/spring-web-4.3.0.RC2.jar] from classpath
2016-06-22 16:44:17,766 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [file:/C:/Users/MELIAD2/.m2/repository/org/springframework/spring-webmvc/4.3.0.RC2/spring-webmvc-4.3.0.RC2.jar] from classpath
2016-06-22 16:44:17,813 [localhost-startStop-1] [] DEBUG StandardJarScanner - Scanning JAR [file:/C:/Users/MELIAD2/.m2/repository/org/apache/tomcat/embed/tomcat-embed-jasper/8.0.33/tomcat-embed-jasper-8.0.33.jar] from classpath

Very odd

Thanks

**Comment by wilkinsona** [comment] 2016-06-22 16:08
Interesting finding, @davidmelia. Thank you. The reason for `WEB-INF/lib` not being scanning in Eclipse is that it only exists once the app's been packaged as an executable war. That is scan twice is still of interest, though. `StandardJarScanner` does contain some logic that should avoid duplicate scanning:

```
if (processedURLs.contains(url)) {
    // Skip this URL it has already been processed
    continue;
}
```

It looks like the URLs are not matching up. When it's `WEB-INF/lib` that's being scanned the path is converted into a URL by calling `ServletContext.getURL()`. My guess would be that the URL it returns differs from the URL of the same jar found via the classpath.

**Comment by wilkinsona** [comment] 2016-06-22 16:51
The URLs are indeed subtly different, for example:

```
jar:file:/Users/awilkinson/dev/workspaces/spring/spring-boot/master/gh-6177/target/gh-6177-0.0.1-SNAPSHOT.war!/WEB-INF/lib/archaius-core-0.7.4.jar
jar:file:/Users/awilkinson/dev/workspaces/spring/spring-boot/master/gh-6177/target/gh-6177-0.0.1-SNAPSHOT.war!/WEB-INF/lib/archaius-core-0.7.4.jar!/
```

The first URL is from the `ServletContext` the second is from the class loader.

**Comment by wilkinsona** [comment] 2016-06-22 17:04
@philwebb Can you remember why our `JarFile` [suffixes its URL with `!/`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader/jar/JarFile.java#L309)? I'm rather wary about changing it, but it does look like it would provide a significant speed up for those trying to use JSPs in an executable war.

**Comment by philwebb** [comment] 2016-06-22 18:45
@wilkinsona I can't remember any specific reason.

**Comment by philwebb** [comment] 2016-06-23 03:43
I've made a few tweaks and I can't see much difference between the 1.3 and 1.4 startup times in eclipse. However, I still see quite a regression when running `java -jar`. My guess is the memory improvements we added to the fat jar support are the problem.

**Comment by davidmelia** [comment] 2016-06-23 19:16
@wilkinsona do you want me to raise a separate issue about the double JAR scanning?

**Comment by philwebb** [comment] 2016-06-23 20:40
A bit more digging. It appears that the fix for #5287 is having quite an impact in 1.4.x (even though it's fine in 1.3.x). Here are some timings:

**v1.3.3**
Started SampleTomcatApplication in 2.484 seconds (JVM running for 2.874)

**v1.4.x**
Started SampleTomcatApplication in 3.84 seconds (JVM running for 4.458)

**v.1.4.x (with 5287 reverted)**
Started SampleTomcatApplication in 2.835 seconds (JVM running for 3.315)

In 1.4.x `JarURLConnection` is created a whopping 107,859 times.

**Comment by philwebb** [comment] 2016-06-23 20:47
OK, it's not #5287 that's the cause, it's #6109.

**Comment by philwebb** [comment] 2016-06-23 22:50
I've added some caching which seems to bring 1.4 jar speeds back in line with 1.3. @wilkinsona Could you re-post your timings on the latest 1.4.x?

**Comment by wilkinsona** [comment] 2016-06-24 09:32
@davidmelia I've opened #6216 for the double-scanning problem

**Comment by buckfeng** [comment] 2018-02-13 06:53
I encountered this exact same issue with 2.0.0.RC1 starter-web.   Fat jar startup time = 7.2s, eclipse run startup time = 3.6s.  A big portion of the increased time while running from a fat jar was attributable to `ConfigServletWebServerApplicationContext` (about 3 seconds).  In eclipse, the same line took less than a second.  

```
2018-02-13 06:16:26.897  INFO 3332 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5ecddf8f: startup date [Tue Feb 13 06:16:26 UTC 2018]; root of context hierarchy
2018-02-13 06:16:29.533  INFO 3332 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9443 (http)
```

**Comment by philwebb** [comment] 2018-02-13 20:23
@buckfeng the refresh method on `AnnotationConfigServletWebServerApplicationContext` initializes all beans so it's hard to know which particular thing is causing the problem. Do you have an example project that you can share that shows the problem?

**Comment by jeacott1** [comment] 2018-08-09 04:01
fwiw - I have a spring boot app (spring boot 1.5.8.RELEASE) packaged as a standard fat jar.
its an undertow/spring mvc + the usual things app, and its startup time in eclipse is ~26 seconds. after mvn package and java -jar myapp its 80 seconds.  inside a docker its double that.

After looking at flame graphs it looks like all the is cpu processing/unpacking jar files.

**Comment by wilkinsona** [comment] 2018-08-09 07:30
Thanks for the data point, @jeacott1. I'm surprised by the apparent overhead of the fat jar support. As described in various comments above, there is some overhead but we've yet to experience anything close to 100% increase first-hand. Could you share your app or a "synthetic" app that reproduces the same behaviour?

**Comment by wilkinsona** [comment] 2018-12-14 16:49
We think this one has run its course. @jeacott1 if you have a chance to provide an app, synthetic or otherwise, that reproduces the behaviour you've described, please open a new issue and we'll take a look.

**Closed by wilkinsona** 2018-12-14 16:49 UTC
Labels: status: feedback-provided

**Comment by jeacott1** [comment] 2018-12-14 23:58
sure. the issue is very real, but I simply haven't had time to create something.
