### ISSUE TITLE
RabbitMq Listener retry goes unstoppable 

### ISSUE THREAD

**Issue by mshetty794** [spring-projects/spring-boot#17415] opened 2019-07-03 07:46 UTC
I have configured all the properties specified in spring boot properties for rabbitmq listener configuration, when there is negative ack i want listener to retry for 3 times below are the configuration added in yaml file of listener.

![image](https://user-images.githubusercontent.com/44093210/60573119-a88c5300-9d94-11e9-9f26-35dcb58bd455.png)

**Comment by wilkinsona** [comment] 2019-07-03 10:36
@mshetty794 I'm not sure I understand the problem that you're describing. It's difficult to be certain based on a short description and a snippet of YAML. Please share a minimal example that reproduces the problem either as a zip attached to this issue or in a separate repository on GitHub.

**Comment by mshetty794** [comment] 2019-07-03 10:55
@wilkinsona

I have a consumer who listens to rabbitmq queue while processing if the consumer fails because of some exception. I am sending a negative acknowledgment with requeue true.

with this consumer is continuously receiving the same request again and again . i want to configure requeue retry to 3 times with some interval

channel.basicNack(tag, false, true);
 with the above code snippet, it tells rabbitmq to not to discard the request. I want to requeue the same 3 times as part of retry mechanism with some interval

**Comment by wilkinsona** [comment] 2019-07-03 10:59
Thanks for the extra details, but if you want us to spend some time investigating this for you, please spend the time to produce the requested sample. Without one, there is too great a risk that we'll be using code and configuration that does not match yours and will not be investigating the same problem.

**Comment by spring-issuemaster** [comment] 2019-07-10 11:00
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-17 11:00
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-17 11:00 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
