### ISSUE TITLE
WebFlux SSE sending partial JSON Data

### ISSUE THREAD

**Issue by xmlking** [spring-projects/spring-boot#10171] opened 2017-09-05 21:32 UTC
I have following handler implementing  Server-Sent-Events with WebFlux 

**Problem:**  occasionally I am getting partial JSON which is breaking my client-side JS code `JSON.parse(e.data)`.  

**Ask:** Is there any workaround to force server to send full JSON event?

```kotlin
@Component
class StreamHandler(final val kafkaDataReceiver: KafkaReceiver<String, String>,
                    final val objectMapper: ObjectMapper) {
    final val logStream = kafkaDataReceiver.receive().map { objectMapper.readValue(it.value(), Log::class.java) }.share()

    init{
        logStream.subscribe {
                //TODO: fake subscriber to keep kafka connect active
        }
    }
    fun fetchLogsSSE(req: ServerRequest) = ok()
            .contentType(TEXT_EVENT_STREAM)
            .body(logStream, Log::class.java)

    fun fetchLogs(req: ServerRequest) = ok()
            .contentType(APPLICATION_STREAM_JSON)
            .body(logStream, Log::class.java)
}
```

Client side JavaScript Code

```js
    var stockEventSource = new EventSource("/logs/feed");
    stockEventSource.onmessage = function (e) {
        var hostname = document.getElementById('hostname').value;
        var appName = document.getElementById('appName').value;
        var level = document.getElementById('level').value;

        if(hostname || appName || level) {
            console.log(hostname + " | " + appName + " | "+ level + " | " + e.data);
            var data = JSON.parse(e.data);// FIXME: sometimes we get partial json
            if( new RegExp(hostname, "g").test(data.HOSTNAME) &&
                new RegExp(appName, "g").test(data.app) &&
                new RegExp(level, "g").test(data.level) ) {
                console.log("match...........")
                term.writeln(e.data)
            }
        } else {
            term.writeln(e.data)
        }
    };
```
This is Good JSON event data, but sometimes I am getting partial JSON string which is breaking  `JSON.parse(e.data)` code.  

```json
 {
"timestamp":"2017-09-05T21:14:54.147-07:00",
"version":1,
"message":"...",
"logger_name":"org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver",
"thread_name":"http-nio-8080-exec-4",
"level":"WARN",
"level_value":30000,
"HOSTNAME":"erwre.my.com",
"app":"my-app"
}
```

**Comment by wilkinsona** [comment] 2017-09-06 05:28
I'm not aware of anything that you should have to do to avoid the JSON events being truncated. However, it's not clear exactly what you are doing as your example is incomplete. The `logger_name` in your example of a good JSON event is also strange as it suggests you're using Spring MVC when the issue title references WebFlux.

I suspect that Spring Boot isn't really involved here and that the problem is in WebFlux or in the JS library that you're using to consume the event stream. Please provide a complete, minimal example that illustrates the problem and we can investigate from there. In minimising the example, please try to reproduce the problem without allowing on a JS library to consume the stream. Truncation that can be reproduced with curl or similar would be ideal.

**Comment by spring-issuemaster** [comment] 2017-09-13 05:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-09-20 05:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-09-20 05:31 UTC
