### ISSUE TITLE
Regression in 2.2M2 using @ConfigurationProperties

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#16580] opened 2019-04-16 15:05 UTC
My application is using some classes annotated with @Component and @ConfigurationProperties(prefix="myprefix") and while trying latest boot milestone (I'm developing with 2.1.x) during startup it stopped to work with an error similar to this one:

> Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'my.domain.MyClassName' available: expected single matching bean but found 2: MyClassName,myprefix-my.domain.MyClassName

Maybe using @ConfigurationProperties together with a @Component is not the best style, but this used to work until I tried boot 2.2.

Is this a regression or do I need to change the way my application uses @ConfigurationProperties ?

**Comment by wilkinsona** [comment] 2019-04-16 15:28
Duplicate of #16580.

**Closed by wilkinsona** 2019-04-16 15:28 UTC
Labels: status: duplicate

**Comment by mbhave** [comment] 2019-04-16 15:29
@Polve This has been documented in a [note in this section](https://docs.spring.io/spring-boot/docs/2.2.0.M2/reference/html/spring-boot-features.html#boot-features-external-config-enabling). 2.2.0.M2 enables automatic scanning of `@ConfigurationProperties`. Annotating them with `@Component` causes the bean to be scanned and registered twice. The fix is to remove `@Component` from the `@ConfigurationProperties` class.

**Comment by Polve** [comment] 2019-05-25 09:16
I'm sorry but I ask to reopen this bug, I'm still unconvinced by the new behavior.

I did a big refactor of my project in order to be able to use separate classes for all configurations, so I could test Spring Boot 2.2.

I encountered a few problems:
1) nested configurations classes does not work in 2.2, details in #16969 

2) ConfigurationProperties classes does not automatically generate beans in 2.1, so I need to mark them with @Component but at the cost of being not compatible with 2.2

3) Even after solving 1) and 2) the app stopped working correctly because an entity class using @MapsId won't populate the id automatically anymore. I suppose this is a problem related to hybernate and not to boot though, I'll try to open an issue there, if you can't point me to something obvious I may be missing

**Comment by snicoll** [comment] 2019-05-25 09:46
@Polve duly noted for 1 and 2, please see an ongoing discussion about it in https://github.com/spring-projects/spring-boot/issues/16712 - As for 3, that's totally unrelated and if you have another upgrade problem, please create a separate issue for it with a sample that we can run ourselves (zip or github repo).

**Comment by Polve** [comment] 2019-05-25 10:34
I confirm point 1) was due to my error: I forgot to declare static nested classes and for some reason it worked in 2.1 anyway.

**Comment by Polve** [comment] 2019-05-25 20:52
For reference, I opened https://hibernate.atlassian.net/browse/HHH-13413 for the third point
