### ISSUE TITLE
Procfile Buildpack ignored by spring-boot:build-image

### ISSUE THREAD

**Issue by linux-china** [spring-projects/spring-boot#26215] opened 2021-04-22 22:44 UTC
I want to put some tasks in Procfile file with Spring Boot application, the spring-boot-maven-plugin configuration as following:

```xml
          <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
               <version>2.5.0-RC1</version>
                <configuration>
                    <image>
                        <builder>paketobuildpacks/builder:full</builder>
                        <env>
                            <SERVICE_BINDING_ROOT>/bindings</SERVICE_BINDING_ROOT>
                        </env>
                    </image>
                </configuration>
            </plugin>
```

Then I create a Procfile with following code:

```
health: curl http://localhost:8080/actuator/health
```

Then I use `mvn -DskipTests clean package spring-boot:build-image` to build the docker image with following output: 
 
```
[INFO]  > Running creator
[INFO]     [creator]     ===> DETECTING
[INFO]     [creator]     5 of 18 buildpacks participating
[INFO]     [creator]     paketo-buildpacks/ca-certificates   2.1.0
[INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 7.1.0
[INFO]     [creator]     paketo-buildpacks/executable-jar    5.0.0
[INFO]     [creator]     paketo-buildpacks/dist-zip          4.0.0
[INFO]     [creator]     paketo-buildpacks/spring-boot       4.2.0
```

Procfile buildpack not detected by the builder. 

Then I use command line `pack build spring-boot25-demo:0.0.1-SNAPSHOT` to build the app, and I get following output: 

```
===> DETECTING
8 of 18 buildpacks participating
paketo-buildpacks/ca-certificates   2.1.0
paketo-buildpacks/bellsoft-liberica 7.1.0
paketo-buildpacks/maven             5.0.0
paketo-buildpacks/executable-jar    5.0.0
paketo-buildpacks/apache-tomcat     5.1.0
paketo-buildpacks/dist-zip          4.0.0
paketo-buildpacks/spring-boot       4.2.0
paketo-buildpacks/procfile          4.1.0
```

And procfile buildpack included by pack CLI. 

Any special with `spring-boot:build-image`?

**Comment by scottfrederick** [comment] 2021-04-22 23:49
It appears that you are running the `pack` command from the root directory of the project, because the `paketo-buildpacks/maven` buildpack is being detected. This means that the entire contents of the project are being sent to the builder and the `maven` buildpack is building the project from source. If the Procfile is at the root of the project tree then the builder will detect it. 

The Spring Boot Maven plugin always builds a jar or war file and then sends only the contents of the built archive to the builder. If Procfile is outside of the source tree (for example, `/src/main/resources`) then it will not be included in the built archive and will not be sent to the builder. You would see the same behavior from `pack` if you used a command like `pack build spring-boot25-demo:0.0.1-SNAPSHOT --path target/spring-boot25-demo-0.0.1-SNAPSHOT.jar`. 

Can you verify that your Procfile is not in the built jar or war?

**Comment by linux-china** [comment] 2021-04-23 01:34
@scottfrederick  no luck to put Procfile in src/main/resources.  Any hack way to include Procfile support with spring-boot:build-image?  😃

**Comment by scottfrederick** [comment] 2021-05-04 21:59
@linux-china I've been looking into some ways to make this work, but I have not come up with a hack using the Spring Boot Maven plugin. The `paketo-buildpacks/procfile` buildpack [requires that the Procfile be at the root of the directory structure](https://paketo.io/docs/buildpacks/configuration/#procfiles) that is sent to the builder, but there's not a way to add a file to the root with the Maven plugin. 

The Maven plugin does not unpack the archive generated by [Boot's `repackage` goal](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#repackage) and send the unpacked contents to the builder. Instead it sends the class files, resources, and dependent jars in the same [layout](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#goals-repackage-parameters-details-layout) as `repackage` uses to build the jar file by generating the proper layout during the upload processing. This is why the `exec-maven-plugin` trick doesn't work, and there's not a way to configure the plugin to copy a file to a location outside of the layout's defined structure. 

This is possible with the Spring Boot Gradle plugin, as the Gradle plugin has more flexibility to include files outside of the defined layout. With a typical Gradle project and a Procfile in the root of the project, this configuration in `build.gradle` will work: 

```
bootJar {
	from(project.rootDir) {
		include 'Procfile'
	}
}
```

I'm tagging this issue for team attention so we can discuss whether we can do anything to improve the situation with the Maven plugin.

**Comment by wilkinsona** [comment] 2021-05-05 06:18
https://github.com/spring-projects/spring-boot/issues/6626 Is related to this. As [summarised in this issue by @nebhale](https://github.com/spring-projects/spring-boot/issues/6626#issuecomment-252920137), placing things in the root of the jar is problematic as it pollutes the application’s classpath:

> My main problem with this whole thing is that the design of the `.profile` and `.profile.d` feature in Cloud Foundry doesn't take into account how Java classpaths work. As you say, putting anything in the root of the application (which is what is required by this feature) means that it will be exposed on the class path of the application, which can lead to unanticipated behavior.

**Comment by scottfrederick** [comment] 2021-05-05 15:51
After some discussion, we've decided to close this issue as a duplicate of #6626. 

I've also created [an issue](https://github.com/paketo-buildpacks/procfile/issues/45) in the Paketo procfile buildpack repository to see if there's a better way to support this specific use case without polluting a jar or war file with a `Procfile`.

**Closed by scottfrederick** 2021-05-05 15:51 UTC
Labels: status: feedback-provided, status: waiting-for-triage
