### ISSUE TITLE
Strange hibernate dependency issue

### ISSUE THREAD

**Issue by Koizumi85** [spring-projects/spring-boot#3219] opened 2015-06-13 14:22 UTC
Hello,

I've tried out Spring Boot `1.3.0.M1` and I found a strange issue with the hibernate dependencies.

After I upgraded from `1.2.4.RELEASE` to `1.3.0.M1` I've got an `AbstractMethodError`:

```
java.lang.AbstractMethodError: org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.getConfigurationValues()Ljava/util/Map;
    at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:404)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844)
    at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
    ... 15 more
```

After some investigations I found, that `hibernate-core` and `hibernate-entitymanager` were present in two different versions:

```
hibernate-core: 4.3.10.Final
hibernate-entitymanager: 4.3.8.Final
```

I tried setting both to `4.3.10.Final` explicitly in my gradle build and it worked.

Then I've tried to find out where this difference is coming from, but i failed.
"gradle dependencies" only showed me, that hibernate-core was raised to 4.3.10.Final, but i did not find which dependency is causing it.

This is the dependency declaration for my project:

```
compile("org.springframework.cloud:spring-cloud-starter-eureka")
compile("org.springframework.boot:spring-boot-starter-web")
compile("org.springframework.boot:spring-boot-starter-actuator")
compile("org.springframework.boot:spring-boot-starter-data-jpa")
compile 'org.postgresql:postgresql:9.3-1103-jdbc41'
compile("org.springframework.cloud:spring-cloud-starter-feign")
compile("org.springframework.cloud:spring-cloud-starter-hystrix")
compile("org.springframework.cloud:spring-cloud-starter-ribbon")
compile("org.springframework.cloud:spring-cloud-starter-bus-amqp")
compile("org.springframework.cloud:spring-cloud-starter-config")
```

and I am adding the `spring-cloud-starter-parent-bom` in version `1.0.2.RELEASE`.

Further i wondered, why I am not getting the `spring-boot-starters` in the `1.3.0.M1` version, but instead in the `1.2.3.RELEASE` version.

Shouldn't the `spring-boot gradle plugin` adding those in the correct version?

Greetings
Christian

**Comment by philwebb** [comment] 2015-06-14 00:21
Could you provide your complete gradle file? We have recently switched to a new Gradle Dependency Management plugin (see the [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#dependency-management)) so it's possible that this could be having some effect.

**Comment by wilkinsona** [comment] 2015-06-14 06:15
This sounds similar to https://github.com/spring-io/initializr/issues/116, albeit with Gradle rather than Maven.

I would guess that the import of the Spring Cloud bom, which contains a superset of Spring Boot 1.2.x's dependency management, is overriding the default dependency management provided by the Boot plugin.

**Comment by snicoll** [comment] 2015-06-14 07:38
Indeed, we should probably put this issue at the top of the TODO stack (this one and spring-io/initializr#116) .

**Comment by Koizumi85** [comment] 2015-06-14 08:32
Hi all,

I've prepared a demonstration repository with a project which contains exactly my gradle setup.
You can find it here:
https://github.com/Koizumi85/spring-boot-test

If you clone this and call ./gradlew build, the simple context-startup test fails.
If you remove the comments of the hibernate dependencies in build.gradle and build again, the test passes.

I hope this helps to find and solve the problem.

**Comment by snicoll** [comment] 2015-06-14 08:58
I am not entierely sure how we're going to fix the problem but dependency management wise you can workaround that for now with the following

```gradle
dependencyManagement {
        imports {
                mavenBom "org.springframework.cloud:spring-cloud-starter-parent:1.0.2.RELEASE"
                mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        }
}
```

With your project, I get a weird `org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.actuate.metrics.writer.MetricWriter] found for dependency:` (ping @dsyer)

**Comment by dsyer** [comment] 2015-06-14 10:27
My best guess on that: you have a mixture of SpringBoot 1.2 and 1.3 on the classpath still.

**Comment by snicoll** [comment] 2015-06-15 06:32
Nope, that's all `1.3.0.M1`: https://gist.github.com/snicoll/883fd829caefd69f6b38

**Comment by dsyer** [comment] 2015-06-15 07:49
There's no actuator anywhere though.

**Comment by wilkinsona** [comment] 2015-06-15 12:52
I think that gist is incomplete. Actuator's a compile dependency of the project:

```
compile("org.springframework.boot:spring-boot-starter-actuator")
```

And I see it in the output from `./gradlew dependencies` and its version is 1.3.0.M1. The full failure is:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servoMetricCollector' defined in class path resource [org/springframework/cloud/netflix/servo/ServoMetricsAutoConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.boot.actuate.metrics.writer.MetricWriter]: : No qualifying bean of type [org.springframework.boot.actuate.metrics.writer.MetricWriter] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.actuate.metrics.writer.MetricWriter] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:766)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:812)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:521)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:678)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:274)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:931)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:920)
	at de.mydomain.ServiceApplication.main(ServiceApplication.java:14)
	... 6 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.boot.actuate.metrics.writer.MetricWriter] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1320)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:961)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 25 more
```

Something very weird is going on as running with `--debug` produces this auto-configuration report:

```
=========================
AUTO-CONFIGURATION REPORT
=========================


Positive matches:
-----------------

   ConfigServiceBootstrapConfiguration#configServicePropertySource
      - matched (OnPropertyCondition)

   PropertyPlaceholderAutoConfiguration#propertySourcesPlaceholderConfigurer
      - @ConditionalOnMissingBean (types: org.springframework.context.support.PropertySourcesPlaceholderConfigurer; SearchStrategy: current) found no beans (OnBeanCondition)


Negative matches:
-----------------

   ConfigServiceBootstrapConfiguration.RetryConfiguration
      - @ConditionalOnClass classes found: org.springframework.retry.annotation.Retryable,org.aspectj.lang.annotation.Aspect,org.springframework.boot.autoconfigure.aop.AopAutoConfiguration (OnClassCondition)
      - @ConditionalOnProperty missing required properties spring.cloud.config.failFast  (OnPropertyCondition)

   DiscoveryClientConfigServiceBootstrapConfiguration
      - @ConditionalOnClass classes found: com.netflix.discovery.DiscoveryClient,org.springframework.cloud.config.client.ConfigServicePropertySourceLocator (OnClassCondition)
      - @ConditionalOnProperty missing required properties spring.cloud.config.discovery.enabled  (OnPropertyCondition)


Exclusions:
-----------

    None
```

**Comment by snicoll** [comment] 2015-06-15 13:07
Yup, I am confused by Gradle report. @dsyer the gist is updated https://gist.github.com/snicoll/883fd829caefd69f6b38

**Comment by snicoll** [comment] 2015-06-16 13:49
Can we leave the `MetricWriter` thing on the side for now? This is unrelated to the original request and looking at the state of Spring Cloud, it looks like the current Spring Boot is not compatible with Spring Cloud (I can see the root cause of the issue above does not match the Spring Cloud master code).

@wilkinsona I think this issue is basically a general dependency problem with multiple BOMs involved. Let me know when you have time to discuss this. Thanks!

**Comment by Toilal** [comment] 2015-06-23 10:18
Same issue here, using a spring batch/spring boot project embedded in Dropwizard.

**Comment by Toilal** [comment] 2015-06-23 12:07
Fixed by setting the latest version of hibernate using `<dependencyManagement>` in maven pom.xml.

**Comment by danielsava** [comment] 2015-07-02 03:28
Do not put Hibernate-core 4.3.10 together with Hibernate-entitymanager 4.3.5. I had the some problem. Fix by setting only Hibernate-entitymanager 4.3.5 or Hibernate-core 4.3.10

**Comment by abedultamimi** [comment] 2015-09-08 07:37
Awesome, just found out that netbeans has replaced my hibernate-entitymanager version with 4.3.1-final
after i unified the version things are well

**Comment by snicoll** [comment] 2017-01-11 15:11
The Spring Cloud bom has been restructured to avoid this problem. Let me know if I am missing anything.

**Closed by snicoll** 2017-01-11 15:11 UTC
