### ISSUE TITLE
Gradle-plugin tests are failing when temp path contains non-ascii characters

### ISSUE THREAD

**Issue by bjornlindstrom** [spring-projects/spring-boot#9929] opened 2017-08-01 18:51 UTC
On my windows machine the default temp path used by java is C:/Users/Björn/AppData/Local/Temp. This is causing BootRunIntegrationTests to fail with the following error:

```
basicExecution [Gradle 4.1-rc-1]
java.lang.AssertionError: 
Expecting:
 <":compileJava
:processResources NO-SOURCE
:classes
:bootRun
1. file:/C:/Users/Bj%c3%b6rn/AppData/Local/Temp/junit1470878138307527972/junit3394823167681286126/build/classes/java/main/
2. file:/C:/Users/Bj%c3%b6rn/AppData/Local/Temp/junit1470878138307527972/junit3394823167681286126/build/resources/main

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
">
to contain:
 <"1. file:/C:/Users/Björn/AppData/Local/Temp/junit1470878138307527972/junit3394823167681286126/build/classes/java/main/"> 

```

How to reproduce
Set environment variable JAVA_TOOL_OPTIONS to i.e. -Djava.io.tmpdir=C:\temp\testö\ and run mvn clean install.

Version: 2.0.0.BUILD-SNAPSHOT

It is easy to work around the problem by setting the the tmpdir with JAVA_TOOL_OPTIONS as described in the how to reproduce.

**Comment by wilkinsona** [comment] 2017-08-01 19:33
I think we'll need to decode the URL in `BootRunApplication`. Something like this:

```
System.out.println(i++ + ". " + URLDecoder.decode(url.toExternalForm(), "UTF-8"));
```

@bjornlindstrom Could you give that a try please and verify it's sufficient to get the Gradle plugin module to build cleanly on your machine?

**Comment by bjornlindstrom** [comment] 2017-08-01 20:00
@wilkinsona That works 👍

**Comment by wilkinsona** [comment] 2017-08-03 07:02
@bjornlindstrom Thanks for the confirmation

**Comment by wilkinsona** [comment] 2017-09-20 10:44
This was addressed as part of https://github.com/spring-projects/spring-boot/issues/10019.

**Comment by wilkinsona** [comment] 2017-09-20 10:44
Duplicate of #10019

**Closed by wilkinsona** 2017-09-20 10:44 UTC
Labels: priority: normal, type: chore
