### ISSUE TITLE
Converter beans cannot be defined as lambdas

### ISSUE THREAD

**Issue by Hoysion** [spring-projects/spring-boot#24413] opened 2020-12-09 02:35 UTC
```java
@Configuration
public class ConverterConfig {
    @Bean
    public Converter<String, LocalDate> localDateConverter() {
        return source -> LocalDate.parse(source, CommonConstants.DATE_FORMATTER);
//        return new Converter<String, LocalDate>() {
//            @Override
//            public LocalDate convert(String source) {
//                return LocalDate.parse(source, CommonConstants.DATE_FORMATTER);
//            }
//        };
    }
}
```
start app successfully when add converter without  the lambda exp.otherwise,failed to start app and the following result will be outputted.
Can't spring boot infer the type from the lambda exp?
```java
Caused by: java.lang.IllegalArgumentException: Unable to determine source type <S> and target type <T> for your Converter [org.hoysing.stress.converter.ConverterConfig$$Lambda$1601/1414642952]; does the class parameterize those types?
```

**Comment by Hoysion** [comment] 2020-12-09 02:45
the version is 2.2.5

**Comment by philwebb** [comment] 2020-12-09 03:16
We need to update `ApplicationConversionService.addBeans` to consider the factory method signature. We have some logic in `ConfigurationPropertiesBean` that could probably be extracted.

**Comment by philwebb** [comment] 2020-12-09 03:17
Flagging for team attention to consider if we want to try and fix this as a bug, or consider it a known limitation and mark it as an enhancement.

**Comment by Hoysion** [comment] 2020-12-09 03:25
ok.thanks!

**Comment by snicoll** [comment] 2020-12-09 07:40
@philwebb don't we have already a PR about that that's been triaged? https://github.com/spring-projects/spring-boot/pull/22885

**Comment by philwebb** [comment] 2020-12-09 18:46
Thanks @snicoll, I knew I'd seen this issue before but I couldn't find it. Closing as a duplicate of #22885

**Closed by philwebb** 2020-12-09 18:46 UTC
Labels: for: team-attention, type: bug
