### ISSUE TITLE
spring.resources.cache.period doesn't work

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#16488] opened 2019-04-08 10:55 UTC
Spring Boot 2.1.4.RELEASE

As far as I can tell, the property `spring.resources.cache.period` can't ever do anything.
`ResourceProperties.Cache.Cachecontrol.toHttpCacheControl` will always return an object, therefore [this else branch](https://github.com/spring-projects/spring-framework/blob/v5.1.6.RELEASE/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/ResourceHandlerRegistration.java#L172) is never taken.

A possible fix is to ensure `toHttpCacheControl` returns `null` if no properties are set.

**Comment by snicoll** [comment] 2019-04-08 11:27
The cache period is [configured as the MaxAge of the CacheControl](https://github.com/spring-projects/spring-boot/blob/cd914aaa4d7507b4e7fd66c65701335745a49303/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration.java#L169-L177). There is also a test that asserts it is set.

Rather than describing a technical solution, can you share a sample we can run that reproduces the problem you're experiencing?

**Comment by OrangeDog** [comment] 2019-04-08 11:57
Sorry, this is with WebMVC, not WebFlux.
It's reproduced with spring-boot-starter-web, no config, a single static file, and the `...period` property set to something valid.

**Comment by snicoll** [comment] 2019-04-08 12:00
And what are we supposed to reproduce with this setup? MVC is also covered by [a test](https://github.com/spring-projects/spring-boot/blob/cd914aaa4d7507b4e7fd66c65701335745a49303/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfigurationTests.java#L796-L815) that's passing at the moment. Can we please ignore the technical analysis and focus on the feature?

**Comment by OrangeDog** [comment] 2019-04-08 12:15
I am focussing on the feature. Despite whatever tests might exist, it doesn't actually work.
Here's an explicit reproduction: https://gist.github.com/OrangeDog/8899a0b33561c3aa2100d9fe94a40f3f

```
$ curl -i http://localhost:8080/test.js
HTTP/1.1 200
Last-Modified: Mon, 08 Apr 2019 11:53:35 GMT
Accept-Ranges: bytes
Content-Type: application/javascript
Content-Length: 0
Date: Mon, 08 Apr 2019 12:15:09 GMT
```

**Comment by snicoll** [comment] 2019-04-08 13:24
Thanks for the reproduction.

**Comment by eiselems** [comment] 2019-05-04 17:56
@snicoll I was looking a bit at this bug.
Thanks for pointing out the test for MVC, it was really helpful. I think I found a major flaw in there.

See: https://github.com/spring-projects/spring-boot/blob/cd914aaa4d7507b4e7fd66c65701335745a49303/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfigurationTests.java#L803-L812

There is a for loop over handlerMap.keySet (handlerMap itself is a Map<String, Object>).
So actually we are iterating over the keySet which is a Set<String>.
So instead of having the ResourceHttpRequestHandler stored in handler, we just have the key, which is a string.

Because of this:
```
			if (handler instanceof ResourceHttpRequestHandler) {
``` 
Is always false, which means the asserts are never evaluated.

**Comment by eiselems** [comment] 2019-05-04 19:00
I tried to create a solution but currently I am not sure if this is the best outcome:
Basically it comes now down to the assertion of the test:

![image](https://user-images.githubusercontent.com/5188694/57183593-85861580-6eaf-11e9-98dc-ff1f367edb43.png)

Would it be ok to return:
CacheControl [max-age=5, must-revalidate, no-transform, public, private, proxy-revalidate]?

**Comment by eiselems** [comment] 2019-05-04 19:23
After the change the POC project done by @OrangeDog returns
```
curl -i http://localhost:8080/test.js

HTTP/1.1 200
Last-Modified: Sat, 04 May 2019 19:19:45 GMT
Cache-Control: max-age=86400
Accept-Ranges: bytes
Content-Type: application/javascript
Content-Length: 6
Date: Sat, 04 May 2019 19:23:05 GMT
Proxy-Connection: keep-alive
Connection: keep-alive```

**Comment by philwebb** [comment] 2019-05-06 05:56
@eiselems Thanks for looking into the cause of this. GitHub won't let us assign the issue to you directly but I'll assign it to `spring-contributor` which will stop anyone else picking it up. If you want to submit a PR for what you have, that would be great!

**Comment by eiselems** [comment] 2019-05-06 07:57
@philwebb Really looking forward to raise a PR. Still want to do some comparison to webflux.
Think it would be best if both implementations would handle the flag the same way.

**Comment by eiselems** [comment] 2019-05-06 21:03
@bclozel Just so I got it right. You are also supporting to fix it in Spring (instead of working around it in boot). Fixing means:

Spring
* Creating a proper CacheControl based on the cachePeriod (if available) in case no CacheControl is set. There we need to consider all cases e.g. -1, 0, any positive duration

Spring Boot:
* Design it, so that the null value of CacheControl is generated and passed together with the cachePeriod to Spring, which then will figure it out
* Update tests to verify if the values got correctly passed to Spring and verify the generated "effective" http headers if possible

Would love to work on this maybe over the next days. I think I will have a look on creating an issue with Spring then and reference it here.

**Comment by eiselems** [comment] 2019-05-08 19:48
Coming back after having a look at the Spring Source, luckily it seems there is no bug in Spring (at least in my opinion).

https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/config/annotation/ResourceHandlerRegistration.java#L169-L174

It is already setting everything correctly and handling null cases.
The problem is like @OrangeDog already said that Boot is actually never giving a `null`CacheControl.

So in order to fix this issue, it should be fine to make sure to pass null as a CacheControl in case nothing got set and just pass the cachePeriod as it is. Spring should then figure it out (see: https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/support/WebContentGenerator.java#L240-L254). 

I will try to update my already opened PR and see what I get.

**Comment by eiselems** [comment] 2019-05-08 21:17
@OrangeDog @snicoll maybe you want to have another look at: https://github.com/spring-projects/spring-boot/pull/16730

**Comment by bclozel** [comment] 2019-05-10 21:11
Closing in favor of #16730

**Closed by bclozel** 2019-05-10 21:11 UTC
Labels: type: bug
