### ISSUE TITLE
Path pattern matching not working with controller

### ISSUE THREAD

**Issue by mohan404** [spring-projects/spring-boot#34385] opened 2023-02-26 11:28 UTC
A simple controller is not working with spring boot 3.0.3. 

Project Structure:
![image](https://user-images.githubusercontent.com/124535636/221407555-2956f83b-82ff-4e47-a2f3-db1531e6fe86.png)

build.gradle
![image](https://user-images.githubusercontent.com/124535636/221407570-13ea9eaa-2ce8-4ba5-979b-feffd3cc2598.png)

TestController:
![image](https://user-images.githubusercontent.com/124535636/221407599-2b28e470-82b4-4023-9f46-9937a496f252.png)

Logs:
[springboot_3.0.3.logs.zip](https://github.com/spring-projects/spring-boot/files/10833581/springboot_3.0.3.logs.zip)

The issue gets resolved, once I switch to spring boot version 3.0.2

**Comment by bclozel** [comment] 2023-02-26 12:05
This is very likely a duplicate of #34379.
If there is no space in the path of the application, we can reopen this issue.

**Closed** 2023-02-26 12:06 UTC
Labels: status: duplicate

**Comment by wilkinsona** [comment] 2023-02-26 13:54
The logs show a space so this do indeed look like a duplicate of #34379:

```
C:\Users\Mohans9\OneDrive - Verifone\Documents\Study\code\jpa\bin\main
```
