### ISSUE TITLE
The build-image goal for the spring-boot-maven-plugin used to work without any issues inside the GitHub Actions.   The image was executed successfully after loading the self-signed certificate.  The build has failed suddenly and received the below error message.    The paketo build pack used is 5.22.0.   Is there any fix available, how to install or copy the certificate inside the Github Actions.

### ISSUE THREAD

**Issue by Exnadella** [spring-projects/spring-boot#33701] opened 2023-01-05 20:15 UTC
The build-image goal for the spring-boot-maven-plugin used to work without any issues inside the GitHub Actions.  The paketo build pack used is 5.22.0.  The build has failed suddenly.  The image was executed successfully after loading the self-signed certificate and received the below error message.  Is there any fix available, how to install or copy the certificate inside the Github Actions.

```
2023-01-05T19:10:14.4706440Z [INFO]  > Running creator
2023-01-05T19:10:19.8527803Z [INFO]     [creator]     ===> ANALYZING
2023-01-05T19:10:19.8748340Z [INFO]     [creator]     Previous image with name "docker.io/library/dockerurcashimage:latest" not found
2023-01-05T19:10:19.8815851Z [INFO]     [creator]     ===> DETECTING
2023-01-05T19:10:20.5292560Z [INFO]     [creator]     6 of 24 buildpacks participating
2023-01-05T19:10:20.5297632Z [INFO]     [creator]     paketo-buildpacks/ca-certificates   3.5.1
2023-01-05T19:10:20.5302159Z [INFO]     [creator]     paketo-buildpacks/bellsoft-liberica 9.10.1
2023-01-05T19:10:20.5302705Z [INFO]     [creator]     paketo-buildpacks/syft              1.23.0
2023-01-05T19:10:20.5303406Z [INFO]     [creator]     paketo-buildpacks/executable-jar    6.5.0
2023-01-05T19:10:20.5307404Z [INFO]     [creator]     paketo-buildpacks/dist-zip          5.4.0
2023-01-05T19:10:20.5307891Z [INFO]     [creator]     paketo-buildpacks/spring-boot       5.22.0
2023-01-05T19:10:20.5311487Z [INFO]     [creator]     ===> RESTORING
2023-01-05T19:10:20.5311839Z [INFO]     [creator]     ===> BUILDING
2023-01-05T19:10:20.5339497Z [INFO]     [creator]     
2023-01-05T19:10:20.5343386Z [INFO]     [creator]     Paketo Buildpack for CA Certificates 3.5.1
2023-01-05T19:10:20.5346973Z [INFO]     [creator]       https://github.com/paketo-buildpacks/ca-certificates
2023-01-05T19:10:20.5352054Z [INFO]     [creator]       Launch Helper: Contributing to layer
2023-01-05T19:10:20.5370795Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
2023-01-05T19:10:20.5440063Z [INFO]     [creator]     
2023-01-05T19:10:20.5440440Z [INFO]     [creator]     Paketo Buildpack for BellSoft Liberica 9.10.1
2023-01-05T19:10:20.5446421Z [INFO]     [creator]       https://github.com/paketo-buildpacks/bellsoft-liberica
2023-01-05T19:10:20.5451835Z [INFO]     [creator]       Build Configuration:
2023-01-05T19:10:20.5456603Z [INFO]     [creator]         $BP_JVM_JLINK_ARGS           --no-man-pages --no-header-files --strip-debug --compress=1  configure custom link arguments (--output must be omitted)
2023-01-05T19:10:20.5460860Z [INFO]     [creator]         $BP_JVM_JLINK_ENABLED        false                                                        enables running jlink tool to generate custom JRE
2023-01-05T19:10:20.5465052Z [INFO]     [creator]         $BP_JVM_TYPE                 JRE                                                          the JVM type - JDK or JRE
2023-01-05T19:10:20.5468945Z [INFO]     [creator]         $BP_JVM_VERSION              11.*                                                         the Java version
2023-01-05T19:10:20.5472681Z [INFO]     [creator]       Launch Configuration:
2023-01-05T19:10:20.5476532Z [INFO]     [creator]         $BPL_DEBUG_ENABLED           false                                                        enables Java remote debugging support
2023-01-05T19:10:20.5480483Z [INFO]     [creator]         $BPL_DEBUG_PORT              8000                                                         configure the remote debugging port
2023-01-05T19:10:20.5484517Z [INFO]     [creator]         $BPL_DEBUG_SUSPEND           false                                                        configure whether to suspend execution until a debugger has attached
2023-01-05T19:10:20.5489809Z [INFO]     [creator]         $BPL_HEAP_DUMP_PATH                                                                       write heap dumps on error to this path
2023-01-05T19:10:20.5496159Z [INFO]     [creator]         $BPL_JAVA_NMT_ENABLED        true                                                         enables Java Native Memory Tracking (NMT)
2023-01-05T19:10:20.5502601Z [INFO]     [creator]         $BPL_JAVA_NMT_LEVEL          summary                                                      configure level of NMT, summary or detail
2023-01-05T19:10:20.5512274Z [INFO]     [creator]         $BPL_JFR_ARGS                                                                             configure custom Java Flight Recording (JFR) arguments
2023-01-05T19:10:20.5512745Z [INFO]     [creator]         $BPL_JFR_ENABLED             false                                                        enables Java Flight Recording (JFR)
2023-01-05T19:10:20.5515050Z [INFO]     [creator]         $BPL_JMX_ENABLED             false                                                        enables Java Management Extensions (JMX)
2023-01-05T19:10:20.5515736Z [INFO]     [creator]         $BPL_JMX_PORT                5000                                                         configure the JMX port
2023-01-05T19:10:20.5516298Z [INFO]     [creator]         $BPL_JVM_HEAD_ROOM           0                                                            the headroom in memory calculation
2023-01-05T19:10:20.5516904Z [INFO]     [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes                                               the number of loaded classes in memory calculation
2023-01-05T19:10:20.5517376Z [INFO]     [creator]         $BPL_JVM_THREAD_COUNT        250                                                          the number of threads in memory calculation
2023-01-05T19:10:20.5517792Z [INFO]     [creator]         $JAVA_TOOL_OPTIONS                                                                        the JVM launch flags
2023-01-05T19:10:20.5518146Z [INFO]     [creator]         Using Java version 11.* from BP_JVM_VERSION
2023-01-05T19:10:20.5523168Z [INFO]     [creator]       BellSoft Liberica JRE 11.0.17: Contributing to layer
2023-01-05T19:10:20.5529534Z [INFO]     [creator]         Downloading from https://github.com/bell-sw/Liberica/releases/download/11.0.17+7/bellsoft-jre11.0.17+7-linux-amd64.tar.gz
2023-01-05T19:10:20.8538240Z [INFO]     [creator]         Verifying checksum
2023-01-05T19:10:21.0381125Z [INFO]     [creator]         Expanding to /layers/paketo-buildpacks_bellsoft-liberica/jre
2023-01-05T19:10:22.4778715Z [INFO]     [creator]         Adding 124 container CA certificates to JVM truststore
2023-01-05T19:10:23.3351054Z [INFO]     [creator]         Writing env.launch/BPI_APPLICATION_PATH.default
2023-01-05T19:10:23.3358049Z [INFO]     [creator]         Writing env.launch/BPI_JVM_CACERTS.default
2023-01-05T19:10:23.3367036Z [INFO]     [creator]         Writing env.launch/BPI_JVM_CLASS_COUNT.default
2023-01-05T19:10:23.3373009Z [INFO]     [creator]         Writing env.launch/BPI_JVM_SECURITY_PROVIDERS.default
2023-01-05T19:10:23.3379010Z [INFO]     [creator]         Writing env.launch/JAVA_HOME.default
2023-01-05T19:10:23.3384399Z [INFO]     [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.append
2023-01-05T19:10:23.3389628Z [INFO]     [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.delim
2023-01-05T19:10:23.3394640Z [INFO]     [creator]         Writing env.launch/MALLOC_ARENA_MAX.default
2023-01-05T19:10:23.3402560Z [INFO]     [creator]       Launch Helper: Contributing to layer
2023-01-05T19:10:23.3437167Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/active-processor-count
2023-01-05T19:10:23.3442679Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/java-opts
2023-01-05T19:10:23.3447495Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/jvm-heap
2023-01-05T19:10:23.3452615Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/link-local-dns
2023-01-05T19:10:23.3457517Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/memory-calculator
2023-01-05T19:10:23.3461746Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/security-providers-configurer
2023-01-05T19:10:23.3466037Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/jmx
2023-01-05T19:10:23.3470373Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/jfr
2023-01-05T19:10:23.3474621Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/security-providers-classpath-9
2023-01-05T19:10:23.3479008Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/debug-9
2023-01-05T19:10:23.3483122Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/nmt
2023-01-05T19:10:23.3487342Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/openssl-certificate-loader
2023-01-05T19:10:23.3495025Z [INFO]     [creator]       Java Security Properties: Contributing to layer
2023-01-05T19:10:23.3500271Z [INFO]     [creator]         Writing env.launch/JAVA_SECURITY_PROPERTIES.default
2023-01-05T19:10:23.3504613Z [INFO]     [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.append
2023-01-05T19:10:23.3508778Z [INFO]     [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.delim
2023-01-05T19:10:23.3578728Z [INFO]     [creator]     
2023-01-05T19:10:23.3579073Z [INFO]     [creator]     Paketo Buildpack for Syft 1.23.0
2023-01-05T19:10:23.3579716Z [INFO]     [creator]       https://github.com/paketo-buildpacks/syft
2023-01-05T19:10:23.3585289Z [INFO]     [creator]         Downloading from https://github.com/anchore/syft/releases/download/v0.62.1/syft_0.62.1_linux_amd64.tar.gz
2023-01-05T19:10:23.6023153Z [INFO]     [creator]         Verifying checksum
2023-01-05T19:10:24.1710815Z [INFO]     [creator]         Writing env.build/SYFT_CHECK_FOR_APP_UPDATE.default
2023-01-05T19:10:24.1775694Z [INFO]     [creator]     
2023-01-05T19:10:24.1776090Z [INFO]     [creator]     Paketo Buildpack for Executable JAR 6.5.0
2023-01-05T19:10:24.1776731Z [INFO]     [creator]       https://github.com/paketo-buildpacks/executable-jar
2023-01-05T19:10:28.6298308Z [INFO]     [creator]       Class Path: Contributing to layer
2023-01-05T19:10:28.6299672Z [INFO]     [creator]         Writing env/CLASSPATH.delim
2023-01-05T19:10:28.6300047Z [INFO]     [creator]         Writing env/CLASSPATH.prepend
2023-01-05T19:10:28.6302076Z [INFO]     [creator]       Process types:
2023-01-05T19:10:28.6304093Z [INFO]     [creator]         executable-jar: java org.springframework.boot.loader.WarLauncher (direct)
2023-01-05T19:10:28.6304829Z [INFO]     [creator]         task:           java org.springframework.boot.loader.WarLauncher (direct)
2023-01-05T19:10:28.6306310Z [INFO]     [creator]         web:            java org.springframework.boot.loader.WarLauncher (direct)
2023-01-05T19:10:28.6578576Z [INFO]     [creator]     
2023-01-05T19:10:28.6579474Z [INFO]     [creator]     Paketo Buildpack for Spring Boot 5.22.0
2023-01-05T19:10:28.6580442Z [INFO]     [creator]       https://github.com/paketo-buildpacks/spring-boot
2023-01-05T19:10:28.6580793Z [INFO]     [creator]       Build Configuration:
2023-01-05T19:10:28.6581214Z [INFO]     [creator]         $BP_SPRING_CLOUD_BINDINGS_DISABLED   false  whether to contribute Spring Boot cloud bindings support
2023-01-05T19:10:28.6581606Z [INFO]     [creator]       Launch Configuration:
2023-01-05T19:10:28.6643444Z [INFO]     [creator]         $BPL_SPRING_CLOUD_BINDINGS_DISABLED  false  whether to auto-configure Spring Boot environment properties from bindings
2023-01-05T19:10:28.6644189Z [INFO]     [creator]         $BPL_SPRING_CLOUD_BINDINGS_ENABLED   true   Deprecated - whether to auto-configure Spring Boot environment properties from bindings
2023-01-05T19:10:30.2332376Z [INFO]     [creator]       Creating slices from layers index
2023-01-05T19:10:30.2333987Z [INFO]     [creator]         dependencies (111.4 MB)
2023-01-05T19:10:30.2340803Z [INFO]     [creator]         spring-boot-loader (281.8 KB)
2023-01-05T19:10:30.2342021Z [INFO]     [creator]         snapshot-dependencies (0.0 B)
2023-01-05T19:10:30.2663431Z [INFO]     [creator]         application (77.3 MB)
2023-01-05T19:10:30.2671092Z [INFO]     [creator]       Launch Helper: Contributing to layer
2023-01-05T19:10:30.2681227Z [INFO]     [creator]         Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings
2023-01-05T19:10:30.2687143Z [INFO]     [creator]       Spring Cloud Bindings 1.10.0: Contributing to layer
2023-01-05T19:10:30.2688353Z [INFO]     [creator]         Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
2023-01-05T19:10:30.4471752Z [INFO]     [creator]     unable to invoke layer creator
2023-01-05T19:10:30.4472942Z [INFO]     [creator]     unable to contribute spring-cloud-bindings layer
2023-01-05T19:10:30.4473445Z [INFO]     [creator]     unable to get dependency spring-cloud-bindings
2023-01-05T19:10:30.4474368Z [INFO]     [creator]     unable to download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar
2023-01-05T19:10:30.4475171Z [INFO]     [creator]     could not download https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar: 401
2023-01-05T19:10:30.4501318Z [INFO]     [creator]     ERROR: failed to build: exit status 1
2023-01-05T19:10:31.2592633Z [INFO] 
2023-01-05T19:10:31.2601592Z [INFO] ------------------------------------------------------------------------
2023-01-05T19:10:31.2601940Z [INFO] Skipping URCash Webapp
2023-01-05T19:10:31.2602381Z [INFO] This project has been banned from the build due to previous failures.
2023-01-05T19:10:31.2602845Z [INFO] ------------------------------------------------------------------------
2023-01-05T19:10:31.2603415Z [INFO] ------------------------------------------------------------------------
2023-01-05T19:10:31.2603716Z [INFO] BUILD FAILURE
2023-01-05T19:10:31.2604216Z [INFO] ------------------------------------------------------------------------
2023-01-05T19:10:31.2604501Z [INFO] Total time:  02:28 min
2023-01-05T19:10:31.2604970Z [INFO] Finished at: 2023-01-05T19:10:31Z
2023-01-05T19:10:31.2605599Z [INFO] ------------------------------------------------------------------------
2023-01-05T19:10:31.2606775Z [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.7.0:build-image (default) on project co.uk.urcash: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:2.7.0:build-image failed: Builder lifecycle 'creator' failed with status code 51 -> [Help 1]
2023-01-05T19:10:31.2607825Z [ERROR] 
2023-01-05T19:10:31.2608322Z [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2023-01-05T19:10:31.2608894Z [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2023-01-05T19:10:31.2609169Z [ERROR] 
2023-01-05T19:10:31.2609591Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2023-01-05T19:10:31.2610224Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
2023-01-05T19:10:31.2889226Z ##[error]Process completed with exit code 1.
```
_Originally posted by @Exnadella in https://github.com/spring-projects/spring-boot/issues/31581#issuecomment-1372691811_

**Comment by Exnadella** [comment] 2023-01-05 20:20
The spring Boot version used is 2.7.0, JDK 11, the distribution used is temurin, 
![image](https://user-images.githubusercontent.com/22579094/210872664-f2949965-8cdd-424c-9b14-7eea240387b3.png)

**Comment by scottfrederick** [comment] 2023-01-05 20:28
Duplicate of #33699

**Closed** 2023-01-06 00:24 UTC
Labels: status: duplicate
