### ISSUE TITLE
Collection-based configuration binding replaces a nested object with a new one

### ISSUE THREAD

**Issue by Fotonix** [spring-projects/spring-boot#14044] opened 2018-08-10 19:43 UTC
This issue happens on Spring boot 2.0, on Spring boot 1.5 it works as expected.

Let’s imagine the following class:
```java
public class Bar {
    private String name;
    private int counter = -1;
    private boolean active = true;

    // getter and setter
}
```
 And there is a bean with a collection of Bars with one initialized item:
```java
@Component
@ConfigurationProperties(prefix = "test.env")
public class Foo {
    private List<Bar> bars = new ArrayList<>();
    
    // getter and setter

    public Foo() {
        Bar defaultBar = new Bar();
        defaultBar.setName("default");
        defaultBar.setCounter(5);
        defaultBar.setActive(false);

        bars.add(defaultBar);
    }
}
```
Using application.properties we override one property in the first item of bars:
```properties
test.env.bars[0].name=test
```
It is expected that the only 'name' field will be overwritten but the whole item is replaced with a new Bar object. After that the Foo.bars list contains one Bar object with the following properties:
 ```properties
name="test"
counter=-1
active=true
```
That means a new object has been created, the only "name" property has been defined, and the old Bar object has been replaced with the new one instead of just resetting "name" property of the existing object.

**Comment by wilkinsona** [comment] 2018-08-13 07:00
Thanks for the report. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/9137 where the comments hopefully explain the reasoning for the change in behaviour and why we believe it is an improvement, particularly [this one](https://github.com/spring-projects/spring-boot/issues/9137#issuecomment-301144003) and [this one](
https://github.com/spring-projects/spring-boot/issues/9137#issuecomment-333161752).

**Closed by wilkinsona** 2018-08-13 07:00 UTC
Labels: status: waiting-for-triage
