### ISSUE TITLE
spring-boot 1.5.4 breaks Gradle annotation processing

### ISSUE THREAD

**Issue by kutzi** [spring-projects/spring-boot#10478] opened 2017-10-02 08:32 UTC
We're using the spring-boot Gradle plugin and the net.ltgt.apt(-idea) plugin for annotation processing.
While trying to upgrade spring-boot, I noticed that the annotation processing for generating sources for immutables.github.io stopped working in 1.5.4, while 1.5.3 works fine.

The configuration looks like this (excerpt):

```
plugins {
  id "org.springframework.boot" version '1.5.7.RELEASE'
  id "net.ltgt.apt-idea" version "0.12"
}

dependencies {
  ext.immutablesVersion = "2.5.5"
  compileOnly "org.immutables:value:" + immutablesVersion + ":annotations"
  apt "org.immutables:value:" + immutablesVersion
  ...
}
```

The effect is that the folder for the generated sources is still generated, but left empty.
So the compilation of the dependend Java sources fails.

Any spring-boot version below and equal 1.5.3 works. Every greater than that fails.

**Comment by wilkinsona** [comment] 2017-10-02 09:07
Can you please provide a small sample that reproduces the problem?

**Comment by kutzi** [comment] 2017-10-02 09:59
Unfortunately I cannot reproduce it with a simple project. So it must be some side effect of some configuration in our full build script.
Any idea how I could debug this? Gradle output even with --debug wasn't showing me anything helping.

**Comment by wilkinsona** [comment] 2017-10-02 10:19
The only thing that I can think of beyond running Gradle with `--debug` is to attach a debugger to the VM running the Gradle build and verify, for example, that it's calling `javac` with the expected arguments.

> Unfortunately I cannot reproduce it with a simple project. So it must be some side effect of some configuration in our full build script.

If you can reproduce it with something bigger then we can take a look at that

**Comment by kutzi** [comment] 2017-10-04 09:12
I have now copied all the build scripts from the project where I can reproduce it to a clean project, but still I cannot reproduce it in the new project ...
Currently, I'm out of clues.
Sending you the original project sources is not an option for me, unfortunately.

**Comment by wilkinsona** [comment] 2017-10-04 09:32
Thanks for trying. Unfortunately, it's impossible for us to diagnose a problem where the cause is unknown so I'll close this one for now. If you figure out how to reproduce the problem in a way that you can share, please let us know and we'll reopen the issue.

**Closed by wilkinsona** 2017-10-04 09:32 UTC
Labels: status: feedback-provided, status: waiting-for-triage
