### ISSUE TITLE
Spring Boot Maven plugin build-image goal debug output is way too verbose

### ISSUE THREAD

**Issue by nickstolwijk** [spring-projects/spring-boot#23006] opened 2020-08-19 08:35 UTC
Spring Boot version: 2.3.3

We are using the new goal `build-image` of the `Spring Boot Maven plugin`. After invoking Maven with the `--debug` flag (`-X`) the Spring Boot Maven plugin started to output all of the hexadecimal communication with the Docker API (I suppose). This is not readable and not helpfull at all.

Endless and endless pages of the following:
```
0x80][\n]"
[DEBUG] http-outgoing-0 >> "[0x16]y[0xa8][0xf8]B([0xc2]*[0x2][0x8a]%$[0xbc][0x8c]F[0xa8][0xc6]*[0x6][0xfd]4[0xb4]C[0x19][0xd8][0xee]4[0xbb][0xb3][0xc8]_[0xf1]_h[0xa2]!J[0xa2][0xdf][0xfd]Q[0xc6];[0xd3][0xf2][0x92]%[0xd1][0x98]&[0xf3]
[0xba][0xf7][0x9e]{[0xcf][0xb9][0xb7][0xfb][0xf3][0xd7][0xb7][0xef][0x0]&[0x90]K[0xa3][0x15][0xd9][0x14]F[0xd2]H[0xe0]N[0xb][0xd2][0x18]m[0xc5][0x18]\[0xb3][0xdc]M[0xe1]^[0x1a])[0x8c][0x1b][0x9f][0xfb])L[0xa4]0[0xc9][0xd0][0x15][0xf
9]|[0x87]K[0x8f][0xaf]{b[0x95][0x7][0xd2][0xec]!C[0xc7][0xf2][0x16]=[0xbb][0x91][0x96][0x9e][[0x10]:[0xc7][0xd0]R[0x90]e[0x9f][0xeb]([0x10][0xc]7NZgjW[0x8f][0xfb]e[0xb7][0xa0][0x3][0xe9][0x97]s[0xb3][0x14][0xd1]4#}[0xa9]g[0x19][0xf4
][0xd0]1[0x87][0xe7][0xeb][[0xa2][0xa8]s[0xc7]^[0x2][0xb1][0xe1][0xd1][0x93][0xbb]"[0xf4][0xa6]*[0xe5][0xde][0xc5]8[0xab][0xa0][0xec][0x86]U[0x83][0xbc][0x11][0xf0][0x8a]x[0xaf][0x82]m[0xb7][0xa8][0x2][0xe1][0xbe][0xe0][0xe6][0xae]E
[0x90][0xa7]mQ[0x86]E[0xb5]#[0x2][0x11][0xe4][0x86]W[0x19][0x92][0xb][0xaa]$[0xc][0x15][0xe9][0x8b]|TY[0x17][0xc1]+[0xc3][0x8e][0xe1][0xc2][0xb2]*r[0xef][0x80]m[0xfd]1[0xa9]7%[0x11][0x9f][0x8d][0xcf][0xc5][0x8b][0x9b][0xc2][0x95]>%*
[0x8a][0xaa]V[0x81][0xbb]`^[0x96]v[0xb8][0x17]q-[0x95][0xbf][0xa0][0xc8][0xb6]ktJ[0x7]J[0xe9]Z[0xdd]&[0xd3]).[0xa4]K[0xc5][0x12]e[0xe8]=[[0x4][0xd2][0x9b][0x7][0xe5][0xa8]"|MEu[0xc6]h[0xc2][0xd0]][0x8d]'[0xcf]0[0xfe][0xef][0x82]1dx[
0xa9][0xf4][0xfa][0xf4]00\[0x1c]:[0xdd]_[0xab][0xaf]O[0x10]'9[0xd6][0xad][0xc][0xed][0x9e]R[0xdb]Q[0xf5][0x8]d0[0xe]$[0x8e]U[A[0xf3][0xe2][0xf6][\n]"
[DEBUG] http-outgoing-0 >> "[0xaf][0xd6][0xfb][0xd2][0xf3]2[0xf2][0xb5][0xac][0x88]U[0x19]Jz[0x98][0xf3]}[0xa5][0xad][0xe4][0xa1][0x99][0xc3]8[0x9e][0x16]/[0x1f]y[0x96][0x86][0xe9]HAE[0xd4][0xb6][0xc7][0xd2][0xc0][0xf5][0xc5]7n[0xcc
]T[0xe2][0xe0][0x1c][0xce]3[0x9c]?[0x1a][
```

Could you take a look at what the supposed output of the debug level of the Maven plugin is?

**Comment by snicoll** [comment] 2020-08-19 08:37
Thanks for the report, this is a duplicate of #22674

**Closed by snicoll** 2020-08-19 08:37 UTC
Labels: status: waiting-for-triage
