### ISSUE TITLE
spring boot do not support META-INF/resources in jar jar

### ISSUE THREAD

**Issue by hengyunabc** [spring-projects/spring-boot#9913] opened 2017-07-31 08:14 UTC
I write a demo to support `META-INF/resources` in jar jar and jsp.

https://github.com/hengyunabc/spring-boot-fat-jar-jsp-sample

When start the demo with `-Dtomcat.staticResourceCustomizer.enabled=false`

```
java -Dtomcat.staticResourceCustomizer.enabled=false -jar jsp-start/target/jsp-start-0.0.1-SNAPSHOT.jar
```

http://localhost:8080/ 404

http://localhost:8080/hello-from-common ok

---

The root reason is that `LaunchedURLClassLoader` urls do not contains the fat jar. 

The parent of `LaunchedURLClassLoader` is `AppClassLoader`, which urls contains the fat jar

**Comment by wilkinsona** [comment] 2017-07-31 08:25
Duplicate of #8324.

Also, please note that we don't support the use of JSPs in fat jars. You should use a war file instead.

**Closed by wilkinsona** 2017-07-31 08:25 UTC
Labels: status: waiting-for-triage
