### ISSUE TITLE
With the latest SNAPSHOT of springboot-starter-parent on windows machines "Java nio file InvalidPathException Illegal char <:> " exception is thrown

### ISSUE THREAD

**Issue by ahmeterdem** [spring-projects/spring-boot#32558] opened 2022-09-30 13:08 UTC
With the latest SNAPSHOT of springboot-starter-parent on windows machines "Java nio file InvalidPathException Illegal char <:> " exception is thrown.

We use 3.0.0.SNAPSHOT  of spring-boot-starter-parent. The machine is windows. I think the path is constructed by adding / at the beginning(as in linux). 

After changing the version of spring-boot-starter-parent to 2.7.4 it worked fine. 

Best regards

**Comment by bclozel** [comment] 2022-09-30 13:10
Closing as a duplicate of spring-projects/spring-framework#29226

**Closed by bclozel** 2022-09-30 13:10 UTC
Labels: status: waiting-for-triage
