### ISSUE TITLE
DataSource Metrics are not created for DataSources behind @RefreshScope proxies

### ISSUE THREAD

**Issue by oxygensar** [spring-projects/spring-boot#6596] opened 2016-08-09 13:12 UTC
It seems that DataSource metrics are not created for DataSources annotated with @RefreshScope.

```
@SpringBootApplication
public class DemoApplication {

    @Autowired
    private DataSource dataSource;

    @Bean
// uncomment to breate datasource metrics
//  @RefreshScope
    public DataSource dataSource(DataSourceProperties properties) {

        DataSourceBuilder factory = DataSourceBuilder
                .create(properties.getClassLoader())
                .driverClassName(properties.getDriverClassName())
                .url(properties.getUrl()).username(properties.getUsername())
                .password(properties.getPassword());
        if (properties.getType() != null) {
            factory.type(properties.getType());
        }
        return factory.build();
    }

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}
```

will give us:

```
curl http://localhost:8080/health

{"status":"UP","diskSpace":{"status":"UP","total":179729068032,"free":44992753664,"threshold":10485760},"db":{"status":"UP","database":"HSQL Database Engine","hello":1},"refreshScope":{"status":"UP"},"configServer":{"status":"UNKNOWN","error":"no property sources located"}}
```

and 

```
curl http://localhost:8080/metrics/datasource.*
{"datasource.primary.active":0,"datasource.primary.usage":0.0}

```

but if one uncomments @RefreshScope line health endpoint will continue working but metrics won't be created:

```
curl http://localhost:8080/metrics/datasource.*
{}
```

Tested on Spring Boot 1.3.5 and 1.4.0

Looks like RefreshScope always creates JDK Dynamic Proxies and classes like HikariPoolDataSourceMetadataProviderConfiguration check dataSource using instanceof operator which doesn't allow them to identify original DataSource behind the proxy.

Please advice are there any plans to add metrics support for RefreshScope beans.

**Comment by philwebb** [comment] 2016-08-09 13:27
There are no immediate plans to support this. It might be possible to extract the underlying target from the proxy and whilst this might work for `@RefreshScope` it probably wouldn't work for other proxy types. Perhaps there's something we can do when #4353 is resolved.

**Comment by oxygensar** [comment] 2016-08-09 13:40
I see, by the way at least in case of Hikari DataSource it's possible to use instanceof HikariConfigMXBean (instead of HikariDataSource) which is an interface and thus implemented by proxy as well as DataSource. This interface provides almost all methods required by DataSourcePoolMetadataProvider. I can submit a pull request in case you think this might be useful.
Another way could be for RefreshScope to respect proxy-target-class...

**Comment by philwebb** [comment] 2016-08-09 14:01
@oxygensar I pull request would be most welcome if you have time. I took a quick look at `HikariDataSourcePoolMetadata` and thought the `DirectFieldAccessor` would cause problems.

**Comment by snicoll** [comment] 2018-12-14 16:57
Duplicate of #15227

**Closed by snicoll** 2018-12-14 16:57 UTC
Labels: type: enhancement
