### ISSUE TITLE
Support @Timed annotation for WebFlux

### ISSUE THREAD

**Issue by lbilger** [spring-projects/spring-boot#18680] opened 2019-10-21 16:35 UTC
We recently switched an application from WebMvc to WebFlux. We used the `@Timed` annotation on our controller methods to get custom timing metrics with custom percentiles. After switching to WebFlux, this stopped working. There is the default metric created by the `MetricsWebFilter`, but I couldn't find a way to configure the percentiles recorded.

It would be great if you could also support the `@Timed` annotation for WebFlux for maximum flexibility.
Alternatively, it would also help us if we could globally configure the percentiles for the timer recorded by the `MetricsWebFilter`.

**Comment by Vakhturov** [comment] 2020-10-19 15:39
Hi guys, could anyone please clarify the status of this issue?
The linked PR looks good and nothing seems be prevent this from merging, but there is no update since August.

**Comment by wilkinsona** [comment] 2020-10-28 15:49
@Vakhturov Unfortunately, we haven't had time to review the pull request yet. We'd like to get the changes into a 2.x release but it's unlikely to be in 2.4.x which RCs tomorrow.

**Comment by patpatpat123** [comment] 2020-12-14 04:23
Hello Team, 

I am currently using 2.4.1 recently released.
The issue is still here I believe.

Created an out of the box Webflux project out of spring.io.
No @Timed annotation, can see the usual

```
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{exception="None",method="POST",outcome="SUCCESS",status="200",uri="/myRoute",} 1.0
http_server_requests_seconds_sum{exception="None",method="POST",outcome="SUCCESS",status="200",uri="/myRoute",} 0.610389546
# HELP http_server_requests_seconds_max  
# TYPE http_server_requests_seconds_max gauge
http_server_requests_seconds_max{exception="None",method="POST",outcome="SUCCESS",status="200",uri="/myRoute",} 0.610389546

```

However, annotated my controller with @Timed("pleasefindme")
and getting the exact same under /prometheus endpoint.

A little help please?
Thank you

**Comment by snicoll** [comment] 2020-12-14 08:26
> The issue is still here I believe.

@patpatpat123 this issue is open and assigned to `2.x` (i.e. unresolved). The feature is not implemented so this to be expected.

**Comment by izeye** [comment] 2021-04-15 01:23
This seems to be resolved via https://github.com/spring-projects/spring-boot/pull/23112.

**Comment by wilkinsona** [comment] 2021-04-15 06:38
Yes indeed. Thanks, @izeye.

**Closed by wilkinsona** 2021-04-15 06:38 UTC
Labels: type: enhancement

**Comment by patpatpat123** [comment] 2021-04-15 07:09
Many thanks all
