### ISSUE TITLE
About embedded tomcat's default temp directory.

### ISSUE THREAD

**Issue by sunbufu** [spring-projects/spring-boot#15935] opened 2019-02-13 05:21 UTC
Hi, I have a question about embedded tomcat's default temp directory.  
When spring boot is running with embedded tomcat, spring boot will create a temp directory for tomcat, like `/tmp/tomcat.****.8080/` on Linux. But Linux will delete it, if we haven't used this directory in 10 days. and you will get an error when tomcat using this directory.  
But I think spring boot should make sure this directory is valid, since created this directory.

**Comment by wilkinsona** [comment] 2019-02-13 07:09
Duplicate of #9616

**Closed by wilkinsona** 2019-02-13 07:09 UTC
Labels: status: waiting-for-triage
