### ISSUE TITLE
Startup time slower in 1.5.x due to excessive calls to RandomAccessFile

### ISSUE THREAD

**Issue by alexanderuv** [spring-projects/spring-boot#11152] opened 2017-11-26 07:51 UTC
**Bug Report**
I have a project that is using Spring Boot 1.2.2. Now, I'm planning to migrate to 1.5.8.
I started by upgrading the packaging (maven plugin - repackage goal) first. Although there's no functional issue, I was surprised to see the startup time in the DEV server DOUBLED (at the very least). However, I can't reproduce this behavior locally - where the startup time actually went down by at least 20%.

In order to understand where the problem was, I tried using every possible version between those two to understand what was the version that introduced the problem. Unfortunately, for some reason versions 1.4.x to 1.5.1 didn't work. Looks like there was some bug that was fixed as I had some classpath issue.

However version 1.3.8 still worked and the startup time was fine. After some more profiling, I finally found something interesting. The number of calls to RandomAccessFile had grown a lot from 1.3.8 to 1.5.2.

- v1.3.8 -> ~291,000 calls 
- v1.5.2 -> ~647,000 calls

This didn't seem like a problem when running locally, but when on the DEV server, it was. Now, the apps running on the DEV server are executed from a Network share, and every file operation has way more latency, so I figured the slowness might be due to the increase in file operations.

Would it be possible to cache some of these calls? or pre-read bigger chunks of the file? Even an extension point would be useful in this case.

<img width="1419" alt="SpringBoot 1.5.2 startup" src="https://user-images.githubusercontent.com/7009201/33238122-457d2634-d23b-11e7-8a39-9e0ad9cceb3e.png">

<img width="1431" alt="SpringBoot 1.3.8 startup" src="https://user-images.githubusercontent.com/7009201/33238129-61301620-d23b-11e7-8843-9a53bd82d297.png">

**Comment by wilkinsona** [comment] 2017-11-26 08:46
Thanks for sharing your findings.

The number of calls to RandomAccessFile should be a function of the number of classes that are loaded and resources that are accessed. Making that access faster via caching (if that’s even possible) would be addressing a symptom rather than the causes. I’d prefer to understand, and hopefully reduce, the apparent increase in class and resource loading. Can you please provide a small sample that illustrates the increase in calls to RandomAcessFile?

**Comment by alexanderuv** [comment] 2017-11-26 19:25
@wilkinsona I tried to see if this happens with any other project (one that I can share) but it seems like the newer version in that case issues less than half the calls to RandomAccessFile. 

It's important to mention my project has 200+ dependencies packaged within the same jar. I guess most projects don't have that many embedded jars... so it might have to do with that

I am adding some debug log statements to the loader to see if I can make sense out of it. Will share results... 

Thanks for the promptness

**Comment by alexanderuv** [comment] 2017-11-26 22:07
@wilkinsona I think I found the actual reason:

v1.3.8 loads all classes at startup and apparently those classes stay loaded. Seems to be due to usage of the system class loader, instead of a custom one. Please correct me if I'm wrong.

v1.5.2 however, has a custom mechanism to load jar files on-demand and although it does some caching, it's only at the metadata level - like files headers and positions, but not content. This means scan operations actually read the file every time.

Now check these two pics:

This is v1.3.8
<img width="1427" alt="v1.3.8" src="https://user-images.githubusercontent.com/7009201/33244783-461dda94-d2b2-11e7-89fd-6da25520b62a.png">
It seems most of the jars, if not all are loaded during the main method.

Now, this is v.1.5.2
<img width="1426" alt="v1.5.2" src="https://user-images.githubusercontent.com/7009201/33244799-7b60f6b4-d2b2-11e7-9181-214dc1b48af0.png">
As you can see, all operations are triggered during initialization, when the Spring context is resolving beans. I checked again and my jar has actually 700+ nested jars, so having to go through each one of them and iterating each single class file might take some time. To be fair, I've only seen it going thru every single one of them when looking for ``message*.properties`` resources. For the rest of beans, it somehow only looks in jars where they are/could be found.

**Comment by wilkinsona** [comment] 2017-11-27 10:35
> v1.3.8 loads all classes at startup and apparently those classes stay loaded. Seems to be due to usage of the system class loader, instead of a custom one. Please correct me if I'm wrong.

AFAIK, the classes stay loaded in both 1.3.x and 1.5.x. Furthermore, while some changes were made to the ClassLoader is 1.4, Boot's custom class loader (`LaunchedURLClassLoader`) should be used in both versions being examined in this issue.

> To be fair, I've only seen it going thru every single one of them when looking for message*.properties resources

There was a [change made to message.properties detection](https://github.com/spring-projects/spring-boot/commit/e520c47c4f8a80b491849679e0deae3509f02805), but it happened in 1.3.2. I don't, yet, understand the difference in behaviour between 1.3.8 and 1.5.2. Specifically, I'd expect `ResourceBundleCondition` to behave in the same way in both versions.

`ResourceBundleCondition.getResources` being called 114532 times doesn't make any sense to me yet. I'd would expect it to be called once per comma-separated entry in the `spring.messages.basename` property. The property defaults to `messages` so I'd expect a single call in a Boot app using the default configuration. That's certainly how various samples that I've just tried behave.

I still feel like I'm a long way away from understanding what's going on here and that a sample that reproduces the behaviour will be the best way to fix that. It doesn't have to be your exact application, just something that's sufficient to reproduce the kind go numbers that you've been sharing.

**Comment by spring-issuemaster** [comment] 2017-12-04 10:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-12-11 10:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-12-11 10:35 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
