### ISSUE TITLE
Multi-profile YAML files with negated profile not working.

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#8318] opened 2017-02-16 19:30 UTC
According to the [documentation](http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/htmlsingle/#boot-features-external-config-multi-profile-yaml), profiles can be negated to exclude sections of a YAML file. For example if the following is the contents of application.yml:
```
prop:
  other: false
---
spring:
  profiles: '!something'
test:
  property: true
---  
```

The property `test.property` should not be set when the `something` profile is active. This does not work for me. I have created an example project and unit test to demonstrate: https://github.com/shollander/test-sb-properties/blob/master/src/test/java/TestPropertiesTest.java

**Comment by mbhave** [comment] 2017-02-16 20:06
@shollander That seems like a bug. Thanks for reporting!

**Comment by wilkinsona** [comment] 2017-02-16 20:12
I'm pretty sure that this is a duplicate of #8011

**Closed by wilkinsona** 2017-02-16 20:12 UTC
Labels: type: bug

**Comment by mbhave** [comment] 2017-02-16 20:22
oh yes it is. thanks @wilkinsona.
