### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: class org.springframework.boot.cloud.CloudFoundryVcapEnvironmentPostProcessor is not assignable to interface org.springframework.context.ApplicationListener

### ISSUE THREAD

**Issue by yangyongkangse** [spring-projects/spring-boot#21502] opened 2020-05-19 09:39 UTC
spring-boot version:2.3.0.RELEASE
spring-cloud version:Hoxton.SR4

**Comment by wilkinsona** [comment] 2020-05-19 09:50
Duplicate of #20749.

**Closed by wilkinsona** 2020-05-19 09:50 UTC
Labels: status: waiting-for-triage
