### ISSUE TITLE
ClassCastException :AjpNioProtocol cannot be cast to AbstractHttp11Protocol

### ISSUE THREAD

**Issue by stunaz** [spring-projects/spring-boot#16462] opened 2019-04-04 13:41 UTC
Hi, with spring-boot 2.1.3.RELEASE, the following code works perfectly.
```java
    @Bean
    public WebServerFactoryCustomizer<TomcatServletWebServerFactory> servletContainer() {
        return server -> {
                server.setProtocol("AJP/1.3");
                server.setPort(8009);

        };
    }
```
with spring-boot 2.2.0.M1, i have the following issue:

```log
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:157)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:407)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1278)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1266)
	at com.nbfg.mf.atpl.web.Application.main(Application.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.ClassCastException: org.apache.coyote.ajp.AjpNioProtocol cannot be cast to org.apache.coyote.http11.AbstractHttp11Protocol
	at org.springframework.boot.autoconfigure.web.embedded.TomcatWebServerFactoryCustomizer.lambda$customizeProcessorCache$12(TomcatWebServerFactoryCustomizer.java:135)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.customizeConnector(TomcatServletWebServerFactory.java:306)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:166)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154)
	... 13 common frames omitted
```

**Comment by wilkinsona** [comment] 2019-04-04 13:44
Duplicate of #16413.

**Closed by wilkinsona** 2019-04-04 13:44 UTC
Labels: status: waiting-for-triage
