### ISSUE TITLE
Password Generated When Using Resource Server

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#14557] opened 2018-09-20 19:12 UTC
A default password is generated by Boot in a WebFlux application when a Resource Server is being used.

Create a resource server within a WebFlux application with nothing but the required dependencies 

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-resource-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-jose</artifactId>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>6.0</version>
        </dependency>
```
and the yml configuration

```yml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://idp:9999/auth/realms/demo
```

 and see that the default password is logged the console

PS: This might also happen in servlet environments, but I'm not certain

**Comment by mbhave** [comment] 2019-07-25 18:06
Closing in favor of PR #17646.

**Closed by mbhave** 2019-07-25 18:06 UTC
Labels: type: enhancement

**Comment by Beer1234** [comment] 2019-07-30 04:40
> A default password is generated by Boot in a WebFlux application when a Resource Server is being used.
> 
> Create a resource server within a WebFlux application with nothing but the required dependencies
> 
> ```
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-webflux</artifactId>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-security</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.security</groupId>
>             <artifactId>spring-security-oauth2-resource-server</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.security</groupId>
>             <artifactId>spring-security-oauth2-jose</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>com.nimbusds</groupId>
>             <artifactId>oauth2-oidc-sdk</artifactId>
>             <version>6.0</version>
>         </dependency>
> ```
> 
> and the yml configuration
> 
> ```yaml
> spring:
>   security:
>     oauth2:
>       resourceserver:
>         jwt:
>           issuer-uri: http://idp:9999/auth/realms/demo
> ```
> 
> and see that the default password is logged the console
> 
> PS: This might also happen in servlet environments, but I'm not certain

**Comment by michaeltecourt** [comment] 2020-02-15 19:16
Hi @rwinch @mbhave,

I'm only seeing this now as I'm a bit late to the Spring Boot 2.2 party.

The problem is that PR #17646 did not only deactivate password generation, but the whole in-memory authentication manager auto-config. It was a feature, not a bug IMHO. 

I actually discussed this a while ago with @dsyer for Spring Boot 1.5 and the old `spring-security-oauth` module (can't retrieve the GitHub issue). He used to downgrade the order of precedence of the OAuth 2.0 module auto-config, so the actuator remained under HTTP Basic security.

The reasoning : In practice, HTTP Basic is the only actuator security that was accepted by the some infrastructure teams I worked with. HTTP Basic is a convenient option for metrics scrapers and old tools like nagios. 
The infrastructure team configured the same actuator username/password for all micro-services on a given environment.

Even when we use OAuth 2.0 for our HTTP APIs, we keep the actuator with HTTP Basic.

Now it just means we have to create the `InMemoryUserDetailsManager` ourselves, but I was curious if this was an intended side-effect ?

**Comment by michaeltecourt** [comment] 2020-02-15 21:25
* It probably deserves a mention in the Spring Boot 2.2 release notes anyway :)

**Comment by mbhave** [comment] 2020-02-25 18:59
@michaeltecourt I think for cases where there's a mix of security models like OAuth2 for the main app and HTTP basic for the actuators, it's better to let the user control it and declare their own `AuthenticationManager`. However, this change has also caused other failures. Please see #20317. If the outcome of that issue is that the user needs to create their own `InMemoryUserDetailsManager`, it should be documented in the release notes indeed.

**Comment by michaeltecourt** [comment] 2020-02-26 08:14
Well, the missing `UserDetailsService` is an inconvenience, and a bit incoherent with the fact that Spring Boot provides the `spring.security.user` config props.
Configuring manually an `AuthenticationManager` feels like the Spring Boot is no longer auto-configuring spring security ?

**Comment by michaeltecourt** [comment] 2020-02-26 08:29
The more I think about it, the less I understand the problem with a default password being generated even though OAuth is used.

IMO the framework shouldn't deactivate HTTP Basic Auth implicitely if JWT is enabled.  
I would rather have a property to enable/disable explicitely HTTP Basic Auth, like `spring.security.http-basic.enabled`. Switching it off would make the `spring.security.user.*` properties ineffective.
The password generation should be triggered by HTTP Basic enabled + undefined `spring.security.user.password` property.

**Comment by mbhave** [comment] 2020-02-26 22:24
The `spring.security.user.*` are not used when the resource server is on the classpath. In Spring Boot 1.x, we've had several issues with the auto-configuration trying to guess and configuring multiple `WebSecurityConfigurerAdapter`s. The security auto-configuration is much simpler now, where, based on the classpath, only one `WebSecurityConfigurerAdapter` is configured. For anything that's more complex, it's best to let the user decide those rules and configure the ordering of `WebSecurityConfigurerAdapter`s etc.

If you have any more thoughts about this, please comment on the issue I linked above since that is the open issue about the missing `AuthenticationManager`.

**Comment by wilkinsona** [comment] 2020-03-05 16:28
We've opened #20399 to make an update to the release notes.
