### ISSUE TITLE
Hikari CP actuator metrics

### ISSUE THREAD

**Issue by mshetty794** [spring-projects/spring-boot#20605] opened 2020-03-22 10:40 UTC
I have been trying to get actuator metrics for Hikari CP.  Let me know if it has to be custom implemented.

Looking for basic metrics like no active connection used etc. 

Below are the Hikari configuration  and actuator set in application.yml 

```yaml
spring:
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
       jdbc.batch_size: 5000
       default_schema: xxxx
       jdbc.fetch_size: 100
       jdbc.time_zone: UTC
       generate_statistics: true
  datasource:
    hikari:
      data-source-properties:
        oracle.net.encryption_client: REQUIRED
        oracle.net.encryption_types_client: ( AES256 )
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@x.x.x.x:1521:orcl
    username: xxxx
    password:xxxx$
    registerMbeans: true
    poolName: hikari-1

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
```

**Comment by wilkinsona** [comment] 2020-03-23 08:03
Thanks for the report. Unfortunately, a snippet of YAML isn't sufficient to allow us to diagnose the problem. To be able to help you we'd need to know the version of Spring Boot you are using and where you are expecting the metrics to appear. The best way to provide that information to us is with a minimal sample that reproduces your problem. You can share it with us by zipping it up and attaching it to this issue or by pushing it to a separate repository.

**Comment by spring-issuemaster** [comment] 2020-03-30 08:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-04-06 08:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-04-06 08:05 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
