### ISSUE TITLE
Upgrade logback to support Jakarta

### ISSUE THREAD

**Issue by livk-cloud** [spring-projects/spring-boot#32691] opened 2022-10-13 02:28 UTC
Current *SpringBootVersion*=3.0.0-M5

The built-in *logbak* version is 1.2.11, which is not compatible with *Jakarta*

![image](https://user-images.githubusercontent.com/50291874/195484620-b4b6498d-1f8c-4e03-8a1a-c273d8d36f35.png)

![image](https://user-images.githubusercontent.com/50291874/195484736-f8a544ce-72d5-4e97-a59d-41bc9900b71e.png)

**Comment by linghengqian** [comment] 2022-10-13 02:55
- Duplicate of https://github.com/spring-projects/spring-boot/issues/12649, this issue should be marked as invalid and closed.

**Closed** 2022-10-13 05:32 UTC
Labels: status: waiting-for-triage
