### ISSUE TITLE
Execution from init.d fails to find keystore

### ISSUE THREAD

**Issue by CluEleSsUK** [spring-projects/spring-boot#6725] opened 2016-08-23 11:18 UTC
I have created an executable jar using the gradle config in version 1.4.0, and when run from command line ./path/to/my/jar.jar all works fine, however when i symlink it to into /etc/init.d/ and run sudo service start myservice the following error is found in the logs:

```
org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Jetty servlet container
        at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:143) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) [spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        at com.vatcat.backend.rest.Application.main(Application.java:13) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [backend-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [backend-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [backend-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [backend-1.0-SNAPSHOT.jar:na]
Caused by: java.lang.IllegalStateException: no valid keystore
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:48) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1023) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:330) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:67) ~[jetty-server-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:260) ~[jetty-server-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[jetty-server-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.11.v20160721.jar!/:9.3.11.v20160721]
        at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:126) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
        ... 18 common frames omitted
```

I've tried a few permissions on the keystore, and it is a fully qualified reference in the application.properties file.

I saw some other artifacts related to system.d permissions (the pid file folder one) and some symlink stuff so figured this might be a bug

**Comment by wilkinsona** [comment] 2016-08-23 13:44
Sorry, but I don't think we'll be able to solve your problem with just the information you've provided. The exception means that Jetty thinks that the `org.eclipse.jetty.util.resource.Resource` that represents the keystore doesn't exist. There are lots of reasons why that could be the case, most of them due to your environment.

We might be able to help if you can provide a small sample that reproduces the problem along with instructions on how to set things up exactly as you have.

**Comment by spring-issuemaster** [comment] 2016-08-30 13:45
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-09-06 13:45
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-09-06 13:45 UTC
