### ISSUE TITLE
Wrong markup in Appendix C of the Reference Manual 

### ISSUE THREAD

**Issue by aaguilera** [spring-projects/spring-boot#18247] opened 2019-09-17 08:30 UTC
In the Reference Manual, tables appearing in sections named

- C.1 From the “spring-boot-autoconfigure” module
- C.2 From the “spring-boot-actuator-autoconfigure” module

are showing wrong markup instead of links to API docs. For example:

> {github-code}/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/activemq/ActiveMQAutoConfiguration.{sc-ext}[`ActiveMQAutoConfiguration`]

or

> {dc-root}/org/springframework/boot/autoconfigure/jms/activemq/ActiveMQAutoConfiguration.{dc-ext}[javadoc]

This behavior appears in all output formats of the documentation (html, epub, pdf).

See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#auto-configuration-classes-from-autoconfigure-module

**Comment by wilkinsona** [comment] 2019-09-17 08:46
Thanks for the report. This is a duplicate of #18163.

**Closed by wilkinsona** 2019-09-17 08:46 UTC
Labels: status: waiting-for-triage
