### ISSUE TITLE
Difficulty deploying a Spring Boot app as a jar file. 

### ISSUE THREAD

**Issue by trish-tt** [spring-projects/spring-boot#16300] opened 2019-03-25 12:36 UTC
Hi everyone, 

I have developed a Spring Boot application for Jira - a proprietary issue tracking product. 

I have run the application on my Eclipse and deployed it on my NGINX server. I am then successfully able to install it on Jira as an add-on. However, when I do the same using a .jar (Java -jar <jar name>) I am unable to install it on Jira. 

Is there a difference between running my application using mvn spring-boot:run and Java -jar <jar name>? Can you please help me understand what the problem is while deploying using the .jar file. 

Thank you!

**Comment by wilkinsona** [comment] 2019-03-25 13:05
> Is there a difference between running my application using mvn spring-boot:run and Java -jar ? 

There are minimal differences when running an application using `spring-boot:run` and `java -jar`. If you have an application that works with one and not with the other, you may have found a bug.

> Can you please help me understand what the problem is while deploying using the .jar file?

Not without a lot more information. If you would like us to spend some time trying to help you, please take the time to provide a complete and minimal sample (as a zip file or in a separate repository on GitHub) that reproduces the problem.

**Comment by trish-tt** [comment] 2019-03-27 06:30
Hello, 

I'm pasting the link of a demo code I've been trying to work with - https://bitbucket.org/Sri_Annapurna/demo-jira-code/src/master/

The atlassian-connect.json file (located at Demo Jira code / src / main / resources / atlassian-connect.json) is my main app-descriptor file that is returned on running the app. Then using the baseUrl (https://apps.senecaglobal.com/jira) in that, I upload the application on my Jira instance. However I receive a HTTP response 401 error. I am attaching a screenshot of the same. 
![Screenshot (60)](https://user-images.githubusercontent.com/48913635/55055007-c5273980-5087-11e9-98c8-7226e1590db8.png)

**Comment by wilkinsona** [comment] 2019-03-27 09:34
Thanks. Unfortunately, the need to have a local JIRA installation in order to reproduce the problem means that it will be some time before I will be able to investigate any further. It's also not clear to me that Spring Boot is causing the problem rather than, say, how Nginx is proxying the application. I would recommend stripping things down as much as possible. For example, by removing Nginx and having JIRA connect to your application directly. You could also try enabling debug logging for `org.springframework.security` to see why the request from JIRA is being rejected with a 401.

**Comment by trish-tt** [comment] 2019-03-27 11:40
Hi, 
Thank you for your suggestion. I have tried to run my app without the NGINX server, using the temporary ngrok server and it works.

However, my question still lies. Why does my application, using the NGINX server, run and get installed while using spring-boot:run but returns an error while using java -jar.

**Comment by wilkinsona** [comment] 2019-03-27 11:50
>  I have tried to run my app without the NGINX server, using the temporary ngrok server and it works.

That would suggest that it's a problem with Nginx or its configuration rather than Spring Boot.

> Why does my application, using the NGINX server, run and get installed while using spring-boot:run but returns an error while using java -jar.

Security should behave exactly the same, irrespective of how you're launching your application. I suspect that you're seeing a difference in behaviour because your configuration is unintentionally different. Perhaps a file is being picked up via the current working directory when launching using `spring-boot:run` but it's not available when using `java -jar` as you're launching from a different directory. As I suggested above, you could enable debug logging for `org.springframework.security` to see why the request from JIRA is being rejected with a 401.

You could also use curl, or similar, to mimic the request that Jira makes to your application. If you can show that responding with a 200 when run using `mvn spring-boot:run` and a 401 when run using `java -jar`, we would be able to continue our investigation.

**Comment by spring-issuemaster** [comment] 2019-04-03 11:53
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-04-10 11:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-04-10 11:52 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
