### ISSUE TITLE
Create a RestClient alternative to WebTestClient and TestRestTemplate

### ISSUE THREAD

**Issue by plebcity** [spring-projects/spring-boot#39848] opened 2024-03-07 09:40 UTC
Since Spring Boot 3.2 we are using RestClient in our production code and we love it but for our Controller/Integration tests there isn't an easy way to create and/or inject a RestClient with all configuration necessary to make requests to the controllers.

I would love to have a preconfigured bean like WebTestClient and TestRestTemplate that we can inject into our tests.

**Comment by wilkinsona** [comment] 2024-03-07 09:46
Thanks for the suggestion. This is a duplicate of https://github.com/spring-projects/spring-framework/issues/31275.

**Closed by wilkinsona** 2024-03-07 09:46 UTC
Labels: status: waiting-for-triage
