### ISSUE TITLE
Spring boot failed to start

### ISSUE THREAD

**Issue by yuluo-yx** [spring-projects/spring-boot#33839] opened 2023-01-16 08:07 UTC
jdk: 17
idea: 2022.x
spring boot: 2.7.7

Spring boot files replaced with other suffixes in addition to dev and default configuration files cannot be started and are stuck at the 
logo

![$MCYOJL}O1CVSIODY1~`N}E](https://user-images.githubusercontent.com/77964041/212627972-15eef3c1-8d2b-4d5b-bb4f-b06f788610bc.png)

**Comment by yuluo-yx** [comment] 2023-01-16 08:08
Code samples are uploaded after masking

**Comment by yuluo-yx** [comment] 2023-01-16 08:54
please See https://github.com/yuluo-yx/spring-boot-2.7.7-.git

**Comment by bclozel** [comment] 2023-01-16 08:58
@yuluo-yx I'm sorry but the repro project has 12+ modules and lots of unrelated dependencies. Please reduce this sample to the minimum required to reproduce this issue.

**Comment by bclozel** [comment] 2023-01-16 10:27
This is silently failing because of

```
org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: failed to req API:localhost:8848/nacos/v1/ns/instance. code:500 msg: java.net.ConnectException: Connection refused
```

The exception is processed by listeners and rethrown by Spring Boot as expected, but I think that something with nacos is preventing this exception from being reported and failing the app properly. I'm closing this issue as this doesn't look related to Spring Boot. Please reach out to the nacos community about this. Feel free to reopen this issue if you manage to reproduce this problem without nacos being involved.

Thanks

**Closed by bclozel** 2023-01-16 10:27 UTC
Labels: status: waiting-for-triage, status: feedback-provided

**Comment by yuluo-yx** [comment] 2023-01-16 10:33
> 
Thank you so much!
