### ISSUE TITLE
The Content-Type of SpringBoot 2.5.6 version '/actuator/prometheus' route has become 'application/openmetrics-text'

### ISSUE THREAD

**Issue by blinkfox** [spring-projects/spring-boot#28585] opened 2021-11-09 10:43 UTC
I used the `spring-boot-starter-actuator` jar in my project. After I upgraded the SpringBoot version from `2.5.5` to `2.5.6`, when I visited the address of `/actuator/prometheus` through a browser, I found This address will become the form of the downloaded file (actually Content-Type is `application/openmetrics-text`) instead of the previous `text/plain`.

I carefully compared and debugged the related code, and found that the order of the two enumeration instances was adjusted in this submission ([Fix broken content negotiation for Prometheus with OpenMetrics](https://github.com/spring-projects/spring-boot/commit/437a1601efe8bd7b9983bbeec27b360368bfe80b)).

I think these two orders should be changed back to the previous order.

**Comment by wilkinsona** [comment] 2021-11-09 10:55
Thanks for the analysis. This is a duplicate of #28446.

**Closed by wilkinsona** 2021-11-09 10:55 UTC
Labels: status: waiting-for-triage
