### ISSUE TITLE
installBootDist creates executables with wrong permission

### ISSUE THREAD

**Issue by occho** [spring-projects/spring-boot#14158] opened 2018-08-21 10:23 UTC
With Gradle `application` plugin, `installBootDist` task is available to install distribution files.

When performing `installBootDist`, I observed the installed executables have wrong permission:
```
$ ./gradlew clean installBootDist

BUILD SUCCESSFUL in 1s
5 actionable tasks: 5 executed
$ ls -l build/install/initial-boot/bin/
total 24
-r-x-wSr-t  1 (xxx)  (xxx)  5207  8 21 19:19 initial
-r-x-wSr-t  1 (xxx)  (xxx)  2178  8 21 19:19 initial.bat
$ gstat -c "%a %n" ./build/install/initial-boot/bin/initial*
3525 ./build/install/initial-boot/bin/initial
3525 ./build/install/initial-boot/bin/initial.bat
```
Tested on mac.

The file permission is set to `-r-x-wSr-t` (0x755 in hex is 3525 in octal).
It should be like `-rwxr-xr-x` (0755, octal).

https://github.com/spring-projects/spring-boot/blob/v2.0.4.RELEASE/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/ApplicationPluginAction.java#L83

## Sample project

https://github.com/occho/gs-spring-boot/tree/filemode-bug-with-application-plugin/initial
## Version tested

spring-boot-gradle-plugin: 2.0.4.RELEASE

**Comment by philwebb** [comment] 2018-08-28 18:32
Thanks for the detailed analysis

**Comment by ivange94** [comment] 2018-09-11 18:43
@philwebb is this issue only about changing this line

`binCopySpec.setFileMode(0x755);`

to 

`binCopySpec.setFileMode(0755);`

**Comment by philwebb** [comment] 2018-09-11 18:59
@ivange94 Pretty much. Also trying to add a test if we can.

**Comment by wilkinsona** [comment] 2018-09-11 19:14
@ivange94 Thanks for your interest in fixing this. I should have assigned this issue to myself as I already have a fix in progress. Sorry. My work in progress is [here](https://github.com/wilkinsona/spring-boot/tree/gh-14158).

**Comment by julmuell** [comment] 2018-09-28 07:18
@wilkinsona On my machine the test fails with `org.junit.ComparisonFailure: expected:<4[20]> but was:<4[36]>`. The file permission of the file is 664 instead of 644. What could be the cause for that?

**Comment by philwebb** [comment] 2018-09-28 13:48
@julmuell What OS do you use? I wonder if it's an issue with the underlying filesystem being used.

**Comment by philwebb** [comment] 2018-10-01 15:06
@julmuell ext4 filesystem I assume?

**Comment by julmuell** [comment] 2018-10-01 18:02
@philwebb yes thats correct

**Comment by philwebb** [comment] 2018-10-02 05:33
Very odd, our CI uses a similar setup. 🤷‍♀️

**Comment by occho** [comment] 2018-10-02 05:52
Just a guess, but due to umask settings?

**Comment by julmuell** [comment] 2018-10-04 14:18
@occho good guess, this make sense. But with my umask setting the permissions should be as expected. Could the maven build run with a different umask?
 
```
➜  ~ umask
022
```

**Comment by wilkinsona** [comment] 2018-10-04 14:38
AFAIK, Maven doesn't do anything to the umask. Complicating things a little is the fact that it's a Gradle build triggered from Maven and the files in question are being copied from Gradle's cache into a tar archive. It's the entry in the tar on which the permissions check is being performed. They're copied with a `null` file mode which means that should be tarred with the same permissions as they have on disk in Gradle's cache.

We can probably afford to have a stronger opinion about the permissions on the files in the archive's lib directory. I'll reopen this issue to explicitly set the permissions to 0644 which should make the test more robust if nothing else.

**Closed** 2018-10-04 14:56 UTC
Labels: type: bug
