### ISSUE TITLE
System.console returns null for spring-boot:run

### ISSUE THREAD

**Issue by balbusm** [spring-projects/spring-boot#6347] opened 2016-07-07 10:19 UTC
I'm writing console application in Spring Boot. It should read some input data. 
When I run it with:
`mvn spring-boot:run`
System.console returns null.
Could you change behavior of run so console is available and user is able to type in.

BTW System.console works for `java -jar application.jar`

**Comment by snicoll** [comment] 2016-07-07 10:48
Works for me on a simple app so yours has probably something specific. Regardless, I am really not sure what we could do about it (check also [this SO thread](http://stackoverflow.com/questions/4203646/system-console-returns-null)). If you want us to investigate, please attach a sample that reproduces the issue.

**Comment by balbusm** [comment] 2016-07-07 13:04
See sample project.
[no-console.zip](https://github.com/spring-projects/spring-boot/files/352174/no-console.zip)

You also need Java 7 (update 25 in my case).
I noticed it works fine for Java 8 (update 92).

**Comment by snicoll** [comment] 2016-07-07 13:20
```
 no-console java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

Works for me. I am going to close this one as I have no indication something is wrong in Spring Boot.

**Closed by snicoll** 2016-07-07 13:20 UTC
Labels: feedback-provided

**Comment by marceloverdijk** [comment] 2017-03-03 13:22
When using Gradle (like `./gradlew bootRun`) the `System.console()` is indeed empty.
The issue can be solved by adding the `standardInput = System.in` to the `bootRun` task.

```
bootRun{
	standardInput = System.in
}
```

The `stadardInput` option is not Spring Boot specific but just part of Gradle's `JavaExec` task.
