### ISSUE TITLE
Upgrading spring boot returning 'text/html' response in case of error response 5XX/4XX

### ISSUE THREAD

**Issue by venkatnpedada** [spring-projects/spring-boot#16194] opened 2019-03-11 13:39 UTC
Error 5XX/4XX returns `text/html` response type instead of JSON after Spring Boot 2 upgradation. Please find the sample code in below repo.

Even tried with excluding Auto-config "ErrorMvcAutoConfiguration.class".

https://github.com/venkatnpedada/gradle-spring-boot-project

**Comment by bclozel** [comment] 2019-03-11 16:22
I've tested your application and it seems to work as expected.

With `ErrorMvcAutoConfiguration` excluded, the error response is the Servlet container error one, in HTML format in every case.

Once `ErrorMvcAutoConfiguration` is "un-excluded", I'm seeing the following behavior:

```
$ curl localhost:8080/echo_with_runtime_exception\?str=test

{"timestamp":"2019-03-11T16:20:12.719+0000","status":500,"error":"Internal Server Error","message":"I have not yet been implemented.","path":"/echo_with_runtime_exception"}
```

```
$curl  localhost:8080/echo_with_custom_exception\?str=test

{"timestamp":"2019-03-11T16:21:46.383+0000","status":409,"error":"Conflict","message":"Oops. Conflict!!!","path":"/echo_with_custom_exception"}%
```

Please clarify what is the expected behavior here and why this should be considered as a bug.
Thanks!

**Comment by spring-issuemaster** [comment] 2019-03-18 16:25
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-03-25 16:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-03-25 16:23 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
