### ISSUE TITLE
Can't git clone the project

### ISSUE THREAD

**Issue by freezehe** [spring-projects/spring-boot#11270] opened 2017-12-06 07:20 UTC
hi,I have a problem.I can't git clone the code on my windows,the error is  "unable to create file spring-boot-project/spring-boot-tools/spring-boot-g                                 radle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/Dependenc                                 yManagementPluginActionIntegrationTests-helpfulErrorWhenVersionlessDependencyFai                                 lsToResolve.gradle: Filename too long",
so please help me.thanks

**Comment by wilkinsona** [comment] 2017-12-06 07:41
Duplicate of #10953

**Closed by wilkinsona** 2017-12-06 07:41 UTC
Labels: status: waiting-for-triage
