### ISSUE TITLE
@ConfigurationProperties doesn't properly support Yaml null values

### ISSUE THREAD

**Issue by Sroca3** [spring-projects/spring-boot#40176] opened 2024-04-05 16:57 UTC
**Problem**
When processing configuration properties from a yaml file it appears there is not proper support of nulls even though yaml supports null as a first class citizen. Instead the [YamlProcessor](https://github.com/spring-projects/spring-framework/blob/main/spring-beans/src/main/java/org/springframework/beans/factory/config/YamlProcessor.java#L344) from spring framework and in turn the [OriginTrackedYamlLoader](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/env/OriginTrackedYamlLoader.java#L134) in spring boot both convert null values to empty strings.

**Example Usage**
Whether this is the right way to do this or not is up for debate, but as an example of where this would be useful is below. The attempt was to store the interpretation of the `is not null` sql concept in yaml in a configuration file:

```
condition:
  operator: NOT_EQUAL_TO
  values: 
  - ~
```
or the equivalent
```
condition:
  operator: NOT_EQUAL_TO
  value: [null]
```

**Related issue**
There is already an existing [issue](https://github.com/spring-projects/spring-framework/issues/19986) logged many years ago for spring-framework that is yet to be addressed. Both would have to be addressed to completely fix this gap though.

**Comment by philwebb** [comment] 2024-04-05 17:09
I think this a duplicate of #24133

**Closed by philwebb** 2024-04-05 17:09 UTC
Labels: status: waiting-for-triage
