### ISSUE TITLE
Very poor performance with Gradle build

### ISSUE THREAD

**Issue by vitalyster** [spring-projects/spring-boot#13095] opened 2018-05-08 08:58 UTC
I did start the discussion in [Gradle issue tracker](https://github.com/gradle/gradle/issues/5284) and we think a problem is in Spring Boot Gradle plugin. I can share build scans and anything else to find the root of the problem

**Comment by wilkinsona** [comment] 2018-05-08 09:11
I suspect that this may be due to the dependency management plugin creating and resolving a detached configuration to apply Maven-style exclusions to you build.

You said on the Gradle issue that it "takes ages" said in the title that performance is "very poor". Can you please quantify ages and very poor?  It's impossible to diagnose a performance problem with subjective descriptions of the time that's taken.

> I can share build scans

Yes please.

> anything else to find the root of the problem.

A sample project that reproduces the problem would be very useful.

**Comment by vitalyster** [comment] 2018-05-08 09:25
> Cumulative time spent resolving dependencies	5m 18.718s

Here is the build scan - https://scans.gradle.com/s/odpmjdnsiw3em

> sample project

I suspect small sample project will be faster, but I will try to create it

**Comment by wilkinsona** [comment] 2018-05-08 09:42
Thanks. Unfortunately, the scan doesn't tell us that much. For example, information about how many dependencies each project in your build has and what those dependencies are would be useful.

Of the total dependency resolution time, resolving detached configurations takes 152.216 seconds. That's slightly less than half of the 318.718s total time. Both seem high, but, again, it's impossible to know if it is high without more information. Are all of the dependencies cached? Or is this including time to download dependencies?

To test my theory about the time being spent applying Maven-style exclusions, you could try [disabling them](https://github.com/spring-gradle-plugins/dependency-management-plugin/#disabling-maven-exclusions). You may then have to add some additional exclusions to your projects' dependencies as [Gradle doesn't handle exclusions in a pom as Maven intends them to be handled](https://github.com/gradle/gradle/issues/1473).

**Comment by vitalyster** [comment] 2018-05-08 10:02
with `applyMavenExclusions = false`:

> Cumulative time spent resolving dependencies	1m 18.888s

(this includes dowload time of tomcat-annotations-api.jar which was not needed before somehow)

removing that line and again:

> Cumulative time spent resolving dependencies	5m 11.929s

(all dependencies are cached, no "download" message)

**Comment by wilkinsona** [comment] 2018-05-08 10:15
That's useful info, thanks. I don't understand the drop from 5m 11 to 1m 18 given that the detached configurations were, apparently, only responsible for 2m 32. Perhaps it's a quirk of how the build scan measures the time taken.

If you don't want to disable Maven exclusion handling and would like to pursue the possibility of making this faster, please open an issue against the [dependency management plugin](/spring-gradle-plugins/dependency-management-plugin) providing a sample that reproduces the problem.

**Closed by wilkinsona** 2018-05-08 10:15 UTC
Labels: status: feedback-provided, status: waiting-for-triage
