### ISSUE TITLE
Unable to set javax.persistence.validation.factory (spring.jpa.properties) as string cannot be cast to class

### ISSUE THREAD

**Issue by bjconlan** [spring-projects/spring-boot#2924] opened 2015-05-07 00:35 UTC
Currently the JpaProperties 'properties' fields get converted to a Map<String, String>. This causes issues in regards to how to register validator (both from a bean instance and from a class reference ie: 'org.springframework.validation.beanvalidation.LocalValidatorFactoryBean').

It would be nice if perhaps this was possible from configuration as opposed to re-implementing a custom EntityManagerFactory and shoehorning this case) (or even better if an explicit bean which implements a ValidatorFactory was registered just use that... else fallback to hibernates created factory (which i believe is also used for mvc method param validation)

**Comment by wilkinsona** [comment] 2015-05-19 13:36
Thanks. This is a duplicate of #2808.

**Closed by wilkinsona** 2015-05-19 13:36 UTC
