### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by pandiyan90** [spring-projects/spring-boot#24367] opened 2020-12-07 12:38 UTC
I have updated the spring boot version to 2.4.0 from 2.3.3.RELEASE. But following error occurs. Even tried moving back to 2.3.3. Still the issue persists. Would be grateful for help.
```
18:00:56.255 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: ConfigFileApplicationListener [org.springframework.boot.context.config.ConfigFileApplicationListener] is deprecated and can only be used as an EnvironmentPostProcessor
    at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:198) ~[spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:203) ~[spring-context-5.3.1.jar:5.3.1]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:196) ~[spring-context-5.3.1.jar:5.3.1]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:170) ~[spring-context-5.3.1.jar:5.3.1]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:148) ~[spring-context-5.3.1.jar:5.3.1]
    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.4.0.jar:2.4.0]
    at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_191]
    at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362) [spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) [spring-boot-2.4.0.jar:2.4.0]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) [spring-boot-2.4.0.jar:2.4.0]
    at net.sh360.clientproxy.SH360ClientProxyApplication.main(SH360ClientProxyApplication.java:14) [classes/:?]
```

**Comment by spencergibb** [comment] 2020-12-07 12:41
Are you are using Spring Cloud? If so, what version?

**Comment by pandiyan90** [comment] 2020-12-07 12:43
No. I am not using Spring Cloud.

**Comment by bclozel** [comment] 2020-12-07 13:31
@pandiyan90 do you have a sample application we could take a look at? Ideally a github project we could clone (or just zip it here directly). Making it minimal and just including the pieces required to reproduce the problem really helps.

Thanks!

**Comment by spring-issuemaster** [comment] 2020-12-14 13:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-12-21 13:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-12-21 13:31 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by bhagwandassoni1953** [comment] 2021-06-20 14:41
java.lang.IllegalStateException: ConfigFileApplicationListener [org.springframework.boot.context.config.ConfigFileApplicationListener] is deprecated and can only be used as an EnvironmentPostProcessor                                                   at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:200)                               at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)                               at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)                                 at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)                                 at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)                                 at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)                                      at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)                                     at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)                    at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)                                                 at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)                                                 at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)                                              at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374)                                                                      at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)                                                                                     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)                                                                                    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)                                                                                    at Application.main(Application.java:15)

**Comment by snicoll** [comment] 2021-06-20 14:56
@bhagwandassoni1953 please ask questions on StackOverflow.

**Comment by bhagwandassoni1953** [comment] 2021-06-20 15:04
Okay.
