### ISSUE TITLE
100% CPU after starting

### ISSUE THREAD

**Issue by Sammers21** [spring-projects/spring-boot#7709] opened 2016-12-20 18:32 UTC
So, during some minutes after re-deploying spring boot jar on my Linux server, the app costs all cpu. why?
![image](https://cloud.githubusercontent.com/assets/16746106/21363013/2ecaaa12-c704-11e6-830f-0a7001c00428.png)

![image](https://cloud.githubusercontent.com/assets/16746106/21363023/3c6bcd40-c704-11e6-8fe5-ff39b8b1d61e.png)

**Comment by philwebb** [comment] 2016-12-20 18:44
I have absolutely no idea. It could be your code, it could be a library, it could be Spring Boot itself. What we'll need is a sample application along with the steps needed to replicate the issue.

**Comment by Sammers21** [comment] 2016-12-20 21:39
The project is an REST service, which contains some @RestControllers. There is no other Threads or Runnable tasks.

**Comment by philwebb** [comment] 2016-12-21 05:41
@Sammers21 Can you please create a minimal sample and tell us how to replicate the issue. We're only going to be able to tell what's going on once we've reproduced the issue locally. A sample application is the best way for us to tell exactly what you're doing.

**Comment by spring-issuemaster** [comment] 2016-12-28 05:44
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-01-04 05:44
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-01-04 05:44 UTC
Labels: waiting-for-triage
