### ISSUE TITLE
Add excludeAutoConfiguration to @SpringBootTest

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-boot#8579] opened 2017-03-12 06:00 UTC
When using `@DataMongoTest` and flapdoodle, it's a snap to switch it on or off based on the `excludeAutoConfiguration` parameter.

When running an end-to-end test using Selenium and `@SpringBootTest`, there is no such option to disable flapdoodle. I tried `@ImportAutoConfiguration#exclude)`, but it didn't work.

So having the means to disable autoconfigs from this test annotation would be quite handy.

**Comment by philwebb** [comment] 2017-03-13 19:03
`@SpringBootTest` is not part of the `spring-boot-test-autoconfigure` project and as such it shouldn't have any knowledge of auto-configuration.

Can you share the Selenium sample so we can work out why `@ImportAutoConfiguration(exclude=...)` isn't working?

**Comment by gregturn** [comment] 2017-03-14 00:51
If you clone https://github.com/gregturn/flapdoodle-and-selenium and then run EndToEndTests, you'll find that despite having `@ImportAutoConfiguration(exclude = EmbeddedMongoAutoConfiguration.class)`, it will still run the test case using embedded MongoDB.

**Comment by philwebb** [comment] 2017-03-14 03:10
Ahh, OK. That makes sense. The `@ImportAutoConfiguration` `excludes` are only applied to those classes that would be imported by _that_ annotation. They have no effect on the `@EnableAutoConfiguration` annotation (via `@SpringBootApplication`) on `LearningSpringBootApplication`.

It might be nice if excludes were cumulative, but that's not currently the case.

The other annotations that offer `exclude` also have `@OverrideAutoConfiguration(enabled = false)`. This means that full auto-configuration never gets applied for them.

I think the easiest work-around for now is to use a `spring.autoconfigure.exclude` `Environment` property:

```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, properties="spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration")
```

**Comment by philwebb** [comment] 2018-03-21 20:56
Possibly somewhat related #12366

**Comment by dhirenmudgil** [comment] 2018-06-04 08:57
What to do if facing similar issues when using `@JsonTest`. Want to exclude auto-configuration of a Component.

**Comment by snicoll** [comment] 2018-06-04 09:03
@dhirenmudgil `@JsonTest` has an `excludeAutoConfiguration` field. Please ask question on StackOverflow. As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by dhirenmudgil** [comment] 2018-06-04 09:53
@snicoll I posted it here, because the same issue is with `@JsonTest` and `excludeAutoConfiguration` is not working because of above mentioned reason `The @ImportAutoConfiguration excludes are only applied to those classes that would be imported by that annotation. They have no effect on the @EnableAutoConfiguration annotation (via @SpringBootApplication) on LearningSpringBootApplication.`. And like `@ SpringBootTest ` it does not take properties. `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, properties="spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration")
`

**Comment by snicoll** [comment] 2018-07-19 09:07
Duplicate of #12586

**Closed by snicoll** 2018-07-19 09:07 UTC
Labels: theme: testing, type: enhancement

**Comment by n0mer** [comment] 2018-09-02 22:13
@philwebb another workaround might be `@TestPropertySource` from spring 4.1:

```java
@TestPropertySource(properties = "spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration")

```
