### ISSUE TITLE
Anomalies when upgrading from 2.1.6 to 2.1.7 

### ISSUE THREAD

**Issue by igler** [spring-projects/spring-boot#18520] opened 2019-10-06 16:12 UTC
After upgrading from spring-boot 2.1.6 to 2.1.7 one of my test fails. After investigating things through debugger I have seen that calling a setter-method affects two objects but I call it only on one of them. These two objects have same <code>System.idendityHashCode</code> variable in 2.1.7 but not in 2.1.6. I wonder if this causes the behavior? How can calling a setter on one object affects another object? BTW, these two objects are entities loaded from database. I compare them to generate changeDetails on properties.

**Comment by wilkinsona** [comment] 2019-10-06 17:31
As far as I know, two objects in the same JVM cannot have the same identity hashcode. I suspect they are in fact the same object. Unfortunately, I can't tell much more from your description of the problem so, as things stand, it isn't possible to help you.

If you'd like us to spend some more time on this please take the time to provide a complete and minimal sample that reproduces the problem. You can do so by attaching a zip to this issue.

**Comment by igler** [comment] 2019-10-08 09:48
Thanx for your answer! Found this [post](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6321873) that two objects can have the same identity hashcode. I wonder why, when calling the setter-method, affects both objects although I only call it on one object. Preparing a sample reproducing my scenario...

**Comment by igler** [comment] 2019-10-08 14:16
Calling <code>session.clear();</code> before loading and manipulating (setter) the object solves the problem. It seems that neo4j-ogm has some caching mechanism that brings undesired results in my case.

**Comment by wilkinsona** [comment] 2019-10-08 16:20
I'm glad to hear you've solved, or at least worked around, you problem. For the record 2.1.6 and 2.1.7 use the same version of Neo4j OGM but they do use different versions of Spring Data Neo4J which I guess you may be using. @michael-simons from Neo4j may be interested in this.

I'm going to close this issue for now at least as it doesn't appear that there's a problem in Spring Boot itself. We can re-open this issue and investigate further if that turns out not to be the case.

**Closed by wilkinsona** 2019-10-08 16:20 UTC
Labels: status: feedback-provided, status: waiting-for-triage
