### ISSUE TITLE
Configuration file cannot reference custom variable

### ISSUE THREAD

**Issue by 501956430** [spring-projects/spring-boot#20610] opened 2020-03-23 08:43 UTC
springboot version 2.2.5

> spring.path=/web
> url.a=http://www.baidu.com${spring.path}/index.html

**No replacement after compilation**

> spring.path=/web
> url.a=http://www.baidu.com${spring.path}/index.html

**Comment by snicoll** [comment] 2020-03-23 09:29
@501956430 it's hard to figure out what you're trying to report. You've mentioned compilation so maybe you're expecting Maven to filter that variable for you? If that's what you want, the default config [uses `@` as delimiter](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-maven). 

If you believe you've found an issue in Spring Boot, please take the time to create a small sample, either as a zip attached to this issue or pushed on a separate github repo.

**Comment by 501956430** [comment] 2020-03-23 09:50
@snicoll 
I hope so  Replace placeholder with

> url.a=http://www.baidu.com${spring.path}/index.html
> url.a=http://www.baidu.com/web/index.html

**Comment by snicoll** [comment] 2020-03-23 10:09
@501956430 sorry but that doesn't help me figuring out what problem you're facing. As requested, please share a small sample we can run ourselves.

**Comment by 501956430** [comment] 2020-03-23 10:33
@snicoll 
References to properties file variables

appliction. properties Defined properties

[spring.path=
url.a=
](url)

**Comment by snicoll** [comment] 2020-03-23 10:36
@501956430 I understood that part but it is not clear to me why it isn't working for you. As requested, please share a small sample that shows the problem. Go on start.spring.io, create a new project and reproduces the problem that you're describing. Once you're done, push that to a repo and share the URL or zip it up and attach the zip here.

**Comment by spring-issuemaster** [comment] 2020-03-30 11:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-04-06 11:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-04-06 11:05 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
