### ISSUE TITLE
spring-boot-starter-actuator needs a newer version of micrometer-core

### ISSUE THREAD

**Issue by SingingBush** [spring-projects/spring-boot#28929] opened 2021-12-08 14:02 UTC
Due to changes in micrometer-core, spring-boot-starter-actuator was updated in issue #27688 to handle the fact that micrometer have changed the package that _DiskSpaceMetrics_ is in (it's now in _io.micrometer.core.instrument.binder.system.DiskSpaceMetrics_). 

The problem is that micrometer-core did that change in the 1.8.* versions but spring-boot-starter-actuator (2.6.1) is pulling in the older 1.7.3 version of micrometer-core which has that class in the old package.

This results in a _java.lang.NoClassDefFoundError_ when initialising the SimpleMetricsExportAutoConfiguration bean.

I was able to work around this problem locally by adding an explicit dependency to micrometer-core 1.8.1 in my pom:

```
    <dependency>
        <groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-core</artifactId>
        <version>1.8.1</version>
    </dependency>
```

**Comment by wilkinsona** [comment] 2021-12-08 14:07
Spring Boot 2.6 should use Micrometer 1.8 by default. Can you please provide a minimal example that shows 1.7.3 being used?

**Comment by antti-markus-cko** [comment] 2021-12-09 08:22
Spring Boot 2.6.1 uses Micrometer 1.8.0 by default - https://github.com/antti-markus-cko/issuedemo

`./gradlew dependencyinsight --dependency micrometer`
gives
```
> Task :dependencyInsight
io.micrometer:micrometer-core:1.8.0 (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.environment     = standard-jvm
         org.gradle.jvm.version         = 17
   ]

io.micrometer:micrometer-core:1.8.0
\--- org.springframework.boot:spring-boot-starter-actuator:2.6.1
     \--- compileClasspath (requested org.springframework.boot:spring-boot-starter-actuator)
```

**Comment by SingingBush** [comment] 2021-12-13 09:19
that's weird, when I do `mvn dependency:tree` the only dependency pulling in micrometer-core is spring-boot-starter-actuator and the version is 1.7.3:

```
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.6.1:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.6.1:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-actuator:jar:2.6.1:compile
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.5:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.7.3:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
```

**Comment by snicoll** [comment] 2021-12-13 09:35
@SingingBush That doesn't mean anything if the version was forced by some dependency management in your project. As andy requested, please share a small sample we can run ourselves that reproduces this.

**Comment by spring-projects-issues** [comment] 2021-12-20 09:36
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Killianoc** [comment] 2021-12-21 10:59
I had this same issue and as @snicoll said it was due to a version being forced by dependency management. In my case it was "azure-spring-boot-bom:3.11.0" forcing version 1.7.3 of micrometer-core.

As OP said, either directly importing micrometer-core will fix this, or else you can exclude it from the direct dependencies  (unfortunately I couldn't exclude it at maven dependency management level as Maven doesn't like that, at least at my version of it)

**Comment by snicoll** [comment] 2021-12-21 11:10
@Killianoc than you for bringing this to my attention. I've reported [the issue to Azure](https://github.com/Azure/azure-sdk-for-java/issues/26136).

**Comment by snicoll** [comment] 2022-01-03 13:56
It's been a while and with a lack of a repro that showcases the problem, I am going to close this now.

**Closed by snicoll** 2022-01-03 13:56 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder

**Comment by scottfrederick** [comment] 2022-06-08 19:44
@sandy11apr It's likely that dependency management in your project is overriding the version of `micrometer-core` that is managed by Spring Boot. We can't tell what that is just from the dependency graph, we'd need to see a sample project to provide more information.
