### ISSUE TITLE
Now, I can send metrics to prometheus and elastic search，how can I send it to cloudwatch

### ISSUE THREAD

**Issue by TsingLiang** [spring-projects/spring-boot#15631] opened 2019-01-07 08:33 UTC
Now, I can send metrics to prometheus and elastic search，how can I send it to cloudwatch。Is there any docs? I find that the source code doesn't include cloudwatch export

**Comment by snicoll** [comment] 2019-01-07 08:40
Duplicate of https://github.com/micrometer-metrics/micrometer-docs/issues/49

**Closed by snicoll** 2019-01-07 08:40 UTC
Labels: status: waiting-for-triage

**Comment by TsingLiang** [comment] 2019-01-07 08:53
I didn't see cloudwatch，is there any docs or examples?
![image](https://user-images.githubusercontent.com/13382535/50758272-a4c3bc00-129c-11e9-8b6e-bbc79ab3ccdf.png)

**Comment by snicoll** [comment] 2019-01-07 08:57
@TsingLiang please take the time to click on the link I've referenced.

**Comment by TsingLiang** [comment] 2019-01-07 09:05
I'm sorry. I didn't see it :( . And this guy didn't see it too
![image](https://user-images.githubusercontent.com/13382535/50758855-58797b80-129e-11e9-8e3b-55a63dc83358.png)

**Comment by TsingLiang** [comment] 2019-01-07 09:10
There is only aws sdk，but it not support actuator(micrometer).
