### ISSUE TITLE
spring boot 2.0.0.M7 and micrometer is 1.0.0-rc.5 caused OOM

### ISSUE THREAD

**Issue by zhangxsh** [spring-projects/spring-boot#12355] opened 2018-03-06 03:02 UTC
Question
 I use zuul as gateway,the online  have four machines,after ten days run,three of them oom.
the dump is:

```
11998072 instances of class java.util.concurrent.LinkedBlockingQueue$Node 
11985797 instances of class  org.LatencyUtils.PauseDetector$ChangeListenersRequest 
238618 instances of class org.LatencyUtils.LatencyStats$PauseTracker 
238612 instances of class org.LatencyUtils.TimeCappedMovingAverageIntervalEstimator$PauseTracker `
```

btw,I also import the spring-boot-actuator unintentionally,and i have not use it.
thanks

**Comment by zhangxsh** [comment] 2018-03-06 03:05
![image](https://user-images.githubusercontent.com/37093837/37012178-4c10b73a-212e-11e8-8cd2-a9d732822a2a.png)
![Uploading image.png…]()

**Comment by philwebb** [comment] 2018-03-06 04:38
Probably a duplicate of #11338. Please upgrade.

**Closed by philwebb** 2018-03-06 04:38 UTC
Labels: status: waiting-for-triage
