### ISSUE TITLE
Crosslinks should not include .html

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-boot#33259] opened 2022-11-18 13:54 UTC
Forward port of issue #33206 to 2.7.x.

**Comment by izeye** [comment] 2022-11-25 00:51
This seems to be a duplicate of https://github.com/spring-projects/spring-boot/issues/33206 as the milestone for https://github.com/spring-projects/spring-boot/issues/33206 has been changed to "2.7.x" that is the same one for this issue.

**Closed** 2022-11-25 08:15 UTC
Labels: status: duplicate
