### ISSUE TITLE
@PathVariable ignores decimals of last double parameter

### ISSUE THREAD

**Issue by celiovasconcelos** [spring-projects/spring-boot#3001] opened 2015-05-18 21:01 UTC
Version: 1.2.3.RELEASE

```
http://localhost:8010/service/-16.529180515612968/-50.389328002929744
```

``` java
@RequestMapping(value="/service/{lat}/{lng}", method = { RequestMethod.GET })
public void test(@PathVariable("lat") Double lat, @PathVariable("lng") Double lng){
	System.out.println(lat); //it prints -16.529180515612968
	System.out.println(lng); //it prints -50.0
}
```

**Comment by gabrielfao** [comment] 2015-05-18 21:03
Same problem

**Comment by wilkinsona** [comment] 2015-05-18 21:30
What version of Boot are you using? A sample that reproduces the problem would also help.

**Comment by celiovasconcelos** [comment] 2015-05-23 23:22
Thank you @wilkinsona
Version: 1.2.3.RELEASE

**Comment by wilkinsona** [comment] 2015-10-12 12:50
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.

**Closed by wilkinsona** 2015-10-12 12:50 UTC
Labels: waiting-for-feedback
