### ISSUE TITLE
Spring Boot 2.2.4 + Spring Batch + Data JPA

### ISSUE THREAD

**Issue by meherbabu-cap** [spring-projects/spring-boot#20324] opened 2020-02-26 19:10 UTC
We upgraded our SpringBoot Application to Spring Boot 2.2.4, Spring 5.2.3 and Spring Batch 2.2.4 releases respectively. Earlier it was Spring Boot 1.5.9 and Spring 4.3.x versions. After upgrading to latest versions, Batch framework not working properly. JPA Repository classes are not getting injected into the ItemWriter class. Does anyone faced similar issue.

**Comment by wilkinsona** [comment] 2020-02-26 19:32
We’re not aware of anyone having problems with Spring Batch, however it’s hard to know exactly what issue you are facing without some more information.

If you would like us to spend some time investigating, please take the time to provide a complete and minimal sample that reproduces the problem. You can share it with us in a separate repository on GitHub or by attaching a zip to this issue.

**Comment by spring-issuemaster** [comment] 2020-03-04 19:33
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-03-11 19:33
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-03-11 19:33 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
