### ISSUE TITLE
After upgraded to Spring Boot 2.0.0.RELEASE, HikariDataSource loaded before ConversionService initialization

### ISSUE THREAD

**Issue by lraymond1206** [spring-projects/spring-boot#12372] opened 2018-03-06 23:20 UTC
I was hiding my credential using credstash. 
Everytime application context starts, I will use a use conversionService to call a credstash service to get actual password. 
There is no issue in 2.0.0.M7. 
After I upgrade to 2.0.0.RELEASE, Hikari will try to connect the database with the encoded credential without triggering the conversionService. Application will still be able to run, but anything related with database will not work. 

Is there a way to solve this?

**Comment by snicoll** [comment] 2018-03-07 07:39
Hard to tell without a sample I am afraid. Can you please share a sample that reproduces the issue? In particular we don't need to credstash part, the part where the `ConversionService` is not invoked is probably enough.

**Comment by spring-issuemaster** [comment] 2018-03-14 07:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-03-21 07:44
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-03-21 07:44 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
