### ISSUE TITLE
spring-data-redis set > 0 always execute "SELECT" before any command

### ISSUE THREAD

**Issue by abccbaandy** [spring-projects/spring-boot#10540] opened 2017-10-06 16:08 UTC
spring boot version : 1.5.7.RELEASE

properties :
`spring.redis.database=3`

code :
```java
HashOperations<String, String, String> hashOperations = redisTemplate.opsForHash();
Map<String, String> map = hashOperations.entries("2330");
```

redis monitor :
```
"SELECT" "3"
"HGETALL" "1234"
"SELECT" "0"
```

it should be only this, isn't it?
````
"HGETALL" "1234"
````

**Comment by mp911de** [comment] 2017-10-10 07:12
Duplicate of https://jira.spring.io/browse/DATAREDIS-714.

**Comment by wilkinsona** [comment] 2017-10-11 10:54
Thanks, @mp911de.

**Closed by wilkinsona** 2017-10-11 10:54 UTC
Labels: status: waiting-for-triage
