### ISSUE TITLE
Property overriding issue with 2.x

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-boot#19694] opened 2020-01-13 18:21 UTC
I have a project based on Spring cloud. It works fine with Greenwich and Spring boot 2.1.
I use the configserver which serves an application.yaml with project wide defaults and profile based application yamls for environment specific overrides for hostnames etc.

So for example with Greenwich.sr2 and Spring boot 2.1.x I get the right hostnames based on the profiles.

When I upgrade to spring boot 2.2.2 and Hoxton.sr1 the application.yaml values are no longer overridden by the profiles. When I remove everything that is overridden and just have it "added" by the profiles it works, but that can't be intended.
During the process I did not change the order of profiles, but I also updated to jdk13.

I tried to check with older spring boot versions, so the error also occurs with 2.2.1.RELEASE, I couldn't use 2.2.0.RELEASE because it didn't compile with jdk13.

**Comment by wilkinsona** [comment] 2020-01-13 18:32
Thanks for the report. Can you please provide a small sample that reproduces the problem?

**Comment by spencergibb** [comment] 2020-01-13 18:34
Possibly https://github.com/spring-cloud/spring-cloud-commons/issues/668?

**Comment by wilkinsona** [comment] 2020-01-13 18:41
Thanks, @spencergibb. That sounds like a pretty good fit. I've subscribed to that issue.

@pcornelissen Can you please let us know if your configuration matches that described in spring-cloud/spring-cloud-commons#668. If it does then I think we can close this issue as a duplicate of the Spring Cloud issue. If it does not, we'll need the sample that I asked for to figure out what's going on.

**Comment by pcornelissen** [comment] 2020-01-13 20:12
I have 

spring.cloud.config.overrideSystemProperties: false

in the application.yaml which is served by the configserver, but not the other two mentioned settings.
I'll try to fabricate a small sample

**Comment by pcornelissen** [comment] 2020-01-13 21:46
https://github.com/pcornelissen/spring-cloud-bug-668 it seems to be related to the hoxton.sr1 release

**Comment by wilkinsona** [comment] 2020-01-13 21:52
Thanks for narrowing this down, @pcornelissen. As it works with Hoxton RELEASE but fails with SR1, I think it's safe to assume for now at least that this is a Spring Cloud bug. If it turns out that a chance in Boot is needed after all, we can re-open this issue and investigate further.

**Closed by wilkinsona** 2020-01-13 21:52 UTC
Labels: status: feedback-provided, status: waiting-for-triage
