### ISSUE TITLE
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils

### ISSUE THREAD

**Issue by Eliaxs1900** [spring-projects/spring-boot#13441] opened 2018-06-11 21:10 UTC
### Selected grandle project with Java
`WARNING: An illegal reflective access operation has occurred`

`WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/C:/Users/eliay/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.0.6.RELEASE/984a52455b1be596b7f1a29f62d21d2f483eb764/spring-core-5.0.6.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)`

`WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
`

`WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
`

`WARNING: All illegal access operations will be denied in a future release
`

**Comment by spencergibb** [comment] 2018-06-11 21:35
This should be reported at jira.spring.io not here, since it's a framework issue

**Comment by jhoeller** [comment] 2018-06-11 21:38
Already dealt with for Spring Framework 5.1: https://jira.spring.io/browse/SPR-15859

**Comment by bclozel** [comment] 2018-06-11 22:01
Closing as a duplicate of SPR-15859.

**Closed by bclozel** 2018-06-11 22:01 UTC
Labels: status: waiting-for-triage

**Comment by rajeshkp** [comment] 2018-08-29 09:02
I am getting a similar warning in JDK 10 as well
