### ISSUE TITLE
Include AbstractJdbcConfiguration beans in @DataJdbcTest

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#28918] opened 2021-12-07 11:26 UTC
When using Spring Data JDBC, it's fairly common to provide a bean that's an `AbstractJdbcConfiguration` sub-class. For example, such a sub-class is used to register custom converters used during reading and writing of entities. At the moment, such beans are filtered out by `@DataJdbcTest`.

They can be included using a custom filter:

```java
@DataJdbcTest(includeFilters = @ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE,
        classes = AbstractJdbcConfiguration.class))
```

It would be good if this include filter wasn't necessary and `AbstractJdbcConfiguration` beans were included automatically.

**Comment by raqueru** [comment] 2021-12-07 13:04
Hello! I'm new to this project and I'd like to understand better where can i find the solution for this issue

**Comment by wilkinsona** [comment] 2021-12-08 14:45
I'd start by creating a new test class named `DataJdbcTypeExcludeFilterTests`, and writing a test that asserts that 
 [`DataJdbcTypeExcludeFilter`](https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-test-autoconfigure/src/main/java/org/springframework/boot/test/autoconfigure/data/jdbc/DataJdbcTypeExcludeFilter.java) does not exclude an `AbstractJdbcConfiguration` sub-class. It should fail to begin with.

With the test in place, `DataJdbcTypeExcludeFilter` can then be changed to include `AbstractJdbcConfiguration`. To do so, its `getDefaultIncludes()` method should be overridden to return a `Set` that contains `AbstractJdbcConfiguration.class`. With this change in place, the new test that was failing should now pass.

**Comment by raviu** [comment] 2021-12-13 14:08
@wilkinsona I've raised a PR for this enhancement per your instructions. Hoping to get my feet wet with the project and this seemed a good place to start! @raqueru apologies in case you're still working on this one.

**Comment by snicoll** [comment] 2021-12-14 08:13
@raqueru were you working on this issue or are you still willing to contribute something? 

@raviu thanks for the PR but I'd have preferred to check first before submitting. I agree it is a bit blurry whether @raqueru is working on it or not but we prefer to give contributors a chance to sort things out before someone else submits something.

Let's see what @raqueru says and we'll proceed accordingly.

**Comment by raqueru** [comment] 2021-12-14 15:36
> No problem! I was trying to solve it but if Raviu already did it, you can proceed

**Comment by mbhave** [comment] 2021-12-14 19:23
Closing in favor of PR #29003.

**Closed by mbhave** 2021-12-14 19:23 UTC
Labels: type: enhancement

**Comment by CichonPawel** [comment] 2022-08-23 08:54
until now, `@DataJdbcTest` did not need a dependency to `spring-boot-starter-data-jdbc`.
 think this is a non-intuitive change. I have lost 30 minutes of my life understanding:
`Caused by: java.lang.NoClassDefFoundError: org/springframework/data/jdbc/repository/config/AbstractJdbcConfiguration`.
