### ISSUE TITLE
RepositoryRestResource resources started returning 404 errors after running for a while

### ISSUE THREAD

**Issue by myvz** [spring-projects/spring-boot#21537] opened 2020-05-22 08:28 UTC
RepositoryRestResource resources started returning 404 errors after running for a while with version 2.2.6.RELEASE. Returning to 2.2.5.RELEASE solved problem. 

I have reproduced exactly the same issue using spring-boot 2.2.6 : JpaRepository classes annotated with @RepositoryRestResource started randomly to return 404 errors after a while.

Here is stackoverflow link
https://stackoverflow.com/questions/61262802/repositoryrestresource-resources-started-returning-404-errors-after-running-for

**Comment by bclozel** [comment] 2020-05-22 09:10
Could you upgrade to Spring Boot 2.2.7 (really, in order to upgrade to Moore SR7) since this looks like a duplicate of [DATAREST-1518](https://jira.spring.io/browse/DATAREST-1518) and [DATAREST-1502](https://jira.spring.io/browse/DATAREST-1502).

I'm closing this issue as a duplicate for now, please reopen this issue with a sample project and more information (like stacktraces) in case the upgrade does not solve the problem you're seeing.

Thanks!

**Closed by bclozel** 2020-05-22 09:10 UTC
Labels: status: waiting-for-triage
