### ISSUE TITLE
RequestDataValueProcessor not called in RedirectViewController

### ISSUE THREAD

**Issue by gillarramendi** [spring-projects/spring-boot#3076] opened 2015-06-01 11:41 UTC
If I define the following redirect view:

	protected static class WebConfig extends WebMvcConfigurerAdapter{
		public void addViewControllers(ViewControllerRegistry registry) {
			registry.addRedirectViewController("/redirect", "/link");
		}
	}
And a custom `RequestDataValueProcessor ` implementation:

	@Bean
	public CustomRequestDataValueProcessor requestDataValueProcessor(){
		return new CustomRequestDataValueProcessor();
	} 

`CustomRequestDataValueProcessor.processUrl(HttpServletRequest, String)` is not called in redirect.

Here is an example application that shows this behavior: https://github.com/gillarramendi/sample-spring-boot

**Comment by SnakeSVx** [comment] 2015-12-04 08:18
We are having the same issue at the moment.

From what my knowledge is about this subject.

The spring framework only expects 1 instance of the RequestDataValueProcessor to exist, but 2 are instantiated. Our custom one and one that is being made by Spring-Security.

In an application without spring-boot it is possible to make the custom one take precedence by defining it in the SecurityConfiguration file, in spring-boot this does not seem possible because of the configuration that happens in the background.

So far we had no luck in getting our own instance to work in spring-boot.

**Comment by SnakeSVx** [comment] 2015-12-04 08:34
A quickfix a co-worker found is messing around with the @Order annotation. But we haven't tested this for all of our applications yet.

**Comment by wilkinsona** [comment] 2015-12-04 09:13
@gillarramendi Sorry, it looks like we missed this when you first raised it. Thank you for the sample project. I've been able to reproduce the problem and am looking into it now.

@SnakeSVx The issue you're facing is different. @gillarramendi is not using Spring Security. Please raise a separate issue if you believe that the behaviour you're experiencing is a bug. A sample project that reproduces the problem would be much appreciated.

**Comment by wilkinsona** [comment] 2015-12-04 09:19
The custom request data value processor isn't called as the `RedirectView` doesn't have access to the application context.

It first tries to access it by calling `getWebApplicationContext()`. This returns `null` as the `RedirectView`, created via `ViewControllerRegistry.addRedirectViewController`, has not had `setApplicationContext` called on it. This makes sense as it isn't exposed as a bean. @rstoyanchev I'm not familiar with this area of Spring MVC. Is this the expected behaviour?

Next, it tries calling `ContextLoader.getCurrentWebApplicationContext()`. This also returns `null`. Boot doesn't use `ContextLoaderListener` so the `ContextLoader`'s web application context is never set.

**Comment by rstoyanchev** [comment] 2015-12-04 14:46
That's right, it seems like exposing the WebApplicatinoContext somehow (perhaps an interceptor or filter that's ApplicationContextAware) as a request attribute should do the trick.

**Comment by wilkinsona** [comment] 2015-12-04 15:12
Thanks, @rstoyanchev. The use of a request attribute seems to be Spring Framework 4.2-specific as it was added in [this commit](https://github.com/spring-projects/spring-framework/commit/4314da922adefdc64bcfc2243ae6b049f5925080). What's the best course of action for Boot 1.2 which uses Framework 4.1.x?

**Comment by rstoyanchev** [comment] 2015-12-04 16:33
Good point, there doesn't seem to be any option for 4.1.x. We probably should setApplicationContext on the ParameterizableViewController (and the contained RedirectView) instances created in ViewControllerRegistry. We do that in other places in WebMvcConfigurationSupport. This would solve the issue for both 4.2.x and 4.1.x.

**Comment by rstoyanchev** [comment] 2015-12-04 16:36
https://jira.spring.io/browse/SPR-13762

**Comment by rstoyanchev** [comment] 2015-12-04 18:30
The upcoming 4.1.9 snapshot build has a fix. I verified the fix with Spring Boot 1.2.7 and the Spring Framework snapshot but would be good to have it confirmed by the reporters.  

I couldn't reproduce the issue in 4.2.x at all due to the above mentioned commit in 4.1.x.

**Comment by wilkinsona** [comment] 2015-12-07 12:42
Thanks again, @rstoyanchev. I've confirmed the fix using the sample project provided by @gillarramendi.

I'm going to close this issue in favour of #4440 which is tracking the upgrade to Spring Framework 4.1.9.

**Closed by wilkinsona** 2015-12-07 12:42 UTC

**Comment by gillarramendi** [comment] 2015-12-09 09:29
Thanks @wilkinsona and @rstoyanchev!
Tested in spring-boot 1.3.1.BUILD-SNAPSHOT and 1.2.7.RELEASE (spring-framework 4.1.9.BUILD-SNAPSHOT) and it is working fine!
