### ISSUE TITLE
server.servlet.contextPath with websocket

### ISSUE THREAD

**Issue by xzzh999** [spring-projects/spring-boot#15973] opened 2019-02-18 06:52 UTC
Hi~ Nice work!
[SockJS relative #470](https://github.com/sockjs/sockjs-client/issues/470)
use spring boot 2.0.2 websocket with contextPath not working good, need u help, thx.

**Comment by wilkinsona** [comment] 2019-02-18 07:55
Thanks for the report. Unfortunately, “not working good” does not give us enough information to diagnose the problem. The SockJS client issue that you opened didn’t make things much clearer. If you would like us to spend some time trying to help you please spend some time to make it easier for us to do so. You can make it easier by describing the problem in detail and by providing a minimal sample (as a zip attached to this isssue or in a separate Git repository) that reproduces the problem.

**Comment by xzzh999** [comment] 2019-02-19 00:45
@wilkinsona 
Thank you for your reply, there is the test [demo](https://github.com/lenve/vhr)(client and server projects), but i don't think it's the project code's problem because the websocket part's code is very simple. I just add **server.servlet.contextPath=/MyServer**, before i add this, the websocket is fast enough to make connection,  but after add this, the connection made is so slow or even failed, and i have already add the CORS code to avoid 404 errors.

**Comment by wilkinsona** [comment] 2019-02-19 07:12
Thanks for the extra information. Can you please explain why you believe the problem is caused by Spring Boot? From your description, where you say the connection sometimes works slowly and sometimes fails, it sounds like a network problem. How does it behave without any proxy configuration?

**Comment by xzzh999** [comment] 2019-02-20 01:48
@wilkinsona 
That is the reason! When i not use proxy table, just build the front end package, and run spring boot server independent, it works ok! When i use proxy to debug, the problem comes!(too slow) Here is the print:

![](https://github.com/xzzh999/markdown-pictures/blob/master/websocket-slow.png?raw=true)

**Comment by wilkinsona** [comment] 2019-02-20 09:09
Thanks for trying things without the proxy. Given that things work well without it, I think it's reasonable to assume that the proxy is causing the problem. That's something that is out of Spring Boot's control so I am going to close this issue. The incompatible SockJS errors look suspicious to me. My understanding is that `proxyTable` is backed by webpack-dev-server. Searching its issue tracker shows others have had similar problems with SockJS. https://github.com/webpack/webpack-dev-server/issues/474 is one example.

**Closed by wilkinsona** 2019-02-20 09:09 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by xzzh999** [comment] 2019-02-21 01:27
@wilkinsona 
Thank you very much!
