### ISSUE TITLE
Bootstrap mode for JPA Repository is not "deferred" in contradiction to the release notes

### ISSUE THREAD

**Issue by khmarbaise** [spring-projects/spring-boot#22606] opened 2020-07-28 05:50 UTC
Based on the [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#bootstrapmode-for-jpa-repositories) it is mentioned that the default mode for JPA repositories is is set to "deferred" 

but in contradiction to the documented behaviour I see in the start log of our spring boot application: (Running on Spring Boot Version 2.3.2.RELEASE
```
INFO  o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
```

I have not yet set the `spring.data.jpa.repositories.bootstrap-mode=default`.

This means from my point of view that the behaviour has not been changed?

**Comment by wilkinsona** [comment] 2020-07-28 07:26
Thanks for the report, but I can't reproduce the behaviour that you have described. The bootstrap mode is `DEFFERED` when I start a minimal application generated by start.spring.io:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.2.RELEASE)

2020-07-28 08:25:22.745  INFO 49682 --- [           main] c.e.demo.JpaBootstrapModeApplication     : Starting JpaBootstrapModeApplication on fulcrum.local with PID 49682 (/Users/awilkinson/dev/workspaces/spring-projects/spring-boot/master/jpa-bootstrap-mode/target/classes started by awilkinson in /Users/awilkinson/dev/workspaces/spring-projects/spring-boot/master/jpa-bootstrap-mode)
2020-07-28 08:25:22.747  INFO 49682 --- [           main] c.e.demo.JpaBootstrapModeApplication     : No active profile set, falling back to default profiles: default
2020-07-28 08:25:23.077  INFO 49682 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.
```

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-issuemaster** [comment] 2020-08-04 07:29
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-08-11 07:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-08-11 07:31 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
