### ISSUE TITLE
Error to read external properties

### ISSUE THREAD

**Issue by ofbizbrazil** [spring-projects/spring-boot#3094] opened 2015-06-02 16:08 UTC
Spring Boot can not read an external property file rightly, cause the order of properties is affecting the result. For example:

application.properties
--------------------------
spring.main.show-banner=false
server.port=9043
server.session-timeout=1800
server.ssl.key-store=file:///C:/Temp/config/localhost.jks
server.ssl.key-store-password=localhost
server.ssl.key-password=localhost

class
------
@Component
public class ShowBanner {

    @Value("${spring.main.show-banner:}")
    private String showBanner;

    @PostConstruct
    public void init() {
        System.out.println(showBanner);
    }
}

In this code if you set in external property file the property "spring.main.show-banner=false" the banner still shows in console if it is set before server section. When the banner should not appear. Because the property returns empty.

If I move the property after server section the banner disappears, because return false value as expected. Why is it happening?

java -jar sample-1.2.3.RELEASE.jar -Dspring.config.location=file:///C:\Temp\config\application.properties

**Comment by snicoll** [comment] 2015-06-02 16:27
Unrelated but your code will not work since you use lower case in your config and dash in your code (Hint: `@Value` does **not** use the relaxed binding). This looks very weird, I'll have a look.

**Comment by ofbizbrazil** [comment] 2015-06-02 17:17
Hi, I changed the code but the error still happens... By the way, Spring Boot uses relaxed binding = so there doesn’t need to be an exact match between the Environment property name and the bean property name. 

Any idea more?

**Comment by marcosbarbero** [comment] 2015-06-02 19:14
@ofbizbrazil Have you the same property configured at your application.properties in classpath?
Because the load precedence if you have it spring.main.show-banner=true in your classpath file it will always show up, unless you turn it of configuring at a /config subdir of the current directory.
The /config subdir has the higher precedence.
You can find more info here http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files

**Comment by ofbizbrazil** [comment] 2015-06-02 19:18
Hi @marcosbarbero 
No, my application.properties in classpath is empty, just the external properties is filled in at the moment.

**Comment by snicoll** [comment] 2015-06-02 19:19
@ofbizbrazil I will have to ask you to provide a sample that reproduce this issue because I can't find any reason why the ordering in the same file would matter. I also tried on a project locally (with your code) and it works as expected.

**Comment by ofbizbrazil** [comment] 2015-06-02 19:40
@snicoll, please find my sample code:

package com.sbb.teste;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SampleApplication {

    public static void main(String[] args) throws Exception {
        SpringApplication.run(SampleApplication.class, args);
    }
}

package com.sbb.teste.service;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Component
public class ShowBanner {

    @Value("${spring.main.show-banner:}")
    private String showBanner;

    @PostConstruct
    public void init() {
        System.out.println(showBanner);
    }
}


1) The application.properties of current application is empty.

2) The external application.properties in C:\Temp\config has:
spring.main.show-banner=false
server.port=9043
server.session-timeout=1800

3) Java command to execute (By the way, I copied the jar generated by Spring Boot to same config folder)
java -jar sample-1.2.3.RELEASE.jar -Dspring.config.location=file:///C:\Temp\config\application.properties

In this example, nothing is printed because the property is at the top of file, so if I move the property after "server.session-timeout=1800" and it prints "false" and banner do not appears.


Output error example :
C:\Temp\config>java -jar sample-1.2.3.RELEASE.jar -Dspring.config.location=file:///C:\Temp\config\application.properties
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.3.RELEASE)

2015-06-02 16:37:29.844  INFO 7484 --- [           main] com.sbb.teste.SampleApplication          : Starting SampleApplication v1.2.3.RELEASE on SAOI
fig)
2015-06-02 16:37:29.874  INFO 7484 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation
text hierarchy

2015-06-02 16:37:30.214  INFO 7484 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-06-02 16:37:30.214  INFO 7484 --- [           main] com.sbb.teste.SampleApplication          : Started SampleApplication in 0.54 seconds (JVM ru
2015-06-02 16:37:30.214  INFO 7484 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.An
t hierarchy
2015-06-02 16:37:30.224  INFO 7484 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown


Output success example :
C:\Temp\config>java -jar sample-1.2.3.RELEASE.jar -Dspring.config.location=file:///C:\Temp\config\application.properties
2015-06-02 16:38:44.128  INFO 5368 --- [           main] com.sbb.teste.SampleApplication          : Starting SampleApplication v1.2.3.RELEASE on S
fig)
2015-06-02 16:38:44.158  INFO 5368 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotat
text hierarchy
false
2015-06-02 16:38:44.498  INFO 5368 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-06-02 16:38:44.498  INFO 5368 --- [           main] com.sbb.teste.SampleApplication          : Started SampleApplication in 0.53 seconds (JVM
2015-06-02 16:38:44.508  INFO 5368 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation
t hierarchy
2015-06-02 16:38:44.508  INFO 5368 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

**Comment by ofbizbrazil** [comment] 2015-06-02 21:07
Hi all, anybody has got any success?

**Comment by snicoll** [comment] 2015-06-03 07:30
@ofbizbrazil in the last two hours? No, sorry.

Your command is wrong. You can't pass a system property *after* the `-jar` instruction. I tried again and it worked (but I have no Windows machine at hand) so I'll ask you to test this one more time with either of the following:

```
java  -Dspring.config.location=file:///C:\Temp\config\application.properties -jar sample-1.2.3.RELEASE.jar
```

or (equivalent)

```
java  -jar sample-1.2.3.RELEASE.jar --spring.config.location=file:///C:\Temp\config\application.properties
```

When you run those commands, make sure that the server is starting on port  `9043` to prove that your configuration file is loaded _at all_ (because my guess is that it isn't)

**Comment by ofbizbrazil** [comment] 2015-06-03 13:27
@snicoll, same error... I guess it's an internal error of Spring Boot.

May Spring has any priority to find properties files?

With error
######################
C:\Temp\config>java -Dspring.config.location=file:///C:\Temp\config\application.properties -jar sample-1.2.3.RELEASE.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.3.RELEASE)

2015-06-03 10:25:13.098  INFO 7060 --- [           main] com.sbb.teste.SampleApplication          : Starting SampleApplication v1.2.3.RELEASE on SAOIT
fig)
2015-06-03 10:25:13.158  INFO 7060 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.
text hierarchy

2015-06-03 10:25:13.644  INFO 7060 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-06-03 10:25:13.650  INFO 7060 --- [           main] com.sbb.teste.SampleApplication          : Started SampleApplication in 0.831 seconds (JVM ru
2015-06-03 10:25:13.651  INFO 7060 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.Ann
t hierarchy
2015-06-03 10:25:13.651  INFO 7060 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown


No error
######################
C:\Temp\config>java -Dspring.config.location=file:///C:\Temp\config\application.properties -jar sample-1.2.3.RELEASE.jar
2015-06-03 10:25:21.316  INFO 6640 --- [           main] com.sbb.teste.SampleApplication          : Starting SampleApplication v1.2.3.RELEASE on SAOI
fig)
2015-06-03 10:25:21.347  INFO 6640 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation
ext hierarchy
false
2015-06-03 10:25:21.685  INFO 6640 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-06-03 10:25:21.692  INFO 6640 --- [           main] com.sbb.teste.SampleApplication          : Started SampleApplication in 0.555 seconds (JVM r
2015-06-03 10:25:21.693  INFO 6640 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.An
 hierarchy
2015-06-03 10:25:21.693  INFO 6640 --- [       Thread-2] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

**Comment by dsyer** [comment] 2015-06-03 13:51
@ofbizbrazil please read the docs on github flavoured markdown (https://help.github.com/articles/github-flavored-markdown/). It will help you to make your comments more readable.

**Comment by snicoll** [comment] 2015-06-03 14:01
I am closing this one because we did several extra tests on a Windows7 machine with your exact command and it worked. We've reached the boundaries of what we can do here.

Your command is all weird anyway. You are **already** in the directory where your `application.properties` is locate  so if you run your app from that directory your `application.properties` will be detected by default (i.e. `java -jar sample-1.2.3.jar` will have the exact same effect since Boot detects an `application.properties` in the working directory).

**Closed by snicoll** 2015-06-03 14:01 UTC

**Comment by ofbizbrazil** [comment] 2015-06-03 14:11
It's really weird, still not working.... Can we compare environments settings? Mines are: Java 1.8_45 32 bits, Windows 7 enterprise, Spring Boot 1.2.3

I also removed from inside jar the file "application.properties" manually and the banner still shows.
Did you really copy all my application properties In the following order I described in older posts? 

C:\Temp\config>java -jar sample-1.2.3.RELEASE.jar
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.2.3.RELEASE)

2015-06-03 11:06:39.816  INFO 1616 --- [           main] com.sbb.teste.SampleApplication          : Starting SampleApplication v1.2.3.RELEASE on SAOIT-H
fig)
2015-06-03 11:06:39.847  INFO 1616 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded
]; root of context hierarchy

**Comment by ofbizbrazil** [comment] 2015-06-03 14:22
@snicoll, to give further info I tried on Solaris using Java 1.7_51 and the same thing happened.

if you run as you described (java -jar sample-1.2.3.RELEASE.jar) and just keeping in the external application.properties external the property 
spring.main.show-banner = false the banner still shows up. 

Why does it happened? Is this property is not being read?

**Comment by tdemande** [comment] 2015-06-03 14:25
@ofbizbrazil, just tried to reproduce on _Win7 + Java 8u25 64bit_. Banner never shows up. I only can suspect a character issue at the beginning  of your file as moving the properties down works fine.

**Comment by ofbizbrazil** [comment] 2015-06-03 14:28
@tdemande, I also tried on Solaris and the same error happened... my application.properties is using UTF-8

**Comment by ofbizbrazil** [comment] 2015-06-03 14:36
Guys, I guess I found!! It seems something with the encoding...

If I set UFT-8 the banner does not work... as UTF-8 without BOM works...

So UFT-8 <> UTF-8 without BOM ?

**Comment by tdemande** [comment] 2015-06-03 14:44
UTF-8 with BOM shouldn't be used in Java (or at all for what I can read). That adds a byte in the file  that is likely to cause your issue.

**Comment by ofbizbrazil** [comment] 2015-06-03 14:44
So why UTF-8 does not work? Can you try it?
