### ISSUE TITLE
Possible bug during executable .war file creation with spring-boot-maven-plugin

### ISSUE THREAD

**Issue by ton3r** [spring-projects/spring-boot#10232] opened 2017-09-08 09:12 UTC
I've tested to set up JSF (Mojarra) with the currently Spring-Boot (1.5.6.RELEASE) and try to create an executable .war file with spring-boot-maven-plugin and the repackage goal.

The problem is that the application within this .war starts up but got problem to initialze. After some days of tests and tests and debug, I finally switch down the Spring-Boot Releases step by step and the last working Version for "executable .war Files" is 1.5.2.

Currently I can't find the final error/bug/reason for this behavior.

I have forked a JSF/SpringBoot Demonstration and set it up with Version 1.5.3.RELEASE

If you follow the instructions (simple `mvn clean install spring-boot:repackage`) and try to execute it with` java -jar` you will see the error. Change in pom to a lower version and it runs perfectly.

https://github.com/ton3r/Spring-Boot-JSF-Example

**Comment by wilkinsona** [comment] 2017-09-08 10:40
Thanks for the sample. I've successfully reproduced the problem now.

As far as I can tell, the problem isn't with Spring Boot itself but with the version of Tomcat that's used. Spring Boot 1.5.2 works and it uses Tomcat 8.5.11. Spring Boot 1.5.3 and later fail and they use more recent versions of Tomcat 8.5. Crucially, Spring Boot 1.5.6 works if I set `<tomcat.version>8.5.11</tomcat.version>` in the application's pom. Lastly, Spring Boot 1.5.6 fails with the latest version of Tomcat 8.5 (8.5.20) so the change in Tomcat's still there.

**Comment by wilkinsona** [comment] 2017-09-08 10:43
The sample also works fine with Spring Boot 1.5.6 and Jetty or Undertow. In short, the problem is specific to Tomcat 8.5 versions after 8.5.11.

**Comment by ton3r** [comment] 2017-09-08 11:13
Yes!! You are right. Have checked this also with my other local applications!! Works perfect with the right TC Version.

**Comment by wilkinsona** [comment] 2017-09-08 11:24
When the application fails, it's looking in H2's jar:

```
jar:war:file:/Users/awilkinson/dev/temp/Spring-Boot-JSF-Example/target/application-0.0.1-SNAPSHOT.war*/WEB-INF/lib/h2-1.4.196.jar!/META-INF/
```

Note the `*/` in the URL which was introduced in Tomcat post 8.5.11. Crucially, H2's jar doesn't have an entry for the `META-INF/` directory; it's only got entries for the files in that directory. This means that this URL should not have been returned from the ClassLoader.getResources() call. When an attempt is made to connect to the jar file, it fails as the `META-INF/` entry doesn't exist:

```
Caused by: java.io.FileNotFoundException: JAR entry META-INF/ not found in /var/folders/zq/v6xkr2696kv05jbf3bddt9680000gn/T/jar_cache4058734571815148022.tmp
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142) ~[na:1.8.0_141]
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89) ~[na:1.8.0_141]
	at com.sun.faces.facelets.util.Classpath.search(Classpath.java:145) ~[jsf-impl-2.2.7.jar!/:2.2.7]
	at com.sun.faces.facelets.util.Classpath.search(Classpath.java:109) ~[jsf-impl-2.2.7.jar!/:2.2.7]
	at com.sun.faces.config.configprovider.MetaInfFacesConfigResourceProvider.loadURLs(MetaInfFacesConfigResourceProvider.java:164) ~[jsf-impl-2.2.7.jar!/:2.2.7]
	at com.sun.faces.config.configprovider.MetaInfFacesConfigResourceProvider.getResources(MetaInfFacesConfigResourceProvider.java:108) ~[jsf-impl-2.2.7.jar!/:2.2.7]
	... 15 common frames omitted
```

It's looking in `/var/folders/zq/v6xkr2696kv05jbf3bddt9680000gn/T/jar_cache4058734571815148022.tmp` as the JDK has copied the jar to a temporary location.

Another way to avoid the problem is to use HSQLDB instead of H2 as its jar does have a `META-INF` entry.

**Comment by wilkinsona** [comment] 2017-09-08 11:51
It's a regression in Tomcat 8.5.14. I've opened https://bz.apache.org/bugzilla/show_bug.cgi?id=61503. There's nothing much that we can do in Spring Boot so I'm going to close this. We'll pick up a version of Tomcat that fixes the problem in due course.

**Closed by wilkinsona** 2017-09-08 11:51 UTC
Labels: status: waiting-for-triage
