### ISSUE TITLE
Version label is not printed on startup with Jigsaw

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#10233] opened 2017-09-08 10:57 UTC
David Syer 
The Spring Boot version info is not printed on startup. That's interesting.

```
java -p target/demo-0.0.1-SNAPSHOT.jar:$CP --add-modules ALL-DEFAULT -m demo/com.example.demo.DemoApplication

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                      
```

cf

```
$ java -cp target/demo-0.0.1-SNAPSHOT.jar:$CP com.example.demo.DemoApplication --endpoints.default.web.enabled=true

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v2.0.0.BUILD-SNAPSHOT)
```

**Comment by wilkinsona** [comment] 2017-09-08 11:12
I suspect this is the same underlying problem as #10049.

**Comment by wilkinsona** [comment] 2018-03-28 11:29
I think a fix similar to the one implemented [here](https://github.com/spring-projects/spring-boot/commit/975c005dfbe85fa37dcee6c3577feb965fc6fccf) would work. However, while that didn't seem unreasonable during a build, I'm not sure it's worth it at runtime.

**Comment by DontSeeSharp** [comment] 2019-03-06 17:28
@wilkinsona is this still relevant? I'd like to work on this.

**Comment by wilkinsona** [comment] 2019-03-06 17:50
@DontSeeSharp Great, thanks. As far as I know this is still relevant. A contribution that fixes it would be much appreciated.

**Comment by DontSeeSharp** [comment] 2019-03-06 17:54
Great, I'll start working.

**Comment by DontSeeSharp** [comment] 2019-03-08 12:21
@wilkinsona, I could not reproduce this on my local Windows machine with [OpenDJK 9.04](https://developers.redhat.com/products/openjdk/download/) from RedHat nor with [Java SE 9](https://jdk.java.net/java-se-ri/9) from Oracle. Tried on sample tomcat project with Spring Boot 2.2.0.

Tried to run in fashion similar to this:
`"C:\Program Files\Java\jdk-9.0.4\bin\java.exe" -jar target/spring-boot-sample-tomcat-2.2.0.BUILD-SNAPSHOT.jar --endpoints.default.web.enabled=true`

Is there anything I might be missing? Maybe this is OpenJDK 9~b114-0ubuntu1 specific?

**Comment by wilkinsona** [comment] 2019-03-08 12:25
@DontSeeSharp Thanks for taking a look. The problem only happens when the application is run using the module path. See the two examples in the opening description. It doesn't work in the first example which uses the module path, but works in the second second which uses the classpath (java -jar).

**Comment by DontSeeSharp** [comment] 2019-03-08 12:25
Oh, I see now, thanks for the feedback.

**Comment by DontSeeSharp** [comment] 2019-03-08 15:52
@wilkinsona As suggested, 975c005 fixes the problem, but it is within `spring-boot-gradle-plugin` module. Is it okay, if I just copy the code over to the `spring-boot` module? (It would create a small amount of duplicate code.)

**Comment by wilkinsona** [comment] 2019-03-08 16:00
Yes, I think that's fine. In this case it's better to have the duplicated code than to place it somewhere that can be shared and that would then need to be public API.

**Comment by philwebb** [comment] 2019-03-11 18:52
Closing in favor of PR #16182 (thanks @DontSeeSharp!)

**Closed by philwebb** 2019-03-11 18:52 UTC
Labels: type: bug
