### ISSUE TITLE
Allow build info goal's timestamp to be disabled so that its output is repeatable

### ISSUE THREAD

**Issue by oehme** [spring-projects/spring-boot#17294] opened 2019-06-21 16:58 UTC
The build-info goal injects a [timestamp](https://github.com/spring-projects/spring-boot/blob/e560b7f6ba91140390a544bb38cb407374e588c7/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/BuildInfoMojo.java#L74) into the build output and there is no way to suppress that as far as I can tell. In the spirit of reproducible builds, it would be great if this could be deactivated.

**Comment by wilkinsona** [comment] 2019-06-21 17:09
Thanks for the suggestion. This would align the Maven plugin's capabilities with our Gradle plugin. It was originally done in Gradle for up-to-date checking purposes but since https://github.com/spring-projects/spring-boot/commit/c80218064fde71b991dee717166da81709558770, it now makes things reproducible too.

**Comment by philwebb** [comment] 2019-07-02 00:56
Closing in favor of PR #17390

**Closed by philwebb** 2019-07-02 00:56 UTC
Labels: type: enhancement
