### ISSUE TITLE
Reactive tracing stopped working after migration from 3.1.5 to 3.1.6

### ISSUE THREAD

**Issue by norbson** [spring-projects/spring-boot#38656] opened 2023-12-05 09:52 UTC
After migration 3.1.5 -> 3.1.6 tracing for reactive apps stopped working (no traceId and spanId in mdc).

Link to simple app to reproduce a problem (plain app from initializr with one dummy rest endpoint and customised log pattern):
https://github.com/norbson/sb-tracing

![image](https://github.com/spring-projects/spring-boot/assets/2744731/084c1b24-726e-4ab0-9b57-669725361403)

![image](https://github.com/spring-projects/spring-boot/assets/2744731/2d6b2061-506c-4535-8a90-3db822d37409)

**Comment by bclozel** [comment] 2023-12-05 09:59
Thanks for the report, I think this is a duplicate of https://github.com/spring-projects/spring-framework/issues/31706.

**Closed by bclozel** 2023-12-05 09:59 UTC
Labels: status: waiting-for-triage
