### ISSUE TITLE
Unkown Maven Configuration Problem

### ISSUE THREAD

**Issue by zndo** [spring-projects/spring-boot#16923] opened 2019-05-21 09:23 UTC
When I using STS4 Created a  Spring Boot Project from parent POM(version 2.1.5.RELEASE)，The Markers show "Maven Configuration Problem",details of "Unknown".Then I changed the version 2.1.4.RELEASE, problems has been resolved.

**Comment by wilkinsona** [comment] 2019-05-21 09:26
Thanks for the report. This is a duplicate of #16882.

**Closed by wilkinsona** 2019-05-21 09:26 UTC
Labels: status: waiting-for-triage
