### ISSUE TITLE
Spring Boot Test 3 NoClassDefFoundError: jakarta/servlet/ServletConnection

### ISSUE THREAD

**Issue by nibexo** [spring-projects/spring-boot#33661] opened 2022-12-30 09:28 UTC
Spring Boot Web + Jetty (exclude Tomcat) + MockMvc 3.0.1 and jakarta-servlet.version 5.0.0

Error test on startup:
```
java.lang.NoClassDefFoundError: jakarta/servlet/ServletConnection
	at org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder.createServletRequest(MockHttpServletRequestBuilder.java:769)
	at org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder.buildRequest(MockHttpServletRequestBuilder.java:663)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:172)
        at org.example.ExampleControllerTest.test(ExampleControllerTest.java:29)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletConnection  
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 74 more
```

reproducer: https://github.com/nibexo/jetty-spring-boot-test-3-repro

**Comment by kdebski85** [comment] 2022-12-31 13:51
Spring Boot 3 requires Jakarta 6, not 5.
Please see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee

**Comment by philwebb** [comment] 2022-12-31 20:30
Unfortunately at the time of release there was no Jetty version available that supported Servlet 6.0. We have [an open issue](https://github.com/spring-projects/spring-boot/issues/33044) to document how to downgrade dependencies. There's a lot of discussion in that issue with a few suggestions.

**Comment by philwebb** [comment] 2022-12-31 20:31
I think we can consider this one a duplicate of #33044

**Closed by philwebb** 2022-12-31 20:31 UTC
Labels: status: waiting-for-triage

**Comment by nibexo** [comment] 2023-01-02 05:48
> Spring Boot 3 requires Jakarta 6, not 5. Please see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee
> 
> `ServletConnection` was added in Jakarta 6: https://jakarta.ee/specifications/platform/10/apidocs/jakarta/servlet/servletconnection `Since: Servlet 6.0`

@kdebski85 
Ok, but as this migration guide said: 

> Jetty does not yet support Servlet 6.0. To use Jetty with Spring Boot 3.0, you will have to downgrade the Servlet API to 5.0. You can use the jakarta-servlet.version property to do so.

I need to set Servlet API to 5.0 when I'm using Spring Boot 3 with Jetty, and it works, but then Spring tests throw exception.

**Comment by bclozel** [comment] 2023-01-02 09:33
@nibexo See https://github.com/spring-projects/spring-boot/issues/33044#issue-1438725435

**Comment by Tak1za** [comment] 2023-01-12 04:54
Found a temporary fix for the problem.
Move back to Jakarta 6.0.0 and add the following dependency:

```

<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-server</artifactId>
    <version>${jetty.version}</version>
</dependency>

```     
 With the latest version of jetty-server.

**Comment by tasosz** [comment] 2023-03-31 13:23
I've had the same issue, and the previously suggested options were not working for everything. Either the service would start or all the tests (inc mockmvc) would succeed. But not everything. :-(

In the end, this setup has worked for all:
```
    ext {
        set("jakarta-servlet.version", '5.0.0')
    }
```

plus:
```
    testImplementation 
            'org.eclipse.jetty:jetty-server:11.0.14',
            'jakarta.servlet:jakarta.servlet-api:6.0.0',
```

**Comment by nibexo** [comment] 2023-03-31 19:30
@tasosz 
Did you try set only
 'org.eclipse.jetty:jetty-server:11.0.14' in implementation section?

**Comment by du-it** [comment] 2023-09-07 11:17
#33044
