### ISSUE TITLE
The space in the configuration file will result in different running results(eclipse and jar)

### ISSUE THREAD

**Issue by shinelon** [spring-projects/spring-boot#7251] opened 2016-10-31 08:04 UTC
I find a case:
```
<version>1.4.1.RELEASE</version>
```
in the application.properties
``` 
logging.config=classpath:log4j2.xml 
```
There is a space behind the 'log4j2.xml',the configuration can work in the eclipse ,but run the configuration as a jar (**java -jar**) it do not work!
```
Logging system failed to initialize using configuration from 'classpath:log4j2.xml '
java.io.FileNotFoundException: class path resource [log4j2.xml ] cannot be resolved to URL because it does not exist
        at org.springframework.util.ResourceUtils.getURL(ResourceUtils.java:138)
```
delete the space behind the 'log4j2.xml',it works as a jar.

is ok?

**Comment by wilkinsona** [comment] 2016-10-31 08:46
I suspect you don't actually have a space at the end of the property in Eclipse (perhaps you have it configure to trim trailing whitespace on save?). With that option disabled and a trailing space, I get the same error launching in Eclipse or from a jar. In short, this issue is a duplicate of #4106.

**Closed by wilkinsona** 2016-10-31 08:46 UTC
Labels: waiting-for-triage
