### ISSUE TITLE
Spring boot Actuator dependency on Jackson prevents usage of GSON

### ISSUE THREAD

**Issue by snaum** [spring-projects/spring-boot#17388] opened 2019-07-01 18:18 UTC
The class
org.springframework.boot.actuate.context.properties.ConfigurationPropertiesReportEndpoint
contains hard dependencies on Jackson classes 
which causes java.lang.NoClassDefFoundError during server startup when Jackson dependencies are excluded from pom.xml in favor of GSON

**Comment by wilkinsona** [comment] 2019-07-01 18:25
Duplicate of #13766.

**Closed by wilkinsona** 2019-07-01 18:25 UTC
Labels: status: waiting-for-triage
