### ISSUE TITLE
Spring boot actuator does not work with integrationflow

### ISSUE THREAD

**Issue by babbarsurbhi9** [spring-projects/spring-boot#23486] opened 2020-09-25 07:54 UTC
I am trying to access actuator health endpoint in spring boot application on the application port, but it shows me 404-not available when I try to access the below url: http://localhost:8080/actuator/health

when I set a different management port using the property: management.server.port=9090, then it allows me to access on port 9090.
I need to access actuator on the same port as the application. Tried setting these properties:
management.endpoints.web.exposure.include=*
management.security.enabled=false

but nothing works. Have this class as well to override the spring security for actuator, which permits unauthorized access to end point /actuator/health. I have below dependencies in my pom.xml:

```
<dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-actuator</artifactId>
          <version>2.0.8.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
          <version>2.0.8.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter</artifactId>
          <version>2.0.8.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-security</artifactId>
          <version>2.0.8.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-integration</artifactId>
          <version>2.0.8.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.integration</groupId>
          <artifactId>spring-integration-core</artifactId>
          <version>5.0.3.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.integration</groupId>
          <artifactId>spring-integration-http</artifactId>
          <version>5.0.3.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.integration</groupId>
          <artifactId>spring-integration-xml</artifactId>
          <version>5.0.3.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework.integration</groupId>
          <artifactId>spring-integration-ws</artifactId>
          <version>5.0.3.RELEASE</version>
        </dependency>
        <dependency>
          <groupId>org.springframework</groupId>
          <artifactId>spring-context-support</artifactId>
          <version>5.0.3.RELEASE</version>
        </dependency>
    <dependency>
          <groupId>org.apache.httpcomponents</groupId>
          <artifactId>httpclient</artifactId>
          <version>4.5.3</version>
        </dependency>
    dependency>
          <groupId>org.junit.jupiter</groupId>
          <artifactId>junit-jupiter-engine</artifactId>
          <version>5.5.2</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>io.cucumber</groupId>
          <artifactId>cucumber-junit</artifactId>
          <version>4.8.0</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>com.github.tomakehurst</groupId>
          <artifactId>wiremock</artifactId>
          <version>2.6.0</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-test</artifactId>
          <version>2.0.8.RELEASE</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
```

**Comment by wilkinsona** [comment] 2020-09-25 08:26
Thanks for the report. Unfortunately, from what you've shared thus far it's not clear to me what the problem might be. You mention integration flow in the title but I can't tell why you think it's related to the problem. I see that you're using Spring Boot 2.0.8. Please note that [support for 2.0.x ended in April 2019](https://github.com/spring-projects/spring-boot/wiki/Supported-Versions#end-of-life-releases).

If you can reproduce the problem with a supported version of Spring Boot (I would recommend at least 2.2.10 and ideally 2.3.4) and you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-issuemaster** [comment] 2020-10-02 08:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-10-09 08:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-10-09 08:30 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
