### ISSUE TITLE
Schema generation properties not well documented

### ISSUE THREAD

**Issue by FelixRiemann** [spring-projects/spring-boot#11678] opened 2018-01-18 17:50 UTC
I am using Spring Boot 1.5.9 (with artifacts `spring-boot-starter-data-jpa`, `spring-boot-starter-web` and `spring-boot-starter-test`), with Hibernate and liquibase.

When running tests annotated with `@DataJpaTest`, the datasource is overridden and H2 is used. Additionally, the property `spring.jpa.hibernate.ddl-auto` defaults to `create-drop` in this case, according to https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html.

I want that my tests run against the schema created by liquibase, but the `create-drop` setting effects that liquibase's the schema is dropped, and then recreated by Hibernate according to the entities.
This is a problem because I am using views, but Hibernate generates regular tables for the corresponding entities.

I expected that schema-generation will be disabled with one of the properties
```
spring.jpa.properties.javax.persistence.schema-generation.database.action = none
spring.jpa.generate-ddl = false
spring.datasource.initialize = false
```
but none of these (or any combination) had the desired effect. The only solution that works for me is explicitly setting `spring.jpa.hibernate.ddl-auto` to `none` (or `validate`), however I find it awkward that I am forced to use a Hibernate specific setting, because I want to stay provider-agnostic as far as possible, and that's what JPA tries to achieve.

Also, I am missing in the documentation which of the four properties has precedence over another, and also what the difference between `spring.jpa.generate-ddl` and `spring.datasource.initialize` is.

**Comment by snicoll** [comment] 2018-01-19 08:34
Duplicate of #9262

**Closed by snicoll** 2018-01-19 08:34 UTC
Labels: status: waiting-for-triage
