### ISSUE TITLE
Fail to start due to org.springframework.boot.context.config.ConfigFileEnvironmentPostProcessor$ConfigurationPropertySources cannot be cast to org.springframework.boot.context.config.ConfigFileApplicationListener$ConfigurationPropertySources

### ISSUE THREAD

**Issue by woraphol-j** [spring-projects/spring-boot#4812] opened 2015-12-19 05:04 UTC
I am trying to upgrade spring boot 1.3.0.RELEASE or 1.3.1.RELEASE from spring boot 1.3.0.M5 but I ran into this issue at start up time. Note that If I start a bare bone and brand new spring boot project on 1.3.0 or 1.3.1, it works fine. However with the existing code base, it fails miserably.

Since the project code base is getting bigger now, I find it hard to dissect part of it and locate the problem. Please advise me what may be related to the problem, I can use 1.3.0.M5 for now, but I plan to upgrade to the newer version if possible.

I debugged and found that this line of code leads to the error is the following java file **ConfigFileApplicationListener.java** :
```java
public static void finishAndRelocate(MutablePropertySources propertySources) {
			String name = APPLICATION_CONFIGURATION_PROPERTY_SOURCE_NAME;
			ConfigurationPropertySources removed = (ConfigurationPropertySources) propertySources
					.get(name); //<----- Exception occurrs here
			if (removed != null) {
				for (PropertySource<?> propertySource : removed.sources) {
					if (propertySource instanceof EnumerableCompositePropertySource) {
						EnumerableCompositePropertySource composite = (EnumerableCompositePropertySource) propertySource;
						for (PropertySource<?> nested : composite.getSource()) {
							propertySources.addAfter(name, nested);
							name = nested.getName();
						}
					}
					else {
						propertySources.addAfter(name, propertySource);
					}
				}
				propertySources.remove(APPLICATION_CONFIGURATION_PROPERTY_SOURCE_NAME);
			}
		}

```

The console log (info logging mode) look like this:
```
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.1.RELEASE)

[user:] -- 11:58:21.816 [restartedMain] INFO  c.a.i.InspectionApiApplication - Starting InspectionApiApplication on woraphol-ubuntu with PID 7074 (/home/woraphol/serverteam/inspection/inspection-api/target/classes started by woraphol in /home/woraphol/serverteam/inspection/inspection-api)
[user:] -- 11:58:21.818 [restartedMain] INFO  c.a.i.InspectionApiApplication - No active profile set, falling back to default profiles: default
[user:] -- 11:58:21.969 [pool-1-thread-1] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.1.Final
[user:] -- 11:58:22.087 [restartedMain] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@68c5b1c9: startup date [Sat Dec 19 11:58:22 ICT 2015]; root of context hierarchy
[user:] -- 11:58:23.845 [restartedMain] INFO  o.s.b.f.s.DefaultListableBeanFactory - Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
[user:] -- 11:58:24.254 [restartedMain] INFO  o.s.b.f.s.DefaultListableBeanFactory - Overriding bean definition for bean 'org.springframework.autoconfigure.redis.RedisProperties' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration; factoryMethodName=redisProperties; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/data/redis/RedisAutoConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.redis.RedisAutoConfiguration; factoryMethodName=redisProperties; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/redis/RedisAutoConfiguration.class]]
[user:] -- 11:58:27.182 [restartedMain] ERROR o.s.boot.SpringApplication - Application startup failed
java.lang.ClassCastException: org.springframework.boot.context.config.ConfigFileEnvironmentPostProcessor$ConfigurationPropertySources cannot be cast to org.springframework.boot.context.config.ConfigFileApplicationListener$ConfigurationPropertySources
	at org.springframework.boot.context.config.ConfigFileApplicationListener$ConfigurationPropertySources.finishAndRelocate(ConfigFileApplicationListener.java:638) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$PropertySourceOrderingPostProcessor.reorderSources(ConfigFileApplicationListener.java:305) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$PropertySourceOrderingPostProcessor.postProcessBeanFactory(ConfigFileApplicationListener.java:300) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:131) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at com.agisaas.inspection.InspectionApiApplication.main(InspectionApiApplication.java:32) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.1.RELEASE.jar:1.3.1.RELEASE]
[user:] -- 11:58:27.186 [restartedMain] INFO  o.s.b.l.ClasspathLoggingApplicationListener - Application failed to start with classpath: [file:/home/woraphol/serverteam/inspection/inspection-api/target/classes/, file:/home/woraphol/serverteam/inspection/inspection-core/target/classes/, file:/home/woraphol/serverteam/inspection/common/target/classes/, file:/home/woraphol/serverteam/inspection/common/target/test-classes/]
```

Please let me know if you need more information. I will try my best to get as much information as I can.

**Comment by wilkinsona** [comment] 2015-12-19 10:57
`ConfigFileEnvironmentPostProcessor` doesn't exist in 1.3.0.RELEASE or later (it was renamed to `ConfigFileApplicationListener`). It looks like you have a mixture of Boot versions on the classpath. You can check using `./gradlew dependencies` or `mvn dependency:tree`.

**Comment by spring-issuemaster** [comment] 2015-12-26 11:00
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-01-02 11:00
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-01-02 11:00 UTC

**Comment by deki** [comment] 2016-01-11 15:37
Just ran into a similar issue, why not adding an instanceof check there?

java.lang.ClassCastException: org.springframework.core.io.support.ResourcePropertySource cannot be cast to org.springframework.boot.context.config.ConfigFileApplicationListener$ConfigurationPropertySources
	at org.springframework.boot.context.config.ConfigFileApplicationListener$ConfigurationPropertySources.finishAndRelocate(ConfigFileApplicationListener.java:638) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$PropertySourceOrderingPostProcessor.reorderSources(ConfigFileApplicationListener.java:305) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener$PropertySourceOrderingPostProcessor.postProcessBeanFactory(ConfigFileApplicationListener.java:300) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:131) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113) [spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]

**Comment by wilkinsona** [comment] 2016-01-11 16:37
@deki I don't think that's a similar issue. This issue was caused by having a mixture of Spring Boot versions on the classpath and an `instanceof` check wouldn't help there.

In your case it looks like the property source named `applicationConfigurationProperties` has been replaced with one of a different type (specifically a `ResourcePropertySource` instance`). I don't understand why you'd want to do that, but perhaps I've overlooked something. If you think you have a valid use case for this, please open a separate issue that describes what you're doing and why so that we can consider it.

**Comment by deki** [comment] 2016-01-11 16:45
Thanks for the quick feedback, I'll take a closer look at it and open a separate issue, if it's still valid.

**Comment by woraphol-j** [comment] 2016-01-23 09:13
Sorry for the absence, to give you an update, thanks @wilkinsona , you are right!. After doing the maven repository clean up, I can successfully get it to go up. This issue can be closed.
