### ISSUE TITLE
java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy

### ISSUE THREAD

**Issue by kimifdw** [spring-projects/spring-boot#13910] opened 2018-07-26 06:59 UTC
I have Spring boot project. The spring boot version is 1.5.9.RELEASE. I run on server Centos.I build and run success several times.But it sometimes will get the below error. the application can run success.How can i solve the problem.Here my Log:
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.warn(SLF4JLocationAwareLog.java:192)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1003)
	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)

**Comment by snicoll** [comment] 2018-07-26 08:51
Duplicate of #6151

**Closed by snicoll** 2018-07-26 08:51 UTC
Labels: status: waiting-for-triage
