### ISSUE TITLE
WebSocket with with Tomcat / HTTP/2 / TLS

### ISSUE THREAD

**Issue by ralscha** [spring-projects/spring-boot#15742] opened 2019-01-20 12:05 UTC
I'm experimenting with HTTP/2 and found an issue where WebSocket does not work when Tomcat is used as the server in Spring Boot 2.1.2

Here is a demo application that demonstrates the problem:    
https://github.com/ralscha/springboot-http2

WebSocket does work with Undertow and Jetty. 
With HTTP/1.1 all servers work. 

An unrelated issue is that HTTP/2 Push works with Tomcat, but not with Undertow and Jetty.

**Comment by philwebb** [comment] 2019-01-22 17:55
@bclozel Do you think this is a Framework issue? I've not looked in detail yet, but it feels unlikely that Boot specific code would be in active here.

**Comment by bclozel** [comment] 2019-01-22 20:50
The problem isn't actually about websocket, but dual http/1.1 + http/2 support.

As far as I know, WebSocket over HTTP/2 is not supported in all those servers. Last time I checked, there was [a proposed standard that got recently updated, RFC 8441](https://tools.ietf.org/html/rfc8441), but nothing more than that. I couldn't find any trace of such support in Tomcat [nor Jetty](https://github.com/eclipse/jetty.project/issues/1364).

After checking your sample, it seems that Undertow and Jetty are doing the connection upgrade over http/1.1.

With your sample, running `curl --http1.1 https://localhost:8443/ --insecure -vv` works with Jetty and Undertow, but not Tomcat.

I guess the issue here is about our setup consistency - should we enable or disable http/1.1 when http/2 is enabled? This is a tough choice to make: many people might rely on http/1.1 for clients that don't support http/2, but others might want to enforce http/2 no matter what. In both cases, the cipher suites and certificates being used should be state of the art.

I'm closing this issue and I've created #15764 to track the underlying problem.

**Closed by bclozel** 2019-01-22 20:50 UTC
Labels: status: invalid
