### ISSUE TITLE
springboot2.1.5 context-path

### ISSUE THREAD

**Issue by xiaoshitou981023** [spring-projects/spring-boot#17338] opened 2019-06-28 02:55 UTC
```yaml
server:
  port: 8888
  servlet:
    context-path: /dev
```

I try it, but this is invalid;

spring-boot version : 2.1.5.RELEASE

**Comment by wilkinsona** [comment] 2019-06-28 06:26
Thanks for the report. We’ll need some more details to be able to diagnose your problem. 

What do you mean by invalid? Can you please describe what you expected to happen and what actually happened. Details of your application’s dependencies would also be useful. A minimal sample, attached as a zip to this issue or in a separate GitHub repository, would be even better.

**Comment by xiaoshitou981023** [comment] 2019-06-28 07:15
> Thanks for the report. We’ll need some more details to be able to diagnose your problem.
> 
> What do you mean by invalid? Can you please describe what you expected to happen and what actually happened. Details of your application’s dependencies would also be useful. A minimal sample, attached as a zip to this issue or in a separate GitHub repository, would be even better.

i am sorry , I'm trying to replace the web with Webflux,  I didn't notice webflux don't hava Servlet
but i want seting an context-path , I don't know how to do it.

**Comment by bclozel** [comment] 2019-06-28 07:53
Closing this issue as a duplicate of #10129

**Closed by bclozel** 2019-06-28 07:53 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by xiaoshitou981023** [comment] 2019-06-28 09:02
> Closing this issue as a duplicate of #10129

webflux does not support context-path , but if use filter trim this context-path , 
Does he have an impact on the existing system?

**Comment by bclozel** [comment] 2019-06-28 10:16
It could work, but you have to pay attention to the ordering of filters (especially if one is taking care of security).

**Comment by xiaoshitou981023** [comment] 2019-06-29 03:16
> It could work, but you have to pay attention to the ordering of filters (especially if one is taking care of security).

Thank you very much for answering my question
