### ISSUE TITLE
Spring Boot Gradle build is never fully up-to-date

### ISSUE THREAD

**Issue by pioterj** [spring-projects/spring-boot#9919] opened 2017-07-31 15:08 UTC
Spring Boot Gradle build is never fully up-to-date without extra configuration.

Below is the plain console output for a `gradle build` command on a simplest Spring Boot app generated by https://start.spring.io/, right after successfully executing a full build.

```
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:jar
:bootRepackage
:assemble
:compileTestJava UP-TO-DATE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build
```
Expected behavior is that all tasks are UP-TO-DATE when re-executing a build without changes.

There is a workaround described in https://stackoverflow.com/a/38036833 but it would be nice if it worked out of the box. 

Spring Boot version 1.5.6.RELEASE.

**Comment by wilkinsona** [comment] 2017-07-31 15:10
Duplicate of #5861

**Closed by wilkinsona** 2017-07-31 15:10 UTC
