### ISSUE TITLE
Velocity templates ignore `spring.velocity.cache` property

### ISSUE THREAD

**Issue by zhoudianyou** [spring-projects/spring-boot#3181] opened 2015-06-10 10:18 UTC
using spring-boot-velocity version is 1.2.4

view doc for  
72.5 Reload Velocity templates without restarting the container
If you are using Velocity, then set spring.velocity.cache to false. See VelocityAutoConfiguration for other Velocity customization options.

container not restarting   ...    Not loading new template

Also you need to set the parameters of what  ?

**Comment by snicoll** [comment] 2015-06-10 10:29
Could you be a bit more specific? What IDE are you using? If you use IJ, you need to make so that the updated template can be seen by the application.

**Comment by zhoudianyou** [comment] 2015-06-10 16:49
My using    spring-boot-sample-web-velocity Project

set application.properties  spring.velocity.cache=false

Run as Main    
server start ........

access  localhost:8080     ----->   sucess      ServerResponse    .vm    view 

---------------------
I want to test  

72.5 Reload Velocity templates without restarting the container
If you are using Velocity, then set spring.velocity.cache to false. See VelocityAutoConfiguration for other Velocity customization options.

Is valid    
edit   target/classes/template/welcome.vm 


---------------------
Refresh   Browser  access localhost:8080   ------------>  response           Not changed

**Comment by philwebb** [comment] 2015-06-14 05:46
I'm unable to replicate the issue on my end. Steps I took:

* Edit `src/main/resources/application.properties` to add `spring.velocity.cache=false`
* Run `SampleWebVelocityApplication`
* Open localhost:8080
* Change `welcome.vm` (I changed the `Time:` text)
* Refresh the browser

I tried editing `src/main/resources/templates/welcome.vm` from eclipse and editing `target/classes/template/welcome.vm` directly. Both worked.

Perhaps there is something different in your setup. Are you able to provide a sample project and also confirm the version of Spring Boot that you're using.

**Comment by wilkinsona** [comment] 2015-10-12 12:51
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.

**Closed by wilkinsona** 2015-10-12 12:51 UTC
Labels: question, waiting-for-feedback

**Comment by chris-elder** [comment] 2016-03-21 12:05
Hi,

I'm also experiencing this issue after upgrading from spring-boot-starter-parent 1.2.8.RELEASE to 1.3.2.RELEASE or 1.3.3.RELEASE

For the dependecies, I have allowed maven to pull the latest. POM snippet below:

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-velocity</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-integration</artifactId>
			<scope>compile</scope>
		</dependency>

**Comment by wilkinsona** [comment] 2016-03-21 12:32
@chris-elder This issue has been closed as we were unable to reproduce the problem. If you can reproduce the problem, please open a new issue with a sample project that does so.

**Comment by wq163** [comment] 2016-05-09 04:52
I can't change too. I use VelocityLayoutViewResolver as follow:

```
@Bean(name = "velocityViewResolver")
    public VelocityLayoutViewResolver velocityViewResolver(VelocityProperties properties) {
        VelocityLayoutViewResolver resolver = new VelocityLayoutViewResolver();
        properties.applyToViewResolver(resolver);
        resolver.setLayoutUrl("layout/default.vm");
        return resolver;
    }
```

**Comment by wq163** [comment] 2016-05-09 05:09
I debug it in AbstractCachingViewResolver#isCache, then i can see a instance named `InternalResourceViewResolver#isCache` return true

![image](https://cloud.githubusercontent.com/assets/1230366/15104163/e36605b8-15e6-11e6-9cba-065e9d8884e7.png)
