### ISSUE TITLE
Using Spring Cloud Config and Spring Boot Actuator in Spring Boot 2.0.2 leads to IllegalStateException

### ISSUE THREAD

**Issue by vkennke** [spring-projects/spring-boot#13126] opened 2018-05-09 16:43 UTC
Spring Boot Version: 2.0.2.RELEASE
Spring Cloud Version: Finchley.RC1

Using Spring Cloud Config and Spring Boot Actuator while exposing the /env Endpoint leads to the following Exception: 

`java.lang.IllegalStateException: Found multiple extensions for the endpoint bean environmentEndpoint (environmentEndpointWebExtension, environmentWebEndpointExtension)`

Stacktrace: https://pastebin.ca/4024026

Minimal example: https://github.com/vkennke/actuator-cloud-config-minimal
Configuration is like https://spring.io/guides/gs/centralized-configuration/

With Spring Boot 2.0.1.RELEASE there is no problem, I think the problem is introduced by https://github.com/spring-projects/spring-boot/issues/12827.

**Comment by snicoll** [comment] 2018-05-09 18:44
Duplicate https://github.com/spring-cloud/spring-cloud-commons/issues/354

**Comment by snicoll** [comment] 2018-05-09 18:48
Actually, this is a problem as we don't support multiple extensions for the same endpoint at the moment. This got hidden by the fact that the name of the bean in Spring Cloud was overriding ours but now that it has been fixed in 2.0.2, this exception occurs.

**Comment by snicoll** [comment] 2018-05-10 08:51
Duplicate of https://github.com/spring-cloud/spring-cloud-commons/issues/367

**Closed by snicoll** 2018-05-10 08:51 UTC
Labels: status: waiting-for-triage

**Comment by superbrown** [comment] 2019-11-05 20:50
Is there a work-around for this?

**Comment by philwebb** [comment] 2019-11-05 23:27
@superbrown The [Spring Cloud issue](https://github.com/spring-cloud/spring-cloud-commons/issues/367) was marked as fixed. If you still have problems please open a new issue at https://github.com/spring-cloud/spring-cloud-commons/issues/new
