### ISSUE TITLE
 Upgrade to Maven Surefire/Failsafe Plugin 2.20.1+

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9414] opened 2017-06-06 05:17 UTC
See #6299  for our first attempt. It looks like a memory leak that we may need to report to the surefire team.

**Comment by shakuzen** [comment] 2017-06-15 13:57
I'm not sure if the cause is the same, but [SUREFIRE-1382](https://issues.apache.org/jira/browse/SUREFIRE-1382) was found and recently fixed in surefire. It should be in the upcoming version `2.20.1` (and in `2.21-SNAPSHOT` already).

**Comment by wilkinsona** [comment] 2017-06-15 16:10
Thanks, @shakuzen. That does sound pretty similar.

**Comment by SebastianDietrich** [comment] 2017-06-27 16:36
please upgrade as well maven-failsafe-plugin (has traditionally the same version as surefire)

**Comment by wilkinsona** [comment] 2017-07-26 08:29
There's no release date set for 2.20.1 and there are still 3 open issues. Moving to M4.

**Comment by wilkinsona** [comment] 2017-09-19 20:30
Good news: 2.20.1 is out. Bad news: JUnit 5 isn't compatible with it. See [this issue](https://github.com/junit-team/junit5/issues/809#issuecomment-330488537) for details. We'll need to update our Junit 5 sample to downgrade Surefire to 2.19.1 as part of this.

**Closed** 2017-09-19 20:32 UTC
Labels: priority: normal, type: enhancement
