### ISSUE TITLE
destroy method not executed when doing Ctrl+C or kill command

### ISSUE THREAD

**Issue by duggu9** [spring-projects/spring-boot#10096] opened 2017-08-29 03:28 UTC
Hi,

I want destroy method executed for a bean which is implementing Disposable Bean.  Below is the piece of code which i have written in my application. When i am trying to stop the application in windows by doing ctrl + c or by kill command in unix, the destroy method is not getting triggered. 

Can someone help me in this regard.

@SpringBootApplication
@EnableScheduling
@EnableJms
public class Sample {
	
	public static void main(String[] args) throws NamingException, JMSException {
		SpringApplication springApplication = new SpringApplication(Sample.class);
		ConfigurableApplicationContext context = springApplication.run(args);
			
		context.registerShutdownHook();
	}
}

**Comment by wilkinsona** [comment] 2017-08-29 08:56
What signal are you sending with `kill`?

**Comment by duggu9** [comment] 2017-08-29 13:31
Hi Wilkinsona,

I am trying to stop the application and see piece of code defined in the destroy method is getting executed.

**Comment by wilkinsona** [comment] 2017-08-29 13:38
Thanks, but that doesn't answer my question. I understand what you are trying to do, but it'd like to know how you are doing it. What is the `kill` command that you're using?

**Comment by duggu9** [comment] 2017-08-29 13:44
kill <PID> in unix and in windows i am running application through command prompt jar -jar command and trying to stop application by doing ctrl+c

**Comment by duggu9** [comment] 2017-08-29 13:45
kill <<PID>> this is the command i am using

**Comment by wilkinsona** [comment] 2017-08-29 13:57
Thanks. Ok, so it sounds like you're sending `TERM` which is the default signal sent by `kill`. That should work. You haven't shared any details of the destroy method that you expect to be called so it's impossible to tell why it isn't being called. Can you please share a small sample that reproduces the behaviour you have described?

**Comment by duggu9** [comment] 2017-08-29 14:12
It is not working in windows when i am trying to stop application using ctrl+c command.

**Comment by wilkinsona** [comment] 2017-08-29 14:15
> You haven't shared any details of the destroy method that you expect to be called so it's impossible to tell why it isn't being called. Can you please share a small sample that reproduces the behaviour you have described?

**Comment by spring-issuemaster** [comment] 2017-09-05 14:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-09-12 14:17
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-09-12 14:17 UTC
