### ISSUE TITLE
Thymeleaf issue - Integration Test

### ISSUE THREAD

**Issue by raxim1** [spring-projects/spring-boot#8238] opened 2017-02-08 18:00 UTC
Question

I'm using
```
@Bean
public LiteDeviceDelegatingViewResolver liteDeviceAwareViewResolver() {
InternalResourceViewResolver delegate = new InternalResourceViewResolver();
...
}
```

 in the WebMvcConfigurerAdapter and it works fine in the real webapp.

InternalResourceViewResolver and ThymeleafResolver does not use the same interface also.

I'm aware of that as a delegate i can use Thymeleaf in my LiteDeviceDelegatingViewResolver, but i don't want to do that, as i have lots of javascript,and just one html page for different devices.

My webapp is not autoconfigured, so the application.properties is being ignored automatically.
Sometimes it would be nice, that it's just loaded as a property source as default, even if it's not autoconfiguring. - i think it was not an expected behavior also.

The question is, why the Thymeleaf is autoconfigured in my test and using the application.properties file also, even if the real webapp does not have any auto configuration and i'm defining the test with 

```
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = AppConfig.class)
```

Bug report

I think it's strange behavior.

Enhancement

I think it's a trap, which might need to be solved, or i might miss something here, pls. help.

**Comment by wilkinsona** [comment] 2017-02-08 18:10
> The question is, why the Thymeleaf is autoconfigured in my test and using the application.properties file also, even if the real webapp does not have any auto configuration

It's impossible to say with the information you've provided. If you'd like us to spend time investigating, please spend some time producing a sample the reproduces the behaviour you've described.

**Comment by raxim1** [comment] 2017-02-08 18:38
I have realized that if i'm removing the 
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

I'm getting the following log:
19:19:46,814 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.thymeleaf] to false
19:19:46,814 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DEBUG_LEVEL_REMAPPER] to Logger[org.thymeleaf]

anyway in the test it won't come up also. The log now seems to me similar, than in my test.

I might attach some extracted thing later on.

**Comment by spring-issuemaster** [comment] 2017-02-15 18:46
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-02-22 18:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-02-22 18:46 UTC
Labels: status: waiting-for-triage
