### ISSUE TITLE
Ease extension of DataSourcePublicMetrics

### ISSUE THREAD

**Issue by mduesterhoeft** [spring-projects/spring-boot#10288] opened 2017-09-14 08:05 UTC
I want to publish additional DataSource metrics that a Tomcat DataSource provides (number of idle connections, current pool size). 

Currently, this is very hard to do because the functionality in `DataSourcePublicMetrics` cannot be reused by subclasses.

I will come up with a proposal on how to improve this situation.

**Comment by wilkinsona** [comment] 2017-09-14 08:16
Thanks for raising this. If you intend to immediately make a proposal in a pull request, there's no need to open an issue too. I'll close this one as a duplicate of the PR.

**Comment by wilkinsona** [comment] 2017-09-14 08:16
Duplicate of #10289

**Closed by wilkinsona** 2017-09-14 08:16 UTC
Labels: status: waiting-for-triage
