### ISSUE TITLE
ConfigurationProperties can't inject environment variable with dash prefix in linux

### ISSUE THREAD

**Issue by higankanshi** [spring-projects/spring-boot#15605] opened 2019-01-03 09:19 UTC
First of all, due to using docker, I have no `application.yml` or `application.properties` in my resource, I am setting properties by environment variable only.

Here are my properties and config define.
```Kotlin
@ConditionalOnProperty(prefix = "my-service", name = ["endpoint"])
@ConfigurationProperties(prefix = "my-service")
@EnableConfigurationProperties(MyServiceConfig::class)
class MyServiceConfig {
    lateinit var endpoint: String

    @Bean
    override fun someBean(): Any {
        // Create bean here by endpoint.
    }
}
```

Because of Linux not support dash('-') for the environment variable, I am using `MY_SERVICE_ENDPOINT` to define these properties.
```
> env
MY_SERVICE_ENDPOINT=http://my-service:8080
```

But windows support it, and I am using `MY-SERVICE_ENDPOINT` to defined these properties in Windows.
```
> env
MY-SERVICE_ENDPOINT=http://my-service:8080
```

This config works fine with Windows, but not Linux. It tells me `endpoint` is not initialized. You can see, I defined a `ConditionalOnProperty` in my config, if spring can't resolve this property, this config should not import.

So, I have more test for it.
It works fine both in Windows and Linux with `Value` annotation.
```Kotlin
@Value("\${my-service.endpoint}")
lateinit var endpoint: String    // Work fine.
```

If I changed my config to this
```Kotlin
@ConditionalOnProperty(prefix = "my-service", name = ["endpoint"])
@ConfigurationProperties(prefix = "my")
@EnableConfigurationProperties(MyServiceConfig::class)
class MyServiceConfig {
    lateinit var serviceEndpoint: String

    @Bean
    override fun someBean(): Any {
        // Create bean here by endpoint.
    }
}
```
You can see, I changed my prefix to `my` and change the property to `serviceEndpoint`, it can work fine with Linux...

**Comment by mbhave** [comment] 2019-01-04 23:02
@higankanshi As you mentioned, Linux does not support `-` for  environment variables so I don't quite follow why you'd expect `MY-SERVICE_ENDPOINT` to work on Linux.  

I'm going to close this issue as `_` should be used as a delimiter for environment variables as stated in the [wiki](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#environment-variables) and not `-`. If you have any more questions, please ask on StackOverflow or Gitter.

**Closed by mbhave** 2019-01-04 23:02 UTC
Labels: status: waiting-for-triage

**Comment by higankanshi** [comment] 2019-01-05 08:07
Have you read my description carefully.

My question is why `Value` and `ConditionalOnProperty` can resolve `my-service.endpoint` to `MY_SERVICE_ENDPOINT`, but `ConditionalOnProperty` not?

**Comment by higankanshi** [comment] 2019-01-05 08:15
@mbhave

**Comment by snicoll** [comment] 2019-01-05 08:55
> Have you read my description carefully?

Yes, I did and asked for help because I didn't understand what you were reporting. I still don't so if you want some help, share a sample (Github repo or zip) that we can run ourselves with instructions.

**Comment by higankanshi** [comment] 2019-01-05 11:04
@snicoll 
My question is why `Value` and `ConditionalOnProperty` can resolve `my-service.endpoint` to `MY_SERVICE_ENDPOINT`, but `ConfigurationProperties` not?

**Comment by higankanshi** [comment] 2019-01-05 11:55
OK, I am not good at English, my wording may be offensive, forget me, please.

I don't know you can't recurrent this problem, I will give you a sample later.

**Comment by higankanshi** [comment] 2019-01-05 11:55
@snicoll

**Comment by bakoontz** [comment] 2020-01-17 21:38
To @devkanro's credit, he has a point:  Hyphens and underscores are handled inconsistently, even within the same environment.  

I can confirm the following works in Linux:

application.yml:
```
vcap:
     services:
        s3-mct-service:
            credentials:
                 <stuff>
```
Some spring class:
```
@ConfigurationProperties(prefix="vcap.services.s3-mct-service.credentials")
```
Now, if I want to run this app locally, in Cygwin,  I can't use the application properties as they are due to the hyphens (not supported as environment vars).  But if I modify them:

```
export VCAP_SERVICES_S3_MCT_SERVICE_CREDENTIALS_ACCESSKEY=<some key>
```
then the @ConfigurationProperties prefix is unrecognized.  

Instead of dismissing the OP, think about the issue:  Inconsistent conversion of periods, hyphens, and underscores lead to different behaviors in different environments.  Why not make them consistent?  There is no reason why a hyphen cannot be interpreted as an underscore.

**Comment by philwebb** [comment] 2020-01-21 21:39
> There is no reason why a hyphen cannot be interpreted as an underscore.

Unfortunately there is a reason why we can't just treat a hyphen as an underscore (in fact we used to have a much more flexible binding mechanism in Spring Boot 1.5 but we changed it because it caused a lot of subtle issues). Depending on the environment, not all property sources may be iterable. With some `PropertySource` implementation we can only ask "what's the value of the property named 'X'", we can't ask "what are all property names that you know about".

In order to support those non-iterable sources, we need an algorithm that can take a configuration key and convert it into a name. In the example above we'd do this:

1) Initial name = `vcap.services.s3-mct-service.credentials`
2) Remove hyphens = `vcap.services.s3mctservice.credentials`
3) Convert dots to underscores = `vcap_services_s3mctservice_credentials`
4) Uppercase = `VCAP_SERVICES_S3MCTSERVICE_CREDENTIALS`

If we allow hyphens we can't make unique mappings. I.e. `vcap.services.s3-mct-service.credentials`, `vcap.services.s3.mct-service.credentials`, `vcap.services.s3-mct.service.credentials`, `vcap.services.s3-mct-service-credentials` all end up as `VCAP_SERVICES_S3_MCT_SERVICE_CREDENTIALS`.

Although the restriction can cause some confusion (as OP pointed out), we've generally found these strict rules to be much less error-prone overall.
