### ISSUE TITLE
Cannot invoke "java.lang.Class.isInterface()" because "typeToRead" is null

### ISSUE THREAD

**Issue by ramonmalcolm10** [spring-projects/spring-boot#29531] opened 2022-01-22 07:12 UTC
When using Spring data JPA projection, the application is failing to start with the following error:

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isInterface()" because "typeToRead" is null
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:181) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:152) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:59) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:95) ~[spring-data-commons-2.6.1.jar:2.6.1]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:81) ~[spring-data-commons-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.<init>(PartTreeJpaQuery.java:217) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:92) ~[spring-data-jpa-2.6.1.jar:2.6.1]
	... 84 common frames omitted
```
 
Affected Spring Boot version is 2.6.3.

**Comment by wilkinsona** [comment] 2022-01-22 08:18
Thanks for the report. This looks like a bug in Spring Data JPA which is managed as a separate project. I believe it's a duplicate of https://github.com/spring-projects/spring-data-jpa/issues/2408.

**Closed by wilkinsona** 2022-01-22 08:18 UTC
Labels: status: waiting-for-triage
