### ISSUE TITLE
Add out-of-the-box health indicator for reactive MongoDB

### ISSUE THREAD

**Issue by olivergierke** [spring-projects/spring-boot#11766] opened 2018-01-25 09:30 UTC
[This section](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_auto_configured_healthindicators) of the reference documentation suggest that an indicator would be auto-configured in case MongoDB was in use. Upon close inspection it seems that the indicator expects a `MongoTemplate` which is not available if you use the new reactive APIs. I guess an additional one is needed based on `ReactiveMongoOperations`.

I guess the same could be done for Cassandra and Redis.

I'd also suggest to refactor the current one to work against `MongoOperations` instead of the implementation class.

**Comment by wilkinsona** [comment] 2018-01-25 09:46
Thanks, @olivergierke. We already have one for Redis but Cassandra seems to be another oversight. I've opened https://github.com/spring-projects/spring-boot/issues/11767 for that.

**Comment by izeye** [comment] 2018-07-31 13:44
This looks resolved via https://github.com/spring-projects/spring-boot/pull/11997.

**Comment by snicoll** [comment] 2018-07-31 13:55
Indeed @izeye, thanks!

Duplicate of #11997

**Closed by snicoll** 2018-07-31 13:55 UTC
Labels: type: enhancement
