### ISSUE TITLE
Order of entries no longer preserved in Map field of @ConfigurationProperties type when bound from YAML

### ISSUE THREAD

**Issue by jkuipers** [spring-projects/spring-boot#21670] opened 2020-06-03 15:39 UTC
After updating to Boot 2.3.0, ordering of entries in a Map-based field in an `@ConfigurationProperties`-annotated class as specified in application.yml are no longer preserved. 
This breaks Spring Cloud Zuul when a user specifies multiple routes with overlapping paths where order is critical. Cloud's docs explicitly state that order is guaranteed to be preserved when using YAML:
https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html#netflix-zuul-reverse-proxy (last section of that paragraph). 

Here's a app with a failing test to reproduce the issue: 
[entries-order.zip](https://github.com/spring-projects/spring-boot/files/4724452/entries-order.zip)
The test fails on my machine, running Windows and OpenJ9 Java 11.

I have not attempted to investigate what change in Boot caused this behavior, so I'm not sure if my OS or Java version are involved, but I'm quite confident that it's a regression in Boot that should be fixed.

**Comment by wilkinsona** [comment] 2020-06-03 15:57
Thanks, @jkuipers. This is a duplicate of #21470.

**Closed by wilkinsona** 2020-06-03 15:57 UTC
Labels: status: waiting-for-triage

**Comment by jkuipers** [comment] 2020-06-03 15:59
Ah, should've searched before reporting. Thanks, glad that this will be addressed.
