### ISSUE TITLE
I didn't see cloudwatch，is there any docs or examples?

### ISSUE THREAD

**Issue by TsingLiang** [spring-projects/spring-boot#15636] opened 2019-01-07 08:56 UTC
I didn't see cloudwatch，is there any docs or examples?
![image](https://user-images.githubusercontent.com/13382535/50758406-17349c00-129d-11e9-8ba2-e749860bc2b9.png)

**Comment by snicoll** [comment] 2019-01-07 09:32
Duplicate of #15631

**Closed by snicoll** 2019-01-07 09:32 UTC
Labels: status: waiting-for-triage
