### ISSUE TITLE
two classes with main method in one project cannot start at the same time

### ISSUE THREAD

**Issue by stillotherguy** [spring-projects/spring-boot#11609] opened 2018-01-12 06:18 UTC
```
@XproPluginApplication
public class ServerMain {

    public static void main(String[] args) throws Exception {
        ApplicationContext context = SpringApplication.run(ServerMain.class);
    }
}

@XproPluginApplication
public class ClientMain {

    public static void main(String[] args) throws Exception {
        ApplicationContext context = SpringApplication.run(ClientMain.class);

        Invoker invoker = context.getBean(Invoker.class);
        while (true) {
            try {
                invoker.invokeVoidAsyncCallback();

                TimeUnit.SECONDS.sleep(5);
            } catch (Exception e) {
                e.printStackTrace();
                TimeUnit.SECONDS.sleep(5);
            }
        }
    }
}

@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@SpringBootApplication(exclude = { HibernateJpaAutoConfiguration.class...}
@EnableDiscoveryClient
@Import(XproPluginRegistrar.class)
public @interface XproPluginApplication {
    RunMode runMode() default RunMode.SERVER;
}
```
ClientMain and ServerMain both in the same project but they are in diffrent packages, When I run ClientMain, ServerMain failed to run with errors below:

> Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.sql.DataSource' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

when I delete ClientMain, problem resolved, this is so weird!

**Comment by wilkinsona** [comment] 2018-01-12 07:06
Can you please provide a complete sample (something that we can unzip or git clone and run) that reproduces the behaviour that you have described?

**Comment by spring-issuemaster** [comment] 2018-01-19 07:09
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-01-26 07:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-01-26 07:07 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
