### ISSUE TITLE
Enable redis cache's ttl setting by cacheName

### ISSUE THREAD

**Issue by lmtoo** [spring-projects/spring-boot#23989] opened 2020-11-02 01:45 UTC
org.springframework.boot.autoconfigure.cache.CacheProperties.Redis only have a default timeToLive , but in generally ， a application need to set timeToLive by cacheName

**Comment by wilkinsona** [comment] 2020-11-02 07:51
Thanks for the suggestion. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/19042.

**Closed by wilkinsona** 2020-11-02 07:51 UTC
Labels: status: waiting-for-triage
