### ISSUE TITLE
Enable Reactor Scheduler Metrics By Default

### ISSUE THREAD

**Issue by michaelmcfadyen** [spring-projects/spring-boot#20733] opened 2020-03-30 22:07 UTC
Project reactor provides an api to expose metrics from it's internal schedulers. These metrics are very useful and I can see it being beneficial to expose these by default within spring boot as this feature may be overlooked by some. One option would be to enable them by default with a feature to allow the user to disable if needed.

How do you enable them:
`Schedulers.enableMetrics();`

Reference:
https://projectreactor.io/docs/core/release/reference/#_scheduler_metrics

**Comment by wilkinsona** [comment] 2020-03-31 07:49
Thanks for the suggestion. This is a duplicate of https://github.com/spring-projects/spring-boot/issues/15374.

**Closed by wilkinsona** 2020-03-31 07:49 UTC
Labels: status: waiting-for-triage
