### ISSUE TITLE
Extend spring-boot-maven-plugin to allow customizing the loader for java SPIs

### ISSUE THREAD

**Issue by MFAshby** [spring-projects/spring-boot#40766] opened 2024-05-15 10:27 UTC
I want to install a custom [DateFormatSymbolsProvider](https://docs.oracle.com/javase/8/docs/api/java/text/spi/DateFormatSymbolsProvider.html) to work around [this issue](https://bugs.openjdk.org/browse/JDK-8256837) where short month symbols changed in the JVM default locales. The supported mechanism for doing this is to use an [SPI](https://www.baeldung.com/java-spi), which requires adding a file to my executable WAR: `META-INF/services/java.text.spi.DateFormatSymbolsProvider`. This must be in the root of the WAR, which is where the loader lives, not my application code.

I am using spring-boot-maven-plugin to create my executable WAR, and I cannot find any supported mechanism for customizing the loader in this way. There are workarounds such as using antrun to post-process the executable WAR, but these introduce extra complexity in the build and are not easily supported to also work in the IDE.

I think this relates to https://github.com/spring-projects/spring-boot/issues/6626 but I can't tell if it's an exact duplicate. Java SPIs are a well defined way of customizing JVM components and it seems unusual there's no documented way to use them in a spring boot application.

**Comment by wilkinsona** [comment] 2024-05-15 10:41
Yes, this is a duplicate of #6626.

**Closed by wilkinsona** 2024-05-15 10:41 UTC
Labels: status: waiting-for-triage
