### ISSUE TITLE
Classpath ordering of archives differs for executing fat jar vs exploded 

### ISSUE THREAD

**Issue by aclement** [spring-projects/spring-boot#11208] opened 2017-11-29 21:08 UTC
When running a fat jar the list of entries from the BOOT-INF/lib folder is treated as already ordered (as produced by the maven plugin) - so we respect it and do not modify it when constructing the classpath we'll use. When running as an exploded jar, we walk the file system and alphabetically sort the set of archives we find in the BOOT-INF/lib folder.  This could give rise to unexpected issues, particularly if you run the jar locally and it is fine then push it to cloud foundry, where it will be unpacked prior to launch.  It is important that the order is predictable but it would be even better if the order was also the same in both cases.

Discussed it a bit with Phil and we talked about perhaps a manifest of the ordering being placed in the jar which could then be discovered in the exploded case and used to order the jars we find. (Is this a bit like the thin jar manifest...)

**Comment by spencergibb** [comment] 2017-11-29 21:13
I worked with a user on this before as well since auto-configuration changed because of the ordering. Actually, I think the user was @mminella.

**Comment by wilkinsona** [comment] 2017-11-29 21:18
Duplicate of #9128.

**Closed by wilkinsona** 2017-11-29 21:18 UTC
Labels: status: waiting-for-triage
