### ISSUE TITLE
Provide ability to set contextSource base through spring.ldap.base property when using embedded LDAP autoconfiguration

### ISSUE THREAD

**Issue by pavelda2** [spring-projects/spring-boot#10443] opened 2017-09-28 10:33 UTC
Spring ldap autoconfiguration provides `spring.ldap.base` which is used when ContextSource for LdapTemplate is created.

For example:
When I specify `spring.ldap.base=dc=company,dc=com` I do not need specify whole DN (`uid=<username>,dc=company,dc=com`) when searching in ldap: 
```
function User findUser(username) {
   return ldapTemplate.lookup("uid=" + username, ldapUserContextMapper);
}
```

But I get in trouble when testing function above with embedded ldap, because contextSource created with [EmbeddedLdapAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/ldap/embedded/EmbeddedLdapAutoConfiguration.java#L100) does not obtain `base` property from `spring.ldap.base` environment property.
Embedded ldap configuration:
```
spring.ldap.embedded.ldif=classpath:test-ldap.ldif
spring.ldap.embedded.validation.schema=classpath:test-ldap-schema.ldif
spring.ldap.embedded.base-dn=dc=company,dc=com
# spring ldap base is ignored by EmbeddedLdapAutoConfiguration
spring.ldap.base=dc=company,dc=com
```
Of course, I can provide custom ContextSource bean and setup base programatically for JUnit tests purpose.
```
@Bean
@ConditionalOnProperty(name = {"spring.ldap.embedded.port", "spring.ldap.base"})
public LdapContextSource contextSource(EmbeddedLdapProperties embeddedProperties, LdapProperties ldapProperties) {
    LdapContextSource ldapContextSource = new LdapContextSource();
    ldapContextSource.setBase(ldapProperties.getBase());
    ldapContextSource.setUrl("ldap://localhost:" + embeddedProperties.getPort());
    return ldapContextSource;
}
```

But simple one line in application.properties would simplify my JUnit tests.

**Comment by snicoll** [comment] 2017-09-28 11:33
Duplicate of #10444 

@pavelda2 if you intend to submit a PR, there is no need to create an issue.

**Closed by snicoll** 2017-09-28 11:33 UTC
Labels: status: waiting-for-triage

**Comment by vdubus** [comment] 2018-01-19 14:53
The problem is still there as of version 2.0.0.M7.
Shouldn't this qualify as a bug? As `EmbeddedLdapAutoConfig` isn't correctly setting the `base` information into `LdapContextSource ` with the value from `spring.ldap.embedded.base-dn`?
I do think we should reopen this ticket.
