### ISSUE TITLE
spring.factories  AutoConfig @Import other Config

### ISSUE THREAD

**Issue by JanYunkai** [spring-projects/spring-boot#16734] opened 2019-05-07 12:03 UTC
env:
spring boot 2.0.8.RELEASE servlet web

```java
@Configuration
@Import(WebMvcConfig.class)
class AutoConfiguration {
}
```

```java
@Configuration
class WebMvcConfig extends WebMvcConfigurationSupport {
 
  @Bean
  Bean bean() {
    // it works
  }

   // not work ,because super class (WebMvcConfigurationSupport) bean not work
    @Override
    protected void addFormatters(FormatterRegistry registry) {
        registry.addConverter(new DateConverter());
    }
}
```

```java
// super class @Bean not work
class WebMvcConfigurationSupport {
	/**
	 * Return a {@link FormattingConversionService} for use with annotated controllers.
	 * <p>See {@link #addFormatters} as an alternative to overriding this method.
	 */
	@Bean
	public FormattingConversionService mvcConversionService() {
		FormattingConversionService conversionService = new DefaultFormattingConversionService();
		addFormatters(conversionService);
		return conversionService;
	}
}
```

```
// META-INF/spring.factories .....
```

**Comment by wilkinsona** [comment] 2019-05-07 12:19
Thanks for the report. It's difficult to know what's happening from a few code snippets and "it works" and "not work". If you'd like us to spend some time trying to help you, can you please spend some time to provide a complete and minimal sample that reproduces the problem. It would also be useful if you could describe the behaviour that you expect and the behaviour that you actually get.

**Comment by spring-issuemaster** [comment] 2019-05-14 12:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-05-21 12:21
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-05-21 12:21 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
