### ISSUE TITLE
log4j2 on spring-boot-starter-log4j2  create two log files insted of one

### ISSUE THREAD

**Issue by waltermelow** [spring-projects/spring-boot#3833] opened 2015-08-26 20:08 UTC
Spring Boot working with `spring-boot-starter-log4j2` and `log4j2`.
Log configuration `log4j2.xml` with current date `log-${date:yyyy-MM-dd-HH-mm-ss-SSS}.log` over file name, and only one \<File\> \<AppenderRef\>.
It generates **two log files** when on the configuration there is only one 

e.g.:
* log-2015-08-26-21-49-30-847.log  (first one empty)
* log-2015-08-26-21-49-31-154.log  (whole content)

*It should be only one log file.*

I updated an example based on `spring-boot-sample-actuator-log4j2`, to check that.

https://github.com/waltermelow/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-actuator-log4j2

On top of that I attach log4j2 configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" monitorInterval="30">
    <Properties>
        <Property name="PID">????</Property>
        <Property name="LOG_PATTERN">%clr{%d{yyyy-MM-dd HH:mm:ss.SSS}}{faint} %clr{%5p} %clr{${sys:PID}}{magenta} %clr{---}{faint} %clr{[%15.15t]}{faint} %clr{%-40.40c{1.}}{cyan} %clr{:}{faint} %m%n%wEx</Property>
    </Properties>
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT" follow="true">
            <PatternLayout pattern="${LOG_PATTERN}"/>
        </Console>
        <File name="file" fileName="logs/log-${date:yyyy-MM-dd-HH-mm-ss-SSS}.log" append="true">
            <PatternLayout pattern="${LOG_PATTERN}"/>
        </File>
    </Appenders>
    <Loggers>
        <Logger name="org.hibernate.validator.internal.util.Version" level="warn" />
        <Logger name="org.apache.coyote.http11.Http11NioProtocol" level="warn" />
        <Logger name="org.apache.tomcat.util.net.NioSelectorPool" level="warn" />
        <Logger name="org.apache.catalina.startup.DigesterFactory" level="error" />

        <Root level="info">
            <AppenderRef ref="Console"/>
            <AppenderRef ref="file"/>
        </Root>
    </Loggers>
</Configuration>
```

**Comment by philwebb** [comment] 2015-09-05 04:14
I think this is probably a duplicate of #2558 (and also 3867). See this https://github.com/spring-projects/spring-boot/issues/2558#issuecomment-115447712 for the reason why double initialization occurs.

Can you try with the latest 1.3 milestone and rename your configuration to `log4J2-spring.xml`.

**Closed by philwebb** 2015-09-05 04:14 UTC

**Comment by waltermelow** [comment] 2015-09-09 14:39
I try it, and it work fine.

Thanks for your great work!
