### ISSUE TITLE
Allow to ignore URL patterns during observation

### ISSUE THREAD

**Issue by benediktwetzel** [spring-projects/spring-boot#33988] opened 2023-01-26 09:24 UTC
Hello, 

We are  migrating SB2.7 to SB3 and so Sleuth to Micrometer. Unfortunately, we are missing some configuration options.
Especially the migration of the following options caused problems:

```YAML
span-filter:
      additional-span-name-patterns-to-ignore:
```

```YAML
web:
      additional-skip-pattern:

```
I would be very happy for a feature that allows to specify URL patterns that are excluded from the observations per configuration property.

I have alredy mentioned this in issue https://github.com/spring-projects/spring-boot/issues/33977 and in the Micrometer [Slack Channel](https://micrometer-metrics.slack.com/archives/C662HUJC9/p1674718016273029).

Thanks in advance!

**Comment by bclozel** [comment] 2023-01-26 10:23
We've got this scheduled in Spring Framework already, as the instrumentation is now implemented in Spring Framework directly.
Closing as a duplicate of https://github.com/spring-projects/spring-framework/issues/29210

**Closed by bclozel** 2023-01-26 10:23 UTC
Labels: status: waiting-for-triage
