### ISSUE TITLE
log4j2 not initialized early enough

### ISSUE THREAD

**Issue by shollander** [spring-projects/spring-boot#5109] opened 2016-02-08 20:22 UTC
I use Log4J2 (spring-boot-starter-log4j2), and I have a custom log4j2.xml file in an external location (not classpath).  I specify the ```logging.config``` system property when starting my application like this:

```
-Dlogging.config=/etc/myconfig/log4j2.xml
````
But I still get this error message when starting up the application:

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
```

It seems that SpringBoot is initializing logging too late. It does load my config file in the end, but it can miss messages when the application fails to start.

**Comment by philwebb** [comment] 2016-02-26 03:04
I'm not sure it's possible to initialize it any earlier I'm afraid. I think that the `configuration file found` message is coming from Log4j2 itself, probably the first time a class is loaded that include `LoggerFactory.getLogger`. Could you add an additional simple `log4j2.xml` config in your jar to prevent the error?

if you can share a sample application that reproduces the problem we can dig a little deeper.

**Comment by spring-issuemaster** [comment] 2016-03-04 03:08
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by shollander** [comment] 2016-03-07 14:40
There are two possible workarounds to this issue:
* Your suggestions of adding an additional ```log4j2.xml``` file to the jar
* Defining an additional system property ```-Dlog4.configurationFile=/etc/myconfig/log4j2.xml```

Both of these solutions are sub-optimal since they create duplication and can lead to confusion. I should not need to specify a configuration multiple times/ways. I would prefer to only use a single property, either the spring boot ```logging.config``` or the native log4j2 ```log4j.configurationFile```. The problem is that spring boot is hijacking the log4j configuration so if I just use the native property then spring boot overrides it with its own.

**Comment by philwebb** [comment] 2016-04-25 03:46
It's unlikely that we we'll have time to come up with a better solution, especially since there is a workaround. A sample application that clearly shows the problem will still be very useful if you do want to progress this issue.

**Comment by spring-issuemaster** [comment] 2016-05-02 03:50
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-05-09 03:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-05-09 03:46 UTC
