### ISSUE TITLE
Exclude correct HikariCP version

### ISSUE THREAD

**Issue by pse-sonic** [spring-projects/spring-boot#16489] opened 2019-04-08 11:32 UTC
Hello,

Spring Boot 2.1.4-RELEASE uses Quartz 2.3.1 which contains hikaricp-java7 (since this release - see https://github.com/quartz-scheduler/quartz/issues/294) but the spring-boot-dependencies POM still excludes hikaricp-java6.

This causes an AbstractMethodError when using HikariCP and Quartz together.

`Caused by: java.lang.AbstractMethodError: Receiver class com.zaxxer.hikari.metrics.micrometer.MicrometerMetricsTrackerFactory does not define or inherit an implementation of the resolved method abstract create(Ljava/lang/String;Lcom/zaxxer/hikari/metrics/PoolStats;)Lcom/zaxxer/hikari/metrics/MetricsTracker; of interface com.zaxxer.hikari.metrics.MetricsTrackerFactory.`

Best regards
Sebastian

**Comment by ielatif** [comment] 2019-04-08 12:20
Is this open for contribution? I would be happy to contribute if @pse-sonic don't mind

**Comment by pse-sonic** [comment] 2019-04-08 12:26
Feel free to solve this issue :)

**Comment by snicoll** [comment] 2019-04-08 12:32
@ielatif fixing the issue is easy but I'd like to put something in place so that our build fails the next time this happens. If you want to give that a try, feel free to go ahead.

**Comment by ielatif** [comment] 2019-04-08 13:15
This is similar to this one https://github.com/spring-projects/spring-boot/issues/12364

There is tests for Quartz in QuartzAutoConfigurationTests :

1. withNoDataSource
2.  withDataSourceUseMemoryByDefault
3. withDataSource

We can add a new test **withHikariCPDataSource** to integrate HikariCP and Quartz. @snicoll What do you think?

**Comment by snicoll** [comment] 2019-04-08 13:30
@ielatif it's already using HikariCP most probably. If you managed to reproduce the error in a test, feel free to submit something.

**Comment by thackel** [comment] 2019-04-08 13:33
Additionally the project should really set up a duplicate classpath check for a maximum possible amount of dependencies (all starters for example).
This would avoid such kind of issues in the future.

**Comment by peterssond** [comment] 2019-04-09 11:00
Is there a workaround for this issue, or should I stay on 2.1.3?

**Comment by snicoll** [comment] 2019-04-09 12:06
You can exclude the dependency yourself in your project for the time being.

**Comment by ielatif** [comment] 2019-04-09 17:05
I submited this PR https://github.com/spring-projects/spring-boot/pull/16502

I have not figured out how to fail using Unit tests. I used maven-enforcer-plugin instead to fail if HikariCP-* dependencies exists.

**Comment by ielatif** [comment] 2019-04-09 17:10
PR https://github.com/spring-projects/spring-boot/pull/16502

**Comment by snicoll** [comment] 2019-04-15 09:19
Closing in favour of PR #16502

**Closed by snicoll** 2019-04-15 09:19 UTC
Labels: type: bug

**Comment by oneiros-de** [comment] 2019-06-05 12:31
For me this is not solved with 2.1.5 and flyway 2.3.1 - the startup still fails with the error.

**Comment by wilkinsona** [comment] 2019-06-05 12:47
@oneiros-de This issue applied specifically to a `com.zaxxer:HikariCP-*` dependency being pulled in via Quartz. You may have such a dependency coming from somewhere else. If you'd like us to investigate, please open a new issue with a minimal sample that reproduces the problem.

**Comment by oridool** [comment] 2020-07-27 18:02
I'm using latest springboot **2.3.2**, and have the same issue mentioned above. 

With springboot 2.3.1 , I didn't get this error.
As a workaround I added to my dependency:
```java
    implementation ('org.springframework.boot:spring-boot-starter-quartz') {
        exclude group: 'com.zaxxer', module: 'HikariCP-java7'
        // workaround for https://github.com/spring-projects/spring-boot/issues/16489
    }
```

Before this exclusion, I had the following dependencies:

+--- org.springframework.boot:spring-boot-starter-quartz -> 2.3.2.RELEASE
|    +--- org.springframework.boot:spring-boot-starter:2.3.2.RELEASE (*)
|    +--- org.springframework:spring-context-support:5.2.8.RELEASE (*)
|    +--- org.springframework:spring-tx:5.2.8.RELEASE (*)
|    \--- org.quartz-scheduler:quartz:2.3.2
|         +--- com.mchange:mchange-commons-java:0.2.15
|         +--- **com.zaxxer:HikariCP-java7:2.4.13**
|         |    \--- org.slf4j:slf4j-api:1.7.21 -> 1.7.30
|         \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.30


 I'm not sure if that is an issue related to Quartz or to SpringBoot...

**Comment by wilkinsona** [comment] 2020-07-28 08:43
Thanks for letting us know, @oridool. This is a bug in the dependency management plugin that the changes made for https://github.com/spring-projects/spring-boot/issues/21911 has exposed. I've opened https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/281.

**Comment by oridool** [comment] 2020-07-28 14:43
Thank you @wilkinsona  for the fast fix.
I assume it will be available with io.spring.dependency-management gradle plugin Version 1.0.**10**.RELEASE . Right?

**Comment by wilkinsona** [comment] 2020-07-28 16:43
Right.
