### ISSUE TITLE
Switch off BackgroundPreinitializer if there are too few CPUs

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#15721] opened 2019-01-16 15:53 UTC
How many is too few? Probably 2 or fewer. When you get to 1 or less it gets to be really slow.

**Comment by philwebb** [comment] 2019-01-16 18:15
Looks like @wilkinsona add this one as well. Will close this as a duplicate of #15722

**Closed by philwebb** 2019-01-16 18:15 UTC
Labels: status: waiting-for-triage
