### ISSUE TITLE
Placeholders are not resolved when a property in the Environment has a String[] value

### ISSUE THREAD

**Issue by darkman97i** [spring-projects/spring-boot#29642] opened 2022-02-03 18:15 UTC
Hi

Tested with:
* from version 2.4.0 to version 2.4.13
* Java OpenJDK 1.8.203
* tomcat-8.5.69
* executing war file into the tomcat

After upgrading from version **2.3.12.RELEASE** to version **2.4.0** I have found this issue. I have **also tested with the latest version 2.4.13** and also it happens. During the loading of the configuration properties file is not able to replace **${catalina.home}** with the path of the tomcat.

I have read  [upgrading-from-spring-boot-23](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#upgrading-from-spring-boot-23) and [Spring-Boot-Config-Data-Migration-Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide) but I have not been able to find the reason why it happens. Finally, I have also added in the application.properties file the parameter `spring.config.use-legacy-processing=true` and nothing was solved. I think has not relation with the issue.

Code sample
```
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration;
import org.springframework.boot.autoconfigure.solr.SolrAutoConfiguration;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.ImportResource;

import java.util.Properties;

@EnableCaching
@SpringBootApplication(exclude = {JmsAutoConfiguration.class, SolrAutoConfiguration.class})
@ImportResource("${okm.authentication.config}")
public class MainAppConfig extends SpringBootServletInitializer {
    public static void main(String[] args) {
        SpringApplication.run(MainAppConfig.class, args);
    }

	public MainAppConfig() {
		super();
		setRegisterErrorPageFilter(false);
	}

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(MainAppConfig.class).properties(getProperties());
    }

    static Properties getProperties() {
        Properties props = new Properties();
        props.put("spring.config.location", new String[]{"classpath:/application.properties", "file:${catalina.home}/openkm.properties"});
        return props;
    }
}
```

When the line
```
props.put("spring.config.location", new String[]{"classpath:/application.properties", "file:${catalina.home}/openkm.properties"});
```
is replaced by file system path the application finds the file and startup as expected
```
props.put("spring.config.location", new String[]{"classpath:/application.properties", "file:/desarrollo/tomcat/tomcat-8.5.69-boot-2/openkm.properties"});
```

Take from here the startup log with the error [startup-error.log](https://github.com/spring-projects/spring-boot/files/7997145/startup-error.log)

Thanks for your time
   Josep

**Comment by mbhave** [comment] 2022-02-03 21:50
@darkman97i Spring Boot 2.4.x has reached end of OSS support. Can you try with Spring Boot version 2.5.9 or 2.6.3 to see if the problem still exists?

From what I can tell by looking at the code, the [property is bound using the binder](https://github.com/spring-projects/spring-boot/blob/3b334485413e224b56b4b006cdbe76f5bef85805/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigDataEnvironment.java#L203) which should take care of placeholder resolution.

**Comment by darkman97i** [comment] 2022-02-04 07:53
I can confirm it happens with 2.5.9 I will try to debug the proposed class looking for the point of what it changes.

**Comment by darkman97i** [comment] 2022-02-04 19:30
I have debug the code and I'm locked because I'm not totally sure in which step the ${catalina.home} should be replaced by the file sytem path ( I supposed is what happens in background? ). I attach some screenshots.

In the next screenshot the value of the **location** still contains **${catalina.home}**, I have debug into the two resolvers are in the list of this.resolvers variable and they do not replace the **${catalina.home}** with file system path ( not sure in what point of the code should be done ? I have compared with previous code in version 2.3.X and this has been radically changed)
![Selección_106](https://user-images.githubusercontent.com/958703/152590788-7a744efa-a1cc-4014-a714-cfdb950613d2.png)

In the next screenshot is trying to load the file, because not changed the value with file system path it raises the error.
![Selección_107](https://user-images.githubusercontent.com/958703/152591222-d7b8a27c-0953-42b5-9dba-c9b7aa8a5e64.png)

Hope this will help in some manner.

**Comment by wilkinsona** [comment] 2022-02-08 12:30
The problem's caused by the rather unusual presence of a `String[]` in a property source. That's set up here:

```
props.put("spring.config.location", new String[]{"classpath:/application.properties", "file:${catalina.home}/openkm.properties"});
```

The problem doesn't occur if a more conventional comma-separated string is used instead:

```
props.put("spring.config.location", "classpath:/application.properties,file:${catalina.home}/openkm.properties");
```

When a `String[]` is used, placeholder resolution is skipped because the property's value is a `String[]` and we're looking for a `String`:

https://github.com/spring-projects/spring-boot/blob/8bc792fd00fd25da3d0bfa516391e432921cb8d5/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/properties/bind/PropertySourcesPlaceholdersResolver.java#L54-L60

It would appear to be straightforward to look for a `String[]` and perhaps a `Collection<String>` here as well but I'm not sure that's the right thing to do. I'd like to get some input from @mbhave and @philwebb before deciding what, if anything, to do.

**Comment by darkman97i** [comment] 2022-02-08 15:58
Thanks, @wilkinsona and @mbhave for your quick answer. Confirmed that replacing the String[] by a single String comma-separated it works. 

For your information, I got the configuration with String[] from version 2.0.3.RELEASE to 2.3.12.RELEASE ).In my opinion, one way to add the parameters is better than two ways, for me comma-separated is comfortable and clear to be used. The only scenario I can imagine could have sense working with String[] will be when a single String contains in the middle some comma that should not be used for splitting ( rare case ).

**Comment by mbhave** [comment] 2022-02-08 23:42
Looking at the code in 2.3.x, it looks like this worked specifically for this property because we [didn't use the `Binder`](https://github.com/spring-projects/spring-boot/blob/44eb8c39d274ab70809a3b64d323530d49bf1083/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L711) for it. It wouldn't have worked for `spring.profiles.active` which was [obtained using the `Binder`](https://github.com/spring-projects/spring-boot/blob/44eb8c39d274ab70809a3b64d323530d49bf1083/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L647). 

While adding support for `String[]` and `Collection<String>` looks straightforward, I'm not sure if we should given the Spring Framework's `PropertySourcesPlaceholderResolver` also [checks if the value is a `String`](https://github.com/spring-projects/spring-framework/blob/5c60a721a7ab81f50e9b88a031bc8a1d3e17ccb4/spring-core/src/main/java/org/springframework/core/env/PropertySourcesPropertyResolver.java#L87) before resolving placeholders.

**Comment by snicoll** [comment] 2022-03-19 09:00
I think we should align to what Framework does.

**Comment by wilkinsona** [comment] 2022-03-19 10:47
Alright, let's leave things as they are which already aligns with Framework.

**Closed by wilkinsona** 2022-03-19 10:47 UTC
Labels: for: team-attention, status: waiting-for-triage

**Comment by KiraResari** [comment] 2023-02-17 07:43
I think I ran into this after running `System.clearProperty("mail.local.address")` as part of a test that checks if changes to Environment Variables are correctly updated. Here's how I run that test:

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class AppSettingsAltEnvrionmentTest {
	public static final String SERVER_ADDRESS_KEY = "mail.local.address";
	
	static final String TEST_ADDRESS = "http://test.address";

    @Autowired
    private AppSettings appSettings;
	
    @BeforeAll
    public static void setup() {
        System.setProperty(SERVER_ADDRESS_KEY, TEST_ADDRESS);
    }

    @Test
    void mailLocalAddressShouldHaveChangedValueIfEnvironemntVariableIsSet(){
        assertEquals(TEST_ADDRESS, appSettings.getLocalAddress());
    }
    
    @AfterAll
    public static void cleanup() {
    	System.clearProperty(SERVER_ADDRESS_KEY);
    }
}
```

In the `AppSettings`, the value is assigned like this:

```
    @Value("${mail.local.address}")
    private String localAddress;
```

It worked once, but all the tests (even completely unrelated ones in a different SpringBootContext) started failing with the error:

```
Could not resolve placeholder 'mail.local.address' in value "${mail.local.address}"
```

**Comment by acarlstein** [comment] 2023-02-21 15:58
I'm getting the same issue with the placeholder, which is weird because another teammate runs the same project, same branch, with everything setup in the exactly same way (same JDK, etc), that she don't have this issue. 

It would be great to have some debug flag to solve this issue at this point because we tried everything and still keeps failing.

**Comment by wilkinsona** [comment] 2023-02-21 16:22
@acarlstein It's not clear from what you've described why you think that this issue is related to your problem. Unless something is adding `String[]` values to the environment, this issue isn't related.

**Comment by acarlstein** [comment] 2023-02-22 03:28
> @acarlstein It's not clear from what you've described why you think that this issue is related to your problem. Unless something is adding `String[]` values to the environment, this issue isn't related.

sorry, wrong issue.
