### ISSUE TITLE
Consider exposing the "defaultProperties" name as public static member of SpringApplication

### ISSUE THREAD

**Issue by brenuart** [spring-projects/spring-boot#11993] opened 2018-02-11 14:54 UTC
Many `EnvironmentPostProcessor` attempt to lookup the "defaultProperties" property source in the environment to insert themselves before/after.
They all make assumption about its name which currently defaults to "defaultProperties" as hardcoded inside the SpringApplication class.

It would be nice if we had a more robust way to locate that property source in the environment.
Possible options are:
- expose a _public static final String_ with the default name ?
- make it a first class citizen like the `CommandLinePropertySource` - we could then look it up by its classname (or its "source name" if it exposes a _public static final_ too)

What do you think ?

**Comment by philwebb** [comment] 2018-02-11 20:53
> Many EnvironmentPostProcessor attempt to lookup the "defaultProperties" property source in the environment to insert themselves before/after.

Are you talking about your own projects, Spring Boot itself or third-party projects? I can't find may direct references to that name in Spring Boot's own codebase.

**Comment by brenuart** [comment] 2018-02-11 22:25
SpringBoot, SpringCloud... and my own projects ;-)
Some examples:
- SpringBoot: [ConfigFileApplicationListener](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/config/ConfigFileApplicationListener.java#L97)
- SpringCloud (Netflix): [ServoEnvironmentPostProcessor](https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/metrics/ServoEnvironmentPostProcessor.java)
- SpringCloud (Sleuth): [TraceEnvironmentPostProcessor](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/autoconfig/TraceEnvironmentPostProcessor.java#L41)

I have seen others but don't remember them - sorry.

**Comment by snicoll** [comment] 2018-02-12 07:18
Duplicate of #3783

**Closed by snicoll** 2018-02-12 07:18 UTC
Labels: status: feedback-provided, status: waiting-for-triage
