### ISSUE TITLE
Unable to set the context-path after upgrading to spring boot 2.1.0

### ISSUE THREAD

**Issue by aarthi-karthick** [spring-projects/spring-boot#15322] opened 2018-11-28 20:29 UTC
In spring 2.0.3 : server.servlet.context-path = /asdf . ---> worked like charm
after upgrading to spring 2.1.0 ---> context-path is not getting set

 Exposing 2 endpoint(s) beneath base path '/actuator'
[main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''

is it a known issue? is there any fix for this?

solutions tried but did not fix the issue:
1. System.setProperty
2. @Bean
  public WebServerFactoryCustomizer<ConfigurableServletWebServerFactory>
      webServerFactoryCustomizer() {
    return factory -> factory.setContextPath("/receipt-creation-service");
  }
3.@Configuration
public class TomcatReactiveWebServerConfig extends TomcatReactiveWebServerFactory {

    private String contextPath="/receipt-creation-service";

    @Override
    protected void configureContext(final Context context) {
        super.configureContext(context);
        if (StringUtils.isNotBlank(this.contextPath)) {
            context.setPath(this.contextPath);
        }
    }
}

**Comment by mbhave** [comment] 2018-11-28 20:40
@aarthi-karthick `server.servlet.context-path` is servlet specific. From your code snippet above, it seems like you might have a webflux application. If that's not the case, please provide a minimal sample application that we can use to reproduce the issue.

**Comment by spring-issuemaster** [comment] 2018-12-05 20:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-12-12 20:45
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-12-12 20:45 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
