### ISSUE TITLE
implicit cast failed on reactive.TomcatHttpHandlerAdapter$TomcatServerHttpRequest

### ISSUE THREAD

**Issue by tutufool** [spring-projects/spring-boot#15489] opened 2018-12-18 15:45 UTC
When upgrade to spring boot 2.1.1, the newly introduced spring-web-5.1.3.RELEASE gives me exceptions:

```
 java.lang.IllegalArgumentException: Can not set org.apache.catalina.connector.Request field org.apache.catalina.connector.RequestFacade.request to org.apache.catalina.core.ApplicationHttpRequest
 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_20]
 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_20]
 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[na:1.8.0_20]
 	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36) ~[na:1.8.0_20]
 	at java.lang.reflect.Field.get(Field.java:387) ~[na:1.8.0_20]
 	at org.springframework.util.ReflectionUtils.getField(ReflectionUtils.java:169) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
 	at org.springframework.http.server.reactive.TomcatHttpHandlerAdapter$TomcatServerHttpRequest.createTomcatHttpHeaders(TomcatHttpHandlerAdapter.java:106) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
 	at org.springframework.http.server.reactive.TomcatHttpHandlerAdapter$TomcatServerHttpRequest.<init>(TomcatHttpHandlerAdapter.java:99) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
 	at org.springframework.http.server.reactive.TomcatHttpHandlerAdapter.createRequest(TomcatHttpHandlerAdapter.java:68) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
 	at org.springframework.http.server.reactive.ServletHttpHandlerAdapter.service(ServletHttpHandlerAdapter.java:171) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.13.jar:9.0.13]
 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.13.jar:9.0.13]
```

related code:

```java
private static HttpHeaders createTomcatHttpHeaders(HttpServletRequest request) {
	org.apache.catalina.connector.Request connectorRequest = (org.apache.catalina.connector.Request)
		ReflectionUtils.getField(COYOTE_REQUEST_FIELD, request);
	Assert.state(connectorRequest != null, "No Tomcat connector request");
	Request tomcatRequest = connectorRequest.getCoyoteRequest();
	TomcatHeadersAdapter headers = new TomcatHeadersAdapter(tomcatRequest.getMimeHeaders());
	return new HttpHeaders(headers);
}
```

The code assuming pass in request is an `org.apache.catalina.connector.RequestFacade`.
But actually it's `org.apache.catalina.core.ApplicationHttpRequest`.

**Comment by bclozel** [comment] 2018-12-18 15:57
This is likely to be a bug in Spring Framework.
Could you provide more information on how to reproduce that? Do you have a sample application I can run?

**Comment by tutufool** [comment] 2018-12-18 17:10
Here you go:
https://github.com/tutufool/ServletOnReactive

**Comment by bclozel** [comment] 2018-12-18 22:17
Thanks for the repro.
I see you're trying to use `org.apache.tomcat.websocket.server.WsFilter` in your application. I've got a couple of comments about that first:

* For websocket support, you should use [what's provided by Spring WebFlux already](https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/web-reactive.html#webflux-websocket)
* In my opinion, it's a bad idea to use Servlet filters on a WebFlux application. Since WebFlux is using the Tomcat container in async IO mode (note: not just async), nothing should read or write to the request/response in a blocking way. Most filters out there won't work.

With that in mind, there might be a problem still in Spring Framework since we shouldn't maybe enforce the total absence of Servlet Filters. Let me get back to you on that.

**Comment by poutsma** [comment] 2018-12-19 11:03
I've created a JIRA for Spring Framework here: https://jira.spring.io/browse/SPR-17611

**Comment by poutsma** [comment] 2018-12-19 11:20
Fixed in https://github.com/spring-projects/spring-framework/commit/5e4a8966eecfa45404e47f2a21a999eebbabb8be

**Comment by wilkinsona** [comment] 2018-12-19 12:56
Thanks, @poutsma. We're building against Framework 5.1.4 snapshots now (as part of #15493) so there's nothing more to do here on the Boot side.

**Closed by wilkinsona** 2018-12-19 12:56 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by tutufool** [comment] 2018-12-24 12:32
@bclozel Thanks for your reminding.

Is there a way to explicitly exclude WsFilter in my case?
I guess WsFilter is default enabled for reactive mode.

However, like I said, my case is special, I have to support both case within same tomcat container:


1. biz logic served via webflux: RestControllers + WebFilters (non-blocking)

2. legacy servlet based admin console: pure servlet + it's own servlet filters (blocking)

#1  and #2 are different request/response processing.
