### ISSUE TITLE
Springboot cache the IP address of the DNS Endpoint forever

### ISSUE THREAD

**Issue by muthu-cs** [spring-projects/spring-boot#19376] opened 2019-12-15 00:08 UTC
When an IP changes in a dns name, the spring applications are continue to send the request to the old IP and taking the new IP address. Even-though java DNS cahce ttl settings are disabled and at the OS level dns resolution is pointing to the new IP. It seems spring boot resolved the dns for the very first time and caching the IP, afterwards it never refreshes.

**Comment by snicoll** [comment] 2019-12-15 00:12
@muthu-cs I am not sure I understood what you mean by "DB Endpoint". Did you mean the `db` health indicator? If so, Spring Boot isn't doing anything more than asking a connection to the connection pool. Can you please clarify what you meant and why do you think this is an issue in Spring Boot?

**Comment by muthu-cs** [comment] 2019-12-15 01:24
@snicoll you can assume any DNS endpoint. We are using Aurora DB cluster endpoints, which is nothing but a route 53/DNS name, when we failover a database, the IP of the DB changes, however the DNS name remains the same. Though at the OS level DNS resolved to the new IP, spring applications continue to connect to the OLD db on the old IP. it seems spring caches the IP during the application bootup and it never resolves the DNS later on. hope that helps.

**Comment by snicoll** [comment] 2019-12-15 02:12
I am afraid it doesn’t. Can you please answer my questions?

**Comment by muthu-cs** [comment] 2019-12-16 02:05
During our test, a vanilla java program trying to access a DNS endpoint always resolves to the latest IP bound to the DNS endpoint. however spring applications resolves to an IP during application boot up time and it never resolves to the latest IP unless we reboot the app server. it seems spring/some spring library which does the DNS resolution caches the IP during initialization and never resolves to DNS or honors the DNS cahce TTL.

**Comment by snicoll** [comment] 2019-12-16 02:32
I am  afraid your already said that and that didn’t answer my questions either. I see no evidence of spring boot being involved in this (vs. the connection pool configuration, that you haven’t shared either). To help us move forward, please share a small sample (zip or github repo) we can run ourselves to reproduce the issue.

**Comment by spring-issuemaster** [comment] 2019-12-23 02:36
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by muthu-cs** [comment] 2019-12-23 04:35
Sure Will provide the sample program to re-produce tomorrow.

**Comment by spring-issuemaster** [comment] 2020-01-06 07:56
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-01-06 07:56 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage

**Comment by jaswindervirk** [comment] 2020-01-29 13:01
we recently upgraded our spring webflux application to 2.1.10 and are facing this issue. We are using route 53 for some microsevice but when that service shift their load to failover we are still hitting their old ip. It seems spring somehow caches the old ip at the time when application starts.
Possible solution - 1. reboot your application 
                                2. While making TCP connection set keepAlive false to make new HTTP connection every time

**Comment by wilkinsona** [comment] 2020-01-29 13:11
@jaswindervirk If making a new connection every time fixes the problem, it does not sound like a DNS caching problem. If it were, requiring a new connection every time would not help as the new connection would attempt to connect to the old IP address. It sounds to me like a kept-alive connection is not being closed when you attempt to shift the load. Reuse of that connection will then result in requests being sent to the old IP address.

**Comment by njssferreira** [comment] 2020-05-15 15:24
> During our test, a vanilla java program trying to access a DNS endpoint always resolves to the latest IP bound to the DNS endpoint. however spring applications resolves to an IP during application boot up time and it never resolves to the latest IP unless we reboot the app server. it seems spring/some spring library which does the DNS resolution caches the IP during initialization and never resolves to DNS or honors the DNS cahce TTL.

Hey, did you manage to solve this issue? I'm facing exactly the same issue...

**Comment by jemmy-dangi12** [comment] 2021-03-31 11:44
Facing the Exact Same issue. Please let us know how did you resolve it

**Comment by smithapitla** [comment] 2021-07-13 17:42
We are facing same issue. Please let us know how to resolve this.

**Comment by YuLimin** [comment] 2021-11-10 14:46
Please provide the sample project for re-produce this issue then analyze what's the root cause.

**Comment by agaddamu** [comment] 2021-11-16 22:43
Experiencing the same issue. Traffic toggle isn't being honored. Old IP address is being cached. 

Scenario
---------
East and West regions
East region - blue and green stacks
West Region - blue and green stacks
Active Stacks : Blue
Inactive Stacks : Green

Deployment Action
---------------------
Toggled 100% traffic from Blue to Green and observed traffic sticking to the Blue stacks. 

Remediation
-------------
1. Toggled 100% traffic to Single Region (East) and brought down the traffic to 0% on WEST
2. Waited for 5 mins
3. Toggled traffic back to both regions and did not observe sticky ip addresses on WEST
4. Repeated the same for EAST.

Any guidance on the internals of Spring WebClient

**Comment by rstoyanchev** [comment] 2021-11-17 09:31
By WebClient internals, you mean the underlying HTTP client. By default, this is Reactor Netty. Please check the section on [host name resolution](https://projectreactor.io/docs/netty/release/reference/index.html#_host_name_resolution) and the available settings for caching and eviction.

**Comment by wilkinsona** [comment] 2021-11-17 09:33
Thanks, @rstoyanchev!

**Comment by praveenchandran** [comment] 2022-09-13 15:09
Maybe this could help someone stumbling upon this ticket. The issue could be related to default ttl of JVM DNS cache. It is set to Forever (-1) by default. You can set the cache TTL in your `jre/lib/security/java.security` file as follows :
networkaddress.cache.ttl=60
networkaddress.cache.negative.ttl=60

PS: Setting the value too low could introduce latencies and increase the number of DNS lookups in your application.
Ref: https://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html

**Comment by ikorchynskyi** [comment] 2023-04-19 07:24
This may be the keep-alive issue. I had a similar problem with `RestTemplate`, and seems that the final fix is to add `Connection: close` header to requests to the other microservices.

**Comment by banandh** [comment] 2023-11-02 17:32
We are also facing the same issue. In UAT we dont have option to update JVM security so we were updating the values via command line and system.setProperty but thats not helping us. We are again ended up the IP address caching issue. Need to understand what is going wrong. Also how to verify if the DNS cache flush out happens properly?
