### ISSUE TITLE
can not clone project ,Filename too long

### ISSUE THREAD

**Issue by wubohai** [spring-projects/spring-boot#10953] opened 2017-11-08 08:18 UTC
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/DependencyManagementPluginActionIntegrationTests-helpfulErrorWhenVersionlessDependencyFailsToResolve.gradle: Filename too long

**Comment by wilkinsona** [comment] 2017-11-08 09:39
I assume you are on Windows. This works fine for me on Windows 7 and for others on Windows 10. You may need to clone the project into a directory nearer your drive’s root or use a different Git client.

**Comment by spring-issuemaster** [comment] 2017-11-15 09:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2017-11-22 09:43
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2017-11-22 09:43 UTC

**Comment by lukaseder** [comment] 2018-01-02 11:00
I've created a duplicate (#11465) of this issue. I don't agree with the comment: https://github.com/spring-projects/spring-boot/issues/10953#issuecomment-342762828

I can reproduce this problem when checking out spring boot into a path that isn't too far from the root path:

```
lukas@DESKTOP-M9T2LD4 MINGW64 ~/workspace/dummy
$ pwd
/c/Users/lukas/workspace/dummy

lukas@DESKTOP-M9T2LD4 MINGW64 ~/workspace/dummy
$ git clone https://github.com/lukaseder/spring-boot
```

The only other applications that I remember running into this problem in the past were created by IBM (Things only worked when putting stuff in `C:\Temp`). In this particular case, there really isn't too much value in having such long file names for those few gradle tests...

**Comment by wilkinsona** [comment] 2018-01-02 11:54
> there really isn't too much value in having such long file names for those few gradle tests...

I see quite a lot of value in having a convention for mapping a test method to the gradle script that the method will run. I also see quite a lot of value in test method names being descriptive. Perhaps you have a suggestion for retaining this value while also coping with Windows' filename limitations?

**Comment by lukaseder** [comment] 2018-01-02 12:23
Some ideas:

- JavaPluginActionIntegrationTests is verbose and not really necessarily so. Most of it should be clear from the path:
  - plugin is already in the package name
  - action is not adding meaningful information (I think)
  - integrationtests ... well, guess what I'd expect inside of a src/test directory? :)

Then again, there are only 5 errors, currently. Perhaps, we could live with an exception on the naming of these files (and add an integration test for Windows)?

**Comment by wilkinsona** [comment] 2018-01-02 12:35
`JavaPluginAction` contains integration tests for the `JavaPluginAction` class (an `Action` implementation that reacts to Gradle's `JavaPlugin` being applied). Thanks for the suggesting, but dropping any or all of `Plugin`, `Action` or `IntegrationTests` will lose information, deviate from the project's naming conventions, or both.

We already have a Windows CI job and it's [quite happy](https://build.spring.io/browse/BOOT-WIN-1087) with the current path lengths. FWIW, it clones the repository into ` C:\opt\bamboo-home\xml-data\build-dir\BOOT-WIN-JOB1`.

**Comment by lukaseder** [comment] 2018-01-02 12:41
> Thanks for the suggestion, but dropping any or all of Plugin, Action or IntegrationTests will lose information, deviate from the project's naming conventions, or both.

I won't further discuss actual naming suggestions, that's not going to be fruitful. I just noticed this problem, which obviously others seem to have reported as well. You can reject the issue as "won't fix" if you don't think the problem is relevant.

Having worked with Oracle for ages (30 character identifier limit!), made me overly pragmatic over the years, so it might just be a matter of different prioritites.

> FWIW, it clones the repository into C:\opt\bamboo-home\xml-data\build-dir\BOOT-WIN-JOB1.

My error message interpretation was wrong. It's not the path that gets too long in this case, but the file name.
