### ISSUE TITLE
Consider adding gzip content encoding support for requests

### ISSUE THREAD

**Issue by izeye** [spring-projects/spring-boot#13269] opened 2018-05-26 06:13 UTC
It would be nice to add gzip content encoding support for requests.

I created a sample project which shows what needs to be done for now: https://github.com/izeye/spring-boot-throwaway-branches/commit/012808ba48943daf38fcffb8f529eb41cd6331ae

**Comment by wilkinsona** [comment] 2018-05-26 06:52
Duplicate of #11827.

**Closed by wilkinsona** 2018-05-26 06:52 UTC
Labels: status: waiting-for-triage
