### ISSUE TITLE
Concurrent modification exception with Undertow

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#3239] opened 2015-06-15 16:48 UTC
Reported in [SPR-13123](https://jira.spring.io/browse/SPR-13123) but could be our issue. Perhaps Undertow allows requests to be processed too early (like Tomcat used to).

**Comment by ceefour** [comment] 2015-06-18 14:49
The error happens when I access the app the first time over a browser. So indeed I'd expect the web server to wait the app initialization to finish before passing the request.

Note that Apache Wicket (6.19.0) is implemented as a Filter (using FilterRegistrationBean), not a Servlet, which may or may not contribute to the problem. What's clear is that the first time app is started, Wicket itself is not yet started. Only after the first request, it passes through the WicketFilter and then Wicket starts itself up. However as I said this problem happened only once and I have been unable to reproduce this ever again.

**Comment by sreekanthsnair** [comment] 2015-06-24 10:09
+1

**Comment by wilkinsona** [comment] 2015-06-24 15:08
@sreekanthsnair Does your +1 indicate that you've also had this problem? If so, is it reproducible? @ceefour has only seen it once and having steps to reproduce it would make diagnosing it much easier.

**Comment by sreekanthsnair** [comment] 2015-06-24 15:14
@wilkinsona Yes i'm also experiencing the same issue and no its not reproducible since experiencing it less frequently. Reported the same at http://stackoverflow.com/questions/30974440

**Comment by wilkinsona** [comment] 2015-06-24 15:18
Thanks. Looking at the question on StackOverflow, it doesn't look like you're using Spring Boot. In other words, it would appear that this is a general problem with Undertow rather than one that's specific to how we're using it in Spring Boot.

**Comment by sreekanthsnair** [comment] 2015-06-24 15:26
No i'm not using spring boot. May be its a problem with undertow but there is no clue in the error log where i can put a discussion with undertow team :) .

**Comment by wilkinsona** [comment] 2015-06-24 15:29
Spring Boot's issue tracker certainly isn't the right place to have a discussion with the Undertow team. You might want to report the problem on [their JIRA](https://issues.jboss.org/browse/UNDERTOW).

**Comment by sreekanthsnair** [comment] 2015-06-24 15:34
As i have mentioned there is nothing in that error log, where i can point its an undertow issue. Anyway let me start a discussion in jboss discussion forum. Thanks

**Comment by wilkinsona** [comment] 2015-06-24 15:50
I can't see how this can happen with embedded Undertow. Undertow doesn't start listening until it's started and we don't start Undertow until `finishRefresh` after all of the standard processing has been performed.

@ceefour Are you using embedded Undertow, or are you deploying to a standalone Undertow/Wildfly server?

**Comment by wilkinsona** [comment] 2015-06-24 15:52
@sreekanthsnair The stack trace in your post on StackOverflow suggests that Wildfly is passing a request to a web application that is still being initialized. I believe that's a bug.

**Comment by ceefour** [comment] 2015-06-24 15:52
Embedded Undertow, the version given by spring boot undertow 1.2.3 dependency.

**Comment by snicoll** [comment] 2015-08-26 08:32
We can't reproduce this issue so we moved this to the general backlog. Could you please provide us a  way to reproduce it (even sporadically)

**Comment by ceefour** [comment] 2015-08-26 08:42
@snicoll sorry, you can just close this anyway. Since I also never got this issue again now. But at least I know it's undertow. So maybe when an issue happens again I can just report to Undertow instead.

**Closed** 2015-08-26 09:52 UTC
Labels: waiting-for-feedback
