### ISSUE TITLE
Allow easy configuration of JMS pool properties

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-boot#1598] opened 2014-09-23 06:32 UTC
ActiveMQ has several properties to allow to tune the pool. Like `maximumActiveSessionPerConnection`, `maxConnections`, `idleTimeout` and `expiryTimeout`. It would be nice if there would be `spring.jms.*` properties available to set them. Preferably in a generic fashion so that they could be applied to the HornetQ implemenation (if applicable).

`spring.jms.activemq.max-connections` for `maxConnections`
`spring.jms.activemq.max-sessions-per-connection ` for `maximumActiveSessionPerConnection`
`spring.jms.activemq.time-between-eviction-runs-millis` for `timeBetweenExpirationCheckMillis`
`spring.jms.activemq.min-evictable-idle-time-millis`  for `idleTimeout`
`spring.jms.activemq.expiry-time-milles` for `expiryTimeout`

Not sure if some of these would apply to HornetQ as well.

**Comment by snicoll** [comment] 2015-06-08 13:48
I don't think the generic piece is a good idea. Now we have content assistance support, being explicit is a better idea. PR welcome.

**Comment by herau** [comment] 2016-03-09 14:02
@snicoll Does this kind of properties can be add to [ActiveMQProperties](https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/activemq/ActiveMQProperties.java) ? Does this issue is still opened to contribution or it's outdated ?

**Comment by snicoll** [comment] 2016-03-09 14:13
I guess but not in that current form: I don't like dumping a bunch of properties in the root namespace for a given library. `spring.jms.activemq.connectionfactory` is the first that comes to mind (and there is a precedent) though I don't like the two words.

The issue is open and ideal for contribution so no, it's not outdated ;)

**Comment by herau** [comment] 2016-03-09 14:17
Ok i will do a proposal for this issue.

**Comment by herau** [comment] 2016-03-10 12:01
@snicoll i made a proposal for this issue: #5372

**Comment by snicoll** [comment] 2016-03-18 09:03
Closing in favour of the PR #5372

**Closed by snicoll** 2016-03-18 09:03 UTC
Labels: duplicate
