### ISSUE TITLE
How to propagate context with trace-id in CommandLineRunner with spring boot 3 and micrometer?

### ISSUE THREAD

**Issue by MarcelEdmundFranke** [spring-projects/spring-boot#34449] opened 2023-03-02 15:20 UTC
After migration to spring boot 3 and micrometer tracing library. The tracing IDs aren't automatically appended to the logs anymore for Classes which implement the CommandLineRunner interface unlike for rest controllers.

Example code
```
@Component
@Slf4j
@RequiredArgsConstructor
public class JobRunner implements CommandLineRunner {

    private final petsJobExecutor petsJobExecutor;

    @TrackExecutionTime
    public void run(String... args) {
        log.info("Started the job");
        petsJobExecutor.updatePets();
        log.info("Finished the job");
    }
}
```

How can I enable automatic trace-id context propagation for CommandLineRunner implementations in sprint boot 3 with micrometer?

**Comment by wilkinsona** [comment] 2023-03-02 17:39
Is the trace ID missing from the two info log calls in the command line runner itself or from logging that's happening within `updatePets()`? If it's the latter, it's very hard to offer any specific guidance as we don't know what `petsJobExecutor` is or how it has been implemented. Perhaps [this Micrometer Tracing documentation](https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide#instrumentations) helps? If it does not and you'd like further assistance, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by MarcelEdmundFranke** [comment] 2023-03-02 18:17
> Is the trace ID missing from the two info log calls in the command line runner itself or from logging that's happening within updatePets()? 

Both cases, it's missing  from the two info log calls and withn the update pets.

**Comment by MarcelEdmundFranke** [comment] 2023-03-02 18:30
@wilkinsona petsJobExecutor is service Component

```
@Service
@ToString
@RequiredArgsConstructor
public class petsJobExecutor {
```

**Comment by MarcelEdmundFranke** [comment] 2023-03-02 18:35
@wilkinsona Do you still need more source code?

**Comment by wilkinsona** [comment] 2023-03-02 19:42
Yes, please. Without knowing how you've configured JobRunner and its threading, it's impossible for us to tell what's supposed to be happening. `@TrackExecutionTime` is also unknown to us – it isn't part of Spring Boot or Micrometer – so there's no way for us to know if there should even be a trace ID available.

**Comment by wilkinsona** [comment] 2023-03-02 19:47
I see you've [also posted about this on Gitter](https://matrix.to/#/!poRJqCihtKxXkqtIDZ:gitter.im/$aEg6ka9xSGdHKKjCAd9s8cQIVR27vNOpeae2zQ4HI2U?via=gitter.im&via=matrix.org&via=hive-mind.network). Unfortunately, cross-posting like this wastes people's time as @bclozel and I have now duplicated effort. That's time that we could have spent helping you or someone else.

I'm going to close this in favor of the Gitter discussion. We can re-open this if it turns out that some changes in Boot are required.

**Closed by wilkinsona** 2023-03-02 19:47 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, theme: observability

**Comment by MarcelEdmundFranke** [comment] 2023-03-03 14:29
@wilkinsona solved it. Micrometer acts not like sleuth lib 

Fix 

```
@Component
@Slf4j
@RequiredArgsConstructor
@Profile("!test")
public class JobRunner implements CommandLineRunner {

    @Autowired
    private final Tracer tracer;

    @Autowired
    private final ObservationRegistry observationRegistry;

    @Autowired
    private final petsJobExecutor petsJobExecutor;

    @TrackExecutionTime
    public void run(String... args) {
        Observation.createNotStarted("ing-loan-job", observationRegistry).observe(() -> {
            log.info("Started the job");
            petsJobExecutor.petsLoans();
            log.info("Finished the job");
        });
    }
}
```

**Comment by MarcelEdmundFranke** [comment] 2023-03-06 10:27
@wilkinsona Thanks for you support! :)
