### ISSUE TITLE
A java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy was thrown when killing my app

### ISSUE THREAD

**Issue by caipanjin** [spring-projects/spring-boot#4968] opened 2016-01-19 03:38 UTC
“kill pid” to stop my app throws the exception as below：

Exception in thread "Thread-7" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:121)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
        at ch.qos.logback.classic.Logger.log(Logger.java:788)
        at org.apache.commons.logging.impl.SLF4JLocationAwareLog.warn(SLF4JLocationAwareLog.java:192)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:978)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:901)

**Comment by snicoll** [comment] 2016-01-19 08:07
It looks like logback has been shutdown when the context needs to log something. Could you please describe what you're doing in more details. At the very minimum the Spring Boot version that you are using and the dependencies you're using. It is always better to provide a sample project that reproduces the issue.

**Comment by caipanjin** [comment] 2016-01-19 08:24
@snicoll I use version 1.3.1.RELEASE, it seems when I shutdown my app, the method doClose in AbstractApplicationContext catching an exception and try to print a log (line:978):

protected void doClose() {
		if (this.active.get() && this.closed.compareAndSet(false, true)) {
			if (logger.isInfoEnabled()) {
				logger.info("Closing " + this);
			}

			LiveBeansView.unregisterApplicationContext(this);

			try {
				// Publish shutdown event.
				publishEvent(new ContextClosedEvent(this));
			}
			catch (Throwable ex) {
				logger.warn("Exception thrown from ApplicationListener handling ContextClosedEvent", ex);
			}

			// Stop all Lifecycle beans, to avoid delays during individual destruction.
			try {
				getLifecycleProcessor().onClose();
			}
			catch (Throwable ex) {
line:978				logger.warn("Exception thrown from LifecycleProcessor on context close", ex);
			}

**Comment by snicoll** [comment] 2016-01-19 08:46
>  it seems when I shutdown my app,

The whole point I am trying to make is that mine doesn't so please help us out by providing a way for us to reproduce the problem.

**Comment by caipanjin** [comment] 2016-01-19 09:48
@snicoll sorry about that.My app uses lots of other frameworks. I am trying to remove them and found if I can  reproduce the problem.

**Comment by spring-issuemaster** [comment] 2016-01-26 10:50
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-02-02 10:50
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-02-02 10:50 UTC

**Comment by manishpatelUK** [comment] 2018-01-20 15:41
I'm getting the same intermittently when I try and call the shutdown actuator endpoint. Oddly, I never get it when I do a curl call from the command line. However if I do the same via an ANT script (bash -c ...) from a remote Jenkins server, 1 out of 3 times I see this guy pop up. Incidentally, the shutdown never seems to work in this case either.

**Comment by hurelhuyag** [comment] 2019-06-20 05:18
Similar exception happening here. But I'm not killing or touching my app. It's just happening frequently.
`Exception in thread "http-nio-8083-exec-2" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy`

**Comment by philwebb** [comment] 2019-06-20 05:53
@hurelhuyag If you have a consistent way to reproduce the issue, please provide a sample here that we can run and debug.
