### ISSUE TITLE
Document server.servlet.encoding.* properties and server.servlet.encoding.mapping in particular

### ISSUE THREAD

**Issue by Dmitrii-Iakovenko** [spring-projects/spring-boot#32472] opened 2022-09-22 00:03 UTC
Spring Boot 2.7.3

1) Spring MVC + Mustache = UTF-8 not working 
2) Add CharacterEncodingFilter = UTF-8 works
3) Add Spring Security + config Mustache = UTF-8 display works, sending - no
4) Change CharacterEncodingFilter to OrderedCharacterEncodingFilter = UTF-8 works

[Repository](https://github.com/Dmitrii-Iakovenko/spring-utf8) demonstrating the issue + commit history.

Old similar problem - https://github.com/spring-projects/spring-boot/issues/3912

**Comment by wilkinsona** [comment] 2022-09-22 08:52
Thanks for the sample. Unfortunately, I've been unable to reproduce the problem using the first commit in the repository. If I disable the auto-configuration of the `OrderedCharacterEncodingFilter` by setting `server.servlet.encoding.enabled=false`, UTF-8 submitted by the form is corrupted while UTF-8 served directly from the mustache template remains correct.

I am on macOS which uses UTF-8 by default, but configuring the JVM to use US-ASCII (verified using `Charset.getDefaultCharset()`) makes no difference to the behaviour. What do I need to do so that the provided sample will reproduce the problem?

**Comment by spring-projects-issues** [comment] 2022-09-29 08:55
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by lksh5737** [comment] 2022-10-05 11:04
2.7.x mustache utf-8 = not working
server.servlet.encoding.force = true or 2.6.x downgrade  = working

**Comment by wilkinsona** [comment] 2022-10-05 11:41
@lksh5737 As I [described above](https://github.com/spring-projects/spring-boot/issues/32472?notification_referrer_id=NT_kwDOAA30-rE0NDUwNTc5MzA2OjkxNDY4Mg#issuecomment-1254723662), that doesn't match the behavior that I have observed. If you or @Dmitrii-Iakovenko can provide a sample that shows the problem, we can take another look.

**Comment by lksh5737** [comment] 2022-10-06 07:26
@wilkinsona https://github.com/lksh5737/mustache_utf8_sample.git

**Comment by lksh5737** [comment] 2022-10-06 08:31
@wilkinsona i am using windows 10

**Comment by lksh5737** [comment] 2022-10-06 09:16
I don't know the difference

**Comment by lksh5737** [comment] 2022-10-06 11:42
Can you tell me how?
I solved it using server.servlet.encoding.force = true

**Comment by wilkinsona** [comment] 2022-10-06 11:59
It hard to offer specific guidance as we don't know where the problem is. I would step through the code using your IDE's debugger to try to identify the point at which the UTF-8 characters are corrupted. The rendering of the `MustacheView` that's done in `renderMergedTemplateModel(Map<String, Object>, HttpServletRequest, HttpServletResponse)` may be a good place to start.

**Comment by spring-projects-issues** [comment] 2022-10-13 12:00
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-10-20 12:00
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by swhyeon98** [comment] 2023-07-15 08:13
https://github.com/swhyeon98/web-services-implemented-by-yourself-with-spring-boot-and-aws.git
By any chance, you can't find any errors in the above sample either?

There are two solutions for this issue.

you can add the following tags to the application.properties file:
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

Alternatively, you could downgrade your Spring Boot version to 2.6.

Both of these methods have resolved the issue.
![sol2](https://github.com/spring-projects/spring-boot/assets/77083527/f847d46c-ba30-4db5-93b0-853771634936)
![sol1](https://github.com/spring-projects/spring-boot/assets/77083527/71639362-6ac4-4cff-99c3-c8682e60c7be)
![error2](https://github.com/spring-projects/spring-boot/assets/77083527/bdf02212-7312-4936-8d53-d02546d8a3a6)
![error1](https://github.com/spring-projects/spring-boot/assets/77083527/6cc93557-6a13-4e8b-bf07-826687824b31)
<img width="1440" alt="Untitled" src="https://github.com/spring-projects/spring-boot/assets/77083527/ccdcf728-6c70-4a02-ab61-157b62475f2e">

**Comment by wilkinsona** [comment] 2023-07-18 08:56
@swhyeon98 Unfortunately, I cannot reproduce the problem with your sample either. I've tried on macOS using its default encoding (`UTF-8`) and also configured to use `windows-1252` (`-Dfile.encoding=cp1252`). In both cases the UTF-8 text is returned:

```
$ curl -i localhost:8080
HTTP/1.1 200 
Content-Type: text/html;charset=UTF-8
Content-Language: en-GB
Content-Length: 239
Date: Tue, 18 Jul 2023 08:55:30 GMT

<!DOCTYPE HTML>
<html>
<head>
    <title>스프링 부트 웹서비스</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
<h1>스프링 부트로 시작하는 웹 서비스</h1>
</body>
</html>
```

**Comment by swhyeon98** [comment] 2023-07-20 08:26
@wilkinsona 
Thank you for your answer.
May I ask a few more questions?

1. did you use the IDE in your testing?
2. Could it be a problem with the IDE?
3. If you used an IDE, which IDE did you use? (I used IntelliJ.)
4. If you used an IDE, could a plug-in have affected the results?

**Comment by wilkinsona** [comment] 2023-07-20 08:49
I ran it in Eclipse and on the command line. On the command line, I built the jar and then ran it using `java -jar`. The results were the same in both cases, both with and without `file.encoding=cp1252`. I've just tried it in IntelliJ, again with and without `file.encoding=cp1252`, and the problem did not occur.

**Comment by swhyeon98** [comment] 2023-07-23 06:42
@wilkinsona Thank you very much.

I will try to find the difference between you and me and the cause (java version, etc.).

If I find the cause, can I comment again then?

**Comment by swhyeon98** [comment] 2023-08-20 14:07
I could not find any difference between you and me, but I think I found the cause of the problem.

When I checked in developer mode - network, I saw that Content-Tpye shows ISO-8859-1.
![Content-Type](https://github.com/spring-projects/spring-boot/assets/77083527/b0ea0a44-f6e5-439e-a913-6a56f96deadc)

So I checked the ViewResolver on Mustache's end,
The result of the check
![mustache_config](https://github.com/spring-projects/spring-boot/assets/77083527/83cd2242-efcd-43f3-a45f-566b356ef388)

if (mustache.getServlet().getContentType() ! = null) {
			resolver.setContentType(mustache.getServlet().getContentType().toString());
		{ }
It seems to occur because the above code only sends up to text/html on the ViewResolver side.
![mustache_getContentType](https://github.com/spring-projects/spring-boot/assets/77083527/6d009118-d8cd-4cb1-93d3-a77a94c2a34e)

You can check this part in my previous sample.

How do you see the output when you check developer mode - network?

**Comment by wilkinsona** [comment] 2023-08-31 10:58
> How do you see the output when you check developer mode - network?

It's the same as it was with `curl`: `text/html;charset=UTF-8`

Looking at the headers in your request that's receiving an `ISO-8859-1` response led me to try sending a request with an `Accept-Language` header. By default in Chrome, the header's value is `en-GB,en-US;q=0.9,en;q=0.8` for me and `curl` doesn't send one at all by default. If I send the same header as your browser, I can reproduce the problem:

```
$ curl -i localhost:8080 -H "Accept-Language: ko-KR,ko;q=0.9"
HTTP/1.1 200 
Content-Type: text/html;charset=ISO-8859-1
Content-Language: ko-KR
Content-Length: 193
Date: Thu, 31 Aug 2023 10:54:47 GMT

<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>??? ?? ????</title>
</head>
<body>
<h1>??? ??? ???? ? ???</h1>
</body>
</html>
```

I'm not yet sure why it has the effect that it does, but it gives me something to investigate.

**Comment by wilkinsona** [comment] 2023-08-31 11:45
The problem is due to Tomcat's mapping of locale's to charsets.

Without an `Accept-Language` header, the default locale is used. On my machine this is `en_GB` which is mapped to `UTF-8`. With an `Accept-Language` header of `Accept-Language: ko-KR,ko;q=0.9` the locale is `ko_KR`. Tomcat has no charset mapping for this locale. This results in the default character encoding being used and the Servlet spec states that this is `ISO-8859-1`.

Tomcat provides a flag that can be used to disable its enforcement of the default character encoding but it doesn't really help. Not with `curl` at least. With the `org.apache.catalina.connector.Response.ENFORCE_ENCODING_IN_GET_WRITER` system property set to `false`, the `Content-Type` changes to omit the charset, but the UTF-8 characters are still corrupted:

```
curl -i localhost:8080 -H "Accept-Language: ko-KR,ko;q=0.9"
HTTP/1.1 200 
Content-Type: text/html
Content-Language: ko-KR
Content-Length: 193
Date: Thu, 31 Aug 2023 11:24:59 GMT

<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>??? ?? ????</title>
</head>
<body>
<h1>??? ??? ???? ? ???</h1>
</body>
</html>
```

Instead, the problem can be addressed by mapping the `ko` locale to `UTF-8`:

```
server.servlet.encoding.mapping.ko=UTF-8
```

This property is equivalent to the `<locale-encoding-mapping-list>` entry in `web.xml`.

Without this custom mapping, the same problem occurs with Jetty as it defaults to `ISO-8859-1` as required by the servlet spec. Interestingly, it does not occur with Undertow which uses `UTF-8` regardless.

While `server.servlet.enocing.mapping` is listed in the configuration properties appendix, it isn't mentioned anywhere in the rest of the reference documentation as far as I can tell. I think we should use this issue to correct that.

**Closed** 2023-10-25 13:41 UTC
Labels: type: documentation
