### ISSUE TITLE
Increase visibility of the 'logger' provided by SpringBootCondition 

### ISSUE THREAD

**Issue by olegz** [spring-projects/spring-boot#9999] opened 2017-08-11 14:26 UTC
A new logger instance is required whenever one implements new condition where internal logging may be helpful, thus resulting in two loggers per instance of the condition. Suggesting to increase  the visibility of the logger provided by  ```SpringBootCondition```

**Comment by wilkinsona** [comment] 2017-08-11 14:31
Duplicate of #10000

**Closed by wilkinsona** 2017-08-11 14:31 UTC
Labels: status: waiting-for-triage
