### ISSUE TITLE
ErrorPageFilter removes Content-Length header for responses without entity

### ISSUE THREAD

**Issue by 0x4a616e** [spring-projects/spring-boot#14086] opened 2018-08-17 07:56 UTC
When the `ErrorPageFilter` is registered, it flushes the response buffer in the `doFilter` method. When no content was added to the response (something like `Response.ok().build()`), this changes the headers sent to the client. Instead of a `Content-Length` Header (wich would have been set by `org.apache.catalina.connector.OutputBuffer` otherwise), a `Transfer-Encoding` header is  sent.

With `ErrorPageFilter`:
    < HTTP/1.1 200 OK
    < Server: Apache-Coyote/1.1
    < Transfer-Encoding: chunked
   < Date: Fri, 17 Aug 2018 07:05:39 GMT

Without `ErrorPageFilter`:
    < HTTP/1.1 200 OK
    < Server: Apache-Coyote/1.1
    < Content-Length: 0
    < Date: Fri, 17 Aug 2018 07:20:47 GMT

**Comment by bclozel** [comment] 2018-08-17 08:13
You're describing implementation details but not the actual issue. Both responses are valid HTTP messages, right? HTTP clients should support both content-length and chunked encodings.

Besides the behavior difference, could you explain what the problem is?

Thanks!

**Comment by 0x4a616e** [comment] 2018-08-17 09:39
You are right, both should be correct HTTP messages and I am also not sure if this is actually a bug. This however lead to subtile behaviour differences with other HTTP client libraries (OkHttp in this case) that returned a content length of -1 for the empty chunked transfer encoding with ErrorPageFilter and a content length of 0 (obviously) without the ErrorPageFilter. Due to a bug in yet another lib, this lead to an exception which is why I noticed this in the first place.

So yeah, this might not be an issue with spring boot after all and you might as well just close this. On the other hand, I was wondering if this really is the intended behaviour as the payload body size is known and thus a content-length header could (or maybe even should) be sent.

**Comment by bclozel** [comment] 2018-08-20 09:03
Sorry about that inconsistency, but looking at our codebase, we're just using `ServletHttpResponse.sendError`, which is the correct call here to trigger the error page case in Servlet container. I think that the Servlet container (in this case) just clears the buffer and does not set the Content-Length header since it doesn't know how much was written up to that point.

From a Spring Boot point of view, I don't think we can improve this situation without breaking other error cases - so I'm closing this issue now. Thanks for the report and feel free to reopen this if you think about a possible solution to that.

**Closed by bclozel** 2018-08-20 09:03 UTC
Labels: status: feedback-provided, status: waiting-for-triage
