### ISSUE TITLE
The error page did not work in Spring boot project

### ISSUE THREAD

**Issue by 7000014349** [spring-projects/spring-boot#15287] opened 2018-11-26 07:42 UTC
I define the error page in the directory `:resources/static/error/404.html`
In local environment ,it worked
But After I publish my source to the server side,it did not work
In the server side,I use the external tomcat,use maven cmd to genarate the "war"
The request url in https://contractdev.azurewebsites.net/menu/init12345
The page is the blank :    
![blank](https://user-images.githubusercontent.com/37426005/49361448-07aeba00-f717-11e8-82ab-21a4c8cc77b8.JPG)

The detail information of the page:
![capture](https://user-images.githubusercontent.com/37426005/49361145-3aa47e00-f716-11e8-8987-5c07089ec5d1.JPG)
And in the log ,there are following information:
org.springframework.boot.web.support.ErrorPageFilter | Cannot forward to error page for request [/matterInfoManger/generalInit1234] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
The local environment:
http://localhost:9011/menu/init12345
The error page is the page that I define
![image](https://user-images.githubusercontent.com/37426005/49361270-8525fa80-f716-11e8-8e09-79d98a662f16.png)

What is the reason and How to solve it

**Comment by wilkinsona** [comment] 2018-11-26 08:03
Sorry, but we can't tell what's causing the problem without some more information. If you'd like us to spend some time investigating, please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2018-12-03 08:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by 7000014349** [comment] 2018-12-04 06:12
I have added more detailed information.
If someone know the reason and solution,Please add the comment
,I would appreciate it

**Comment by wilkinsona** [comment] 2018-12-04 07:52
Thanks, but that’s not really what we’re looking for. Something is committing the response to early, but it’s impossible to tell what that is from the information you have provided. As I said above, if you would like us to spend more time trying to help you please take the time to provide a complete minimal sample (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by wilkinsona** [comment] 2019-01-12 12:10
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by wilkinsona** 2019-01-12 12:10 UTC
Labels: status: feedback-reminder, status: waiting-for-triage
