### ISSUE TITLE
Investigate "Failed to create volume" CI issues

### ISSUE THREAD

**Issue by dreis2211** [spring-projects/spring-boot#19931] opened 2020-01-26 10:06 UTC
Hi,

since yesterday the amount of "failed to create volume" errors seems to be on a level that "forces" me into this issue:
![image](https://user-images.githubusercontent.com/6304496/73133458-25c92f00-4029-11ea-9f74-b3b2e7250d90.png)

I wonder if there's anything from the Spring-Boot perspective that we can do to investigate what's going on as long as https://github.com/concourse/concourse/issues/800 remains unresolved.

Maybe we can put some "debug" commands to the build pipeline scripts. E.g. `lsof | wc -l` to show open files; displaying `ulimit`s;  some Docker diagnostics like `docker system df`. Etc.

Feel free to close this issue of course, in case you already know what's going on. But I thought it might be worth to track the findings in a centralized place.

Cheers,
Christoph

**Comment by wilkinsona** [comment] 2020-01-26 11:33
I'm sure this is frustrating for you, @dreis2211. Thank you for raising it in such a constructive manner.

Unfortunately, based on my (rather superficial) understanding of how Concourse works, I don't think the diagnostics that we add to an individual task will help. I believe the failure is occurring outside of that task and outside of the container in which it's running. We've escalated the problem with the Concourse team so hopefully we'll get some guidance soon on what we can do to diagnose the cause.

Given the timing of the volume creation failure – once a task appears to have completed – my theory at the moment is that the failure is occurring when Concourse is attempting to honour the task's cache configuration. We use this configuration to share the local Maven and Gradle caches between runs. This caching is task and worker-specific, i.e. we end up with a volume per task and per worker. This theory is backed up a little bit by things improving when we recreated all of the workers. New workers results in fresh caches for each of the new workers.

I'd like to further test my theory by deleting the `task-cache` volumes but [there's no way for me to do that](https://github.com/concourse/concourse/issues/1038) right now. We can perhaps take the more severe option of asking for all of the workers to be recreated. Another option would be to disable the task caching. That will have a negative impact on build times, but that may well be better than the current situation.

**Comment by wilkinsona** [comment] 2020-01-30 14:49
The workers were recreated over the weekend. It seems to have improved the situation a little, but volume creation failures are still occurring with 3 in [build](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.3.x/jobs/build) and 1 in [build-pull-requests](https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-2.3.x/jobs/build-pull-requests) so far today.

We're continuing to work with the Concourse team to get to the bottom of the problem.

**Comment by dreis2211** [comment] 2020-01-30 15:37
Thanks for the heads-up. I really think https://github.com/concourse/concourse/issues/800 could help here.

**Comment by dreis2211** [comment] 2020-02-20 11:30
I don't want to jinx it, but it seems that on the current master this is happening less frequent now. Did anything change, @wilkinsona ? I suspected my PR #20157 , but there were failures afterwards.

**Comment by dreis2211** [comment] 2020-02-20 16:32
I jinxed it 😆 https://ci.spring.io/builds/107398

**Comment by wilkinsona** [comment] 2020-02-25 11:57
The only change that I'm aware of is that @trevormarshall has been recreating the workers on a semi-regular basis. Trevor, any news from the Concourse team that might move things towards a solution?

**Comment by wilkinsona** [comment] 2020-03-06 17:19
Our current strategy of recreating the workers periodically seems to be working. Any other improvements will require the involvement of the Concourse team and, perhaps, some changes in Concourse itself. I don't expect any changes in Boot's pipelines so I'm going to close this one for now. We can re-open it if it transpires that we do need to make some changes.

**Comment by dreis2211** [comment] 2020-03-06 17:20
It improved drastically, so totally agree. Thanks @wilkinsona

**Closed by wilkinsona** 2020-03-06 17:19 UTC
Labels: status: waiting-for-triage

**Comment by trevormarshall** [comment] 2020-03-06 17:31
We've been monitoring the cluster for some time before updating here. We have not needed to recreate the workers for 3 weeks now. 21 days ago we re-deployed the Concourse workers to a secondary AZ, on different hardware, with newer CPU and flash storage.
