### ISSUE TITLE
The spring.redis.database property does not take effect in ReactiveRedisTemplate

### ISSUE THREAD

**Issue by wangxing-git** [spring-projects/spring-boot#16651] opened 2019-04-25 10:00 UTC
### spring boot version
2.1.2.RELEASE
### pom.xml
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
</dependency>
```
### application.properties
```
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0
spring.redis.lettuce.pool.max-wait=-1ms
spring.redis.port=6379
spring.redis.host=****
spring.redis.password=****
spring.redis.database=8
```
But the database is always 0 when I use `ReactiveRedisTemplate`.
And when I use `RedisTemplate`, the database is normal.
Is it not supported when using reactive redis?

**Comment by wilkinsona** [comment] 2019-04-25 11:18
The different behaviour is due to `LettuceConnectionFactory` which is part of Spring Data Redis. I'm not sure if that's a bug or if it's working as designed. I have asked @mp911de to take a look.

**Comment by mp911de** [comment] 2019-04-25 11:35
I wasn't able to reproduce the behavior with a vanilla Spring Boot 2.1.2.RELEASE. Can you please provide some bits that reproduce the issue?

**Comment by wilkinsona** [comment] 2019-04-25 11:43
Thanks, @mp911de. It looks like my reading of the code was flawed. Sorry. Looking more closely, I can see the database being using in the reactive case in `doCreateConnectionProvider`.

@wangxing-git If you would like us to spend some more time investigating, can you please spend some time creating the sample that Mark has requested either as a zip attached to this issue or in a separate repository.

**Comment by mp911de** [comment] 2019-04-25 11:48
I was digging a bit more into this. Disabling connection sharing or using dedicated connections is required to reproduce (e.g. usage of blocking commands such as `BRPOP`) the issue which is from that perspective a bug.

I filed [DATAREDIS-973](https://jira.spring.io/browse/DATAREDIS-973) to fix the issue in Spring Data Redis. We can close this ticket and track further progress in Spring Data Redis.

**Comment by wangxing-git** [comment] 2019-04-25 12:01
@mp911de You are right

**Comment by wilkinsona** [comment] 2019-04-25 12:20
Thanks again, @mp911de.

**Closed by wilkinsona** 2019-04-25 12:20 UTC
Labels: status: feedback-provided, status: waiting-for-triage
