### ISSUE TITLE
Restricting change property values on @ConfigurationProperties

### ISSUE THREAD

**Issue by ljhade24** [spring-projects/spring-boot#12571] opened 2018-03-21 10:48 UTC
Is it possible to restrict changing `@ConfigurationProperties` bean's value?
here's the example below
```
@Component
public class Testcase {

  @Autowired
  TestProperty property;

  @PostConstruct
  public void testMethod {
    System.out.println(property.getStr());
    property.setStr("test");
    System.out.println(property.getStr());
  }

  @Data
  @Component
  @ConfigurationProperties("test")
  public class TestProperty {
    private String str;
  }
}
```

it results the first line '1234' as my application.properties I set and the second line displays 'test' and it has changed. The setter method shouldn't be called as developers know what there're doing but can I restrict it?

**Comment by snicoll** [comment] 2018-03-21 11:30
Duplicate of #8762

**Closed by snicoll** 2018-03-21 11:30 UTC
Labels: status: waiting-for-triage
