### ISSUE TITLE
Ensure that incubating Gradle API is not part of any of the Gradle plugin's public API

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-boot#11640] opened 2018-01-16 08:14 UTC
The problem can be observed when build info generation is enabled.

Sample build script to reproduce the warning:

```gradle
buildscript {
	repositories {
		mavenCentral()
		maven { url 'https://repo.spring.io/milestone/' }
	}
	dependencies {
		classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.0.M7'
	}
}

apply plugin: 'org.springframework.boot'

springBoot {
	buildInfo()
}
```

The warning itself:
```shell
$ ./gradlew projects --warning-mode=all
> Configure project : 
The property(Class) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the ObjectFactory.property(Class) method instead.
        at build_74a8d8t7twxo4kla2mf7jb5h1$_run_closure1.doCall(/home/vedran/dev/projects/gradle-sample/build.gradle:14)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
> Task :projects 

------------------------------------------------------------
Root project
------------------------------------------------------------

Root project 'gradle-sample'
No sub-projects

To see a list of the tasks of a project, run gradlew <project-path>:tasks
For example, try running gradlew :tasks


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

**Comment by wilkinsona** [comment] 2018-01-16 08:29
This looks like a regression of https://github.com/gradle/gradle/issues/3262. @vpavic, can you please raise this with the Gradle team? /cc @bmuschko

**Comment by vpavic** [comment] 2018-01-16 13:21
Looking at deprecation warning related issues in Gradle, especially gradle/gradle#3457 and gradle/gradle#3726 (which is a part of 4.5 RC1), I think the new behavior is intentional.

After all, I did have to include `--warning-mode=all` option to show the warning details. Without it, the output contains only a warning summary is printed:

```shell
$ ./gradlew projects 
> Task :projects 

------------------------------------------------------------
Root project
------------------------------------------------------------

Root project 'gradle-sample'
No sub-projects

To see a list of the tasks of a project, run gradlew <project-path>:tasks
For example, try running gradlew :tasks


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed

There are 1 deprecation warnings, which may break the build in Gradle 5.0. Please run with --warning-mode=all to see them.
```

**Comment by wilkinsona** [comment] 2018-01-16 13:43
Thanks, @vpavic. I think that's a fairly significant step backwards from https://github.com/gradle/gradle/issues/3262 but I guess we'll just have to live with it. While we continue to support Gradle 4.0, the alternative is a large amount of reflective code to call the new `ObjectFactory.property(Class)` method when it's available and I don't want to do that.

**Comment by oehme** [comment] 2018-01-16 15:16
You can always use `--warning-mode none` if you are not interested in Gradle 5.0 compatiblity.

**Comment by wilkinsona** [comment] 2018-01-16 18:14
@oehme Thanks for the suggestion, but that still puts the onus on the user to do something. IMO, they shouldn't have to do anything to avoid any sign of the warning as it isn't really aimed at them.

**Comment by oehme** [comment] 2018-01-16 21:03
Supporting this on the plugin side is still on the table, just much more complex to do correctly.

**Comment by wilkinsona** [comment] 2018-01-17 12:03
After some further consideration, I think we need to drop the use of `PropertyState`.

Since its introduction in 4.0 as an incubating feature it has been deprecated and `Property` was introduced as its replacement in 4.3. The latter is also incubating. Given the previous experience with the incubation of `PropertyState`, I think it would be foolhardy to move to `Property` as we may suffer the same problems again.

We should avoid using Gradle API that's marked as incubating in the signature of any of our public APIs.

**Closed** 2018-01-17 12:36 UTC
Labels: priority: high, type: enhancement
