### ISSUE TITLE
Can not Deploy Spring RESTful Jersey in glassfish 4.0

### ISSUE THREAD

**Issue by Khamphai** [spring-projects/spring-boot#13310] opened 2018-05-31 08:02 UTC
Error occurred during deployment: Exception while loading the app:

```
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration$$EnhancerBySpringCGLIB$$fd8318d2]: Constructor threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'resourceConfigCustomizer' defined in class path resource [org/springframework/boot/autoconfigure/jersey/JerseyAutoConfiguration$Jack .... msg.seeServerLog
```

```
public class JerseyConfig extends ResourceConfig {

    public JerseyConfig() {

        register(AuthenticationResource.class);
        register(CoreResource.class);
        register(TestingResource.class);

        //Auth Exception
        register(AccessDeniedExceptionMapper.class);
        register(AuthenticationExceptionMapper.class);
        register(AuthenticationTokenRefreshmentExceptionMapper.class);

        //API Exception Response
        register(CoreResponseExceptionMapper.class);

        //ObjectMapper Jacson
        register(ObjectMapperProvider.class);
    }

}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.1"
         xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         metadata-complete="true"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd">

    <display-name>myapigateway</display-name>

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>

    <servlet>
        <servlet-name>myapi</servlet-name>
        <servlet-class>com.sun.jersey.spi.spring.container.servlet.SpringServlet</servlet-class>
        <init-param>
            <param-name>com.sun.jersey.config.property.packages</param-name>
            <param-value>com.ldbmobile.corporate.common.config.JerseyConfig</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>myapi</servlet-name>
        <url-pattern>/api/*</url-pattern>
    </servlet-mapping>

</web-app>
```

**Comment by wilkinsona** [comment] 2018-05-31 08:16
Thanks for the report, but it's not clear to me why you think this is a problem with Spring Boot. It's hard to tell as you have only included part of the failure message. You haven't even told us the version of Spring Boot that you are using.

A typical Spring Boot application does not have a `web.xml` and does not declare a `ContextLoaderListener`. Please refer to the [documentation for creating a deployable war file] and the sample to which it links and update your application accordingly

If the suggestion does not help, please provide a small sample application that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2018-06-07 08:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2018-06-14 08:19
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-06-14 08:19 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
