### ISSUE TITLE
Integration with spring-session

### ISSUE THREAD

**Issue by jgogstad** [spring-projects/spring-boot#7141] opened 2016-10-11 11:03 UTC
Using [spring-session][spring-session] to implement persistent database sessions, one can no longer use the session configuration in the spring-boot [documentation][spring-boot-configuration], like `server.session.cookie.secure` or `server.session.cookie.http-only`.

Spring-boot configures `javax.servlet.SessionCookieConfig` through `org.springframework.boot.autoconfigure.web.ServerProperties.SessionConfiguringInitializer` and relies on the servlet container to use this configuration for cookies. For some reason, spring-session is configured [its own way][spring-session-configuration] and doesn't even consider reading any `SessionCookieConfig`.

Spring-boot should either provide a `org.springframework.session.web.http.CookieSerializer` that propagates configuration from `SessionCookieConfiguration`, or the problem should be fixed in spring-session.

Maybe we could get a maven artifact `spring-boot-starter-session` that configures this? Spring session seems to be configured differently from any other spring framework with Spring Boot ([documentation](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot.html#updating-dependencies))

[spring-session]: http://projects.spring.io/spring-session/
[spring-session-configuration]: http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/custom-cookie.html#custom-cookie-spring-configuration
[spring-boot-configuration]: http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

**Comment by wilkinsona** [comment] 2016-10-11 11:12
Before we decide what to do, @rwinch can you please comment on Spring Session's configuration approach and the possibility of it using `SessionCookieConfig`?

**Comment by wilkinsona** [comment] 2016-10-11 11:19
> Maybe we could get a maven artifact spring-boot-starter-session that configures this?

Boot's own starters doesn't actually contain any code. The code's in `spring-boot-autoconfigure`. The starters are just a short way of adding several dependencies to your app as one. We don't have one for Spring Session is there's only one module that you'd definitely want (`spring-session`). Whatever else you'd need then depends on which session repository you're using.

**Comment by jgogstad** [comment] 2016-10-11 11:34
Ah, I'm not familiar with the architecture around starters I'm afraid. Having `org.springframework.session:spring-session` and then the starter for your datastore is fine I guess.

Anyway, the real case for this issue is making the integration with `spring-session` more seamless. We either need to change the defaults of `org.springframework.session.web.http.DefaultCookieSerializer` or place a custom spring-boot implementation somewhere.

**Comment by rwinch** [comment] 2016-10-11 13:24
This looks like a duplicate of https://github.com/spring-projects/spring-session/issues/87 

While we would love this issue to be resolved, we have been busy with other higher priority issues. Contributions welcome :)

**Comment by snicoll** [comment] 2016-10-11 13:25
Duplicates spring-projects/spring-session#87

**Closed by snicoll** 2016-10-11 13:25 UTC
Labels: waiting-for-triage
