### ISSUE TITLE
MessageSourceAutoConfiguration fails to read messages.properties when running an executable jar with name starting with "spring-boot-"

### ISSUE THREAD

**Issue by britter** [spring-projects/spring-boot#4811] opened 2015-12-18 22:02 UTC
When MessageSourceAutoConfiguration looks for messages.properties it tries to load all classpath resources using [`MessageSourceAutoConfiguration$SkipPatternPathMatchingResourcePatternResolver.doFindAllClassPathResources(String)`](https://github.com/spring-projects/spring-boot/blob/877e6e034ce58cfa84a237579891a94e197c3b12/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/MessageSourceAutoConfiguration.java#L223). In my case I'm working on an application called [spring-boot-heroku-demo](https://github.com/britter/spring-boot-heroku-demo), so it will also filter the root classpath resource `URL [jar:file:/Users/bene/workspace/projects/spring-boot-heroku-demo/target/spring-boot-heroku-demo-0.0.1-SNAPSHOT.jar!/]` because file name returned by that resource is "spring-boot-heroku-demo-0.0.1-SNAPSHOT.jar!/" which starts with "spring-boot".
It works when running the application from an IDE for example, because in this case resources will be loaded from the file system and not from the jar, so a completely different code path is taken to find the messages.properties file.

Possible solutions:
* Document that "spring-boot-" is a reserved project prefix which must not be used.
* List all spring-boot projects with full name in the [`SKIPPED`](https://github.com/spring-projects/spring-boot/blob/877e6e034ce58cfa84a237579891a94e197c3b12/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/MessageSourceAutoConfiguration.java#L200-L208) array in `MessageSourceAutoConfiguration$SkipPatternPathMatchingResourcePatternResolver`
* Match against the full path of each resource being checked - spring boot project jars will always be included in the lib/ directory.
* None of the above - the described use case is unlikely to affect any other users.

I'm happy to contribute a patch. Please let me know which solution you'd like to use.

**Comment by britter** [comment] 2015-12-19 08:21
A possible workaround for this is to set [`build.finalName`](http://maven.apache.org/pom.html#BaseBuild_Element) in a maven based build to something not starting with "spring-boot-".

**Comment by snicoll** [comment] 2015-12-22 12:16
I am not sure, the current situation looks quite wrong to me. Here are my thoughts on your proposals:

1. Not an option (per the bug label added unless someone else disagrees)
2. Maybe
3. It doesn't change the fact you may have a library with that prefix that you include in your spring boot app. To me it fixes your particular use case but not the underlying problem.

I guess the wildcard scanning is the problem in the first place. Maybe we can change that or we could bring a configuration option that would whitelist a given name (`spring-boot-heroku-demo`). Yet, having to do that is very weird (you have to know about it!).

I am afraid we'll have to give it more thoughts as fixing this one does not look straightforward to me.

**Comment by britter** [comment] 2015-12-22 12:27
Option 2 might become a maintenance nightmare. One has to remember to extend the `SKIPPED` array when new spring-boot projects are added. So although I've suggested it, I don't think it is a good fix.

> It doesn't change the fact you may have a library with that prefix that you include in your spring boot app. To me it fixes your particular use case but not the underlying problem.

Good point, didn't thought about that.

> Maybe we can change that or we could bring a configuration option that would whitelist a given name (spring-boot-heroku-demo). Yet, having to do that is very weird (you have to know about it!).

Yes, and the list might become long if you happen to use several project with the spring-boot prefix (or any other prefix listed in the `SKIPPED` array).

> I am afraid we'll have to give it more thoughts as fixing this one does not look straightforward to me.

Fine by me. The workaround I described above, works for me. Thank you for looking into this on short notice.

**Comment by philwebb** [comment] 2015-12-23 19:15
My vote would be a variation on 2) and switch `SKIPPED` to a set of regex patterns that we can tighten up. The reason that these were added in the first place was as a performance optimization, as long as for production apps we skip common library jars, we shouldn't see any performance regression.

**Comment by snicoll** [comment] 2015-12-24 06:47
> The reason that these were added in the first place was as a performance optimization

Maybe we could try to fix that instead (moving the location or how it is discovered).

**Comment by philwebb** [comment] 2016-01-21 16:22
See #4930

**Comment by philwebb** [comment] 2016-01-21 23:16
We've decided to change the `message.properties` detection logic removing the need entirely for the custom pattern resolver. Fixed in e520c47c4f8a80b491849679e0deae3509f02805

**Closed by philwebb** 2016-01-21 23:16 UTC
Labels: bug

**Comment by britter** [comment] 2016-01-22 07:39
Nice, thanks!
