### ISSUE TITLE
Kafka Producer batch-size config property wrongly documented as "number of messages" rather than "bytes"

### ISSUE THREAD

**Issue by lorenzo-nutmeg** [spring-projects/spring-boot#13127] opened 2018-05-09 16:45 UTC
# Documentation Issue

In _Appendix A: Common application properties_ (`appendix-application-properties.adoc`)
Section: _Apache Kafka properties_

`spring.kafka.producer.batch-size` property is documented as "Number of **records** to batch before sending"

But it maps to the `batch.size` Producer configuration properties. 
Kafka documentation says it "...controls the default batch size in **bytes**" 
(see https://kafka.apache.org/documentation/#producerconfigs)

**Comment by wilkinsona** [comment] 2018-05-09 18:10
Duplicate of #13128.

**Closed by wilkinsona** 2018-05-09 18:10 UTC
Labels: status: waiting-for-triage
