### ISSUE TITLE
Management health group does not inherit show-details property

### ISSUE THREAD

**Issue by fonimus** [spring-projects/spring-boot#22012] opened 2020-06-18 10:11 UTC
Hello,

I am using health group feature and I noticed that I have to specify show-details for each group.
In my understanding (doc : https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/reference/htmlsingle/#production-ready-health-groups) it should use the `management.endpoint.health.show-details` as default value, but it is not.

````yml
management:
  endpoint:
    health:
      show-details: always
      group:
        ping-only:
          #show-details: always
          include: ping
        comp1-only:
          #show-details: always
          include: comp1
        comp2-only:
          #show-details: always
          include: comp2
        without-components:
          #show-details: always
          include: '*'
          exclude: 'comp1,comp2'
````

with previous configuration I get :

````json
http://localhost:8080/actuator/health/without-components

{"status":"UP"}
````

If I uncomment lines I get :

````json
http://localhost:8080/actuator/health/without-components

{"status":"UP","components":{"diskSpace":{"status":"UP","details":{"total":250685575168,"free":54778855424,"threshold":10485760,"exists":true}},"ping":{"status":"UP"}}}
````

Note: I am using 2.3.1.RELEASE version

**Comment by philwebb** [comment] 2020-06-18 21:52
Thanks for the bug report. I think the problem is that we set a default value in `HealthProperties.showDetails` and for groups it should be null.

**Comment by polarbear567** [comment] 2020-06-19 03:10
Hi, @philwebb 
I can take this issue.

**Comment by bclozel** [comment] 2020-06-19 09:43
Closing in favor of #22022

**Closed by bclozel** 2020-06-19 09:43 UTC
Labels: type: bug
