### ISSUE TITLE
Devtools session configuration conflict with Spring Session

### ISSUE THREAD

**Issue by rakpan** [spring-projects/spring-boot#7628] opened 2016-12-12 19:54 UTC
When Spring Boot devtools is available on the classpath, it seems to be setting the server sessions to be persistent. 

For undertow, if the sessions are persistent, below code exists in  `UndertowEmbeddedServletContainerFactory`

```
		if (isPersistSession()) {
			File dir = getValidSessionStoreDir();
			deployment.setSessionPersistenceManager(new FileSessionPersistence(dir));
		}
```

Now, this seems to be OK without Spring Session. But, when I have Spring session with `@EnableJdbcHttpSession` on my code. The above code results in an exception, especially when I dont have any session directories configured.

So, the default value of `true` for `server.session.persistent` is probably not needed in devtools if Spring Session is available on the classpath.

**Comment by wilkinsona** [comment] 2016-12-13 11:44
> The above code results in an exception, especially when I dont have any session directories configured.

What's the exception that you're seeing? Can you please provide a small sample the reproduces it?

**Comment by rakpan** [comment] 2016-12-13 20:49
Below is the stack trace. I will create a sample github project to demo it.

```
java.io.EOFException: null
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at java.util.HashMap.readObject(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at java.util.HashMap.readObject(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at org.springframework.boot.context.embedded.undertow.FileSessionPersistence.readSession(FileSessionPersistence.java:123)
	at org.springframework.boot.context.embedded.undertow.FileSessionPersistence.load(FileSessionPersistence.java:107)
	at org.springframework.boot.context.embedded.undertow.FileSessionPersistence.load(FileSessionPersistence.java:98)
	at org.springframework.boot.context.embedded.undertow.FileSessionPersistence.loadSessionAttributes(FileSessionPersistence.java:85)
	at io.undertow.servlet.handlers.SessionRestoringHandler.start(SessionRestoringHandler.java:74)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:507)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.createUndertowServer(UndertowEmbeddedServletContainer.java:133)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:119)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at com.tb.ao.ArchOnlineApplication.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

```

**Comment by rakpan** [comment] 2016-12-14 18:47
It doesnt seem to be happening in a standalone project. May be I'm missing something. Will research further.

**Comment by spring-issuemaster** [comment] 2016-12-21 19:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2016-12-28 19:14
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2016-12-28 19:14 UTC
Labels: waiting-for-triage
