### ISSUE TITLE
AutoConfiguration support for Data Mongo ReactiveGridFsTemplate

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-boot#16393] opened 2019-03-31 12:23 UTC
The latest Spring Data Mongo has brought Reactive support for GridFs, but Spring Boot 2.2.0.M1
is lack of an `AutoConfiguration` class to activate it, I have to configure it manually at the moment.

https://github.com/hantsy/spring-reactive-sample/blob/master/boot-data-mongo-gridfs/src/main/java/com/example/demo/DemoApplication.java#L35-L43

**Comment by ayudovin** [comment] 2019-04-04 08:15
@wilkinsona, I would like to work on it. Please let me know if I can start working on it?

**Comment by philwebb** [comment] 2019-04-04 17:13
@ayudovin Much appreciated. The issue isn't assigned and it doesn't look like it should be too involved so please go head.

**Comment by mbhave** [comment] 2019-04-10 20:44
Closing in favor of PR #16467.

**Closed by mbhave** 2019-04-10 20:44 UTC
Labels: type: enhancement
