### ISSUE TITLE
Converter and Formatter interfaces cannot be implemented together

### ISSUE THREAD

**Issue by NielsNet** [spring-projects/spring-boot#20031] opened 2020-02-04 09:16 UTC
Up to Spring Boot 2.1.x it was possible to have a class that implements both `org.springframework.core.convert.converter.Converter` and `org.springframework.format.Formatter`.  
However, since 2.2.x it is not possible anymore.  
In my project a Bean (`@JsonComponent`) was implementing both interfaces and with a change from 2.1.x to 2.2.x Spring started complaining that there was no Converter registered to convert my Request Parameters from `String` to the given class.  
As soon as I remoe the `Converter` interface the converter is used again.

Ideally Formatter and Converter interface should be compatible again. 
If not possible a warning in the javadoc of both interfaces and in the Spring Docs would be usefull.

**Comment by bclozel** [comment] 2020-02-04 09:52
From the description of this issue, it's not clear what is causing the regression you're seeing here, nor whether it's not possible to implement both interfaces or if it's an infrastructure setup issue.

Could you provide a sample application that demonstrates the issue? Something really basic that works with 2.1.x and fails with 2.2.x. Thanks!

**Comment by spring-issuemaster** [comment] 2020-02-11 09:55
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-02-18 09:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-02-18 09:55 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
