### ISSUE TITLE
Spring Boot Actuator: setting all endpoints as sensitive makes all accessible

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-boot#4368] opened 2015-11-02 15:57 UTC
From original report: https://jira.spring.io/browse/SEC-3141

QUOTE:

**Environment:** Spring Boot 1.3.0.M5 with embedded Tomcat

I've set up a Spring Boot project and added the Actuator dependency, so that I can make use of the monitoring functionality.

Per default, all endpoints except 2 (health and info) are sensitive (http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints). The sensitive ones require HTTP basic authentication per default.

I would like all endpoints to be considered sensitive. To do this, I set the following 2 properties in my application.properties:

```
endpoints.health.sensitive=true
endpoints.info.sensitive=true
```

This makes those endpoints, which are insensitive per default, sensitive.  I would expect all management endpoint requests to now require HTTP basic authentication. Unfortunately, now NONE of them require authentication.

Strangely, when I make only 1 of the 2 insensitive-per-default endpoints sensitive, everything works as expected. For example, when I only explicitly configure `endpoints.health.sensitive=true`, then the health endpoint requires authentication, but the info endpoint is still freely accessible.

**Comment by rwinch** [comment] 2015-11-02 16:02
When I try this, it seems to be working as expected for me. If you provide your own Spring Security configuration then that takes precedence over Spring Boot's security configuration. Specifically this does not appear to be true for me:

> Strangely, when I make only 1 of the 2 insensitive-per-default endpoints sensitive, everything works as expected. For example, when I only explicitly configure endpoints.health.sensitive=true, then the health endpoint requires authentication, but the info endpoint is still freely accessible.

I put together a sample at https://github.com/rwinch/spring-security-sample/tree/sec-3141 that demonstrates if you provide your own Spring Security configuration both endpoints are open (if that is what the overridden configuration provides).

Perhaps the original reporter can provide a sample to illustrate the issue.

**Comment by snicoll** [comment] 2015-11-02 17:02
I am confused. Are you saying you can't reproduce what the original reporter is raising? Using quotes in your original description would be nice :)

**Comment by rwinch** [comment] 2015-11-02 18:09
>  Using quotes in your original description would be nice :)

I'm not sure I follow. The issue description contains exactly what the original reporter submitted in JIRA, so it seemed a bit unnecessary to quote it. You can easily see what they reported by following the link next to "Original report" in the description.

> Using quotes in your original description would be nice :)

My [comment](https://github.com/spring-projects/spring-boot/issues/4368#issuecomment-153062502) was my response to the original reporter that I was not able to reproduce their claim (which I quoted):

>> Strangely, when I make only 1 of the 2 insensitive-per-default endpoints sensitive, everything works as expected. For example, when I only explicitly configure endpoints.health.sensitive=true, then the health endpoint requires authentication, but the info endpoint is still freely accessible.

Does this clarify?

**Comment by dsyer** [comment] 2015-11-03 09:21
Seems like it's just pilot error then? The user that reported in Security JIRA had a custom configuration that opened up all the endpoints. So we can close this?

**Comment by bencody** [comment] 2015-11-03 10:35
I produced a minimal project with which this issue can be reproduced:

https://github.com/bencody/sec3141

Thanks for looking into it.

**Comment by rwinch** [comment] 2015-11-03 18:01
Thanks for the project @bencody I can confirm this is a bug. I'm not sure why I was not able to reproduce the issue you described previously as my sample project behaves as you described now. Perhaps this was just an error on my part.

It appears to be a problem with the refactoring that took place in 4c8c3768294a7f which will mark any request as permitAll if there are no sensitive as apposed to marking no request as permitAll. I have submitted a PR https://github.com/spring-projects/spring-boot/pull/4383 to resolve it.

**Comment by snicoll** [comment] 2015-11-04 07:51
thanks for the PR Rob!

**Comment by philwebb** [comment] 2015-11-09 23:33
I think commit 1e464da2480568014a87dd0bac6febe63a76c889 might also be relevant

**Closed** 2015-11-10 08:13 UTC
Labels: blocker
