### ISSUE TITLE
CassandraAutoconfiguration leads to ignored parameters in db-config.conf

### ISSUE THREAD

**Issue by nilsvillwock** [spring-projects/spring-boot#31025] opened 2022-05-13 11:22 UTC
We are using the cassandra driver specific configuration file `db-config.conf` via the property:

```yaml
spring:
  data:
    cassandra:
      config: file:/db-config.conf
```

The problem now is that even when I do not define further spring-boot `CassandraProperties` in the yaml, there are default values already set and these properties are ignored in the `db-config.conf`. file. The reason seem to be, because the `db-config.conf` properties are loaded as fallback after the default spring boot `CassandraProperties`. Spring Boot `CassandraProperties` should win, but only if they are actively set.

The following Cassandra properties always initialized and so always ignored in `db-config.conf`

![initCassandraProperties](https://user-images.githubusercontent.com/46843697/168272455-9e4a00d6-6809-4598-a65f-9cff202fda0d.png)

**Comment by snicoll** [comment] 2022-05-16 12:16
@philwebb I can see you've flagged this as a bug but the current behavior is the expected behavior, see https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#data.nosql.cassandra.connecting. Perhaps the documentation should be more explicit that a default value counts as a value being present.

@nilsvillwock the purpose of the config property is to let define properties that the Spring Boot namespace does not support.

**Comment by nilsvillwock** [comment] 2022-05-16 13:25
OK, please adjust the documentation from:

If a property is both present in spring.data.cassandra.* and the configuration file, the value in spring.data.cassandra.* takes precedence.

to:

If a property is both present **(even it is only by default)** in spring.data.cassandra.* and the configuration file, the value in spring.data.cassandra.* takes precedence.

**Comment by snicoll** [comment] 2022-05-18 15:50
We've discussed this at the team meeting and we come to realize that it was supposed to work as expected (see #24065). The problem is that some properties were overlooked, typically the ones that have a primitive type (and a default value of 0).

@nilsvillwock it would be good to list the properties that you tried to define in `db-config.conf` that did not work.

**Comment by nilsvillwock** [comment] 2022-05-19 06:45
@snicoll 
The properties which are ignored in the db-config file are the ones you can see at the screenshot  in my initial post

**Comment by ittays** [comment] 2022-06-02 09:59
Can you please look into my PR? 
Eventually, to simplify the port configuration, I preferred not to defer the `contact-points` config, and not to cross-use a host from one config layer and a port from another.

**Comment by snicoll** [comment] 2022-06-02 11:54
@ittays there's no need to ask us to do that. The whole team already received a notification when you created the pR.

**Comment by philwebb** [comment] 2022-06-09 18:43
Closing in favor of PR #31238. Thanks @ittays!

**Closed by philwebb** 2022-06-09 18:43 UTC
Labels: type: bug
