### ISSUE TITLE
ResourceHttpRequestHandler  404 when encounter no english character filename , springbot 2.6.6

### ISSUE THREAD

**Issue by xiaoqiaotq** [spring-projects/spring-boot#30657] opened 2022-04-14 07:02 UTC
springbot 2.6.6
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```
### config 
![Dingtalk_20220414143633.jpg](https://s2.loli.net/2022/04/14/vVOEbL81Q4ztTAq.jpg)

### url path encode twice ,lead to fileResouce not found ,just need one
```
// test curl
curl --location --request GET 'localhost:9898/r/测试832878.tmp'

// see below pic
// first encode
测试832878.tmp   -->  %E6%B5%8B%E8%AF%95832878.tmp   
// second encode bug ??
%E6%B5%8B%E8%AF%95832878.tmp --> %25E6%25B5%258B%25E8%25AF%2595832878.tmp
```
![Dingtalk_20220414144431.jpg](https://s2.loli.net/2022/04/14/QSBJYbAs5mKnt9u.jpg)

**Comment by pruidong** [comment] 2022-04-14 14:22
Can't tell from the picture, I feel you should provide a minimal example.

**Comment by bclozel** [comment] 2022-04-14 14:32
Closing as a duplicate of spring-projects/spring-framework#27791

**Closed by bclozel** 2022-04-14 14:32 UTC
Labels: status: waiting-for-triage
