### ISSUE TITLE
Inegration tests: application.yml is not loaded

### ISSUE THREAD

**Issue by mdeknowis** [spring-projects/spring-boot#11973] opened 2018-02-09 08:48 UTC
We upgraded from spring boot 2.0.0.M4 to 2.0.0.RC1

We experience, that our integration tests are not longer working as before. The evaluation of `@Value` does not load the data from our `application.yml`

We created a minimum project to reproduce this issue:
* [samples.zip](https://github.com/spring-projects/spring-boot/files/1710274/samples.zip)

While using M4 the out is as expected:

```txt
value=en_US
myConfig.value=en_US
```

the output using RC1 is:

```txt
value=${spring.mvc.locale}
myConfig.value=${spring.mvc.locale}
```

It looks like, that the `ResourceLoader` does not find the `application.yml`, even it is in the classpath in RC1:

```txt
TRACE 32720 --- [           main] o.s.b.c.c.ConfigFileApplicationListener  : Skipped missing config 'classpath:/application.yml'
```

But in M4 there was this DEBUGlog entry:

```txt
DEBUG 16860 --- [           main] o.s.b.c.c.ConfigFileApplicationListener  : Loaded config file 'file:/..../target/classes/application.yml' (classpath:/application.yml)
```

The basic project structue is:

```txt
.
+--- pom.xml
+--- run-mvn.bat
+--- src
|   +--- main
|   |   +--- filtered
|   |   |   +--- application.yml
|   |   +--- java
|   |   |   +--- spring
|   |   |   |   +--- test
|   |   |   |   |   +--- TestApplication.java
|   |   +--- resources
|   |   |   +--- .gitignore
|   +--- test
|   |   +--- java
|   |   |   +--- spring
|   |   |   |   +--- test
|   |   |   |   |   +--- simple
|   |   |   |   |   |   +--- SimpleIT.java
|   |   +--- resources
|   |   |   +--- logback-test.xml
```

That is working fine on M4, but fails on RC1.

But if we add `application.yml` to the project root like this:

```txt
.
+--- application.yml  <--- ADDED
+--- pom.xml
+--- run-mvn.bat
+--- src
|   +--- main
|   |   +--- filtered
|   |   |   +--- application.yml
|   |   +--- java
|   |   |   +--- spring
|   |   |   |   +--- test
|   |   |   |   |   +--- TestApplication.java
|   |   +--- resources
|   |   |   +--- .gitignore
|   +--- test
|   |   +--- java
|   |   |   +--- spring
|   |   |   |   +--- test
|   |   |   |   |   +--- simple
|   |   |   |   |   |   +--- SimpleIT.java
|   |   +--- resources
|   |   |   +--- logback-test.xml
```

But so far it looks like, it's only related with integration tests somehow. So we are not able to upgrade these to the most recent RC1 version.

**Comment by snicoll** [comment] 2018-02-09 09:05
@mdeknowis that's quite a complex arrangement you have there and nothing that indicates a regression in Spring Boot. The "not working sample" works for me. If I run the IT in my IDE, it passes.

This is really about making sure that `application.yml` is on the classpath (if you're using an IDE, making sure it is integrated with the build and copy the yml file so that it's included in the classpath). It looks a local setup issue since adding the yaml file at the root is enough (the working directory of the test is probably the module directory). 

Given that the "not working sample" works out of the box for me, I am going to close this issue.

**Closed by snicoll** 2018-02-09 09:05 UTC
Labels: status: waiting-for-triage

**Comment by snicoll** [comment] 2018-02-09 10:35
Actually this is a duplicate of the other issue you've created #11974 (I didn't use Maven to run the IT but the symptom here is the same)
